### ISSUE TITLE
Jenkins ssh drop at beginning of the job

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1022]
The issue shows no logs on AWS, meanwhile on Jenkins build log there seems to be not even single operation done before ssh drops.

## Expected Behavior
Result reported, logs available.

## Current Behavior
Failure before executing any part of autotest and no artifacts on AWS.
```
Started by upstream project "autotest-per-patch" build number 48462
originally caused by:
 Started by user sys_sgci
[EnvInject] - Loading node environment variables.
FATAL: java.io.IOException: Unexpected termination of the channel
java.io.EOFException
	at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2675)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3150)
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:859)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:355)
	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:48)
	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:63)
Caused: java.io.IOException: Unexpected termination of the channel
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:77)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to fedora_vm_9
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
		at hudson.remoting.Request.call(Request.java:192)
		at hudson.remoting.Channel.call(Channel.java:907)
		at hudson.FilePath.act(FilePath.java:1081)
		at org.jenkinsci.plugins.envinject.service.EnvironmentVariablesNodeLoader.gatherEnvVarsForNode(EnvironmentVariablesNodeLoader.java:64)
		at org.jenkinsci.plugins.envinject.EnvInjectListener.loadEnvironmentVariablesNode(EnvInjectListener.java:80)
		at org.jenkinsci.plugins.envinject.EnvInjectListener.setUpEnvironment(EnvInjectListener.java:44)
		at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:542)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:462)
		at hudson.model.Run.execute(Run.java:1724)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused: hudson.remoting.RequestAbortedException
	at hudson.remoting.Request.abort(Request.java:329)
	at hudson.remoting.Channel.terminate(Channel.java:992)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:96)
ERROR: Build step failed with exception
java.lang.NullPointerException
Build step 'Execute Scripts' marked build as failure
ERROR: Step ‘Archive the artifacts’ failed: no workspace for NVMe_tests/nvme_autotest #41537
Tests finished with errors. Please check the logs for more info.
Execution node will be rebooted.
Triggering a new build of reset-job
Finished: FAILURE
```

## Context (Environment including OS version, SPDK version, etc.)
https://dqtibwqq6s6ux.cloudfront.net/public_build/autotest-per-patch_48462.html

**Comment by Seth5141** [comment]
Possible duplicate of #1007. I don't know how granular we want to be about tracking these Jenkins network connection errors.

**Comment by jimharris** [comment]
I think we can close this one.  I'm thinking we track all of them as one issue, and let someone more familiar with Jenkins look at the reports on #1007 and create separate issues if warranted.

**Comment by tomzawadzki** [comment]
Duplicate of #1007

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @Comphix. log: Not Found
