### ISSUE TITLE
AddressSanitizer: stack-buffer-overflow on Fedora30

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1083]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

Tests should pass
## Current Behavior

Test fail on:
```
Suite: nvme_pcie
  Test: prp_list_append .../home/sys_sgci/spdk/lib/nvme/nvme_pcie.c:1739:nvme_pcie_prp_list_append: *ERROR*: virt_addr 0x100001 not dword aligned
/home/sys_sgci/spdk/lib/nvme/nvme_pcie.c:1768:nvme_pcie_prp_list_append: *ERROR*: PRP 2 not page aligned (0x900800)
/home/sys_sgci/spdk/lib/nvme/nvme_pcie.c:1758:nvme_pcie_prp_list_append: *ERROR*: vtophys(0x100000) failed
/home/sys_sgci/spdk/lib/nvme/nvme_pcie.c:1752:nvme_pcie_prp_list_append: *ERROR*: out of PRP entries
/home/sys_sgci/spdk/lib/nvme/nvme_pcie.c:1752:nvme_pcie_prp_list_append: *ERROR*: out of PRP entries
passed
  Test: nvme_pcie_hotplug_monitor ...=================================================================
==117118==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffefc9049c0 at pc 0x000000405082 bp 0x7ffefc902860 sp 0x7ffefc902850
READ of size 8 at 0x7ffefc9049c0 thread T0
    #0 0x405081 in _nvme_pcie_hotplug_monitor /home/sys_sgci/spdk/lib/nvme/nvme_pcie.c:318
    #1 0x40a4fe in test_nvme_pcie_hotplug_monitor /home/sys_sgci/spdk/test/unit/lib/nvme/nvme_pcie.c/nvme_pcie_ut.c:948
    #2 0x7f204226bf9a  (/lib64/libcunit.so.1+0x4f9a)
    #3 0x7f204226c230  (/lib64/libcunit.so.1+0x5230)
    #4 0x7f204226c646 in CU_run_all_tests (/lib64/libcunit.so.1+0x5646)
    #5 0x40ab32 in main /home/sys_sgci/spdk/test/unit/lib/nvme/nvme_pcie.c/nvme_pcie_ut.c:1003
    #6 0x7f20413f5f42 in __libc_start_main (/lib64/libc.so.6+0x23f42)
    #7 0x402cad in _start (/home/sys_sgci/spdk/test/unit/lib/nvme/nvme_pcie.c/nvme_pcie_ut+0x402cad)

Address 0x7ffefc9049c0 is located in stack of thread T0 at offset 7280 in frame
    #0 0x4098a2 in test_nvme_pcie_hotplug_monitor /home/sys_sgci/spdk/test/unit/lib/nvme/nvme_pcie.c/nvme_pcie_ut.c:883

  This frame has 4 object(s):
    [32, 36) 'attr' (line 886)
    [48, 128) 'dummy' (line 885)
    [160, 736) 'test_nvme_probe_ctx' (line 887)
    [864, 7200) 'ctrlr' (line 884) <== Memory access at offset 7280 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow /home/sys_sgci/spdk/lib/nvme/nvme_pcie.c:318 in _nvme_pcie_hotplug_monitor
Shadow bytes around the buggy address:
  0x10005f9188e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005f9188f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005f918900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005f918910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005f918920: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f3 f3
=>0x10005f918930: f3 f3 f3 f3 f3 f3 f3 f3[f3]f3 f3 f3 f3 f3 f3 f3
  0x10005f918940: f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 f3 00 00
  0x10005f918950: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005f918960: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005f918970: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10005f918980: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==117118==ABORTING
  11:20:57      # trap - ERR
  11:20:57      # print_backtrace
  11:20:57      # [[ ehxBE =~ e ]]
  11:20:57      # xtrace_disable
  11:20:57      # PREV_BASH_OPTS=ehxBE
  11:20:57      # set +x
========== Backtrace start: ==========

in /home/sys_sgci/spdk/test/common/autotest_common.sh:574 -> run_test()
     ...
   569          shift
   570          echo "************************************"
   571          echo "START TEST $test_type $*"
   572          echo "************************************"
   573          xtrace_restore
=> 574          time "$@"
   575          xtrace_disable
   576          echo "************************************"
   577          echo "END TEST $test_type $*"
   578          echo "************************************"
   579          xtrace_restore
     ...
in /home/sys_sgci/spdk/autotest.sh:148 -> main()
     ...
   143  # Unit Tests
   144  #####################
   145
   146  if [ $SPDK_TEST_UNITTEST -eq 1 ]; then
   147          timing_enter unittest
=> 148          run_test suite ./test/unit/unittest.sh
   149          report_test_completion "unittest"
   150          timing_exit unittest
   151  fi
   152
   153
     ...

========== Backtrace end ==========
  11:20:57      # xtrace_enable
  11:20:57      # return 0

real    0m28.557s
user    0m26.364s
sys     0m2.084s
 11:20:57       # process_core
 11:20:57       # ret=0
 11:20:57       # IFS=
 11:20:57       # read -r -d '' core
  11:20:57      # find . -type f '(' -name 'core\.?[0-9]*' -o -name '*.core' ')' -print0
 11:20:57       # return 0
 11:20:57       # autotest_cleanup
 11:20:57       # /home/sys_sgci/spdk/scripts/setup.sh reset
0000:00:09.0 (8086 5845): uio_pci_generic -> nvme
0000:00:0c.0 (8086 5845): uio_pci_generic -> nvme
0000:00:0d.0 (8086 5845): uio_pci_generic -> nvme
0000:00:0e.0 (1d1d 1f1f): Skipping un-whitelisted NVMe controller
0000:00:0b.0 (1af4 1001): uio_pci_generic -> virtio-pci
0000:00:0a.0 (1af4 1004): uio_pci_generic -> virtio-pci
 11:20:58       # /home/sys_sgci/spdk/scripts/setup.sh cleanup
ls: cannot access '/dev/shm/*': No such file or directory
Clean
  11:20:58      # uname -s
 11:20:58       # '[' Linux = Linux ']'
 11:20:58       # grep -q '#define SPDK_CONFIG_IGB_UIO_DRIVER 1' /home/sys_sgci/spdk/include/spdk/config.h
 11:20:58       # modprobe -r uio_pci_generic
 11:20:58       # rm -rf /var/tmp/asan_suppression_file
 11:20:58       # exit 1
```
## Steps to Reproduce

1. Run unittest_autotest

## Context (Environment including OS version, SPDK version, etc.)

OS: Fedora30
Kernel: 5.3.12-200.fc30.x86_64
clang version 8.0.0 (Fedora 8.0.0-3.fc30)
commit: 3ad192e3b5a3c4345d40a2e9ff4d8aedaf332064
gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)

**Comment by yidong0635** [comment]
Please check this after ben's simplified patches,and rebase from master. Sorry for inconvenience.

**Comment by yidong0635** [comment]
still can be reproduced, will check this.

**Comment by wawryk** [comment]
Check today on commit: 5c5b167a0d383849057f8f7881cc8d4ca08973cd 
The same situation

**Comment by optimistyzy** [comment]
@glodfish-zg Can you see this issue?

**Comment by yidong0635** [comment]
@optimistyzy  @glodfish-zg @wawryk :
I think this issue is a wrong report , the analyzer of  unittest on fedora30,  can't use an normal way to fix it.
steps:
    pctrlr =  SPDK_CONTAINEROF(ctrlr, struct nvme_pcie_ctrlr, ctrlr);
    pctrlr->devhandle accessing pctrlr , but it reports ctrlr "Memory access at offset 7280 overflows this variable"

**Comment by yidong0635** [comment]
I post a patch here: https://review.gerrithub.io/c/spdk/spdk/+/476420
Just for RFC. I don't have a better method to cover this. If you have ,please paste here.
Thanks!

**Comment by wawryk** [comment]
It works
Thanks @yidong0635

**Comment by glodfish-zg** [comment]
@yidong0635  I add +1 to your patch. You can close this issue when the patch is merged.

**Comment by yidong0635** [comment]
@glodfish-zg thanks, let @wawryk to close this issue.
