### ISSUE TITLE
nvmf_tgt hangs after an attempt to create subsystem with invalid model|serial number is made

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1192]
SPDK: v20.01-rc1 (HEAD->e97ad60f)
OS: Debian 10 (Kernel version: 4.19.67, 4.19.0-6-amd64 build)

Config:
```
CONFIG_PREFIX="/usr/local"
CONFIG_ARCH=native
CONFIG_CROSS_PREFIX=
CONFIG_DEBUG=n
CONFIG_LOG_BACKTRACE=n
CONFIG_WERROR=n
CONFIG_LTO=n
CONFIG_PGO_CAPTURE=n
CONFIG_PGO_USE=n
CONFIG_COVERAGE=n
CONFIG_ASAN=n
CONFIG_UBSAN=n
CONFIG_TSAN=n
CONFIG_TESTS=y
CONFIG_ENV=
CONFIG_DPDK_DIR=
CONFIG_FIO_PLUGIN=n
CONFIG_FIO_SOURCE_DIR=/usr/src/fio
CONFIG_RDMA=n
CONFIG_RDMA_SEND_WITH_INVAL=n
CONFIG_NVME_CUSE=n
CONFIG_FC=n
CONFIG_FC_PATH=
CONFIG_RBD=n
CONFIG_VHOST=y
CONFIG_VHOST_INTERNAL_LIB=n
CONFIG_VIRTIO=y
CONFIG_PMDK=n
CONFIG_PMDK_DIR=
CONFIG_REDUCE=n
CONFIG_VPP=n
CONFIG_VPP_DIR=
CONFIG_ISCSI_INITIATOR=n
CONFIG_CRYPTO=n
CONFIG_SHARED=n
CONFIG_VTUNE=n
CONFIG_VTUNE_DIR=
CONFIG_IGB_UIO_DRIVER=n
CONFIG_IPSEC_MB=n
CONFIG_OCF=n
CONFIG_OCF_PATH=
CONFIG_CUSTOMOCF=n
CONFIG_ISAL=y
CONFIG_URING=n
CONFIG_URING_PATH=
CONFIG_FUSE=n
```

After an attempt to create a subsystem with an invalid serial number (or model) is made, the nvmf_tgt doesn't gracefully handle TERM anymore:

Include ascii chat that's not supported by the nvme spec to trigger the error:
```
./scripts/rpc.py nvmf_create_subsystem -d "$(echo -e "\x1f")"  nqn.2016-06.io.spdk:cnode$RANDOM
nvmf_rpc.c: 411:spdk_rpc_nvmf_create_subsystem: *ERROR*: Subsystem nqn.2016-06.io.spdk:cnode24267: invalid model number ''
request:
{
  "nqn": "nqn.2016-06.io.spdk:cnode24267", 
  "serial_number": "00000000000000000000",
  "model_number": "\u001f",
  "method": "nvmf_create_subsystem",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -32602,
  "message": "Invalid parameters"
}
```
 Regardless of the failure above, the subsystem is still created?
```
root@debianMB[SPDK]:~/spdk_repo/spdk# ./scripts/rpc.py nvmf_get_subsystems
[
  {
    "nqn": "nqn.2014-08.org.nvmexpress.discovery",
    "subtype": "Discovery",
    "listen_addresses": [],
    "allow_any_host": true,
    "hosts": []
  },
  {
    "nqn": "nqn.2016-06.io.spdk:cnode24267", 
    "subtype": "NVMe",
    "listen_addresses": [],
    "allow_any_host": false,
    "hosts": [],
    "serial_number": "00000000000000000000",
    "model_number": "SPDK bdev Controller",
    "namespaces": []
  }
]
```
Ok, let's try to kill it:
```
root@debianMB[SPDK]:~/spdk_repo/spdk# kill %
root@debianMB[SPDK]:~/spdk_repo/spdk#
root@debianMB[SPDK]:~/spdk_repo/spdk# [[ -e /proc/$!/ ]]; echo $?
0
root@debianMB[SPDK]:~/spdk_repo/spdk# grep -q spdk /proc/net/unix; echo $?
0
root@debianMB[SPDK]:~/spdk_repo/spdk# kill %
# It just doesn't want to go away...
root@debianMB[SPDK]:~/spdk_repo/spdk# [[ -e /proc/$!/ ]]; echo $?
0
```
Note that process didn't die, but the spdk socket was closed:
```
# ... but the /var/tmp/spdk.sock actually gets closed
root@debianMB[SPDK]:~/spdk_repo/spdk# grep -q spdk /proc/net/unix; echo $?
1
root@debianMB[SPDK]:~/spdk_repo/spdk# ./scripts/rpc.py nvmf_get_subsystems
Traceback (most recent call last):
  File "/root/spdk_repo/spdk/scripts/rpc/client.py", line 51, in __init__
    self.sock.connect((addr, port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/rpc.py", line 2340, in <module>
    args.client = rpc.client.JSONRPCClient(args.server_addr, args.port, args.timeout, log_level=getattr(logging, args.verbose.upper()))
  File "/root/spdk_repo/spdk/scripts/rpc/client.py", line 56, in __init__
    "Error details: %s" % (addr, ex))
rpc.client.JSONRPCException: Error while connecting to /var/tmp/spdk.sock
Error details: [Errno -2] Name or service not known
root@debianMB[SPDK]:~/spdk_repo/spdk# jobs
[1]+  Running                 ./app/nvmf_tgt/nvmf_tgt &
# one last try...
root@debianMB[SPDK]:~/spdk_repo/spdk# kill %
# ... nope, need to bash it with a stick
root@debianMB[SPDK]:~/spdk_repo/spdk# kill -9 %
root@debianMB[SPDK]:~/spdk_repo/spdk#
[1]+  Killed                  ./app/nvmf_tgt/nvmf_tgt
root@debianMB[SPDK]:~/spdk_repo/spdk#
```

This is a bit problematic since during cleanup performed after the tests, `killprocess()` would block forever in this case as `wait()` would not have a chance to return (blocking entire test run as a result).  Spotted in here: https://review.spdk.io/gerrit/c/spdk/spdk/+/693

**Comment by AlekseyMarchuk** [comment]
I will check this issue

**Comment by AlekseyMarchuk** [comment]
Hi @mikeBashStuff 

Could you check if patch https://review.spdk.io/gerrit/c/spdk/spdk/+/832 fixes the issue?

**Comment by mikeBashStuff** [comment]
@AlekseyMarchuk  Sure, will do.

**Comment by mikeBashStuff** [comment]
@AlekseyMarchuk I just tested it locally and with your patch everything worked beautifully. :)  It would be really nice to have this merged so https://review.spdk.io/gerrit/c/spdk/spdk/+/693 can be done as well (would need to just adjust code to fit your improvements in the format of the rpc responses :)).

**Comment by AlekseyMarchuk** [comment]
Thank you @mikeBashStuff !
