### ISSUE TITLE
iSCSI bdev called poller_unregister() by the different thread that called poller_register().

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1204]
https://dqtibwqq6s6ux.cloudfront.net/results/autotest-per-patch/builds/3469/archive/iscsi-autotest/build.log

```
Thread 1 (Thread 0x7fa610de7200 (LWP 1192409)):
#0  0x00007fa61a27c57f in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007fa61a266895 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007fa61a266769 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007fa61a274a26 in __assert_fail () from /lib64/libc.so.6
No symbol table info available.
#4  0x0000000000701827 in spdk_poller_unregister (ppoller=0x2859c60) at thread.c:865
        thread = 0x286cd20
        poller = 0x2859010
        __PRETTY_FUNCTION__ = "spdk_poller_unregister"
        __func__ = "spdk_poller_unregister"
#5  0x000000000067834d in bdev_iscsi_destroy_cb (io_device=0x2859a30, ctx_buf=0x286caa0) at bdev_iscsi.c:535
        lun = 0x2859a30
        __PRETTY_FUNCTION__ = "bdev_iscsi_destroy_cb"
#6  0x00000000007070d1 in _spdk_put_io_channel (arg=0x286ca70) at thread.c:1272
        ch = 0x286ca70
        do_remove_dev = true
        thread = 0x286cd20
        __func__ = "_spdk_put_io_channel"
        __PRETTY_FUNCTION__ = "_spdk_put_io_channel"
#7  0x00000000006fca87 in _spdk_msg_queue_run_batch (thread=0x286cd20, max_msgs=8) at thread.c:477
        msg = 0x200019c91600
        count = 3
        i = 0
        messages = {0x200019c91600, 0x200019c91840, 0x200019c916c0, 0x0, 0x0, 0x0, 0x0, 0x0}
        __PRETTY_FUNCTION__ = "_spdk_msg_queue_run_batch"
```

**Comment by shuhei-matsumoto** [comment]
This was caused by https://review.spdk.io/gerrit/c/spdk/spdk/+/890/1.

So close this for now.
Sorry for confused information.

**Comment by changpe1** [comment]
> This was caused by https://review.spdk.io/gerrit/c/spdk/spdk/+/890/1.
> 
> So close this for now.
> Sorry for confused information.

@shuhei-matsumoto Can we close this issue now?

**Comment by shuhei-matsumoto** [comment]
Oh yes, I close this. Thanks @changpe1
