### ISSUE TITLE
rocksdb_insert test - memory leaks, segfault

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1221]
SPDK: v20.01 (HEAD->b70c23feb09af29755db5aa8d81da5378a3d01ce)
OS: Debian 10 (Kernel: 4.19.67)
Config:
```
CONFIG_PREFIX="/usr/local"
CONFIG_ARCH=native
CONFIG_CROSS_PREFIX=
CONFIG_DEBUG=n
CONFIG_LOG_BACKTRACE=n
CONFIG_WERROR=n
CONFIG_LTO=n
CONFIG_PGO_CAPTURE=n
CONFIG_PGO_USE=n
CONFIG_COVERAGE=y
CONFIG_ASAN=y
CONFIG_UBSAN=n
CONFIG_TSAN=n
CONFIG_TESTS=y
CONFIG_ENV=
CONFIG_DPDK_DIR=
CONFIG_FIO_PLUGIN=y
CONFIG_FIO_SOURCE_DIR=/usr/src/fio
CONFIG_RDMA=y
CONFIG_RDMA_SEND_WITH_INVAL=n
CONFIG_NVME_CUSE=y
CONFIG_FC=n
CONFIG_FC_PATH=
CONFIG_RBD=n
CONFIG_VHOST=y
CONFIG_VHOST_INTERNAL_LIB=n
CONFIG_VIRTIO=y
CONFIG_PMDK=n
CONFIG_PMDK_DIR=
CONFIG_REDUCE=n
CONFIG_VPP=n
CONFIG_VPP_DIR=
CONFIG_ISCSI_INITIATOR=y
CONFIG_CRYPTO=y
CONFIG_SHARED=n
CONFIG_VTUNE=n
CONFIG_VTUNE_DIR=
CONFIG_IGB_UIO_DRIVER=n
CONFIG_IPSEC_MB=n
CONFIG_OCF=n
CONFIG_OCF_PATH=
CONFIG_CUSTOMOCF=n
CONFIG_ISAL=y
CONFIG_URING=n
CONFIG_URING_PATH=
CONFIG_FUSE=n
```

Memory leak spotted while running `rocksdb.sh` while not having Nvme0n1 bdev around:
```
************************************
START TEST rocksdb_insert
************************************
...
 17:14:13       # echo -n Start insert test phase...
Start insert test phase... 17:14:13     # taskset 0xFF /root/spdk_repo/spdk/../rocksdb/db_bench --flagfile=insert_flags.txt
  17:14:14      # trap - ERR
  17:14:14      # print_backtrace
  17:14:14      # [[ ehxBET =~ e ]]
  17:14:14      # args=("${BASH_ARGV[@]}")
  17:14:14      # local args
  17:14:14      # xtrace_disable
  17:14:14      # '[' no '!=' yes ']'
  17:14:14      # PREV_BASH_OPTS=ehxBET
  17:14:14      # [[ ehxBET == *\x* ]]
  17:14:14      # XTRACE_DISABLED=yes
  17:14:14      # set +x
========== Backtrace start: ==========

in ./test/blobfs/rocksdb/rocksdb.sh:37 -> run_step(["insert"])
     ...
backtrace unavailable
     ...
in /root/spdk_repo/spdk/test/common/autotest_common.sh:636 -> run_test(["rocksdb_insert"],["run_step"],["insert"])
     ...
   631          timing_enter $test_name
   632          echo "************************************"
   633          echo "START TEST $test_name"
   634          echo "************************************"
   635          xtrace_restore
=> 636          time "$@"
   637          xtrace_disable
   638          echo "************************************"
   639          echo "END TEST $test_name"
   640          echo "************************************"
   641          timing_exit $test_name
     ...
in ./test/blobfs/rocksdb/rocksdb.sh:148 -> main([])
     ...
backtrace unavailable
     ...

========== Backtrace end ==========
  17:14:14      # xtrace_enable
  17:14:14      # return 0

real    0m1.345s
user    0m1.577s
sys     0m0.379s

real    0m1.347s
user    0m1.577s
sys     0m0.382s
 17:14:14       # read_db_bench
 17:14:14       # local step=insert_db_bench.txt
 17:14:14       # local step_read
 17:14:14       # [[ -e insert_db_bench.txt ]]
 17:14:14       # xtrace_disable
 17:14:14       # '[' no '!=' yes ']'
 17:14:14       # PREV_BASH_OPTS=ehxBET
 17:14:14       # [[ ehxBET == *\x* ]]
 17:14:14       # XTRACE_DISABLED=yes
 17:14:14       # set +x
* insert_db_bench.txt (FAILED)Starting SPDK v20.04-pre git sha1 26328b7b1 / DPDK 19.11.0 initialization...
* insert_db_bench.txt (FAILED)[ DPDK EAL parameters: rocksdb --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1645090 ]
* insert_db_bench.txt (FAILED)EAL: No available hugepages reported in hugepages-1048576kB
* insert_db_bench.txt (FAILED)app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
* insert_db_bench.txt (FAILED)app.c: 546:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0x80 specified.
* insert_db_bench.txt (FAILED)app.c: 550:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s rocksdb -p 1645090' to capture a snapshot of events at runtime.
* insert_db_bench.txt (FAILED)app.c: 552:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/rocksdb_trace.pid1645090 for offline analysis/debug.
* insert_db_bench.txt (FAILED)reactor.c: 317:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
* insert_db_bench.txt (FAILED)cryptodev_aesni_mb_create() line 1321: IPSec Multi-buffer library version used: 0.52.0
* insert_db_bench.txt (FAILED)
* insert_db_bench.txt (FAILED)rpc.c: 181:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.
* insert_db_bench.txt (FAILED)rpc.c:  72:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at /var/tmp/spdk.sock
* insert_db_bench.txt (FAILED)/root/spdk_repo/spdk/lib/rocksdb/env_spdk.cc: 673:spdk_rocksdb_run: *ERROR*: bdev Nvme0n1 not found
* insert_db_bench.txt (FAILED)
* insert_db_bench.txt (FAILED)=================================================================
* insert_db_bench.txt (FAILED)==1645090==ERROR: LeakSanitizer: detected memory leaks
* insert_db_bench.txt (FAILED)
* insert_db_bench.txt (FAILED)Direct leak of 611712 byte(s) in 9 object(s) allocated from:
* insert_db_bench.txt (FAILED)    #0 0x7feaf9115018 in __interceptor_posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0xea018)
* insert_db_bench.txt (FAILED)    #1 0x56408d665eee in alloc_mb_mgr (/usr/src/rocksdb/db_bench+0x83ceee)
* insert_db_bench.txt (FAILED)
* insert_db_bench.txt (FAILED)Direct leak of 32 byte(s) in 1 object(s) allocated from:
* insert_db_bench.txt (FAILED)    #0 0x7feaf9114518 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
* insert_db_bench.txt (FAILED)    #1 0x56408d3c71b7 in spdk_bdev_nvme_set_hotplug /root/spdk_repo/spdk/module/bdev/nvme/bdev_nvme.c:1445
* insert_db_bench.txt (FAILED)
* insert_db_bench.txt (FAILED)SUMMARY: AddressSanitizer: 611744 byte(s) leaked in 10 allocation(s).
 17:14:14       # xtrace_enable
 17:14:14       # run_bsdump
 17:14:14       # /root/spdk_repo/spdk/examples/blob/cli/blobcli -c /root/spdk_repo/spdk/test/blobfs/rocksdb/rocksdb.conf -b Nvme0n1 -D
root@debianMB[SPDK]:~/spdk_repo/spdk#
```
Aaaand segfault was spotted when bdev was in place, but there was no enough memory around:
```
************************************
START TEST rocksdb_insert
************************************
...
 17:40:35       # echo -n Start insert test phase...
Start insert test phase... 17:40:35     # taskset 0xFF /root/spdk_repo/spdk/../rocksdb/db_bench --flagfile=insert_flags.txt
./test/blobfs/rocksdb/rocksdb.sh: line 21: 1691698 Segmentation fault      (core dumped) taskset 0xFF $DB_BENCH --flagfile="$1"_flags.txt &> "$1"_db_bench.txt
  17:40:58      # trap - ERR
  17:40:58      # print_backtrace
  17:40:58      # [[ ehxBET =~ e ]]
  17:40:58      # args=("${BASH_ARGV[@]}")
  17:40:58      # local args
  17:40:58      # xtrace_disable
  17:40:58      # '[' no '!=' yes ']'
  17:40:58      # PREV_BASH_OPTS=ehxBET
  17:40:58      # [[ ehxBET == *\x* ]]
  17:40:58      # XTRACE_DISABLED=yes
  17:40:58      # set +x
========== Backtrace start: ==========

in ./test/blobfs/rocksdb/rocksdb.sh:37 -> run_step(["insert"])
     ...
backtrace unavailable
     ...
in /root/spdk_repo/spdk/test/common/autotest_common.sh:636 -> run_test(["rocksdb_insert"],["run_step"],["insert"])
     ...
   631          timing_enter $test_name
   632          echo "************************************"
   633          echo "START TEST $test_name"
   634          echo "************************************"
   635          xtrace_restore
=> 636          time "$@"
   637          xtrace_disable
   638          echo "************************************"
   639          echo "END TEST $test_name"
   640          echo "************************************"
   641          timing_exit $test_name
     ...
in ./test/blobfs/rocksdb/rocksdb.sh:144 -> main([])
     ...
backtrace unavailable
     ...

========== Backtrace end ==========
  17:40:58      # xtrace_enable
  17:40:58      # return 0

real    0m22.931s
user    0m34.570s
sys     0m10.241s

real    0m22.934s
user    0m34.571s
sys     0m10.243s
 17:40:58       # read_db_bench
 17:40:58       # local step=insert_db_bench.txt
 17:40:58       # local step_read
 17:40:58       # [[ -e insert_db_bench.txt ]]
 17:40:58       # xtrace_disable
 17:40:58       # '[' no '!=' yes ']'
 17:40:58       # PREV_BASH_OPTS=ehxBET
 17:40:58       # [[ ehxBET == *\x* ]]
 17:40:58       # XTRACE_DISABLED=yes
 17:40:58       # set +x
* insert_db_bench.txt (FAILED)Starting SPDK v20.04-pre git sha1 b70c23feb / DPDK 19.11.0 initialization...
* insert_db_bench.txt (FAILED)[ DPDK EAL parameters: rocksdb --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1691698 ]
* insert_db_bench.txt (FAILED)EAL: No available hugepages reported in hugepages-1048576kB
* insert_db_bench.txt (FAILED)app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
* insert_db_bench.txt (FAILED)app.c: 546:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0x80 specified.
* insert_db_bench.txt (FAILED)app.c: 550:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s rocksdb -p 1691698' to capture a snapshot of events at runtime.
* insert_db_bench.txt (FAILED)app.c: 552:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/rocksdb_trace.pid1691698 for offline analysis/debug.
* insert_db_bench.txt (FAILED)reactor.c: 317:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
* insert_db_bench.txt (FAILED)cryptodev_aesni_mb_create() line 1321: IPSec Multi-buffer library version used: 0.52.0
* insert_db_bench.txt (FAILED)
* insert_db_bench.txt (FAILED)blobfs.c: 272:__initialize_cache: *ERROR*: Create mempool failed, you may increase the memory and try again
* insert_db_bench.txt (FAILED)Received signal 11 (Segmentation fault)
* insert_db_bench.txt (FAILED)#0   /lib/x86_64-linux-gnu/libc.so.6(+0x37840) [0x7f8f1484e840] ??        ??:0
* insert_db_bench.txt (FAILED)#1   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x775a6b) [0x55d325b62a6b] ??      ??:0
* insert_db_bench.txt (FAILED)#2   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x5d622c) [0x55d3259c322c] ??      ??:0
* insert_db_bench.txt (FAILED)#3   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x5d653a) [0x55d3259c353a] ??      ??:0
* insert_db_bench.txt (FAILED)#4   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x5e1219) [0x55d3259ce219] ??      ??:0
* insert_db_bench.txt (FAILED)#5   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x42055a) [0x55d32580d55a] ??      ??:0
* insert_db_bench.txt (FAILED)#6   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x4acc85) [0x55d325899c85] ??      ??:0
* insert_db_bench.txt (FAILED)#7   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x4ad253) [0x55d32589a253] ??      ??:0
* insert_db_bench.txt (FAILED)#8   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x3ba3ad) [0x55d3257a73ad] ??      ??:0
* insert_db_bench.txt (FAILED)#9   /root/spdk_repo/spdk/../rocksdb/db_bench(+0x3ba47e) [0x55d3257a747e] ??      ??:0
* insert_db_bench.txt (FAILED)#10  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x37b74a) [0x55d32576874a] ??      ??:0
* insert_db_bench.txt (FAILED)#11  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x380567) [0x55d32576d567] ??      ??:0
* insert_db_bench.txt (FAILED)#12  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x3816f1) [0x55d32576e6f1] ??      ??:0
* insert_db_bench.txt (FAILED)#13  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x38322d) [0x55d32577022d] ??      ??:0
* insert_db_bench.txt (FAILED)#14  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x2f30a5) [0x55d3256e00a5] ??      ??:0
* insert_db_bench.txt (FAILED)#15  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x2f3739) [0x55d3256e0739] ??      ??:0
* insert_db_bench.txt (FAILED)#16  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x2ffb1c) [0x55d3256ecb1c] ??      ??:0
* insert_db_bench.txt (FAILED)#17  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x2e03da) [0x55d3256cd3da] ??      ??:0
* insert_db_bench.txt (FAILED)#18  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb) [0x7f8f1483b09b] ??  ??:0
* insert_db_bench.txt (FAILED)#19  /root/spdk_repo/spdk/../rocksdb/db_bench(+0x2df03a) [0x55d3256cc03a] ??      ??:0
 17:40:58       # xtrace_enable
 17:40:58       # run_bsdump
 17:40:58       # /root/spdk_repo/spdk/examples/blob/cli/blobcli -c /root/spdk_repo/spdk/test/blobfs/rocksdb/rocksdb.conf -b Nvme0n1 -D
 17:41:08       # rm -f /root/spdk_repo/spdk/test/blobfs/rocksdb/rocksdb.conf
 17:41:08       # exit 1
root@debianMB[SPDK]:~/spdk_repo/spdk#
```
Just to note that everything works perfectly fine in case the environment is properly set up (hugepages, uio drivers, etc).

**Comment by darsto** [comment]
```
* insert_db_bench.txt (FAILED)Direct leak of 611712 byte(s) in 9 object(s) allocated from:
* insert_db_bench.txt (FAILED)    #0 0x7feaf9115018 in __interceptor_posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0xea018)
* insert_db_bench.txt (FAILED)    #1 0x56408d665eee in alloc_mb_mgr (/usr/src/rocksdb/db_bench+0x83ceee)
* insert_db_bench.txt (FAILED)
* insert_db_bench.txt (FAILED)Direct leak of 32 byte(s) in 1 object(s) allocated from:
* insert_db_bench.txt (FAILED)    #0 0x7feaf9114518 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0xe9518)
* insert_db_bench.txt (FAILED)    #1 0x56408d3c71b7 in spdk_bdev_nvme_set_hotplug /root/spdk_repo/spdk/module/bdev/nvme/bdev_nvme.c:1445
* insert_db_bench.txt (FAILED)
```

I'm pretty sure this is because we don't do proper cleanup on initialization failure.
There was a github issue about it - https://github.com/spdk/spdk/issues/739
I'm going to close this one and reopen #739 . It's not just a bug lurking somewhere in our crypto or nvme hotplug - there's probably more we don't even know about, because we're not testing initialization failures.

**Comment by mikeBashStuff** [comment]
@darsto What about the segfault? You think it's caused by the very same thing - https://github.com/spdk/spdk/issues/739?

**Comment by darsto** [comment]
Yup.

```
* insert_db_bench.txt (FAILED)blobfs.c: 272:__initialize_cache: *ERROR*: Create mempool failed, you may increase the memory and try again
* insert_db_bench.txt (FAILED)Received signal 11 (Segmentation fault)
```

We just don't handle initialization failures properly
