### ISSUE TITLE
iSCSI target got segmentation fault when connection is killed between spdk_iscsi_conn_write_pdu() and its callback.

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#1278]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

SPDK iSCSI target got segmentation fault because conn->sock was NULL when spdk_sock_group_remove_sock() was called.

```
106888 2020-03-12T16:06:33.636459+09:00 SN01-Sano hsds-platform[1969]: conn.c: 913:spdk_iscsi_drop_conns: *ERROR*: drop old connections iqn.1994-04.jp.co.hitachi:rsd.sph.t.04436.000 by iqn.1991-05.com.microsoft:win-g7mqgirmfls12,i,0x400001370000
106889 2020-03-12T16:06:33.636692+09:00 SN01-Sano hsds-platform[1969]: conn.c: 917:spdk_iscsi_drop_conns: *ERROR*: exiting conn by iqn.1991-05.com.microsoft:win-g7mqgirmfls12,i,0x400001370000 (192.168.134.179)
106890 2020-03-12T16:06:33.636850+09:00 SN01-Sano hsds-platform[1969]: conn.c: 917:spdk_iscsi_drop_conns: *ERROR*: exiting conn by iqn.1991-05.com.microsoft:win-g7mqgirmfls12,i,0x400001370000 (192.168.134.180)
106891 2020-03-12T16:06:33.637056+09:00 SN01-Sano hsds-platform[1969]: conn.c: 939:spdk_iscsi_drop_conns: *ERROR*: exiting 2 conns 
106892 2020-03-12T16:06:33.641020+09:00 SN01-Sano kernel: [14136.243683] reactor_0[12906]: segfault at 0 ip 00000000022c852b sp 00007f2ee16498d0 error 4 in hsds-fe[400000+2416000] 

#0  spdk_sock_group_remove_sock (group=0x14229b20, sock=0x0) at sock.c:489 
#1  0x00000000022ca02c in iscsi_poll_group_remove_conn (pg=0x7c96880, conn=conn@entry=0x7f2ed38bc000) at conn.c:191
#2  0x00000000022cc620 in spdk_iscsi_conn_schedule (conn=0x7f2ed38bc000) at conn.c:1592
#3  0x00000000022cb3c5 in iscsi_conn_free_tasks (conn=conn@entry=0x7f2ed38bc000) at conn.c:348
#4  0x00000000022cb438 in _iscsi_conn_destruct (conn=0x7f2ed38bc000) at conn.c:661
#5  0x00000000022da7dd in iscsi_poll_group_poll (ctx=<optimized out>) at iscsi_subsystem.c:1163
#6  0x00000000022c39c6 in spdk_thread_poll (thread=0x14233800, max_msgs=max_msgs@entry=0, now=now@entry=29642183956942) at thread.c:531
#7  0x000000000230898d in _spdk_reactor_run (arg=0x14227c80) at reactor.c:337
#8  0x00000000023091a9 in spdk_reactors_start () at reactor.c:426
#9  0x0000000002307977 in spdk_app_start (opts=opts@entry=0x7f2ee164a0e0,

```

## Expected Behavior

No segmentation fault.

## Current Behavior

The above

## Possible Solution

None.

## Steps to Reproduce

Some operation from host to SPDK iSCSI target.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 20.01

**Comment by shuhei-matsumoto** [comment]
The patch is https://review.spdk.io/gerrit/c/spdk/spdk/+/1275

**Comment by darsto** [comment]
Fix merged. Thanks Shuhei
