### ISSUE TITLE
Frequent iSCSI test fail in CI system related with RPC

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1319]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Most of patch fails due to the rpc issue in the following log:
https://ci.spdk.io/results/autotest-per-patch/builds/8063/archive/unittest-autotest/build.log

## Expected Behavior

The test should pass

## Current Behavior

Failed.

## Possible Solution

Need to investigate 

## Steps to Reproduce

See the log:

iscsi_get_connections returned [{'id': 0, 'cid': 0, 'tsih': 1, 'initiator_addr': '10.0.0.2', 'target_addr': '10.0.0.1', 'target_node_name': '', 'thread_name': 'iscsi_poll_group_0'}], expected empty. Exiting with status 1
Traceback (most recent call last):
  File "/var/jenkins/workspace/iscsi-autotest/spdk/test/iscsi_tgt/rpc_config/rpc_config.py", line 502, in <module>
    raise e
  File "/var/jenkins/workspace/iscsi-autotest/spdk/test/iscsi_tgt/rpc_config/rpc_config.py", line 498, in <module>
    verify_iscsi_connection_rpc_methods(rpc_py)
  File "/var/jenkins/workspace/iscsi-autotest/spdk/test/iscsi_tgt/rpc_config/rpc_config.py", line 102, in verify_iscsi_connection_rpc_methods
    "iscsi_get_connections returned {}, expected empty".format(jsonvalue))
  File "/var/jenkins/workspace/iscsi-autotest/spdk/test/iscsi_tgt/rpc_config/rpc_config.py", line 74, in verify
    raise RpcException(retcode, msg)
__main__.RpcException: iscsi_get_connections returned [{'id': 0, 'cid': 0, 'tsih': 1, 'initiator_addr': '10.0.0.2', 'target_addr': '10.0.0.1', 'target_node_name': '', 'thread_name': 'iscsi_poll_group_0'}], expected empty
  08:43:27	# trap - ERR
  08:43:27	# print_backtrace
  08:43:27	# [[ ehxBET =~ e ]]
  08:43:27	# args=("${BASH_ARGV[@]}")
  08:43:27	# local args
  08:43:27	# xtrace_disable
  08:43:27	# '[' no '!=' yes ']'
  08:43:27	# PREV_BASH_OPTS=ehxBET
  08:43:27	# [[ ehxBET == *\x* ]]
  08:43:27	# XTRACE_DISABLED=yes
  08:43:27	# set +x
========== Backtrace start: ==========

in ./test/iscsi_tgt/rpc_config/rpc_config.sh:54 -> main(["posix"])
     ...
   49  	sleep 1
   50  	! ps $rpc_wait_pid
   51  	
   52  	timing_exit start_iscsi_tgt
   53  	
=> 54  	$rpc_config_py $rpc_py $TARGET_IP $INITIATOR_IP $ISCSI_PORT $NETMASK $TARGET_NAMESPACE $TEST_TYPE
   55  	
   56  	$rpc_py bdev_get_bdevs
   57  	
   58  	trap - SIGINT SIGTERM EXIT
   59  	
     ...

**Comment by karlatec** [comment]
> Most of patch fails due to the rpc issue in the following log:
> https://ci.spdk.io/results/autotest-per-patch/builds/8063/archive/unittest-autotest/build.log

That doesn't look like a related issue
```
  SO libspdk_blobfs_bdev.so.2.0
In file included from /var/jenkins/workspace/unittest-autotest/spdk/include/spdk/stdinc.h:48,
                 from posix.c:34:
posix.c: In function â€˜spdk_posix_sock_group_impl_add_sockâ€™:
posix.c:1080:10: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]
 1080 |   assert(sock->pending_recv = false);
      |          ^~~~
cc1: all warnings being treated as errors
make[3]: *** [/var/jenkins/workspace/unittest-autotest/spdk/mk/spdk.common.mk:367: posix.o] Error 1
  SYMLINK libspdk_bdev_gpt.so
make[2]: *** [/var/jenkins/workspace/unittest-autotest/spdk/mk/spdk.subdirs.mk:44: posix] Error 2
make[1]: *** [/var/jenkins/workspace/unittest-autotest/spdk/mk/spdk.subdirs.mk:44: sock] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by optimistyzy** [comment]
@karlatec I also see patches from others have the same behavior

**Comment by optimistyzy** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/8065/archive/iscsi-autotest/build.log

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_8204.html

**Comment by changpe1** [comment]
[Bug Scrub] Could you take a look ?

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @wawryk. log: https://ci.spdk.io/public_build/autotest-per-patch_8821.html

**Comment by AlekseyMarchuk** [comment]
No new reports for 2 months, suggest closing it
