### ISSUE TITLE
nvmf_tgt exit and report error if  binding with a wrong  address

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1326]
# Issue:
commit: b8eaa9679132c5e701c7ecd5bd1050ed1bc2a458
```
./app/nvmf_tgt/nvmf_tgt --json reconnmalloc.json
Starting SPDK v20.04-pre git sha1 56870cb7a / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid6450 ]
app.c: 646:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 362:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
rdma.c:2709:spdk_nvmf_rdma_listen: *ERROR*: rdma_bind_addr() failed
nvmf.c: 571:spdk_nvmf_tgt_listen: *ERROR*: Unable to listen on address '192.168.133.11'
json_config.c: 192:rpc_client_poller: *ERROR*: error response: {"code":-32602,"message":"Invalid parameters"}}
app.c: 716:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero

=================================================================
==6450==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 584 byte(s) in 1 object(s) allocated from:



    #0 0x7f4bd91ede56 in __interceptor_calloc (/lib64/libasan.so.5+0x10de56)
    #1 0x55723e in spdk_nvmf_transport_listen /home/storage/spdk/lib/nvmf/transport.c:214

```
./configure --with-rdma --enable-asan

nvmf target will exit and report memory leaks.

reconnmalloc.json
[reconn.txt](https://github.com/spdk/spdk/files/4406487/reconn.txt)

**Comment by changpe1** [comment]
Thanks @yidong0635, will you take a look ?

**Comment by yidong0635** [comment]
ok , I got the solution.

**Comment by yidong0635** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/1595

**Comment by changpe1** [comment]
Patch was merged, close this issue.
