### ISSUE TITLE
the spdk iscsi disk can't be formatted in vmware esxi 6.7.0 

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#1414]
## Expected Behavior

the spdk iscsi disk can be formatted with vmfs5 and vmfs6
## Current Behavior
the spdk iscsi disk can't be formatted with vmfs5 and vmfs6.

## Possible Solution
the vmware reported following log:
```
2020-05-26T06:10:41.680Z cpu7:2100033 opID=db37ede)World: 11942: VC opID 18ac3b26 maps to vmkernel opID db37ede
2020-05-26T06:10:41.680Z cpu7:2100033 opID=db37ede)LVM: 12674: LVMProbeDevice failed with status "Device does not contain a logical volume".
2020-05-26T06:10:41.682Z cpu0:2098283)ScsiDeviceIO: 3029: Cmd(0x459a40a191c0) 0x16, CmdSN 0xd0a from world 0 to dev "naa.2000000347006f9a" failed H:0x0 D:0x2 P:0x0 Valid sense data: 0x5 0x20 0x0.
2020-05-26T06:10:41.682Z cpu7:2100033 opID=db37ede)LVM: 10419: LVMProbeDevice failed on (3964225888, naa.2000000347006f9a:1): Device does not contain a logical volume
2020-05-26T06:10:41.682Z cpu7:2100033 opID=db37ede)FSS: 2350: Failed to create FS on dev [naa.2000000347006f9a:1] fs [dfsdf] type [vmfs3] fbSize 1048576 => Not supported
```
it seems that the block size is not correct.
## Steps to Reproduce
1.  run spdk iscsi tgt, configure AIO bdev with block size 512.
2. In vmware esxi .7, configure iscsi device.
3. try to create new datastore using spdk iscsi device.

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit: b8ac3e8acdfd6bcb81204e160d652b681fd05052
vmware version: vmware esxi 6.7.0-8169922-standard

**Comment by changpe1** [comment]
@liang2yan Do you have any SPDK log information when this happened?

**Comment by liang2yan** [comment]
I have use Linux LIO iscsi target to reproduce this issue. And the vmware esxi can correctly format the iscsi device which is from LIO iscsi target.
Then I run spdk iscsi target with iscsi and scsi debug log again, the issue still can be reproduced. i have put some log in the attached file which is got when the issue happened.
[1414.txt.txt](https://github.com/spdk/spdk/files/4728038/1414.txt.txt)

**Comment by changpe1** [comment]
I believe that the issue should relate with RESERVE 0x16 command defined in SPC2, in existing SPDK reservation implementation, we didn't support this command, while LIO target do support that.

**Comment by changpe1** [comment]
OK, after the investigation, I think we can add RESERVE/RELEASE support defined in SPC2 as backward compatible. I mark this as an enhancement issue.

**Comment by Comphix** [comment]
Thanks @changpe1

**Comment by changpe1** [comment]
@liang2yan I implemented a fake support https://review.spdk.io/gerrit/c/spdk/spdk/+/2802/1 now, it will always return success for RESERVE/RELEASE now, can you have a try with your environment, if it can work I will add the whole support according to the specification. Thanks.

**Comment by liang2yan** [comment]
@changpe1 , I have tried your patch. the spdk iscsi target crashed while vmware esxi tried to format the disk. The spdk log is as below:

```
CDB
00000000  1a 08 0a 00 10 00 00 00  00 00 00 00 00 00 00 00   ................
[2020-06-09 11:05:48.936585] iscsi.c:4573:iscsi_pdu_payload_handle: *DEBUG*: opcode 1
[2020-06-09 11:05:48.936598] scsi_bdev.c: 918:bdev_scsi_mode_sense_page: *DEBUG*: MODE_SENSE Control
[2020-06-09 11:05:48.936609] scsi_bdev.c: 918:bdev_scsi_mode_sense_page: *DEBUG*: MODE_SENSE Control
[2020-06-09 11:05:48.936619] iscsi.c:3077:iscsi_transfer_in: *DEBUG*: Transfer 16
[2020-06-09 11:05:48.936633] iscsi.c:3112:iscsi_transfer_in: *DEBUG*: Transfer=16, Offset=0, Len=16
[2020-06-09 11:05:48.936642] iscsi.c:3114:iscsi_transfer_in: *DEBUG*: StatSN=213, DataSN=0, Offset=0, Len=16
[2020-06-09 11:05:48.936722] iscsi.c:4493:iscsi_pdu_hdr_handle: *DEBUG*: opcode 1
CDB
00000000  28 00 00 00 00 00 00 00  01 00 00 00 00 00 00 00   (...............
[2020-06-09 11:05:48.936750] iscsi.c:4573:iscsi_pdu_payload_handle: *DEBUG*: opcode 1
[2020-06-09 11:05:48.936764] scsi_bdev.c:1350:bdev_scsi_readwrite: *DEBUG*: Read: lba=0, len=1
[2020-06-09 11:05:48.936794] iscsi.c:3077:iscsi_transfer_in: *DEBUG*: Transfer 512
[2020-06-09 11:05:48.936813] iscsi.c:3112:iscsi_transfer_in: *DEBUG*: Transfer=512, Offset=0, Len=512
[2020-06-09 11:05:48.936824] iscsi.c:3114:iscsi_transfer_in: *DEBUG*: StatSN=214, DataSN=0, Offset=0, Len=512
[2020-06-09 11:05:48.936902] iscsi.c:4493:iscsi_pdu_hdr_handle: *DEBUG*: opcode 1
CDB
00000000  28 00 00 00 00 01 00 00  01 00 00 00 00 00 00 00   (...............
[2020-06-09 11:05:48.936934] iscsi.c:4573:iscsi_pdu_payload_handle: *DEBUG*: opcode 1
[2020-06-09 11:05:48.936947] scsi_bdev.c:1350:bdev_scsi_readwrite: *DEBUG*: Read: lba=1, len=1
[2020-06-09 11:05:48.936976] iscsi.c:3077:iscsi_transfer_in: *DEBUG*: Transfer 512
[2020-06-09 11:05:48.936989] iscsi.c:3112:iscsi_transfer_in: *DEBUG*: Transfer=512, Offset=0, Len=512
[2020-06-09 11:05:48.937002] iscsi.c:3114:iscsi_transfer_in: *DEBUG*: StatSN=215, DataSN=0, Offset=0, Len=512
[2020-06-09 11:05:48.937080] iscsi.c:4493:iscsi_pdu_hdr_handle: *DEBUG*: opcode 1
CDB
00000000  28 00 00 00 00 02 00 00  20 00 00 00 00 00 00 00   (....... .......
[2020-06-09 11:05:48.937111] iscsi.c:4573:iscsi_pdu_payload_handle: *DEBUG*: opcode 1
[2020-06-09 11:05:48.937122] scsi_bdev.c:1350:bdev_scsi_readwrite: *DEBUG*: Read: lba=2, len=32
[2020-06-09 11:05:48.937156] iscsi.c:3077:iscsi_transfer_in: *DEBUG*: Transfer 16384
[2020-06-09 11:05:48.937171] iscsi.c:3112:iscsi_transfer_in: *DEBUG*: Transfer=16384, Offset=0, Len=16384
[2020-06-09 11:05:48.937184] iscsi.c:3114:iscsi_transfer_in: *DEBUG*: StatSN=216, DataSN=0, Offset=0, Len=16384
[2020-06-09 11:05:48.937446] iscsi.c:4493:iscsi_pdu_hdr_handle: *DEBUG*: opcode 1
CDB
00000000  1a 00 0a 00 18 00 00 00  00 00 00 00 00 00 00 00   ................
[2020-06-09 11:05:48.937478] iscsi.c:4573:iscsi_pdu_payload_handle: *DEBUG*: opcode 1
[2020-06-09 11:05:48.937490] scsi_bdev.c: 918:bdev_scsi_mode_sense_page: *DEBUG*: MODE_SENSE Control
[2020-06-09 11:05:48.937500] scsi_bdev.c: 918:bdev_scsi_mode_sense_page: *DEBUG*: MODE_SENSE Control
[2020-06-09 11:05:48.937514] iscsi.c:3077:iscsi_transfer_in: *DEBUG*: Transfer 24
[2020-06-09 11:05:48.937524] iscsi.c:3112:iscsi_transfer_in: *DEBUG*: Transfer=24, Offset=0, Len=24
[2020-06-09 11:05:48.937534] iscsi.c:3114:iscsi_transfer_in: *DEBUG*: StatSN=217, DataSN=0, Offset=0, Len=24
[2020-06-09 11:05:48.937616] iscsi.c:4493:iscsi_pdu_hdr_handle: *DEBUG*: opcode 1
CDB
00000000  16 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................
[2020-06-09 11:05:48.937647] iscsi.c:4573:iscsi_pdu_payload_handle: *DEBUG*: opcode 1
iscsi_tgt: task.c:161: spdk_scsi_task_gather_data: Assertion `iovs[i].iov_base != ((void *)0)' failed.
Aborted (core dumped)
```
The coredump is as below:
```
Core was generated by `./app/iscsi_tgt/iscsi_tgt --json iscsi.json -L iscsi -L scsi'.
Program terminated with signal 6, Aborted.
#0  0x00007ff449bb6207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
55        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-39.el7.x86_64 libuuid-2.23.2-63.el7.x86_64 numactl-libs-2.0.12-5.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64
(gdb) bt
#0  0x00007ff449bb6207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ff449bb78f8 in __GI_abort () at abort.c:90
#2  0x00007ff449baf026 in __assert_fail_base (fmt=0x7ff449d09ea0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x61b2d0 "iovs[i].iov_base != ((void *)0)", file=file@entry=0x61b240 "task.c",
    line=line@entry=161, function=function@entry=0x61b390 <__PRETTY_FUNCTION__.11364> "spdk_scsi_task_gather_data") at assert.c:92
#3  0x00007ff449baf0d2 in __GI___assert_fail (assertion=0x61b2d0 "iovs[i].iov_base != ((void *)0)", file=0x61b240 "task.c", line=161, function=0x61b390 <__PRETTY_FUNCTION__.11364> "spdk_scsi_task_gather_data") at assert.c:101
#4  0x00000000004ecf98 in spdk_scsi_task_gather_data (task=0x20002ca11bc0, len=0x7ffee4754f30) at task.c:161
#5  0x00000000004ea36b in bdev_scsi_process_primary (task=0x20002ca11bc0) at scsi_bdev.c:1941
#6  0x00000000004ea48c in bdev_scsi_execute (task=0x20002ca11bc0) at scsi_bdev.c:1987
#7  0x00000000004e53ba in _scsi_lun_execute_task (lun=0x2925ac0, task=0x20002ca11bc0) at lun.c:205
#8  0x00000000004e558c in scsi_lun_execute_task (lun=0x2925ac0, task=0x20002ca11bc0) at lun.c:259
#9  0x00000000004e48a5 in spdk_scsi_dev_queue_task (dev=0x8a7800 <g_devs>, task=0x20002ca11bc0) at dev.c:274
#10 0x00000000004d0670 in iscsi_queue_task (conn=0x7ff440140000, task=0x20002ca11bc0) at iscsi.c:3264
#11 0x00000000004d0eda in iscsi_pdu_payload_op_scsi (conn=0x7ff440140000, pdu=0x200015b04040) at iscsi.c:3473
#12 0x00000000004d3c5a in iscsi_pdu_payload_handle (conn=0x7ff440140000, pdu=0x200015b04040) at iscsi.c:4583
#13 0x00000000004d4523 in iscsi_read_pdu (conn=0x7ff440140000) at iscsi.c:4786
#14 0x00000000004d45f7 in iscsi_handle_incoming_pdus (conn=0x7ff440140000) at iscsi.c:4821
#15 0x00000000004c5c04 in iscsi_conn_sock_cb (arg=0x7ff440140000, group=0x1d288c0, sock=0x2924e00) at conn.c:1566
#16 0x0000000000500bcf in sock_group_impl_poll_count (group_impl=0x291c830, group=0x1d288c0, max_events=32) at sock.c:618
#17 0x0000000000500c66 in spdk_sock_group_poll_count (group=0x1d288c0, max_events=32) at sock.c:645
#18 0x0000000000500a62 in spdk_sock_group_poll (group=0x1d288c0) at sock.c:582
#19 0x00000000004dfe3f in iscsi_poll_group_poll (ctx=0x1d30b50) at iscsi_subsystem.c:1195
#20 0x00000000004f1a83 in thread_poll (thread=0x291c4e0, max_msgs=0, now=3190404057817706) at thread.c:593
#21 0x00000000004f1ed0 in spdk_thread_poll (thread=0x291c4e0, max_msgs=0, now=3190404057817706) at thread.c:680
#22 0x00000000004a539c in _reactor_run (reactor=0x1d30c00) at reactor.c:326
#23 0x00000000004a54ae in reactor_run (arg=0x1d30c00) at reactor.c:382
#24 0x00000000004a58c9 in spdk_reactors_start () at reactor.c:477
#25 0x00000000004a3919 in spdk_app_start (opts=0x7ffee4755900, start_fn=0x4055e1 <spdk_startup>, arg1=0x0) at app.c:688
#26 0x0000000000405773 in main (argc=7, argv=0x7ffee4755aa8) at iscsi_tgt.c:112

```

**Comment by changpe1** [comment]
@liang2yan Thanks Liang, I updated the patch, please try again.

**Comment by liang2yan** [comment]
Tried your updated patch. The vmware esxi can correctly format the spdk iscsi target with AIO and nvme bdev. So the patch works.

**Comment by changpe1** [comment]
> Tried your updated patch. The vmware esxi can correctly format the spdk iscsi target with AIO and nvme bdev. So the patch works.

Thanks Liang, then I will add SPC2 RESERVE/RELEASE support, both VMWARE ESXI and Windows will use SPC2 RESERVE/RELEASE.

**Comment by liang2yan** [comment]
I have verified this issue with the patch link below:
https://review.spdk.io/gerrit/c/spdk/spdk/+/2802/5

The vmware esxi can format the spdk iscsi disk. But sometimes it is slow that operating the datastore which is created using SPDK iscsi disk. let me get some logs about this problem.

**Comment by liang2yan** [comment]
I have tried several times, the issue which I mentioned in last comment only happened one time. And it doesn't affect the normal operation. So I think we can close this issue after the patch merged.

**Comment by changpe1** [comment]
Thanks @liang2yan, glad to see that, I will start the code review process now.

**Comment by changpe1** [comment]
Closing this issue as patch was merged.
