### ISSUE TITLE
Memory leaks w/ tcmalloc during nvme-autotest

### ISSUE THREAD

**Issue by wawryk** [spdk/spdk#1426]
## Expected Behavior
test pass

## Current Behavior
test fail

## Steps to Reproduce

1.Run nvme_autotest on clearlinux

## Context (Environment including OS version, SPDK version, etc.)
```
=================================================================
==221933==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fbd1507bf9f in operator new(unsigned long) (/usr/lib64/libasan.so.5+0x10ff9f)
    #1 0x7fbd12af2b2d  (/usr/lib64/libtcmalloc.so.4+0x2eb2d)
    #2 0x7fbd12af336c in MallocExtension::Register(MallocExtension*) (/usr/lib64/libtcmalloc.so.4+0x2f36c)
    #3 0x7fbd12adc223  (/usr/lib64/libtcmalloc.so.4+0x18223)
    #4 0x7fbd159bae9b in call_init /builddir/build/BUILD/glibc-2.31/elf/dl-init.c:72

-----------------------------------------------------
Suppressions used:
  count      bytes template
     51        821 /usr/src/fio/parse.c
   5802     510576 /usr/src/fio/iolog.c
      5         30 /usr/src/fio/init.c
      2        838 fio_memalign
      2         32 spdk_fio_io_u_init
-----------------------------------------------------

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
  08:50:15      # trap - ERR
  08:50:15      # print_backtrace
  08:50:15      # [[ ehxBET =~ e ]]
  08:50:15      # args=("${BASH_ARGV[@]}")
  08:50:15      # local args
  08:50:15      # xtrace_disable
  08:50:15      # '[' no '!=' yes ']'
  08:50:15      # PREV_BASH_OPTS=ehxBET
  08:50:15      # [[ ehxBET == *\x* ]]
  08:50:15      # XTRACE_DISABLED=yes
  08:50:15      # set +x
========== Backtrace start: ==========

in /home/clear/spdk_repo/spdk/test/common/autotest_common.sh:1121 -> fio_bdev(["/home/clear/spdk_repo/spdk/test/ocf/integrity/test.fio"],["--aux-path=/tmp/"],["--ioengine=spdk_bdev"],["--filename=PT_Nvme:WT_Nvme:WB_Nvme0:WB_Nvme1"],["--spdk_json_conf=/home/clear/spdk_repo/spdk/test/ocf/integrity/modes.conf"],["--thread=1"])
     ...
   1116
   1117         # Preload AddressSanitizer library to fio if fio_plugin was compiled with it
   1118         local asan_lib
   1119         asan_lib=$(ldd $bdev_plugin | grep libasan | awk '{print $3}')
   1120
   1121         LD_PRELOAD="$asan_lib $bdev_plugin" "$fio_dir"/fio "$@"
   1122 }
   1123
   1124 function fio_nvme() {
   1125         # Setup fio binary cmd line
   1126         local fio_dir=$CONFIG_FIO_SOURCE_DIR
     ...
in /home/clear/spdk_repo/spdk/test/ocf/integrity/fio-modes.sh:9 -> fio_verify(["--filename=PT_Nvme:WT_Nvme:WB_Nvme0:WB_Nvme1"],["--spdk_json_conf=/home/clear/spdk_repo/spdk/test/ocf/integrity/modes.conf"],["--thread=1"])
     ...
   4    rootdir=$(readlink -f $curdir/../../..)
   5
   6    source $rootdir/test/ocf/common.sh
   7
   8    function fio_verify() {
=> 9            fio_bdev $curdir/test.fio --aux-path=/tmp/ --ioengine=spdk_bdev "$@"
   10   }
   11
   12   function cleanup() {
   13           rm -f $curdir/modes.conf
   14   }
     ...
in /home/clear/spdk_repo/spdk/test/ocf/integrity/fio-modes.sh:87 -> main([])
     ...
   82   jq . "$curdir/modes.conf"
   83
   84   # ... and now back to our regularly scheduled program
   85   xtrace_restore
   86
=> 87   fio_verify --filename=PT_Nvme:WT_Nvme:WB_Nvme0:WB_Nvme1 --spdk_json_conf="$curdir/modes.conf" --thread=1
   88
   89   trap - SIGINT SIGTERM EXIT
   90   cleanup
     ...

========== Backtrace end ==========
  08:50:15      # xtrace_enable
  08:50:15      # return 0
 08:50:15       # cleanup
 08:50:15       # rm -f /home/clear/spdk_repo/spdk/test/ocf/integrity/modes.conf
 08:50:15       # exit 1
  08:50:15      # trap - ERR
  08:50:15      # print_backtrace
  08:50:15      # [[ ehxBET =~ e ]]
  08:50:15      # args=("${BASH_ARGV[@]}")
  08:50:15      # local args
  08:50:15      # xtrace_disable
  08:50:15      # '[' no '!=' yes ']'
  08:50:15      # PREV_BASH_OPTS=ehxBET
  08:50:15      # [[ ehxBET == *\x* ]]
  08:50:15      # XTRACE_DISABLED=yes
  08:50:15      # set +x
========== Backtrace start: ==========

in /home/clear/spdk_repo/spdk/test/common/autotest_common.sh:874 -> run_test(["ocf_fio_modes"],["/home/clear/spdk_repo/spdk/test/ocf/integrity/fio-modes.sh"])
     ...
   869          timing_enter $test_name
   870          echo "************************************"
   871          echo "START TEST $test_name"
   872          echo "************************************"
   873          xtrace_restore
=> 874          time "$@"
   875          xtrace_disable
   876          echo "************************************"
   877          echo "END TEST $test_name"
   878          echo "************************************"
   879          timing_exit $test_name
     ...
in ./test/ocf/ocf.sh:8 -> main([])
     ...
   3    testdir=$(readlink -f $(dirname $0))
   4    rootdir=$(readlink -f $testdir/../..)
   5
   6    source $rootdir/test/common/autotest_common.sh
   7
=> 8    run_test "ocf_fio_modes" "$testdir/integrity/fio-modes.sh"
   9    run_test "ocf_bdevperf_iotypes" "$testdir/integrity/bdevperf-iotypes.sh"
   10   run_test "ocf_stats" "$testdir/integrity/stats.sh"
   11   run_test "ocf_create_destruct" "$testdir/management/create-destruct.sh"
   12   run_test "ocf_multicore" "$testdir/management/multicore.sh"
   13   run_test "ocf_persistent_metadata" "$testdir/management/persistent-metadata.sh"
     ...

========== Backtrace end ==========
  08:50:15      # xtrace_enable
  08:50:15      # return 0

real    0m25.316s
user    0m56.864s
sys     0m3.902s
  08:50:15      # trap - ERR
  08:50:15      # print_backtrace
  08:50:15      # [[ ehxBET =~ e ]]
  08:50:15      # args=("${BASH_ARGV[@]}")
  08:50:15      # local args
  08:50:15      # xtrace_disable
  08:50:15      # '[' no '!=' yes ']'
  08:50:15      # PREV_BASH_OPTS=ehxBET
  08:50:15      # [[ ehxBET == *\x* ]]
  08:50:15      # XTRACE_DISABLED=yes
  08:50:15      # set +x
========== Backtrace start: ==========

in /home/clear/spdk_repo/spdk/test/common/autotest_common.sh:874 -> run_test(["ocf"],["./test/ocf/ocf.sh"])
     ...
   869          timing_enter $test_name
   870          echo "************************************"
   871          echo "START TEST $test_name"
   872          echo "************************************"
   873          xtrace_restore
=> 874          time "$@"
   875          xtrace_disable
   876          echo "************************************"
   877          echo "END TEST $test_name"
   878          echo "************************************"
   879          timing_exit $test_name
     ...
in /home/clear/spdk_repo/spdk/autotest.sh:273 -> main(["/home/clear/autorun-spdk.conf"])
     ...
   268                  run_test "blockdev_rbd" ./test/bdev/blockdev.sh "rbd"
   269                  run_test "spdkcli_rbd" ./test/spdkcli/rbd.sh
   270          fi
   271
   272          if [ $SPDK_TEST_OCF -eq 1 ]; then
=> 273                  run_test "ocf" ./test/ocf/ocf.sh
   274          fi
   275
   276          if [ $SPDK_TEST_FTL -eq 1 ]; then
   277                  run_test "ftl" ./test/ftl/ftl.sh
   278          fi
     ...

========== Backtrace end ==========
  08:50:15      # xtrace_enable
  08:50:15      # return 0

real    0m25.398s
user    0m56.909s
sys     0m3.959s
```

OS: Linux clearlinux 5.4.33-31.lts2019 #1 SMP Fri Apr 17 03:03:03 PDT 2020 x86_64 GNU/Linux
gcc:
```
gcc (Clear Linux OS for Intel Architecture) 9.3.1 20200420 releases/gcc-9.3.0-156-g47ea8616d4
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

clang:
```
clang version 10.0.0
Target: x86_64-generic-linux
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by darsto** [comment]
Apparently it's discouraged to use ASAN with custom allocators, but I might try just to suppress those leaks and see if any other issues arise. If it works, then I would say we can use it on CI.

**Comment by darsto** [comment]
My Clear Linux VM can't mmap hugepages for whatever reason. Sorry, I don't have time to look into this deeper so I'm unassigning myself

**Comment by darsto** [comment]
Apparently this doesn't happen every time. @wawryk will see if it's even still reproducible on a clear system.

**Comment by wawryk** [comment]
Today, I use new, clean vm to test this once more and have other memory leak:
```
=================================================================
==56991==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 40960 byte(s) in 1 object(s) allocated from:
    #0 0x7f6abc0ff337 in calloc (/usr/lib64/libasan.so.6+0xcb337)
    #1 0x55b286b5af68 in nvme_rdma_calloc /home/clear/spdk_repo/spdk/lib/nvme/nvme_rdma.c:309
    #2 0x55b286b66ac6 in nvme_rdma_alloc_reqs /home/clear/spdk_repo/spdk/lib/nvme/nvme_rdma.c:924
    #3 0x55b286b732b6 in nvme_rdma_ctrlr_create_qpair /home/clear/spdk_repo/spdk/lib/nvme/nvme_rdma.c:1767
    #4 0x55b286b75352 in nvme_rdma_ctrlr_create_io_qpair /home/clear/spdk_repo/spdk/lib/nvme/nvme_rdma.c:1869
    #5 0x55b286b0f31d in nvme_transport_ctrlr_create_io_qpair /home/clear/spdk_repo/spdk/lib/nvme/nvme_transport.c:270
    #6 0x55b286a94cdf in nvme_ctrlr_create_io_qpair /home/clear/spdk_repo/spdk/lib/nvme/nvme_ctrlr.c:361
    #7 0x55b286a95ac2 in spdk_nvme_ctrlr_alloc_io_qpair /home/clear/spdk_repo/spdk/lib/nvme/nvme_ctrlr.c:446
    #8 0x55b286a65448 in nvme_init_ns_worker_ctx /home/clear/spdk_repo/spdk/examples/nvme/perf/perf.c:620
    #9 0x55b286a6a1e1 in init_ns_worker_ctx /home/clear/spdk_repo/spdk/examples/nvme/perf/perf.c:1024
    #10 0x55b286a6a8d0 in work_fn /home/clear/spdk_repo/spdk/examples/nvme/perf/perf.c:1076
    #11 0x55b286a743db in main /home/clear/spdk_repo/spdk/examples/nvme/perf/perf.c:2115
    #12 0x7f6abb14851c in __libc_start_main (/usr/lib64/haswell/libc.so.6+0x2a51c)

```

**Comment by darsto** [comment]
That's probably unrelated to clear linux - it's not a tcmalloc issue, so I guess it could happen on other systems too. Can you create another github issue?

**Comment by tomzawadzki** [comment]
[Bug scrub] @wawryk please update the current status of the tcmalloc related issue.

As for https://github.com/spdk/spdk/issues/1426#issuecomment-640754908 @wawryk will open new issue.

**Comment by wawryk** [comment]
New issue: https://github.com/spdk/spdk/issues/1447
This one was related to specific vm configuration. Closing
