### ISSUE TITLE
arbitration report Segmentation fault in some P3700

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#1446]
```
# ./examples/nvme/arbitration/arbitration -t 3 -i 0
Starting SPDK v20.07-pre git sha1 8ddecca / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: arb -c 0xf --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to 0000:5e:00.0
Attaching to 0000:d8:00.0
Attaching to 0000:d9:00.0
Attached to 0000:d9:00.0
Controller INTEL SSDPD2MD016T4  (CVEK6183000D2P0DGN  ): Skipping inactive NS 0
......
Controller INTEL SSDPD2MD016T4  (CVEK6183000D2P0DGN  ): Skipping inactive NS 0
Attached to 0000:d8:00.0
Controller INTEL SSDPE2KX040T8O (BTLJ848204F24P0DGN  ): Skipping inactive NS 0
......
Controller INTEL SSDPE2KX040T8O (BTLJ848204F24P0DGN  ): Skipping inactive NS 0
Attached to 0000:5e:00.0
Associating INTEL SSDPE2MD400G4  (CVFT7021008Y400PGN  ) with lcore 3
Associating INTEL SSDPE2KX040T8O (BTLJ848204F24P0DGN  ) with lcore 2
Associating INTEL SSDPD2MD016T4  (CVEK6183000D2P0DGN  ) with lcore 1
Associating INTEL SSDPE2MD400G4  (CVFT7021008Y400PGN  ) with lcore 0
./examples/nvme/arbitration/arbitration run with configuration:
./examples/nvme/arbitration/arbitration -q 64 -s 131072 -w randrw -M 50 -l 0 -t 3 -c 0xf -m 0 -a 0 -b 0 -n 100000 -i 0
Initialization complete. Launching workers.
Starting thread on core 3 with urgent priority queue
Starting thread on core 2 with urgent priority queue
Starting thread on core 1 with urgent priority queue
Starting thread on core 0 with urgent priority queue
[2020-06-18 18:48:05.342695] nvme_pcie.c:1839:nvme_pcie_prp_list_append: *ERROR*: vtophys(0x200001400000) failed
[2020-06-18 18:48:05.342928] nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: READ sqid:1 cid:886 nsid:1 lba:677610748 len:4
[2020-06-18 18:48:05.342980] nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:1 cid:886 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
[2020-06-18 18:48:05.343260] nvme_pcie.c:1839:nvme_pcie_prp_list_append: *ERROR*: vtophys(0x200001600000) failed
[2020-06-18 18:48:05.343300] nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:2 cid:884 nsid:1 lba:456804092 len:4
[2020-06-18 18:48:05.343316] nvme_qpair.c: 306:spdk_nvme_qpair_print_completion: *NOTICE*: INVALID FIELD (00/02) sqid:2 cid:884 cdw0:0 sqhd:0000 p:0 m:0 dnr:1
EAL: Error: Invalid memory
EAL: Error: Invalid memory
EAL: Error: Invalid memory
EAL: Error: Invalid memory
EAL: Error: Invalid memory
Segmentation fault

```
But no core dump file was creatd.

## Expected Behavior

arbitration run pass like below.
```
# ./examples/nvme/arbitration/arbitration -t 3 -i 0
Starting SPDK v20.07-pre git sha1 f20e375 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: arb -c 0xf --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x2000000000
EAL: No available hugepages reported in hugepages-1048576kB
Initializing NVMe Controllers
Attaching to 0000:03:00.0
Attaching to 0000:04:00.0
Attached to 0000:04:00.0
Attached to 0000:03:00.0
Associating INTEL SSDPEDMD800G4  (PHFT640100R3800CGN  ) with lcore 3
Associating INTEL SSDPEDMD800G4  (CVFT5352000Q800CGN  ) with lcore 2
Associating INTEL SSDPEDMD800G4  (PHFT640100R3800CGN  ) with lcore 1
Associating INTEL SSDPEDMD800G4  (CVFT5352000Q800CGN  ) with lcore 0
./examples/nvme/arbitration/arbitration run with configuration:
./examples/nvme/arbitration/arbitration -q 64 -s 131072 -w randrw -M 50 -l 0 -t 3 -c 0xf -m 0 -a 0 -b 0 -n 100000 -i 0
Initialization complete. Launching workers.
Starting thread on core 3 with urgent priority queue
Starting thread on core 2 with urgent priority queue
Starting thread on core 1 with urgent priority queue
Starting thread on core 0 with urgent priority queue
INTEL SSDPEDMD800G4  (PHFT640100R3800CGN  ) core 3: 14623.33 IO/s     6.84 secs/100000 ios
INTEL SSDPEDMD800G4  (CVFT5352000Q800CGN  ) core 2: 14669.33 IO/s     6.82 secs/100000 ios
INTEL SSDPEDMD800G4  (PHFT640100R3800CGN  ) core 1: 14513.67 IO/s     6.89 secs/100000 ios
INTEL SSDPEDMD800G4  (CVFT5352000Q800CGN  ) core 0: 14837.00 IO/s     6.74 secs/100000 ios
========================================================
```

## Current Behavior

arbitration run failed.

## Possible Solution

Need verify if these P3700s support  WRR.

## Steps to Reproduce

1. run ./examples/nvme/arbitration/arbitration -t 3 -i 0

## Context (Environment including OS version, SPDK version, etc.)

SPDK commit d5eb583584f63abf3a1dce2b70372f1cc09ab9a9

**Comment by changpe1** [comment]
The drive was formatted to extended LBA format, while the arbitration test still use spdk_nvme_ns_get_sector_size() to get the block size, not only arbitration test utility use this API, some other test utility also use this API when doing IOs.

Here is the fix patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/2934

**Comment by wanghailiangx** [comment]
@changpe1 Do you have any other patch?

**Comment by changpe1** [comment]
> @changpe1 Do you have any other patch?

No, please verify again, I don't see arbitration errors from the NVME and OPAL log.

**Comment by wanghailiangx** [comment]
When I insert a P3700 ssd, there is still errors.

```
************************************
START TEST nvme_arbitration
************************************
 01:39:28       # xtrace_enable
 01:39:28       # /home/storage/spdk-latest/build/examples/arbitration -t 3 -i 0
Starting SPDK v20.07-pre git sha1 d5eb583 / DPDK 19.11.0 initialization...
[ DPDK EAL parameters: arb -c 0xf --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
Initializing NVMe Controllers
Attached to 0000:d9:00.0
/home/storage/spdk-latest/test/common/autotest_common.sh: line 851: 111271 Segmentation fault      (core dumped) "$@"
......
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/storage/spdk-latest/build/examples/arbitration -t 3 -i 0'.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000422a19 in _nvme_ns_get_data (ns=0x2000f95f3d28) at nvme_ns.c:39
39              return &ns->ctrlr->nsdata[ns->id - 1];

Thread 6 (Thread 0x7ffff5181700 (LWP 111273)):
#0  0x00007ffff691bbad in recvmsg () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00000000004b6eed in read_msg (m=0x7ffff5180ae0, s=0x7ffff5180a70) at /home/storage/spdk-latest/dpdk/lib/librte_eal/common/eal_common_proc.c:279
        msglen = 0
        iov = {iov_base = 0x7ffff5180ae0, iov_len = 332}
        msgh = {msg_name = 0x7ffff5180a70, msg_namelen = 110, msg_iov = 0x7ffff5180a30, msg_iovlen = 1, msg_control = 0x7ffff51809c0, msg_controllen = 48, msg_flags = 0}
        control = '\000' <repeats 47 times>
        cmsg = 0x0
        buflen = 332
#2  0x00000000004b732c in mp_handle (arg=0x0) at /home/storage/spdk-latest/dpdk/lib/librte_eal/common/eal_common_proc.c:380
        msg = {type = 0, msg = {name = '\000' <repeats 63 times>, len_param = 0, num_fds = 0, param = '\000' <repeats 255 times>, fds = {0, 0, 0, 0, 0, 1, 0, 0}}}
        sa = {sun_family = 0, sun_path = '\000' <repeats 107 times>}
#3  0x00000000004b691e in rte_thread_init (arg=0x89a9e0) at /home/storage/spdk-latest/dpdk/lib/librte_eal/common/eal_common_thread.c:165
        ret = 0
        params = 0x89a9e0
        start_routine = 0x4b7301 <mp_handle>
        routine_arg = 0x0
#4  0x00007ffff6914ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007ffff663d8dd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 5 (Thread 0x7ffff5982700 (LWP 111272)):
#0  0x00007ffff663deb3 in epoll_wait () from /lib64/libc.so.6
No symbol table info available.
#1  0x00000000004a6749 in eal_intr_handle_interrupts (pfd=5, totalfds=2) at /home/storage/spdk-latest/dpdk/lib/librte_eal/linux/eal/eal_interrupts.c:1016
        events = {{events = 1, data = {ptr = 0x3, fd = 3, u32 = 3, u64 = 3}}, {events = 0, data = {ptr = 0x300000001, fd = 1, u32 = 1, u64 = 12884901889}}}
        nfds = 0
#2  0x00000000004a6928 in eal_intr_thread_main (arg=0x0) at /home/storage/spdk-latest/dpdk/lib/librte_eal/linux/eal/eal_interrupts.c:1100
        pipe_event = {events = 3, data = {ptr = 0x3, fd = 3, u32 = 3, u64 = 3}}
        src = 0x0
        numfds = 2
        pfd = 5
        ev = {events = 8211, data = {ptr = 0x6, fd = 6, u32 = 6, u64 = 6}}
        __func__ = "eal_intr_thread_main"
#3  0x00000000004b691e in rte_thread_init (arg=0x89a9e0) at /home/storage/spdk-latest/dpdk/lib/librte_eal/common/eal_common_thread.c:165
        ret = -1
        params = 0x89a9e0
        start_routine = 0x4a67aa <eal_intr_thread_main>
        routine_arg = 0x0
#4  0x00007ffff6914ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007ffff663d8dd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7ffff47fc700 (LWP 111274)):
#0  0x00007ffff691b75d in read () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000049d326 in eal_thread_loop (arg=0x0) at /home/storage/spdk-latest/dpdk/lib/librte_eal/linux/eal/eal_thread.c:133
        fct_arg = 0x0
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 1
        thread_id = 140737295402752
        m2s = 26
        s2m = 2077
        cpuset = "1", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#2  0x00007ffff6914ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007ffff663d8dd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7ffff37fa700 (LWP 111276)):
#0  0x00007ffff691b75d in read () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000049d326 in eal_thread_loop (arg=0x0) at /home/storage/spdk-latest/dpdk/lib/librte_eal/linux/eal/eal_thread.c:133
        fct_arg = 0x0
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 3
        thread_id = 140737278617344
        m2s = 2082
        s2m = 2085
        cpuset = "3", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#2  0x00007ffff6914ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007ffff663d8dd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7ffff3ffb700 (LWP 111275)):
#0  0x00007ffff691b75d in read () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x000000000049d326 in eal_thread_loop (arg=0x0) at /home/storage/spdk-latest/dpdk/lib/librte_eal/linux/eal/eal_thread.c:133
        fct_arg = 0x0
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 2
        thread_id = 140737287010048
        m2s = 2078
        s2m = 2081
        cpuset = "2", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#2  0x00007ffff6914ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007ffff663d8dd in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 1 (Thread 0x7ffff7fda9c0 (LWP 111271)):
#0  0x0000000000422a19 in _nvme_ns_get_data (ns=0x2000f95f3d28) at nvme_ns.c:39
No locals.
#1  0x00000000004235b2 in spdk_nvme_ns_get_num_sectors (ns=0x2000f95f3d28) at nvme_ns.c:249
No locals.
#2  0x00000000004235f4 in spdk_nvme_ns_get_size (ns=0x2000f95f3d28) at nvme_ns.c:255
No locals.
#3  0x00000000004051f2 in register_ns (ctrlr=0x2000f961f340, ns=0x2000f95f3d28) at arbitration.c:161
        entry = 0x17cd100
        cdata = 0x2000f961f930
#4  0x0000000000405860 in register_ctrlr (ctrlr=0x2000f961f340) at arbitration.c:256
        nsid = 2
        num_ns = 16
        ns = 0x2000f95f3d28
        entry = 0x8a29b0
        cap = {raw = 206997489663, bits = {mqes = 2047, cqr = 1, ams = 1, reserved1 = 0, to = 50, dstrd = 0, nssrs = 1, css = 1, bps = 0, reserved2 = 0, mpsmin = 0, mpsmax = 0, reserved3 = 0}}
        cdata = 0x2000f961f930
#5  0x0000000000407cb5 in attach_cb (cb_ctx=0x0, trid=0x2000f961f368, ctrlr=0x2000f961f340, opts=0x2000f9620958) at arbitration.c:874
No locals.
#6  0x0000000000432005 in nvme_probe_internal (probe_ctx=0x8a2550, direct_connect=false) at nvme.c:663
        rc = 0
        ctrlr = 0x2000f961f340
        ctrlr_tmp = 0x8a2550
        __func__ = "nvme_probe_internal"
#7  0x0000000000434954 in spdk_nvme_probe_async (trid=0x7fffffffd710, cb_ctx=0x0, probe_cb=0x407bd8 <probe_cb>, attach_cb=0x407c44 <attach_cb>, remove_cb=0x0) at nvme.c:1351
        rc = 0
        probe_ctx = 0x8a2550
#8  0x0000000000432220 in spdk_nvme_probe (trid=0x7fffffffd710, cb_ctx=0x0, probe_cb=0x407bd8 <probe_cb>, attach_cb=0x407c44 <attach_cb>, remove_cb=0x0) at nvme.c:704
        trid_pcie = {trstring = "PCIE", '\000' <repeats 28 times>, trtype = SPDK_NVME_TRANSPORT_PCIE, adrfam = 0, traddr = '\000' <repeats 256 times>, trsvcid = '\000' <repeats 32 times>, subnqn = '\000' <repeats 223 times>, priority = 0}
        probe_ctx = 0x0
        __func__ = "spdk_nvme_probe"
#9  0x0000000000407d20 in register_controllers () at arbitration.c:882
No locals.
#10 0x0000000000408812 in main (argc=5, argv=0x7fffffffdb38) at arbitration.c:1098
        rc = 0
        worker = 0x7fffffffd9e0
        master_worker = 0x4c7c59 <rte_cpu_get_flag_enabled+99>
        master_core = 0
        task_pool_name = "T\000\000\000\000\000\000\000\raV", '\000' <repeats 18 times>
        task_count = 82
        opts = {name = 0x566e05 "arb", core_mask = 0x5661d0 "0xf", shm_id = 0, mem_channel = -1, master_core = -1, mem_size = -1, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, num_pci_addr = 0, hugedir = 0x0, pci_blacklist = 0x0, pci_whitelist = 0x0, base_virtaddr = 35184372088832, env_context = 0x0}
        __PRETTY_FUNCTION__ = "main"
 01:39:28       # cp /home/storage/spdk-latest/build/examples/arbitration /home/storage/spdk-latest/../output
 01:39:28       # mv ./core.111271 /home/storage/spdk-latest/../output
 01:39:28       # chmod a+r /home/storage/spdk-latest/../output/./core.111271
 01:39:28       # ret=1
 01:39:28       # IFS=
 01:39:28       # read -r -d '' core
 01:39:28       # return 1

```

**Comment by changpe1** [comment]
@wanghailiangx P3700 only has one namespace, just wondering how the nsid=2 comes from.

**Comment by changpe1** [comment]
@wanghailiangx Can we close this issue now?

**Comment by wanghailiangx** [comment]
Issue is removed, now we can close it, thanks @changpe1 .
