### ISSUE TITLE
iscsi luns on lvols lead to errors from bdev_io_get_buf

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#1478]
Creating an iscsi lun on a lvol leads to a lot of noise from `spdk_tgt`.  This appears quite frequently:

```
bdev.c: 793:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
```

A read through #1406 makes me worry that this may be triggering heap corruption.  That is "fixed" but it seems the fix merely papers over a real problem.

## Expected Behavior

Use of default values in creating an lvstore, lvol, and iscsi target should be a happy path without frequent error messages.

## Current Behavior

`spdk_tgt` logs frequent error messages that give the impression there are serious problems.  With a tiny bit of testing, I have not seen bad side effects.  As I mentioned above, #1406 implies that there may be some heap corruption lurking.

## Possible Solution

If this is not really a serious error, alter the message to not say "ERROR".

If this happy path is something that should work better, consider this change:

```
diff --git a/lib/bdev/bdev.c b/lib/bdev/bdev.c
index ec4dd3f2d..1378f6d40 100644
--- a/lib/bdev/bdev.c
+++ b/lib/bdev/bdev.c
@@ -83,7 +83,7 @@ int __itt_init_ittlib(const char *, __itt_group_id);
 #define SPDK_BDEV_QOS_LIMIT_NOT_DEFINED                UINT64_MAX
 #define SPDK_BDEV_IO_POLL_INTERVAL_IN_MSEC     1000

-#define SPDK_BDEV_POOL_ALIGNMENT 512
+#define SPDK_BDEV_POOL_ALIGNMENT 4096

 static const char *qos_conf_type[] = {"Limit_IOPS",
                                      "Limit_BPS", "Limit_Read_BPS", "Limit_Write_BPS"
```

That change has been very lightly tested but does seem to alleviate the problem.

## Steps to Reproduce

In one window:

```
# /opt/spdk/bin/spdk_tgt
```

In another:

```
[root@ws1 spdk]# rpc bdev_lvol_get_lvstores
[
  {
    "uuid": "f414bed1-279f-4db3-831b-dcdd9fabc7d7",
    "name": "lvs1",
    "base_bdev": "aio1",
    "total_data_clusters": 511,
    "free_clusters": 501,
    "block_size": 4096,
    "cluster_size": 4194304
  }
]
[root@ws1 spdk]# rpc bdev_lvol_create -l lvs1 bug 100
4c426020-487a-4b2a-9de0-40afe2e1c233
[root@ws1 spdk]# rpc iscsi_create_portal_group 1 127.0.0.1:3260
[root@ws1 spdk]# rpc iscsi_create_initiator_group 2 ANY 127.0.0.1/32
[root@ws1 spdk]# rpc iscsi_create_target_node bug bug_alias lvs1/bug:0 1:2 64 -d
[root@ws1 spdk]# iscsiadm -m node --logout
...
[root@ws1 spdk]# iscsiadm --mode discoverydb --type sendtargets --portal 127.0.0.1 --discover
127.0.0.1:3260,1 iqn.2016-06.io.spdk:bug
[root@ws1 spdk]# iscsiadm -m node --login
Logging in to [iface: default, target: iqn.2016-06.io.spdk:bug, portal: 127.0.0.1,3260]
Login to [iface: default, target: iqn.2016-06.io.spdk:bug, portal: 127.0.0.1,3260] successful.
```

In response to the login I see:

```
[2020-07-07 11:11:43.730795] bdev.c: 793:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2020-07-07 11:11:43.735890] bdev.c: 793:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2020-07-07 11:11:43.735912] bdev.c: 793:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2020-07-07 11:11:43.735918] bdev.c: 793:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2020-07-07 11:11:43.748609] bdev.c: 793:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
[2020-07-07 11:11:43.752601] bdev.c: 793:bdev_io_get_buf: *ERROR*: Length + alignment 69632 is larger than allowed
```

Note that the error message can be a bit misleading as `md_len` (0 in this case) was not added to the error message in commit ca99028730e4bfb62633220a15296b36c009263a.

## Context (Environment including OS version, SPDK version, etc.)

Running on CentOS 8, origin/master at commit 6366e361fe33a63a7dda712fb415640fa6d3ba16.

**Comment by changpe1** [comment]
[Bug Scrub] @liang2yan could you try to reproduce this issue ?

**Comment by liang2yan** [comment]
I reproduced this issue with specified commit and master branch. the iscsi target reported same error. moreover, if I add "-L bdev" argument(need to enable debug in configuration), the iscsi target will crash. the core dump info is as below:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./build/bin/iscsi_tgt -L bdev'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50        return ret;
[Current thread is 1 (Thread 0x7f90135a1380 (LWP 1951832))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f90135e1895 in __GI_abort () at abort.c:79
#2  0x00007f90135e1769 in __assert_fail_base (
    fmt=0x7f901374f0b8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x613e70 "bdev_ch->io_outstanding > 0", file=0x61312a "bdev.c", line=4913,
    function=<optimized out>) at assert.c:92
#3  0x00007f90135f0e86 in __GI___assert_fail (assertion=0x613e70 "bdev_ch->io_outstanding > 0",
    file=0x61312a "bdev.c", line=4913,
    function=0x614d90 <__PRETTY_FUNCTION__.30> "spdk_bdev_io_complete") at assert.c:101
#4  0x00000000004bdf32 in spdk_bdev_io_complete (bdev_io=0x200006d12940,
    status=SPDK_BDEV_IO_STATUS_SUCCESS) at bdev.c:4913
#5  0x000000000041c59b in lvol_op_comp (cb_arg=0x200006d12940, bserrno=0) at vbdev_lvol.c:763
#6  0x0000000000447c11 in bs_call_cpl (cpl=0x7fff8b238d90, bserrno=0) at request.c:58
#7  0x0000000000447d3f in bs_request_set_complete (set=0x2bf2840) at request.c:90
#8  0x00000000004484c1 in bs_sequence_finish (seq=0x2bf2840, bserrno=0) at request.c:256
#9  0x000000000043c48d in rw_iov_done (seq=0x2bf2840, cb_arg=0x0, bserrno=0) at blobstore.c:2634
#10 0x0000000000447d87 in bs_sequence_completion (channel=0x2bc5820, cb_arg=0x2bf2840, bserrno=0)
    at request.c:99
#11 0x0000000000434ff4 in bdev_blob_io_complete (bdev_io=0x200006d12380, success=true, arg=0x2bf2870)
    at blob_bdev.c:86
#12 0x00000000004bdc81 in bdev_io_complete (ctx=0x200006d12380) at bdev.c:4848
#13 0x00000000004be097 in spdk_bdev_io_complete (bdev_io=0x200006d12380,
    status=SPDK_BDEV_IO_STATUS_SUCCESS) at bdev.c:4936
#14 0x0000000000491bc6 in bdev_aio_group_poll (arg=0x2bc5bd0) at bdev_aio.c:337
#15 0x00000000004f429e in thread_poll (thread=0x2bc25c0, max_msgs=0, now=1123606693082100)
--Type <RET> for more, q to quit, c to continue without paging--c
    at thread.c:602
#16 0x00000000004f46eb in spdk_thread_poll (thread=0x2bc25c0, max_msgs=0, now=1123606693082100) at thread.c:689
#17 0x00000000004a7126 in _reactor_run (reactor=0x2bc0300) at reactor.c:326
#18 0x00000000004a7238 in reactor_run (arg=0x2bc0300) at reactor.c:382
#19 0x00000000004a764f in spdk_reactors_start () at reactor.c:477
#20 0x00000000004a55bc in spdk_app_start (opts=0x7fff8b23a4b0, start_fn=0x4067fc <spdk_startup>, arg1=0x0) at app.c:688
#21 0x0000000000406990 in main (argc=3, argv=0x7fff8b23a668) at iscsi_tgt.c:112
(gdb) quit
```

**Comment by changpe1** [comment]
I can also reproduce in my local, I'm debugging this issue now.

**Comment by changpe1** [comment]
I pushed a fix patch for this issue https://review.spdk.io/gerrit/c/spdk/spdk/+/3495.

**Comment by changpe1** [comment]
@mgerdts patch has been merged, instead of adjusting the SPDK_BDEV_POOL_ALIGNMENT value in bdev layer, I adjusted the data alignment in AIO bdev layer, the issue already fixed in my local, closing this patch for now, you can reopen it if it still exist in your environment.
