### ISSUE TITLE
[IOAT]  IOAT failure on start and cause segment fault when the application shutdown.

### ISSUE THREAD

**Issue by optimistyzy** [spdk/spdk#1534]
If we start application with IOAT several times (under some workloads). And after some times, we cannot restart the application with IOAT device, then we shutdown the application, we will see the segment fault.

## Current Behavior

IOAT start failure and if we shut down the application, we will have segement fault. Current the solution is to reset the machine. But I want to say, there is no issue before 20.04 release. 

For example, If you start an nvmf tgt application with the following configuration file.

[Global]

[Bdev]

[Malloc]
  NumberOfLuns 1
  LunSizeInMB 512

[Split]
      Split Malloc0 8

[Ioat]
Enable Yes

[Nvmf]
  AcceptorPollRate 10000

[Transport]
  Type TCP
  InCapsuleDataSize 4096
  NumSharedBuffers 2048
[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  #Listen TCP 10.67.111.25:4420
  Listen TCP 127.0.0.1:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  #Namespace Nvme0n1 1
  Namespace Malloc0p0
  Namespace Malloc0p1
  Namespace Malloc0p2
  Namespace Malloc0p3
  Namespace Malloc0p4
  Namespace Malloc0p5
  Namespace Malloc0p6
  Namespace Malloc0p7

you will see the following. 

./build/bin/nvmf_tgt -c tcp_split.conf -m 0x10000
[2020-08-06 22:45:35.932145] conf.c: 626:spdk_conf_read: *ERROR*: INI configuration has been deprecated and will be removed in a future release. Please switch to JSON-RPC.
Starting SPDK v20.10-pre git sha1 a63c4b5cd / DPDK 20.05.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x10000 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid3752 ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2020-08-06 22:45:36.014897] app.c: 666:spdk_app_start: *NOTICE*: Total cores available: 1
[2020-08-06 22:45:36.143765] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 16
[2020-08-06 22:45:36.143848] accel_engine.c: 509:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2020-08-06 22:45:36.195921] ioat.c: 277:ioat_reset_hw: *ERROR*: timed out waiting for suspend
[2020-08-06 22:45:36.205985] ioat.c: 487:ioat_channel_start: *ERROR*: could not start channel: status = 0x403600000
 error = 0x100
[2020-08-06 22:45:36.206273] ioat.c: 555:ioat_enum_cb: *ERROR*: ioat_attach() failed
EAL: Requested device 0000:00:04.1 cannot be used
[2020-08-06 22:45:36.239674] accel_engine_ioat.c: 701:accel_engine_ioat_init: *NOTICE*: Accel engine updated to use IOAT engine.
[2020-08-06 22:45:36.477270] tcp.c: 469:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2020-08-06 22:45:36.525541] conf.c: 351:nvmf_parse_subsystem: *NOTICE*: Subsystem nqn.2016-06.io.spdk:cnode1: missing model number, will use default
[2020-08-06 22:45:36.525835] tcp.c: 650:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 10.67.111.25 port 4420 ***

And if you shutdown the application, you will see the coredump:

warning: Unexpected size of section `.reg-xstate/3711' in core file.
#0  0x00007f8fa27c01c5 in __strlen_avx2 () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f8fa25a6700 (LWP 3711))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-29.fc30.x86_64 libaio-0.3.111-4.fc30.x86_64 libibverbs-20.1-3.fc30.x86_64 libnl3-3.4.0-8.fc30.x86_64 librdmacm-20.1-3.fc30.x86_64 libuuid-2.33.2-2.fc30.x86_64 numactl-libs-2.0.12-2.fc30.x86_64 openssl-libs-1.1.1g-1.fc30.x86_64 zlib-1.2.11-19.fc30.x86_64
(gdb) bt
#0  0x00007f8fa27c01c5 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00007f8fa26cca1e in __vfprintf_internal () from /lib64/libc.so.6
#2  0x00007f8fa26de2ca in __vsnprintf_internal () from /lib64/libc.so.6
#3  0x00007f8fa26b7446 in snprintf () from /lib64/libc.so.6
#4  0x00000000004cbbff in snprintf (__fmt=0x5571b9 "%s", __n=32, __s=0x7f8fa25a5a00 "") at /usr/include/bits/stdio2.h:67
#5  remove_rte_dev (rte_dev=<optimized out>) at pci.c:107
#6  0x00000000004e7000 in eal_alarm_callback ()
#7  0x00000000004e939a in eal_intr_thread_main ()
#8  0x00007f8fa28324c0 in start_thread () from /lib64/libpthread.so.0
#9  0x00007f8fa2760133 in clone () from /lib64/libc.so.6
(gdb)

The error is located in pci.c line: 107.

## Possible Solution

1 Restart the machine. //But I want to express previously there is no such issue. I think whether this happens because one time the application does not correctly shutdown, then the IOAT device is not recycled.
2  Even we face such condition, there is still a question, why there is failure when shutting down the application.

## Steps to Reproduce

1. When the NVMe-oF application does not correctly shutdown. Then restart the application with the configuration attached.
2. Then kill the nvme-of application, then you see the coredump.
3.
4.

**Comment by optimistyzy** [comment]
@peluse  I think that someone may report this issue on the mailing list, and you suggest restarting the machine, it solves the problem. But I think that there may be still some issues with our software (may be in SPDK or DPDK), previously we do not have this issue (Because I use ioat on malloc bdev on NVMe-oF TCP target test). I did not see this issue before 20.04. So we may need dig more.

**Comment by optimistyzy** [comment]
@darsto I remembered that you changed the PCI device management part code. Is this issue related with this?  Thanks.

**Comment by peluse** [comment]
@optimistyzy  So the mailing list issue was different, it was an issue in the community member's code that actually required a hard reset to recover IOAT, that was resolved. 

@darsto not sure if you were talking to me but I did make this change back in Feb https://review.spdk.io/gerrit/c/spdk/spdk/+/839 and AFAIK that's really the only thing that has changed in IOAT that would be worth looking into. I can try to repo on this end but @optimistyzy as you're already set to repro this can you look at that smal change and back it out on your test system and see if has an impact?

**Comment by optimistyzy** [comment]
@peluse Let me download the patch since my reported issue will happen after an unexpected application shutdown with IOAT. So it need some time to see whether it will be helpful.

**Comment by optimistyzy** [comment]
Close this issue since I am not seeing the similar issue on the master those days! Will reopen it if see this again.
