### ISSUE TITLE
vhost target crashed  after input a wrong vhost_scsi_controller_add_target command

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1575]
# Issue

```
./build/bin/vhost -S /var/tmp -m 0xF00000
Starting SPDK v20.10-pre git sha1 2b16cfff9 / DPDK 19.11.2 initialization...
[ DPDK EAL parameters: vhost --no-shconf -c 0xF00000 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid1613 ]
EAL: No available hugepages reported in hugepages-1048576kB
[2020-08-26 07:46:35.420398] app.c: 665:spdk_app_start: *NOTICE*: Total cores available: 4
[2020-08-26 07:46:35.573055] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 21
[2020-08-26 07:46:35.573975] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 22
[2020-08-26 07:46:35.574852] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 23
[2020-08-26 07:46:35.575657] reactor.c: 371:reactor_run: *NOTICE*: Reactor started on core 20
[2020-08-26 07:46:35.575726] accel_engine.c: 500:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2020-08-26 07:46:50.454396] bdev_rbd.c: 710:bdev_rbd_create: *NOTICE*: Add Ceph0 rbd disk to lun
[2020-08-26 07:47:00.109944] vhost_scsi.c: 799:to_scsi_dev: *ERROR*: vhost0: not a vhost-scsi device.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1613==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000a8 (pc 0x559c50513d5b bp 0x0fffd6568546 sp 0x7ffeb2b42a08 T0)
==1613==The signal is caused by a WRITE memory access.
==1613==Hint: address points to the zero page.
    #0 0x559c50513d5a in spdk_vhost_scsi_dev_add_tgt /home/storage/spdkdevcodes/spdk/lib/vhost/vhost_scsi.c:1034
    #1 0x559c5050e656 in rpc_vhost_scsi_controller_add_target /home/storage/spdkdevcodes/spdk/lib/vhost/vhost_rpc.c:145
    #2 0x559c5052502b in parse_single_request /home/storage/spdkdevcodes/spdk/lib/jsonrpc/jsonrpc_server.c:103
    #3 0x559c5052502b in jsonrpc_parse_request /home/storage/spdkdevcodes/spdk/lib/jsonrpc/jsonrpc_server.c:233
    #4 0x559c505266cb in jsonrpc_server_conn_recv /home/storage/spdkdevcodes/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:315
    #5 0x559c505266cb in spdk_jsonrpc_server_poll /home/storage/spdkdevcodes/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:433
    #6 0x559c50521fc8 in rpc_subsystem_poll /home/storage/spdkdevcodes/spdk/lib/event/rpc.c:51
    #7 0x559c5056c920 in thread_poll /home/storage/spdkdevcodes/spdk/lib/thread/thread.c:646
    #8 0x559c5056c920 in spdk_thread_poll /home/storage/spdkdevcodes/spdk/lib/thread/thread.c:689
    #9 0x559c50520e2a in _reactor_run /home/storage/spdkdevcodes/spdk/lib/event/reactor.c:326
    #10 0x559c50520e2a in reactor_run /home/storage/spdkdevcodes/spdk/lib/event/reactor.c:382
    #11 0x559c50521ceb in spdk_reactors_start /home/storage/spdkdevcodes/spdk/lib/event/reactor.c:477
    #12 0x559c5051e082 in spdk_app_start /home/storage/spdkdevcodes/spdk/lib/event/app.c:709
    #13 0x559c503e9b78 in main /home/storage/spdkdevcodes/spdk/app/vhost/vhost.c:106
    #14 0x7f45947b0b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #15 0x559c503ee8c9 in _start (/home/storage/spdkdevcodes/spdk/build/bin/vhost+0x908c9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/storage/spdkdevcodes/spdk/lib/vhost/vhost_scsi.c:1034 in spdk_vhost_scsi_dev_add_tgt
==1613==ABORTING
```

## Steps to Reproduce

```
./configure --with-rbd --without-isal --enable-asan
ceph osd pool create rbd 8
ceph osd pool create testpool 8
rbd pool init pool testpool
rbd create testpool/imagetest --size 50G --image-format 2 --image-feature layering
```
start a target:
```
./build/bin/vhost -S /var/tmp -m 0xF00000 
./scripts/rpc.py bdev_rbd_create testpool imagetest 512
./scripts/rpc.py vhost_create_blk_controller vhost0 --cpumask 0xF00000 Ceph0
./scripts/rpc.py vhost_scsi_controller_add_target vhost0 1 Ceph0 ( input a wrong command
 )

```
## Context (Environment including OS version, SPDK version, etc.)

uname -a : 4.15.0-112-generic #113-Ubuntu SMP Thu Jul
commit: 2b16cfff9e56ebe5da4f850e26af4ba60dfe54aa

**Comment by yidong0635** [comment]
try to add fix here：
https://review.spdk.io/gerrit/c/spdk/spdk/+/3951

**Comment by yidong0635** [comment]
Patch was merged, close this issue.
