### ISSUE TITLE
[autobuild] "make" test failed due to missing mesonbuild python module

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#1579]
https://ci.spdk.io/results/autotest-per-patch/builds/25041/archive/BlobFS-autotest/build.log

Point of failure:
```
00:00:32.075  START TEST make
00:00:32.075  ************************************
00:00:32.076   13:11:49	$ xtrace_enable
00:00:32.076   13:11:49	$ make -j16
00:00:32.316  Traceback (most recent call last):
00:00:32.316    File "/usr/local/bin/meson", line 6, in <module>
00:00:32.316      from mesonbuild.mesonmain import main
00:00:32.316  ModuleNotFoundError: No module named 'mesonbuild'
00:00:32.324  make[1]: *** [Makefile:149: /var/jenkins/workspace/BlobFS-autotest/spdk/dpdk/build-tmp] Error 1
00:00:32.325  make: *** [/var/jenkins/workspace/BlobFS-autotest/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
00:00:32.325    13:11:49	$ trap - ERR
00:00:32.325    13:11:49	$ print_backtrace
00:00:32.326    13:11:49	$ [[ ehxBET =~ e ]]
00:00:32.326    13:11:49	$ args=("${BASH_ARGV[@]}")
00:00:32.326    13:11:49	$ local args
00:00:32.326    13:11:49	$ xtrace_disable
00:00:32.326    13:11:49	$ '[' no '!=' yes ']'
00:00:32.326    13:11:49	$ PREV_BASH_OPTS=ehxBET
00:00:32.326    13:11:49	$ [[ ehxBET == *\x* ]]
00:00:32.326    13:11:49	$ XTRACE_DISABLED=yes
00:00:32.326    13:11:49	$ set +x
00:00:32.326  ========== Backtrace start: ==========
00:00:32.326  
00:00:32.337  in /var/jenkins/workspace/BlobFS-autotest/spdk/test/common/autotest_common.sh:922 -> run_test(["make"],["make"],["-j16"])
00:00:32.337       ...
00:00:32.337     917 		timing_enter $test_name
00:00:32.337     918 		echo "************************************"
00:00:32.337     919 		echo "START TEST $test_name"
00:00:32.337     920 		echo "************************************"
00:00:32.337     921 		xtrace_restore
00:00:32.337  => 922 		time "$@"
00:00:32.337     923 		xtrace_disable
00:00:32.337     924 		echo "************************************"
00:00:32.337     925 		echo "END TEST $test_name"
00:00:32.337     926 		echo "************************************"
00:00:32.337     927 		timing_exit $test_name
00:00:32.337       ...
00:00:32.343  in /var/jenkins/workspace/BlobFS-autotest/spdk/autobuild.sh:188 -> main(["/home/sys_sgci/autorun-spdk.conf"])
00:00:32.343       ...
00:00:32.343     183 		if [ "$SPDK_TEST_OCF" -eq 1 ]; then
00:00:32.343     184 			run_test "autobuild_ocf_precompile" ocf_precompile
00:00:32.343     185 		fi
00:00:32.343     186 		# if we aren't testing the unittests, build with shared objects.
00:00:32.343     187 		./configure $config_params --with-shared
00:00:32.343  => 188 		run_test "make" $MAKE $MAKEFLAGS
00:00:32.343     189 	fi
00:00:32.343       ...
00:00:32.343  
00:00:32.343  ========== Backtrace end ==========
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25041.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_25044.html

**Comment by karlatec** [comment]
GP1 has meson installed:
```
[sys_sgci@GrizzlyPass1 ~]$ pip list installed | grep meson
meson             0.55.1
```

I see that pip is a symlink to pip3, so there's no pip for python2, which doesn't have meson installed:
```
[sys_sgci@GrizzlyPass1 ~]$ python
Python 3.8.5 (default, Aug 12 2020, 00:00:00)
[GCC 10.2.1 20200723 (Red Hat 10.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mesonbuild
>>>
[sys_sgci@GrizzlyPass1 ~]$ python2
Python 2.7.18 (default, Jul 20 2020, 00:00:00)
[GCC 10.1.1 20200507 (Red Hat 10.1.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> import mesonbuild
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mesonbuild
```

Any chance that this error is a result of using Python2 instead of Python3?

**Comment by mikeBashStuff** [comment]
`meson` explicitly execs `python3` so that would be unlikely I think.

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue occurred in just two builds linked above, and then never again. There was no changes done on CI to resolve it. Let's close it.
