### ISSUE TITLE
nvmf: race condition between _nvmf_ctrlr_destruct and nvmf_ctrlr_association_remove

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#1635]
A long running hot plug test where the drive is under IO failed with the following core:

```
#3  <signal handler called>
#4  0x000000000054df84 in nvmf_transport_qpair_fini ()
#5  0x00000000005498d5 in spdk_nvmf_qpair_disconnect ()
#6  0x000000000053f31f in nvmf_ctrlr_association_remove ()
#7  0x000000000055da87 in spdk_thread_poll ()
#8  0x000000000050e608 in reactor_run ()
#9  0x00000000004211f5 in eal_thread_loop.cold ()
#10 0x00007fc56c6072de in start_thread () from /lib64/libpthread.so.0
#11 0x00007fc56b415a63 in clone () from /lib64/libc.so.6
```

I also get the following log output:
```
2020-10-18 17:54:32.978 PDT {15725} I {nvmf_tgt} bdev_nvme.c:1532:attach_cb Attached to 0000:c2:00.0 (HotInNvme2766)
// Scan Adding HotInNvme2766n1 to subsystem nqn.2019-20.com.hpe:51402ec01492a82f.0.bay00
2020-10-18 17:54:35.628 PDT {15725} I {nvmf_tgt} subsystem.c:426:nvmf_subsystem_set_state nvgrid: subsystem->state=3 actual_old_state=2, expected=2
2020-10-18 17:54:35.805 PDT {15725} I {nvmf_tgt} subsystem.c:426:nvmf_subsystem_set_state nvgrid: subsystem->state=4 actual_old_state=3, expected=3
2020-10-18 17:54:35.805 PDT {15725} I {nvmf_tgt} subsystem.c:426:nvmf_subsystem_set_state nvgrid: subsystem->state=5 actual_old_state=4, expected=4
2020-10-18 17:54:36.113 PDT {15725} I {nvmf_tgt} ctrlr.c:2661:nvmf_ctrlr_async_event_notification !!! AEN sent: subnqn=nqn.2019-20.com.xxx:X.0.Y, event: type=0002, info=0000, log page id=0004

2020-10-18 17:54:36.113 PDT {15725} E {nvmf_tgt} ctrlr.c:934:nvmf_prop_set_cc Prop Set CC toggled reserved bits 0x2!
2020-10-18 17:54:36.113 PDT {15725} E {nvmf_tgt} ctrlr.c:1177:nvmf_property_set prop set_cb failed
2020-10-18 17:54:36.289 PDT {15725} I {nvmf_tgt} subsystem.c:426:nvmf_subsystem_set_state nvgrid: subsystem->state=2 actual_old_state=5, expected=5

// The message below was added by me
2020-10-18 17:54:36.378 PDT {15725} I {nvmf_tgt} ctrlr.c:431:_nvmf_ctrlr_destruct Disconnect: cntlid: 0x0159  subnqn: "nqn.2019-20.com.xxx:X.0.Y"  hostnqn: "2014-08.org.nvmexpress:uuid:55f9af2a-f638-4e04-bd0a-dd5c424ebb45"

2020-10-18 17:54:36.409 PDT {15725} I {nvmf_tgt} ctrlr.c:771:nvmf_ctrlr_association_remove !!! Disconnecting host from subsystem nqn.2019-20.com.xxx:X.0.Ydue to association timeout [ctrlr->admin_qpair=0x7fc564cb52d0]
```

From looking at the above log output, it seems that the ctrlr structure is already freed in _nvmf_ctrlr_destruct when nvmf_ctrlr_association_remove poller task is called. However, _nvmf_ctrlr_destruct does stop the poller for nvmf_ctrlr_association_remove . So it's not clear to me how we can get into this situation. I'm pretty sure that the ctrlr is the same in _nvmf_ctrlr_destruct and nvmf_ctrlr_association_remove but I'd have to log the ctrlr address to be sure.

Note, this may not even be an issue related to hot plug but initiators connecting/disconnecting.

The message from nvmf_ctrlr_association_remove is called when I run IO on the **same** system where the target is running. This message doesn't seem to be generated when running IO **remotely**.

I also wonder if the failure in nvmf_prop_set_cc is indicating a corruption.

## Steps to Reproduce

I can reproduce the above signature where _nvmf_ctrlr_destruct is called first and then nvmf_ctrlr_association_remove when I fail the nvmf_prop_set_cc:
```
	if (diff.bits.shn) {
		if (cc.bits.shn == SPDK_NVME_SHN_NORMAL ||
		    cc.bits.shn == SPDK_NVME_SHN_ABRUPT) {
			SPDK_DEBUGLOG(SPDK_LOG_NVMF, "Property Set CC Shutdown %u%ub!\n",
				      cc.bits.shn >> 1, cc.bits.shn & 1);
			ctrlr->vcprop.cc.bits.shn = cc.bits.shn;
#ifdef NVGRID_ONLY
			SPDK_NOTICELOG("!!! Property Set CC Shutdown cc.bits.shn=%d, [ctrlr=%p]\n", cc.bits.shn, ctrlr);
#endif
			spdk_for_each_channel(ctrlr->subsys->tgt,
					      nvmf_ctrlr_disconnect_io_qpairs_on_pg,
					      ctrlr,
					      nvmf_ctrlr_cc_shn_done);

			/* From the time a shutdown is initiated the controller shall disable
			 * Keep Alive timer */
			nvmf_ctrlr_stop_keep_alive_timer(ctrlr);
			// mhae testing
			diff.raw = 1;
```

It's unclear to me how this can happen, since we unregister the poller in _nvmf_ctrlr_destruct. I can also reproduce the core dump that way (access to freed ctrlr).

## Context (Environment including OS version, SPDK version, etc.)
CentOS 8.2, SPDK 20.07

**Comment by benlwalker** [comment]
I don't consider this patch a full "fix", but it probably does make it impossible to reproduce the bug: https://review.spdk.io/gerrit/c/spdk/spdk/+/4814

**Comment by mhae** [comment]
Had some more instances of this issue and it seems unrelated to the toggle in the reserved CC bits.

**Comment by mhae** [comment]
I think the issue is that we're overwriting the assoc poller when we get a CC disable & shutdown:

```
2020-10-27 08:16:40.341 PDT {31910} I {nvmf_tgt_app} ctrlr.c:891:nvmf_prop_set_cc !!! Property Set CC Disable [ctrlr=0x7f480cb68d40]
2020-10-27 08:16:40.341 PDT {31910} I {nvmf_tgt_app} ctrlr.c:909:nvmf_prop_set_cc !!! Property Set CC Shutdown cc.bits.shn=1, [ctrlr=0x7f480cb68d40]
2020-10-27 08:16:40.341 PDT {31910} E {nvmf_tgt_app} ctrlr.c:960:nvmf_prop_set_cc Prop Set CC toggled reserved bits 0x2!
2020-10-27 08:16:40.341 PDT {31910} E {nvmf_tgt_app} ctrlr.c:962:nvmf_prop_set_cc cur CC: 0x00044000, r1=0x0, r2=0x0
2020-10-27 08:16:40.341 PDT {31910} E {nvmf_tgt_app} ctrlr.c:963:nvmf_prop_set_cc new CC: 0x00044002, r1=0x1, r2=0x0

...

2020-10-27 08:16:40.430 PDT {31910} I {nvmf_tgt_app} ctrlr.c:837:nvmf_ctrlr_cc_reset_done !!! timer set: [ctrlr=0x7f480cb68d40] ctrlr->association_timer=0x7f480cb266f0

2020-10-27 08:16:40.430 PDT {31910} I {nvmf_tgt_app} ctrlr.c:803:nvmf_ctrlr_cc_shn_done ???????????? ctrlr->association_timer still set: [ctrlr=0x7f480cb68d40] ctrlr->association_timer=0x7f480cb266f0
2020-10-27 08:16:40.430 PDT {31910} I {nvmf_tgt_app} ctrlr.c:809:nvmf_ctrlr_cc_shn_done !!! timer set: [ctrlr=0x7f480cb68d40] ctrlr->association_timer=0x7f480cb51bb0
```

**Comment by mhae** [comment]
There is a fix (https://review.spdk.io/gerrit/c/spdk/spdk/+/4935) for this condition. Although it seems more like a corruption of the CC register that seems to be maintained by the NVMF target, the code as written can trigger setting the assoc timer twice when both CC.en and CC.shn are set. The fix at least gets rid of the double triggering of the assoc timer that can result in access to freed memory.

**Comment by jimharris** [comment]
Nice analysis and root cause @mhae.  I posted some comments on your patch.  We should get this in for the 20.10 release this week.
