### ISSUE TITLE
[VM-host-WFP1/Vagrant] Initialization parameters must be an attributes hash, got NilClass nil

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1666]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/29848/archive/unittest-vg-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/29844/archive/ubuntu16-vg-autotest/build.log

## Execution failed at

```
00:06:17.329  /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/collection.rb:87:in `new': Initialization parameters must be an attributes hash, got NilClass nil (ArgumentError)
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `block in load'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `each'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `load'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-libvirt-0.7.0/lib/fog/libvirt/models/compute/volumes.rb:11:in `all'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-libvirt-0.7.0/lib/fog/libvirt/models/compute/server.rb:140:in `block in volumes'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-libvirt-0.7.0/lib/fog/libvirt/models/compute/server.rb:140:in `map'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-libvirt-0.7.0/lib/fog/libvirt/models/compute/server.rb:140:in `volumes'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/fog-libvirt-0.7.0/lib/fog/libvirt/models/compute/server.rb:91:in `destroy'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/destroy_domain.rb:47:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/forward_ports.rb:197:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:53:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/call.rb:53:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-sshfs-1.3.4/lib/vagrant-sshfs/action_hostpath_fixup.rb:125:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /var/lib/libvirt/images/.vagrant.d/gems/2.4.4/gems/vagrant-sshfs-1.3.4/lib/vagrant-sshfs/action_hostpath_fixup.rb:102:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:238:in `action_raw'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:209:in `block in action'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:615:in `lock'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `call'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `action'
00:06:17.329  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
00:06:17.359  Build step 'Execute shell' marked build as failure
00:06:17.424  [PostBuildScript] - [INFO] Executing post build scripts.
00:06:17.430  [ubuntu16-vg-autotest] $ /usr/bin/env bash /tmp/jenkins6401092023299890545.sh
00:06:17.434  + [[ -n ubuntu1604 ]]
00:06:17.434  + mv /var/jenkins/workspace/ubuntu16-vg-autotest/ubuntu1604-libvirt/output /var/jenkins/workspace/ubuntu16-vg-autotest/output
00:06:17.452  [ubuntu16-vg-autotest] $ /usr/bin/env bash /tmp/jenkins9144978273990414196.sh
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_29848.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_29844.html

**Comment by mikeBashStuff** [comment]
Usually, vagrant fails like so when VM's storage (i.e. the disk|snapshot image) suddenly goes away, i.e. is manually removed. I don't think this was indeed the case here, however, the common mitigation is to restart `libvirtd` daemon when it happens. I did that and cleaned up unused storage pools `libvirtd` was complaining about, including some lingering config files for non existing VM domains.

WFP1 seems to fine now so closing this issue for now. Please, reopen if it pops again on the CI.

**Comment by tomzawadzki** [comment]
This has happened on following build https://ci.spdk.io/public_build/autotest-per-patch_96647.html
Patch https://review.spdk.io/gerrit/c/spdk/dpdk/+/16443

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_100157.html

**Comment by ksztyber** [comment]
[Bug scrub] @mikeBashStuff has patches to the CI repo that should fix it. After merging, we can close this one.

**Comment by mikeBashStuff** [comment]
Patches got merged couple of weeks back, closing.
