### ISSUE TITLE
[VM-host-PE1/Vagrant] No space left on device

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#1667]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/29836/archive/unittest-vg-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/29839/archive/unittest-vg-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/29842/archive/unittest-vg-autotest/build.log
https://ci.spdk.io/results/autotest-per-patch/builds/29841/archive/unittest-vg-autotest/build.log

## Execution failed at
```
00:00:28.864  mkdir: created directory '/var/jenkins/workspace/unittest-vg-autotest/fedora31-libvirt'
00:00:28.866  /var/jenkins/workspace/unittest-vg-autotest/fedora31-libvirt /var/jenkins/workspace/unittest-vg-autotest
00:00:29.662  /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `close': No space left on device @ fptr_finalize_flush - /var/lib/libvirt/images/.vagrant.d/perm_test_EWDYNDZZPAQHGWNVRREYBWXNSLKKMXAD (Errno::ENOSPC)
00:00:29.662  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `open'
00:00:29.662  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `open'
00:00:29.662  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `setup_home_path'
00:00:29.662  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:135:in `initialize'
00:00:29.662  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `new'
00:00:29.662  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `<main>'
00:00:29.668  + cd fedora31-libvirt
00:00:29.668  + vagrant destroy -f
00:00:30.482  /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `close': No space left on device @ fptr_finalize_flush - /var/lib/libvirt/images/.vagrant.d/perm_test_ITWUDEXRNOPSAOVMWDMRSBLREERANWJY (Errno::ENOSPC)
00:00:30.482  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `open'
00:00:30.482  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `open'
00:00:30.482  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:837:in `setup_home_path'
00:00:30.482  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:135:in `initialize'
00:00:30.482  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `new'
00:00:30.482  	from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/bin/vagrant:145:in `<main>'
00:00:30.498  Build step 'Execute shell' marked build as failure
00:00:30.539  [PostBuildScript] - [INFO] Executing post build scripts.
00:00:30.545  [unittest-vg-autotest] $ /usr/bin/env bash /tmp/jenkins3731512272975283072.sh
00:00:30.549  + [[ -n fedora31 ]]
00:00:30.550  + mv /var/jenkins/workspace/unittest-vg-autotest/fedora31-libvirt/output /var/jenkins/workspace/unittest-vg-autotest/output
00:00:30.567  [unittest-vg-autotest] $ /usr/bin/env bash /tmp/jenkins1410830148482989625.sh
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29805.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @glodfish-zg. log: https://ci.spdk.io/public_build/autotest-per-patch_29806.html

**Comment by karlatec** [comment]
No  new instances since last two weeks.
Disk space was freed and improvements were done to VM scripts to better cleanup backing storage files in case of VM failure or crash.
