### ISSUE TITLE
memory leak in an error path of thread

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1729]
# Issue
```
[root@waikikibeach56 spdk]# ./build/bin/spdk_tgt -m 0x1 --json jsonc.json
[2020-12-29 03:41:25.683695] Starting SPDK v21.01-pre git sha1 f420b9ef0 / DPDK 20.08.0 initialization...
[2020-12-29 03:41:25.684180] [ DPDK EAL parameters: [2020-12-29 03:41:25.684218] spdk_tgt [2020-12-29 03:41:25.684254] --no-shconf [2020-12-29 03:41:25.684279] -c 0x1 [2020-12-29 03:41:25.684305] --log-level=lib.eal:6 [2020-12-29 03:41:25.684328] --log-level=lib.cryptodev:5 [2020-12-29 03:41:25.684371] --log-level=user1:6 [2020-12-29 03:41:25.684398] --iova-mode=pa [2020-12-29 03:41:25.684426] --base-virtaddr=0x200000000000 [2020-12-29 03:41:25.684464] --match-allocations [2020-12-29 03:41:25.684494] --file-prefix=spdk_pid9622 [2020-12-29 03:41:25.684517] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2020-12-29 03:41:25.805965] app.c: 536:spdk_app_start: *NOTICE*: Total cores available: 1
[2020-12-29 03:41:25.918126] reactor.c: 699:reactor_run: *NOTICE*: Reactor started on core 0
[2020-12-29 03:41:25.926863] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2020-12-29 03:41:27.112798] nvme_rdma.c:1097:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-12-29 03:41:27.112875] nvme_rdma.c:1328:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
^C[2020-12-29 03:42:43.194795] nvme_rdma.c: 537:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = -104)
[2020-12-29 03:42:43.195059] nvme_rdma.c:2003:nvme_rdma_ctrlr_construct: *ERROR*: failed to connect admin qpair
[2020-12-29 03:42:43.195173] nvme_ctrlr.c: 908:nvme_ctrlr_shutdown_async: *ERROR*: ctrlr 192.167.125.11 get_cc() failed
[2020-12-29 03:42:43.195367] nvme.c: 675:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 192.167.125.11
[2020-12-29 03:42:43.195417] nvme.c: 818:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2020-12-29 03:42:43.195510] bdev_nvme.c:2024:bdev_nvme_create: *ERROR*: No controller was found with provided trid (traddr: 192.167.125.11)
[2020-12-29 03:42:43.198729] app.c: 605:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
[2020-12-29 03:42:43.420123] thread.c: 892:spdk_thread_send_msg: *ERROR*: Thread app_thread is marked as exited.

=================================================================
==9622==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 336 byte(s) in 1 object(s) allocated from:
    #0 0x7fc7e9647f16 in __interceptor_calloc (/lib64/libasan.so.5+0x10df16)
    #1 0x62bb06 in spdk_io_device_register /home/yidong/spdk/lib/thread/thread.c:1356

SUMMARY: AddressSanitizer: 336 byte(s) leaked in 1 allocation(s).

```
# Steps
`./configure --with-rdma --enable-asan`
jsonc.json
```
 {
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_set_options",
          "params": {
            "action_on_timeout": "none",
            "timeout_us": 0,
            "retry_count": 4,
            "arbitration_burst": 0,
            "low_priority_weight": 0,
            "medium_priority_weight": 0,
            "high_priority_weight": 0,
            "nvme_adminq_poll_period_us": 10000,
            "keep_alive_timeout_ms": 10000,
            "nvme_ioq_poll_period_us": 0,
            "io_queue_requests": 0,
            "delay_cmd_submit": true
          }
        },
        {
          "params": {
            "name": "Nvme0",
            "trtype": "rdma",
            "traddr": "192.167.125.11",
            "adrfam": "ipv4",
            "trsvcid": "4420",
            "subnqn": "nqn.2016-06.io.spdk:cnode0",
            "hostnqn": "nqn.2016-06.io.spdk:host0"
          },
          "method": "bdev_nvme_attach_controller"
        }
      ]
    }
  ]
}
```
Just can't configure NIC, and kill the host app.
## Context (Environment including OS version, SPDK version, etc.)
commit f420b9ef0a9ab7f410e6e70675c8b5196cb2f4e8

**Comment by Comphix** [comment]
Hi Yidong,

This issue is occurred when killing the spdk_tgt app?

**Comment by yidong0635** [comment]
Just tried again，using the latest code， sometimes the host app  can‘t be killed after the target is terminated without doing any other things.
```
start target 
start host app(spdk_tgt)
kill nvmf_target
kill host app(spdk_tgt)  can't killed endless prints of restting controller 
```
```

[2020-12-29 07:53:31.910340] nvme_rdma.c:1097:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-12-29 07:53:31.910405] nvme_rdma.c:1328:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
^C^C^C[2020-12-29 07:54:47.706149] nvme_rdma.c: 537:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = -104)
[2020-12-29 07:54:47.706383] nvme_ctrlr.c:1369:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
[2020-12-29 07:54:47.706441] nvme_ctrlr.c: 880:nvme_ctrlr_fail: *ERROR*: ctrlr 192.167.125.11 in failed state.
[2020-12-29 07:54:47.706477] bdev_nvme.c: 386:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
[2020-12-29 07:54:47.706526] nvme_ctrlr.c:3421:nvme_ctrlr_keep_alive: *ERROR*: Submitting Keep Alive failed
[2020-12-29 07:54:47.706579] nvme_ctrlr.c:1353:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
[2020-12-29 07:54:48.709371] nvme_rdma.c:1097:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-12-29 07:54:48.709440] nvme_rdma.c:1328:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
^C^C^C^C^C^C^C[2020-12-29 07:56:04.506171] nvme_rdma.c: 537:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = -104)
[2020-12-29 07:56:04.506399] nvme_ctrlr.c:1369:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
[2020-12-29 07:56:04.506455] nvme_ctrlr.c: 880:nvme_ctrlr_fail: *ERROR*: ctrlr 192.167.125.11 in failed state.
[2020-12-29 07:56:04.506494] bdev_nvme.c: 386:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
[2020-12-29 07:56:04.638607] nvme_ctrlr.c:3421:nvme_ctrlr_keep_alive: *ERROR*: Submitting Keep Alive failed
[2020-12-29 07:56:04.642286] nvme_ctrlr.c:1353:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
[2020-12-29 07:56:05.645058] nvme_rdma.c:1097:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-12-29 07:56:05.645126] nvme_rdma.c:1328:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair
[2020-12-29 07:57:21.306134] nvme_rdma.c: 537:nvme_rdma_validate_cm_event: *ERROR*: Expected RDMA_CM_EVENT_DISCONNECTED but received RDMA_CM_EVENT_REJECTED (8) from CM event channel (status = -104)
[2020-12-29 07:57:21.306361] nvme_ctrlr.c:1369:spdk_nvme_ctrlr_reset: *ERROR*: Controller reinitialization failed.
[2020-12-29 07:57:21.306418] nvme_ctrlr.c: 880:nvme_ctrlr_fail: *ERROR*: ctrlr 192.167.125.11 in failed state.
[2020-12-29 07:57:21.306452] bdev_nvme.c: 386:_bdev_nvme_reset_complete: *ERROR*: Resetting controller failed.
[2020-12-29 07:57:21.306606] nvme_ctrlr.c:3421:nvme_ctrlr_keep_alive: *ERROR*: Submitting Keep Alive failed
[2020-12-29 07:57:21.306669] nvme_ctrlr.c:1353:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
[2020-12-29 07:57:22.309542] nvme_rdma.c:1097:nvme_rdma_connect: *ERROR*: RDMA connect error -99
[2020-12-29 07:57:22.309611] nvme_rdma.c:1328:_nvme_rdma_ctrlr_connect_qpair: *ERROR*: Unable to connect the rqpair

```

**Comment by yidong0635** [comment]
ISSUE can be reproduced without configuring host IP and after killing host app.

**Comment by shuhei-matsumoto** [comment]
Hi @yidong0635 ,

I guess the following case occurred.
We could not destruct the controller because it continued to try resetting.
A temporary poller, ctrlr->destruct_poller checks if the controller is not being reset but its interval is 1 ms. It's sufficiently likely that the controller was being reset always when the poller ran.

Independent from this issue, A possible fix is included in my patch series. The purpose is to remove ctrlr->destruct_poller. The controller will destruct itself at the end of reset processing if destruction is requested.
https://review.spdk.io/gerrit/c/spdk/spdk/+/5607/12

Will you rebase to the latest master and cherry-pick this patch?
 
Besides, will you add --enable-debug too and reproduce the issue?
More information will be helpful.

**Comment by yidong0635** [comment]
@shuhei-matsumoto  Thanks for your response, I will check this ASAP.

**Comment by yidong0635** [comment]
@shuhei-matsumoto 
Do you mean the fix for long time resetting issue or  for the memory leak issue?
 it reports by host app.

For memory leak issue.
```
target on
host app on without configuring host app
ctrl+c host app 
with you above patch or not still the same on non-debug mode. (it's hard to reproduce with debug mode)
```
```

**Comment by shuhei-matsumoto** [comment]
Hi @yidong0635 
Thanks for your quick help. My patch was for long lasting reset.

I could not reproduce the issue for TCP transport locally. (Unfortunately I cannot try RDMA transport immediately now.) I want to investigate more after new year but hopefully others will find root cause soon.

**Comment by yidong0635** [comment]
For the memory issue， I have a reference patch about this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/5744
Dev was deferred to the end and using async mode to free it (spdk_thread_send_msg) , but thread->state was exited.
That  callbacks can't be executed.

**Comment by shuhei-matsumoto** [comment]
Hi @yidong0635 

Thanks for the patch. If the thread is exited, it will be freed immediately by reactor. Reactor controls thread resource. Checking thread state outside reactor is not safe.  We may be able to add complex fix but we want to avoid it for now.

How about extending timeout to 30 seconds or 60 seconds? SPDK_THREAD_EXIT_TIMEOUT_SEC is 5 second now but it may be too short.

**Comment by yidong0635** [comment]
@shuhei-matsumoto , it's not timeout issue,  the leaked resource is dev.
in `spdk_io_device_unregister`, `refcnt>0`, dev was deferred to release in a round of `put_io_channel` 
```
if (do_remove_dev) {
		io_device_free(ch->dev);
	}
```
then` io_device_free`  using `spdk_thread_send_msg` with `callback _finish_unregister` to free dev
`thread_exit ` foreached all the pollers and channels , it executed to the end , without return and  set `thread->state = SPDK_THREAD_STATE_EXITED`;
`thread->state = _SPDK_THREAD_STATE_EXITED` before  `spdk_thread_send_msg` starts.

maybe there's better solution about this.

**Comment by shuhei-matsumoto** [comment]
Hi @yidong0635 

Thank you so much for kind explanation. It is very nice and I understood the issue now.

It may be better if we defer exiting a thread if the thread is registered to dev->unregister_thread.
I will work on this including unit test.
Your reference patch is also very helpful.

**Comment by shuhei-matsumoto** [comment]
Hi @yidong0635 

Will you take a look or try the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/5796 ?

**Comment by yidong0635** [comment]
@shuhei-matsumoto  thanks , It's ok for me.

**Comment by shuhei-matsumoto** [comment]
Thank you @yidong0635 I assigned myself to this issue.

**Comment by yidong0635** [comment]
Thanks @shuhei-matsumoto   patch was merged , Issue was fixed, close this one.
