### ISSUE TITLE
[iscsi-nightly-vg-autotest] segfault in iscsi_tgt_fuzz

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1788]
## Current Behavior

iscsi_tgt_fuzz results in segmentation fault during nightly tests.
https://ci.spdk.io/public_build/autotest-nightly_2394.html
https://ci.spdk.io/results/autotest-nightly/builds/2394/archive/iscsi-nightly-vg-autotest/index.html

Coredump files available via links above.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/vagrant/spdk_repo/spdk/test/app/fuzz/iscsi_fuzz/iscsi_fuzz -m 0xF0 -T 10.'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f9d166f1625 in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f9d162e69c0 (LWP 48887))]

Thread 6 (Thread 0x7f9d15ae3700 (LWP 48889)):
#0  0x00007f9d17ed23f9 in _reactor_run (reactor=0x2278ec0) at reactor.c:899
        thread = 0x7f9d15ae1a20
        lw_thread = 0x0
        tmp = 0x7f9d178c4bbe <rte_get_tsc_cycles+17>
        now = 140312681663334
        rc = 634
#1  0x00007f9d17ed2770 in reactor_run (arg=0x2278ec0) at reactor.c:930
        reactor = 0x2278ec0
        thread = 0x0
        lw_thread = 0x0
        tmp = 0x0
        thread_name = "reactor_5", '\000' <repeats 15 times>, "\364\027\211\026\235\177\000"
        last_sched = 0
        __func__ = "reactor_run"
        __PRETTY_FUNCTION__ = "reactor_run"
#2  0x00007f9d177e4ae9 in eal_thread_loop (arg=0x0) at ../lib/librte_eal/linux/eal_thread.c:127
        fct_arg = 0x2278ec0
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 5
        thread_id = 140312650331904
        m2w = 7
        w2m = 11
        cpuset = "5", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#3  0x00007f9d168874e2 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#4  0x00007f9d167b66a3 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 5 (Thread 0x7f9d0ffff700 (LWP 48892)):
#0  0x00007f9d168919af in accept () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f9d1765080b in socket_listener (socket=0x7f9d176557e0 <v2_socket>) at ../lib/librte_telemetry/telemetry.c:345
        th = 0
        s = 0x7f9d176557e0 <v2_socket>
        s_accepted = 0
#2  0x00007f9d168874e2 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9d167b66a3 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 4 (Thread 0x7f9d162e4700 (LWP 48888)):
#0  0x00007f9d167b69de in epoll_wait () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f9d177dc2b7 in eal_intr_handle_interrupts (pfd=8, totalfds=1) at ../lib/librte_eal/linux/eal_interrupts.c:1045
        events = {{events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}}
        nfds = 0
#2  0x00007f9d177dc4b0 in eal_intr_thread_main (arg=0x0) at ../lib/librte_eal/linux/eal_interrupts.c:1130
        pipe_event = {events = 3, data = {ptr = 0x4, fd = 4, u32 = 4, u64 = 4}}
        src = 0x0
        numfds = 1
        pfd = 8
        __func__ = "eal_intr_thread_main"
#3  0x00007f9d177c2881 in ctrl_thread_init (arg=0x21bdb90) at ../lib/librte_eal/common/eal_common_thread.c:193
        ret = -1
        internal_conf = 0x7f9d1781b4c0 <internal_config>
        cpuset = 0x7f9d1781e5f8 <internal_config+12600>
        params = 0x21bdb90
        start_routine = 0x7f9d177dc319 <eal_intr_thread_main>
        routine_arg = 0x0
#4  0x00007f9d168874e2 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#5  0x00007f9d167b66a3 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 3 (Thread 0x7f9d152e2700 (LWP 48890)):
#0  reactor_run (arg=0x2279180) at reactor.c:927
        reactor = 0x2279180
        thread = 0x0
        lw_thread = 0x0
        tmp = 0x0
        thread_name = "reactor_6", '\000' <repeats 15 times>, "\364\027\211\026\235\177\000"
        last_sched = 0
        __func__ = "reactor_run"
        __PRETTY_FUNCTION__ = "reactor_run"
#1  0x00007f9d177e4ae9 in eal_thread_loop (arg=0x0) at ../lib/librte_eal/linux/eal_thread.c:127
        fct_arg = 0x2279180
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 6
        thread_id = 140312641939200
        m2w = 12
        w2m = 15
        cpuset = "6", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#2  0x00007f9d168874e2 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#3  0x00007f9d167b66a3 in clone () from /lib64/libc.so.6
No symbol table info available.

Thread 2 (Thread 0x7f9d14ae1700 (LWP 48891)):
#0  spdk_ring_dequeue (ring=0x200006effe80, objs=0x7f9d14adf980, count=8) at env.c:435
No locals.
#1  0x00007f9d17ecf2cf in event_queue_run_batch (reactor=0x2279440) at reactor.c:571
        count = 0
        i = 0
        events = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
        thread = 0x0
        lw_thread = 0x0
        __func__ = "event_queue_run_batch"
        __PRETTY_FUNCTION__ = "event_queue_run_batch"
#2  0x00007f9d17ed1ec2 in _reactor_run (reactor=0x2279440) at reactor.c:881
        thread = 0x7f9d14adfa20
        lw_thread = 0x0
        tmp = 0x7f9d178c4bbe <rte_get_tsc_cycles+17>
        now = 140312681663334
        rc = 634
#3  0x00007f9d17ed2770 in reactor_run (arg=0x2279440) at reactor.c:930
        reactor = 0x2279440
        thread = 0x0
        lw_thread = 0x0
        tmp = 0x0
        thread_name = "reactor_7", '\000' <repeats 15 times>, "\364\027\211\026\235\177\000"
        last_sched = 0
        __func__ = "reactor_run"
        __PRETTY_FUNCTION__ = "reactor_run"
#4  0x00007f9d177e4ae9 in eal_thread_loop (arg=0x0) at ../lib/librte_eal/linux/eal_thread.c:127
        fct_arg = 0x2279440
        c = 0 '\000'
        n = 1
        ret = 0
        lcore_id = 7
        thread_id = 140312633546496
        m2w = 16
        w2m = 19
        cpuset = "7", '\000' <repeats 254 times>
        __func__ = "eal_thread_loop"
#5  0x00007f9d168874e2 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#6  0x00007f9d167b66a3 in clone () from /lib64/libc.so.6
No symbol table info available.
#7  0x00007f9d17f3e12b in _sock_check_zcopy (sock=0x227b500) at posix.c:729
        psock = 0x227b500
        group = 0x0
        msgh = {msg_name = 0x0, msg_namelen = 0, msg_iov = 0x0, msg_iovlen = 0, msg_control = 0x7fffbb7949f0, msg_controllen = 32, msg_flags = 8200}
        buf = " ", '\000' <repeats 11 times>, "\v\000\000\000\000\000\000\000\005\000\001\000\000\000\000\000\000\000\000"
        rc = 0
        serr = 0x7fffbb794a00
        cm = 0x7fffbb7949f0
        idx = 0
        req = 0x0
        treq = 0x0
        found = true
        __func__ = "_sock_check_zcopy"
#8  0x00007f9d17f3f351 in posix_sock_flush (sock=0x227b500) at posix.c:851
        psock = 0x227b500
#9  0x00007f9d17f1aa0e in spdk_sock_flush (sock=0x227b500) at sock.c:462
No locals.
#10 0x0000000000444fc7 in poll_dev (ctx=0x2279e90) at iscsi_fuzz.c:931
        dev_ctx = 0x2279e90
        conn = 0x227a0f0
        current_ticks = 2727073762432
        pdu = 0x0
        tmp = 0x0
#11 0x00007f9d17a5f145 in thread_poll (thread=0x22799e0, max_msgs=0, now=2727073754515) at thread.c:652
        poller_rc = 0
        msg_count = 0
        poller = 0x227d7a0
        tmp = 0x0
        critical_msg = 0x0
        rc = 0
        __func__ = "thread_poll"
#12 0x00007f9d17a60e55 in spdk_thread_poll (thread=0x22799e0, max_msgs=0, now=2727073754515) at thread.c:740
        orig_thread = 0x0
        rc = 0
#13 0x00007f9d17ed1f6b in _reactor_run (reactor=0x2278c00) at reactor.c:885
        thread = 0x22799e0
        lw_thread = 0x2279d20
        tmp = 0x0
        now = 2727073754515
        rc = 1
#14 0x00007f9d17ed2770 in reactor_run (arg=0x2278c00) at reactor.c:930
        reactor = 0x2278c00
        thread = 0x7f9d177b2b24 <rte_get_next_lcore+42>
        lw_thread = 0x7f00000000
        tmp = 0x7fffbb794c80
        thread_name = "reactor_4\000\000\000\200\000\000\000\260Ly\273\377\177\000\000\247\334\217\027\004\000\000"
        last_sched = 0
        __func__ = "reactor_run"
        __PRETTY_FUNCTION__ = "reactor_run"
#15 0x00007f9d17ed34ed in spdk_reactors_start () at reactor.c:1040
        reactor = 0x2278c00
        i = 4294967295
        current_core = 4
        rc = 0
        __func__ = "spdk_reactors_start"
        __PRETTY_FUNCTION__ = "spdk_reactors_start"
#16 0x00007f9d17ec9205 in spdk_app_start (opts_user=0x7fffbb794fe0, start_fn=0x445942 <begin_iscsi_fuzz>, arg1=0x0) at app.c:580
        rc = 0
        tty = 0x0
        tmp_cpumask = {str = '\000' <repeats 256 times>, cpus = "\020", '\000' <repeats 126 times>}
        g_env_was_setup = false
        opts_local = {name = 0x47d940 "iscsi_fuzz", config_file = 0x0, json_config_file = 0x0, json_config_ignore_errors = false, rpc_addr = 0x7f9d17ee81c0 "/var/tmp/spdk.sock", reactor_mask = 0x7fffbb796149 "0xF0", tpoint_group_mask = 0x0, shm_id = -1, shutdown_cb = 0x0, enable_coredump = true, mem_channel = -1, {main_core = -1, master_core = -1}, mem_size = -1, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, hugedir = 0x0, print_level = SPDK_LOG_INFO, num_pci_addr = 0, {pci_blocked = 0x0, pci_blacklist = 0x0}, {pci_allowed = 0x0, pci_whitelist = 0x0}, iova_mode = 0x0, max_delay_us = 0, delay_subsystem_init = false, num_entries = 32768, env_context = 0x0, log = 0x0, base_virtaddr = 35184372088832, opts_size = 200}
        opts = 0x7fffbb794d40
        __func__ = "spdk_app_start"
#17 0x000000000044613a in main (argc=7, argv=0x7fffbb795198) at iscsi_fuzz.c:1085
        opts = {name = 0x47d940 "iscsi_fuzz", config_file = 0x0, json_config_file = 0x0, json_config_ignore_errors = false, rpc_addr = 0x7f9d17ee81c0 "/var/tmp/spdk.sock", reactor_mask = 0x7fffbb796149 "0xF0", tpoint_group_mask = 0x0, shm_id = -1, shutdown_cb = 0x0, enable_coredump = true, mem_channel = -1, {main_core = -1, master_core = -1}, mem_size = -1, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, hugedir = 0x0, print_level = SPDK_LOG_INFO, num_pci_addr = 0, {pci_blocked = 0x0, pci_blacklist = 0x0}, {pci_allowed = 0x0, pci_whitelist = 0x0}, iova_mode = 0x0, max_delay_us = 0, delay_subsystem_init = false, num_entries = 32768, env_context = 0x0, log = 0x0, base_virtaddr = 35184372088832, opts_size = 200}
        rc = 0


```

## Steps to Reproduce

1. Build SPDK with
```
./configure --enable-debug --enable-werror --with-rdma --with-idxd --with-fio=/usr/src/fio --with-iscsi-initiator --disable-unit-tests --with-rbd --enable-ubsan --enable-coverage --without-isal --with-shared
```
2. Start iscsi_tgt_fuzz test:
```
RUN_NIGHTLY=1 ./test/iscsi_tgt/fuzz/fuzz.sh --iso
```

## Context (Environment including OS version, SPDK version, etc.)
Linux fedora31.localdomain 5.6.11-200.fc31.x86_64
gcc version 9.3.1 20200408
SPDK afbab54cbb doc/accel_fw: update docs to reflect updated configuration

**Comment by yidong0635** [comment]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  _sock_check_zcopy (sock=sock@entry=0x1cdad90) at posix.c:729
729                                     TAILQ_INSERT_TAIL(&group->pending_recv, psock, link);
[Current thread is 1 (Thread 0x7fab6d523980 (LWP 26443))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.29-9.fc30.x86_64 openssl-libs-1.1.1d-2.fc30.x86_64
(gdb) bt
#0  _sock_check_zcopy (sock=sock@entry=0x1cdad90) at posix.c:729
#1  0x000000000042cdce in posix_sock_flush (sock=0x1cdad90) at posix.c:851
#2  0x000000000041f5ad in poll_dev (ctx=0x1905040) at iscsi_fuzz.c:931
#3  0x0000000000448f7d in thread_poll (now=9464666270021930, max_msgs=0, thread=0x1904ca0) at thread.c:652
#4  spdk_thread_poll (thread=thread@entry=0x1904ca0, max_msgs=max_msgs@entry=0, now=9464666270021930) at thread.c:740
#5  0x00000000004321f8 in _reactor_run (reactor=0x1903c80) at reactor.c:885
#6  reactor_run (arg=0x1903c80) at reactor.c:930
#7  0x0000000000432627 in spdk_reactors_start () at reactor.c:1040
#8  0x000000000042f857 in spdk_app_start (opts_user=opts_user@entry=0x7ffe5704c6f0, start_fn=start_fn@entry=0x41a9a0 <begin_iscsi_fuzz>, arg1=arg1@entry=0x0) at app.c:580
#9  0x0000000000417fba in main (argc=7, argv=0x7ffe5704c8b8) at iscsi_fuzz.c:1085
(gdb)

**Comment by optimistyzy** [comment]
See this patch : https://review.spdk.io/gerrit/c/spdk/spdk/+/6334
