### ISSUE TITLE
test/dd/bdev_to_bdev.sh got SEGV

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1803]
# issue 
```
test/dd/bdev_to_bdev.sh
* Purging old temporary test storage (/tmp/spdk.ODQuvR)
* Looking for test storage...
* Found test storage at /root/spdk/test/dd
   03:11:19     # xtrace_enable
  03:11:19      # source /root/spdk/scripts/common.sh
 03:11:19       # nvmes=("$@")
 03:11:19       # trap cleanup EXIT
 03:11:19       # bs=1048576
 03:11:19       # (( 0 > 1 ))
 03:11:19       # nvme0=Nvme0
 03:11:19       # bdev0=Nvme0n1
 03:11:19       # nvme0_pci=
 03:11:19       # aio1=/root/spdk/test/dd/aio1
 03:11:19       # bdev1=aio1
 03:11:19       # method_bdev_nvme_attach_controller_1=(["name"]=$nvme0 ["traddr"]=$nvme0_pci ["trtype"]=pcie)
 03:11:19       # declare -A method_bdev_nvme_attach_controller_1
 03:11:19       # method_bdev_aio_create_0=(["name"]=$bdev1 ["filename"]=$aio1 ["block_size"]=4096)
 03:11:19       # declare -A method_bdev_aio_create_0
 03:11:19       # /root/spdk/build/bin/spdk_dd --if=/dev/zero --of=/root/spdk/test/dd/aio1 --bs=1048576 --count=2048
[2021-02-20 03:11:19.469422] Starting SPDK v21.04-pre git sha1 9ab2855d6 / DPDK 20.11.0 initialization...
[2021-02-20 03:11:19.469718] [ DPDK EAL parameters: [2021-02-20 03:11:19.469758] spdk_dd [2021-02-20 03:11:19.469792] --no-shconf [2021-02-20 03:11:19.469819] -c 0x1 [2021-02-20 03:11:19.469855] --log-level=lib.eal:6 [2021-02-20 03:11:19.469884] --log-level=lib.cryptodev:5 [2021-02-20 03:11:19.469932] --log-level=user1:6 [2021-02-20 03:11:19.469961] --iova-mode=pa [2021-02-20 03:11:19.469992] --base-virtaddr=0x200000000000 [2021-02-20 03:11:19.470018] --match-allocations [2021-02-20 03:11:19.470050] --file-prefix=spdk_pid14378 [2021-02-20 03:11:19.470081] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2021-02-20 03:11:19.580364] app.c: 538:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-02-20 03:11:19.687330] reactor.c: 915:reactor_run: *NOTICE*: Reactor started on core 0
[2021-02-20 03:11:19.687416] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Copying: 2048/2048 [MB] (average 2 GBps)

 03:11:25       # test_file0=/root/spdk/test/dd/dd.dump0
 03:11:25       # test_file1=/root/spdk/test/dd/dd.dump1
 03:11:25       # magic='This Is Our Magic, find it'
 03:11:25       # echo 'This Is Our Magic, find it'
 03:11:25       # run_test dd_inflate_file /root/spdk/build/bin/spdk_dd --if=/dev/zero --of=/root/spdk/test/dd/dd.dump0 --oflag=append --bs=1048576 --count=512
 03:11:25       # '[' 7 -le 1 ']'
 03:11:25       # xtrace_disable
 03:11:25       # '[' '' '!=' yes ']'
 03:11:25       # PREV_BASH_OPTS=ehxBET
 03:11:25       # [[ ehxBET == *\x* ]]
 03:11:25       # XTRACE_DISABLED=yes
 03:11:25       # set +x
************************************
START TEST dd_inflate_file
************************************
 03:11:25       # xtrace_enable
 03:11:25       # /root/spdk/build/bin/spdk_dd --if=/dev/zero --of=/root/spdk/test/dd/dd.dump0 --oflag=append --bs=1048576 --count=512
[2021-02-20 03:11:25.611117] Starting SPDK v21.04-pre git sha1 9ab2855d6 / DPDK 20.11.0 initialization...
[2021-02-20 03:11:25.611395] [ DPDK EAL parameters: [2021-02-20 03:11:25.611428] spdk_dd [2021-02-20 03:11:25.611457] --no-shconf [2021-02-20 03:11:25.611483] -c 0x1 [2021-02-20 03:11:25.611516] --log-level=lib.eal:6 [2021-02-20 03:11:25.611542] --log-level=lib.cryptodev:5 [2021-02-20 03:11:25.611583] --log-level=user1:6 [2021-02-20 03:11:25.611606] --iova-mode=pa [2021-02-20 03:11:25.611633] --base-virtaddr=0x200000000000 [2021-02-20 03:11:25.611655] --match-allocations [2021-02-20 03:11:25.611692] --file-prefix=spdk_pid14384 [2021-02-20 03:11:25.611721] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2021-02-20 03:11:25.720719] app.c: 538:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-02-20 03:11:25.827224] reactor.c: 915:reactor_run: *NOTICE*: Reactor started on core 0
[2021-02-20 03:11:25.827310] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
Copying: 512/512 [MB] (average 2 GBps)


real    0m0.721s
user    0m0.223s
sys     0m0.463s
 03:11:26       # xtrace_disable
 03:11:26       # '[' no '!=' yes ']'
 03:11:26       # PREV_BASH_OPTS=ehxBET
 03:11:26       # [[ ehxBET == *\x* ]]
 03:11:26       # XTRACE_DISABLED=yes
 03:11:26       # set +x
************************************
END TEST dd_inflate_file
************************************
 03:11:26       # xtrace_enable
  03:11:26      # wc -c
 03:11:26       # test_file0_size=536870939
 03:11:26       # run_test dd_copy_to_out_bdev /root/spdk/build/bin/spdk_dd --if=/root/spdk/test/dd/dd.dump0 --ob=Nvme0n1 --json /dev/fd/62
  03:11:26      # gen_conf
 03:11:26       # '[' 6 -le 1 ']'
 03:11:26       # xtrace_disable
  03:11:26      # xtrace_disable
 03:11:26       # '[' no '!=' yes ']'
 03:11:26       # PREV_BASH_OPTS=ehxBET
  03:11:26      # '[' no '!=' yes ']'
 03:11:26       # [[ ehxBET == *\x* ]]
 03:11:26       # XTRACE_DISABLED=yes
  03:11:26      # PREV_BASH_OPTS=ehxBET
 03:11:26       # set +x
  03:11:26      # [[ ehxBET == *\x* ]]
  03:11:26      # XTRACE_DISABLED=yes
  03:11:26      # set +x
************************************
START TEST dd_copy_to_out_bdev
************************************
 03:11:26       # xtrace_enable
 03:11:26       # /root/spdk/build/bin/spdk_dd --if=/root/spdk/test/dd/dd.dump0 --ob=Nvme0n1 --json /dev/fd/62
[2021-02-20 03:11:26.366428] Starting SPDK v21.04-pre git sha1 9ab2855d6 / DPDK 20.11.0 initialization...
[2021-02-20 03:11:26.366688] [ DPDK EAL parameters: [2021-02-20 03:11:26.366735] spdk_dd [2021-02-20 03:11:26.366767] --no-shconf [2021-02-20 03:11:26.366792] -c 0x1 [2021-02-20 03:11:26.366824] --log-level=lib.eal:6 [2021-02-20 03:11:26.366850] --log-level=lib.cryptodev:5 [2021-02-20 03:11:26.366891] --log-level=user1:6 [2021-02-20 03:11:26.366915] --iova-mode=pa [2021-02-20 03:11:26.366959] --base-virtaddr=0x200000000000 [2021-02-20 03:11:26.366982] --match-allocations [2021-02-20 03:11:26.367012] --file-prefix=spdk_pid14410 [2021-02-20 03:11:26.367039] ]
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "block_size": 4096,
            "filename": "/root/spdk/test/dd/aio1",
            "name": "aio1"
          },
          "method": "bdev_aio_create"
        },
        {
          "params": {
            "trtype": "pcie",
            "traddr": "",
            "name": "Nvme0"
          },
          "method": "bdev_nvme_attach_controller"
        }
      ]
    }
  ]
}
  03:11:26      # xtrace_enable
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2021-02-20 03:11:26.477747] app.c: 538:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-02-20 03:11:26.584514] reactor.c: 915:reactor_run: *NOTICE*: Reactor started on core 0
[2021-02-20 03:11:26.585263] accel_engine.c: 692:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==14410==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004296df bp 0x616000004880 sp 0x7ffc319475f0 T0)
==14410==The signal is caused by a READ memory access.
==14410==Hint: address points to the zero page.
    #0 0x4296de in nvme_ctrlr_populate_namespaces /root/spdk/module/bdev/nvme/bdev_nvme.c:1406
    #1 0x4d16bb in nvme_ctrlr_poll_internal /root/spdk/lib/nvme/nvme.c:745
    #2 0x4d16bb in spdk_nvme_probe_poll_async /root/spdk/lib/nvme/nvme.c:1518
    #3 0x42c80f in bdev_nvme_async_poll /root/spdk/module/bdev/nvme/bdev_nvme.c:1990
    #4 0x577956 in thread_poll /root/spdk/lib/thread/thread.c:696
    #5 0x577956 in spdk_thread_poll /root/spdk/lib/thread/thread.c:740
    #6 0x56db5b in _reactor_run /root/spdk/lib/event/reactor.c:885
    #7 0x56db5b in reactor_run /root/spdk/lib/event/reactor.c:930
    #8 0x56e6a5 in spdk_reactors_start /root/spdk/lib/event/reactor.c:1031
    #9 0x567f77 in spdk_app_start /root/spdk/lib/event/app.c:580
    #10 0x41a53c in main /root/spdk/app/spdk_dd/spdk_dd.c:1167
    #11 0x7fae12ccaf42 in __libc_start_main (/lib64/libc.so.6+0x23f42)
    #12 0x41faed in _start (/root/spdk/build/bin/spdk_dd+0x41faed)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /root/spdk/module/bdev/nvme/bdev_nvme.c:1406 in nvme_ctrlr_populate_namespaces
==14410==ABORTING

```
OS: fedora30
commit: 9ab2855d6e74c9c1f02994c7544bc90d36795b29

**Comment by yidong0635** [comment]
this case is designed to accepted a parameter, so direct to run this test scripts is not right. 
but I found other case happens can't find  the controller .  maybe these cases have relationships。
and I close this one.
