### ISSUE TITLE
vfio-user: SPDK target crash when attaching multiple VMs

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1834]
## Current Behavior

SPDK target crashes when multiple VMs (3 and more in my case) attach via vfio-user sockets.

## Steps to Reproduce

1. Clone & build SPDK with vfio-user option:
```
git submodule update --init
./configure --with-fio=/usr/src/fio --with-vfio-user --enable-debug
make -j100
```
2. Clone & build vfio-user capable Qemu:
```
git clone https://github.com/tmakatos/qemu.git
git checkout origin/vfio-user-v0.6
./configure --target-list="x86_64-softmmu" --enable-kvm --enable-linux-aio --enable-numa
make -j100
```

3. Configure SPDK target and run multiple VMs.
```
#!/usr/bin/env bash

build/bin/nvmf_tgt -p 0 -m [24] &
pid=$!
echo "PID: $pid"
sleep 1
read -p "Waiting..."
rm -rf /dev/shm/muser
scripts/rpc.py nvmf_create_transport --trtype VFIOUSER

for i in $(seq 0 2); do
        cpu1=$((25 + i))
        cpu2=$((30 + i))
        vm_muser_dir="/home/sys_sgci/vhost_test/vms/$i/muser"
        rm -rf $vm_muser_dir
        mkdir -p $vm_muser_dir/iommu_group
        mkdir -p $vm_muser_dir/domain/muser$i/$i
        mkdir -p /dev/shm/muser/muser$i

        scripts/rpc.py bdev_malloc_create 128 512 -b Malloc${i}
        scripts/rpc.py nvmf_create_subsystem nqn.2019-07.io.spdk:cnode${i} -s SPDK00${i} -a
        scripts/rpc.py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode${i} Malloc${i}
        scripts/rpc.py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode${i} -t VFIOUSER -a $vm_muser_dir/domain/muser$i/$i -s 0
        ln -s $vm_muser_dir/domain/muser$i/$i $vm_muser_dir/domain/muser$i/$i/iommu_group
        ln -s $vm_muser_dir/domain/muser$i/$i $vm_muser_dir/iommu_group/$i
        ln -s $vm_muser_dir/domain/muser$i/$i/bar0 /dev/shm/muser/muser$i/bar0
done

for i in $(seq 0 2); do

        vm_muser_dir="/home/sys_sgci/vhost_test/vms/$i/muser"

        sudo taskset -a -c ${cpu1},${cpu2} /usr/local/qemu/vfio-user/bin/qemu-system-x86_64 \
-m 4096 --enable-kvm -cpu host -smp 2 -vga std -vnc :10${i} -daemonize \
-object memory-backend-file,id=mem,size=4096M,mem-path=/dev/hugepages,prealloc=yes,share=yes,host-nodes=1,policy=bind \
-snapshot -monitor telnet:127.0.0.1:10${i}02,server,nowait \
-numa node,memdev=mem -pidfile /home/sys_sgci/vhost_test/vms/${i}/qemu.pid \
-serial file:/home/sys_sgci/vhost_test/vms/${i}/serial.log \
-D /home/sys_sgci/vhost_test/vms/${i}/qemu.log \
-chardev file,path=/home/sys_sgci/vhost_test/vms/${i}/seabios.log,id=seabios \
-device isa-debugcon,iobase=0x402,chardev=seabios \
-net user,hostfwd=tcp::10${i}00-:22,hostfwd=tcp::10${i}01-:8765 \
-net nic -drive file=/home/sys_sgsw/fedora33.qcow2,if=none,id=os_disk \
-device ide-hd,drive=os_disk,bootindex=0 \
-device vfio-user-pci,socket=$vm_muser_dir/domain/muser${i}/${i}/cntrl

done
```

At some point while VMs are booting SPDK target crashes with:
```
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/var/jenkins/workspace/vhost-perf/regression-vhost/spdk/build/bin/nvmf_tgt -r /'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000406b53 in bdev_malloc_readv (mdisk=0xffffffff, ch=0x17b4300, task=0x2010074c6468, iov=0x19ac2b0, iovcnt=1, len=512, offset=0) at bdev_malloc.c:143
143             void *src = mdisk->malloc_buf + offset;
[Current thread is 1 (Thread 0x7f45d9cab980 (LWP 306272))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.31-6.fc32.x86_64 json-c-0.13.1-13.fc32.x86_64 libaio-0.3.111-7.fc32.x86_64 libuuid-2.35.2-1.fc32.x86_64 numactl-libs-2.0.12-4.fc32.x86_64 openssl-libs-1.1.1i-1.fc32.x86_64 zlib-1.2.11-21.fc32.x86_64
(gdb) bt
#0  0x0000000000406b53 in bdev_malloc_readv (mdisk=0xffffffff, ch=0x17b4300, task=0x2010074c6468, iov=0x19ac2b0, iovcnt=1, len=512, offset=0) at bdev_malloc.c:143
#1  0x0000000000407078 in _bdev_malloc_submit_request (ch=0x17b4300, bdev_io=0x2010074c6100) at bdev_malloc.c:251
#2  0x00000000004072cb in bdev_malloc_submit_request (ch=0x17b4300, bdev_io=0x2010074c6100) at bdev_malloc.c:319
#3  0x00000000004dafb9 in bdev_io_do_submit (bdev_ch=0x17bb390, bdev_io=0x2010074c6100) at bdev.c:1896
#4  0x00000000004dc0d9 in _bdev_io_submit (ctx=0x2010074c6100) at bdev.c:2295
#5  0x00000000004dc627 in bdev_io_submit (bdev_io=0x2010074c6100) at bdev.c:2412
#6  0x00000000004df2c2 in bdev_readv_blocks_with_md (desc=0x17baa10, ch=0x17bb360, iov=0x19ac2b0, iovcnt=1, md_buf=0x0, offset_blocks=0, num_blocks=1, cb=0x482701 <nvmf_bdev_ctrlr_complete_cmd>, cb_arg=0x19ac188) at bdev.c:3647
#7  0x00000000004df319 in spdk_bdev_readv_blocks (desc=0x17baa10, ch=0x17bb360, iov=0x19ac2b0, iovcnt=1, offset_blocks=0, num_blocks=1, cb=0x482701 <nvmf_bdev_ctrlr_complete_cmd>, cb_arg=0x19ac188) at bdev.c:3656
#8  0x0000000000482f03 in nvmf_bdev_ctrlr_read_cmd (bdev=0x17ba5c0, desc=0x17baa10, ch=0x17bb360, req=0x19ac188) at ctrlr_bdev.c:289
#9  0x0000000000480eb0 in nvmf_ctrlr_process_io_cmd (req=0x19ac188) at ctrlr.c:3421
#10 0x0000000000481a79 in spdk_nvmf_request_exec (req=0x19ac188) at ctrlr.c:3670
#11 0x00000000004a3212 in handle_cmd_req (ctrlr=0x1776ae0, cmd=0x7f4581efc000, req=0x19ac188) at vfio_user.c:2146
#12 0x00000000004a00a6 in consume_cmd (ctrlr=0x1776ae0, qpair=0x17789a0, cmd=0x7f4581efc000) at vfio_user.c:1002
#13 0x00000000004a0162 in handle_sq_tdbl_write (ctrlr=0x1776ae0, new_tail=8, qpair=0x17789a0) at vfio_user.c:1025
#14 0x00000000004a32ce in nvmf_vfio_user_qpair_poll (qpair=0x17789a0) at vfio_user.c:2175
#15 0x00000000004a3447 in nvmf_vfio_user_poll_group_poll (group=0x177c9d0) at vfio_user.c:2228
#16 0x0000000000494bf0 in nvmf_transport_poll_group_poll (group=0x177c9d0) at transport.c:508
#17 0x000000000048ac78 in nvmf_poll_group_poll (ctx=0x17632b0) at nvmf.c:100
#18 0x00000000004fd475 in thread_poll (thread=0x1762ee0, max_msgs=0, now=702711557765162) at thread.c:652
#19 0x00000000004fd8d4 in spdk_thread_poll (thread=0x1762ee0, max_msgs=0, now=702711557765162) at thread.c:740
#20 0x00000000004f55d5 in _reactor_run (reactor=0x175f1c0) at reactor.c:885
#21 0x00000000004f5710 in reactor_run (arg=0x175f1c0) at reactor.c:930
#22 0x00000000004f5aea in spdk_reactors_start () at reactor.c:1031
#23 0x00000000004f27c5 in spdk_app_start (opts_user=0x7ffc73dfd8b0, start_fn=0x4067df <nvmf_tgt_started>, arg1=0x0) at app.c:566
#24 0x0000000000406932 in main (argc=7, argv=0x7ffc73dfda68) at nvmf_main.c:75
```

**NOTE**
For actual reproduction I'm using test/vhost/perf/vhost_perf.sh scripts. The script in reproduction scripts is as close to what's happening in vhost_perf.sh as possible, but for some reason does not end in SPDK target crash (even though I'd expectit to).
I will be working on better reproduction steps and try to update later.

## Context (Environment including OS version, SPDK version, etc.)

SPDK: `13f868977e module/bdev: remove deprecated API`
libvfio-user submodule: `052d709 fix IRQ disable path (#386)` (current master)
gcc version 10.2.1 20201125 (Red Hat 10.2.1-9) (GCC)

**Comment by changpe1** [comment]
I tested 2 VMs and failed with the following errors:

[2021-03-17 23:21:15.165114] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: W 7 0x86-0x88
[2021-03-17 23:21:15.165452] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: W 7 0x86-0x88
[2021-03-17 23:21:15.165458] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: enable MSI-X

[2021-03-17 23:21:15.165464] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: all MSI-X vectors masked

[2021-03-17 23:21:15.170005] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: disabling IRQ type INTx range [0-0)
[2021-03-17 23:21:15.170150] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: disabling IRQ type MSI-X range [0-0)
[2021-03-17 23:21:15.170162] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: failed to close IRQ fd 0: Bad file descriptor
[2021-03-17 23:21:15.170169] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: failed to close IRQ fd 0: Bad file descriptor
[2021-03-17 23:21:15.170175] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: failed to close IRQ fd 1041: Bad file descriptor
[2021-03-17 23:21:15.170181] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: failed to close IRQ fd 0: Bad file descriptor
[2021-03-17 23:21:15.170187] vfio_user.c:1348:vfio_user_log: *DEBUG*: /var/run/muser/domain/muser1/9: failed to close IRQ fd 0: Bad file descriptor
[2021-03-17 23:21:15.170195] vfio_user.c:1356:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/9: failed to reply: Bad file descriptor
[2021-03-17 23:21:15.170208] vfio_user.c: 254:fail_ctrlr: *ERROR*: :/var/run/muser/domain/muser1/9 failing controller
[2021-03-17 23:21:15.170219] vfio_user.c:1356:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/9: failed to receive request: Bad file descriptor
[2021-03-17 23:21:15.170231] vfio_user.c:1356:vfio_user_log: *ERROR*: /var/run/muser/domain/muser1/9: failed to receive request: Bad file descriptor

**Comment by yidong0635** [comment]
```
[2021-03-24 15:38:39.017248] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: invalid IRQ type 1
[2021-03-24 15:38:39.017316] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: msg0x12: cmd 7 failed: Invalid argument
[2021-03-24 15:38:39.017397] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: invalid IRQ type 1
[2021-03-24 15:38:39.017414] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: msg0x14: cmd 7 failed: Invalid argument
[2021-03-24 15:38:39.030460] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: invalid IRQ type 1
[2021-03-24 15:38:39.030481] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: msg0x19: cmd 7 failed: Invalid argument
[2021-03-24 15:38:39.030981] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: invalid IRQ type 1
[2021-03-24 15:38:39.030999] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: msg0x1a: cmd 7 failed: Invalid argument
[2021-03-24 15:38:39.031038] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: invalid IRQ type 1
[2021-03-24 15:38:39.031053] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: msg0x1b: cmd 7 failed: Invalid argument
 create vm_done
[2021-03-24 15:38:39.088856] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: invalid IRQ type 1
[2021-03-24 15:38:39.088883] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: msg0x51: cmd 7 failed: Invalid argument
[2021-03-24 15:38:39.088966] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: invalid IRQ type 1
[2021-03-24 15:38:39.088981] vfio_user.c:1351:vfio_user_log: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: msg0x53: cmd 7 failed: Invalid argument
[2021-03-24 15:38:39.175803] vfio_user.c: 510:acq_map: *ERROR*: Map ACQ failed, ACQ 3ffde000, errno -1
[2021-03-24 15:38:39.175836] vfio_user.c:1043:map_admin_queue: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: failed to map CQ0: -1
[2021-03-24 15:38:39.175850] vfio_user.c:1104:memory_region_add_cb: *NOTICE*: Failed to map SQID 1 0x3ffd8000-0x3ffdc000, will try again in next poll
[2021-03-24 15:38:39.176211] vfio_user.c: 510:acq_map: *ERROR*: Map ACQ failed, ACQ 3ffde000, errno -1
[2021-03-24 15:38:39.176229] vfio_user.c:1043:map_admin_queue: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: failed to map CQ0: -1
[2021-03-24 15:38:39.176243] vfio_user.c:1104:memory_region_add_cb: *NOTICE*: Failed to map SQID 1 0x3ffd8000-0x3ffdc000, will try again in next poll
[2021-03-24 15:38:39.176299] vfio_user.c: 510:acq_map: *ERROR*: Map ACQ failed, ACQ 3ffde000, errno -1
[2021-03-24 15:38:39.176314] vfio_user.c:1043:map_admin_queue: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: failed to map CQ0: -1
[2021-03-24 15:38:39.176328] vfio_user.c:1104:memory_region_add_cb: *NOTICE*: Failed to map SQID 1 0x3ffd8000-0x3ffdc000, will try again in next poll
[2021-03-24 15:38:39.176380] vfio_user.c: 510:acq_map: *ERROR*: Map ACQ failed, ACQ 3ffde000, errno -1
[2021-03-24 15:38:39.176395] vfio_user.c:1043:map_admin_queue: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: failed to map CQ0: -1
[2021-03-24 15:38:39.176407] vfio_user.c:1104:memory_region_add_cb: *NOTICE*: Failed to map SQID 1 0x3ffd8000-0x3ffdc000, will try again in next poll
[2021-03-24 15:38:39.177490] vfio_user.c: 510:acq_map: *ERROR*: Map ACQ failed, ACQ 3ffde000, errno -1
[2021-03-24 15:38:39.177508] vfio_user.c:1043:map_admin_queue: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: failed to map CQ0: -1
[2021-03-24 15:38:39.177521] vfio_user.c:1104:memory_region_add_cb: *NOTICE*: Failed to map SQID 1 0x3ffd8000-0x3ffdc000, will try again in next poll
[2021-03-24 15:38:39.177579] vfio_user.c: 510:acq_map: *ERROR*: Map ACQ failed, ACQ 3ffde000, errno -1
[2021-03-24 15:38:39.177593] vfio_user.c:1043:map_admin_queue: *ERROR*: /home/yidong/vms/0/muser/domain/muser0/0: failed to map CQ0: -1
[2021-03-24 15:38:39.177605] vfio_user.c:1104:memory_region_add_cb: *NOTICE*: Failed to map SQID 1 0x3ffd8000-0x3ffdc000, will try again in next poll
```

It there any update it?

**Comment by changpe1** [comment]
Maybe tomorrow, one PR is going to be merged to libvfio-user, I tested with this PR, the two VMs cases passed.

**Comment by jimharris** [comment]
Hi @changpe1, can we close this issue?

**Comment by changpe1** [comment]
Closing this issue now as the patch has been merged.
