### ISSUE TITLE
How to change location of spdk.sock and spdk.sock.lock 

### ISSUE THREAD

**Issue by Aniruddha8699** [spdk/spdk#1841]
How to move these files- spdk.sock, spdk.sock.lock from /var/tmp to any other location?

**Comment by Comphix** [comment]
You can use -r parameter to assign a preferred location. The spdk.sock is the default one.

**Comment by Aniruddha8699** [comment]
@Comphix I followed these steps,

mkdir /test

cd spdk
./build/bin/spdk_tgt -r /test

And I got the following error msg

[2021-03-18 11:59:01.902671] Starting SPDK v21.04-pre git sha1 97ef87010 / DPDK                                                                              20.11.0 initialization...
[2021-03-18 11:59:01.902784] [ DPDK EAL parameters: [2021-03-18 11:59:01.902795]                                                                              spdk_tgt [2021-03-18 11:59:01.902805] --no-shconf [2021-03-18 11:59:01.902813]                                                                              -c 0x1 [2021-03-18 11:59:01.902820] --log-level=lib.eal:6 [2021-03-18 11:59:01.9                                                                             02828] --log-level=lib.cryptodev:5 [2021-03-18 11:59:01.902832] --log-level=user                                                                             1:6 [2021-03-18 11:59:01.902837] --iova-mode=pa [2021-03-18 11:59:01.902841] --b                                                                             ase-virtaddr=0x200000000000 [2021-03-18 11:59:01.902846] --match-allocations [20                                                                             21-03-18 11:59:01.902851] --file-prefix=spdk_pid1733 [2021-03-18 11:59:01.902855                                                                             ] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2021-03-18 11:59:02.043720] app.c: 538:spdk_app_start: *NOTICE*: Total cores av                                                                             ailable: 1
[2021-03-18 11:59:02.111497] trace_flags.c: 296:spdk_trace_register_description:                                                                              *ERROR*: name (FC_REQ_READ_SUBMIT_TO_BDEV) too long
[2021-03-18 11:59:02.111596] trace_flags.c: 296:spdk_trace_register_description:                                                                              *ERROR*: name (FC_REQ_WRITE_NEED_BUFFER) too long
[2021-03-18 11:59:02.111607] trace_flags.c: 296:spdk_trace_register_description:                                                                              *ERROR*: name (FC_REQ_WRITE_SUBMIT_TO_BDEV) too long
[2021-03-18 11:59:02.111613] trace_flags.c: 296:spdk_trace_register_description:                                                                              *ERROR*: name (FC_REQ_NONE_SUBMIT_TO_BDEV) too long
[2021-03-18 11:59:02.111620] trace_flags.c: 296:spdk_trace_register_description:                                                                              *ERROR*: name (FC_REQ_ABORTED_SUBMIT_TO_BDEV) too long
[2021-03-18 11:59:02.111634] reactor.c: 915:reactor_run: *NOTICE*: Reactor start                                                                             ed on core 0
[2021-03-18 11:59:02.111654] accel_engine.c: 854:spdk_accel_engine_initialize: *                                                                             NOTICE*: Accel engine initialized to use software engine.
[2021-03-18 11:59:02.188572] jsonrpc_server_tcp.c:  81:spdk_jsonrpc_server_liste                                                                             n: *ERROR*: could not bind JSON-RPC server: Address already in use
[2021-03-18 11:59:02.188767] rpc.c: 203:spdk_rpc_listen: *ERROR*: spdk_jsonrpc_s                                                                             erver_listen() failed
[2021-03-18 11:59:02.188809] rpc.c:  71:spdk_rpc_initialize: *ERROR*: Unable to                                                                              start RPC service at /test

Is it the correct way to do it? 
Please guide me

**Comment by Comphix** [comment]
Please have a try as below:

/build/bin/spdk_tgt -r /test/spdk.sock

**Comment by Aniruddha8699** [comment]
**Yes it is working.
Thank you.**

But now while executing RPC commands it is giving error
For eg,
**I used scripts/rpc.py bdev_get_bdevs** 
and it is throwing this error

Traceback (most recent call last):
  File "/root/spdk/scripts/rpc/client.py", line 71, in _connect
    self.sock.connect((addr, port))
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/rpc.py", line 2696, in <module>
    conn_retries=args.conn_retries)
  File "/root/spdk/scripts/rpc/client.py", line 47, in __init__
    self._connect(addr, port)
  File "/root/spdk/scripts/rpc/client.py", line 76, in _connect
    "Error details: %s" % (addr, ex))
rpc.client.JSONRPCException: Error while connecting to /var/tmp/spdk.sock
Error details: [Errno -2] Name or service not known

What to do now?

**Comment by Comphix** [comment]
For the rpc.py, need to add the -s parameter to specify your preferred RPC address

rpc.py -s /test/spdk.sock

**Comment by Aniruddha8699** [comment]
Yes it is working.
Thank you so much !!
