### ISSUE TITLE
idxd unit tests fail on UndefinedBehaviorSanitizer when using clang 11

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1847]
## Current Behavior

IDXD unit tests fail when compiling with Clang version 11.

## Steps to Reproduce

1. Create ~/autorun-spdk.conf file:
```
SPDK_RUN_VALGRIND=1
SPDK_TEST_UNITTEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_RUN_ASAN=1
SPDK_RUN_UBSAN=1
```
2. Do `spdk/autobuild.sh ~/autorun-spdk.conf`
3. Run idxd unit test
```
************************************
START TEST unittest_idxd
************************************
 12:57:50       # xtrace_enable
 12:57:50       # /home/vagrant/spdk_repo/spdk/test/unit/lib/idxd/idxd.c/idxd_ut


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: idxd
  Test: test_spdk_idxd_reconfigure_chan ...passed
  Test: test_spdk_idxd_set_config ...passed
  Test: test_idxd_wait_cmd ...[2021-03-22 12:57:50.975857] /home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c: 292:idxd_wait_cmd: *ERROR*: Command status reg reports error 0x1
[2021-03-22 12:57:50.976275] /home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c: 286:idxd_wait_cmd: *ERROR*: Command timeout, waited 1
passed
  Test: test_idxd_reset_dev ...[2021-03-22 12:57:50.976429] /home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c: 292:idxd_wait_cmd: *ERROR*: Command status reg reports error 0x1
[2021-03-22 12:57:50.976512] /home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c: 426:idxd_reset_dev: *ERROR*: Error resetting device 4294967274
passed
  Test: test_idxd_group_config ...passed
  Test: test_idxd_wq_config ...[2021-03-22 12:57:50.976829] /home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c: 503:idxd_wq_config: *NOTICE*: Total ring slots available space 0x40, so per work queue is 0x40
/home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c:526:19: runtime error: applying zero offset to null pointer
    #0 0x576d2d  (/home/vagrant/spdk_repo/spdk/test/unit/lib/idxd/idxd.c/idxd_ut+0x576d2d)
    #1 0x55b090  (/home/vagrant/spdk_repo/spdk/test/unit/lib/idxd/idxd.c/idxd_ut+0x55b090)
    #2 0x7f3e65f5a1a6  (/lib64/libcunit.so.1+0x41a6)
    #3 0x7f3e65f5a528  (/lib64/libcunit.so.1+0x4528)
    #4 0x7f3e65f5b456  (/lib64/libcunit.so.1+0x5456)
    #5 0x550ef2  (/home/vagrant/spdk_repo/spdk/test/unit/lib/idxd/idxd.c/idxd_ut+0x550ef2)
    #6 0x7f3e658e81e1  (/lib64/libc.so.6+0x281e1)
    #7 0x42061d  (/home/vagrant/spdk_repo/spdk/test/unit/lib/idxd/idxd.c/idxd_ut+0x42061d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c:526:19 in
/home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh: line 903: 137592 Aborted                 (core dumped) "$@"
```

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/home/vagrant/spdk_repo/spdk/test/unit/lib/idxd/idxd.c/idxd_ut'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f3e658fd9d5 in raise () from /lib64/libc.so.6

Thread 1 (Thread 0x7f3e657f9800 (LWP 137592)):
#0  0x00007f3e658fd9d5 in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f3e658e68a4 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00000000004e452b in __sanitizer::Abort() ()
No symbol table info available.
#3  0x00000000004e2878 in __sanitizer::Die() ()
No symbol table info available.
#4  0x00000000004f32c9 in __ubsan::ScopedReport::~ScopedReport() ()
No symbol table info available.
#5  0x00000000004f77f5 in handlePointerOverflowImpl(__ubsan::PointerOverflowData*, unsigned long, unsigned long, __ubsan::ReportOptions) ()
No symbol table info available.
#6  0x00000000004f8421 in __ubsan_handle_pointer_overflow ()
No symbol table info available.
#7  0x0000000000576d2e in idxd_wq_config (idxd=0x7ffda96b02c0) at /home/vagrant/spdk_repo/spdk/lib/idxd/idxd.c:526
        i = 0
        j = 15428856
        queue = 0x604000000190
        wq_size = 64
#8  0x000000000055b091 in test_idxd_wq_config () at idxd_ut.c:112
        idxd = {device = 0x0, reg_base = 0x61d000001e80, portals = 0x0, socket_id = 0, wq_id = 0, num_channels = 0, needs_rebalance = false, num_channels_lock = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0
, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, registers = {version = 0, gencap = {{block_on_fault = 0, overlap_copy = 0, cache_control_mem = 0, cache_control_ca
che = 0, rsvd = 0, int_handle_req = 0, dest_readback = 0, drain_readback = 0, rsvd2 = 0, max_xfer_shift = 30, max_batch_shift = 4, max_ims_mult = 0, config_en = 0, max_descs_per_engine = 0, rsvd3 = 0}, raw = 10354688}, wqcap = {{total
_wq_size = 64, num_wqs = 1, rsvd = 0, shared_mode = 0, dedicated_mode = 0, rsvd2 = 0, priority = 0, occupancy = 0, occupancy_int = 0, rsvd3 = 0}, raw = 65600}, groupcap = {{num_groups = 0, total_tokens = 0, token_en = 0, token_limit =
 0, rsvd = 0}, raw = 0}, enginecap = {{num_engines = 0, rsvd = 0}, raw = 0}, opcap = {raw = {0, 0, 0, 0}}}, ims_offset = 0, msix_perm_offset = 0, wqcfg_offset = 1280, grpcfg_offset = 0, perfmon_offset = 0, groups = 0x0, queues = 0x604
000000190}
        wqcfg = {{wq_size = 0, rsvd = 0, wq_thresh = 0, rsvd1 = 0, mode = 0, bof = 0, rsvd2 = 0, priority = 0, pasid = 0, pasid_en = 0, priv = 0, rsvd3 = 0, max_xfer_shift = 0, max_batch_shift = 0, rsvd4 = 0, occupancy_inth = 0, occup
ancy_table_sel = 0, rsvd5 = 0, occupancy_limit = 0, occupancy_int_en = 0, rsvd6 = 0, occupancy = 0, occupancy_int = 0, rsvd7 = 0, mode_support = 0, wq_state = 0, rsvd8 = 0}, raw = {0, 0, 0, 0, 0, 0, 0, 0}}
        expected = {64, 0, 17, 158, 0, 0, 1073741824, 0}
        wq_size = 64
        rc = 1
        i = 0
        j = 1024
#9  0x00007f3e65f5a1a7 in run_single_test.constprop () from /lib64/libcunit.so.1
No symbol table info available.
#10 0x00007f3e65f5a529 in run_single_suite.constprop () from /lib64/libcunit.so.1
No symbol table info available.
#11 0x00007f3e65f5b457 in CU_run_all_tests () from /lib64/libcunit.so.1
No symbol table info available.
#12 0x0000000000550ef3 in main (argc=1, argv=0x7ffda96b18b8) at idxd_ut.c:304
        suite = 0x6080000000a0
        num_failures = 0

```

## Context (Environment including OS version, SPDK version, etc.)
SPDK `b8db1af4e`  `thread: criticalmsg also indicates valid event`
clang version 11.0.0 (Fedora 11.0.0-2.fc33)
Fedora 33 5.10.23-200.fc33.x86_64

**Comment by karlatec** [comment]
Suggesting to port the fix to 21.01.x branch once the fix is ready

**Comment by peluse** [comment]
never tried with clang before, will have a few min later today can look unless someone else gets to it first

**Comment by peluse** [comment]
@karlatec here is the proposed fix.  I'm very curious though why this just came up now, is this a new test config in CI? https://review.spdk.io/gerrit/c/spdk/spdk/+/7016

**Comment by karlatec** [comment]
@peluse Yes. Current test VMs have clang version 9, new ones have version 11.

**Comment by karlatec** [comment]
Ran tests with you patch, 10/10 pass rate. Thanks!

**Comment by peluse** [comment]
fix here: https://review.spdk.io/gerrit/c/spdk/spdk/+/7016
