### ISSUE TITLE
g_hotplug_probe_ctx is double free when exiting the spdk_tgt

### ISSUE THREAD

**Issue by Comphix** [spdk/spdk#1849]
Start the spdk_tgt, enable the hotplug, insert one new NVMe SSD. After this, exit (ctrl + c) the spdk_tgt, a core dump is generated.

## Expected Behavior

No core dump will trigger

## Current Behavior

Core dump triggerred.

./spdk_tgt
[2021-03-23 15:09:16.553571] Starting SPDK v21.04-pre git sha1 289c1d5bb / DPDK 20.11.0 initialization...
[2021-03-23 15:09:16.553865] [ DPDK EAL parameters: [2021-03-23 15:09:16.553892] spdk_tgt [2021-03-23 15:09:16.553909] --no-shconf [2021-03-23 15:09:16.553942] -c 0x1 [2021-03-23 15:09:16.553958] --log-level=lib.eal:6 [2021-03-23 15:09:16.553984] --log-level=lib.cryptodev:5 [2021-03-23 15:09:16.554003] --log-level=user1:6 [2021-03-23 15:09:16.554019] --iova-mode=pa [2021-03-23 15:09:16.554038] --base-virtaddr=0x200000000000 [2021-03-23 15:09:16.554060] --match-allocations [2021-03-23 15:09:16.554077] --file-prefix=spdk_pid29140 [2021-03-23 15:09:16.554093] ]
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2021-03-23 15:09:16.653605] app.c: 535:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-03-23 15:09:16.817086] reactor.c: 915:reactor_run: *NOTICE*: Reactor started on core 0
[2021-03-23 15:09:16.817215] accel_engine.c: 854:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
EAL: failed to parse device "pci:0000:0b:00:0"
[2021-03-23 15:09:29.142038] pci.c:1098:spdk_pci_device_allow: *ERROR*: rte_devargs_parse() failed on 'pci:0000:0b:00:0'
^C*** Error in `./spdk_tgt': double free or corruption (!prev): 0x0000000002a183f0 ***

(gdb) info threads
  Id   Target Id         Frame
  3    Thread 0x7fa4404bb700 (LWP 29142) 0x00007fa4414ba98d in accept () from /lib64/libpthread.so.0
  2    Thread 0x7fa440cbc700 (LWP 29141) 0x00007fa4411e1923 in epoll_wait () from /lib64/libc.so.6
* 1    Thread 0x7fa44274a980 (LWP 29140) 0x00007fa44111e1f7 in raise () from /lib64/libc.so.6
(gdb) inthre 1
Undefined command: "inthre".  Try "help".
(gdb) bt
#0  0x00007fa44111e1f7 in raise () from /lib64/libc.so.6
#1  0x00007fa44111f8e8 in abort () from /lib64/libc.so.6
#2  0x00007fa44115df47 in __libc_message () from /lib64/libc.so.6
#3  0x00007fa441165619 in _int_free () from /lib64/libc.so.6
#4  0x00000000004d9d8c in spdk_nvme_probe_poll_async (probe_ctx=0x2a183f0) at nvme.c:1526
#5  0x000000000040b9e0 in bdev_nvme_hotplug_probe (arg=0x0) at bdev_nvme.c:1736
#6  0x0000000000529f19 in thread_poll (thread=0x250fcd0, max_msgs=0, now=42183280010919271) at thread.c:696
#7  0x000000000052a114 in spdk_thread_poll (thread=0x250fcd0, max_msgs=0, now=42183280010919271) at thread.c:740
#8  0x0000000000521ed5 in _reactor_run (reactor=0x250f980) at reactor.c:885
#9  0x0000000000522010 in reactor_run (arg=0x250f980) at reactor.c:930
#10 0x00000000005223f0 in spdk_reactors_start () at reactor.c:1031
#11 0x000000000051f131 in spdk_app_start (opts_user=0x7ffeb39bab90, start_fn=0x405a54 <spdk_tgt_started>, arg1=0x0) at app.c:577
#12 0x0000000000405b72 in main (argc=1, argv=0x7ffeb39bad38) at spdk_tgt.c:120

## Steps to Reproduce

1. PCI_ALLOWED="none" ./scripts/setup.sh
2. start spdk_tgt
3. ./scripts/rpc.py bdev_nvme_set_hotplug -e
4. PCI_ALLOWED="0000:0b:00.0" ./scripts/setup.sh  (0000:0b:00.0 is an example)
5. exit spdk_tgt

## Context (Environment including OS version, SPDK version, etc.)

SPDK commit 6e2c2306f9339694074c7436b4b832c96fb49820

**Comment by Comphix** [comment]
Patch for this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/7002

**Comment by Comphix** [comment]
Patch merged. Close this issue.
