### ISSUE TITLE
vfio-user nvmf crash in nvmf_transport_qpair_abort_request()

### ISSUE THREAD

**Issue by jlevon** [spdk/spdk#1883]
Running current SPDK master with vfio-user nvmf, I got this crash when the backing iscsi server went down:

```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00005587bc213284 in nvmf_transport_qpair_abort_request (qpair=0x7ff45829bde0, req=0x7ff4611546f8) at transport.c:563
#2  0x00005587bc1fd757 in nvmf_qpair_abort_request (qpair=0x7ff45829bde0, req=0x7ff4611546f8) at ctrlr.c:2456
#3  0x00005587bc1fd820 in nvmf_ctrlr_abort_on_pg (i=0x7ff45827dd90) at ctrlr.c:2485
#4  0x00005587bc2acd79 in _call_channel (ctx=0x7ff45827dd90) at thread.c:1746
#5  0x00005587bc2aa1a3 in msg_queue_run_batch (thread=0x7ff458275dc0, max_msgs=8) at thread.c:553
#6  0x00005587bc2aa46a in thread_poll (thread=0x7ff458275dc0, max_msgs=0, now=2247640321374676) at thread.c:632
#7  0x00005587bc2aaa01 in spdk_thread_poll (thread=0x7ff458275dc0, max_msgs=0, now=2247640321374676) at thread.c:741
#8  0x00005587bc12c53a in nvmf_reactor_run (arg=0x7ff458001ca0) at /usr/src/debug/nutanix-frodo-1.0/nvme/nvme.c:175
#9  0x00005587bc130d17 in nvmf_tgt_main (arg=0x7ffccb71bfa8) at /usr/src/debug/nutanix-frodo-1.0/nvme/nvme.c:1153
#10 0x00007ff45fef4ea5 in start_thread () from /lib64/libpthread.so.0
#11 0x00007ff45eff098d in clone () from /lib64/libc.so.6
```

`->qpair_abort_request` has no implementation in `vfio-user.c`

cc @changpe1

**Comment by changpe1** [comment]
Right, I will add a fix patch for it.

**Comment by changpe1** [comment]
I submitted a quick fix https://review.spdk.io/gerrit/c/spdk/spdk/+/7291, I need to think about how to add ABORT support with vfio-user later.
