### ISSUE TITLE
[nvmf] run identify in nvmf_vfio_user got memory leak

### ISSUE THREAD

**Issue by yidong0635** [spdk/spdk#1885]
# Issue 
This issue not only happened here but also on other test .
```
/root/spdk/build/examples/identify -r 'trtype:VFIOUSER traddr:/var/run/muser/domain/muser1/1' -g -L nvme -L nvme_vfio -L vfio_pci
[2021-04-09 02:39:52.988095] Starting SPDK v21.04-pre git sha1 233f3f305 / DPDK 20.11.0 initialization...
[2021-04-09 02:39:52.988371] [ DPDK EAL parameters: [2021-04-09 02:39:52.988402] identify [2021-04-09 02:39:52.988425] --no-shconf [2021-04-09 02:39:52.988441] -c 0x1 [2021-04-09 02:39:52.988468] -n 1 [2021-04-09 02:39:52.988488] -m 0 [2021-04-09 02:39:52.988520] --no-pci [2021-04-09 02:39:52.988539] --single-file-segments [2021-04-09 02:39:52.988561] --log-level=lib.eal:6 [2021-04-09 02:39:52.988579] --log-level=lib.cryptodev:5 [2021-04-09 02:39:52.988601] --log-level=user1:6 [2021-04-09 02:39:52.988623] --iova-mode=pa [2021-04-09 02:39:52.988652] --base-virtaddr=0x200000000000 [2021-04-09 02:39:52.988670] --match-allocations [2021-04-09 02:39:52.988690] --file-prefix=spdk_pid35737 [2021-04-09 02:39:52.988707] ]
EAL: No free hugepages reported in hugepages-2048kB
EAL: No available hugepages reported in hugepages-1048576kB
EAL: No legacy callbacks, legacy socket not created
[2021-04-09 02:39:53.025403] nvme_vfio_user.c: 323:nvme_vfio_ctrlr_scan: *NOTICE*: Scan controller : /var/run/muser/domain/muser1/1
[2021-04-09 02:39:53.029456] vfio_user.c: 269:vfio_user_check_version: *NOTICE*: VFIO_USER_VERSION Negotiate version 0.1
[2021-04-09 02:39:53.029554] vfio_user_pci.c: 260:vfio_device_setup_sparse_mmaps: *NOTICE*: Sparse region 0, Size 0x1000, Offset 0x1000, Map addr 0x7fea6c175000
[2021-04-09 02:39:53.030594] vfio_user_pci.c: 408:spdk_vfio_user_setup: *NOTICE*: Device vfio-user0, Path /var/run/muser/domain/muser1/1/cntrl Setup Successfully
[2021-04-09 02:39:53.055456] ctrlr.c:2075:nvmf_ctrlr_get_log_page: *ERROR*: Unsupported Get Log Page 0x70
[2021-04-09 02:39:53.061464] nvme_qpair.c: 248:nvme_admin_qpair_print_command: *NOTICE*: GET LOG PAGE (02) qid:0 cid:21 nsid:0 cdw10:00ff0070 cdw11:00000000 PRP1 0x200000388000 PRP2 0x0
[2021-04-09 02:39:53.061493] nvme_qpair.c: 452:spdk_nvme_print_completion: *NOTICE*: INVALID FIELD (00/02) qid:0 cid:21 cdw0:0 sqhd:000a p:1 m:0 dnr:0
=====================================================
NVMe over Fabrics controller at /var/run/muser/domain/muser1/1:: nqn.2014-08.org.nvmexpress.discovery
=====================================================
Controller Capabilities/Features
================================
Vendor ID:                             0000
Subsystem Vendor ID:                   0000
Serial Number:                         SPDK1
Model Number:                          SPDK bdev Controller
Firmware Version:                      21.04
Recommended Arb Burst:                 6
IEEE OUI Identifier:                   00 00 00
Multi-path I/O
  May have multiple subsystem ports:   Yes
  May be connected to multiple hosts:  Yes
  Associated with SR-IOV VF:           No
Max Data Transfer Size:                131072
Max Number of Namespaces:              32
NVMe Specification Version (VS):       1.3
NVMe Specification Version (Identify): 1.3
Maximum Queue Entries:                 256
Contiguous Queues Required:            Yes
Arbitration Mechanisms Supported
  Weighted Round Robin:                Not Supported
  Vendor Specific:                     Not Supported
Reset Timeout:                         500 ms
Doorbell Stride:                       4 bytes
NVM Subsystem Reset:                   Not Supported
Command Sets Supported
  NVM Command Set:                     Supported
Boot Partition:                        Not Supported
Memory Page Size Minimum:              4096 bytes
Memory Page Size Maximum:              4096 bytes
Persistent Memory Region:              Not Supported
Optional Asynchronous Events Supported
  Namespace Attribute Notices:         Supported
  Firmware Activation Notices:         Not Supported
128-bit Host Identifier:               Supported

Controller Memory Buffer Support
================================
Supported:                             No

Persistent Memory Region Support
================================
Supported:                             No

Admin Command Set Attributes
============================
Security Send/Receive:                 Not Supported
Format NVM:                            Not Supported
Firmware Activate/Download:            Not Supported
Namespace Management:                  Not Supported
Device Self-Test:                      Not Supported
Directives:                            Not Supported
NVMe-MI:                               Not Supported
Virtualization Management:             Not Supported
Doorbell Buffer Config:                Not Supported
Abort Command Limit:                   1
Async Event Request Limit:             1
Number of Firmware Slots:              N/A
Firmware Slot 1 Read-Only:             N/A
Firmware Update Granularity:           No Information Provided
Per-Namespace SMART Log:               No
Asymmetric Namespace Access Log Page:  Not Supported
Command Effects Log Page:              Supported
Get Log Page Extended Data:            Supported
Telemetry Log Pages:                   Not Supported
Error Log Page Entries Supported:      128
Keep Alive:                            Supported
Keep Alive Granularity:                10000 ms

NVM Command Set Attributes
==========================
Submission Queue Entry Size
  Max:                       64
  Min:                       64
Completion Queue Entry Size
  Max:                       16
  Min:                       16
Number of Namespaces:        32
Compare Command:             Not Supported
Write Uncorrectable Command: Not Supported
Dataset Management Command:  Supported
Write Zeroes Command:        Supported
Set Features Save Field:     Not Supported
Reservations:                Supported
Timestamp:                   Not Supported
Volatile Write Cache:        Present
Atomic Write Unit (Normal):  1
Atomic Write Unit (PFail):   1
Atomic Compare & Write Unit: 2
Fused Compare & Write:       Supported
Scatter-Gather List
  SGL Command Set:           Supported (Dword aligned)
  SGL Keyed:                 Not Supported
  SGL Bit Bucket Descriptor: Not Supported
  SGL Metadata Pointer:      Not Supported
  Oversized SGL:             Not Supported
  SGL Metadata Address:      Not Supported
  SGL Offset:                Not Supported
  Transport SGL Data Block:  Not Supported
Replay Protected Memory Block:  Not Supported

Firmware Slot Information
=========================
Active slot:                 0


Commands Supported and Effects
==============================
Admin Commands
--------------
                  Get Log Page (02h): Supported
                      Identify (06h): Supported
                         Abort (08h): Supported
                  Set Features (09h): Supported
                  Get Features (0Ah): Supported
    Asynchronous Event Request (0Ch): Supported
                    Keep Alive (18h): Supported
I/O Commands
------------
                         Flush (00h): Supported LBA-Change
                         Write (01h): Supported LBA-Change
                          Read (02h): Supported
                       Compare (05h): Supported
                  Write Zeroes (08h): Supported LBA-Change
            Dataset Management (09h): Supported LBA-Change

Error Log
=========

Active Namespaces
=================
Namespace ID:1
Command Set Identifier:                NVM (00h)
Deallocate:                            Supported
Deallocated/Unwritten Error:           Not Supported
Deallocated Read Value:                Unknown
Deallocate in Write Zeroes:            Not Supported
Deallocated Guard Field:               0xFFFF
Flush:                                 Supported
Reservation:                           Supported
Namespace Sharing Capabilities:        Multiple Controllers
Size (in LBAs):                        131072 (0GiB)
Capacity (in LBAs):                    131072 (0GiB)
Utilization (in LBAs):                 131072 (0GiB)
UUID:                                  10f281fc-0f54-46ef-a692-96b4efa7ee3a
Thin Provisioning:                     Not Supported
Per-NS Atomic Units:                   No
NGUID/EUI64 Never Reused:              No
Number of LBA Formats:                 1
Current LBA Format:                    LBA Format #00
LBA Format #00: Data Size:   512  Metadata Size:     0

[2021-04-09 02:39:53.080490] vfio_user_pci.c: 422:spdk_vfio_user_release: *NOTICE*: Release file /var/run/muser/domain/muser1/1/cntrl
[2021-04-09 02:39:53.100490] vfio_user.c:1551:destroy_ctrlr: *NOTICE*: destroy /var/run/muser/domain/muser1/1

=================================================================
==35737==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2097240 byte(s) in 1 object(s) allocated from:
    #0 0x7fea70173f16 in __interceptor_calloc (/lib64/libasan.so.5+0x10df16)
    #1 0x5a7bb5 in spdk_mem_map_alloc /root/spdk/lib/env_dpdk/memory.c:293

SUMMARY: AddressSanitizer: 2097240 byte(s) leaked in 1 allocation(s).
  02:39:53      # trap - ERR
  02:39:53      # print_backtrace
  02:39:53      # [[ ehxBET =~ e ]]
  02:39:53      # args=("${BASH_ARGV[@]}")
  02:39:53      # local args
  02:39:53      # xtrace_disable
  02:39:53      # '[' no '!=' yes ']'
  02:39:53      # PREV_BASH_OPTS=ehxBET
  02:39:53      # [[ ehxBET == *\x* ]]
  02:39:53      # XTRACE_DISABLED=yes
  02:39:53      # set +x
========== Backtrace start: ==========

in ./test/nvmf/target/nvmf_vfio_user.sh:42 -> main([])
     ...
   37           $rpc_py nvmf_subsystem_add_ns nqn.2019-07.io.spdk:cnode$i Malloc$i
   38           $rpc_py nvmf_subsystem_add_listener nqn.2019-07.io.spdk:cnode$i -t VFIOUSER -a "/var/run/muser/domain/muser$i/$i" -s 0
   39   done
   40
   41   for i in $(seq 1 $NUM_DEVICES); do
=> 42           $SPDK_EXAMPLE_DIR/identify -r "trtype:VFIOUSER traddr:/var/run/muser/domain/muser$i/$i" -g -L nvme -L nvme_vfio -L vfio_pci
   43           sleep 1
   44           $SPDK_EXAMPLE_DIR/perf -r "trtype:VFIOUSER traddr:/var/run/muser/domain/muser$i/$i" -s 256 -g -q 128 -o 4096 -w read -t 5 -c 0x2
   45           sleep 1
   46           $SPDK_EXAMPLE_DIR/perf -r "trtype:VFIOUSER traddr:/var/run/muser/domain/muser$i/$i" -s 256 -g -q 128 -o 4096 -w write -t 5 -c 0x2
   47           sleep 1
     ...

========== Backtrace end ==========
  02:39:53      # xtrace_enable

```

## Possible Solution

https://review.spdk.io/gerrit/c/spdk/spdk/+/7249

## Steps to Reproduce

./configure --with-vfio-user --enable-asan --enable-ubsan 
./test/nvmf/target/nvmf_vfio_user.sh 
or  ./test/nvmf/host/multipath.sh (kill test while running fio)

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @optimistyzy. log: https://ci.spdk.io/public_build/autotest-per-patch_41456.html

**Comment by yidong0635** [comment]
Patch was merged, close this one.
