### ISSUE TITLE
[vhost autofuzz] Assertion `lun->reservation.flags & SCSI_SPC2_RESERVE' failed

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#1898]
## Current Behavior

Vhost fuzzer fails with `Assertion `lun->reservation.flags & SCSI_SPC2_RESERVE' failed` .

## Steps to Reproduce

1. Build SPDK with 
```
 ./configure --enable-asan --enable-ubsan --enable-debug --without-isal --with-vhost --with-virtio
```
2. Run vhost fuzzer test:
```
test/fuzz/autofuzz.sh --module=vhost --transport=all
```
3. Test fails at:
```
[...] (Full log in attachments)
Malloc2
 10:44:57       # /home/vagrant/spdk_repo/spdk/test/fuzz/../../scripts/rpc.py vhost_create_scsi_controller naa.VhostScsi0.2
 10:44:57       # /home/vagrant/spdk_repo/spdk/test/fuzz/../../scripts/rpc.py vhost_scsi_controller_add_target naa.VhostScsi0.2 0 Malloc2
0
  10:44:58      # pwd
 10:44:58       # /home/vagrant/spdk_repo/spdk/test/fuzz/../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/vagrant/spdk_repo/spdk/naa.VhostScsi0.1 -l -v
  10:44:58      # pwd
 10:44:58       # /home/vagrant/spdk_repo/spdk/test/fuzz/../../test/app/fuzz/common/fuzz_rpc.py -s /var/tmp/spdk_fuzz.sock fuzz_vhost_create_dev -s /home/vagrant/spdk_repo/spdk/naa.VhostScsi0.2 -v -m
 10:44:58       # /home/vagrant/spdk_repo/spdk/test/fuzz/../../scripts/rpc.py -s /var/tmp/spdk_fuzz.sock framework_start_init
 10:44:58       # wait 15952
Fuzzing completed.
device 0x611000001300 stats: Completed I/O: 3395262, Successful I/O: 0
device 0x611000001440 stats: Completed I/O: 3395022, Successful I/O: 13336
device 0x611000001580 stats: Completed I/O: 2542240, Successful I/O: 35
/home/vagrant/spdk_repo/spdk/test/fuzz/autofuzz_vhost.sh: line 71: 15946 Aborted                 (core dumped) "${VHOST_APP[@]}" &> "$output_dir/vhost_fuzz_tgt_output.txt"
 10:56:32       # trap - SIGINT SIGTERM exit
 10:56:32       # killprocess 15946
 10:56:32       # '[' -z 15946 ']'
 10:56:32       # kill -0 15946
/home/vagrant/spdk_repo/spdk/test/fuzz/../../test/common/autotest_common.sh: line 799: kill: (15946) - No such process
[...]
```

Fuzzer output (full log in attachments):
```
[...]
[2021-04-14 10:56:27.106549] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abf2688 req_idx 31 failed ======
[2021-04-14 10:56:27.106564] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abf3ff0 req_idx 34 failed ======
[2021-04-14 10:56:27.106578] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abf5958 req_idx 37 failed ======
[2021-04-14 10:56:27.106592] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abf72c0 req_idx 40 failed ======
[2021-04-14 10:56:27.106606] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abf8c28 req_idx 43 failed ======
[2021-04-14 10:56:27.106619] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abfa590 req_idx 46 failed ======
[2021-04-14 10:56:27.106633] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abfbef8 req_idx 49 failed ======
[2021-04-14 10:56:27.106659] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abfd860 req_idx 52 failed ======
[2021-04-14 10:56:27.106673] vhost_blk.c: 660:process_blk_task: *ERROR*: ====== Task 0x20001abff1c8 req_idx 55 failed ======
vhost: scsi_pr.c:1030: scsi2_release: Assertion `lun->reservation.flags & SCSI_SPC2_RESERVE' failed.

```

Core dump:
```
#0  0x00007fbc359a49d5 in raise () from /lib64/libc.so.6
#1  0x00007fbc3598d8a4 in abort () from /lib64/libc.so.6
#2  0x00007fbc3598d789 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007fbc3599d026 in __assert_fail () from /lib64/libc.so.6
#4  0x000000000074b1de in scsi2_release (task=0x200023c83de0) at scsi_pr.c:1030
#5  0x0000000000741d98 in bdev_scsi_process_primary (task=0x200023c83de0) at scsi_bdev.c:1946
#6  0x00000000007420b7 in bdev_scsi_execute (task=0x200023c83de0) at scsi_bdev.c:1977
#7  0x000000000072df97 in _scsi_lun_execute_task (lun=0x619000002d80, task=0x200023c83de0) at lun.c:209
#8  0x000000000072e8b5 in scsi_lun_execute_task (lun=0x619000002d80, task=0x200023c83de0) at lun.c:263
#9  0x000000000072a70c in spdk_scsi_dev_queue_task (dev=0x151b620 <g_devs>, task=0x200023c83de0) at dev.c:292
#10 0x0000000000708006 in task_submit (task=0x200023c83de0) at vhost_scsi.c:381
#11 0x000000000070e3ce in process_scsi_task (vsession=0x62d0000c8400, vq=0x62d0000c8580, req_idx=362) at vhost_scsi.c:724
#12 0x000000000070f8ec in process_vq (svsession=0x62d0000c8400, vq=0x62d0000c8580) at vhost_scsi.c:799
#13 0x000000000070fcee in vdev_worker (arg=0x62d0000c8400) at vhost_scsi.c:831
#14 0x0000000000815246 in thread_poll (thread=0x619000002880, max_msgs=0, now=2411152404360) at thread.c:644
#15 0x00000000008173e5 in spdk_thread_poll (thread=0x619000002880, max_msgs=0, now=2411152404360) at thread.c:732
#16 0x00000000007f6153 in _reactor_run (reactor=0x617000002000) at reactor.c:888
#17 0x00000000007f68c1 in reactor_run (arg=0x617000002000) at reactor.c:926
#18 0x00000000007f757d in spdk_reactors_start () at reactor.c:1034
#19 0x00000000007ec205 in spdk_app_start (opts_user=0x7ffeaec19240, start_fn=0x407c8e <vhost_started>, arg1=0x0) at app.c:577
#20 0x0000000000407ee2 in main (argc=3, argv=0x7ffeaec19458) at vhost.c:105

```

## Context (Environment including OS version, SPDK version, etc.)

SPDK 530646f60
fedora33-cloud-210413300 5.11.12-200.fc33.x86_64
gcc (GCC) 10.2.1 20201125 (Red Hat 10.2.1-9)
[output.zip](https://github.com/spdk/spdk/files/6310553/output.zip)

**Comment by jimharris** [comment]
I think it's likely that the fuzzer submitted a RELEASE without a prior RESERVE.  Probably we shouldn't be asserting but rather just failing the command with error status.

@changpe1 - can you take a look?

**Comment by changpe1** [comment]
> I think it's likely that the fuzzer submitted a RELEASE without a prior RESERVE. Probably we shouldn't be asserting but rather just failing the command with error status.
> 
> @changpe1 - can you take a look?

Yeah, we should return SCSI error status for this case, I fixed this issue via https://review.spdk.io/gerrit/c/spdk/spdk/+/7379.

**Comment by jimharris** [comment]
Patch merged.
