### ISSUE TITLE
[scheduler] spdk_top aborted and report "ERROR: AddressSanitizer: SEGV on unknown address"

### ISSUE THREAD

**Issue by ChengqiangMeng** [spdk/spdk#1899]
Run ./build/bin/spdk_top while run spdk/test/scheduler/scheduler.sh. spdk_top aborted and report "ERROR: AddressSanitizer: SEGV on unknown address".

## Current Behavior

```
spdk_top.c:803:49: runtime error: member access within null pointer of type 'const struct rpc_thread_info'
AddressSanitizer:DEADLYSIGNAL 
=================================================================
==579946==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x00000040c61d bp 0x7ffc48677a60 sp 0x7ffc48677a20 T0)
==579946==The signal is caused by a READ memory access. 
==579946==Hint: address points to the zero page.
#0 0x40c61c in sort_threads /home/mengchengqiang/spdk/app/spdk_top/spdk_top.c:803
#1 0x7f21bb7ad684 in msort_with_tmp.part.0 (/lib64/libc.so.6+0x39684) 
#2 0x7f21bb7ad5f4 in msort_with_tmp.part.0 (/lib64/libc.so.6+0x395f4)
#3 0x7f21bb7ad5f4 in msort_with_tmp.part.0 (/lib64/libc.so.6+0x395f4) 
#4 0x7f21bb7adb55 in __GI___qsort_r (/lib64/libc.so.6+0x39b55) 
#5 0x40db20 in refresh_threads_tab /home/mengchengqiang/spdk/app/spdk_top/spdk_top.c:897 
#6 0x41cdd3 in refresh_tab /home/mengchengqiang/spdk/app/spdk_top/spdk_top.c:1466
#7 0x427a53 in show_stats /home/mengchengqiang/spdk/app/spdk_top/spdk_top.c:2401
#8 0x428b91 in main /home/mengchengqiang/spdk/app/spdk_top/spdk_top.c:2521
#9 0x7f21bb797f42 in __libc_start_main (/lib64/libc.so.6+0x23f42) 
#10 0x4079bd in _start (/home/mengchengqiang/spdk/build/bin/spdk_top+0x4079bd) 

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mengchengqiang/spdk/app/spdk_top/spdk_top.c:803 in sort_threads 
==579946==ABORTING
```

## Steps to Reproduce

1. Build SPDK with
    `./configure --enable-asan --enable-ubsan --enable-debug`
2. `./test/scheduler/scheduler.sh` 
3. When it runs to the following part ("when load_balancing.sh is running")，run `./buil/bin/spdk_top`. spdk_top will abort.
```
 00:11:42#active_thread 4 100
 00:11:42 # rpc_cmd --plugin scheduler_plugin scheduler_thread_set_active 4 100
 00:11:42 # xtrace_disable
 00:11:42 # '[' no '!=' yes ']'
 00:11:42 # PREV_BASH_OPTS=ehxBET
 00:11:42 # [[ ehxBET == *\x* ]]
 00:11:42 # XTRACE_DISABLED=yes
 00:11:42 # set +x
 00:11:42 # xtrace_enable
 00:11:42 # [[ 0 == 0 ]]
 00:11:42 # sleep 2
 00:11:44# rpc_cmd framework_get_reactors
 00:11:44# xtrace_disable
 00:11:44# '[' no '!=' yes ']'
 00:11:44# PREV_BASH_OPTS=hxBET
 00:11:44# jq -r '.reactors[]'
 00:11:44# [[ hxBET == *\x* ]]
 00:11:44# XTRACE_DISABLED=yes
 00:11:44# set +x
 00:11:44# xtrace_enable
 00:11:44# [[ 0 == 0 ]]
 00:11:44 # reactor_framework='{
"lcore": 1,
"busy": 10625621060,
"idle": 25312480176,
"lw_threads": [
{
"name": "app_thread",
"id": 1,
"cpumask": "2",
"elapsed": 36196870564
}
]
}
{
"lcore": 2,
"busy": 35181474204,
"idle": 756864504,
"lw_threads": [
{
"name": "thread_cpu_2",
"id": 5,
"cpumask": "4",
"elapsed": 19407863824
}
]
}
{
"lcore": 3,
"busy": 35938242653,
"idle": 0,
"lw_threads": [
{
"name": "thread_cpu_3",
"id": 6,
"cpumask": "8",
"elapsed": 19381458084
}
]
}
{
"lcore": 4,
"busy": 35937810981,
"idle": 0,
"lw_threads": [
{
"name": "thread_cpu_4",
"id": 7,
"cpumask": "10",
"elapsed": 14971410564
}
]
}
{
"lcore": 45,
"busy": 35937953296,
"idle": 0,
"lw_threads": [
{
"name": "thread_cpu_45",
"id": 8,
"cpumask": "200000000000",
"elapsed": 14971403674
}
]
}
{
"lcore": 46,
"busy": 35937817330,
"idle": 0,
"lw_threads": [
{
"name": "thread_cpu_46",
"id": 9,
"cpumask": "400000000000",
"elapsed": 14971414758
}
]
}
{
"lcore": 47,
"busy": 34540389104,
"idle": 1397610804,
"lw_threads": [
{
"name": "thread_cpu_47",
"id": 10,
"cpumask": "800000000000",
"elapsed": 14971397500
}
]
}
{
"lcore": 48,
"busy": 35938009294,
"idle": 0,
"lw_threads": [
{
"name": "thread_cpu_48",
"id": 11,
"cpumask": "1000000000000",
"elapsed": 14971421774
},
{
"name": "thread0",
"id": 4,
"cpumask": "1e0000000001c",
"elapsed": 1772345040
}
]
}'
 00:11:44# jq -r 'select(.lcore == 1) | .lw_threads[] | select(.id == 4)'
 00:11:44 # [[ -z '' ]]
 00:11:44# jq -r 'select(.lcore == 47) | .lw_threads[] | select(.id == 4)'
 00:11:45 # [[ -z '' ]]
 00:11:45 # destroy_thread 4
 00:11:45 # rpc_cmd --plugin scheduler_plugin scheduler_thread_delete 4
 00:11:45 # xtrace_disable
 00:11:45 # '[' no '!=' yes ']'
 00:11:45 # PREV_BASH_OPTS=ehxBET
 00:11:45 # [[ ehxBET == *\x* ]]
 00:11:45 # XTRACE_DISABLED=yes
 00:11:45 # set +x
 00:11:45 # xtrace_enable
 00:11:45 # [[ 0 == 0 ]]
 00:11:45 # for thread in "${extra_threads[@]}"
 00:11:45 # destroy_thread 5
 00:11:45 # rpc_cmd --plugin scheduler_plugin scheduler_thread_delete 5
 00:11:45 # xtrace_disable
 00:11:45 # '[' no '!=' yes ']'
 00:11:45 # PREV_BASH_OPTS=ehxBET
 00:11:45 # [[ ehxBET == *\x* ]]
 00:11:45 # XTRACE_DISABLED=yes
 00:11:45 # set +x
 00:11:45 # xtrace_enable
 00:11:45 # [[ 0 == 0 ]]
 00:11:45 # for thread in "${extra_threads[@]}"
 00:11:45 # destroy_thread 6
 00:11:45 # rpc_cmd --plugin scheduler_plugin scheduler_thread_delete 6
 00:11:45 # xtrace_disable
 00:11:45 # '[' no '!=' yes ']'
 00:11:45 # PREV_BASH_OPTS=ehxBET
 00:11:45 # [[ ehxBET == *\x* ]]
 00:11:45 # XTRACE_DISABLED=yes
 00:11:45 # set +x
 00:11:45 # xtrace_enable
 00:11:45 # [[ 0 == 0 ]]
 00:11:45 # for thread in "${extra_threads[@]}"
 00:11:45 # destroy_thread 7
 00:11:45 # rpc_cmd --plugin scheduler_plugin scheduler_thread_delete 7
 00:11:45 # xtrace_disable
 00:11:45 # '[' no '!=' yes ']'
 00:11:45 # PREV_BASH_OPTS=ehxBET
 00:11:45 # [[ ehxBET == *\x* ]]
 00:11:45 # XTRACE_DISABLED=yes
 00:11:45 # set +x
 00:11:45 # xtrace_enable
 00:11:45 # [[ 0 == 0 ]]
 00:11:45 # for thread in "${extra_threads[@]}"
 00:11:45 # destroy_thread 8
 00:11:45 # rpc_cmd --plugin scheduler_plugin scheduler_thread_delete 8
 00:11:45 # xtrace_disable
 00:11:45 # '[' no '!=' yes ']'
 00:11:45 # PREV_BASH_OPTS=ehxBET
 00:11:45 # [[ ehxBET == *\x* ]]
 00:11:45 # XTRACE_DISABLED=yes
 00:11:45 # set +x
 00:11:45 # xtrace_enable
 00:11:45 # [[ 0 == 0 ]]
 00:11:45 # for thread in "${extra_threads[@]}"
 00:11:45 # destroy_thread 9
 00:11:45 # rpc_cmd --plugin scheduler_plugin scheduler_thread_delete 9
 00:11:45 # xtrace_disable
 00:11:45 # '[' no '!=' yes ']'
 00:11:45 # PREV_BASH_OPTS=ehxBET
 00:11:45 # [[ ehxBET == *\x* ]]
```

## Context (Environment including OS version, SPDK version, etc.)

commit:       dad0a6077
OS version：Fedora30 Linux version 5.4.59  (gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)) #2 SMP

**Comment by changpe1** [comment]
@ChengqiangMeng can you take a look for this issue?

**Comment by ChengqiangMeng** [comment]
here is the patch: https://review.spdk.io/gerrit/c/spdk/spdk/+/7493
