### ISSUE TITLE
heap corruption after disconnecting from NVMe target with a reservation key registered with more than 1 client connected

### ISSUE THREAD

**Issue by jonathan-teh** [spdk/spdk#1928]
## Expected Behavior

A subsequent connect to the same NVMe target or getting an NVMe reservation report should succeed.

## Current Behavior

glibc reports either `corrupted size vs. prev_size` on `calloc()` or `double free or corruption (!prev)` on `free()` and `spdk_tgt` aborts. See reproducers.

## Possible Solution

Not investigated.

## Steps to Reproduce
This requires 2 NVMe clients (one of which can be on the same host as SPDK). I was unable to reproduce with only 1 client.

1. With `spdk_tgt` running, create an aio bdev and allow it to be accessed over an NVMe namespace. I use this script (as root):
```
truncate -s 128M /tmp/aio0.img
scripts/rpc.py bdev_aio_create /tmp/aio0.img aio0 512
scripts/rpc.py nvmf_create_subsystem nqn.2021-03.spdk:aio0 -a
scripts/rpc.py nvmf_subsystem_add_ns nqn.2021-03.spdk:aio0 aio0
scripts/rpc.py nvmf_create_transport -t tcp
scripts/rpc.py nvmf_subsystem_add_listener -t tcp -a 192.168.122.1 -s 4420 nqn.2021-03.spdk:aio0
```
2. On client 1, connect to the NVMe target and register an NVMe reservation key:
```
# nvme connect -t tcp -a 192.168.122.1 -s 4420 -n nqn.2021-03.spdk:aio0
# nvme resv-register -c1 /dev/nvme0n1 -k123
# nvme resv-report -c1 /dev/nvme0n1
NVME Reservation Report success

NVME Reservation status:

gen       : 1
rtype     : 0
regctl    : 1
ptpls     : 0
regctlext[0] :
  cntlid     : ffff
  rcsts      : 0
  rkey       : 7b
  hostid     : 7c5a00da534140bf88c5412bc84b
```
3. On client 2, connect to the same NVMe target.
4. On client 1, disconnect from that target and try to reconnect:
```
# nvme disconnect -d /dev/nvme0
# nvme connect -t tcp -a 192.168.122.1 -s 4420 -n nqn.2021-03.spdk:aio0
Failed to write to /dev/nvme-fabrics: Resource temporarily unavailable
```
5. Observe that `spdk_tgt` has aborted:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2021-05-04 13:09:02.408044] Starting SPDK v21.07-pre git sha1 63642befd / DPDK 20.11.0 initialization...
[2021-05-04 13:09:02.408178] [ DPDK EAL parameters: [2021-05-04 13:09:02.408203] spdk_tgt [2021-05-04 13:09:02.408218] --no-shconf [2021-05-04 13:09:02.408231] -c 0x1 [2021-05-04 13:09:02.408246] --log-level=lib.eal:6 [2021-05-04 13:09:02.408261] --log-level=lib.cryptodev:5 [2021-05-04 13:09:02.408277] --log-level=user1:6 [2021-05-04 13:09:02.408292] --iova-mode=pa [2021-05-04 13:09:02.408307] --base-virtaddr=0x200000000000 [2021-05-04 13:09:02.408323] --match-allocations [2021-05-04 13:09:02.408338] --file-prefix=spdk_pid20860 [2021-05-04 13:09:02.408353] ]
[New Thread 0x7ffff7984700 (LWP 20864)]
EAL: No available hugepages reported in hugepages-1048576kB
[New Thread 0x7ffff7183700 (LWP 20865)]
EAL: No legacy callbacks, legacy socket not created
[2021-05-04 13:09:02.540429] app.c: 535:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-05-04 13:09:02.682682] reactor.c: 929:reactor_run: *NOTICE*: Reactor started on core 0
[2021-05-04 13:09:02.682760] accel_engine.c: 852:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-05-04 13:09:04.311787] tcp.c: 551:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2021-05-04 13:09:04.458482] tcp.c: 745:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 192.168.122.1 port 4420 ***
corrupted size vs. prev_size

Thread 1 "reactor_0" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a4d859 in __GI_abort () at abort.c:79
#2  0x00007ffff7ab83ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7be2285 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7ac047c in malloc_printerr (str=str@entry=0x7ffff7be043a "corrupted size vs. prev_size") at malloc.c:5347
#4  0x00007ffff7ac0aeb in unlink_chunk (p=p@entry=0x5555573cd2f0, av=0x7ffff7c13b80 <main_arena>) at malloc.c:1454
#5  0x00007ffff7ac0c2f in malloc_consolidate (av=av@entry=0x7ffff7c13b80 <main_arena>) at malloc.c:4502
#6  0x00007ffff7ac2e03 in _int_malloc (av=av@entry=0x7ffff7c13b80 <main_arena>, bytes=bytes@entry=1888) at malloc.c:3699
#7  0x00007ffff7ac6d15 in __libc_calloc (n=<optimised out>, elem_size=<optimised out>) at malloc.c:3428
#8  0x000055555560af03 in nvmf_tcp_handle_connect (sock=<optimised out>, port=0x55555740fa90, transport=0x5555575c05c0)
    at tcp.c:1074
#9  nvmf_tcp_port_accept (port=<optimised out>, transport=<optimised out>) at tcp.c:1074
#10 nvmf_tcp_accept (transport=0x5555575c05c0) at tcp.c:1090
#11 0x000055555560036c in nvmf_tgt_accept (ctx=<optimised out>) at nvmf.c:243
#12 0x00005555556623ed in thread_poll (thread=thread@entry=0x55555734c240, max_msgs=max_msgs@entry=0, now=now@entry=39748709190003)
    at thread.c:688
#13 0x0000555555662eb0 in spdk_thread_poll (thread=thread@entry=0x55555734c240, max_msgs=max_msgs@entry=0, now=39748709190003)
    at thread.c:733
#14 0x000055555565e629 in _reactor_run (reactor=0x55555734be40) at reactor.c:906
#15 reactor_run (arg=0x55555734be40) at reactor.c:944
#16 0x000055555565e9e7 in spdk_reactors_start () at reactor.c:1052
#17 0x000055555565b940 in spdk_app_start (opts_user=<optimised out>, start_fn=0x555555592180 <spdk_tgt_started>, arg1=0x0)
    at app.c:577
#18 0x000055555558d381 in main (argc=1, argv=0x7fffffffe5a8) at spdk_tgt.c:120
```
That describes the reproducer which exposes heap-corruption via `calloc()`. This other reproducer is via `free()`.

6. Follow steps 1-2 earlier.
7. On client 2, connect to the NVMe target, register an NVMe reservation key, then disconnect:
```
# nvme connect -t tcp -a 192.168.122.1 -s 4420 -n nqn.2021-03.spdk:aio0
# nvme resv-register -c1 /dev/nvme0n1 -k234
NVME Reservation  success
# nvme disconnect -d /dev/nvme0
```
7. On client 1, get the NVMe Reservation Report:
```
# nvme resv-report -c1 /dev/nvme0n1
NVME IO command error:0371
```
8. Observe that `spdk_tgt` has aborted:
```
[2021-05-04 13:26:31.439037] Starting SPDK v21.07-pre git sha1 63642befd / DPDK 20.11.0 initialization...
[2021-05-04 13:26:31.439102] [ DPDK EAL parameters: [2021-05-04 13:26:31.439112] spdk_tgt [2021-05-04 13:26:31.439121] --no-shconf [2021-05-04 13:26:31.439128] -c 0x1 [2021-05-04 13:26:31.439135] --log-level=lib.eal:6 [2021-05-04 13:26:31.439142] --log-level=lib.cryptodev:5 [2021-05-04 13:26:31.439148] --log-level=user1:6 [2021-05-04 13:26:31.439154] --iova-mode=pa [2021-05-04 13:26:31.439160] --base-virtaddr=0x200000000000 [2021-05-04 13:26:31.439166] --match-allocations [2021-05-04 13:26:31.439172] --file-prefix=spdk_pid21287 [2021-05-04 13:26:31.439179] ]
[New Thread 0x7ffff7984700 (LWP 21291)]
EAL: No available hugepages reported in hugepages-1048576kB
[New Thread 0x7ffff7183700 (LWP 21293)]
EAL: No legacy callbacks, legacy socket not created
[2021-05-04 13:26:31.566381] app.c: 535:spdk_app_start: *NOTICE*: Total cores available: 1
[2021-05-04 13:26:31.702830] reactor.c: 929:reactor_run: *NOTICE*: Reactor started on core 0
[2021-05-04 13:26:31.702911] accel_engine.c: 852:spdk_accel_engine_initialize: *NOTICE*: Accel engine initialized to use software engine.
[2021-05-04 13:26:56.991773] tcp.c: 551:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2021-05-04 13:26:57.138472] tcp.c: 745:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 192.168.122.1 port 4420 ***
double free or corruption (!prev)

Thread 1 "reactor_0" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7a4d859 in __GI_abort () at abort.c:79
#2  0x00007ffff7ab83ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7be2285 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#3  0x00007ffff7ac047c in malloc_printerr (str=str@entry=0x7ffff7be4690 "double free or corruption (!prev)") at malloc.c:5347
#4  0x00007ffff7ac212c in _int_free (av=0x7ffff7c13b80 <main_arena>, p=0x555557a2ab80, have_lock=<optimised out>) at malloc.c:4317
#5  0x00005555555ffd48 in nvmf_ns_reservation_report (ctrlr=<optimised out>, req=0x555557aebe88, ns=0x555557570ac0)
    at subsystem.c:2701
#6  nvmf_ns_reservation_request (ctx=0x555557aebe88) at subsystem.c:2753
#7  0x000055555566225f in msg_queue_run_batch (max_msgs=<optimised out>, thread=0x55555734c240) at thread.c:544
#8  thread_poll (thread=thread@entry=0x55555734c240, max_msgs=max_msgs@entry=0, now=now@entry=43436451179779) at thread.c:623
#9  0x0000555555662eb0 in spdk_thread_poll (thread=thread@entry=0x55555734c240, max_msgs=max_msgs@entry=0, now=43436451179779)
    at thread.c:733
#10 0x000055555565e629 in _reactor_run (reactor=0x55555734be40) at reactor.c:906
#11 reactor_run (arg=0x55555734be40) at reactor.c:944
#12 0x000055555565e9e7 in spdk_reactors_start () at reactor.c:1052
#13 0x000055555565b940 in spdk_app_start (opts_user=<optimised out>, start_fn=0x555555592180 <spdk_tgt_started>, arg1=0x0)
    at app.c:577
#14 0x000055555558d381 in main (argc=1, argv=0x7fffffffe5a8) at spdk_tgt.c:120
```

## Context (Environment including OS version, SPDK version, etc.)

Ubuntu 20.04 (kernel 5.4.0-72-generic), SPDK 21.07-pre git sha1 63642befd (current as of 2021-05-04 1220Z)

Also reproducible with SPDK 21.04.

**Comment by changpe1** [comment]
Thanks for reporting, I will take a look.

**Comment by changpe1** [comment]
I fixed this issue via https://review.spdk.io/gerrit/c/spdk/spdk/+/7822.

**Comment by jonathan-teh** [comment]
Thanks, I've tested the fix and it works for me.
