### ISSUE TITLE
Segmentation fault in nvme_request_remove_child when trying to fail a controller that has queued aborts

### ISSUE THREAD

**Issue by rmvasuki** [spdk/spdk#2022]
We hit a segfault in our application when trying to fail a controller by calling `spdk_nvme_ctrlr_fail`.

## Expected Behavior

No segmentation fault.

## Current Behavior

Segmentation fault with this stacktrace:
```
#0  nvme_request_remove_child (parent=0x0, parent=0x0, child=0x2000b5600940) at nvme_internal.h:1098
#1  nvme_complete_abort_request (ctx=0x2000b5600940, cpl=0x2000b56009e4) at nvme_ctrlr_cmd.c:669
#2  0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5600940, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#3  nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#4  0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#5  nvme_complete_abort_request (ctx=0x2000b5600a80, cpl=0x2000b5600b24) at nvme_ctrlr_cmd.c:667
#6  0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5600a80, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#7  nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#8  0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#9  nvme_complete_abort_request (ctx=0x2000b5600bc0, cpl=0x2000b5600c64) at nvme_ctrlr_cmd.c:667
#10 0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5600bc0, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#11 nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#12 0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#13 nvme_complete_abort_request (ctx=0x2000b5600e40, cpl=0x2000b5600ee4) at nvme_ctrlr_cmd.c:667
#14 0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5600e40, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#15 nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#16 0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#17 nvme_complete_abort_request (ctx=0x2000b5600f80, cpl=0x2000b5601024) at nvme_ctrlr_cmd.c:667
#18 0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5600f80, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#19 nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#20 0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#21 nvme_complete_abort_request (ctx=0x2000b56010c0, cpl=0x2000b5601164) at nvme_ctrlr_cmd.c:667
#22 0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b56010c0, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#23 nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#24 0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#25 nvme_complete_abort_request (ctx=0x2000b5601340, cpl=0x2000b56013e4) at nvme_ctrlr_cmd.c:667
#26 0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5601340, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#27 nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#28 0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#29 nvme_complete_abort_request (ctx=0x2000b5601480, cpl=0x2000b5601524) at nvme_ctrlr_cmd.c:667
#30 0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5601480, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#31 nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#32 0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#33 nvme_complete_abort_request (ctx=0x2000b56015c0, cpl=0x2000b5601664) at nvme_ctrlr_cmd.c:667
#34 0x0000555555614dac in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b56015c0, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#35 nvme_ctrlr_retry_queued_abort (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr_cmd.c:587
#36 0x0000555555614f34 in nvme_ctrlr_retry_queued_abort (ctrlr=<optimized out>) at nvme_ctrlr_cmd.c:667
#37 nvme_complete_abort_request (ctx=0x2000b5601d40, cpl=0x7ffa83df1570) at nvme_ctrlr_cmd.c:667
#38 0x0000555555634a79 in nvme_complete_request (qpair=<optimized out>, cpl=<optimized out>, req=0x2000b5601d40, cb_arg=<optimized out>, cb_fn=<optimized out>) at nvme_internal.h:1056
#39 nvme_rdma_req_complete (rdma_req=rdma_req@entry=0x7ffa2c241060, rsp=rsp@entry=0x7ffa83df1570) at nvme_rdma.c:391
#40 0x0000555555634c9f in nvme_rdma_qpair_abort_reqs (qpair=0x7ffa2c23a1f0, dnr=<optimized out>) at nvme_rdma.c:2149
#41 0x000055555562a727 in nvme_transport_ctrlr_disconnect_qpair (ctrlr=ctrlr@entry=0x7ffa2c23e1c0, qpair=0x7ffa2c23a1f0) at nvme_transport.c:350
#42 0x0000555555617d00 in nvme_ctrlr_fail (ctrlr=ctrlr@entry=0x7ffa2c23e1c0, hot_remove=hot_remove@entry=false) at nvme_ctrlr.c:803
#43 0x0000555555617d59 in spdk_nvme_ctrlr_fail (ctrlr=0x7ffa2c23e1c0) at nvme_ctrlr.c:816
```

## Possible Solution
```
diff --git a/lib/nvme/nvme_ctrlr_cmd.c b/lib/nvme/nvme_ctrlr_cmd.c
index 64b406f..2331d41 100644
--- a/lib/nvme/nvme_ctrlr_cmd.c
+++ b/lib/nvme/nvme_ctrlr_cmd.c
@@ -570,7 +570,7 @@ nvme_ctrlr_retry_queued_abort(struct spdk_nvme_ctrlr *ctrlr)
        struct nvme_request     *next, *tmp;
        int rc;
-       if (ctrlr->is_resetting || ctrlr->is_destructed) {
+       if (ctrlr->is_resetting || ctrlr->is_destructed || ctrlr->is_failed) {
                return;
        }
```

## Steps to Reproduce

This bug report was filed by a partner team, so I don't have a list of steps to reproduce the issue.
However, I believe this may reproduce the issue:
1. Issue a large number of aborts, so that some of them are queued up on the `ctrlr->queued_aborts` queue.
2. Try to fail the controller by calling `spdk_nvme_ctrlr_fail`

## Context (Environment including OS version, SPDK version, etc.)

This issue was seen on SPDK v20.07.

**Comment by rmvasuki** [comment]
I've provided a build to the team that reported the issue, if the fix works, I can submit the patch for it.

**Comment by changpe1** [comment]
here is the patch set https://review.spdk.io/gerrit/c/spdk/spdk/+/8585

**Comment by jimharris** [comment]
Patch merged.  Thanks!
