### ISSUE TITLE
NVMf/vfio-user: assertion failure when spamming FLR

### ISSUE THREAD

**Issue by tmakatos** [spdk/spdk#2043]
Using SPDK b8b1f1922 (Debian guest, 8 vCPUs, KVM enabled), spammig FLR results in SPDK asserting. In the guest:
```
while true; do
        echo 1 > /sys/bus/pci/devices/0000\:00\:03.0/reset
done
```
SPDK:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/root/src/spdk/build/bin/nvmf_tgt -i 0 -e 0xFFFF -m 0x1'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7f21571d0980 (LWP 76619))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f21573f3535 in __GI_abort () at abort.c:79
#2  0x00007f21573f340f in __assert_fail_base (fmt=0x7f2157555ee0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7f2157bf7578 "ctrlr->qp[cmd->cdw10_bits.delete_io_q.qid]->state == VFIO_USER_QPAIR_ACTIVE",
    file=0x7f2157bf704b "vfio_user.c", line=982, function=<optimized out>) at assert.c:92
#3  0x00007f2157401102 in __GI___assert_fail (assertion=0x7f2157bf7578 "ctrlr->qp[cmd->cdw10_bits.delete_io_q.qid]->state == VFIO_USER_QPAIR_ACTIVE", file=0x7f2157bf704b "vfio_user.c", line=982,
    function=0x7f2157bf8030 <__PRETTY_FUNCTION__.18977> "handle_del_io_q") at assert.c:101
#4  0x00007f2157bdb5ed in handle_del_io_q (ctrlr=0x556fa765a650, cmd=0x7f20b5d53200, is_cq=false) at vfio_user.c:982
#5  0x00007f2157bdb778 in consume_admin_cmd (ctrlr=0x556fa765a650, cmd=0x7f20b5d53200) at vfio_user.c:1011
#6  0x00007f2157bdba5d in consume_cmd (ctrlr=0x556fa765a650, qpair=0x556fa765a8b0, cmd=0x7f20b5d53200) at vfio_user.c:1062
#7  0x00007f2157bdbb3d in handle_sq_tdbl_write (ctrlr=0x556fa765a650, new_tail=9, qpair=0x556fa765a8b0) at vfio_user.c:1088
#8  0x00007f2157bdf4c1 in nvmf_vfio_user_qpair_poll (qpair=0x556fa765a8b0) at vfio_user.c:2409
#9  0x00007f2157bdf547 in nvmf_vfio_user_poll_group_poll (group=0x556fa7662c70) at vfio_user.c:2440
#10 0x00007f2157bd04c2 in nvmf_transport_poll_group_poll (group=0x556fa7662c70) at transport.c:517
#11 0x00007f2157bc657e in nvmf_poll_group_poll (ctx=0x556fa7649500) at nvmf.c:100
#12 0x00007f2157a8b62e in thread_execute_poller (thread=0x556fa7649110, poller=0x556fa7659590) at thread.c:793
#13 0x00007f2157a8bacf in thread_poll (thread=0x556fa7649110, max_msgs=0, now=211580847899863) at thread.c:915
#14 0x00007f2157a8bbff in spdk_thread_poll (thread=0x556fa7649110, max_msgs=0, now=211580847899863) at thread.c:966
#15 0x00007f2157c1ceab in _reactor_run (reactor=0x556fa7645600) at reactor.c:924
#16 0x00007f2157c1cf9c in reactor_run (arg=0x556fa7645600) at reactor.c:962
#17 0x00007f2157c1d3c2 in spdk_reactors_start () at reactor.c:1070
#18 0x00007f2157c19f5a in spdk_app_start (opts_user=0x7fff0f0b5ee0, start_fn=0x556fa59a51be <nvmf_tgt_started>, arg1=0x0) at app.c:579
#19 0x0000556fa59a52ca in main (argc=7, argv=0x7fff0f0b6088) at nvmf_main.c:75
```

**Comment by changpe1** [comment]
CREATE IO QUEUE PAIR is a synchronous API while the NVMf library is using a poller to connect this queue pair, so here we need to process CREATE/DELETE IO QUEUE PAIR in the asynchronous way. I will provide a fix.

**Comment by changpe1** [comment]
Here is the patch for Create IO SQ https://review.spdk.io/gerrit/c/spdk/spdk/+/8786, the Delete IO SQ also need a patch.

**Comment by tomzawadzki** [comment]
Patch fixing this issue has been merged.

**Comment by tmakatos** [comment]
@tomzawadzki FLR doesn't work, see my comment here: https://review.spdk.io/gerrit/c/spdk/spdk/+/7689

**Comment by jlevon** [comment]
FLR works for me with latest bits?

**Comment by jlevon** [comment]
unless this is jsut referring to the pending reset CR?

**Comment by changpe1** [comment]
My Linux VM doesn't report any error when doing "echo 1 >/sys/bus/pci/devices/0000\:00\:04.0/reset", but I didn't add the FLR callback in SPDK vfio-user target.

**Comment by tmakatos** [comment]
Have you tried the repro I pasted on the gerrit review?
