### ISSUE TITLE
[nvmf_rpc] segmentation fault while detaching controller

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2136]
After sending `bdev_nvme_detach_controller`, the target app was killed with `SIGSEGV`. It appears that this happened, because the qpair got deleted before it was connected.

## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/57112/archive/nvme-cmb-pmr-vg-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_57112.html

## Execution failed at
```
00:06:09.276   11:35:52	-- nvme/nvme_rpc.sh@18 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:00:06.0
00:06:09.511  Nvme0n1
00:06:09.527   11:35:52	-- nvme/nvme_rpc.sh@24 -- # '[' -f non_existing_file ']'
00:06:09.527   11:35:52	-- nvme/nvme_rpc.sh@29 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_nvme_apply_firmware non_existing_file Nvme0n1
00:06:09.739  [2021-08-27 11:35:52.879464] nvme_qpair.c: 249:nvme_admin_qpair_print_command: *NOTICE*: DELETE IO SQ (00) qid:0 cid:23 nsid:0 cdw10:00000001 cdw11:00000000 
00:06:09.740  [2021-08-27 11:35:52.879710] nvme_qpair.c: 453:spdk_nvme_print_completion: *NOTICE*: INVALID QUEUE IDENTIFIER (01/01) qid:0 cid:23 cdw0:0 sqhd:0012 p:1 m:0 dnr:1
00:06:09.744  request:
00:06:09.744  {
00:06:09.744    "filename": "non_existing_file",
00:06:09.744    "bdev_name": "Nvme0n1",
00:06:09.744    "method": "bdev_nvme_apply_firmware",
00:06:09.744    "req_id": 1
00:06:09.744  }
00:06:09.744  Got JSON-RPC error response
00:06:09.744  response:
00:06:09.744  {
00:06:09.744    "code": -32603,
00:06:09.744    "message": "open file failed."
00:06:09.744  }
00:06:09.766   11:35:52	-- nvme/nvme_rpc.sh@29 -- # rv=1
00:06:09.767   11:35:52	-- nvme/nvme_rpc.sh@30 -- # '[' -z 1 ']'
00:06:09.767   11:35:52	-- nvme/nvme_rpc.sh@34 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_nvme_detach_controller Nvme0
00:06:12.168  Traceback (most recent call last):
00:06:12.168    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2776, in <module>
00:06:12.170      call_rpc_func(args)
00:06:12.170    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2694, in call_rpc_func
00:06:12.170      args.func(args)
00:06:12.170    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 572, in bdev_nvme_detach_controller
00:06:12.170      rpc.bdev.bdev_nvme_detach_controller(args.client,
00:06:12.171    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/bdev.py", line 615, in bdev_nvme_detach_controller
00:06:12.171      return client.call('bdev_nvme_detach_controller', params)
00:06:12.171    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 183, in call
00:06:12.171      response = self.recv()
00:06:12.172    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 161, in recv
00:06:12.172      newdata = self.sock.recv(4096)
00:06:12.172  ConnectionResetError: [Errno 104] Connection reset by peer
00:06:12.188  test/nvme/nvme_rpc.sh: line 34: 21298 Segmentation fault      (core dumped) $SPDK_BIN_DIR/spdk_tgt -m 0x3
00:06:12.188    11:35:55	-- nvme/nvme_rpc.sh@34 -- # trap - ERR
00:06:12.189    11:35:55	-- nvme/nvme_rpc.sh@34 -- # print_backtrace
00:06:12.189    11:35:55	-- common/autotest_common.sh@985 -- # [[ ehxBET =~ e ]]
00:06:12.189    11:35:55	-- common/autotest_common.sh@987 -- # args=("${BASH_ARGV[@]}")
00:06:12.190    11:35:55	-- common/autotest_common.sh@987 -- # local args
00:06:12.190    11:35:55	-- common/autotest_common.sh@989 -- # xtrace_disable
00:06:12.190    11:35:55	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:06:12.190    11:35:55	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:06:12.191    11:35:55	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:06:12.191    11:35:55	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:06:12.191    11:35:55	-- common/autotest_common.sh@19 -- # set +x
```

**Comment by ksztyber** [comment]
Patch merged.
