### ISSUE TITLE
[nvme_tcp] poll_group was used after free and caused NULL pointer access

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#2170]
# Bug report

By the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9515/3 when an I/O qpair is disconnected, all related I/O qpairs are freed. In this operation, the corresponding poll groups were removed. Then unexpected NULL pointer access occurred.

https://ci.spdk.io/results/autotest-per-patch/builds/58563/archive/nvmf-tcp-uring-vg-autotest/build.log

>00:15:08.785  [2021-09-21 16:00:10.796650] nvme_qpair.c: 752:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 1
00:15:08.785  [2021-09-21 16:00:10.796664] bdev_nvme.c: 538:bdev_nvme_disconnected_qpair_cb: *NOTICE*: qpair 0x7fa98c149430 is disconnected, free the qpair and reset controller.
00:15:08.785  nvme_tcp.c:1078:3: runtime error: member access within null pointer of type 'struct nvme_tcp_poll_group'
00:15:08.857      #0 0x7fa9eada7d14 in tcp_data_recv_crc32_done /home/vagrant/spdk_repo/spdk/lib/nvme/nvme_tcp.c:1078
00:15:08.857      #1 0x7fa9ea713a46 in spdk_accel_task_complete /home/vagrant/spdk_repo/spdk/lib/accel/accel_engine.c:127
00:15:08.857      #2 0x7fa9ea72228d in accel_comp_poll /home/vagrant/spdk_repo/spdk/lib/accel/accel_engine.c:1168
00:15:08.858      #3 0x7fa9ea643941 in thread_execute_poller /home/vagrant/spdk_repo/spdk/lib/thread/thread.c:808
00:15:08.858      #4 0x7fa9ea64535c in thread_poll /home/vagrant/spdk_repo/spdk/lib/thread/thread.c:930
00:15:08.858      #5 0x7fa9ea64570c in spdk_thread_poll /home/vagrant/spdk_repo/spdk/lib/thread/thread.c:981
00:15:08.859      #6 0x7fa9ebdd3a77 in spdk_fio_poll_thread /home/vagrant/spdk_repo/spdk/examples/bdev/fio_plugin/fio_plugin.c:793
00:15:08.859      #7 0x7fa9ebdcf1f7 in spdk_init_thread_poll /home/vagrant/spdk_repo/spdk/examples/bdev/fio_plugin/fio_plugin.c:305
00:15:08.859      #8 0x7fa9eb57a3f8 in start_thread (/usr/lib64/libpthread.so.0+0x93f8)
00:15:08.859      #9 0x7fa9eb32c4c2 in __clone (/usr/lib64/libc.so.6+0x1014c2)
00:15:08.859  
00:15:28.753  [2021-09-21 16:00:30.764289] ctrlr.c: 191:nvmf_ctrlr_keep_alive_poll: *NOTICE*: Disconnecting host nqn.2016-06.io.spdk:host0 from subsystem nqn.2016-06.io.spdk:cnode0 due to keep alive timeout.
00:17:49.772  Build timed out (after 15 minutes). Marking the build as failed.

## Expected Behavior

qpair->poll_group should not be accessed after it is cleared.

## Current Behavior

In lib/nvme/nvme_tcp.c, _pdu_write_done() and tcp_data_recv_crc32_done() use tqpair->qpair.poll_group without checking if it is not NULL.

## Possible Solution

_pdu_write_done() and tcp_data_recv_crc32_done() use tqpair->qpair.poll_group only if it is not NULL.

## Steps to Reproduce

The test fio_dif_digest caused this error in the CI.

## Context (Environment including OS version, SPDK version, etc.)

Latest SPDK master + the patch https://review.spdk.io/gerrit/c/spdk/spdk/+/9515/3

**Comment by shuhei-matsumoto** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/9560/1
