### ISSUE TITLE
[freebsd] nvme_rpc test failed while calling bdev_nvme_detach_controller 

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2210]
https://ci.spdk.io/results/autotest-per-patch/builds/60872/archive/freebsd-vg-autotest/build.log

Point of failure:
```
00:06:12.195   12:16:22	-- nvme/nvme_rpc.sh@34 -- # /usr/home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_nvme_detach_controller Nvme0
00:06:15.180  Traceback (most recent call last):
00:06:15.180    File "/usr/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2775, in <module>
00:06:15.180      call_rpc_func(args)
00:06:15.180    File "/usr/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2680, in call_rpc_func
00:06:15.180      args.func(args)
00:06:15.180    File "/usr/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 580, in bdev_nvme_detach_controller
00:06:15.180      subnqn=args.subnqn)
00:06:15.180    File "/usr/home/vagrant/spdk_repo/spdk/scripts/rpc/bdev.py", line 619, in bdev_nvme_detach_controller
00:06:15.180      return client.call('bdev_nvme_detach_controller', params)
00:06:15.180    File "/usr/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 183, in call
00:06:15.180      response = self.recv()
00:06:15.180    File "/usr/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 161, in recv
00:06:15.180      newdata = self.sock.recv(4096)
00:06:15.180  ConnectionResetError: [Errno 54] Connection reset by peer
00:06:15.191    12:16:25	-- nvme/nvme_rpc.sh@34 -- # trap - ERR
00:06:15.191    12:16:25	-- nvme/nvme_rpc.sh@34 -- # print_backtrace
00:06:15.191    12:16:25	-- common/autotest_common.sh@993 -- # [[ ehxBET =~ e ]]
00:06:15.192    12:16:25	-- common/autotest_common.sh@995 -- # args=()
00:06:15.192    12:16:25	-- common/autotest_common.sh@995 -- # local args
00:06:15.192    12:16:25	-- common/autotest_common.sh@997 -- # xtrace_disable
00:06:15.192    12:16:25	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:06:15.193    12:16:25	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:06:15.193    12:16:25	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:06:15.193    12:16:25	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:06:15.193    12:16:25	-- common/autotest_common.sh@19 -- # set +x
00:06:15.194  ========== Backtrace start: ==========
00:06:15.194  
00:06:15.203  in test/nvme/nvme_rpc.sh:34 -> main([])
00:06:15.203       ...
00:06:15.203     29  	$rpc_py bdev_nvme_apply_firmware non_existing_file Nvme0n1 || rv=$?
00:06:15.203     30  	if [ -z "$rv" ]; then
00:06:15.203     31  		exit 1
00:06:15.203     32  	fi
00:06:15.203     33  	
00:06:15.203  => 34  	$rpc_py bdev_nvme_detach_controller Nvme0
00:06:15.203     35  	
00:06:15.203     36  	trap - SIGINT SIGTERM EXIT
00:06:15.203     37  	killprocess $spdk_tgt_pid
00:06:15.203       ...
00:06:15.203  
00:06:15.203  ========== Backtrace end ==========
00:06:15.203    12:16:25	-- common/autotest_common.sh@1033 -- # xtrace_enable
00:06:15.203    12:16:25	-- common/autotest_common.sh@1034 -- # return 0
00:06:15.203   12:16:25	-- nvme/nvme_rpc.sh@1 -- # kill -9 7396
00:06:15.204   12:16:25	-- nvme/nvme_rpc.sh@1 -- # exit 1
00:06:15.204    12:16:25	-- common/autotest_common.sh@965 -- # trap - ERR
00:06:15.204    12:16:25	-- common/autotest_common.sh@965 -- # print_backtrace
00:06:15.204    12:16:25	-- common/autotest_common.sh@993 -- # [[ ehxBET =~ e ]]
00:06:15.205    12:16:25	-- common/autotest_common.sh@995 -- # args=('test/nvme/nvme_rpc.sh' 'nvme_rpc' '/home/vagrant/autorun-spdk.conf')
00:06:15.205    12:16:25	-- common/autotest_common.sh@995 -- # local args
00:06:15.205    12:16:25	-- common/autotest_common.sh@997 -- # xtrace_disable
00:06:15.205    12:16:25	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:06:15.205    12:16:25	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:06:15.206    12:16:25	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:06:15.206    12:16:25	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:06:15.206    12:16:25	-- common/autotest_common.sh@19 -- # set +x
00:06:15.206  ========== Backtrace start: ==========
00:06:15.206  
00:06:15.215  in /usr/home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:965 -> run_test(["nvme_rpc"],["test/nvme/nvme_rpc.sh"])
00:06:15.215       ...
00:06:15.215     960 		timing_enter $test_name
00:06:15.215     961 		echo "************************************"
00:06:15.215     962 		echo "START TEST $test_name"
00:06:15.215     963 		echo "************************************"
00:06:15.215     964 		xtrace_restore
00:06:15.215  => 965 		time "$@"
00:06:15.215     966 		xtrace_disable
00:06:15.215     967 		echo "************************************"
00:06:15.215     968 		echo "END TEST $test_name"
00:06:15.215     969 		echo "************************************"
00:06:15.215     970 		timing_exit $test_name
00:06:15.215       ...
00:06:15.221  in /usr/home/vagrant/spdk_repo/spdk/autotest.sh:232 -> main(["/home/vagrant/autorun-spdk.conf"])
00:06:15.221       ...
00:06:15.221     227 				run_test "nvme_cuse" test/nvme/cuse/nvme_cuse.sh
00:06:15.221     228 			fi
00:06:15.221     229 			if [[ $SPDK_TEST_NVME_CMB -eq 1 ]]; then
00:06:15.221     230 				run_test "nvme_cmb" test/nvme/cmb/cmb.sh
00:06:15.221     231 			fi
00:06:15.221  => 232 			run_test "nvme_rpc" test/nvme/nvme_rpc.sh
00:06:15.221     233 			# Only test hotplug without ASAN enabled. Since if it is
00:06:15.221     234 			# enabled, it catches SEGV earlier than our handler which
00:06:15.221     235 			# breaks the hotplug logic.
00:06:15.221     236 			if [ $SPDK_RUN_ASAN -eq 0 ]; then
00:06:15.221     237 				run_test "nvme_hotplug" test/nvme/hotplug.sh
00:06:15.221       ...
00:06:15.221  
00:06:15.221  ========== Backtrace end ==========
```

Quite unexpected, not sure why this suddenly could fail.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @floatious. log: https://ci.spdk.io/public_build/autotest-per-patch_61720.html

**Comment by floatious** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/61720/archive/nvme-cmb-pmr-vg-autotest/build.log

Not on FreeBSD, but spdk_tgt seems to segfault when it gets a bdev_nvme_detach_controller,
so I assume that it is the same bug.

00:05:12.703   10:20:33	-- nvme/nvme_rpc.sh@34 -- # /home/vagrant/spdk_repo/spdk/scripts/rpc.py bdev_nvme_detach_controller Nvme0
00:05:18.745  Traceback (most recent call last):
00:05:18.745    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2793, in <module>
00:05:18.746      call_rpc_func(args)
00:05:18.746    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 2698, in call_rpc_func
00:05:18.747      args.func(args)
00:05:18.747    File "/home/vagrant/spdk_repo/spdk/scripts/rpc.py", line 581, in bdev_nvme_detach_controller
00:05:18.748      rpc.bdev.bdev_nvme_detach_controller(args.client,
00:05:18.748    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/bdev.py", line 637, in bdev_nvme_detach_controller
00:05:18.748      return client.call('bdev_nvme_detach_controller', params)
00:05:18.748    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 183, in call
00:05:18.748      response = self.recv()
00:05:18.748    File "/home/vagrant/spdk_repo/spdk/scripts/rpc/client.py", line 161, in recv
00:05:18.748      newdata = self.sock.recv(4096)
00:05:18.749  ConnectionResetError: [Errno 104] Connection reset by peer
00:05:18.762  test/nvme/nvme_rpc.sh: line 34: 21550 Segmentation fault      (core dumped) $SPDK_BIN_DIR/spdk_tgt -m 0x3

**Comment by changpe1** [comment]
Patch has been merged, closing this issue now.
