### ISSUE TITLE
vhost core dump when use error configuration

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#238]
## Problem Statement
SPDK core dump when testing vhost-scsi target with error configuration.
## Steps to reproduce
Change the vhost.conf.in file as Configuration
On target, Run command ./app/vhost/vhost -c ./vhost.conf.in
## Configuration
file "vhost.conf.in"
### case1:
[Global]
   LogFacility "local7"
[Rpc]
  Enable Yes
  Listen 127.0.0.1
[Ioat]
  Disable Yes
[AIO]
[Malloc]
  NumberOfLuns 3
  LunSizeInMB 128
  BlockSize 4096
[Nvme]
  TransportID "trtype:PCIe traddr:0000:03:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:81:00.0" Nvme1
  RetryCount 4
  ActionOnTimeout Yes
  Timeout 30
  AdminPollRate 100000
[Gpt]
  Disable Yes
[Split]
  Split Nvme0n1 5
[VhostScsi0]
  Name vhost.0
  **Dev  0 Malloc0
  Target  1 Malloc1**
### case2:
[Global]
   LogFacility "local7"
[Rpc]
  Enable Yes
  Listen 127.0.0.1
[Ioat]
  Disable Yes
[AIO]
[Malloc]
  NumberOfLuns 3
  LunSizeInMB 128
  BlockSize 4096
[Nvme]
  TransportID "trtype:PCIe traddr:0000:03:00.0" Nvme0
  TransportID "trtype:PCIe traddr:0000:81:00.0" Nvme1
  RetryCount 4
  ActionOnTimeout Yes
  Timeout 30
  AdminPollRate 100000
[Gpt]
  Disable Yes
[Split]
  Split Nvme0n1 5
[VhostScsi0]
  **Nam** vhost.0
  Dev  0 Malloc0

**Comment by ChenWang01** [comment]
## commit : e8650a81eefb8ab56de9eb01a8ad7eb83d763d99
## Target information:
Starting DPDK 17.11.0 initialization...
[ DPDK EAL parameters: vhost -c 0x1 -m 1024 --file-prefix=spdk_pid169957 ]
EAL: Detected 44 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
EAL: VFIO support initialized
app.c: 376:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 654:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 426:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: Cannot open /dev/vfio/46: Device or resource busy
EAL: Requested device 0000:03:00.0 cannot be used
EAL: PCI device 0000:04:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: Cannot open /dev/vfio/47: Device or resource busy
EAL: Requested device 0000:04:00.0 cannot be used
EAL: PCI device 0000:81:00.0 on NUMA socket 1
EAL:   probe driver: 8086:953 spdk_nvme
EAL: Cannot open /dev/vfio/52: Device or resource busy
EAL: Requested device 0000:81:00.0 cannot be used
VHOST_CONFIG: vhost-user server: socket created, fd: 15
VHOST_CONFIG: bind to vhost.0
vhost.c: 728:spdk_vhost_dev_register: *NOTICE*: Controller vhost.0: new controller added
vhost_scsi.c: 952:spdk_vhost_scsi_controller_construct: *ERROR*: Used both 'Dev' and 'Target' keywords in section [VhostScsi0]
Please use one.
vhost.c:1155:spdk_vhost_startup: *ERROR*: Cannot construct vhost controllers
vhost.c:1187:session_shutdown: *NOTICE*: Exiting
vhost.c: 764:spdk_vhost_dev_unregister: *NOTICE*: Controller vhost.0: removed
vhost.c:1187:session_shutdown: *NOTICE*: Exiting
*** Error in `./app/vhost/vhost': double free or corruption (!prev): 0x0000000000c4f7a0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x7f93d3b18619]
./app/vhost/vhost[0x430c19]
./app/vhost/vhost[0x430cf8]
./app/vhost/vhost[0x440ee2]
./app/vhost/vhost[0x4413bc]
./app/vhost/vhost[0x4401b4]
./app/vhost/vhost[0x4052d6]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f93d3abdc05]
./app/vhost/vhost[0x40602b]
======= Memory map: ========
00400000-00493000 r-xp 00000000 08:12 1610894400                         /home/wangchen/spdk-wang/app/vhost/vhost
00692000-00695000 r--p 00092000 08:12 1610894400                         /home/wangchen/spdk-wang/app/vhost/vhost
00695000-006a5000 rw-p 00095000 08:12 1610894400                         /home/wangchen/spdk-wang/app/vhost/vhost
006a5000-008c7000 rw-p 00000000 00:00 0
00c44000-017dc000 rw-p 00000000 00:00 0                                  [heap]
7f9380000000-7f9380021000 rw-p 00000000 00:00 0
7f9380021000-7f9384000000 ---p 00000000 00:00 0
7f9386800000-7f9386a00000 rw-s 00000000 00:22 80701105                   /dev/hugepages/spdk_pid169957map_3157
7f9386a00000-7f9386c00000 rw-s 00000000 00:22 80701104                   /dev/hugepages/spdk_pid169957map_3156
7f9386c00000-7f9386e00000 rw-s 00000000 00:22 80701103                   /dev/hugepages/spdk_pid169957map_3155
7f9386e00000-7f9387000000 rw-s 00000000 00:22 80701102                   /dev/hugepages/spdk_pid169957map_3154
7f9387000000-7f9387200000 rw-s 00000000 00:22 80701101                   /dev/hugepages/spdk_pid169957map_3153
7f9387200000-7f9387400000 rw-s 00000000 00:22 80701100                   /dev/hugepages/spdk_pid169957map_3152
7f9387400000-7f9387600000 rw-s 00000000 00:22 80701099                   /dev/hugepages/spdk_pid169957map_3151
7f9387600000-7f9387800000 rw-s 00000000 00:22 80701098                   /dev/hugepages/spdk_pid169957map_3150
7f9387800000-7f9387a00000 rw-s 00000000 00:22 80701097                   /dev/hugepages/spdk_pid169957map_3149
7f9387a00000-7f9387c00000 rw-s 00000000 00:22 80701096                   /dev/hugepages/spdk_pid169957map_3148
7f9387c00000-7f9387e00000 rw-s 00000000 00:22 80701095                   /dev/hugepages/spdk_pid169957map_3147
7f9387e00000-7f9388000000 rw-s 00000000 00:22 80701094                   /dev/hugepages/spdk_pid169957map_3146
7f9388000000-7f9388200000 rw-s 00000000 00:22 80701093                   /dev/hugepages/spdk_pid169957map_3145
7f9388200000-7f9388400000 rw-s 00000000 00:22 80701092                   /dev/hugepages/spdk_pid169957map_3144
7f9388400000-7f9388600000 rw-s 00000000 00:22 80701091                   /dev/hugepages/spdk_pid169957map_3143
7f9388600000-7f9388800000 rw-s 00000000 00:22 80701090                   /dev/hugepages/spdk_pid169957map_3142
7f9388800000-7f9388a00000 rw-s 00000000 00:22 80701089                   /dev/hugepages/spdk_pid169957map_3141
7f9388a00000-7f9388c00000 rw-s 00000000 00:22 80701088                   /dev/hugepages/spdk_pid169957map_3140
7f9388c00000-7f9388e00000 rw-s 00000000 00:22 80701087                   /dev/hugepages/spdk_pid169957map_3139
7f9388e00000-7f9389000000 rw-s 00000000 00:22 80701086                   /dev/hugepages/spdk_pid169957map_3138
7f9389000000-7f9389200000 rw-s 00000000 00:22 80701085                   /dev/hugepages/spdk_pid169957map_3137
7f9389200000-7f9389400000 rw-s 00000000 00:22 80701084                   /dev/hugepages/spdk_pid169957map_3136
7f9389400000-7f9389600000 rw-s 00000000 00:22 80701083                   /dev/hugepages/spdk_pid169957map_3135
7f9389600000-7f9389800000 rw-s 00000000 00:22 80701082                   /dev/hugepages/spdk_pid169957map_3134
7f9389800000-7f9389a00000 rw-s 00000000 00:22 80701081                   /dev/hugepages/spdk_pid169957map_3133
7f9389a00000-7f9389c00000 rw-s 00000000 00:22 80701080                   /dev/hugepages/spdk_pid169957map_3132
7f9389c00000-7f9389e00000 rw-s 00000000 00:22 80701079                   /dev/hugepages/spdk_pid169957map_3131
7f9389e00000-7f938a000000 rw-s 00000000 00:22 80701078                   /dev/hugepages/spdk_pid169957map_3130
7f938a000000-7f938a200000 rw-s 00000000 00:22 80701077                   /dev/hugepages/spdk_pid169957map_3129
7f938a200000-7f938a400000 rw-s 00000000 00:22 80701076                   /dev/hugepages/spdk_pid169957map_3128
7f938a400000-7f938a600000 rw-s 00000000 00:22 80701075                   /dev/hugepages/spdk_pid169957map_3127
7f938a600000-7f938a800000 rw-s 00000000 00:22 80701074                   /dev/hugepages/spdk_pid169957map_3126
7f938a800000-7f938aa00000 rw-s 00000000 00:22 80701073                   /dev/hugepages/spdk_pid169957map_3125
7f938aa00000-7f938ac00000 rw-s 00000000 00:22 80701072                   /dev/hugepages/spdk_pid169957map_3124
7f938ac00000-7f938ae00000 rw-s 00000000 00:22 80701071                   /dev/hugepages/spdk_pid169957map_3123
7f938ae00000-7f938b000000 rw-s 00000000 00:22 80701070                   /dev/hugepages/spdk_pid169957map_3122
7f938b000000-7f938b200000 rw-s 00000000 00:22 80701069                   /dev/hugepages/spdk_pid169957map_3121
7f938b200000-7f938b400000 rw-s 00000000 00:22 80701068                   /dev/hugepages/spdk_pid169957map_3120
7f938b400000-7f938b600000 rw-s 00000000 00:22 80701067                   /dev/hugepages/spdk_pid169957map_3119
7f938b600000-7f938b800000 rw-s 00000000 00:22 80701066                   /dev/hugepages/spdk_pid169957map_3118
7f938b800000-7f938ba00000 rw-s 00000000 00:22 80701065                   /dev/hugepages/spdk_pid169957map_3117
7f938ba00000-7f938bc00000 rw-s 00000000 00:22 80701064                   /dev/hugepages/spdk_pid169957map_3116
7f938bc00000-7f938be00000 rw-s 00000000 00:22 80701063                   /dev/hugepages/spdk_pid169957map_3115
7f938be00000-7f938c000000 rw-s 00000000 00:22 80701062                   /dev/hugepages/spdk_pid169957map_3114
7f938c000000-7f938c200000 rw-s 00000000 00:22 80701061                   /dev/hugepages/spdk_pid169957map_3113
7f938c200000-7f938c400000 rw-s 00000000 00:22 80701060                   /dev/hugepages/spdk_pid169957map_3112
7f938c400000-7f938c600000 rw-s 00000000 00:22 80701059                   /dev/hugepages/spdk_pid169957map_3111
7f938c600000-7f938c800000 rw-s 00000000 00:22 80701058                   /dev/hugepages/spdk_pid169957map_3110
7f938c800000-7f938ca00000 rw-s 00000000 00:22 80701057                   /dev/hugepages/spdk_pid169957map_3109
7f938ca00000-7f938cc00000 rw-s 00000000 00:22 80701056                   /dev/hugepages/spdk_pid169957map_3108
7f938cc00000-7f938ce00000 rw-s 00000000 00:22 80701055                   /dev/hugepages/spdk_pid169957map_3107
7f938ce00000-7f938d000000 rw-s 00000000 00:22 80701054                   /dev/hugepages/spdk_pid169957map_3106
7f938d000000-7f938d200000 rw-s 00000000 00:22 80701053                   /dev/hugepages/spdk_pid169957map_3105
7f938d200000-7f938d400000 rw-s 00000000 00:22 80701052                   /dev/hugepages/spdk_pid169957map_3104
7f938d400000-7f938d600000 rw-s 00000000 00:22 80701051                   /dev/hugepages/spdk_pid169957map_3103
7f938d600000-7f938d800000 rw-s 00000000 00:22 80701050                   /dev/hugepages/spdk_pid169957map_3102
7f938d800000-7f938da00000 rw-s 00000000 00:22 80701049                   /dev/hugepages/spdk_pid169957map_3101
7f938da00000-7f938dc00000 rw-s 00000000 00:22 80701048                   /dev/hugepages/spdk_pid169957map_3100
7f938dc00000-7f938de00000 rw-s 00000000 00:22 80701047                   /dev/hugepages/spdk_pid169957map_3099
7f938de00000-7f938e000000 rw-s 00000000 00:22 80701046                   /dev/hugepages/spdk_pid169957map_3098
7f938e000000-7f938e200000 rw-s 00000000 00:22 80701045                   /dev/hugepages/spdk_pid169957map_3097
7f938e200000-7f938e400000 rw-s 00000000 00:22 80701044                   /dev/hugepages/spdk_pid169957map_3096
7f938e400000-7f938e600000 rw-s 00000000 00:22 80701043                   /dev/hugepages/spdk_pid169957map_3095
7f938e600000-7f938e800000 rw-s 00000000 00:22 80701042                   /dev/hugepages/spdk_pid169957map_3094
7f938e800000-7f938ea00000 rw-s 00000000 00:22 80701041                   /dev/hugepages/spdk_pid169957map_3093
7f938ea00000-7f938ec00000 rw-s 00000000 00:22 80701040                   /dev/hugepages/spdk_pid169957map_3092
7f938ec00000-7f938ee00000 rw-s 00000000 00:22 80701039                   /dev/hugepages/spdk_pid169957map_3091
7f938ee00000-7f938f000000 rw-s 00000000 00:22 80701038                   /dev/hugepages/spdk_pid169957map_3090
7f938f000000-7f938f200000 rw-s 00000000 00:22 80701037                   /dev/hugepages/spdk_pid169957map_3089
7f938f200000-7f938f400000 rw-s 00000000 00:22 80701036                   /dev/hugepages/spdk_pid169957map_3088
7f938f400000-7f938f600000 rw-s 00000000 00:22 80701035                   /dev/hugepages/spdk_pid169957map_3087
7f938f600000-7f938f800000 rw-s 00000000 00:22 80701034                   /dev/hugepages/spdk_pid169957map_3086
7f938f800000-7f938fa00000 rw-s 00000000 00:22 80701033                   /dev/hugepages/spdk_pid169957map_3085
7f938fa00000-7f938fc00000 rw-s 00000000 00:22 80701032                   /dev/hugepages/spdk_pid169957map_3084
7f938fc00000-7f938fe00000 rw-s 00000000 00:22 80701031                   /dev/hugepages/spdk_pid169957map_3083
7f938fe00000-7f9390000000 rw-s 00000000 00:22 80701030                   /dev/hugepages/spdk_pid169957map_3082
7f9390000000-7f9390200000 rw-s 00000000 00:22 80701029                   /dev/hugepages/spdk_pid169957map_3081
7f9390200000-7f9390400000 rw-s 00000000 00:22 80701028                   /dev/hugepages/spdk_pid169957map_3080
7f9390400000-7f9390600000 rw-s 00000000 00:22 80701027                   /dev/hugepages/spdk_pid169957map_3079
7f9390600000-7f9390800000 rw-s 00000000 00:22 80701026                   /dev/hugepages/spdk_pid169957map_3078
7f9390800000-7f9390a00000 rw-s 00000000 00:22 80701025                   /dev/hugepages/spdk_pid169957map_3077
7f9390a00000-7f9390c00000 rw-s 00000000 00:22 80701024                   /dev/hugepages/spdk_pid169957map_3076
7f9390c00000-7f9390e00000 rw-s 00000000 00:22 80701023                   /dev/hugepages/spdk_pid169957map_3075
7f9390e00000-7f9391000000 rw-s 00000000 00:22 80701022                   /dev/hugepages/spdk_pid169957map_3074
7f9391000000-7f9391200000 rw-s 00000000 00:22 80701021                   /dev/hugepages/spdk_pid169957map_3073
7f9391200000-7f9391400000 rw-s 00000000 00:22 80701020                   /dev/hugepages/spdk_pid169957map_3072
7f9392eee000-7f9392eef000 ---p 00000000 00:00 0
7f9392eef000-7f93936ef000 rw-p 00000000 00:00 0
7f93936ef000-7f939b800000 rw-s 00000000 00:12 80677530                   /dev/shm/vhost_trace.pid169957
7f939b800000-7f939ba00000 rw-s 00000000 00:22 80701329                   /dev/hugepages/spdk_pid169957map_3381
7f939ba00000-7f939bc00000 rw-s 00000000 00:22 80701328                   /dev/hugepages/spdk_pid169957map_3380
7f939bc00000-7f939be00000 rw-s 00000000 00:22 80701327                   /dev/hugepages/spdk_pid169957map_3379
7f939be00000-7f939c000000 rw-s 00000000 00:22 80701326                   /dev/hugepages/spdk_pid169957map_3378
7f939c000000-7f939c200000 rw-s 00000000 00:22 80701325                   /dev/hugepages/spdk_pid169957map_3377
7f939c200000-7f939c400000 rw-s 00000000 00:22 80701324                   /dev/hugepages/spdk_pid169957map_3376
7f939c400000-7f939c600000 rw-s 00000000 00:22 80701323                   /dev/hugepages/spdk_pid169957map_3375
7f939c600000-7f939c800000 rw-s 00000000 00:22 80701322                   /dev/hugepages/spdk_pid169957map_3374
7f939c800000-7f939ca00000 rw-s 00000000 00:22 80701321                   /dev/hugepages/spdk_pid169957map_3373
7f939ca00000-7f939cc00000 rw-s 00000000 00:22 80701320                   /dev/hugepages/spdk_pid169957map_3372
7f939cc00000-7f939ce00000 rw-s 00000000 00:22 80701319                   /dev/hugepages/spdk_pid169957map_3371
7f939ce00000-7f939d000000 rw-s 00000000 00:22 80701318                   /dev/hugepages/spdk_pid169957map_3370
7f939d000000-7f939d200000 rw-s 00000000 00:22 80701317                   /dev/hugepages/spdk_pid169957map_3369
7f939d200000-7f939d400000 rw-s 00000000 00:22 80701316                   /dev/hugepages/spdk_pid169957map_3368
7f939d400000-7f939d600000 rw-s 00000000 00:22 80701315                   /dev/hugepages/spdk_pid169957map_3367
7f939d600000-7f939d800000 rw-s 00000000 00:22 80701314                   /dev/hugepages/spdk_pid169957map_3366
7f939d800000-7f939da00000 rw-s 00000000 00:22 80701313                   /dev/hugepages/spdk_pid169957map_3365
7f939da00000-7f939dc00000 rw-s 00000000 00:22 80701312                   /dev/hugepages/spdk_pid169957map_3364
7f939dc00000-7f939de00000 rw-s 00000000 00:22 80701311                   /dev/hugepages/spdk_pid169957map_3363
7f939de00000-7f939e000000 rw-s 00000000 00:22 80701310                   /dev/hugepages/spdk_pid169957map_3362
7f939e000000-7f939e200000 rw-s 00000000 00:22 80701309                   /dev/hugepages/spdk_pid169957map_3361
7f939e200000-7f939e400000 rw-s 00000000 00:22 80701308                   /dev/hugepages/spdk_pid169957map_3360
7f939e400000-7f939e600000 rw-s 00000000 00:22 80701307                   /dev/hugepages/spdk_pid169957map_3359
7f939e600000-7f939e800000 rw-s 00000000 00:22 80701306                   /dev/hugepages/spdk_pid169957map_3358
7f939e800000-7f939ea00000 rw-s 00000000 00:22 80701305                   /dev/hugepages/spdk_pid169957map_3357
7f939ea00000-7f939ec00000 rw-s 00000000 00:22 80701304                   /dev/hugepages/spdk_pid169957map_3356
7f939ec00000-7f939ee00000 rw-s 00000000 00:22 80701303                   /dev/hugepages/spdk_pid169957map_3355
7f939ee00000-7f939f000000 rw-s 00000000 00:22 80701302                   /dev/hugepages/spdk_pid169957map_3354
7f939f000000-7f939f200000 rw-s 00000000 00:22 80701301                   /dev/hugepages/spdk_pid169957map_3353
7f939f200000-7f939f400000 rw-s 00000000 00:22 80701300                   /dev/hugepages/spdk_pid169957map_3352
7f939f400000-7f939f600000 rw-s 00000000 00:22 80701299                   /dev/hugepages/spdk_pid169957map_3351
7f939f600000-7f939f800000 rw-s 00000000 00:22 80701298                   /dev/hugepages/spdk_pid169957map_3350
7f939f800000-7f939fa00000 rw-s 00000000 00:22 80701297                   /dev/hugepages/spdk_pid169957map_3349
7f939fa00000-7f939fc00000 rw-s 00000000 00:22 80701296                   /dev/hugepages/spdk_pid169957map_3348
7f939fc00000-7f939fe00000 rw-s 00000000 00:22 80701295                   /dev/hugepages/spdk_pid169957map_3347
7f939fe00000-7f93a0000000 rw-s 00000000 00:22 80701294                   /dev/hugepages/spdk_pid169957map_3346
7f93a0000000-7f93a0200000 rw-s 00000000 00:22 80701293                   /dev/hugepages/spdk_pid169957map_3345
7f93a0200000-7f93a0400000 rw-s 00000000 00:22 80701292                   /dev/hugepages/spdk_pid169957map_3344
7f93a0400000-7f93a0600000 rw-s 00000000 00:22 80701291                   /dev/hugepages/spdk_pid169957map_3343
7f93a0600000-7f93a0800000 rw-s 00000000 00:22 80701290                   /dev/hugepages/spdk_pid169957map_3342
7f93a0800000-7f93a0a00000 rw-s 00000000 00:22 80701289                   /dev/hugepages/spdk_pid169957map_3341
7f93a0a00000-7f93a0c00000 rw-s 00000000 00:22 80701288                   /dev/hugepages/spdk_pid169957map_3340
7f93a0c00000-7f93a0e00000 rw-s 00000000 00:22 80701287                   /dev/hugepages/spdk_pid169957map_3339
7f93a0e00000-7f93a1000000 rw-s 00000000 00:22 80701286                   /dev/hugepages/spdk_pid169957map_3338
7f93a1000000-7f93a1200000 rw-s 00000000 00:22 80701285                   /dev/hugepages/spdk_pid169957map_3337
7f93a1200000-7f93a1400000 rw-s 00000000 00:22 80701284                   /dev/hugepages/spdk_pid169957map_3336
7f93a1400000-7f93a1600000 rw-s 00000000 00:22 80701283                   /dev/hugepages/spdk_pid169957map_3335
7f93a1600000-7f93a1800000 rw-s 00000000 00:22 80701282                   /dev/hugepages/spdk_pid169957map_3334
7f93a1800000-7f93a1a00000 rw-s 00000000 00:22 80701281                   /dev/hugepages/spdk_pid169957map_3333
7f93a1a00000-7f93a1c00000 rw-s 00000000 00:22 80701280                   /dev/hugepages/spdk_pid169957map_3332
7f93a1c00000-7f93a1e00000 rw-s 00000000 00:22 80701279                   /dev/hugepages/spdk_pid169957map_3331
7f93a1e00000-7f93a2000000 rw-s 00000000 00:22 80701278                   /dev/hugepages/spdk_pid169957map_3330
7f93a2000000-7f93a2200000 rw-s 00000000 00:22 80701277                   /dev/hugepages/spdk_pid169957map_3329
7f93a2200000-7f93a2400000 rw-s 00000000 00:22 80701276                   /dev/hugepages/spdk_pid169957map_3328
7f93a2400000-7f93a2600000 rw-s 00000000 00:22 80701275                   /dev/hugepages/spdk_pid169957map_3327
7f93a2600000-7f93a2800000 rw-s 00000000 00:22 80701274                   /dev/hugepages/spdk_pid169957map_3326
7f93a2800000-7f93a2a00000 rw-s 00000000 00:22 80701273                   /dev/hugepages/spdk_pid169957map_3325
7f93a2a00000-7f93a2c00000 rw-s 00000000 00:22 80701272                   /dev/hugepages/spdk_pid169957map_3324
7f93a2c00000-7f93a2e00000 rw-s 00000000 00:22 80701271                   /dev/hugepages/spdk_pid169957map_3323
7f93a2e00000-7f93a3000000 rw-s 00000000 00:22 80701270                   /dev/hugepages/spdk_pid169957map_3322#############dev is 0tgt is 1Aborted (core dumped)

## gdb information:
#0  0x00007f93d3ad11f7 in raise () from /lib64/libc.so.6
#1  0x00007f93d3ad28e8 in abort () from /lib64/libc.so.6
#2  0x00007f93d3b10f47 in __libc_message () from /lib64/libc.so.6
#3  0x00007f93d3b18619 in _int_free () from /lib64/libc.so.6
#4  0x0000000000430c19 in _spdk_vhost_fini_remove_vdev_cb (vdev=<optimized out>, arg=0x4281d0 <spdk_vhost_subsystem_fini_done>) at vhost.c:1352
#5  0x0000000000430cf8 in spdk_vhost_call_external_event_foreach (fn=0x430bf0 <_spdk_vhost_fini_remove_vdev_cb>, arg=0x4281d0 <spdk_vhost_subsystem_fini_done>) at vhost.c:1310
#6  0x0000000000440ee2 in _spdk_event_queue_run_batch (reactor=0xc4e040, reactor=0xc4e040) at reactor.c:196
#7  _spdk_reactor_run (arg=0xc4e040) at reactor.c:438
#8  0x00000000004413bc in spdk_reactors_start () at reactor.c:628
#9  0x00000000004401b4 in spdk_app_start (opts=opts@entry=0x7ffd13668f50, start_fn=0x430e20 <spdk_vhost_startup>, arg1=0x0, arg2=arg2@entry=0x0) at app.c:434
#10 0x00000000004052d6 in main (argc=<optimized out>, argv=<optimized out>) at vhost.c:109
