### ISSUE TITLE
nvme/rdma  test fail and nvmf_tgt enters an infinite loop

### ISSUE THREAD

**Issue by fengchunsong** [spdk/spdk#2380]
# Bug report
After a perf test is performed on the nvme/rdma, the connection fails during the perf test again, and the nvmf_tgt enters an infinite loop.

## Expected Behavior
The perf test of the nvme/rdma succeeds every time.

## Current Behavior
The perf test of the nvme rdma is successfully completed for the first time.  nvmf_tgt log
[2022-02-16 09:24:39.759601] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd2af10 sge[16]  next 0x20001e1c0008 total_length 8320 num_extra_wrs 1
[2022-02-16 09:24:39.759629] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd2af10 sge[16]  next 0x20001e1bfd88 total_length 8320 num_extra_wrs 1
[2022-02-16 09:24:39.759655] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd2af10 sge[16]  next 0x20001e1bfb08 total_length 8320 num_extra_wrs 1
[2022-02-16 09:24:39.759683] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd2af10 sge[16]  next 0x20001e1bf888 total_length 8320 num_extra_wrs 1
[2022-02-16 09:24:39.759712] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd24570 sge[16]  next 0x20001e1bf608 total_length 8320 num_extra_wrs 1
[2022-02-16 09:24:39.759741] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd2af10 sge[16]  next 0x20001e1bf388 total_length 8320 num_extra_wrs 1

run the perf test again, the following error message is displayed:
[2022-02-16 09:25:07.017946] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018011] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018028] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018041] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018054] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018065] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018076] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018087] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018087] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd476a0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1
[2022-02-16 09:25:07.018125] rdma.c:1477:nvmf_rdma_fill_wr_sgl: *NOTICE*: C1 rqpair 0xd46ec0 sge[16]  next (nil) total_length 1024 num_extra_wrs -1

#0  nvmf_rdma_fill_wr_sgl (rdma_req=rdma_req@entry=0xffff1357a950, wr=0xffff1357adf8, total_length=1024, num_extra_wrs=4294967295, device=<optimized out>, rgroup=0xb678f0) at rdma.c:1441
        mem_translation = {mr_or_key = {mr = 0xb677b0, key = 11958192}, translation_type = 0 '\000'}
        dif_ctx = 0xffff1357aca8
        sg_ele = 0xffff1357af78
        iov = <optimized out>
        remaining_data_block = 0
        lkey = <optimized out>
        remaining = <optimized out>
        rc = <optimized out>
        __func__ = "nvmf_rdma_fill_wr_sgl"
#1  0x0000000000476b3c in nvmf_rdma_request_fill_iovs (length=<optimized out>, rdma_req=0xffff1357a950, device=0xb65170, rtransport=0xada460) at rdma.c:1584
        num_wrs = 0
        rqpair = <optimized out>
        rgroup = 0xb678f0
        req = 0xffff1357a950
        wr = 0xffff1357adf8
        rc = 0
        rqpair = <optimized out>
        rgroup = <optimized out>
        req = <optimized out>
        wr = <optimized out>
        rc = <optimized out>
        num_wrs = <optimized out>
#2  nvmf_rdma_request_parse_sgl (rdma_req=0xffff1357a950, device=0xb65170, rtransport=0xada460) at rdma.c:1752
        rsp = 0x2000efcbead0
        length = <optimized out>
        req = 0xffff1357a950
        sgl = <optimized out>
        rc = <optimized out>
        req = <optimized out>
        rsp = <optimized out>
        sgl = <optimized out>
        rc = <optimized out>
        length = <optimized out>
        __func__ = "nvmf_rdma_request_parse_sgl"
        offset = <optimized out>
        max_len = <optimized out>
#3  nvmf_rdma_request_process (rtransport=rtransport@entry=0xada460, rdma_req=0xffff1357a950) at rdma.c:1959
        rqpair = 0xd46010
        device = <optimized out>
        rgroup = 0xb678f0
        rsp = <optimized out>
        rc = <optimized out>
        rdma_recv = <optimized out>
        prev_state = <optimized out>
        progress = true
        data_posted = <optimized out>
        num_blocks = <optimized out>
        __func__ = "nvmf_rdma_request_process"
#4  0x0000000000476fa8 in nvmf_rdma_qpair_process_pending (rtransport=rtransport@entry=0xada460, rqpair=rqpair@entry=0xd46010, drain=drain@entry=false) at rdma.c:2727
        req = <optimized out>
        tmp = <optimized out>
        rdma_req = <optimized out>
        req_tmp = <optimized out>
        resources = 0xbe8420
#5  0x0000000000477b78 in nvmf_rdma_poller_poll (rtransport=rtransport@entry=0xada460, rpoller=rpoller@entry=0xba8180) at rdma.c:3920

## Possible Solution
diff --git a/lib/nvmf/rdma.c b/lib/nvmf/rdma.c
index e8fa7f647..29c70eb10 100644
--- a/lib/nvmf/rdma.c
+++ b/lib/nvmf/rdma.c
@@ -1848,6 +1848,7 @@ _nvmf_rdma_request_free(struct spdk_nvmf_rdma_request *rdma_req,
        rdma_req->rsp.wr.next = NULL;
        rdma_req->data.wr.next = NULL;
        rdma_req->offset = 0;
+       rdma_req->req.dif_enabled = false;
        memset(&rdma_req->req.dif, 0, sizeof(rdma_req->req.dif));
        rqpair->qd--;

## Steps to Reproduce

1.format nvme disk with 512+8
2. run nof target
./nvmf_tgt -m 0x3fff000000000000 &
./rpc.py nvmf_create_transport -t RDMA -f -q 128 -m 127 -c 4096 -i 16384 -u 8320 -a 128 -n 4096 -b 32 -s 30000
./rpc.py bdev_nvme_attach_controller -b Nvme0 -t PCIe -a 0000:02:00.0
./rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode${i} -a -s SPDK0000000000000${i}
./rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode${i} Nvme0n$[ $i+1 ]
./rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode${i} -t RDMA -a 172.19.37.251 -s 842$i
3.run perf test
./build/examples/perf -r 'trtype:RDMA adrfam:IPv4 traddr:172.19.37.251 trsvcid:8420' -w randwrite -o 1048576 -t 80 -q 64 -c 0xffffff
4..run perf test again, it is fail
## Context (Environment including OS version, SPDK version, etc.)
CentOS 8.1
SPDK 21.10

**Comment by AlekseyMarchuk** [comment]
Fix posted by @fengchunsong https://review.spdk.io/gerrit/c/spdk/spdk/+/11646
