### ISSUE TITLE
[spdk-master-vs-dpdk-main] Core dump in crypto tests when creating crypto bdev

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2412]
# Bug report

crypto-autotest builds fail with core dump when building SPDK with upstream DPDK `main` branch.
This affects both SPDK `master` and `v22.01.x` branches.
https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_420.html
https://ci.spdk.io/public_build/autotest-spdk-v22.01-LTS-vs-dpdk-main_136.html

## Steps to Reproduce

1. Run SPDK autorun.sh with following config:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_BLOCKDEV=1
SPDK_TEST_ISAL=1
SPDK_TEST_CRYPTO=1
SPDK_TEST_REDUCE=1
SPDK_RUN_UBSAN=1
SPDK_TEST_NATIVE_DPDK=main
SPDK_RUN_EXTERNAL_DPDK=/spdk-temp/dpdk/build
```
2. Tests fail after reaching tests with crypto-specific features in `./test/json_config/json_config.sh`.
```
/var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_malloc_create 8 1024 --name MallocForCryptoBdev
/var/jenkins/workspace/crypto-autotest/spdk/scripts/rpc.py -s /var/tmp/spdk_tgt.sock bdev_crypto_create MallocForCryptoBdev CryptoMallocBdev crypto_qat 0123456789123456

00:05:56.027  [2022-03-03 07:50:50.119539] vbdev_crypto.c:1766:vbdev_crypto_claim: *NOTICE*: QAT in use: Required alignment set to 10
00:05:56.027  [2022-03-03 07:50:50.119582] vbdev_crypto.c:1769:vbdev_crypto_claim: *NOTICE*: QAT using cipher: AES_CBC
00:05:56.027  vbdev_crypto.c:520:2: runtime error: store to null pointer of type 'struct spdk_bdev_io *'
00:05:56.027      #0 0x7f80adc58e81 in _crypto_operation_complete /var/jenkins/workspace/crypto-autotest/spdk/module/bdev/crypto/vbdev_crypto.c:520
00:05:56.027      #1 0x7f80adc6629e in _crypto_operation /var/jenkins/workspace/crypto-autotest/spdk/module/bdev/crypto/vbdev_crypto.c:902
00:05:56.027      #2 0x7f80adc6b1b3 in _complete_internal_read /var/jenkins/workspace/crypto-autotest/spdk/module/bdev/crypto/vbdev_crypto.c:1011
00:05:56.027      #3 0x7f80acd8620d in bdev_io_complete /var/jenkins/workspace/crypto-autotest/spdk/lib/bdev/bdev.c:5494
00:05:56.027      #4 0x7f80acd86f8a in spdk_bdev_io_complete /var/jenkins/workspace/crypto-autotest/spdk/lib/bdev/bdev.c:5564
00:05:56.027      #5 0x7f80ae08f8d1 in malloc_done /var/jenkins/workspace/crypto-autotest/spdk/module/bdev/malloc/bdev_malloc.c:82
00:05:56.027      #6 0x7f80acc8cb8c in spdk_accel_task_complete /var/jenkins/workspace/crypto-autotest/spdk/lib/accel/accel_engine.c:124
00:05:56.027      #7 0x7f80acc91faf in accel_comp_poll /var/jenkins/workspace/crypto-autotest/spdk/lib/accel/accel_engine.c:667
00:05:56.027      #8 0x7f80acbbc5d8 in thread_execute_poller /var/jenkins/workspace/crypto-autotest/spdk/lib/thread/thread.c:813
00:05:56.027      #9 0x7f80acbbe18a in thread_poll /var/jenkins/workspace/crypto-autotest/spdk/lib/thread/thread.c:935
00:05:56.027      #10 0x7f80acbbe560 in spdk_thread_poll /var/jenkins/workspace/crypto-autotest/spdk/lib/thread/thread.c:986
00:05:56.027      #11 0x7f80ad1074a0 in _reactor_run /var/jenkins/workspace/crypto-autotest/spdk/lib/event/reactor.c:920
00:05:56.027      #12 0x7f80ad107af0 in reactor_run /var/jenkins/workspace/crypto-autotest/spdk/lib/event/reactor.c:958
00:05:56.027      #13 0x7f80ad10849a in spdk_reactors_start /var/jenkins/workspace/crypto-autotest/spdk/lib/event/reactor.c:1060
00:05:56.027      #14 0x7f80ad0fda22 in spdk_app_start /var/jenkins/workspace/crypto-autotest/spdk/lib/event/app.c:643
00:05:56.027      #15 0x405859 in main /var/jenkins/workspace/crypto-autotest/spdk/app/spdk_tgt/spdk_tgt.c:120
00:05:56.027      #16 0x7f80abaa0b74 in __libc_start_main (/usr/lib64/libc.so.6+0x27b74)
00:05:56.027      #17 0x40535d in _start (/var/jenkins/workspace/crypto-autotest/spdk/build/bin/spdk_tgt+0x40535d)
00:05:56.027  
00:05:59.330  Connection closed with partial response:
00:05:59.330  
00:05:59.330  
00:05:59.330  ./test/json_config/json_config.sh: line 33: 137551 Aborted                 (core dumped) $SPDK_BIN_DIR/spdk_tgt ${app_params[$app]} ${app_extra_params} -r ${app_socket[$app]} "$@"
```

## Context (Environment including OS version, SPDK version, etc.)

Last successful build:
https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_392.html
SPDK: `5c80b1e5ab0 nvme/rdma: Limit max_sges by command capsule size`
DPDK: `de2bc16 app/eventdev: add crypto producer mode`

First failed build:
https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_393.html
SPDK: `5c80b1e5ab0 nvme/rdma: Limit max_sges by command capsule size`
DPDK: `35cb5bd doc: support IPsec Multi-buffer lib v1.2`

DPDK git log diff:
```
$ git log de2bc16..35cb5bd --oneline
35cb5bd236 doc: support IPsec Multi-buffer lib v1.2
a501609ea6 crypto/ipsec_mb: fix length and offset settings
96d0dc2a3c crypto/ipsec_mb: fix ZUC operation overwrite
bd3769739b crypto/ipsec_mb: fix ZUC authentication verify
cfb566048e crypto/ipsec_mb: check missing operation types
a965e76806 crypto/virtio: fix out-of-bounds access
fb6996eec0 baseband/acc100: avoid out-of-bounds access
aaf4ac4043 examples/l2fwd-crypto: fix port mask overflow
5816147901 test/crypto: add L4 checksum case for transport mode
42902e810d test/crypto: add TTL and hop limit decrement cases
1998071cb6 doc: fix FIPS guide
48a398718d examples/ipsec-secgw: add pool size parameters
5fb245ba6d examples/ipsec-secgw: fix buffer freeing in vector mode
5315b7746c examples/ipsec-secgw: avoid logs in data path
a15f7b7d8a examples/ipsec-secgw: add check for unprotected port mask
002486db23 crypto/qat: refactor asymmetric session
6c25a68adc crypto/qat: add ECPM algorithm
b5324d3854 crypto/qat: add ECDSA algorithm
7b012789ad crypto/qat: add named elliptic curves
3b78aa7b23 crypto/qat: refactor asymmetric crypto functions
ff01b26fb2 crypto/qat: support out-of-place SG list
85fec6fd96 crypto/qat: unify raw data path functions
fb3b9f4922 crypto/qat: rework burst data path
2becec6bee crypto/qat: unify asymmetric functions
e0a6761022 crypto/qat: unify symmetric functions
a234330286 crypto/qat: rework asymmetric op build operation
254558c832 crypto/qat: rework session functions
a815a04cea crypto/qat: support symmetric build op request
c3352e724d common/qat: define build request and dequeue operations
521fbc716e crypto/cnxk: support TTL or hop limit decrement
3387912f5c cryptodev: fix RSA key type name
03944ff5e3 crypto/ipsec_mb: support null auth/cipher for aesni_mb
080c84cde4 cryptodev: fix asymmetric private session variable size
f819a1629b crypto/ipsec_mb: remove useless check
d02c6bfcb9 test/crypto: add ESN and antireplay cases
70c60cfd93 test/crypto: add copy and set DSCP cases
```

**Comment by peluse** [comment]
oh man, I've been watching all the DPDK crypto updates lately and wondering when we would get bitten...

**Comment by peluse** [comment]
@karlatec as usual I can't run autorun.sh, I get one error after another and have spent 30 min addressing them adn they just keep coming.  The env is just not that compatible with my dev system.  Isn't there an easy way for me to just use the latest dpdk in my spdk/dpdk dir instead of having to run all of these long complicated scripts that make it really hard to debug something?  I should be able to build w/the latest dpdk and repro by simply creating a crypto bdev manually, that would make debug much simpler.  Little help?

**Comment by jimharris** [comment]
> @karlatec as usual I can't run autorun.sh, I get one error after another and have spent 30 min addressing them adn they just keep coming. The env is just not that compatible with my dev system. Isn't there an easy way for me to just use the latest dpdk in my spdk/dpdk dir instead of having to run all of these long complicated scripts that make it really hard to debug something? I should be able to build w/the latest dpdk and repro by simply creating a crypto bdev manually, that would make debug much simpler. Little help?

Hi @peluse,

Yes, you can always change your dpdk submodule to temporarily point at some other DPDK commit.  For example:

```
cd dpdk
git remote add upstream https://github.com/dpdk/dpdk.git
git checkout upstream/main
cd ..
make clean
# may need to adjust options to match exact autorun.sh configuration
./configure --with-crypto --enable-debug
make -jX
```

**Comment by peluse** [comment]
@jimharris life saver! :)

**Comment by peluse** [comment]
Well, I get an error on 'git checkout upstream/main' even though it said it added the remote OK.  Anyway, i just rm -rf'd my dpdk submodule dir and cloned dpdk into it and that worked (meaning I can get log in dpdk and know I'm on latest main).  Can't reproduce the error yet but at least I can use the correct dpdk which is a great start, thanks again.  LMK if you have any clue on the checkout upstrean/error but it's no big deal if not

**Comment by jimharris** [comment]
> Well, I get an error on 'git checkout upstream/main' even though it said it added the remote OK. Anyway, i just rm -rf'd my dpdk submodule dir and cloned dpdk into it and that worked (meaning I can get log in dpdk and know I'm on latest main). Can't reproduce the error yet but at least I can use the correct dpdk which is a great start, thanks again. LMK if you have any clue on the checkout upstrean/error but it's no big deal if not

I missed a step in there. You need to fetch upstream before the checkout.

**Comment by peluse** [comment]
LOL, thanks Jim.  Still unable to repro w/latest DPDK, latest SPDK, ISAL or QAT but I'm just starting with super basic stuff.  Will continue to add steps and see what else we're doing in the autorun steps that I'm not doing manually.

**Comment by peluse** [comment]
@karlatec so I can't reproduce this manually with latest SPDK and latest DPDK with either ISAL or QAT, not quite sure why.  I'm *assuming* that the failing IO is an examine-IO from either gpt or lvol and because of whatever reason is failing in the decomp.  There is a patch out there that I don't think would fix anything but might provide a clue.  If there is a failure in the decomp operation the code on master would double complete and, assuming that didn't make something else explore, could be the reason why the driver_ctx of the bdev_io is NULL (that's the failure).  Can you try with this patch and let me know if there is a difference in behavior?

https://review.spdk.io/gerrit/c/spdk/spdk/+/11629

If not maybe we can chat tomorrow morn my time and try to figure out how we can either simplify steps to repro or figure out why I've really never been able to run the automated test script w/any success on my dev systems.

**Comment by karlatec** [comment]
Could you rebase the patch so taht it contains the fix for? https://github.com/spdk/spdk/issues/2409

**Comment by tomzawadzki** [comment]
[Bug scrub] A related change in https://review.spdk.io/gerrit/c/spdk/spdk/+/11629 might help to determine if and what fix is needed for this issue. After that one is merged/rebased, let's see if further testing confirms it.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_72978.html

**Comment by karlatec** [comment]
> Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_72978.html

Not related.

**Comment by karlatec** [comment]
So looking at recent builds of spdk-master-vs-dpdk-main it seems that merging linked patch fixed the issue: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-main_446.html (it failed, but that's a separate problem).

What about v22.01.x though? It still fails: https://ci.spdk.io/public_build/autotest-spdk-v22.01-LTS-vs-dpdk-main_164.html
Which of the two merged patches should I cherry-pick to v22.01.x branch? (https://review.spdk.io/gerrit/c/spdk/spdk/+/11628/14, https://review.spdk.io/gerrit/c/spdk/spdk/+/11629/14)

**Comment by peluse** [comment]
Great thanks @karlatec! Before we close this I want to take another look at the code and try to understand how what I expected was the cause (dbl completion) could go undetected now as that was really a secondary error.  May want to add some more debug and re-run, could very well be that we handle the error correctly now, i just want to know what the error was.  Same thing on backport, lets hold off just a bit...

**Comment by karlatec** [comment]
IMO this is important. It's the LTS branch that fails to build / test with mainline DPDK, and we're going to support LTS until next year.  

Also - we run spdk v22.01.x vs dpdk-main daily, so "failed" test results haunt me when I take a look at CI dashboard: https://ci.spdk.io/public_build/autotest-spdk-v22.01-LTS-vs-dpdk-main.html

**Comment by peluse** [comment]
@karlatec thanks again.  I'll carve out some time this week (or Sat) to at least dig in a bit and narrow things down so maybe even if I don't have b/w to supply a full fix I can provide enough info that maybe someone else can.

**Comment by jimharris** [comment]
@karlatec - can you bisect this down to a specific DPDK commit?

**Comment by peluse** [comment]
So I mis-spoke, I canont repor - still can't even get a debug env going to work on this.  Using autobuild.sh works and running autotest.sh gives me a failure but not he correct one.  I need to be able to build manually and make changes manually to both SPDK and DPDK in order to debug.  I tried running autobuild.sh and then running configure --with-dpdk=/spdk-temp/dpdk but that doesn't build.  @karlatec I guess I need to spend another few min on the phone with you as I can neither repro or debug at this time.

**Comment by peluse** [comment]
OK, I did enough hacking with my dev env that I can do what I need to do now without the automation scripts.  Can repro the segfault above so will fix the error handling error and see what the earlier error is

**Comment by peluse** [comment]
The failing DPDK commit is below *however* I haven't debugged it enough to know why and I fully suspect this isn't the only issue. 

e0a6761022bd368e114fdea27809391ef0ad2c41 is the first bad commit
commit e0a6761022bd368e114fdea27809391ef0ad2c41
Author: Kai Ji <kai.ji@intel.com>
Date:   Wed Feb 23 08:50:02 2022 +0800

    crypto/qat: unify symmetric functions

    This patch removes qat_sym_pmd.c and integrates all the functions into
    qat_sym.c. The unified/integrated qat sym crypto pmd functions should
    make them easier to maintain.

    Signed-off-by: Kai Ji <kai.ji@intel.com>
    Acked-by: Fan Zhang <roy.fan.zhang@intel.com>

**Comment by peluse** [comment]
@karlatec bit of a diversion here as I try to collect enough data to have a conversation with dpdk-dev.  When I try to compile master vs DPDK main I don't get the same issue I see on the nightly builds.  I get this (I can compile fine with 22.01.x and DPDK main).  Any idea what this mess is?

Program cat found: YES (/bin/cat)
Project name: DPDK
Project version: 22.03.0-rc2
Using 'CC' from environment with value: 'cc'

meson.build:4:0: ERROR: Compiler cc can not compile programs.

A full log can be found at /home/peluse/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
make[1]: *** [Makefile:195: /home/peluse/spdk/dpdk/build-tmp] Error 1
make: *** [/home/peluse/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
peluse@pels3:~/spdk$ cat /home/peluse/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
Build started at 2022-03-22T21:41:40.081777
Main binary: /usr/bin/python3
Build Options: '-Dc_args= -I -fPIC -Wno-error ' -Dc_link_args=-L -Denable_docs=false -Dtests=false -Denable_kmods=false -Dmachine=native -Denable_drivers=bus,bus/pci,bus/vdev,mempool/ring,crypto/qat,compress/qat,common/qat,crypto,crypto/ipsec_mb,crypto/aesni_mb -Ddisable_libs=efd,pdump,latencystats,pcapng,stack,bbdev,port,lpm,flow_classify,rawdev,gpudev,eventdev,bpf,ipsec,bitratestats,gro,rib,regexdev,gso,graph,ip_frag,kni,cfgfile,member,node,acl,dmadev,distributor,jobstats,fib,pipeline,metrics,sched,table -Dprefix=/home/peluse/spdk/dpdk/build -Dlibdir=lib -Dbuildtype=debug
Python system: Linux
The Meson build system
Version: 0.56.0
Source dir: /home/peluse/spdk/dpdk
Build dir: /home/peluse/spdk/dpdk/build-tmp
Build type: native build
Program cat found: YES (/bin/cat)
Running command: /bin/cat /home/peluse/spdk/dpdk/VERSION
--- stdout ---
22.03.0-rc2

--- stderr ---


Project name: DPDK
Project version: 22.03.0-rc2
Using 'CC' from environment with value: 'cc'
None of 'CFLAGS' are defined in the environment, not changing global flags.
None of 'LDFLAGS' are defined in the environment, not changing global flags.
None of 'CPPFLAGS' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity check compiler command line: cc /home/peluse/spdk/dpdk/build-tmp/meson-private/sanitycheckc.c -o /home/peluse/spdk/dpdk/build-tmp/meson-private/sanitycheckc.exe -I -fPIC -Wno-error -pipe -D_FILE_OFFSET_BITS=64 -L
Sanity check compile stdout:

-----
Sanity check compile stderr:
cc: error: missing argument to ‘-L’

-----

meson.build:4:0: ERROR: Compiler cc can not compile programs.
peluse@pels3:~/spdk$ git pull
warning: redirecting to https://review.spdk.io/gerrit/spdk/spdk/
Already up to date.
peluse@pels3:~/spdk$ make clean -j99
make[2]: Nothing to be done for 'clean'.
peluse@pels3:~/spdk$ make -j99
The Meson build system
Version: 0.56.0
Source dir: /home/peluse/spdk/dpdk
Build dir: /home/peluse/spdk/dpdk/build-tmp
Build type: native build
Program cat found: YES (/bin/cat)
Project name: DPDK
Project version: 22.07.0-rc0
Using 'CC' from environment with value: 'cc'

meson.build:4:0: ERROR: Compiler cc can not compile programs.

A full log can be found at /home/peluse/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
make[1]: *** [Makefile:195: /home/peluse/spdk/dpdk/build-tmp] Error 1
make: *** [/home/peluse/spdk/mk/spdk.subdirs.mk:44: dpdkbuild] Error 2
peluse@pels3:~/spdk$ cat /home/peluse/spdk/dpdk/build-tmp/meson-logs/meson-log.txt
Build started at 2022-03-22T21:46:53.956494
Main binary: /usr/bin/python3
Build Options: '-Dc_args= -I -fPIC -Wno-error ' -Dc_link_args=-L -Denable_docs=false -Dtests=false -Denable_kmods=false -Dmachine=native -Denable_drivers=bus,bus/pci,bus/vdev,mempool/ring,crypto/qat,compress/qat,common/qat,crypto,crypto/ipsec_mb,crypto/aesni_mb -Ddisable_libs=efd,pdump,latencystats,pcapng,stack,bbdev,port,lpm,flow_classify,rawdev,gpudev,eventdev,bpf,ipsec,bitratestats,gro,rib,regexdev,gso,graph,ip_frag,kni,cfgfile,member,node,acl,dmadev,distributor,jobstats,fib,pipeline,metrics,sched,table -Dprefix=/home/peluse/spdk/dpdk/build -Dlibdir=lib -Dbuildtype=debug
Python system: Linux
The Meson build system
Version: 0.56.0
Source dir: /home/peluse/spdk/dpdk
Build dir: /home/peluse/spdk/dpdk/build-tmp
Build type: native build
Program cat found: YES (/bin/cat)
Running command: /bin/cat /home/peluse/spdk/dpdk/VERSION
--- stdout ---
22.07.0-rc0

--- stderr ---


Project name: DPDK
Project version: 22.07.0-rc0
Using 'CC' from environment with value: 'cc'
None of 'CFLAGS' are defined in the environment, not changing global flags.
None of 'LDFLAGS' are defined in the environment, not changing global flags.
None of 'CPPFLAGS' are defined in the environment, not changing global flags.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity testing C compiler: cc
Is cross compiler: False.
None of 'CC_LD' are defined in the environment, not changing global flags.
Sanity check compiler command line: cc /home/peluse/spdk/dpdk/build-tmp/meson-private/sanitycheckc.c -o /home/peluse/spdk/dpdk/build-tmp/meson-private/sanitycheckc.exe -I -fPIC -Wno-error -pipe -D_FILE_OFFSET_BITS=64 -L
Sanity check compile stdout:

-----
Sanity check compile stderr:
cc: error: missing argument to ‘-L’

-----

meson.build:4:0: ERROR: Compiler cc can not compile programs.
peluse@pels3:~/spdk$

**Comment by peluse** [comment]
A bit more info... on the DPDK patch where this begins, new code was added that is processing the ops.  We are unable to get even the first op processed, when we send a burst in we get a return value indicating that 0 were accepted.  The code that is kicking it back is easy to identify but I'll need to talk with dpdk-dev folks to know what/why our inputs were fine before but are not now.  Yuri has made some changes in how we construct ops which is what I'd like to use before reporting the issue however master+DPDK main won't build.  I'd prefer not to cherry pick from other patches and root cause this on a mix-n-match patch set.

**Comment by peluse** [comment]
FYI for those watching at home, the DPDK patch above that is the first failure that I've found is paired with v22.01.x, when using SPDK master+ DPDK main something else is broken.  Working on tracking that down now to better understand the myriad of issues here....

**Comment by peluse** [comment]
@karlatec so if I keep going up the DPDK git log all the way to latest main things "just work" and I confirm if I go back to the patch I mention above where things first start going south they're still broken.  So basically with SPDK master *or* v22.01.x I have no problems with crypto when I'm on DPDK main.  Below is the commit that I'm on w/DPDK.  What I don't understand looking at the CI logs is (1) where to find which DPDK commit is being used and (2) is the QAT max num devices patch applied? For #1 that would be critical to know because somewhere in between the last release and main it was broken in the way that we're seeing in CI and I could reproduce that, however now it work.  For (2) without our patch to DPDK to change max crypto from 64 to 128 you'll get a bunch of messages from the SPDK app saying that we've reached the max number of crypto devices which is what I see in the CI logs.  So, in short, I'm not sure why I have everything working now using latest/greatest w/the QAT patch and CI is failing

commit 1d5e58e9b6962cb00fc5c7369cbf4e3b932a9b8e (HEAD, upstream/main, master)
Author: David Marchand <david.marchand@redhat.com>
Date:   Fri Mar 18 15:35:08 2022 +0100

    version: 22.07-rc0

    Start a new release cycle with empty release notes.
    Bump version and ABI minor.

    Signed-off-by: David Marchand <david.marchand@redhat.com>
    Acked-by: Thomas Monjalon <thomas@monjalon.net>
    Acked-by: Aaron Conole <aconole@redhat.com>

**Comment by tomzawadzki** [comment]
[Bug scrub] Patch that increasing the max crypto devices didn't apply correctly due to tag changes on DPDK side, Karol will take a look at this part.

**Comment by peluse** [comment]
@karlatec looking good.  Lets get this closed out and get a few wins w/master+main then look LTS vs main and see what needs to be back ported

**Comment by tomzawadzki** [comment]
[Bug scrub] The issue is fixed for latest SPDK and DPDK main. Let's close this issue and @karlatec can you open one specific for investigating which backports are required to enable builds against SPDK LTS ?
