### ISSUE TITLE
Out of space failure on VM-host-PE3

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2417]
Seeing this manifest in a lot of different ways.  First failure in my patch series shows:

from zns-vg-autotest:
```
00:05:48.140   20:45:49	-- common/autotest_common.sh@615 -- $ '[' -x /usr/local/FlameGraph/flamegraph.pl ']'
00:05:48.140   20:45:49	-- common/autotest_common.sh@617 -- $ /usr/local/FlameGraph/flamegraph.pl --title 'Build Timing' --nametype Step: --countname seconds /home/vagrant/spdk_repo/spdk/../output/timing.txt
00:05:48.140  Ignored 2 lines with invalid format
00:05:48.141   20:45:49	-- spdk/autopackage.sh@109 -- $ exit 0
00:05:48.154  [Pipeline] sleep
00:05:48.156  Sleeping for 5 sec
00:05:53.158  [Pipeline] }
00:05:53.180  [Pipeline] // timeout
00:05:53.186  [Pipeline] }
00:05:53.207  [Pipeline] // stage
00:05:53.213  [Pipeline] }
00:05:53.233  [Pipeline] // catchError
00:05:53.243  [Pipeline] stage
00:05:53.245  [Pipeline] { (Stop VM)
00:05:53.263  [Pipeline] sh
00:05:53.552  + vagrant halt
00:05:54.932  /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:835:in `close': No space left on device @ fptr_finalize_flush - /var/lib/libvirt/images/.vagrant.d/perm_test_XMRUEPWIBISAFFUGLGXCLVXVUCHBAEHS (Errno::ENOSPC)
00:05:54.932  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:835:in `open'
00:05:54.932  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:835:in `open'
00:05:54.932  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:835:in `setup_home_path'
00:05:54.932  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:135:in `initialize'
00:05:54.932  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/bin/vagrant:145:in `new'
00:05:54.932  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/bin/vagrant:145:in `<top (required)>'
00:05:54.932  	from /usr/bin/vagrant:23:in `load'
00:05:54.932  	from /usr/bin/vagrant:23:in `<main>'
00:05:54.947  [Pipeline] }
00:05:54.968  [Pipeline] // stage
00:05:54.977  [Pipeline] }
00:05:54.998  [Pipeline] // dir
00:05:55.007  [Pipeline] }
00:05:55.011  ERROR: script returned exit code 1
00:05:55.029  [Pipeline] // catchError
00:05:55.039  [Pipeline] stage
00:05:55.042  [Pipeline] { (Epilogue)
00:05:55.057  [Pipeline] sh
00:05:55.341  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:05:55.341  + cd /var/jenkins/workspace/zns-vg-autotest/output
00:05:55.341  jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: line 8: cd: /var/jenkins/workspace/zns-vg-autotest/output: No such file or directory
00:05:55.356  [Pipeline] }
00:05:55.380  [Pipeline] // stage
```

https://ci.spdk.io/public_build/autotest-per-patch_72705.html
The clang-vg-autotest in this 72705 run failed similarly.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72705.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72707.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72717.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72715.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_72712.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_72699.html

**Comment by xjjx** [comment]
Old VM images removed. Test run on PE3 passed.
