### ISSUE TITLE
[vhost-autotest/autotest-nightly] [TEST vhost_scsi_lvol_integrity] Currently unable to find bdev with name: Nvme0n1, *ERROR*: Cannot create blobstore device

### ISSUE THREAD

**Issue by kgodzwox** [spdk/spdk#2490]
# CI Intermittent Failure

**TEST vhost_scsi_lvol_integrity**
vhost-autotest/autotest-nightly

## Link to the failed CI build

https://ci.spdk.io/public_build/autotest-nightly_640.html
https://ci.spdk.io/public_build/autotest-nightly_639.html

It may be helpful. Both tests, where the problem occurred, were performed on the WFP4 machine. Build run on GP8 has passed:
https://ci.spdk.io/public_build/autotest-nightly_638.html

## Execution failed at

```
00:15:36.498   09:16:32	-- vhost/common.sh@66 -- # echo -e 'INFO: Creating lvol store on device Nvme0n1'
00:15:36.498  INFO: Creating lvol store on device Nvme0n1
00:15:36.498    09:16:32	-- lvol/lvol_test.sh@108 -- # /var/jenkins/workspace/vhost-autotest/spdk/scripts/rpc.py -s /root/vhost_test/vhost/0/rpc.sock bdev_lvol_create_lvstore Nvme0n1 lvs_0 -c 4194304
00:15:36.498  [2022-04-28 09:16:32.258843] bdev.c:6469:spdk_bdev_open_ext: *NOTICE*: Currently unable to find bdev with name: Nvme0n1
00:15:36.498  [2022-04-28 09:16:32.258917] vbdev_lvol.c: 269:vbdev_lvs_create: *ERROR*: Cannot create blobstore device
00:15:36.758     09:16:32	-- lvol/lvol_test.sh@108 -- # clean_lvol_cfg
00:15:36.758     09:16:32	-- lvol/lvol_test.sh@42 -- # notice 'Removing lvol bdevs'
00:15:36.758     09:16:32	-- vhost/common.sh@89 -- # message INFO 'Removing lvol bdevs'
00:15:36.758     09:16:32	-- vhost/common.sh@55 -- # local verbose_out
00:15:36.758     09:16:32	-- vhost/common.sh@56 -- # false
00:15:36.758     09:16:32	-- vhost/common.sh@57 -- # verbose_out=
00:15:36.758     09:16:32	-- vhost/common.sh@64 -- # local msg_type=INFO
00:15:36.758     09:16:32	-- vhost/common.sh@65 -- # shift
00:15:36.758     09:16:32	-- vhost/common.sh@66 -- # echo -e 'INFO: Removing lvol bdevs'
00:15:36.758     09:16:32	-- lvol/lvol_test.sh@48 -- # notice 'Removing lvol stores'
00:15:36.758     09:16:32	-- vhost/common.sh@89 -- # message INFO 'Removing lvol stores'
00:15:36.758     09:16:32	-- vhost/common.sh@55 -- # local verbose_out
00:15:36.758     09:16:32	-- vhost/common.sh@56 -- # false
00:15:36.758     09:16:32	-- vhost/common.sh@57 -- # verbose_out=
00:15:36.758     09:16:32	-- vhost/common.sh@64 -- # local msg_type=INFO
00:15:36.758     09:16:32	-- vhost/common.sh@65 -- # shift
00:15:36.758     09:16:32	-- vhost/common.sh@66 -- # echo -e 'INFO: Removing lvol stores'
00:15:36.759     09:16:32	-- lvol/lvol_test.sh@49 -- # /var/jenkins/workspace/vhost-autotest/spdk/scripts/rpc.py -s /root/vhost_test/vhost/0/rpc.sock bdev_lvol_delete_lvstore -u ''
00:15:36.759  Traceback (most recent call last):
00:15:36.759    File "/var/jenkins/workspace/vhost-autotest/spdk/scripts/rpc.py", line 3043, in <module>
00:15:36.759      call_rpc_func(args)
00:15:36.759    File "/var/jenkins/workspace/vhost-autotest/spdk/scripts/rpc.py", line 2944, in call_rpc_func
00:15:36.759      args.func(args)
00:15:36.759    File "/var/jenkins/workspace/vhost-autotest/spdk/scripts/rpc.py", line 1909, in bdev_lvol_delete_lvstore
00:15:36.759      rpc.lvol.bdev_lvol_delete_lvstore(args.client,
00:15:36.759    File "/var/jenkins/workspace/vhost-autotest/spdk/python/spdk/rpc/lvol.py", line 200, in bdev_lvol_delete_lvstore
00:15:36.759      raise ValueError("Exactly one of uuid or lvs_name must be specified")
00:15:36.759  ValueError: Exactly one of uuid or lvs_name must be specified
00:15:36.759     09:16:32	-- lvol/lvol_test.sh@50 -- # notice 'lvol store  removed'
00:15:36.759     09:16:32	-- vhost/common.sh@89 -- # message INFO 'lvol store  removed'
00:15:36.759     09:16:32	-- vhost/common.sh@55 -- # local verbose_out
00:15:36.759     09:16:32	-- vhost/common.sh@56 -- # false
00:15:36.759     09:16:32	-- vhost/common.sh@57 -- # verbose_out=
00:15:36.759     09:16:32	-- vhost/common.sh@64 -- # local msg_type=INFO
00:15:36.759     09:16:32	-- vhost/common.sh@65 -- # shift
00:15:36.759     09:16:32	-- vhost/common.sh@66 -- # echo -e 'INFO: lvol store  removed'
00:15:36.759     09:16:32	-- lvol/lvol_test.sh@108 -- # error_exit '' 108
00:15:36.759     09:16:32	-- vhost/common.sh@1261 -- # trap - ERR
00:15:36.759     09:16:32	-- vhost/common.sh@1262 -- # print_backtrace
00:15:36.759     09:16:32	-- common/autotest_common.sh@992 -- # [[ hxBET =~ e ]]
00:15:36.759     09:16:32	-- common/autotest_common.sh@992 -- # return 0
00:15:36.759     09:16:32	-- vhost/common.sh@1263 -- # set +e
00:15:36.759     09:16:32	-- vhost/common.sh@1264 -- # error 'Error on  108'
00:15:36.759     09:16:32	-- vhost/common.sh@77 -- # echo ===========
00:15:36.759  ===========
```
```
00:15:37.963   09:16:33	-- lvol/lvol_test.sh@108 -- # ls_guid='request:
00:15:37.963  {
00:15:37.963    "bdev_name": "Nvme0n1",
00:15:37.963    "lvs_name": "lvs_0",
00:15:37.963    "cluster_sz": 4194304,
00:15:37.963    "method": "bdev_lvol_create_lvstore",
00:15:37.963    "req_id": 1
00:15:37.963  }
00:15:37.963  Got JSON-RPC error response
00:15:37.963  response:
00:15:37.963  {
00:15:37.963    "code": 19,
00:15:37.963    "message": "Unknown error -19"
00:15:37.963  }
00:15:37.963  INFO: Removing lvol bdevs
00:15:37.963  INFO: Removing lvol stores
00:15:37.963  INFO: lvol store  removed
00:15:37.963  INFO: APP EXITING
00:15:37.963  INFO: killing all VMs
00:15:37.963  INFO: killing vhost app
00:15:37.963  INFO: killing vhost (PID 866652) app
00:15:37.963  INFO: sent SIGINT to vhost app - waiting 60 seconds to exit
00:15:37.963  .
00:15:37.963  INFO: EXIT DONE'
00:15:37.963    09:16:33	-- lvol/lvol_test.sh@108 -- # clean_lvol_cfg
00:15:37.963    09:16:33	-- lvol/lvol_test.sh@42 -- # notice 'Removing lvol bdevs'
00:15:37.963    09:16:33	-- vhost/common.sh@89 -- # message INFO 'Removing lvol bdevs'
00:15:37.963    09:16:33	-- vhost/common.sh@55 -- # local verbose_out
00:15:37.963    09:16:33	-- vhost/common.sh@56 -- # false
00:15:37.963    09:16:33	-- vhost/common.sh@57 -- # verbose_out=
00:15:37.963    09:16:33	-- vhost/common.sh@64 -- # local msg_type=INFO
00:15:37.963    09:16:33	-- vhost/common.sh@65 -- # shift
00:15:37.963    09:16:33	-- vhost/common.sh@66 -- # echo -e 'INFO: Removing lvol bdevs'
00:15:37.963  INFO: Removing lvol bdevs
00:15:37.963    09:16:33	-- lvol/lvol_test.sh@48 -- # notice 'Removing lvol stores'
00:15:37.963    09:16:33	-- vhost/common.sh@89 -- # message INFO 'Removing lvol stores'
00:15:37.963    09:16:33	-- vhost/common.sh@55 -- # local verbose_out
00:15:37.963    09:16:33	-- vhost/common.sh@56 -- # false
00:15:37.963    09:16:33	-- vhost/common.sh@57 -- # verbose_out=
00:15:37.963    09:16:33	-- vhost/common.sh@64 -- # local msg_type=INFO
00:15:37.963    09:16:33	-- vhost/common.sh@65 -- # shift
00:15:37.963    09:16:33	-- vhost/common.sh@66 -- # echo -e 'INFO: Removing lvol stores'
00:15:37.963  INFO: Removing lvol stores
00:15:37.963    09:16:33	-- lvol/lvol_test.sh@49 -- # /var/jenkins/workspace/vhost-autotest/spdk/scripts/rpc.py -s /root/vhost_test/vhost/0/rpc.sock bdev_lvol_delete_lvstore -u 'request:
00:15:37.963  {
00:15:37.963    "bdev_name": "Nvme0n1",
00:15:37.963    "lvs_name": "lvs_0",
00:15:37.963    "cluster_sz": 4194304,
00:15:37.963    "method": "bdev_lvol_create_lvstore",
00:15:37.963    "req_id": 1
00:15:37.963  }
00:15:37.963  Got JSON-RPC error response
00:15:37.963  response:
00:15:37.963  {
00:15:37.963    "code": 19,
00:15:37.963    "message": "Unknown error -19"
00:15:37.963  }
00:15:37.963  INFO: Removing lvol bdevs
00:15:37.963  INFO: Removing lvol stores
00:15:37.963  INFO: lvol store  removed
00:15:37.963  INFO: APP EXITING
00:15:37.963  INFO: killing all VMs
00:15:37.963  INFO: killing vhost app
00:15:37.963  INFO: killing vhost (PID 866652) app
00:15:37.963  INFO: sent SIGINT to vhost app - waiting 60 seconds to exit
00:15:37.963  .
00:15:37.963  INFO: EXIT DONE'
00:15:37.963  Error while connecting to /root/vhost_test/vhost/0/rpc.sock
00:15:37.963  Is SPDK application running?
00:15:37.963  Error details: Invalid or non-existing address: '/root/vhost_test/vhost/0/rpc.sock'
00:15:37.963    09:16:33	-- common/autotest_common.sh@964 -- # trap - ERR
00:15:37.963    09:16:33	-- common/autotest_common.sh@964 -- # print_backtrace
00:15:37.963    09:16:33	-- common/autotest_common.sh@992 -- # [[ ehxBET =~ e ]]
00:15:37.963    09:16:33	-- common/autotest_common.sh@994 -- # args=('--thin-provisioning' '--ctrl-type=spdk_vhost_scsi' '--fio-bin=/root/spdk_dependencies/fio' '-x' '/var/jenkins/workspace/vhost-autotest/spdk/test/vhost/lvol/lvol_test.sh' 'vhost_scsi_lvol_integrity')
00:15:37.963    09:16:33	-- common/autotest_common.sh@994 -- # local args
00:15:37.963    09:16:33	-- common/autotest_common.sh@996 -- # xtrace_disable
00:15:37.963    09:16:33	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:15:37.963    09:16:33	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:15:37.963    09:16:33	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:15:37.963    09:16:33	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:15:37.963    09:16:33	-- common/autotest_common.sh@19 -- # set +x
00:15:37.963  ========== Backtrace start: ==========
00:15:37.963  
00:15:37.963  in /var/jenkins/workspace/vhost-autotest/spdk/test/common/autotest_common.sh:964 -> run_test(["vhost_scsi_lvol_integrity"],["/var/jenkins/workspace/vhost-autotest/spdk/test/vhost/lvol/lvol_test.sh"],["-x"],["--fio-bin=/root/spdk_dependencies/fio"],["--ctrl-type=spdk_vhost_scsi"],["--thin-provisioning"])
00:15:37.963       ...
00:15:37.963     959 		timing_enter $test_name
00:15:37.963     960 		echo "************************************"
00:15:37.963     961 		echo "START TEST $test_name"
00:15:37.963     962 		echo "************************************"
00:15:37.964     963 		xtrace_restore
00:15:37.964  => 964 		time "$@"
00:15:37.964     965 		xtrace_disable
00:15:37.964     966 		echo "************************************"
00:15:37.964     967 		echo "END TEST $test_name"
00:15:37.964     968 		echo "************************************"
00:15:37.964     969 		timing_exit $test_name
00:15:37.964       ...
00:15:37.964  in ./test/vhost/vhost.sh:57 -> main([])
00:15:37.964       ...
00:15:37.964     52  		run_test "vhost_migration" $WORKDIR/migration/migration.sh -x \
00:15:37.964     53  			--fio-bin=$FIO_BIN --os=$VM_IMAGE
00:15:37.964     54  	fi
00:15:37.964     55  	
00:15:37.964     56  	echo 'Running lvol integrity suite...'
00:15:37.964  => 57  	run_test "vhost_scsi_lvol_integrity" $WORKDIR/lvol/lvol_test.sh -x --fio-bin=$FIO_BIN \
00:15:37.964     58  		--ctrl-type=spdk_vhost_scsi --thin-provisioning
00:15:37.964     59  	
00:15:37.964     60  	echo 'Running lvol integrity suite...'
00:15:37.964     61  	run_test "vhost_blk_lvol_integrity" $WORKDIR/lvol/lvol_test.sh -x --fio-bin=$FIO_BIN \
00:15:37.964     62  		--ctrl-type=spdk_vhost_blk
00:15:37.964       ...
00:15:37.964  
00:15:37.964  ========== Backtrace end ==========
00:15:37.964    09:16:33	-- common/autotest_common.sh@1032 -- # xtrace_enable
00:15:37.964    09:16:33	-- common/autotest_common.sh@1033 -- # return 0
00:15:37.964  
00:15:37.964  real	0m2.691s
00:15:37.964  user	0m2.099s
00:15:37.964  sys	0m0.672s
00:15:37.964    09:16:33	-- common/autotest_common.sh@964 -- # trap - ERR
00:15:37.964    09:16:33	-- common/autotest_common.sh@964 -- # print_backtrace
00:15:37.964    09:16:33	-- common/autotest_common.sh@992 -- # [[ ehxBET =~ e ]]
00:15:37.964    09:16:33	-- common/autotest_common.sh@994 -- # args=('./test/vhost/vhost.sh' 'vhost' 'autorun-spdk.conf')
00:15:37.964    09:16:33	-- common/autotest_common.sh@994 -- # local args
00:15:37.964    09:16:33	-- common/autotest_common.sh@996 -- # xtrace_disable
00:15:37.964    09:16:33	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:15:37.964    09:16:33	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
00:15:37.964    09:16:33	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
00:15:37.964    09:16:33	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:15:37.964    09:16:33	-- common/autotest_common.sh@19 -- # set +x
00:15:37.964  ========== Backtrace start: ==========
00:15:37.964  
00:15:37.964  in /var/jenkins/workspace/vhost-autotest/spdk/test/common/autotest_common.sh:964 -> run_test(["vhost"],["./test/vhost/vhost.sh"])
00:15:37.964       ...
00:15:37.964     959 		timing_enter $test_name
00:15:37.964     960 		echo "************************************"
00:15:37.964     961 		echo "START TEST $test_name"
00:15:37.964     962 		echo "************************************"
00:15:37.964     963 		xtrace_restore
00:15:37.964  => 964 		time "$@"
00:15:37.964     965 		xtrace_disable
00:15:37.964     966 		echo "************************************"
00:15:37.964     967 		echo "END TEST $test_name"
00:15:37.964     968 		echo "************************************"
00:15:37.964     969 		timing_exit $test_name
00:15:37.964       ...
00:15:37.964  in /var/jenkins/workspace/vhost-autotest/spdk/autotest.sh:267 -> main(["autorun-spdk.conf"])
00:15:37.964       ...
00:15:37.964     262 				exit 1
00:15:37.964     263 			fi
00:15:37.964     264 		fi
00:15:37.964     265 	
00:15:37.964     266 		if [ $SPDK_TEST_VHOST -eq 1 ]; then
00:15:37.964  => 267 			run_test "vhost" ./test/vhost/vhost.sh
00:15:37.964     268 		fi
00:15:37.964     269 	
00:15:37.964     270 		if [ $SPDK_TEST_VFIOUSER_QEMU -eq 1 ]; then
00:15:37.964     271 			run_test "vfio_user_qemu" ./test/vfio_user/vfio_user.sh
00:15:37.964     272 		fi
00:15:37.964       ...
00:15:37.964  
00:15:37.964  ========== Backtrace end ==========
```

**Comment by karlatec** [comment]
Looked through autotest-nightly history and it seems vhost-autotest always fails on WFP4.
At first I though something might be wrong with the NVMe drive (broken or missing), but all other tests before `vhost_scsi_lvol_integrity` pass.  

Could you try taking WFP4 offline in Jenkins for a while and reproduce the fail manually, just to check if there are no messages missing from CI logs?

**Comment by jimharris** [comment]
[Bug Scrub] Assigning to @karlatec for now.  @karlatec - if this needs more analysis on the test/logs itself, please assign to me.

**Comment by karlatec** [comment]
Re-assigning to @kgodzwox. Could you please see if this still reproduces and try to narrow down what might be the issue?

**Comment by kgodzwox** [comment]
The issue is currently not reproducing
