### ISSUE TITLE
[vhost vs qemu] Program terminated with signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by jchachux** [spdk/spdk#2550]
# Fail while executing `vhost-vs-qemu`

## Link to the failed CI build

`vhost-vs-qemu` test job 299

## Execution failed at

```
08:04:49  real	0m40.766s
08:04:49  user	1m30.368s
08:04:49  sys	0m8.930s
08:04:49   08:04:49	-- common/autotest_common.sh@1 -- # autotest_cleanup
08:04:49   08:04:49	-- common/autotest_common.sh@1240 -- # local autotest_es=1
08:04:49   08:04:49	-- common/autotest_common.sh@1241 -- # xtrace_disable
08:04:49   08:04:49	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
08:04:49   08:04:49	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
08:04:49   08:04:49	-- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
08:04:49   08:04:49	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
08:04:49   08:04:49	-- common/autotest_common.sh@19 -- # set +x
08:04:59  ##### CORE BT qemu-system-x86_64_1731609.core.bt.txt #####
08:04:59  
08:04:59  gdb: warning: Couldn't determine a path for the index cache directory.
08:04:59  
08:04:59  warning: Can't open file /dev/hugepages/qemu_back_mem.mem.tH6Bkt (deleted) during file-backed mapping note processing
08:04:59  
08:04:59  warning: Can't open file anon_inode:kvm-vcpu:1 which was expanded to anon_inode:kvm-vcpu:1 during file-backed mapping note processing
08:04:59  
08:04:59  warning: Can't open file anon_inode:kvm-vcpu:0 which was expanded to anon_inode:kvm-vcpu:0 during file-backed mapping note processing
08:04:59  
08:04:59  warning: Can't open file /dev/zero (deleted) during file-backed mapping note processing
08:04:59  [New LWP 1731609]
08:04:59  [New LWP 1731610]
08:04:59  [New LWP 1731614]
08:04:59  [New LWP 1731615]
08:04:59  [Thread debugging using libthread_db enabled]
08:04:59  Using host libthread_db library "/usr/lib64/libthread_db.so.1".
08:04:59  Core was generated by `/var/jenkins/workspace/vhost-vs-qemu/qemu_bin/bin/qemu-system-x86_64 -m 1024 --'.
08:04:59  Program terminated with signal SIGSEGV, Segmentation fault.
08:04:59  #0  0x00005613d68521a9 in vhost_user_backend_init (dev=0x5613d9d9bd00, opaque=0x5613d9d9bfb0, errp=0x7fff52334180) at ../hw/virtio/vhost-user.c:2034
08:04:59  2034	                error_setg(errp, "vhost-user device %s expecting "
08:04:59  [Current thread is 1 (Thread 0x7fda1250cec0 (LWP 1731609))]
08:04:59  
08:04:59  Thread 4 (Thread 0x7fda11861640 (LWP 1731615)):
08:04:59  #0  0x00007fda1be6d3fa in __futex_abstimed_wait_common () at /usr/lib64/libc.so.6
08:04:59  #1  0x00007fda1be6fbf0 in pthread_cond_wait@@GLIBC_2.3.2 () at /usr/lib64/libc.so.6
08:04:59  #2  0x00005613d6a6a5ab in qemu_cond_wait_impl (cond=0x5613d903dc60, mutex=0x5613d7267320 <qemu_global_mutex>, file=0x5613d6b78e13 "../softmmu/cpus.c", line=423) at ../util/qemu-thread-posix.c:219
08:04:59          err = <optimized out>
08:04:59          __PRETTY_FUNCTION__ = "qemu_cond_wait_impl"
08:04:59          __func__ = "qemu_cond_wait_impl"
08:04:59  #3  0x00005613d66fbd7e in qemu_wait_io_event (cpu=cpu@entry=0x5613d902ed30) at ../softmmu/cpus.c:423
08:04:59          _f = <optimized out>
08:04:59          slept = true
08:04:59  #4  0x00005613d69027a0 in kvm_vcpu_thread_fn (arg=arg@entry=0x5613d902ed30) at ../accel/kvm/kvm-accel-ops.c:54
08:04:59          cpu = 0x5613d902ed30
08:04:59          r = <optimized out>
08:04:59  #5  0x00005613d6a69a69 in qemu_thread_start (args=<optimized out>) at ../util/qemu-thread-posix.c:504
08:04:59          __cancel_buf = {__cancel_jmp_buf = {{__cancel_jmp_buf = {140574573598272, 2814290004118283780, 94643245274944, 7, 140574747723136, 0, 8403097695004599812, 2814260018893628932}, __mask_was_saved = 0}}, __pad = {0x7fda1185d6f0, 0x0, 0x7fd9c4000b50, 0x7fd9c40008d0}}
08:04:59          __cancel_routine = 0x5613d6a69ac0 <qemu_thread_atexit_notify>
08:04:59          __not_first_call = <optimized out>
08:04:59          start_routine = 0x5613d6902720 <kvm_vcpu_thread_fn>
08:04:59          arg = 0x5613d902ed30
08:04:59          r = <optimized out>
08:04:59  #6  0x00007fda1be7085a in start_thread () at /usr/lib64/libc.so.6
08:04:59  #7  0x00007fda1be104c0 in clone3 () at /usr/lib64/libc.so.6
```

**Comment by changpe1** [comment]
@jchachux can you list the failure web page here, I want to know more information about the failure, e.g: QEMU version.

**Comment by jchachux** [comment]
> @jchachux can you list the failure web page here, I want to know more information about the failure, e.g: QEMU version.

Unfortunately this job is not publicly available. 

I attached full log file:
[vhost-vs-qemu299.txt](https://github.com/spdk/spdk/files/8888797/vhost-vs-qemu299.txt)
.

**Comment by tomzawadzki** [comment]
@jchachux please always provide all the necessary details to reproduce the issue and other relevant details for any testing.

In this particular case this backtrace the attached log was for https://github.com/qemu/qemu/commit/6d940eff4734bcb40b1a25f62d7cec5a396f994a.
The failure started to occur between https://github.com/qemu/qemu/commit/9b1f58854959c5a9bdb347e3e04c252ab7fc9ef5 and https://github.com/qemu/qemu/commit/6d940eff4734bcb40b1a25f62d7cec5a396f994a.
It was fixed couple days later somewhere between https://github.com/qemu/qemu/commit/2663c41cfa2c3be34c62de97902a375b81027efd and https://github.com/qemu/qemu/commit/b871cc83d69a4463ac641286eef7d773ad5b5aaa.

For the last 3 days the failure is no longer observed testing with latest QEMU.
