### ISSUE TITLE
Exception has occurred. when deleting an raid bdev, which has a failty base bdev.

### ISSUE THREAD

**Issue by anonsurnfmi** [spdk/spdk#2557]
# Bug report
Exception has occurred. when deleting an raid bdev, which has an unexist base bdev.

## Steps to Reproduce
[Step 1]. Create Raid Bdev using an unexist bdev, 
    rpc-cmd:    rpc.py bdev_raid_create -n "raid0" -z 64 -r 0 -b "disk0n1 disk1n1 disk2n1"
   ( disk2n1 is a failty base bdev)
    Expected Behavior:  create success
    Current Behavior:    create success

[Step 2]. delete Raid Bdev
    rpc-cmd:  rpc.py bdev_raid_delete raid0
    Expected Behavior: delete success
    Current Behavior:  Assert has occurred.

![image](https://user-images.githubusercontent.com/97174787/173795877-1357820f-8ca3-4000-ac5d-9c2090f1b8ba.png)

## Context
SPDK Version:  v22.01.1 LTS  

## Possiable Solution
in function raid_bdev_remove_base_devices 
----------------------------------------------------------------------
	RAID_FOR_EACH_BASE_BDEV(raid_bdev, base_info) {
		if (base_info->bdev == NULL) {        //<---------- a)  when base_bdev not exist this will continue
			continue;
		}

		assert(base_info->desc);
		base_info->remove_scheduled = true;

		if (raid_bdev->destruct_called == true ||
		    raid_bdev->state == RAID_BDEV_STATE_CONFIGURING) {
			/*
			 * As raid bdev is not registered yet or already unregistered,
			 * so cleanup should be done here itself.
			 */
			raid_bdev_free_base_bdev_resource(raid_bdev, base_info);
			if (raid_bdev->num_base_bdevs_discovered == 0) {
				/* There is no base bdev for this raid, so free the raid device. */
				raid_bdev_cleanup(raid_bdev);    //<----------b)    if "a) "happened , this never called
				if (cb_fn) {
					cb_fn(cb_arg, 0);
				}
				return;
			}
		}
	}

**Comment by Comphix** [comment]
For below creation, as disk2n1 is a failty base bdev, any logs from the creation? Not sure whether this is relating to the free operation.

```
[Step 1]. Create Raid Bdev.
rpc-cmd: rpc.py bdev_raid_create -n "raid0" -z 64 -r 0 -b "disk0n1 disk1n1 disk2n1"
( disk2n1 is a failty base bdev)
Expected Behavior: create success
Current Behavior: create success
```

**Comment by jimharris** [comment]
Hi @anonsurnfmi,

Can you provide a specific set of instructions I can use to reproduce the assert you are seeing?  I tried the following and was not able to hit an assert:

Terminal 1:
```
./configure --enable-debug
make
build/bin/nvmf_tgt
```

Terminal 2:
```
scripts/rpc.py bdev_malloc_create 64 512 -b malloc0
scripts/rpc.py bdev_malloc_create 64 512 -b malloc1
scripts/rpc.py bdev_raid_create -n raid0 -z 64 -r 0 -b "malloc0 malloc1"
scripts/rpc.py bdev_raid_delete raid0
```

Can you also describe what is meant by a "failty base bdev"?  Do you mean "faulty"?  And if so, faulty in what way?

Thanks,

Jim

**Comment by anonsurnfmi** [comment]
> For below creation, as disk2n1 is a failty base bdev, any logs from the creation? Not sure whether this is relating to the free operation.

"disk2n1" can be an arbitrary bdev name，be sure that dose not exist in the bdev list. 
The bdev_raid_create returns success even if the bdev name does not exist.  

You can reproduce it as above.

**Comment by anonsurnfmi** [comment]
> Hi @anonsurnfmi,
> 
> Can you provide a specific set of instructions I can use to reproduce the assert you are seeing? I tried the following and was not able to hit an assert:
> 
> Terminal 1:
> 
> ```
> ./configure --enable-debug
> make
> build/bin/nvmf_tgt
> ```
> 
> Terminal 2:
> 
> ```
> scripts/rpc.py bdev_malloc_create 64 512 -b malloc0
> scripts/rpc.py bdev_malloc_create 64 512 -b malloc1
> scripts/rpc.py bdev_raid_create -n raid0 -z 64 -r 0 -b "malloc0 malloc1"
> scripts/rpc.py bdev_raid_delete raid0
> ```
> 
> Can you also describe what is meant by a "failty base bdev"? Do you mean "faulty"? And if so, faulty in what way?
> 
> Thanks,
> 
> Jim


Terminal 1:
./configure --enable-debug **--enable-debug**
make
build/bin/nvmf_tgt

Terminal 2:
scripts/rpc.py bdev_raid_create -n raid0 -z 64 -r 0 -b "nonexist_bdev0 nonexist_bdev1"
scripts/rpc.py bdev_raid_get_bdevs all
scripts/rpc.py bdev_raid_delete raid0

You don't have to create any bdev, "nonexist_bdev0 nonexist_bdev1" are not actually exist.
and bdev_raid_get_bdevs will return success anyway.

Try it.

**Comment by Comphix** [comment]
Yes, this issue could be reproduced and will take a look at the fix.

```
(gdb) bt
#0  0x00007ffff643b1f7 in raise () from /lib64/libc.so.6
#1  0x00007ffff643c8e8 in abort () from /lib64/libc.so.6
#2  0x00007ffff6434266 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007ffff6434312 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000430d1a in bdev_raid_delete_done (cb_arg=0xeb64b0, rc=0) at bdev_raid_rpc.c:371
#5  0x000000000042fc30 in raid_bdev_deconfigure (raid_bdev=0xc62310,
    cb_fn=0x430c4d <bdev_raid_delete_done>, cb_arg=0xeb64b0) at bdev_raid.c:1282
#6  0x0000000000430232 in raid_bdev_remove_base_devices (raid_cfg=0xc62270,
    cb_fn=0x430c4d <bdev_raid_delete_done>, cb_arg=0xeb64b0) at bdev_raid.c:1462
#7  0x0000000000430e4f in rpc_bdev_raid_delete (request=0xc58f30, params=0xc59090)
    at bdev_raid_rpc.c:423
#8  0x00000000005132b5 in jsonrpc_handler (request=0xc58f30, method=0xc59050, params=0xc59090)
    at rpc.c:128
#9  0x0000000000515265 in jsonrpc_server_handle_request (request=0xc58f30, method=0xc59050,
    params=0xc59090) at jsonrpc_server_tcp.c:244
#10 0x0000000000513d5b in parse_single_request (request=0xc58f30, values=0xc59010)
    at jsonrpc_server.c:103
#11 0x0000000000514342 in jsonrpc_parse_request (conn=0xc80db0, json=0xc80dc8, size=104)
    at jsonrpc_server.c:233
#12 0x0000000000515485 in jsonrpc_server_conn_recv (conn=0xc80db0) at jsonrpc_server_tcp.c:306
#13 0x0000000000515857 in spdk_jsonrpc_server_poll (server=0xc80d80) at jsonrpc_server_tcp.c:424
#14 0x00000000005135ae in spdk_rpc_accept () at rpc.c:217
#15 0x0000000000503d69 in rpc_subsystem_poll (arg=0x0) at rpc.c:49
#16 0x000000000050a868 in thread_execute_timed_poller (thread=0xc54190, poller=0xc75c10,
    now=19368630973297390) at thread.c:878
#17 0x000000000050ab11 in thread_poll (thread=0xc54190, max_msgs=0, now=19368630973297390)
    at thread.c:966
#18 0x000000000050abb0 in spdk_thread_poll (thread=0xc54190, max_msgs=0, now=19368630973297390)
    at thread.c:992
#19 0x00000000004dbcad in _reactor_run (reactor=0xc51480) at reactor.c:924
#20 0x00000000004dbd9c in reactor_run (arg=0xc51480) at reactor.c:962
#21 0x00000000004dc167 in spdk_reactors_start () at reactor.c:1064
#22 0x00000000004d8cdd in spdk_app_start (opts_user=0x7fffffffdcd0,
    start_fn=0x409db6 <bdevperf_run>, arg1=0x0) at app.c:645
#23 0x000000000040a859 in main (argc=18, argv=0x7fffffffde88) at bdevperf.c:2157
```

**Comment by Comphix** [comment]
Raised the patch as following:

https://review.spdk.io/gerrit/c/spdk/spdk/+/13061

**Comment by changpe1** [comment]
Patch has been merged, closing this issue now.
