### ISSUE TITLE
[SMA] Can't find some modules in spdk/python/spdk/sma/proto path, such as sma_pb2, sma_pb2_grpc...

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2592]
# Bug report

Some module can't be found in spdk/python/spdk/sma/proto path, SMA test run fail.

## Steps to Reproduce

1. Compile SPDK code
2. `./test/sma/sma.sh`
3. Error raised 
[2022-07-18 13:13:56.840447] app.c: 575:spdk_app_start: *NOTICE*: Total cores available: 1
Traceback (most recent call last):
  File "/home/wenjun/spdk/scripts/sma.py", line 15, in <module>
    import spdk.sma as sma               # noqa
  File "/home/wenjun/spdk/python/spdk/sma/__init__.py", line 7, in <module>
    from .sma import StorageManagementAgent     # noqa
  File "/home/wenjun/spdk/python/spdk/sma/sma.py", line 6, in <module>
    from .device import DeviceException
  File "/home/wenjun/spdk/python/spdk/sma/device/__init__.py", line 1, in <module>
    from .device import DeviceException
  File "/home/wenjun/spdk/python/spdk/sma/device/device.py", line 1, in <module>
    from ..proto import sma_pb2
ImportError: cannot import name 'sma_pb2' from 'spdk.sma.proto' (unknown location)

There is no module named sma_pb2 in spdk/python/spdk/sma/proto path, or should I export PYTHONPATH=xxxx.

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: 3512714b3f3dbb9f432bdc5dba0d85fc65fd7b22

**Comment by junwenx** [comment]
@ksztyber The reason is that, sorry for my wrong configuration, now it is ok. And the ticket can be closed. Thanks!
