### ISSUE TITLE
[vhost_blockdev] job hit timeout while waiting for vhost to terminate

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2601]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-per-patch/builds/81043/archive/vhost-initiator-vg-autotest/build.log

```
00:03:44.492    12:34:29	-- initiator/blockdev.sh@66 -- # rpc_cmd -s /tmp/spdk2.sock save_subsystem_config -n bdev
00:03:44.492    12:34:29	-- common/autotest_common.sh@486 -- # xtrace_disable
00:03:44.492    12:34:29	-- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
00:03:44.492    12:34:29	-- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=hxBET
00:03:44.492    12:34:29	-- common/autotest_common.sh@16 -- # [[ hxBET == *\x* ]]
00:03:44.492    12:34:29	-- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
00:03:44.492    12:34:29	-- common/autotest_common.sh@19 -- # set +x
00:03:44.492    12:34:29	-- common/autotest_common.sh@513 -- # xtrace_enable
00:03:44.492    12:34:29	-- common/autotest_common.sh@514 -- # [[ 0 == 0 ]]
00:03:44.492   12:34:29	-- initiator/blockdev.sh@71 -- # killprocess 17327
00:03:44.492   12:34:29	-- common/autotest_common.sh@822 -- # '[' -z 17327 ']'
00:03:44.492   12:34:29	-- common/autotest_common.sh@826 -- # kill -0 17327
00:03:44.492    12:34:29	-- common/autotest_common.sh@827 -- # uname
00:03:44.492   12:34:29	-- common/autotest_common.sh@827 -- # '[' Linux = Linux ']'
00:03:44.492    12:34:29	-- common/autotest_common.sh@828 -- # ps --no-headers -o comm= 17327
00:03:44.492   12:34:29	-- common/autotest_common.sh@828 -- # process_name=reactor_0
00:03:44.492   12:34:29	-- common/autotest_common.sh@832 -- # '[' reactor_0 = sudo ']'
00:03:44.492   12:34:29	-- common/autotest_common.sh@840 -- # echo 'killing process with pid 17327'
00:03:44.492  killing process with pid 17327
00:03:44.492   12:34:29	-- common/autotest_common.sh@841 -- # kill 17327
00:03:44.492   12:34:29	-- common/autotest_common.sh@846 -- # wait 17327
00:03:44.751  VHOST_CONFIG: (/home/vagrant/spdk_repo/spdk/naa.Malloc1.0) read message VHOST_USER_SET_MEM_TABLE
...
00:03:45.278  VHOST_CONFIG: (/home/vagrant/spdk_repo/spdk/naa.Malloc1.0) vhost peer closed
00:16:23.743  Cancelling nested steps due to timeout
00:16:23.746  Sending interrupt signal to processe
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_81043.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @EugeneKochetov. log: https://ci.spdk.io/public_build/autotest-per-patch_81010.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_81221.html

**Comment by mikeBashStuff** [comment]
This is the same issue as #2596 . Verified while attaching to `spdk_tgt` when it locks:

```
Attaching to process 8628
[New LWP 8630]
[New LWP 8631]

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.fedoraproject.org/
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading 0.57 MB separate debug info for /usr/lib64/iscsi/libiscsi.so.9
Downloading 0.13 MB separate debug info for /root/.cache/debuginfod_client/af8c9e8e7d6021042c066b805c179185f490389e/debuginfo
Downloading 1.79 MB separate debug info for /usr/lib64/libubsan.so.1
Downloading 65.95 MB separate debug info for /root/.cache/debuginfod_client/a30a9c81bfb63c0c4303f49e23d90b05f1a01f53/debuginfo
Downloading 7.43 MB separate debug info for /usr/lib64/libc.so.6
Downloading 0.01 MB separate debug info for /usr/lib64/libaio.so.1
Downloading 0.00 MB separate debug info for /root/.cache/debuginfod_client/10d0b58965f676c6d82d836326436912cfa81b7e/debuginfo
Downloading 1.94 MB separate debug info for /usr/lib64/libssl.so.1.1
Downloading 0.04 MB separate debug info for /root/.cache/debuginfod_client/36503cbaf9669d62565307ca9de097fdb1e2d170/debuginfo
Downloading 7.96 MB separate debug info for /usr/lib64/libcrypto.so.1.1
Downloading 0.59 MB separate debug info for /usr/lib64/libibverbs.so.1
Downloading 0.34 MB separate debug info for /root/.cache/debuginfod_client/a874d27cb4a63cc2741374b19bb1fba607c192b4/debuginfo
Downloading 0.37 MB separate debug info for /usr/lib64/librdmacm.so.1
Downloading 0.33 MB separate debug info for /usr/lib64/libgcc_s.so.1
Downloading 0.08 MB separate debug info for /usr/lib64/libuuid.so.1
Downloading 0.20 MB separate debug info for /root/.cache/debuginfod_client/52d4ea2a005c5cbce6e92f00278205803074b572/debuginfo
Downloading 2.20 MB separate debug info for /usr/lib64/libm.so.6
Downloading 0.15 MB separate debug info for /usr/lib64/libnuma.so.1
Downloading 0.01 MB separate debug info for /root/.cache/debuginfod_client/24b3826eb785d8e4dfec3a9b8e5fe37117269d57/debuginfo
Downloading 3.75 MB separate debug info for /usr/lib64/libgcrypt.so.20
Downloading 0.02 MB separate debug info for /root/.cache/debuginfod_client/711d41580c5a8649a79a8430a985dac3e25b5ba2/debuginfo
Downloading 14.35 MB separate debug info for /usr/lib64/libstdc++.so.6
Downloading 0.21 MB separate debug info for /usr/lib64/libz.so.1
Downloading 1.71 MB separate debug info for /usr/lib64/libnl-route-3.so.200
Downloading 0.07 MB separate debug info for /root/.cache/debuginfod_client/25ac144713fd4d7ed0d9394a7d36c424b185fdf1/debuginfo
Downloading 0.41 MB separate debug info for /usr/lib64/libnl-3.so.200
Downloading 0.52 MB separate debug info for /usr/lib64/libgpg-error.so.0
Downloading 0.03 MB separate debug info for /root/.cache/debuginfod_client/081975d0a3416374b4883b2f1639fd3c9df42390/debuginfo

bt
^CCancelling download of separate debug info for system-supplied DSO at 0x7ffdd9597000...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
0x00007f8379f93ed4 in rte_spinlock_lock (sl=0x7f8379fe0001) at ../lib/eal/x86/include/rte_spinlock.h:28
28              asm volatile (
(gdb) bt
#0  0x00007f8379f93ed4 in rte_spinlock_lock (sl=0x7f8379fe0001) at ../lib/eal/x86/include/rte_spinlock.h:28
#1  0x00007f8379f95847 in malloc_heap_free (elem=0x200000266000) at ../lib/eal/common/malloc_heap.c:878
#2  0x00007f8379f97388 in mem_free (addr=0x200000266080, trace_ena=true) at ../lib/eal/common/rte_malloc.c:37
#3  0x00007f8379f973cc in rte_free (addr=0x200000266080) at ../lib/eal/common/rte_malloc.c:44
#4  0x00007f8379d87dca in rte_mempool_free_memchunks (mp=0x200000266800) at ../lib/mempool/rte_mempool.c:292
#5  0x00007f8379d8985b in rte_mempool_free (mp=0x200000266800) at ../lib/mempool/rte_mempool.c:741
#6  0x00007f837b02c76c in spdk_mempool_free (mp=0x200000266800) at env.c:238
#7  0x00007f837a25b59f in spdk_thread_lib_fini () at thread.c:314
#8  0x00007f837a7cbf6c in spdk_reactors_fini () at reactor.c:276
#9  0x00007f837a7c7daf in spdk_app_fini () at app.c:628
#10 0x000000000040276a in main (argc=4, argv=0x7ffdd93fb138) at spdk_tgt.c:93
(gdb) bt full
#0  0x00007f8379f93ed4 in rte_spinlock_lock (sl=0x7f8379fe0001) at ../lib/eal/x86/include/rte_spinlock.h:28
        lock_val = 1
#1  0x00007f8379f95847 in malloc_heap_free (elem=0x200000266000) at ../lib/eal/common/malloc_heap.c:878
        heap = 0x7f8379fe0001
        start = 0x7ffdd93fae10
        aligned_start = 0x200000266000
        end = 0x7ffdd93fadc0
        aligned_end = 0x200003fff400
        len = 140202663723644
        aligned_len = 140728248282608
        page_sz = 2097152
        msl = 0x7f8379fe2348 <early_mem_config+136>
        i = 8192
        n_segs = 2515072
        before_space = 5
        after_space = 184320
        ret = 0
        unmapped = false
        internal_conf = 0x7f8379fe95c0 <internal_config>
        asan_ptr = 0x200000266140
        asan_data_len = 64
#2  0x00007f8379f97388 in mem_free (addr=0x200000266080, trace_ena=true) at ../lib/eal/common/rte_malloc.c:37
No locals.
#3  0x00007f8379f973cc in rte_free (addr=0x200000266080) at ../lib/eal/common/rte_malloc.c:44
No locals.
#4  0x00007f8379d87dca in rte_mempool_free_memchunks (mp=0x200000266800) at ../lib/mempool/rte_mempool.c:292
        memhdr = 0x200000266080
        elt = 0x200003fff440
#5  0x00007f8379d8985b in rte_mempool_free (mp=0x200000266800) at ../lib/mempool/rte_mempool.c:741
        mempool_list = 0x7f8379fe6778 <early_mem_config+17592>
        te = 0x200000266940
#6  0x00007f837b02c76c in spdk_mempool_free (mp=0x200000266800) at env.c:238
No locals.
#7  0x00007f837a25b59f in spdk_thread_lib_fini () at thread.c:314
        dev = 0x0
        __func__ = "spdk_thread_lib_fini"
#8  0x00007f837a7cbf6c in spdk_reactors_fini () at reactor.c:276
        i = 128
        reactor = 0x7f8376d77c78
        __PRETTY_FUNCTION__ = "spdk_reactors_fini"
#9  0x00007f837a7c7daf in spdk_app_fini () at app.c:628
No locals.
#10 0x000000000040276a in main (argc=4, argv=0x7ffdd93fb138) at spdk_tgt.c:93
        opts = {name = 0x4050f4 "spdk_tgt", json_config_file = 0x0, json_config_ignore_errors = false, rpc_addr = 0x7ffdd93fcda4 "/tmp/spdk2.sock", reactor_mask = 0x7f837a7df1cc "0x1", tpoint_group_mask = 0x0,
          shm_id = -1, shutdown_cb = 0x0, enable_coredump = true, mem_channel = -1, main_core = -1, mem_size = -1, no_pci = false, hugepage_single_segments = true, unlink_hugepage = false, hugedir = 0x0,
          print_level = SPDK_LOG_INFO, num_pci_addr = 0, pci_blocked = 0x0, pci_allowed = 0x0, iova_mode = 0x0, delay_subsystem_init = false, num_entries = 32768, env_context = 0x0, log = 0x0,
          base_virtaddr = 35184372088832, opts_size = 200, disable_signal_handlers = false, msg_mempool_size = 262143}
        rc = 0
(gdb) info proc cmdline
process 8628
cmdline = '/root/spdk/build/bin/spdk_tgt -r /tmp/spdk2.sock -g'
(gdb)

```

**Comment by jimharris** [comment]
This is closely related to #2596.  The failing call stacks are identical, they just result in different symptoms (SIGSEGV for 2596, hang for 2601).
