### ISSUE TITLE
Performance of NVMf/VFIOUSER with Cloud-hypervisor 

### ISSUE THREAD

**Issue by Apokleos** [spdk/spdk#2626]
# Bug report
Hi, @changpe1, I open an issue for my test configuration. and FIO parameters are same to the PPT's.  

## Expected Behavior
Get Similar behaviour as the official statistics.

## Current Behavior
NVMf/VFIOUSER cores scaling performance is diffrent from the data in [High Performance NVMe Virtualization with SPDK and vfio-user](https://www.snia.org/educational-library/high-performance-nvme-virtualization-spdk-and-vfio-user-2021) with Cloud-hypervisor

## Steps to Reproduce
0. SPDK 
NVMf/VFIOUSER : 
```build/bin/nvmf_tgt -m 0xF000000 ```
VHost-user-blk : 
```build/bin/vhost -m 0xF0000 -S $VHU_UDS_PATH```
1. NVMf/VFIOUSER
```
rpc.py bdev_null_create ${NVFU_BDEV} 102400 512
${RPC_CMD} nvmf_create_subsystem -a -s ${SERIAL_NUMBER} ${NQN}
${RPC_CMD} nvmf_subsystem_add_ns ${NQN} ${NVFU_BDEV}
${RPC_CMD} nvmf_subsystem_add_listener -t ${TRTYPE} -a ${TRADDR} -s 0 ${NQN}
${RPC_CMD} nvmf_get_subsystems
```
2. VHOST-USER-BLK
```
${RPC_CMD} bdev_null_create ${VHU_BDEV} 102400 512
${RPC_CMD} vhost_create_blk_controller vhostx$i.sock ${VHU_BDEV}
```

3. The script for running a CLH VM.
```
#!/bin/bash
# ; $ cd ClhDev/
# ; $tree -L 2
# ; .
# ; ├── xxx
# ; ├── Clh02
# ; │   ├── clh-vfu-vm.sh
# ; │   ├── focal20.04-amd64.raw
# ; │   └── vmlinux
# ; └── cloud-hypervisor

set -e # fast fail

Action=$1

TAG=2
NUM=4
CPU=4
MEMOR=8G
CLHx=Clh02

CLH_DEV_ROOT=/xxx/ClhDev
CLH_WORK_DIR=$CLH_DEV_ROOT/${CLHx}
CLOUD_HYPERVISOR_DEV=${CLH_DEV_ROOT}
ROOT_RAW_DISK=${CLH_WORK_DIR}/focal20.04-amd64.raw

# vhost user blk uds
VHU_UDS_PATH=/tmp/vhu-targets
VHU_BLK_UDS=${VHU_UDS_PATH}/vhostx2.sock
VHU_BLK_DEV="--disk path=${ROOT_RAW_DISK} vhost_user=true,socket=${VHU_BLK_UDS},num_queues=${NUM}"

# nvmf/VFIO_USER_DEV Target NVMF_VFU_PATH=
NVMF_VFU_TARGET=/tmp/nvmf-vfiouserx${TAG}/cntrl
VFIO_USER_DEV="--user-device socket=${NVMF_VFU_TARGET}"

VMM=${CLOUD_HYPERVISOR_DEV}/cloud-hypervisor
MACHINE="--cpus boot=${CPU} --memory size=${MEMOR},shared=on"
#MACHINE="--cpus boot=${CPU} --memory size=${MEMOR},shared=on,hugepages=on,hugepage_size=2M,prefault=on"
VMLINUX="--kernel ${CLH_WORK_DIR}/vmlinux --console off --serial tty"
DISK="--disk path=${ROOT_RAW_DISK},poll_queue=on,num_queues=${NUM}"

function clh_vmm_start_nvmf_vfu_vmlinux() {
	${VMM} ${MACHINE} --cmdline "console=ttyS0 root=/dev/vda1 rw iommu=off" ${VMLINUX} ${DISK} ${VFIO_USER_DEV}
}

function clh_vmm_start_vhu_vmlinux() {
	${VMM} ${MACHINE} --cmdline "console=ttyS0 root=/dev/vda1 rw iommu=off" ${VMLINUX} ${VHU_BLK_DEV} 
}

main () {
  case ${Action} in
    nvmf)
    echo "do clh nvmf vfu run"
    clh_vmm_start_nvmf_vfu_vmlinux
    ;;
    vhu)
    echo "do clh vhost-user run."
   	clh_vmm_start_vhu_vmlinux
    ;;
    *)
    echo "unsupport action"
    exit 1
    ;;
  esac
}

CURR_TIME=`date +%s`
setcap cap_net_admin+ep ${VMM}
main

```

## Context (Environment including OS version, SPDK version, etc.)
SPDK: 
master branch

Cloud-Hypervisor: 
cloud-hypervisor v25.0-120-g0c9b4fef

Thanks.

**Comment by changpe1** [comment]
@Apokleos Do you meet the following error when running cloud hypervisor?

[    0.246793] nvme 0000:00:05.0: enabling device (0000 -> 0002)
thread 'vcpu3' panicked at 'Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', vmm/src/interrupt.rs:82:18

**Comment by Apokleos** [comment]
> 



> @Apokleos Do you meet the following error when running cloud hypervisor?
> 
> [ 0.246793] nvme 0000:00:05.0: enabling device (0000 -> 0002) thread 'vcpu3' panicked at 'Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', vmm/src/interrupt.rs:82:18
>

I didn't meet the error ever. What's your command for running CLH VM?

**Comment by changpe1** [comment]
> > 
> 
> > @Apokleos Do you meet the following error when running cloud hypervisor?
> > [ 0.246793] nvme 0000:00:05.0: enabling device (0000 -> 0002) thread 'vcpu3' panicked at 'Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', vmm/src/interrupt.rs:82:18
> 
> I didn't meet the error ever. What's your command for running CLH VM?

![image](https://user-images.githubusercontent.com/14796941/182786166-785e262c-ac1c-424b-b4c9-0947a7a0c1d2.png)

**Comment by Apokleos** [comment]
I 

> > > 
> > 
> > 
> > > @Apokleos Do you meet the following error when running cloud hypervisor?
> > > [ 0.246793] nvme 0000:00:05.0: enabling device (0000 -> 0002) thread 'vcpu3' panicked at 'Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', vmm/src/interrupt.rs:82:18
> > 
> > 
> > I didn't meet the error ever. What's your command for running CLH VM?
> 
> ![image](https://user-images.githubusercontent.com/14796941/182786166-785e262c-ac1c-424b-b4c9-0947a7a0c1d2.png)
>
I think the argument `--api-socket` needs to be removed.

**Comment by changpe1** [comment]
Looks like the cloud image reported this error due to too many file descriptors, but this issue is somehow caused by vfio-user target, I'm curious that how can you run it successfully.

[pid  9735] dup(461)                    = 1015
[pid  9735] dup(462)                    = 1016
[pid  9735] dup(463)                    = 1017
[pid  9735] dup(464)                    = 1018
[pid  9735] dup(465)                    = 1019
[pid  9735] dup(466)                    = 1020
[pid  9735] dup(467)                    = 1021
[pid  9735] dup(468)                    = 1022
[pid  9735] dup(469)                    = 1023
[pid  9735] dup(470)                    = -1 EMFILE (Too many open files)
[pid  9735] write(2, "thread '", 8thread ')     = 8
[pid  9735] write(2, "vcpu0", 5vcpu0)        = 5
[pid  9735] write(2, "' panicked at '", 15' panicked at ') = 15
[pid  9735] write(2, "Failed cloning interrupt's Event"..., 104Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "Too many open files" }) = 104

**Comment by Apokleos** [comment]
> Looks like the cloud image reported this error due to too many file descriptors, but this issue is somehow caused by vfio-user target, I'm curious that how can you run it successfully.
> 
> [pid 9735] dup(461) = 1015 [pid 9735] dup(462) = 1016 [pid 9735] dup(463) = 1017 [pid 9735] dup(464) = 1018 [pid 9735] dup(465) = 1019 [pid 9735] dup(466) = 1020 [pid 9735] dup(467) = 1021 [pid 9735] dup(468) = 1022 [pid 9735] dup(469) = 1023 [pid 9735] dup(470) = -1 EMFILE (Too many open files) [pid 9735] write(2, "thread '", 8thread ') = 8 [pid 9735] write(2, "vcpu0", 5vcpu0) = 5 [pid 9735] write(2, "' panicked at '", 15' panicked at ') = 15 [pid 9735] write(2, "Failed cloning interrupt's Event"..., 104Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "Too many open files" }) = 104

>
My cmd line:
```
./cloud-hypervisor --cpus boot=16 --memory size=16G,shared=on \
--cmdline console=ttyS0 root=/dev/vda1 rw iommu=off \
--kernel ./vmlinux --console off --serial tty \
--net tap=virttap1 \
--disk path=./focal20.04-amd64.raw,num_queues=16 \
--user-device socket=/tmp/nvmf-vfiouserx1/cntrl
```

I get vmlinux and focal raw cloud image from [Cloud-Hypervisor Official Run](https://github.com/cloud-hypervisor/cloud-hypervisor#run)

**Comment by changpe1** [comment]
> > Looks like the cloud image reported this error due to too many file descriptors, but this issue is somehow caused by vfio-user target, I'm curious that how can you run it successfully.
> > [pid 9735] dup(461) = 1015 [pid 9735] dup(462) = 1016 [pid 9735] dup(463) = 1017 [pid 9735] dup(464) = 1018 [pid 9735] dup(465) = 1019 [pid 9735] dup(466) = 1020 [pid 9735] dup(467) = 1021 [pid 9735] dup(468) = 1022 [pid 9735] dup(469) = 1023 [pid 9735] dup(470) = -1 EMFILE (Too many open files) [pid 9735] write(2, "thread '", 8thread ') = 8 [pid 9735] write(2, "vcpu0", 5vcpu0) = 5 [pid 9735] write(2, "' panicked at '", 15' panicked at ') = 15 [pid 9735] write(2, "Failed cloning interrupt's Event"..., 104Failed cloning interrupt's EventFd: Os { code: 24, kind: Uncategorized, message: "Too many open files" }) = 104
> 
> > 
> 
> My cmd line:
> 
> ```
> ./cloud-hypervisor --cpus boot=16 --memory size=16G,shared=on \
> --cmdline console=ttyS0 root=/dev/vda1 rw iommu=off \
> --kernel ./vmlinux --console off --serial tty \
> --net tap=virttap1 \
> --disk path=./focal20.04-amd64.raw,num_queues=16 \
> --user-device socket=/tmp/nvmf-vfiouserx1/cntrl
> ```
> 
> I get vmlinux and focal raw cloud image from [Cloud-Hypervisor Official Run](https://github.com/cloud-hypervisor/cloud-hypervisor#run)

OK, I can run it now after limit the MSIX from default 512 to 16, looks like this is a bug in cloud-hypervisor to duplicate all supported interrupt fds.

**Comment by changpe1** [comment]
I tested my vfio-user virtio-blk patches https://review.spdk.io/gerrit/c/spdk/spdk/+/12315 with cloud-hypervisor and QEMU, so for the same virtio-blk device type, cloud-hypervisor also showed not so good performance compared with QEMU.

But we do have a comparison for vhost-user-blk and vfio-user blk, they have similar performance results, so I guess this issue is related with hypervisor itself or VM guest kernel.

**Comment by Apokleos** [comment]
> I tested my vfio-user virtio-blk patches https://review.spdk.io/gerrit/c/spdk/spdk/+/12315 with cloud-hypervisor and QEMU, so for the same virtio-blk device type, cloud-hypervisor also showed not so good performance compared with QEMU.
> 
> But we do have a comparison for vhost-user-blk and vfio-user blk, they have similar performance results, so I guess this issue is related with hypervisor itself or VM guest kernel.
>
Hi,  @changpe1 

 I also have the similar performance result between vfu-blk and vhu-blk, even with the CLH VMM. and I think that it already reaches the target based on the design of vfu-blk.

But, the NVMf/VFIOUSER still shows not good as related statistics.

**Comment by changpe1** [comment]
> > I tested my vfio-user virtio-blk patches https://review.spdk.io/gerrit/c/spdk/spdk/+/12315 with cloud-hypervisor and QEMU, so for the same virtio-blk device type, cloud-hypervisor also showed not so good performance compared with QEMU.
> > But we do have a comparison for vhost-user-blk and vfio-user blk, they have similar performance results, so I guess this issue is related with hypervisor itself or VM guest kernel.
> 
> Hi, @changpe1
> 
> I also have the similar performance result between vfu-blk and vhu-blk, even with the CLH VMM. and I think that it already reaches the target based on the design of vfu-blk.
> 
> But, the NVMf/VFIOUSER still shows not good as related statistics.

I didn't do the direct comparison between vfu-blk and vhu-blk with Cloud-Hypervisor, I tested them with QEMU and got similar performance number, in theory, they should have similar performance number if you are using the same VMM.

**Comment by Apokleos** [comment]
> > > I tested my vfio-user virtio-blk patches https://review.spdk.io/gerrit/c/spdk/spdk/+/12315 with cloud-hypervisor and QEMU, so for the same virtio-blk device type, cloud-hypervisor also showed not so good performance compared with QEMU.
> > > But we do have a comparison for vhost-user-blk and vfio-user blk, they have similar performance results, so I guess this issue is related with hypervisor itself or VM guest kernel.
> > 
> > 
> > Hi, @changpe1
> > I also have the similar performance result between vfu-blk and vhu-blk, even with the CLH VMM. and I think that it already reaches the target based on the design of vfu-blk.
> > But, the NVMf/VFIOUSER still shows not good as related statistics.
> 
> I didn't do the direct comparison between vfu-blk and vhu-blk with Cloud-Hypervisor, I tested them with QEMU and got similar performance number, in theory, they should have similar performance number if you are using the same VMM.
>
Yes, with the same VMM testing ,the result will be similar, and as the result of similar performance, vfu-blk will be an option for some scenario.

But  if NVMF/VFIOUSER gets a better performance compared with vhost-user-blk with many VMs(one VM case seems no point), NVMF-VFIOUSER and vfu-blk will help us more.

And I am waiting for the new v22.09.
