### ISSUE TITLE
[rocky 8 & pmdk] java errors  - ClosedByInterruptException

### ISSUE THREAD

**Issue by peluse** [spdk/spdk#2648]
00:01:34.207  + /usr/local/bin/ssh -t -F ssh_conf vagrant@vagrant sudo chown vagrant:vagrant spdk_repo
00:01:34.221  [Pipeline] sh
00:07:11.186  [Pipeline] }
00:07:11.224  [Pipeline] // timeout
00:07:11.229  [Pipeline] }
00:07:11.257  [Pipeline] // stage
00:07:11.264  [Pipeline] }
00:07:11.268  java.nio.channels.ClosedByInterruptException
00:07:11.268  	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
00:07:11.268  	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
00:07:11.268  	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:285)
00:07:11.268  	at org.jenkinsci.plugins.workflow.support.pickles.serialization.RiverWriter.<init>(RiverWriter.java:109)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:577)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgram(CpsThreadGroup.java:554)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.saveProgramIfPossible(CpsThreadGroup.java:537)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:461)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
00:07:11.268  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
00:07:11.268  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:07:11.268  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
00:07:11.268  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
00:07:11.268  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
00:07:11.268  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
00:07:11.268  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:07:11.268  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:07:11.268  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:07:11.268  	at java.base/java.lang.Thread.run(Thread.java:829)
00:07:11.286  [Pipeline] // catchError
00:07:11.293  [Pipeline] stage
00:07:11.295  [Pipeline] { (Stop VM)
00:07:11.307  [Pipeline] sh
00:07:31.834  + vagrant halt
00:07:31.834  ==> default: Halting domain...
00:07:40.814  [Pipeline] sh
00:07:41.903  + vagrant destroy -f
00:07:46.385  ==> default: Removing domain...
00:07:46.397  [Pipeline] sh
00:07:51.511  + mv output /var/jenkins/workspace/rocky8-vg-autotest@2/output
00:07:51.529  [Pipeline] }
00:07:51.553  [Pipeline] // stage
00:07:51.560  [Pipeline] }
00:07:51.584  [Pipeline] // dir
00:07:51.594  [Pipeline] }
00:07:51.618  [Pipeline] // catchError
00:07:51.627  [Pipeline] stage
00:07:51.630  [Pipeline] { (Epilogue)
00:07:51.643  [Pipeline] sh
00:07:52.032  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:07:52.048  [Pipeline] archiveArtifacts
00:07:52.056  Archiving artifacts
00:07:52.072  [Pipeline] cleanWs
00:07:52.082  [WS-CLEANUP] Deleting project workspace...
00:07:52.083  [WS-CLEANUP] Deferred wipeout is used...
00:07:52.091  [WS-CLEANUP] done
00:07:52.093  [Pipeline] }
00:07:52.115  [Pipeline] // stage
00:07:52.121  [Pipeline] }
00:07:52.138  [Pipeline] // node
00:07:52.147  [Pipeline] End of Pipeline
00:07:52.167  Finished: FAILURE

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @peluse. log: https://ci.spdk.io/public_build/autotest-per-patch_82849.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_83619.html
