### ISSUE TITLE
Memory leaks detected inside xnvme_dev_alloc

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2654]
```
SPDK: v22.05-rc1-426-gcd1b7ab0e
```

For SPDK built with xnvme support and enabled ASAN, the following memory leak is picked up while working with xnvme bdev:

```
09:33:07       -- dd/malloc.sh@61 -- # /root/spdk_test/build/bin/spdk_dd --ib=malloc0 --ob=zram0 --json /dev/fd/62
  09:33:07      -- dd/malloc.sh@61 -- # gen_conf
  09:33:07      -- dd/common.sh@26 -- # xtrace_disable
  09:33:07      -- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
  09:33:07      -- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
  09:33:07      -- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
  09:33:07      -- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
  09:33:07      -- common/autotest_common.sh@19 -- # set +x
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "block_size": 512,
            "num_blocks": 1048576,
            "name": "malloc0"
          },
          "method": "bdev_malloc_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/zram1",
            "name": "zram0"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "method": "bdev_wait_for_examine"
        }
      ]
    }
  ]
}
  09:33:07      -- dd/common.sh@95 -- # xtrace_enable
[2022-08-23 09:33:07.495608] Starting SPDK v22.09-pre git sha1 7e815c3ba / DPDK 22.03.0 initialization...
[2022-08-23 09:33:07.495948] [ DPDK EAL parameters: [2022-08-23 09:33:07.496026] spdk_dd [2022-08-23 09:33:07.496137] --no-shconf [2022-08-23 09:33:07.496251] -c 0x1 [2022-08-23 09:33:07.496416] --huge-unlink [2022-08-23 09:33:07.496510] --log-level=lib.eal:6 [2022-08-23 09:33:07.496671] --log-level=lib.cryptodev:5 [2022-08-23 09:33:07.496712] --log-level=user1:6 [2022-08-23 09:33:07.496802] --iova-mode=pa [2022-08-23 09:33:07.496888] --base-virtaddr=0x200000000000 [2022-08-23 09:33:07.496985] --match-allocations [2022-08-23 09:33:07.497063] --file-prefix=spdk_pid798746 [2022-08-23 09:33:07.497157] ]
TELEMETRY: No legacy callbacks, legacy socket not created
[2022-08-23 09:33:07.640140] app.c: 586:spdk_app_start: *NOTICE*: Total cores available: 1
[2022-08-23 09:33:08.027617] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 0
[2022-08-23 09:33:08.029337] accel_sw.c: 377:sw_accel_engine_init: *NOTICE*: Accel framework software engine initialized.
Copying: 512/512 [MB] (average 283 MBps)


=================================================================
==798746==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 17272 byte(s) in 1 object(s) allocated from:
    #0 0x7f5ebbeb2ad7 in calloc (/usr/lib64/libasan.so.6+0xaead7)
    #1 0x409b52 in xnvme_dev_alloc (/root/spdk_test/build/bin/spdk_dd+0x409b52)

SUMMARY: AddressSanitizer: 17272 byte(s) leaked in 1 allocation(s).
  09:33:10      -- dd/malloc.sh@61 -- # trap - ERR
  09:33:10      -- dd/malloc.sh@61 -- # print_backtrace
  09:33:10      -- common/autotest_common.sh@1046 -- # [[ ehxBET =~ e ]]
  09:33:10      -- common/autotest_common.sh@1048 -- # args=('malloc_to_xnvme_copy' 'dd_malloc_to_xnvme_copy')
  09:33:10      -- common/autotest_common.sh@1048 -- # local args
  09:33:10      -- common/autotest_common.sh@1050 -- # xtrace_disable
  09:33:10      -- common/autotest_common.sh@14 -- # '[' no '!=' yes ']'
  09:33:10      -- common/autotest_common.sh@15 -- # PREV_BASH_OPTS=ehxBET
  09:33:10      -- common/autotest_common.sh@16 -- # [[ ehxBET == *\x* ]]
  09:33:10      -- common/autotest_common.sh@17 -- # XTRACE_DISABLED=yes
  09:33:10      -- common/autotest_common.sh@19 -- # set +x
========== Backtrace start: ==========

in ./test/dd/malloc.sh:61 -> malloc_to_xnvme_copy([])
     ...
   56                   method_bdev_xnvme_create_0["name"]=$xnvme0
   57                   method_bdev_xnvme_create_0["filename"]="/dev/zram$xnvme0_dev"
   58                   method_bdev_xnvme_create_0["io_mechanism"]="$io"
   59
   60                   "${DD_APP[@]}" \
=> 61                           --ib="$mbdev0" \
   62                           --ob="$xnvme0" \
   63                           --json <(gen_conf)
   64
   65                   "${DD_APP[@]}" \
   66                           --ib="$xnvme0" \
     ...
in /root/spdk_test/test/common/autotest_common.sh:1018 -> run_test(["dd_malloc_to_xnvme_copy"],["malloc_to_xnvme_copy"])
     ...
   1013         timing_enter $test_name
   1014         echo "************************************"
   1015         echo "START TEST $test_name"
   1016         echo "************************************"
   1017         xtrace_restore
   1018         time "$@"
   1019         xtrace_disable
   1020         echo "************************************"
   1021         echo "END TEST $test_name"
   1022         echo "************************************"
   1023         timing_exit $test_name
     ...
in ./test/dd/malloc.sh:75 -> main([])
     ...
   70
   71           remove_zram_dev "$xnvme0_dev"
   72   }
   73
   74   run_test "dd_malloc_copy" malloc_copy
=> 75   run_test "dd_malloc_to_xnvme_copy" malloc_to_xnvme_copy
     ...

========== Backtrace end ==========
```

Reproduced by: https://review.spdk.io/gerrit/c/spdk/spdk/+/14119
Workaround: https://review.spdk.io/gerrit/c/spdk/spdk/+/14118/10/test/common/autotest_common.sh

**Comment by yidong0635** [comment]
@mikeBashStuff  What about this one?
https://review.spdk.io/gerrit/c/spdk/spdk/+/14177

**Comment by Comphix** [comment]
@yidong0635 ， will you also try to raise a child patch after below patch so as to easily verify the fix?

Reproduced by: https://review.spdk.io/gerrit/c/spdk/spdk/+/14119

**Comment by yidong0635** [comment]
@Comphix   I rebase my patch to the above test serials and add remove suppression memory leak change. patch serials https://review.spdk.io/gerrit/c/spdk/spdk/+/14177

**Comment by mikeBashStuff** [comment]
@Comphix @yidong0635 Apologies, I have missed your comments. Please, rebase your patches once more - the tests should be now hooked to the nvme-vg-autotest job (we've added `SPDK_TEST_XNVME` flag on the CI side today) so you should be able to see now if your changes fix the issue. :)

**Comment by yidong0635** [comment]
@mikeBashStuff 
It doesn't matter, you are so kind. I rebased code to your  enabled `SPDK_TEST_XNVME` testing.
And I verified that:
1.(https://review.spdk.io/gerrit/c/spdk/spdk/+/14119)  suppressed memory leak.   ------->`pass`
2.(https://review.spdk.io/gerrit/c/spdk/spdk/+/14224)    removed suppressed memory leak--->`fail`
3. https://review.spdk.io/gerrit/c/spdk/spdk/+/14177       fixed memory leak              --------   ` pass`
Can I keep it independent without  merging 2 to 3?
Since I verified it's fixed this issue.  And Just rebase 2 after 3?
That just need rebase and update the commit message.

**Comment by changpe1** [comment]
patch has been merged, closing it now.
