### ISSUE TITLE
spdk_bdev plugin crashes while handling xnvme devices

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2702]
```
SPDK: v22.09-pre-623-ga1100c714
```

This is seen under nvme-perf test suite with changes from these patches: https://review.spdk.io/gerrit/q/topic:xnvme-perf. Crash happens when `fio` terminates.

Auto generated fio configuration:
```
[global]
direct=1
thread=1
norandommap=1
group_reporting=1
time_based=1
description="Test io_plugin=spdk-plugin-bdev-xnvme Blocksize=4096 Workload=randread MIX=100 qd=128"

rw=randread
rwmixread=100
bs=4096
runtime=5
ramp_time=0
numjobs=1
log_avg_msec=0

[filename0]
iodepth=2816
cpus_allowed=0 #CPU NUMA Node 0
filename=Nvme0 #NVMe NUMA Node 0
filename=Nvme1 #NVMe NUMA Node 0
filename=Nvme2 #NVMe NUMA Node 0
filename=Nvme3 #NVMe NUMA Node 0
filename=Nvme4 #NVMe NUMA Node 0
filename=Nvme5 #NVMe NUMA Node 0
filename=Nvme6 #NVMe NUMA Node 0
filename=Nvme7 #NVMe NUMA Node 0
filename=Nvme8 #NVMe NUMA Node 0
filename=Nvme9 #NVMe NUMA Node 0
filename=Nvme10 #NVMe NUMA Node 1
filename=Nvme11 #NVMe NUMA Node 1
filename=Nvme12 #NVMe NUMA Node 1
filename=Nvme13 #NVMe NUMA Node 1
filename=Nvme14 #NVMe NUMA Node 1
filename=Nvme15 #NVMe NUMA Node 1
filename=Nvme16 #NVMe NUMA Node 1
filename=Nvme17 #NVMe NUMA Node 1
filename=Nvme18 #NVMe NUMA Node 1
filename=Nvme19 #NVMe NUMA Node 1
filename=Nvme20 #NVMe NUMA Node 1
filename=Nvme21 #NVMe NUMA Node 1
```

bdev configuration:
```
{
  "subsystems": [
    {
      "subsystem": "bdev",
      "config": [
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme15n1",
            "name": "Nvme0"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme8n1",
            "name": "Nvme1"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme19n1",
            "name": "Nvme10"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme21n1",
            "name": "Nvme11"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme20n1",
            "name": "Nvme12"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme12n1",
            "name": "Nvme13"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme14n1",
            "name": "Nvme14"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme1n1",
            "name": "Nvme15"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme3n1",
            "name": "Nvme16"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme18n1",
            "name": "Nvme17"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme9n1",
            "name": "Nvme18"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme16n1",
            "name": "Nvme19"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme4n1",
            "name": "Nvme2"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme17n1",
            "name": "Nvme20"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme10n1",
            "name": "Nvme21"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme0n1",
            "name": "Nvme3"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme11n1",
            "name": "Nvme4"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme2n1",
            "name": "Nvme5"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme13n1",
            "name": "Nvme6"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme6n1",
            "name": "Nvme7"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme7n1",
            "name": "Nvme8"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "params": {
            "io_mechanism": "libaio",
            "filename": "/dev/nvme5n1",
            "name": "Nvme9"
          },
          "method": "bdev_xnvme_create"
        },
        {
          "method": "bdev_wait_for_examine"
        }
      ]
    }
  ]
}
```

Point of crash (the actual benchmark finishes just fine, results are generated, but `fio` terminates ungracefully):
```
17:40:16       -- perf/common.sh@400 -- # /usr/src/fio/fio /root/spdk/test/nvme/perf/config.fio --output-format=json --output=/root/spdk/test/nvme/perf/result.json --ioengine=spdk_bdev --spdk_json_conf=/root/spdk/test/nvme/perf/bdev.conf --spdk_mem=4096
TELEMETRY: No legacy callbacks, legacy socket not created
/root/spdk/test/nvme/perf/common.sh: line 394: 1830844 Segmentation fault      (core dumped) LD_PRELOAD=$plugin_dir/spdk_bdev $FIO_BIN $testdir/config.fio --output-format=json "${@:2}" --ioengine=spdk_bdev --spdk_json_conf=$testdir/bdev.conf --spdk_mem=4096
  17:40:24      -- perf/common.sh@400 -- # rm -f '*.state' /root/spdk/test/nvme/perf/bdev.conf
  17:40:24      -- perf/common.sh@400 -- # kill
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[root@spdk-SM-12 spdk]#
```

Core's bt:
```
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `/usr/src/fio/fio /root/spdk/test/nvme/perf/config.fio --output-format=json --ou'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7f9a8ac38640 (LWP 1833023))]
Thread 4 (Thread 0x7f9a8bc3a640 (LWP 1833025)):
#0  0x00007f9ad37e7e0f in accept () from /usr/lib64/libc.so.6
No symbol table info available.
#1  0x00007f9ad49ec619 in socket_listener (socket=0x7f9ad4d3e380 <v2_socket>) at ../lib/telemetry/telemetry.c:399
        th = 140301746546240
        rc = 0
        s = 0x7f9ad4d3e380 <v2_socket>
        s_accepted = 32666
#2  0x00007f9ad3762a87 in start_thread () from /usr/lib64/libc.so.6
No symbol table info available.
#3  0x00007f9ad37e7640 in clone3 () from /usr/lib64/libc.so.6
No symbol table info available.
Thread 3 (Thread 0x7f9a8b439640 (LWP 1833024)):
#0  0x00007f9ad37e6c1e in epoll_wait () from /usr/lib64/libc.so.6
No symbol table info available.
#1  0x00007f9ad495509d in eal_intr_handle_interrupts (pfd=9, totalfds=1) at ../lib/eal/linux/eal_interrupts.c:1077
        events = {{events = 2336442208, data = {ptr = 0xd493683a00007f9a, fd = 32666, u32 = 32666, u64 = 15317701355934613402}}}
        nfds = 0
#2  0x00007f9ad49552d0 in eal_intr_thread_main (arg=0x0) at ../lib/eal/linux/eal_interrupts.c:1163
        pipe_event = {events = 3, data = {ptr = 0x7, fd = 7, u32 = 7, u64 = 7}}
        src = 0x0
        numfds = 1
        pfd = 9
        __func__ = "eal_intr_thread_main"
#3  0x00007f9ad4936c46 in ctrl_thread_init (arg=0x10286c0) at ../lib/eal/common/eal_common_thread.c:203
        internal_conf = 0x7f9ad4c1de80 <internal_config>
        cpuset = 0x7f9ad4c212c8 <internal_config+13384>
        params = 0x10286c0
        start_routine = 0x7f9ad4955102 <eal_intr_thread_main>
        routine_arg = 0x0
#4  0x00007f9ad3762a87 in start_thread () from /usr/lib64/libc.so.6
No symbol table info available.
#5  0x00007f9ad37e7640 in clone3 () from /usr/lib64/libc.so.6
No symbol table info available.
Thread 2 (Thread 0x7f9ac9faad80 (LWP 1832909)):
#0  0x00007f9ad375f72a in __futex_abstimed_wait_common () from /usr/lib64/libc.so.6
No symbol table info available.
#1  0x00007f9ad37645f4 in __pthread_clockjoin_ex () from /usr/lib64/libc.so.6
No symbol table info available.
#2  0x00007f9ad47cd588 in spdk_fio_finish_env () at fio_plugin.c:1311
No locals.
#3  0x00007f9ad47cd5a9 in spdk_fio_unregister () at fio_plugin.c:1321
No locals.
#4  0x00007f9ad4dded6c in _dl_fini () at dl-fini.c:139
        array = 0x7f9ad4ba07d8
        i = <optimized out>
        l = 0x7f9ad4dcc430
        maps = 0x7ffcd032bef0
        i = 2
        l = <optimized out>
        nmaps = <optimized out>
        nloaded = <optimized out>
        ns = 0
        do_audit = <optimized out>
        __PRETTY_FUNCTION__ = "_dl_fini"
#5  0x00007f9ad3719de5 in __run_exit_handlers () from /usr/lib64/libc.so.6
No symbol table info available.
#6  0x00007f9ad3719f60 in exit () from /usr/lib64/libc.so.6
No symbol table info available.
#7  0x00007f9ad3702567 in __libc_start_call_main () from /usr/lib64/libc.so.6
No symbol table info available.
#8  0x00007f9ad370260c in __libc_start_main_impl () from /usr/lib64/libc.so.6
No symbol table info available.
#9  0x000000000040fe55 in _start ()
No symbol table info available.
Thread 1 (Thread 0x7f9a8ac38640 (LWP 1833023)):
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x00007f9ad4ad3f8d in xnvme_queue_term () from /root/spdk/build/fio/spdk_bdev
No symbol table info available.
#2  0x00007f9ad486202f in bdev_xnvme_queue_destroy_cb (io_device=0x13cb900, ctx_buf=0x10d3410) at bdev_xnvme.c:295
        ch = 0x10d3410
#3  0x00007f9ad48ebe0c in put_io_channel (arg=0x10d33b0) at thread.c:2222
        ch = 0x10d33b0
        do_remove_dev = true
        thread = 0x101cc00
        __func__ = "put_io_channel"
        __PRETTY_FUNCTION__ = "put_io_channel"
#4  0x00007f9ad48e82dd in msg_queue_run_batch (thread=0x101cc00, max_msgs=8) at thread.c:692
        msg = 0x2000fd0487c0
        count = 8
        i = 6
        messages = {0x2000fd048c40, 0x2000fd048b80, 0x2000fd048ac0, 0x2000fd048a00, 0x2000fd048940, 0x2000fd048880, 0x2000fd0487c0, 0x2000fd048700}
        notify = 1
        rc = 32666
        __func__ = "msg_queue_run_batch"
        __PRETTY_FUNCTION__ = "msg_queue_run_batch"
#5  0x00007f9ad48e8b28 in thread_poll (thread=0x101cc00, max_msgs=0, now=11085974740346641) at thread.c:908
        msg_count = 32666
        poller = 0x7f9ad489ba66 <rte_get_timer_cycles+9>
        tmp = 0x7f9ad48a198c <spdk_get_ticks+9>
        critical_msg = 0x0
        rc = 0
#6  0x00007f9ad48e8cb5 in spdk_thread_poll (thread=0x101cc00, max_msgs=0, now=11085974740346641) at thread.c:968
        orig_thread = 0x101c800
        rc = 1
        notify = 1
        __func__ = "spdk_thread_poll"
#7  0x00007f9ad47cc9e6 in spdk_fio_poll_thread (fio_thread=0x101cf40) at fio_plugin.c:832
No locals.
#8  0x00007f9ad47cb711 in spdk_init_thread_poll (arg=0x102dd40) at fio_plugin.c:376
        eo = 0x102dd40
        fio_thread = 0x101cb40
        thread = 0x101cf40
        tmp = 0x101cb40
        opts = {name = 0x7f9ad4ae20b8 "fio", core_mask = 0x7f9ad4b0cdb5 "0x1", shm_id = -1, mem_channel = -1, main_core = -1, mem_size = 4096, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, num_pci_addr = 0, hugedir = 0x0, pci_blocked = 0x0, pci_allowed = 0x0, iova_mode = 0x0, base_virtaddr = 35184372088832, env_context = 0x0}
        done = false
        rc = 0
        ts = {tv_sec = 4263743, tv_nsec = 380210450}
        td = <error reading variable td (value of type `thread_data' requires 281376 bytes, which is more than max-value-size)>
        __func__ = "spdk_init_thread_poll"
#9  0x00007f9ad3762a87 in start_thread () from /usr/lib64/libc.so.6
No symbol table info available.
#10 0x00007f9ad37e7640 in clone3 () from /usr/lib64/libc.so.6
No symbol table info available.
```

Core dump info [fio_xnvme_coredump.zip](https://github.com/spdk/spdk/files/9600503/fio_xnvme_coredump.zip)

**Comment by tomzawadzki** [comment]
Hi @krish-reddy, would you be able to take a look at this issue ?

**Comment by krish-reddy** [comment]
Sure, will look into this @tomzawadzki

**Comment by krish-reddy** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/14680

This patch fixes the issue.
