### ISSUE TITLE
[ llvm nvmf fuzz ] Core dump when using a non-exist port when fuzzing

### ISSUE THREAD

**Issue by junwenx** [spdk/spdk#2744]
# Sighting report

System core dump

## Expected Behavior

Just give a message, not core dump

## Steps to Reproduce

1. `CC=clang-12 CXX=clang++-12 ./configure --with-fuzzer=/usr/lib64/clang/12/lib/linux/libclang_rt.fuzzer_no_main-x86_64.a`
2. `make -j`
3. Using 4420 port to launch target
4. Using 4421 port to fuzz, `mkdir -p /tmp/llvm_fuzz1/`  `./test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F "trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4421" -c test/fuzz/llvm/nvmf/fuzz_json.conf -D /tmp/llvm_fuzz1/ -Z 1 -t 10`
5. error raised:
[2022-10-17 14:29:34.094278] tcp.c: 613:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2022-10-17 14:29:34.110659] tcp.c: 817:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.2 port 4421 ***
[2022-10-17 14:29:34.122416] rpc.c: 159:spdk_rpc_listen: *ERROR*: RPC Unix domain socket path /var/tmp/spdk.sock in use. Specify another.
[2022-10-17 14:29:34.122448] rpc.c:  42:spdk_rpc_initialize: *ERROR*: Unable to start RPC service at /var/tmp/spdk.sock
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3888765277
INFO: Loaded 1 modules   (32481 inline 8-bit counters): 32481 [0x888fc3, 0x890ea4),
INFO: Loaded 1 PC tables (32481 PCs): 32481 [0x890ea8,0x90fcb8),
INFO:        0 files found in /tmp/llvm_fuzz1/
[2022-10-17 14:29:34.152711] posix.c: 922:posix_sock_create: *ERROR*: connect() failed, errno = 111
[2022-10-17 14:29:34.152761] posix.c: 922:posix_sock_create: *ERROR*: connect() failed, errno = 111
[2022-10-17 14:29:34.152773] nvme_tcp.c:1940:nvme_tcp_qpair_connect_sock: *ERROR*: sock connection error of tqpair=0x7f4868003570 with addr=127.0.0.1, port=4421
[2022-10-17 14:29:34.152785] nvme_tcp.c:2150:nvme_tcp_ctrlr_construct: *ERROR*: failed to create admin qpair
[2022-10-17 14:29:34.152792] nvme.c: 677:nvme_ctrlr_probe: *ERROR*: Failed to construct NVMe controller for SSD: 127.0.0.1
[2022-10-17 14:29:34.152798] nvme.c: 815:nvme_probe_internal: *ERROR*: NVMe ctrlr scan failed
[2022-10-17 14:29:34.152804] nvme.c: 994:spdk_nvme_connect: *ERROR*: Create probe context failed
spdk_nvme_connect() failed for transport address '127.0.0.1'
[2022-10-17 14:29:34.152811] app.c: 676:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==1061681==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x00000000026c (pc 0x000000547168 bp 0x7f487047f1b0 sp 0x7f487047f100 T1061684)
==1061681==The signal is caused by a READ memory access.
==1061681==Hint: address points to the zero page.
    #0 0x547168 in spdk_nvme_ctrlr_alloc_io_qpair /home/wenjun/spdk/lib/nvme/nvme_ctrlr.c:453:6
    #1 0x469b53 in TestOneInput /home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:789:15
    #2 0x6f7a39 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6f7a39)
    #3 0x6faa35 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/wenjun/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x6 faa35)

## Context (Environment including OS version, SPDK version, etc.)
SPDK version: fd487dbd8bcc41f4ef108fec9c0349be88d1a498

**Comment by wanqunintel** [comment]
it seems we need to add "Error Handling" for this kind of scenario.

**Comment by changpe1** [comment]
@junwenx you can add a return in `llvm_nvme_fuzz.c` when getting the first error in line 786. Note that the fuzz test purpose is for fuzzing NVMe commands, not the use case described above. can you submit a patch to fix it?

**Comment by junwenx** [comment]
Add a patch https://review.spdk.io/gerrit/c/spdk/spdk/+/15160

> Note that the fuzz test purpose is for fuzzing NVMe commands, not the use case described above
Yes, know that. Thanks
