### ISSUE TITLE
Accel: run nvmf_tgt with --wait-for-rpc then RPC accel_get_opc_assignments casues core dumped

### ISSUE THREAD

**Issue by wanghailiangx** [spdk/spdk#2770]
# Sighting report
When I run nvmf_tgt with --wait-for-rpc, normal practice is: run RPC framework_start_init before RPC accel_get_opc_assignments.
Reports like this:
```
{
  "copy": "software",
  "fill": "software",
  "dualcast": "software",
  "compare": "software",
  "crc32c": "software",
  "copy_crc32c": "software",
  "compress": "software",
  "decompress": "software"
}
```
A wrong attempt: run RPC accel_get_opc_assignments without RPC framework_start_init. This cause core dumped.

## Expected Behavior
```
# ./scripts/rpc.py accel_get_opc_assignments
request:
{
  "method": "accel_get_opc_assignments",
  "req_id": 1
}
Got JSON-RPC error response
response:
{
  "code": -1,
  "message": "Method may only be called after framework is initialized using framework_start_init RPC."
}
```

## Current Behavior
```
# ./scripts/rpc.py accel_get_opc_assignments
Connection closed with partial response:
```
Target reports:
```
accel_rpc.c:  40:rpc_accel_get_opc_assignments: *NOTICE*: FYI error (-2) getting module name.
json_write.c:457:9: runtime error: null pointer passed as argument 1, which is declared to never be null
Segmentation fault (core dumped)
```

```
(gdb) bt
#0  0x00007f9626d3c5e5 in __strlen_avx2 () from /lib64/libc.so.6
#1  0x00000000008d8853 in spdk_json_write_string (w=0x2f1d470, val=0x0) at json_write.c:457
#2  0x00000000008d9dcf in spdk_json_write_named_string (w=0x2f1d470, name=0xb6325c "copy", val=0x0) at json_write.c:732
#3  0x0000000000865735 in rpc_accel_get_opc_assignments (request=0x2f15400, params=0x0) at accel_rpc.c:42
#4  0x00000000008c4b87 in jsonrpc_handler (request=0x2f15400, method=0x2ef4d10, params=0x0) at rpc.c:101
#5  0x00000000008ca8a7 in jsonrpc_server_handle_request (request=0x2f15400, method=0x2ef4d10, params=0x0) at jsonrpc_server_tcp.c:216
#6  0x00000000008c5ff4 in parse_single_request (request=0x2f15400, values=0x2ef4cd0) at jsonrpc_server.c:75
#7  0x00000000008c717f in jsonrpc_parse_request (conn=0x7f9624fcf040, json=0x7f9624fcf058, size=74) at jsonrpc_server.c:205
#8  0x00000000008caea9 in jsonrpc_server_conn_recv (conn=0x7f9624fcf040) at jsonrpc_server_tcp.c:278
#9  0x00000000008cbeec in spdk_jsonrpc_server_poll (server=0x7f9624fcf010) at jsonrpc_server_tcp.c:396
#10 0x00000000008c4eb7 in spdk_rpc_accept () at rpc.c:190
#11 0x00000000008841a7 in rpc_subsystem_poll (arg=0x0) at rpc.c:21
#12 0x00000000008ab260 in thread_execute_timed_poller (thread=0x2f14ed0, poller=0x2f15260, now=22115941523196000) at thread.c:854
#13 0x00000000008abc64 in thread_poll (thread=0x2f14ed0, max_msgs=0, now=22115941523196000) at thread.c:942
#14 0x00000000008abd55 in spdk_thread_poll (thread=0x2f14ed0, max_msgs=0, now=22115941523196000) at thread.c:968
#15 0x00000000007f2aa0 in _reactor_run (reactor=0x2f14900) at reactor.c:903
#16 0x00000000007f2f8c in reactor_run (arg=0x2f14900) at reactor.c:941
#17 0x00000000007f369f in spdk_reactors_start () at reactor.c:1043
#18 0x00000000007eb52e in spdk_app_start (opts_user=0x7ffe347353b0, start_fn=0x407d3f <nvmf_tgt_started>, arg1=0x0) at app.c:737
#19 0x0000000000407e83 in main (argc=2, argv=0x7ffe34735568) at nvmf_main.c:47
```

## Possible Solution
Register accel_get_opc_assignments only with SPDK_RPC_RUNTIME.

## Steps to Reproduce
1. ./build/bin/nvmf_tgt --wait-for-rpc
2. ./scripts/rpc.py accel_get_opc_assignments

## Context (Environment including OS version, SPDK version, etc.)
SPDK commit  30cbc5a0d2e6adeb8e2497f226b79549d78e0b1c

**Comment by wanghailiangx** [comment]
A patch for review: https://review.spdk.io/gerrit/c/spdk/spdk/+/15377

**Comment by wanghailiangx** [comment]
The above patch has been merged, now closing this issue.
