### ISSUE TITLE
[sma_nvmf_tcp] AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#2783]
```
00:29:33.419  ************************************
00:29:33.419  START TEST sma_nvmf_tcp
00:29:33.419  ************************************
00:29:33.419   11:03:04	-- common/autotest_common.sh@1058 -- # xtrace_enable
00:29:33.419   11:03:04	-- common/autotest_common.sh@1059 -- # /var/jenkins/workspace/vfio-user-autotest/spdk/test/sma/nvmf_tcp.sh
00:29:33.419  * Looking for test storage...
00:29:33.419  * Found test storage at /var/jenkins/workspace/vfio-user-autotest/spdk/test/sma
00:29:33.419    11:03:04	-- common/autotest_common.sh@1622 -- # xtrace_enable
00:29:33.419   11:03:04	-- sma/nvmf_tcp.sh@7 -- # source /var/jenkins/workspace/vfio-user-autotest/spdk/test/sma/common.sh
00:29:33.419   11:03:04	-- sma/nvmf_tcp.sh@67 -- # trap 'cleanup; exit 1' SIGINT SIGTERM EXIT
00:29:33.419   11:03:04	-- sma/nvmf_tcp.sh@70 -- # tgtpid=1073131
00:29:33.419   11:03:04	-- sma/nvmf_tcp.sh@69 -- # /var/jenkins/workspace/vfio-user-autotest/spdk/build/bin/spdk_tgt
00:29:33.419   11:03:04	-- sma/nvmf_tcp.sh@80 -- # smapid=1073133
00:29:33.419   11:03:04	-- sma/nvmf_tcp.sh@83 -- # sma_waitforlisten
00:29:33.419    11:03:04	-- sma/nvmf_tcp.sh@72 -- # cat
00:29:33.419   11:03:04	-- sma/common.sh@2 -- # local sma_addr=127.0.0.1
00:29:33.419   11:03:04	-- sma/nvmf_tcp.sh@72 -- # /var/jenkins/workspace/vfio-user-autotest/spdk/scripts/sma.py -c /dev/fd/63
00:29:33.419   11:03:04	-- sma/common.sh@3 -- # local sma_port=8080
00:29:33.419   11:03:04	-- sma/common.sh@5 -- # (( i = 0 ))
00:29:33.419   11:03:04	-- sma/common.sh@5 -- # (( i < 5 ))
00:29:33.419   11:03:04	-- sma/common.sh@6 -- # nc -z 127.0.0.1 8080
00:29:33.419   11:03:04	-- sma/common.sh@9 -- # sleep 1s
00:29:33.419  [2022-11-16 11:03:04.610845] Starting SPDK v23.01-pre git sha1 21909356e / DPDK 22.07.0 initialization...
00:29:33.419  [2022-11-16 11:03:04.610906] [ DPDK EAL parameters: [2022-11-16 11:03:04.610928] spdk_tgt [2022-11-16 11:03:04.610940] --no-shconf [2022-11-16 11:03:04.610953] -c 0x1 [2022-11-16 11:03:04.610963] --huge-unlink [2022-11-16 11:03:04.610985] --log-level=lib.eal:6 [2022-11-16 11:03:04.610997] --log-level=lib.cryptodev:5 [2022-11-16 11:03:04.611013] --log-level=user1:6 [2022-11-16 11:03:04.611023] --base-virtaddr=0x200000000000 [2022-11-16 11:03:04.611037] --match-allocations [2022-11-16 11:03:04.611048] --file-prefix=spdk_pid1073131 [2022-11-16 11:03:04.611067] ]
00:29:33.419  EAL: No free 2048 kB hugepages reported on node 1
00:29:33.419  TELEMETRY: No legacy callbacks, legacy socket not created
00:29:33.678  [2022-11-16 11:03:04.699104] app.c: 705:spdk_app_start: *NOTICE*: Total cores available: 1
00:29:33.678  Traceback (most recent call last):
00:29:33.678    File "/var/jenkins/workspace/vfio-user-autotest/spdk/scripts/sma.py", line 19, in <module>
00:29:33.678      import spdk.sma as sma               # noqa
00:29:33.678    File "/var/jenkins/workspace/vfio-user-autotest/spdk/python/spdk/sma/__init__.py", line 7, in <module>
00:29:33.678      from .sma import StorageManagementAgent      # noqa
00:29:33.678    File "/var/jenkins/workspace/vfio-user-autotest/spdk/python/spdk/sma/sma.py", line 6, in <module>
00:29:33.678      from .device import DeviceException
00:29:33.678    File "/var/jenkins/workspace/vfio-user-autotest/spdk/python/spdk/sma/device/__init__.py", line 3, in <module>
00:29:33.678      from .nvmf_tcp import NvmfTcpDeviceManager
00:29:33.678    File "/var/jenkins/workspace/vfio-user-autotest/spdk/python/spdk/sma/device/nvmf_tcp.py", line 10, in <module>
00:29:33.678      from ..proto import nvmf_tcp_pb2
00:29:33.678    File "/var/jenkins/workspace/vfio-user-autotest/spdk/python/spdk/sma/proto/nvmf_tcp_pb2.py", line 18, in <module>
00:29:33.678      _builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
00:29:33.678    File "/usr/local/lib64/python3.10/site-packages/google/protobuf/internal/builder.py", line 64, in BuildMessageAndEnumDescriptors
00:29:33.679      for (name, msg_des) in file_des.message_types_by_name.items():
00:29:33.679  AttributeError: 'NoneType' object has no attribute 'message_types_by_name'
00:29:33.679  [2022-11-16 11:03:04.777429] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 0
00:29:33.679  [2022-11-16 11:03:04.777551] accel_sw.c: 466:sw_accel_module_init: *NOTICE*: Accel framework software module initialized.
00:29:33.679  [2022-11-16 11:03:04.831737] vbdev_crypto.c: 435:vbdev_crypto_init_crypto_drivers: *NOTICE*: Found crypto devices: 1
00:29:34.616   11:03:05	-- sma/common.sh@5 -- # (( i++ ))
00:29:34.616   11:03:05	-- sma/common.sh@5 -- # (( i < 5 ))
00:29:34.616   11:03:05	-- sma/common.sh@6 -- # nc -z 127.0.0.1 8080
00:29:34.616   11:03:05	-- sma/common.sh@9 -- # sleep 1s
00:29:35.554   11:03:06	-- sma/common.sh@5 -- # (( i++ ))
00:29:35.554   11:03:06	-- sma/common.sh@5 -- # (( i < 5 ))
00:29:35.554   11:03:06	-- sma/common.sh@6 -- # nc -z 127.0.0.1 8080
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_89666.html

**Comment by ksztyber** [comment]
This looks like an issue with the versions of grpcio / protobuf. The grpcio autogenerated code doesn't work with the installed protobuf package.

But it only happened, because, for some reason, the test was run on Fedora 36:

> 00:21:31.225  Linux spdk-WFP-09 5.19.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 16 22:50:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

which shouldn't be deployed on the CI yet. The test system must have been booted to f36 by mistake.

**Comment by mikeBashStuff** [comment]
> which shouldn't be deployed on the CI yet. The test system must have been booted to f36 by mistake.
Similar case to #2782. WFP9 is running now under fedora35.

**Comment by ksztyber** [comment]
Since this has only happened once over a week ago and @mikeBashStuff is saying the system has been since rebooted to f35, I think we can close this.
