### ISSUE TITLE
blobstore: used_md_pages and used_clusters modified unsafely

### ISSUE THREAD

**Issue by mgerdts** [spdk/spdk#2831]
# Sighting report

I've had a report of:

```
bs_claim_md_page: Assertion `spdk_bit_array_get(bs->used_md_pages, page) == false' failed.
```

This happens with development external snapshot bits with a workload that creates, deletes, and performs IO on esnap clones.  I believe that this is a generic problem with cluster allocation that happens in the write path.  I can observe behavior that I think is related to this problem with spdk master at commit e189949f38e3dacbe5c4ccf496ed99e05fdad696 with fio.

## Expected Behavior

spdk does not crash with the assertion mentioned above.

## Current Behavior

This is a backtrace from external snapshot development bits:

```
[Current thread is 1 (Thread 0x7f54d2fe5700 (LWP 19))]
(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f54d6014859 in __GI_abort () at abort.c:79
#2  0x00007f54d6014729 in __assert_fail_base (fmt=0x7f54d61aa588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x5569f801f420 "spdk_bit_array_get(bs->used_md_pages, page) == false",
    file=0x5569f801f374 "blobstore.c", line=101, function=<optimized out>) at assert.c:92
#3  0x00007f54d6025fd6 in __GI___assert_fail (
    assertion=0x5569f801f420 "spdk_bit_array_get(bs->used_md_pages, page) == false",
    file=0x5569f801f374 "blobstore.c", line=101,
    function=0x5569f8021850 <__PRETTY_FUNCTION__.13547> "bs_claim_md_page") at assert.c:101
#4  0x00005569f7cb6fdc in bs_claim_md_page (bs=0x5569f99f1f30, page=4230) at blobstore.c:101
#5  0x00005569f7cb73d0 in bs_allocate_cluster (blob=0x5569faff90c0, cluster_num=242176, cluster=0x7f54b0235f28,
    lowest_free_md_page=0x7f54b0235f30, update_map=false) at blobstore.c:186
#6  0x00005569f7cbcf0f in bs_allocate_and_copy_cluster (blob=0x5569faff90c0, _ch=0x7f54b0220960,
    io_unit=247989008, op=0x7f54b02348f0) at blobstore.c:2551
#7  0x00005569f7cbe359 in blob_request_submit_rw_iov (blob=0x5569faff90c0, _channel=0x7f54b0220960,
    iov=0x7f54b0190b60, iovcnt=1, offset=247989008, length=1, cb_fn=0x5569f7c918b5 <lvol_op_comp>,
    cb_arg=0x200008e6e980, read=false, ext_io_opts=0x0) at blobstore.c:3115
#8  0x00005569f7cca413 in spdk_blob_io_writev_ext (blob=0x5569faff90c0, channel=0x7f54b0220960,
    iov=0x7f54b0190b60, iovcnt=1, offset=247989008, length=1, cb_fn=0x5569f7c918b5 <lvol_op_comp>,
    cb_arg=0x200008e6e980, io_opts=0x0) at blobstore.c:7918
#9  0x00005569f7cce0af in bs_user_op_execute (op=0x7f54b0224450) at request.c:513
#10 0x00005569f7cbca18 in blob_allocate_and_copy_cluster_cpl (cb_arg=0x7f54b0235fa0, bserrno=0)
    at blobstore.c:2423
#11 0x00005569f7ccca8e in bs_call_cpl (cpl=0x7f54d2fe3850, bserrno=0) at request.c:31
#12 0x00005569f7cccbc3 in bs_request_set_complete (set=0x7f54b0231010) at request.c:63
#13 0x00005569f7ccd5bf in bs_sequence_finish (seq=0x7f54b0231010, bserrno=0) at request.c:270
#14 0x00005569f7cbcb0a in blob_insert_cluster_cpl (cb_arg=0x7f54b0235fa0, bserrno=0) at blobstore.c:2453
#15 0x00005569f7cc98eb in blob_insert_cluster_msg_cpl (arg=0x7f54b0235f50) at blobstore.c:7636
#16 0x00005569f7dfd20a in msg_queue_run_batch (thread=0x5569f99cefa0, max_msgs=8) at thread.c:692
#17 0x00005569f7dfda21 in thread_poll (thread=0x5569f99cefa0, max_msgs=0, now=58538832195340) at thread.c:908
#18 0x00005569f7dfdbb2 in spdk_thread_poll (thread=0x5569f99cefa0, max_msgs=0, now=58538832195340)
    at thread.c:968
#19 0x00005569f7dc6177 in _reactor_run (reactor=0x5569f99c60c0) at reactor.c:901
#20 0x00005569f7dc6269 in reactor_run (arg=0x5569f99c60c0) at reactor.c:939
#21 0x00005569f7e76a07 in eal_thread_loop (arg=0x0) at ../lib/eal/linux/eal_thread.c:140
#22 0x00007f54d61ec609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#23 0x00007f54d6111133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

That is not `bs->md_thread`.

```
(gdb) print tls_thread
$1 = (struct spdk_thread *) 0x5569f99cefa0
(gdb) frame 4
#4  0x00005569f7cb6fdc in bs_claim_md_page (bs=0x5569f99f1f30, page=4230) at blobstore.c:101
101             assert(spdk_bit_array_get(bs->used_md_pages, page) == false);
(gdb) print bs->md_thread
$2 = (struct spdk_thread *) 0x5569f99caa60
(gdb) print bs->md_thread == tls_thread
$3 = 0
```

I believe that this tells me that this thread holds the mutex that should be protecting this data.

```
gdb) print bs->used_clusters_mutex
$4 = {__data = {__lock = 1, __count = 0, __owner = 19, __nusers = 1, __kind = 0, __spins = 0, __elision = 0,
    __list = {__prev = 0x0, __next = 0x0}},
  __size = "\001\000\000\000\000\000\000\000\023\000\000\000\001", '\000' <repeats 26 times>, __align = 1}
(gdb) info thread
  Id   Target Id                      Frame
* 1    Thread 0x7f54d2fe5700 (LWP 19) 0x00005569f7cb6fdc in bs_claim_md_page (bs=0x5569f99f1f30, page=4230)
    at blobstore.c:101
```

Thus, I think this thread was the victim of another thread claiming a md page without holding the lock.  By converting `bs->used_clusters_mutex` to a `spdk_spinlock` and adding `assert(spdk_spin_held(&bs->used_clusters_lock))` to `bs_claim_md_page()` I can find lots of callers that do not take the lock.

## Possible Solution

Two options:

1. Convert the mutex to a spinlock and use assertions as described above to track down all the callers that don't take a lock.
2. Bounce anything that needs to allocate clusters or md pages to `bs->md_thread`. Add assertions to ensure all access to the related bit fields is on the md thread.

## Steps to Reproduce

This does not reliably reproduce the bug, but can be used to trigger these debug asserts.  These require [a mutex to spinlock conversion](https://review.spdk.io/gerrit/c/spdk/spdk/+/15952).

```diff
diff --git a/lib/blob/blobstore.c b/lib/blob/blobstore.c
index 5cc32bc36..59b616659 100644
--- a/lib/blob/blobstore.c
+++ b/lib/blob/blobstore.c
@@ -75,6 +75,7 @@ bs_claim_md_page(struct spdk_blob_store *bs, uint32_t page)
 {
        assert(page < spdk_bit_array_capacity(bs->used_md_pages));
        assert(spdk_bit_array_get(bs->used_md_pages, page) == false);
+       assert(spdk_spin_held(&bs->used_clusters_lock));

        spdk_bit_array_set(bs->used_md_pages, page);
 }
@@ -84,6 +85,7 @@ bs_release_md_page(struct spdk_blob_store *bs, uint32_t page)
 {
        assert(page < spdk_bit_array_capacity(bs->used_md_pages));
        assert(spdk_bit_array_get(bs->used_md_pages, page) == true);
+       assert(spdk_spin_held(&bs->used_clusters_lock));

        spdk_bit_array_clear(bs->used_md_pages, page);
 }
@@ -93,6 +95,8 @@ bs_claim_cluster(struct spdk_blob_store *bs)
 {
        uint32_t cluster_num;

+       assert(spdk_spin_held(&bs->used_clusters_lock));
+
        cluster_num = spdk_bit_pool_allocate_bit(bs->used_clusters);
        if (cluster_num == UINT32_MAX) {
                return UINT32_MAX;
@@ -138,6 +142,8 @@ bs_allocate_cluster(struct spdk_blob *blob, uint32_t cluster_num,
 {
        uint32_t *extent_page = 0;

+       assert(spdk_spin_held(&blob->bs->used_clusters_lock));
+
        *cluster = bs_claim_cluster(blob->bs);
        if (*cluster == UINT32_MAX) {
                /* No more free clusters. Cannot satisfy the request */
```

Using [race.fio](https://github.com/spdk/spdk/files/10239188/race.fio.txt) and [race.json](https://github.com/spdk/spdk/files/10239189/race.json.txt):

```
top=`pwd`
./configure --with-rdma --without-rbd --enable-debug --enable-werror --with-fio=$top/../fio && make -j `nproc`
sudo env  LD_LIBRARY_PATH=$top/build/lib:$top/dpdk/build/lib:$top/build/libvfio-user/usr/local/lib \
     LD_PRELOAD="$top/build/fio/spdk_bdev' \
    ../fio/fio --ioengine=spdk_bdev --iodepth=64  race.fio --spdk_json_conf=race.json --spdk_mem=0 
```

## Context (Environment including OS version, SPDK version, etc.)

Observed on Rocky 8.7 and Ubuntu 20.04 using bits branched from master at commit 156b48b2988466bba122e27b431a2002cb087322 and still reproducible with master at commit e189949f38e3dacbe5c4ccf496ed99e05fdad696.

**Comment by mgerdts** [comment]
See https://review.spdk.io/gerrit/c/spdk/spdk/+/15953

**Comment by wanghailiangx** [comment]
Thanks Mike, the above patch has been merged, is it possible to close this issue?
