### ISSUE TITLE
[BlobFS-autotest] java.lang.InterruptedException

### ISSUE THREAD

**Issue by KKaras169169** [spdk/spdk#2850]
## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/93935/archive/BlobFS-autotest/build.log

## Execution failed at

```
00:05:14.663  java.lang.InterruptedException
00:05:14.663  	at java.base/java.lang.Object.wait(Native Method)
00:05:14.663  	at hudson.remoting.Request.call(Request.java:177)
00:05:14.663  	at hudson.remoting.Channel.call(Channel.java:999)
00:05:14.663  	at hudson.FilePath.act(FilePath.java:1186)
00:05:14.663  	at hudson.FilePath.act(FilePath.java:1175)
00:05:14.663  	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.getAgentInfo(FileMonitoringTask.java:202)
00:05:14.663  	at org.jenkinsci.plugins.durabletask.BourneShellScript.launchWithCookie(BourneShellScript.java:126)
00:05:14.663  	at org.jenkinsci.plugins.durabletask.FileMonitoringTask.launch(FileMonitoringTask.java:132)
00:05:14.663  	at org.jenkinsci.plugins.workflow.steps.durable_task.DurableTaskStep$Execution.start(DurableTaskStep.java:326)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:322)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
00:05:14.663  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
00:05:14.663  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
00:05:14.663  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
00:05:14.663  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
00:05:14.663  	at lib.sh_with_output(lib.groovy:380)
00:05:14.663  	at lib.add_node_info(lib.groovy:474)
00:05:14.663  	at lib.add_node_info(lib.groovy)
00:05:14.663  	at WorkflowScript.prologue(WorkflowScript:40)
00:05:14.663  	at WorkflowScript.run(WorkflowScript:124)
00:05:14.663  	at ___cps.transform___(Native Method)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
00:05:14.663  	at jdk.internal.reflect.GeneratedMethodAccessor257.invoke(Unknown Source)
00:05:14.663  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:05:14.663  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
00:05:14.663  	at jdk.internal.reflect.GeneratedMethodAccessor271.invoke(Unknown Source)
00:05:14.663  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:05:14.663  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
00:05:14.663  	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
00:05:14.663  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
00:05:14.663  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
00:05:14.663  	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
00:05:14.663  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
00:05:14.663  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
00:05:14.663  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:187)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:420)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:95)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
00:05:14.663  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
00:05:14.663  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:05:14.663  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
00:05:14.663  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:30)
00:05:14.663  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:70)
00:05:14.663  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
00:05:14.663  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
00:05:14.663  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
00:05:14.663  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
00:05:14.663  	at java.base/java.lang.Thread.run(Thread.java:829)
00:05:14.680  [Pipeline] // catchError
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_93935.html

**Comment by ksztyber** [comment]
[Bug scrub] Hasn't occurred for over 2 months, closing.
