### ISSUE TITLE
jenkins crashed while selecting agent for the job

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#2867]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-per-patch/builds/95060/archive/nvmf-phy-autotest/build.log

```
00:00:07.047  [Pipeline] Start of Pipeline
00:00:07.066  [Pipeline] node
00:00:22.067  Still waiting to schedule task
00:00:22.068  â€˜GP10â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜GP17â€™ is offline
00:00:22.068  â€˜GP18â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜GP19â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜GP20â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜GP21â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜GP22â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜GP5â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜ImageBuilder1â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜ImageBuilder2â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜Jenkinsâ€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜ME1â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜ME2â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜ME3â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM11â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM1â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM2â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM3â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM5â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM6â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM7â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜SM8â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-PE1â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-PE2â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-PE3â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-PE4â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-SM16â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-SM17â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-SM18â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-SM4â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜VM-host-WFP1â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜WCP0â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.068  â€˜WCP3â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜WCP4â€™ is offline
00:00:22.069  â€˜WFP10â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜WFP11â€™ is offline
00:00:22.069  â€˜WFP13â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜WFP14â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜WFP18â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜WFP22â€™ is offline
00:00:22.069  â€˜WFP5â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜WFP6â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜ipxe-stagingâ€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜ipxeâ€™ doesnâ€™t have label â€˜NetMLXâ€™
00:00:22.069  â€˜prc_bsc_waikikibeach64â€™ doesnâ€™t have label â€˜NetMLXâ€™
00:03:41.970  GP17 was marked offline: Connection was broken: java.io.EOFException
00:03:41.970  	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2911)
00:03:41.971  	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3406)
00:03:41.971  	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:932)
00:03:41.971  	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:375)
00:03:41.971  	at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:49)
00:03:41.971  	at hudson.remoting.Command.readFrom(Command.java:142)
00:03:41.971  	at hudson.remoting.Command.readFrom(Command.java:128)
00:03:41.971  	at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:35)
00:03:41.971  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:61)
00:03:41.971  Caused: java.io.IOException: Unexpected termination of the channel
00:03:41.971  	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:75)
00:03:41.971  
00:03:41.979  [Pipeline] // node
00:03:42.004  [Pipeline] End of Pipeline
# ... more traces follow
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_95060.html

**Comment by Comphix** [comment]
Please Karol take a look. Thanks.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_95665.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_95681.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mgerdts. log: https://ci.spdk.io/public_build/autotest-per-patch_97546.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KKaras169169. log: https://ci.spdk.io/public_build/autotest-per-patch_98019.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_98790.html

**Comment by xjjx** [comment]
This is most probably internal network issue, thus why it says "Unexpected termination of the channel". What we can do in this case is retrigger this subjob, I'll prepare patch for this case.

The last reported case is a different one - it's a case when machine wasn't restarted after previous aborted test, and for unknown reason jenkins didn't execute last steps (or actually it try execute the "compress" script but killed it immediately).
