### ISSUE TITLE
[nvmf-phy-autotest] Node was marked offline

### ISSUE THREAD

**Issue by tomzawadzki** [spdk/spdk#2882]
# CI Intermittent Failure

Before even starting autotest, when awaiting to schedule a job - it times out.

## Link to the failed CI build

https://ci.spdk.io/results/autotest-per-patch/builds/97004/archive/nvmf-phy-autotest/build.log

## Execution failed at

```
00:00:06.079  Commit message: "sorcerer: get ip"
00:00:06.079   > git rev-list --no-walk c425e63cf93aa0095229019b95d9ff7fd409fd14 # timeout=10
00:00:06.171  [Pipeline] Start of Pipeline
00:00:06.188  [Pipeline] node
00:00:20.838  GP16 was marked offline: Connection was broken: java.io.EOFException
00:00:20.838  	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2911)
00:00:20.838  	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3406)
```

**Comment by tomzawadzki** [comment]
Duplicate of https://github.com/spdk/spdk/issues/2867.
That one has bit more logs , like `Still waiting to schedule task`.
