### ISSUE TITLE
[vagrant] create_volume_xml: Call to virStorageVolCreateXML failed

### ISSUE THREAD

**Issue by ksztyber** [spdk/spdk#2894]
```
00:07:29.326  + DISTRO=ubuntu1804 CPUS=10 RAM=12288 jbp/jenkins/jjb-config/jobs/scripts/vagrant_create_vm.sh
00:07:29.326  Setup: -n 10 -s 12288 -x http://proxy-dmz.intel.com:911 -p libvirt --qemu-emulator=/usr/local/qemu/vanilla-v7.0.0/bin/qemu-system-x86_64 -b /var/lib/libvirt/images/backends/ex7-nvme.img -H -a -v ubuntu1804
00:07:29.326  
00:07:29.326  DIR=/var/jenkins/workspace/ubuntu18-vg-autotest/spdk/scripts/vagrant
00:07:29.326  SPDK_DIR=/var/jenkins/workspace/ubuntu18-vg-autotest/spdk
00:07:29.326  VAGRANT_TARGET=/var/jenkins/workspace/ubuntu18-vg-autotest
00:07:29.326  HELP=0
00:07:29.326  DRY_RUN=0
00:07:29.326  NVME_FILE=/var/lib/libvirt/images/backends/ex7-nvme.img,
00:07:29.326  NVME_DISKS_TYPE=nvme,
00:07:29.326  NVME_AUTO_CREATE=0
00:07:29.326  NVME_DISKS_NAMESPACES=,
00:07:29.326  NVME_CMB=,
00:07:29.326  NVME_PMR=,
00:07:29.326  NVME_ZNS=,
00:07:29.326  NVME_MS=,
00:07:29.326  SPDK_VAGRANT_DISTRO=ubuntu1804
00:07:29.326  SPDK_VAGRANT_VMCPU=10
00:07:29.326  SPDK_VAGRANT_VMRAM=12288
00:07:29.326  SPDK_VAGRANT_PROVIDER=libvirt
00:07:29.326  SPDK_VAGRANT_HTTP_PROXY=http://proxy-dmz.intel.com:911
00:07:29.326  SPDK_QEMU_EMULATOR=/usr/local/qemu/vanilla-v7.0.0/bin/qemu-system-x86_64
00:07:29.326  SPDK_OPENSTACK_NETWORK=0
00:07:29.326  VAGRANT_PACKAGE_BOX=0
00:07:29.326  VAGRANTFILE=/var/jenkins/workspace/ubuntu18-vg-autotest/spdk/scripts/vagrant/Vagrantfile
00:07:29.326  FORCE_DISTRO=false
00:07:29.326  VAGRANT_BOX_VERSION=
00:07:29.326  EXTRA_VAGRANTFILES=
00:07:29.326  
00:07:29.326  mkdir: created directory '/var/jenkins/workspace/ubuntu18-vg-autotest/ubuntu1804-libvirt'
00:07:29.326  /var/jenkins/workspace/ubuntu18-vg-autotest/ubuntu1804-libvirt /var/jenkins/workspace/ubuntu18-vg-autotest
00:07:32.677  Bringing machine 'default' up with 'libvirt' provider...
00:07:33.614  ==> default: Uploading base box image as volume into libvirt storage...
00:07:33.614  /usr/lib/ruby/vendor_ruby/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virStorageVolCreateXML failed: storage volume 'spdk-VAGRANTSLASH-ubuntu1804_vagrant_box_image_18.04-210809484.img' exists already (Libvirt::Error)
00:07:33.614  	from /usr/lib/ruby/vendor_ruby/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
00:07:33.615  	from /usr/lib/ruby/vendor_ruby/fog/libvirt/models/compute/volume.rb:42:in `save'
00:07:33.615  	from /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:50:in `create'
00:07:33.615  	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:107:in `block in call'
00:07:33.615  	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:65:in `synchronize'
00:07:33.615  	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/handle_box_image.rb:65:in `call'
```
## Link to the failed CI build
https://ci.spdk.io/results/autotest-per-patch/builds/97975/archive/ubuntu18-vg-autotest/build.log
https://ci.spdk.io/public_build/autotest-per-patch_97975.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_97975.html

**Comment by mikeBashStuff** [comment]
Fixed directly on the node, small patch needed on the jenkins side. Closing for now.
