### ISSUE TITLE
[short-fuzz-autotest] nvmf_fuzz failed due to memory leaks

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2967]
# Sighting report

In CI job `short-fuzz-autotest` test `nvmf_fuzz` fails due to memory leaks.
https://ci.spdk.io/public_build/autotest-per-patch_100976.html
https://ci.spdk.io/results/autotest-per-patch/builds/100976/archive/short-fuzz-autotest/index.html
https://ci.spdk.io/results/autotest-per-patch/builds/100976/archive/short-fuzz-autotest/build.log

## Current Behavior

libasan detects following. Not sure if 100% reproducible.
```
00:05:36.556  ************************************
00:05:36.556  START TEST nvmf_fuzz
00:05:36.556  ************************************
00:05:36.556   13:09:16	-- common/autotest_common.sh@941 -- # xtrace_enable
00:05:36.556   13:09:16	-- common/autotest_common.sh@942 -- # /var/jenkins/workspace/short-fuzz-autotest/spdk/test/fuzz/llvm/nvmf/run.sh
00:05:36.816  * Looking for test storage...
00:05:36.816  * Found test storage at /var/jenkins/workspace/short-fuzz-autotest/spdk/test/fuzz/llvm/nvmf
00:05:36.816    13:09:16	-- common/autotest_common.sh@1504 -- # xtrace_enable
00:05:36.816   13:09:16	-- nvmf/run.sh@53 -- # fuzzfile=/var/jenkins/workspace/short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c
00:05:36.816    13:09:16	-- nvmf/run.sh@54 -- # grep -c 'fn =' /var/jenkins/workspace/short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c
00:05:36.816   13:09:16	-- nvmf/run.sh@54 -- # fuzz_num=25
00:05:36.816   13:09:16	-- nvmf/run.sh@55 -- # [[ 25 -ne 0 ]]
00:05:36.816   13:09:16	-- nvmf/run.sh@57 -- # trap 'process_shm --id 0; rm -rf /tmp/llvm_fuzz*; exit 1' SIGINT SIGTERM EXIT
00:05:36.816   13:09:16	-- nvmf/run.sh@59 -- # trid='trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420'
00:05:36.816   13:09:16	-- nvmf/run.sh@61 -- # [[ 1 -eq 1 ]]
00:05:36.816   13:09:16	-- nvmf/run.sh@62 -- # (( i = 0 ))
00:05:36.816   13:09:16	-- nvmf/run.sh@62 -- # (( i < fuzz_num ))
00:05:36.816   13:09:16	-- nvmf/run.sh@63 -- # start_llvm_fuzz 0
00:05:36.816   13:09:16	-- nvmf/run.sh@21 -- # local fuzzer_type=0
00:05:36.816   13:09:16	-- nvmf/run.sh@22 -- # local corpus_dir
00:05:36.816   13:09:16	-- nvmf/run.sh@23 -- # corpus_dir=/tmp/llvm_fuzz0
00:05:36.816   13:09:16	-- nvmf/run.sh@24 -- # mkdir -p /tmp/llvm_fuzz0
00:05:36.816   13:09:16	-- nvmf/run.sh@25 -- # /var/jenkins/workspace/short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz -m 0x1 -i 0 -F 'trtype:tcp adrfam:IPv4 subnqn:nqn.2016-06.io.spdk:cnode1 traddr:127.0.0.1 trsvcid:4420' -c /var/jenkins/workspace/short-fuzz-autotest/spdk/test/fuzz/llvm/nvmf/fuzz_json.conf -t 1 -D /tmp/llvm_fuzz0 -Z 0
00:05:36.816  [2023-03-29 13:09:16.417688] Starting SPDK v23.05-pre git sha1 4280a2e75 / DPDK 22.11.1 initialization...
00:05:36.816  [2023-03-29 13:09:16.417807] [ DPDK EAL parameters: nvme_fuzz -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk0 --proc-type=auto ]
00:05:36.816  EAL: No free 2048 kB hugepages reported on node 1
00:05:36.816  TELEMETRY: No legacy callbacks, legacy socket not created
00:05:36.816  [2023-03-29 13:09:16.552043] app.c: 730:spdk_app_start: *NOTICE*: Total cores available: 1
00:05:37.076  [2023-03-29 13:09:16.625794] reactor.c: 926:reactor_run: *NOTICE*: Reactor started on core 0
00:05:37.076  [2023-03-29 13:09:16.673882] accel_sw.c: 601:sw_accel_module_init: *NOTICE*: Accel framework software module initialized.
00:05:37.076  [2023-03-29 13:09:16.789609] 'OCF Core' volume operations registered
00:05:37.076  [2023-03-29 13:09:16.792763] 'SPDK_block_device' volume operations registered
00:05:37.076  [2023-03-29 13:09:16.830182] tcp.c: 629:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
00:05:37.335  [2023-03-29 13:09:16.846370] tcp.c: 854:nvmf_tcp_listen: *NOTICE*: *** NVMe/TCP Target Listening on 127.0.0.1 port 4420 ***
00:05:37.335  INFO: Running with entropic power schedule (0xFF, 100).
00:05:37.335  INFO: Seed: 4138198467
00:05:37.335  INFO: Loaded 1 modules   (398225 inline 8-bit counters): 398225 [0x4231dcc, 0x429315d), 
00:05:37.335  INFO: Loaded 1 PC tables (398225 PCs): 398225 [0x4293160,0x48a6a70), 
00:05:37.335  INFO:        0 files found in /tmp/llvm_fuzz0
00:05:37.335  INFO: A corpus is not provided, starting from an empty corpus
00:05:37.335  #2	INITED cov: 11398 ft: 11399 corp: 1/1b exec/s: 0 rss: 148Mb
00:05:37.629  
00:05:37.629  =================================================================
00:05:37.629  ==4062125==ERROR: LeakSanitizer: detected memory leaks
00:05:37.629  
00:05:37.629  Direct leak of 256 byte(s) in 8 object(s) allocated from:
00:05:37.629      #0 0x53d5e7 in __interceptor_calloc (/var/jenkins/workspace/short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x53d5e7) (BuildId: abedeb83095b0070b79aa3b2726d2aaa68f0dc53)
00:05:37.629      #1 0x10557a5 in env_allocator_create_extended /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/ocf_env.c:65:14
00:05:37.629      #2 0x1058c68 in env_mpool_create /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/mpool.c:56:25
00:05:37.629      #3 0xf4cde0 in ocf_req_allocator_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/ocf_request.c:57:27
00:05:37.629      #4 0xf122e6 in ocf_ctx_create /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/ocf_ctx.c:173:8
00:05:37.629      #5 0xbf5602 in vbdev_ocf_ctx_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/bdev/ocf/ctx.c:445:8
00:05:37.629      #6 0xc426d4 in vbdev_ocf_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/bdev/ocf/vbdev_ocf.c:1271:11
00:05:37.629      #7 0x23075d8 in bdev_modules_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/bdev/bdev.c:1883:8
00:05:37.629      #8 0x2302673 in spdk_bdev_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/bdev/bdev.c:1953:7
00:05:37.629      #9 0x21f62f1 in bdev_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/bdev/bdev.c:24:2
00:05:37.629      #10 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.629      #11 0x21f6931 in accel_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/accel/accel.c:20:2
00:05:37.629      #12 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.629      #13 0x22aaba8 in sock_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/sock/sock.c:13:2
00:05:37.629      #14 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.629      #15 0x2252071 in scheduler_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/scheduler/scheduler.c:23:2
00:05:37.629      #16 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.629      #17 0x2250f19 in iobuf_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/iobuf/iobuf.c:57:2
00:05:37.629      #18 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.629      #19 0x21f70f3 in vmd_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/vmd/vmd.c:63:2
00:05:37.629      #20 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.629      #21 0x22b9b5c in spdk_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:194:2
00:05:37.629      #22 0x22b0260 in app_json_config_load_subsystem /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/json_config.c:471:4
00:05:37.629      #23 0x26153ce in msg_queue_run_batch /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:841:3
00:05:37.629      #24 0x25b1f2d in thread_poll /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:1063:14
00:05:37.629      #25 0x25b139c in spdk_thread_poll /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:1156:8
00:05:37.629      #26 0x228edca in _reactor_run /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/reactor.c:903:8
00:05:37.629      #27 0x227fbb3 in reactor_run /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/reactor.c:941:4
00:05:37.629      #28 0x227f32e in spdk_reactors_start /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/reactor.c:1053:2
00:05:37.629      #29 0x2257067 in spdk_app_start /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/app.c:771:2
00:05:37.629  
00:05:37.629  Direct leak of 224 byte(s) in 7 object(s) allocated from:
00:05:37.629      #0 0x53d5e7 in __interceptor_calloc (/var/jenkins/workspace/short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x53d5e7) (BuildId: abedeb83095b0070b79aa3b2726d2aaa68f0dc53)
00:05:37.629      #1 0x10557a5 in env_allocator_create_extended /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/ocf_env.c:65:14
00:05:37.629      #2 0x1058c68 in env_mpool_create /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/mpool.c:56:25
00:05:37.629      #3 0xdf2946 in ocf_metadata_io_ctx_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/metadata/metadata_io.c:535:27
00:05:37.629      #4 0xf12336 in ocf_ctx_create /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/ocf_ctx.c:177:8
00:05:37.629      #5 0xbf5602 in vbdev_ocf_ctx_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/bdev/ocf/ctx.c:445:8
00:05:37.629      #6 0xc426d4 in vbdev_ocf_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/bdev/ocf/vbdev_ocf.c:1271:11
00:05:37.629      #7 0x23075d8 in bdev_modules_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/bdev/bdev.c:1883:8
00:05:37.629      #8 0x2302673 in spdk_bdev_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/bdev/bdev.c:1953:7
00:05:37.629      #9 0x21f62f1 in bdev_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/bdev/bdev.c:24:2
00:05:37.629      #10 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.629      #11 0x21f6931 in accel_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/accel/accel.c:20:2
00:05:37.629      #12 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #13 0x22aaba8 in sock_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/sock/sock.c:13:2
00:05:37.630      #14 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #15 0x2252071 in scheduler_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/scheduler/scheduler.c:23:2
00:05:37.630      #16 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #17 0x2250f19 in iobuf_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/iobuf/iobuf.c:57:2
00:05:37.630      #18 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #19 0x21f70f3 in vmd_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/vmd/vmd.c:63:2
00:05:37.630      #20 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #21 0x22b9b5c in spdk_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:194:2
00:05:37.630      #22 0x22b0260 in app_json_config_load_subsystem /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/json_config.c:471:4
00:05:37.630      #23 0x26153ce in msg_queue_run_batch /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:841:3
00:05:37.630      #24 0x25b1f2d in thread_poll /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:1063:14
00:05:37.630      #25 0x25b139c in spdk_thread_poll /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:1156:8
00:05:37.630      #26 0x228edca in _reactor_run /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/reactor.c:903:8
00:05:37.630      #27 0x227fbb3 in reactor_run /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/reactor.c:941:4
00:05:37.630      #28 0x227f32e in spdk_reactors_start /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/reactor.c:1053:2
00:05:37.630      #29 0x2257067 in spdk_app_start /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/app.c:771:2
00:05:37.630  
00:05:37.630  Direct leak of 32 byte(s) in 1 object(s) allocated from:
00:05:37.630      #0 0x53d5e7 in __interceptor_calloc (/var/jenkins/workspace/short-fuzz-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x53d5e7) (BuildId: abedeb83095b0070b79aa3b2726d2aaa68f0dc53)
00:05:37.630      #1 0x10557a5 in env_allocator_create_extended /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/ocf_env.c:65:14
00:05:37.630      #2 0x10555b2 in env_allocator_create /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/ocf_env.c:53:9
00:05:37.630      #3 0xf1bc4a in ocf_io_allocator_default_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/ocf_io.c:37:20
00:05:37.630      #4 0xf91f9b in ocf_io_allocator_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/utils/utils_io_allocator.h:52:9
00:05:37.630      #5 0xf93756 in ocf_volume_type_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/ocf_volume.c:57:8
00:05:37.630      #6 0xf0ee98 in ocf_ctx_register_volume_type_extended /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/ocf_ctx.c:36:2
00:05:37.630      #7 0xf0f87a in ocf_ctx_register_volume_type /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/env_ocf/src/ocf/ocf_ctx.c:58:9
00:05:37.630      #8 0xc57230 in vbdev_ocf_volume_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/bdev/ocf/volume.c:411:9
00:05:37.630      #9 0xc4274e in vbdev_ocf_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/bdev/ocf/vbdev_ocf.c:1277:11
00:05:37.630      #10 0x23075d8 in bdev_modules_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/bdev/bdev.c:1883:8
00:05:37.630      #11 0x2302673 in spdk_bdev_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/bdev/bdev.c:1953:7
00:05:37.630      #12 0x21f62f1 in bdev_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/bdev/bdev.c:24:2
00:05:37.630      #13 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #14 0x21f6931 in accel_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/accel/accel.c:20:2
00:05:37.630      #15 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #16 0x22aaba8 in sock_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/sock/sock.c:13:2
00:05:37.630      #17 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #18 0x2252071 in scheduler_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/scheduler/scheduler.c:23:2
00:05:37.630      #19 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #20 0x2250f19 in iobuf_subsystem_initialize /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/iobuf/iobuf.c:57:2
00:05:37.630      #21 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #22 0x21f70f3 in vmd_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/module/event/subsystems/vmd/vmd.c:63:2
00:05:37.630      #23 0x22b9036 in spdk_subsystem_init_next /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:161:3
00:05:37.630      #24 0x22b9b5c in spdk_subsystem_init /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/subsystem.c:194:2
00:05:37.630      #25 0x22b0260 in app_json_config_load_subsystem /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/init/json_config.c:471:4
00:05:37.630      #26 0x26153ce in msg_queue_run_batch /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:841:3
00:05:37.630      #27 0x25b1f2d in thread_poll /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:1063:14
00:05:37.630      #28 0x25b139c in spdk_thread_poll /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/thread/thread.c:1156:8
00:05:37.630      #29 0x228edca in _reactor_run /var/jenkins/workspace/short-fuzz-autotest/spdk/lib/event/reactor.c:903:8
00:05:37.630  
00:05:37.630  SUMMARY: AddressSanitizer: 512 byte(s) leaked in 16 allocation(s).
00:05:37.630  INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
00:05:37.630  
```

## Steps to Reproduce

1. Prepare configuration file:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_FUZZER_SHORT=1
SPDK_TEST_FUZZER=1
SPDK_RUN_UBSAN=1
SPDK_RUN_ASAN=1
```
2. `./autorun.sh ~/autorun.conf`

## Context (Environment including OS version, SPDK version, etc.)

https://review.spdk.io/gerrit/c/spdk/spdk/+/17143/34 based on d69516f5e734734515f191b085e7403eac3d5aac from master branch

**Comment by sberbz** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/17682
