### ISSUE TITLE
[SPDK segfault during secondary process cleanup] Observing a segfault on V22 of SPDK during section process cleanup

### ISSUE THREAD

**Issue by tusmah** [spdk/spdk#2968]
# Sighting report

Hi,

We have an SPDK application which has a primary secondary setup. There is a single primary process and 4 secondary processes which do IO. We have to restart the processes periodically. Sometimes during restart, we see segfaults when the secondary process tries to clean up IO q-pairs that it was using. After this, the only way to recover is to restart the SPDK process group with the SPDK primary process and the secondary processes.

## Expected Behavior

No Segfaults on SPDK IO q-pair cleanup

## Current Behavior

Segfault while calling spdk_nvme_ctrlr_free_io_qpair(..) which calls nvme_transport_ctrlr_disconnect_qpair(..) which in turn calls nvme_transport_qpair_abort_reqs(..) where we segfault

## Possible Solution

-

## Steps to Reproduce

JNI C code executed during cleanup -

```
JNIEXPORT jint JNICALL Java_xxx_cleanup
(JNIEnv *env, jclass class)
{
// Wait for SPDK threads to exit
spdk_env_thread_wait_all();
// Free IO q-pairs
int rc;
for (int i = 0; i < num_queues; i++) {
if (NULL != read_queues[i].qpair) {
rc = spdk_nvme_ctrlr_free_io_qpair(read_queues[i].qpair);
if (rc != 0) {
    printf("Failed to free IO q/pair. %d", rc);
}
}
}
// spdk nvme detach
rc = spdk_nvme_detach(ctrlr);
if (rc != 0) {
    printf("Failed to detach NVME device. %d", rc);
}
// clean up any resources allocated through 'spdk_env_init'
spdk_env_fini();
return 0;
}
```

Segfault observed -

```
Current thread (0x00007fff7c003030):  JavaThread "Thread-1" [_thread_in_native, id=28963, stack(0x00007fff40ab8000,0x00007fff40bb9000)]

Stack: [0x00007fff40ab8000,0x00007fff40bb9000],  sp=0x00007fff40bb76a8,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libxxx-1.0.so+0xa270e]  nvme_transport_qpair_abort_reqs+0xe

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  xxx.cleanup()V+0
j  xxxcleanup()V+4
j  xxx.cleanup()V+155
j  xxx$initxxxReader$1()V+15
j  xxx$$Lambda$267+0x00000001002c6db8.run()V+4
j  java.lang.Thread.run()V+11 java.base@17.0.6
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x00007fff6af3bb10
```

Stack slot to memory mapping:

```
stack at sp + 0 slots: 0x00007fffbd4fb7a6: nvme_transport_ctrlr_disconnect_qpair+0x0000000000000066 in xxx-1.0.so at 0x00007fffbd459000
stack at sp + 1 slots: 0x0000600000bd7d20 points into unknown readable memory: 0x00006000005e23c0 | c0 23 5e 00 00 60 00 00
stack at sp + 2 slots: 0x00006000005e23c0 points into unknown readable memory: 0x00006000005c0f00 | 00 0f 5c 00 00 60 00 00
stack at sp + 3 slots: 0x000060000a3ffec0 points into unknown readable memory: 0x00002b9100000000 | 00 00 00 00 91 2b 00 00
stack at sp + 4 slots: 0x00007fffbd4e77b0: spdk_nvme_ctrlr_free_io_qpair+0x0000000000000040 in xxx1.0.so at 0x00007fffbd459000
stack at sp + 5 slots: 0x0000600000bd7ec0 points into unknown readable memory: 0x00002bab00000000 | 00 00 00 00 ab 2b 00 00
stack at sp + 6 slots: 0x0000000000000001 is an unknown value
stack at sp + 7 slots: 0x000060000a3ffec0 points into unknown readable memory: 0x00002b9100000000 | 00 00 00 00 91 2b 00 00
```

## Context (Environment including OS version, SPDK version, etc.)

OS version -

`5.4.231-145.341.amzn2int.x86_64 #1 SMP Wed Feb 15 03:24:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

SPDK release - https://spdk.io/release/2022/05/12/22.01.1_release/

**Comment by jimharris** [comment]
The secondary process is freeing the qpairs before it exits?  Or the new secondary process is trying to free qpairs allocated by a previous secondary process?

Unfortunately it looks like there's too much happening in your code outside of what was shared here, including your Java bindings.  Can you narrow down exactly what in nvme_transport_qpair_abort_reqs is causing the segfault?

**Comment by tusmah** [comment]
In this case the secondary process is trying to free the qpair before it exits. Thats what throws and after that none of the secondary processes are able to start up.

Run gdb on the program with debug symbols gives this -

```
[2023-03-31 04:39:36.595629] nvme_ctrlr.c:3462:nvme_ctrlr_remove_inactive_proc: *ERROR*: [0000:00:1d.0] process 21984 terminated unexpected
free(): invalid pointer
```

Not sure if this helps.

**Comment by tusmah** [comment]
Seems like its segfaulting here -

```
int
nvme_pcie_qpair_destroy(struct spdk_nvme_qpair *qpair)
{
	struct nvme_pcie_qpair *pqpair = nvme_pcie_qpair(qpair);

	if (nvme_qpair_is_admin_queue(qpair)) {
		nvme_pcie_admin_qpair_destroy(qpair);
	}
	/*
	 * We check sq_vaddr and cq_vaddr to see if the user specified the memory
	 * buffers when creating the I/O queue.
	 * If the user specified them, we cannot free that memory.
	 * Nor do we free it if it's in the CMB.
	 */
	if (!pqpair->sq_vaddr && pqpair->cmd && !pqpair->sq_in_cmb) {
		spdk_free(pqpair->cmd);
	}
	if (!pqpair->cq_vaddr && pqpair->cpl) {
		spdk_free(pqpair->cpl);
	}
	if (pqpair->tr) {
		spdk_free(pqpair->tr);
	}

	nvme_qpair_deinit(qpair);

	if (!pqpair->shared_stats) {
		if (qpair->id) {
			free(pqpair->stat); ---------> Segfault here?
		} else {
			/* statistics of admin qpair are allocates from huge pages because
			 * admin qpair is shared for multi-process */
			spdk_free(pqpair->stat);
		}

	}

	spdk_free(pqpair);

	return 0;
}
```

**Comment by jimharris** [comment]
> In this case the secondary process is trying to free the qpair before it exits. Run gdb on the program with debug symbols gives this -

Note there has been a fix to nvme_pcie_qpair_destroy() to avoid freeing pqpair->stat from a foreign process.  You're obviously hitting a side effect of that problem.

But there is still a lot of missing detail here.  There is one primary process and four secondary processes.  You say the secondary process is freeing the qpair before it exits, but the call stack here shows this process is trying to do an spdk_nvme_connect.  Why is it doing a connect while it is exiting?  Is this call stack from the primary process or one of the secondary processes?

My suggestion would be to look very closely at how each of your processes are both allocating and freeing IO qpairs.  It appears that one of your process is trying to allocate an IO qpair, but notices that some other process exited without free its IO qpairs, and then hits the call stack shown below.


> 
> ```
> [2023-03-31 04:39:36.595629] nvme_ctrlr.c:3462:nvme_ctrlr_remove_inactive_proc: *ERROR*: [0000:00:1d.0] process 21984 terminated unexpected
> free(): invalid pointer
> ```
> 
> Backtrace -
> 
> ```
> (gdb) backtrace
> #0  0x0000fffff7ab6530 in raise () from /lib64/libc.so.6
> #1  0x0000fffff7ab7d74 in abort () from /lib64/libc.so.6
> #2  0x0000fffff7af1920 in __libc_message () from /lib64/libc.so.6
> #3  0x0000fffff7af8084 in malloc_printerr () from /lib64/libc.so.6
> #4  0x0000fffff7af9b20 in _int_free () from /lib64/libc.so.6
> #5  0x0000fffff7f67f94 in nvme_pcie_qpair_destroy (qpair=qpair@entry=0x600007817de0) at nvme_pcie_common.c:1029
> #6  0x0000fffff7f68430 in nvme_pcie_ctrlr_delete_io_qpair (ctrlr=0x600000400380, qpair=0x600007817de0) at nvme_pcie_common.c:1166
> #7  0x0000fffff7f711c0 in nvme_transport_ctrlr_delete_io_qpair (ctrlr=ctrlr@entry=0x600000400380, qpair=qpair@entry=0x600007817de0) at nvme_transport.c:452
> #8  0x0000fffff7f5dd84 in spdk_nvme_ctrlr_free_io_qpair (qpair=0x600007817de0) at nvme_ctrlr.c:654
> #9  0x0000fffff7f5dfe0 in nvme_ctrlr_cleanup_process (proc=0x60000781d940) at nvme_ctrlr.c:3422
> #10 nvme_ctrlr_remove_inactive_proc (ctrlr=ctrlr@entry=0x600000400380) at nvme_ctrlr.c:3466
> #11 0x0000fffff7f5e058 in nvme_ctrlr_proc_get_ref (ctrlr=0x600000400380) at nvme_ctrlr.c:3482
> #12 0x0000fffff7f6fbac in nvme_probe_internal (probe_ctx=probe_ctx@entry=0xaaaaaabcf8b0, direct_connect=direct_connect@entry=true) at nvme.c:863
> #13 0x0000fffff7f7035c in spdk_nvme_connect_async (trid=trid@entry=0xffffffffce90, opts=0xffffffffcc20, attach_cb=attach_cb@entry=0x0) at nvme.c:1577
> #14 0x0000fffff7f705e8 in spdk_nvme_connect (trid=0xffffffffce90, opts=0xffffffffd0d0, opts_size=<optimized out>) at nvme.c:1018
> <redacted>
> ```
> 
> Not sure if this helps.

**Comment by tusmah** [comment]
Apologies. This one is slightly different. The previous issue was for secondary when it was trying to clean up. I am trying to get the segfault for that as well.

This one is one of the issues that we are seeing as well during startup of the secondary process. I will try to get the other segfault details tomorrow

**Comment by jimharris** [comment]
Closing due to inactivity.
