### ISSUE TITLE
[vfio_user_virtio_blk_restart_vm] AddressSanitizer: SEGV on unknown address 0x7ff7347df002

### ISSUE THREAD

**Issue by jchachux** [spdk/spdk#2975]
```
12:12:48  INFO: Waiting for VMs to boot
12:12:48  INFO: waiting for VM1 (/root/vhost_test/vms/1)
12:12:56  AddressSanitizer:DEADLYSIGNAL
12:12:56  =================================================================
12:12:56  ==118353==ERROR: AddressSanitizer: SEGV on unknown address 0x7f8ae11df002 (pc 0x7f8aec4bef02 bp 0x7ffcd27d2c50 sp 0x7ffcd27d2c10 T0)
12:12:56  ==118353==The signal is caused by a WRITE memory access.
12:12:56      #0 0x7f8aec4bef02 in virtio_dev_map_vq /var/jenkins/workspace/vfio-user-autotest/spdk/module/vfu_device/vfu_virtio.c:102
12:12:56      #1 0x7f8aec4c13b2 in virtio_dev_enable_vq /var/jenkins/workspace/vfio-user-autotest/spdk/module/vfu_device/vfu_virtio.c:276
12:12:56      #2 0x7f8aec4cf40f in virtio_vfu_pci_common_cfg /var/jenkins/workspace/vfio-user-autotest/spdk/module/vfu_device/vfu_virtio.c:1007
12:12:56      #3 0x7f8aec4d6214 in virtio_vfu_access_bar4 /var/jenkins/workspace/vfio-user-autotest/spdk/module/vfu_device/vfu_virtio.c:1263
12:12:56      #4 0x7f8ae6f73f40 in region_access ../../../libvfio-user/lib/libvfio-user.c:233
12:12:56      #5 0x7f8ae6f7441d in handle_region_access ../../../libvfio-user/lib/libvfio-user.c:338
12:12:56      #6 0x7f8ae6f764d4 in handle_request ../../../libvfio-user/lib/libvfio-user.c:1164
12:12:56      #7 0x7f8ae6f76eef in vfu_run_ctx ../../../libvfio-user/lib/libvfio-user.c:1466
12:12:56      #8 0x7f8aea32264a in tgt_vfu_ctx_poller /var/jenkins/workspace/vfio-user-autotest/spdk/lib/vfu_tgt/tgt_endpoint.c:132
12:12:56      #9 0x7f8aea214012 in thread_execute_timed_poller /var/jenkins/workspace/vfio-user-autotest/spdk/lib/thread/thread.c:1007
12:12:56      #10 0x7f8aea21527a in thread_poll /var/jenkins/workspace/vfio-user-autotest/spdk/lib/thread/thread.c:1097
12:12:56      #11 0x7f8aea215f14 in spdk_thread_poll /var/jenkins/workspace/vfio-user-autotest/spdk/lib/thread/thread.c:1156
12:12:56      #12 0x7f8aeae08396 in _reactor_run /var/jenkins/workspace/vfio-user-autotest/spdk/lib/event/reactor.c:914
12:12:56      #13 0x7f8aeae08cce in reactor_run /var/jenkins/workspace/vfio-user-autotest/spdk/lib/event/reactor.c:952
12:12:56      #14 0x7f8aeae09c16 in spdk_reactors_start /var/jenkins/workspace/vfio-user-autotest/spdk/lib/event/reactor.c:1068
12:12:56      #15 0x7f8aeadf8f2c in spdk_app_start /var/jenkins/workspace/vfio-user-autotest/spdk/lib/event/app.c:771
12:12:56      #16 0x40299f in main /var/jenkins/workspace/vfio-user-autotest/spdk/app/spdk_tgt/spdk_tgt.c:92
12:12:56      #17 0x7f8ae77fb50f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2750f)
12:12:56      #18 0x7f8ae77fb5c8 in __libc_start_main@GLIBC_2.2.5 (/usr/lib64/libc.so.6+0x275c8)
12:12:56      #19 0x402364 in _start (/var/jenkins/workspace/vfio-user-autotest/spdk/build/bin/spdk_tgt+0x402364)
12:12:56  
12:12:56  AddressSanitizer can not provide additional info.
12:12:56  SUMMARY: AddressSanitizer: SEGV /var/jenkins/workspace/vfio-user-autotest/spdk/module/vfu_device/vfu_virtio.c:102 in virtio_dev_map_vq
12:12:56  ==118353==ABORTING
12:13:11  
12:13:11  INFO: VM1 ready
12:13:11  Warning: Permanently added '[127.0.0.1]:10100' (ED25519) to the list of known hosts.
12:13:11  Warning: Permanently added '[127.0.0.1]:10100' (ED25519) to the list of known hosts.
12:13:11  INFO: all VMs ready
12:13:11   12:13:09	-- vhost/common.sh@978 -- # xtrace_enable
12:13:11   12:13:09	-- vhost/common.sh@979 -- # return 0
```

## Link to the failed CI build

Failed on the non production Jenkins server
Logs attached
[CI.log](https://github.com/spdk/spdk/files/11169440/CI.log)
[dmesg.log](https://github.com/spdk/spdk/files/11169448/dmesg.log)
[dmesg.init.log](https://github.com/spdk/spdk/files/11169449/dmesg.init.log)

## Execution failed at
```
12:13:11    12:13:10	-- vhost/common.sh@330 -- # sshpass -p root ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=root -p 10100 127.0.0.1 bash -s
12:13:11  Warning: Permanently added '[127.0.0.1]:10100' (ED25519) to the list of known hosts.
12:13:11   12:13:10	-- vhost/common.sh@1042 -- # SCSI_DISK=
12:13:11   12:13:10	-- vhost/common.sh@1044 -- # [[ -z '' ]]
12:13:11   12:13:10	-- vhost/common.sh@1045 -- # error 'no blk test disk found!'
12:13:11   12:13:10	-- vhost/common.sh@82 -- # echo ===========
12:13:11  ===========
12:13:11   12:13:10	-- vhost/common.sh@83 -- # message ERROR 'no blk test disk found!'
12:13:11   12:13:10	-- vhost/common.sh@60 -- # local verbose_out
12:13:11   12:13:10	-- vhost/common.sh@61 -- # false
12:13:11   12:13:10	-- vhost/common.sh@62 -- # verbose_out=
12:13:11   12:13:10	-- vhost/common.sh@69 -- # local msg_type=ERROR
12:13:11   12:13:10	-- vhost/common.sh@70 -- # shift
12:13:11   12:13:10	-- vhost/common.sh@71 -- # echo -e 'ERROR: no blk test disk found!'
12:13:11  ERROR: no blk test disk found!
12:13:11   12:13:10	-- vhost/common.sh@84 -- # echo ===========
12:13:11  ===========
12:13:11   12:13:10	-- vhost/common.sh@86 -- # false
12:13:11    12:13:10	-- vhost/common.sh@86 -- # trap - ERR
12:13:11    12:13:10	-- vhost/common.sh@86 -- # print_backtrace
12:13:11    12:13:10	-- common/autotest_common.sh@1097 -- # [[ ehxBET =~ e ]]
12:13:11    12:13:10	-- common/autotest_common.sh@1099 -- # args=('no blk test disk found!' '1' '1' 'virtio_blk' 'virtio_blk')
12:13:11    12:13:10	-- common/autotest_common.sh@1099 -- # local args
12:13:11    12:13:10	-- common/autotest_common.sh@1101 -- # xtrace_disable
12:13:11    12:13:10	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
12:13:11    12:13:10	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
12:13:11    12:13:10	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
12:13:11    12:13:10	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
12:13:11    12:13:10	-- common/autotest_common.sh@24 -- # set +x
12:13:11  ========== Backtrace start: ==========
12:13:11  
12:13:11  in /var/jenkins/workspace/vfio-user-autotest/spdk/test/vhost/common.sh:86 -> error(["no blk test disk found!"])
12:13:11       ...
12:13:11     81  	function error() {
12:13:11     82  		echo "===========" >&2
12:13:11     83  		message "ERROR" "$@" >&2
12:13:11     84  		echo "===========" >&2
12:13:11     85  		# Don't 'return 1' since the stack trace will be incomplete (why?) missing upper command.
12:13:11  => 86  		false
12:13:11     87  	}
12:13:11     88  	
12:13:11     89  	function warning() {
12:13:11     90  		message "WARN" "$@" >&2
12:13:11     91  	}
12:13:11       ...
```

**Comment by changpe1** [comment]
@jchachux let me take a look, can you post the failed patch set ?

**Comment by jimharris** [comment]
@jchachux - can you post the failed patch set per request from @changpe1?

**Comment by jchachux** [comment]
This is happening on latest master on 2 Wolf Pass Servers. Maybe this is HW specific. I am attaching some hw specs
QEMU emulator version 7.0.50
[lshw.log](https://github.com/spdk/spdk/files/11210085/lshw.log)

**Comment by changpe1** [comment]
@jchachux I can't run SPDK in your systems with a non-priviledged user, does this system run other test cases correctly?
from the code's context, I don't find any exceptions.

**Comment by jchachux** [comment]
@changpe1 The OS is our regular system that runs all our tests and the user you received credentials for is  listed in the sudoers group with all necessary permissions.

**Comment by jchachux** [comment]
@changpe1 I noticed that this error occurs only when the disk block size is set to 4096. When we change it to 512, the issue doesn't occur. 
```
[sys_sgci@spdk-WFP-26 ~]$ sudo nvme id-ns /dev/nvme0n1
...
lbaf  0 : ms:0   lbads:9  rp:0x2 (in use)
lbaf  1 : ms:0   lbads:12 rp:0 
```

Also in vhost job in vhost boot test we get:
```
echo 'ERROR: Your device "Nvme0n1" block size is 4096, but should be 512 bytes.'
11:24:15  ERROR: Your device "Nvme0n1" block size is 4096, but should be 512 bytes.
```
Do you know why there is a need for 512 block size?

**Comment by tomzawadzki** [comment]
[Bug scrub] @jchachux Can you please update on the latest in the issue ? Were the machines finally added to the CI and whether the block size was affecting the results.

**Comment by jchachux** [comment]
Machines were successfully added to the CI. Additionally, changing the block size resolved the issue, and now both tests are passing on multiple servers where they were previously failing. Therefore, it seems that the problem has been resolved, and everything is working fine now.
