### ISSUE TITLE
 Memory leak in nvme/reconnect/reconnect.c allocate_task() 

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#2995]
# Sighting report

libasan detects:
```
==133277==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 3072 byte(s) in 96 object(s) allocated from:
    #0 0x7fa5013d9097 in calloc (/usr/lib64/libasan.so.8+0xba097)
    #1 0x412673 in allocate_task /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:467
    #2 0x4127ba in submit_io /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:486
    #3 0x412ad8 in work_fn /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:513
    #4 0x8ffadb in eal_thread_loop ../lib/eal/common/eal_common_thread.c:211
    #5 0x7fa4ffc0812c in start_thread (/usr/lib64/libc.so.6+0x8b12c)

Direct leak of 1024 byte(s) in 32 object(s) allocated from:
    #0 0x7fa5013d9097 in calloc (/usr/lib64/libasan.so.8+0xba097)
    #1 0x412673 in allocate_task /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:467
    #2 0x4127ba in submit_io /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:486
    #3 0x412ad8 in work_fn /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:513
    #4 0x418d8d in main /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:1122
    #5 0x7fa4ffba450f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2750f)

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7fa5013d9097 in calloc (/usr/lib64/libasan.so.8+0xba097)
    #1 0x40e954 in nvme_init_ns_worker_ctx /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:192
    #2 0x41295a in work_fn /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:503
    #3 0x418d8d in main /home/sys_sgci/spdk/examples/nvme/reconnect/reconnect.c:1122
    #4 0x7fa4ffba450f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2750f)

SUMMARY: AddressSanitizer: 4104 byte(s) leaked in 129 allocation(s).
```
During `nvmf_target_disconnect_tc2` test (part of test/nvmf/host/target_disconnect.sh) using RDMA transport.

https://ci.spdk.io/public_build/autotest-per-patch_102831.html
https://ci.spdk.io/results/autotest-per-patch/builds/102831/archive/nvmf-phy-autotest/build.log

## Current Behavior

^up
Full log: 
[target_disconnect.txt](https://github.com/spdk/spdk/files/11340358/target_disconnect.txt)

## Steps to Reproduce
```
./configure --enable-asan --enable-ubsan --enable-coverage --enable-werror \
--enable-debug --with-crypto --with-fuse --with-idxd --with-nvme-cuse --with-rdma \
--with-usdt --with-fio --with-iscsi-initiator --with-nvme-cuse --with-vbdev-compress \
--with-dpdk-compressdev --with-rbd --with-ublk --with-raid5f --with-vfio-user --with-sma \
--with-xnvme --with-avahi --with-uring --with-ocf; 

make -j
sudo -E SPDK_TEST_NVMF=1   SPDK_TEST_NVMF_NICS=mlx5  SPDK_RUN_UBSAN=1 SPDK_RUN_ASAN=1 NET_TYPE=phy ./test/nvmf/host/target_disconnect.sh --iso --transport=rdma
```

## Context (Environment including OS version, SPDK version, etc.)

SPDK master branch with `e407385e036014161beab8a2e3f855dfeac00cb4` as last merged commit.
Cherry-picked on top for #2948 retest:
* https://review.spdk.io/gerrit/c/spdk/spdk/+/17788/4
* https://review.spdk.io/gerrit/c/spdk/spdk/+/17797/3
* https://review.spdk.io/gerrit/c/spdk/spdk/+/17287/11
* https://review.spdk.io/gerrit/c/spdk/spdk/+/17143

Fedora 37 6.1.14-200.fc37.x86_64
gcc (GCC) 12.2.1 20221121 (Red Hat 12.2.1-4)

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/17873

**Comment by ksztyber** [comment]
Patch was merged, closing.
