### ISSUE TITLE
[Fedora38] [iscsi_tgt_reset] bdev_scsi_inquiry: *ERROR*: unsupported INQUIRY VPD page 0xb9

### ISSUE THREAD

**Issue by kgodzwox** [spdk/spdk#3005]
# Sighting report
Tests run under Fedora 38.
Subjob `iscsi-uring-vg-autotest` failed during `iscsi_tgt_reset` test.
Subjob `iscsi-vg-autotest` failed during `iscsi_tgt_reset` test.

```
[2023-04-24T15:42:08.974Z] Logging in to [iface: default, target: iqn.2016-06.io.spdk:Target3, portal: 10.0.0.1,3260]
[2023-04-24T15:42:08.974Z] Login to [iface: default, target: iqn.2016-06.io.spdk:Target3, portal: 10.0.0.1,3260] successful.
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@49 -- # waitforiscsidevices 1
[2023-04-24T15:42:08.974Z]  15:42:08	-- iscsi_tgt/common.sh@116 -- # local num=1
[2023-04-24T15:42:08.974Z]  15:42:08	-- iscsi_tgt/common.sh@118 -- # (( i = 1 ))
[2023-04-24T15:42:08.974Z]  15:42:08	-- iscsi_tgt/common.sh@118 -- # (( i <= 20 ))
[2023-04-24T15:42:08.974Z]   15:42:08	-- iscsi_tgt/common.sh@119 -- # iscsiadm -m session -P 3
[2023-04-24T15:42:08.974Z]   15:42:08	-- iscsi_tgt/common.sh@119 -- # grep -c 'Attached scsi disk sd[a-z]*'
[2023-04-24T15:42:08.974Z]  15:42:08	-- iscsi_tgt/common.sh@119 -- # n=1
[2023-04-24T15:42:08.974Z]  15:42:08	-- iscsi_tgt/common.sh@120 -- # '[' 1 -ne 1 ']'
[2023-04-24T15:42:08.974Z]  15:42:08	-- iscsi_tgt/common.sh@123 -- # return 0
[2023-04-24T15:42:08.974Z]   15:42:08	-- reset/reset.sh@51 -- # iscsiadm -m session -P 3
[2023-04-24T15:42:08.974Z]   15:42:08	-- reset/reset.sh@51 -- # grep 'Attached scsi disk'
[2023-04-24T15:42:08.974Z]   15:42:08	-- reset/reset.sh@51 -- # awk '{print $4}'
[2023-04-24T15:42:08.974Z] [2023-04-24 15:42:08.879687] scsi_bdev.c: 618:bdev_scsi_inquiry: *ERROR*: unsupported INQUIRY VPD page 0xb9
[2023-04-24T15:42:08.974Z] FIO pid: 54036
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@51 -- # dev=sda
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@54 -- # fiopid=54036
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@55 -- # echo 'FIO pid: 54036'
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@57 -- # trap 'iscsicleanup; killprocess $pid; killprocess $fiopid; iscsitestfini; exit 1' SIGINT SIGTERM EXIT
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@53 -- # /home/vagrant/spdk_repo/spdk/scripts/fio-wrapper -p iscsi -i 512 -d 1 -t read -r 60
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@60 -- # for i in 1 2 3
[2023-04-24T15:42:08.974Z]  15:42:08	-- reset/reset.sh@61 -- # sleep 1
[2023-04-24T15:42:08.974Z] [global]
[2023-04-24T15:42:08.974Z] thread=1
[2023-04-24T15:42:08.974Z] invalidate=1
[2023-04-24T15:42:08.974Z] rw=read
[2023-04-24T15:42:08.974Z] time_based=1
[2023-04-24T15:42:08.974Z] runtime=60
[2023-04-24T15:42:08.974Z] ioengine=libaio
[2023-04-24T15:42:08.974Z] direct=1
[2023-04-24T15:42:08.974Z] bs=512
[2023-04-24T15:42:08.974Z] iodepth=1
[2023-04-24T15:42:08.974Z] norandommap=1
[2023-04-24T15:42:08.974Z] numjobs=1
[2023-04-24T15:42:08.974Z] verify_dump=1
[2023-04-24T15:42:08.974Z] verify_backlog=512
[2023-04-24T15:42:08.974Z] verify_state_save=0
[2023-04-24T15:42:08.974Z] [job0]
[2023-04-24T15:42:08.974Z] filename=/dev/sda
[2023-04-24T15:42:08.974Z] queue_depth set to 113 (sda)
[2023-04-24T15:42:09.911Z]  15:42:09	-- reset/reset.sh@62 -- # kill -s 0 54000
[2023-04-24T15:42:09.911Z]  15:42:09	-- reset/reset.sh@63 -- # kill -s 0 54036
[2023-04-24T15:42:09.911Z]  15:42:09	-- reset/reset.sh@64 -- # sg_reset -d /dev/sda
[2023-04-24T15:42:09.911Z] [2023-04-24 15:42:09.894132] iscsi.c:3672:iscsi_pdu_hdr_op_task: *NOTICE*: LOGICAL_UNIT_RESET
[2023-04-24T15:42:09.911Z]  15:42:09	-- reset/reset.sh@65 -- # sleep 1
[2023-04-24T15:42:09.911Z] [2023-04-24 15:42:09.908770] scsi_bdev.c: 618:bdev_scsi_inquiry: *ERROR*: unsupported INQUIRY VPD page 0xb9
[2023-04-24T15:42:10.840Z] /home/vagrant/spdk_repo/spdk/scripts/fio-wrapper: line 46: 54057 Done                    fio_config "$@"
[2023-04-24T15:42:10.840Z]      54058 Illegal instruction     (core dumped) | fio -
[2023-04-24T15:42:11.098Z]  15:42:10	-- reset/reset.sh@66 -- # kill -s 0 54000
[2023-04-24T15:42:11.098Z]  15:42:10	-- reset/reset.sh@67 -- # kill -s 0 54036
[2023-04-24T15:42:11.098Z] /home/vagrant/spdk_repo/spdk/test/iscsi_tgt/reset/reset.sh: line 67: kill: (54036) - No such process
[2023-04-24T15:42:11.098Z]   15:42:10	-- reset/reset.sh@67 -- # trap - ERR
[2023-04-24T15:42:11.098Z]   15:42:10	-- reset/reset.sh@67 -- # print_backtrace
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@1097 -- # [[ ehxBET =~ e ]]
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@1099 -- # args=()
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@1099 -- # local args
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@1101 -- # xtrace_disable
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@19 -- # '[' no '!=' yes ']'
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@20 -- # PREV_BASH_OPTS=ehxBET
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@21 -- # [[ ehxBET == *\x* ]]
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@22 -- # XTRACE_DISABLED=yes
[2023-04-24T15:42:11.098Z]   15:42:10	-- common/autotest_common.sh@24 -- # set +x
[2023-04-24T15:42:11.098Z] ========== Backtrace start: ==========
[2023-04-24T15:42:11.098Z] 
[2023-04-24T15:42:11.098Z] in /home/vagrant/spdk_repo/spdk/test/iscsi_tgt/reset/reset.sh:67 -> main([])
[2023-04-24T15:42:11.098Z]      ...
[2023-04-24T15:42:11.098Z]    62  		kill -s 0 $pid
[2023-04-24T15:42:11.098Z]    63  		kill -s 0 $fiopid
[2023-04-24T15:42:11.098Z]    64  		sg_reset -d /dev/$dev
[2023-04-24T15:42:11.098Z]    65  		sleep 1
[2023-04-24T15:42:11.098Z]    66  		kill -s 0 $pid
[2023-04-24T15:42:11.098Z] => 67  		kill -s 0 $fiopid
[2023-04-24T15:42:11.098Z]    68  	done
[2023-04-24T15:42:11.098Z]    69  	
[2023-04-24T15:42:11.098Z]    70  	kill $fiopid
[2023-04-24T15:42:11.098Z]    71  	wait $fiopid || true
[2023-04-24T15:42:11.098Z]    72  	
[2023-04-24T15:42:11.098Z]      ...
[2023-04-24T15:42:11.098Z] 
[2023-04-24T15:42:11.098Z] ========== Backtrace end ==========
```
```
[2023-04-24T15:42:11.665Z] ========== Backtrace start: ==========
[2023-04-24T15:42:11.665Z] 
[2023-04-24T15:42:11.665Z] in /home/vagrant/spdk_repo/spdk/test/common/autotest_common.sh:1069 -> run_test(["iscsi_tgt_reset"],["/home/vagrant/spdk_repo/spdk/test/iscsi_tgt/reset/reset.sh"])
[2023-04-24T15:42:11.665Z]      ...
[2023-04-24T15:42:11.665Z]    1064		timing_enter $test_name
[2023-04-24T15:42:11.665Z]    1065		echo "************************************"
[2023-04-24T15:42:11.665Z]    1066		echo "START TEST $test_name"
[2023-04-24T15:42:11.665Z]    1067		echo "************************************"
[2023-04-24T15:42:11.665Z]    1068		xtrace_restore
[2023-04-24T15:42:11.665Z]    1069		time "$@"
[2023-04-24T15:42:11.665Z]    1070		xtrace_disable
[2023-04-24T15:42:11.665Z]    1071		echo "************************************"
[2023-04-24T15:42:11.665Z]    1072		echo "END TEST $test_name"
[2023-04-24T15:42:11.665Z]    1073		echo "************************************"
[2023-04-24T15:42:11.665Z]    1074		timing_exit $test_name
[2023-04-24T15:42:11.665Z]      ...
[2023-04-24T15:42:11.665Z] in /home/vagrant/spdk_repo/spdk/test/iscsi_tgt/iscsi_tgt.sh:32 -> main([])
[2023-04-24T15:42:11.665Z]      ...
[2023-04-24T15:42:11.665Z]    27  		run_test "iscsi_tgt_calsoft" $rootdir/test/iscsi_tgt/calsoft/calsoft.sh
[2023-04-24T15:42:11.665Z]    28  	else
[2023-04-24T15:42:11.665Z]    29  		skip_run_test_with_warning "WARNING: Calsoft binaries not found, skipping test!"
[2023-04-24T15:42:11.665Z]    30  	fi
[2023-04-24T15:42:11.665Z]    31  	run_test "iscsi_tgt_filesystem" $rootdir/test/iscsi_tgt/filesystem/filesystem.sh
[2023-04-24T15:42:11.665Z] => 32  	run_test "iscsi_tgt_reset" $rootdir/test/iscsi_tgt/reset/reset.sh
[2023-04-24T15:42:11.665Z]    33  	run_test "iscsi_tgt_rpc_config" $rootdir/test/iscsi_tgt/rpc_config/rpc_config.sh
[2023-04-24T15:42:11.665Z]    34  	run_test "iscsi_tgt_iscsi_lvol" $rootdir/test/iscsi_tgt/lvol/iscsi_lvol.sh
[2023-04-24T15:42:11.665Z]    35  	run_test "iscsi_tgt_fio" $rootdir/test/iscsi_tgt/fio/fio.sh
[2023-04-24T15:42:11.665Z]    36  	run_test "iscsi_tgt_qos" $rootdir/test/iscsi_tgt/qos/qos.sh
[2023-04-24T15:42:11.665Z]    37  	run_test "iscsi_tgt_ip_migration" $rootdir/test/iscsi_tgt/ip_migration/ip_migration.sh
[2023-04-24T15:42:11.665Z]      ...
[2023-04-24T15:42:11.665Z] 
[2023-04-24T15:42:11.665Z] ========== Backtrace end ==========
```
```
[2023-04-24T15:42:21.635Z] ##### CORE BT fio_54058.core.bt.txt #####
[2023-04-24T15:42:21.635Z] 
[2023-04-24T15:42:21.635Z] gdb: warning: Couldn't determine a path for the index cache directory.
[2023-04-24T15:42:21.635Z] [New LWP 54058]
[2023-04-24T15:42:21.635Z] [Thread debugging using libthread_db enabled]
[2023-04-24T15:42:21.635Z] Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[2023-04-24T15:42:21.635Z] Core was generated by `fio -'.
[2023-04-24T15:42:21.635Z] Program terminated with signal SIGILL, Illegal instruction.
[2023-04-24T15:42:21.635Z] #0  0x000000000040f917 in fio_client_hash_init () at client.c:96
[2023-04-24T15:42:21.635Z] 96			INIT_FLIST_HEAD(&client_hash[i]);
[2023-04-24T15:42:21.635Z] 
[2023-04-24T15:42:21.635Z] Thread 1 (Thread 0x7fae0726a540 (LWP 54058)):
[2023-04-24T15:42:21.635Z] #0  0x000000000040f917 in fio_client_hash_init () at client.c:96
[2023-04-24T15:42:21.635Z]         i = 0
[2023-04-24T15:42:21.635Z] #1  0x00007fae081efc84 in __libc_start_main_impl () from /usr/lib64/libc.so.6
[2023-04-24T15:42:21.635Z] No symbol table info available.
[2023-04-24T15:42:21.635Z] #2  0x000000000040fbc5 in _start ()
[2023-04-24T15:42:21.635Z] No symbol table info available.
[2023-04-24T15:42:21.635Z] 
[2023-04-24T15:42:21.635Z] --
[2023-04-24T15:42:23.011Z] INFO: APP EXITING
[2023-04-24T15:42:23.011Z] INFO: killing all VMs
[2023-04-24T15:42:23.011Z] INFO: killing vhost app
[2023-04-24T15:42:23.011Z] WARN: no vhost pid file found
[2023-04-24T15:42:23.011Z] INFO: EXIT DONE
[2023-04-24T15:42:23.267Z] 0000:00:03.0 (1af4 1001): Active devices: mount@vda:vda2,mount@vda:vda3,mount@vda:vda5, so not binding PCI dev
[2023-04-24T15:42:23.267Z] Waiting for block devices as requested
[2023-04-24T15:42:23.267Z] 0000:00:06.0 (1b36 0010): uio_pci_generic -> nvme
[2023-04-24T15:42:23.526Z] 0000:00:07.0 (1b36 0010): uio_pci_generic -> nvme
[2023-04-24T15:42:24.093Z] 0000:00:03.0 (1af4 1001): Active devices: mount@vda:vda2,mount@vda:vda3,mount@vda:vda5, so not binding PCI dev
[2023-04-24T15:42:24.093Z] Cleaning
```

## Context (Environment including OS version, SPDK version, etc.)
OS: `Fedora38`
Kernel: `6.2.11-300.fc38.x86_64`
SPDK ver: `v23.05-pre-526-g487069501`

Tests run on unofficial Jenkins. Build log available below:
[iscsi-uring-vg-autotest.log](https://github.com/spdk/spdk/files/11352746/iscsi-uring-vg-autotest.log)
[iscsi-vg-autotest.log](https://github.com/spdk/spdk/files/11352747/iscsi-vg-autotest.log)

**Comment by jimharris** [comment]
This is a dup of #3002.  The error message isn't important here, the test is failing because fio crashed due to the SIGILL reported in #3002.
