### ISSUE TITLE
nvmf-tcp-autotest: memory leak in json_util.c spdk_json_strdup 

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#3009]
# Sighting report

ASAN detects a memory leak in spdk_json_strdup() called in during NVMe-oF test:
https://ci.spdk.io/public_build/autotest-per-patch_103268.html
https://ci.spdk.io/results/autotest-per-patch/builds/103268/archive/nvmf-tcp-phy-autotest/index.html
https://ci.spdk.io/results/autotest-per-patch/builds/103268/archive/nvmf-tcp-uring-vg-autotest/index.html
https://ci.spdk.io/results/autotest-per-patch/builds/103268/archive/nvmf-tcp-vg-autotest/index.html

## Current Behavior

```
00:13:13.491  =================================================================
00:13:13.491  ==1565809==ERROR: LeakSanitizer: detected memory leaks
00:13:13.491  
00:13:13.491  Direct leak of 29 byte(s) in 2 object(s) allocated from:
00:13:13.491      #0 0x7f7f878fb6af in __interceptor_malloc (/usr/lib64/libasan.so.8+0xba6af)
00:13:13.491      #1 0x7f7f83a084c3 in spdk_json_strdup /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/json/json_util.c:61
00:13:13.491      #2 0x7f7f83a0c611 in spdk_json_decode_string /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/json/json_util.c:492
00:13:13.491      #3 0x7f7f83a0b339 in _json_decode_object /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/json/json_util.c:331
00:13:13.491      #4 0x7f7f83a0bd34 in spdk_json_decode_object /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/json/json_util.c:388
00:13:13.491      #5 0x7f7f83d4bd30 in rpc_sock_impl_set_options /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/sock/sock_rpc.c:140
00:13:13.491      #6 0x7f7f83aaa23f in jsonrpc_handler /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/rpc/rpc.c:124
00:13:13.491      #7 0x7f7f83a6c543 in jsonrpc_server_handle_request /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:222
00:13:13.491      #8 0x7f7f83a6422a in parse_single_request /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/jsonrpc/jsonrpc_server.c:75
00:13:13.491      #9 0x7f7f83a66210 in jsonrpc_parse_request /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/jsonrpc/jsonrpc_server.c:205
00:13:13.491      #10 0x7f7f83a6cfbb in jsonrpc_server_conn_recv /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:284
00:13:13.491      #11 0x7f7f83a6ec63 in spdk_jsonrpc_server_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:402
00:13:13.491      #12 0x7f7f83aaa6db in spdk_rpc_accept /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/rpc/rpc.c:213
00:13:13.491      #13 0x7f7f83cf999d in rpc_subsystem_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/init/rpc.c:21
00:13:13.491      #14 0x7f7f83bd722a in thread_execute_timed_poller /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:984
00:13:13.491      #15 0x7f7f83bd84e3 in thread_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:1074
00:13:13.491      #16 0x7f7f83bd91b7 in spdk_thread_poll /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/thread/thread.c:1133
00:13:13.491      #17 0x7f7f844b1bee in _reactor_run /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:914
00:13:13.491      #18 0x7f7f844b254b in reactor_run /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:952
00:13:13.491      #19 0x7f7f844b34e4 in spdk_reactors_start /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/reactor.c:1068
00:13:13.491      #20 0x7f7f844a18cf in spdk_app_start /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/lib/event/app.c:779
00:13:13.491      #21 0x405e32 in main /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/app/nvmf_tgt/nvmf_main.c:47
00:13:13.491      #22 0x7f7f8009250f in __libc_start_call_main (/usr/lib64/libc.so.6+0x2750f)
00:13:13.491  
00:13:13.491  SUMMARY: AddressSanitizer: 29 byte(s) leaked in 2 allocation(s).
```

## Steps to Reproduce

1. Create autorun conf file:
```
SPDK_RUN_FUNCTIONAL_TEST=1
SPDK_TEST_NVMF=1
SPDK_TEST_NVME_CLI=1
SPDK_TEST_NVMF_TRANSPORT=tcp
SPDK_TEST_NVMF_NICS=e810
SPDK_RUN_UBSAN=1
```
2. Configure and make SPDK:
```
./configure --enable-asan --enable-ubsan --enable-coverage --enable-werror --enable-debug \
--with-crypto --with-fuse --with-idxd --with-nvme-cuse --with-rdma --with-usdt --with-fio \
--with-iscsi-initiator --with-nvme-cuse --with-vbdev-compress --with-dpdk-compressdev \
--with-rbd --with-ublk --with-raid5f --with-vfio-user --with-sma --with-xnvme --with-avahi \
--with-uring --with-ocf --with-shared
make -j
``` 
3. `spdk/test/nvmf/target/tls.sh --transport=tcp --iso`

## Context (Environment including OS version, SPDK version, etc.)

https://review.spdk.io/gerrit/c/spdk/spdk/+/17143
(based on master branch 6828ed1807e750af3ff4d49686614fe6013191bf)

**Comment by ksztyber** [comment]
I think this is a duplicate of #2949.
