### ISSUE TITLE
NVMe RDMA Initiator core dump

### ISSUE THREAD

**Issue by C0reFast** [spdk/spdk#3037]
# Sighting report

when attaching a spdk nvme target using rdma, the initiator crashes and coredump generated.
```
Connection closed with partial response:
```

## Current Behavior
the backtrace:
```
#0  0x00007f316413327c in ucma_process_addr_resolved (evt=0x1a02960) at ../librdmacm/cma.c:2252
2252                        evt->id_priv->id.verbs->device->transport_type == IBV_TRANSPORT_IB)
[Current thread is 1 (Thread 0x7f316385f9c0 (LWP 1815152))]
Missing separate debuginfos, use: dnf debuginfo-install sina-nbs-vhost-1.0.0-3.el9.x86_64
(gdb)
(gdb) bt
#0  0x00007f316413327c in ucma_process_addr_resolved (evt=0x1a02960) at ../librdmacm/cma.c:2252
#1  rdma_get_cm_event (channel=0x1a50110, event=0x7ffd467c8868) at ../librdmacm/cma.c:2537
#2  0x00000000004afbbe in nvme_rdma_poll_events (rctrlr=0x20006801f200) at nvme_rdma.c:560
#3  0x00000000004afe06 in nvme_rdma_process_event_poll (rqpair=0x2000758b1780) at nvme_rdma.c:656
#4  0x00000000004b217f in nvme_rdma_ctrlr_connect_qpair_poll (ctrlr=0x20006801f200, qpair=0x2000758b1780) at nvme_rdma.c:1378
#5  0x00000000004b5aab in nvme_rdma_qpair_process_completions (qpair=0x2000758b1780, max_completions=31) at nvme_rdma.c:2732
#6  0x000000000049a9ad in nvme_transport_qpair_process_completions (qpair=0x2000758b1780, max_completions=0) at nvme_transport.c:614
#7  0x000000000049412f in spdk_nvme_qpair_process_completions (qpair=0x2000758b1780, max_completions=0) at nvme_qpair.c:792
#8  0x00000000004802a2 in nvme_ctrlr_process_init (ctrlr=0x20006801f200) at nvme_ctrlr.c:3807
#9  0x0000000000496724 in nvme_ctrlr_poll_internal (ctrlr=0x20006801f200, probe_ctx=0x1a34cd0) at nvme.c:697
#10 0x0000000000498b75 in spdk_nvme_probe_poll_async (probe_ctx=0x1a34cd0) at nvme.c:1510
#11 0x000000000041ac79 in bdev_nvme_async_poll (arg=0x1a34700) at bdev_nvme.c:5517
#12 0x0000000000574994 in thread_execute_timed_poller (thread=0x1a27e70, poller=0x1a35860, now=507955674172700) at thread.c:998
#13 0x0000000000574cb6 in thread_poll (thread=0x1a27e70, max_msgs=0, now=507955674172700) at thread.c:1088
#14 0x0000000000574ed7 in spdk_thread_poll (thread=0x1a27e70, max_msgs=0, now=507955674172700) at thread.c:1147
#15 0x000000000052a6d6 in _reactor_run (reactor=0x1a27800) at reactor.c:914
#16 0x000000000052a7ca in reactor_run (arg=0x1a27800) at reactor.c:952
#17 0x000000000052ac64 in spdk_reactors_start () at reactor.c:1068
#18 0x0000000000526eaf in spdk_app_start (opts_user=0x7ffd467c8f70, start_fn=0x4098fa <vhost_started>, arg1=0x0) at app.c:808
#19 0x00000000004099f0 in main (argc=8, argv=0x7ffd467c9168) at vhost.c:77
```
I did some gdb tracking, found the `evt->id_priv->id.verbs` is null:
```
Thread 1 "reactor_1" hit Breakpoint 2, ucma_process_addr_resolved (evt=0x25e3960) at ../librdmacm/cma.c:2249
2249            if (af_ib_support) {
(gdb) print evt
$1 = (struct cma_event *) 0x25e3960
(gdb) print *evt
$2 = {event = {id = 0x262d250, listen_id = 0x0, event = RDMA_CM_EVENT_ADDR_RESOLVED, status = 0, param = {conn = {private_data = 0x0, private_data_len = 0 '\000', responder_resources = 0 '\000',
        initiator_depth = 0 '\000', flow_control = 0 '\000', retry_count = 0 '\000', rnr_retry_count = 0 '\000', srq = 0 '\000', qp_num = 0}, ud = {private_data = 0x0, private_data_len = 0 '\000', ah_attr = {
          grh = {dgid = {raw = '\000' <repeats 15 times>, global = {subnet_prefix = 0, interface_id = 0}}, flow_label = 0, sgid_index = 0 '\000', hop_limit = 0 '\000', traffic_class = 0 '\000'}, dlid = 0,
          sl = 0 '\000', src_path_bits = 0 '\000', static_rate = 0 '\000', is_global = 0 '\000', port_num = 0 '\000'}, qp_num = 0, qkey = 0}}}, private_data = '\000' <repeats 255 times>, id_priv = 0x262d250,
  mc = 0x0}
(gdb) print evt->id_priv                                                                                                                                                                                         $3 = (struct cma_id_private *) 0x262d250
(gdb) print *evt->id_priv
$4 = {id = {verbs = 0x0, channel = 0x262d070, context = 0x2000758b1780, qp = 0x0, route = {addr = {{src_addr = {sa_family = 0, sa_data = '\000' <repeats 13 times>}, src_sin = {sin_family = 0, sin_port = 0,
            sin_addr = {s_addr = 0}, sin_zero = "\000\000\000\000\000\000\000"}, src_sin6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>,
                __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, src_storage = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}}, {
          dst_addr = {sa_family = 2, sa_data = "\021D\n\001'\032\000\000\000\000\000\000\000"}, dst_sin = {sin_family = 2, sin_port = 17425, sin_addr = {s_addr = 438763786},
            sin_zero = "\000\000\000\000\000\000\000"}, dst_sin6 = {sin6_family = 2, sin6_port = 17425, sin6_flowinfo = 438763786, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>,
                __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, dst_storage = {ss_family = 2, __ss_padding = "\021D\n\001'\032", '\000' <repeats 111 times>,
            __ss_align = 0}}, addr = {ibaddr = {sgid = {raw = '\000' <repeats 15 times>, global = {subnet_prefix = 0, interface_id = 0}}, dgid = {raw = '\000' <repeats 15 times>, global = {subnet_prefix = 0,
                interface_id = 0}}, pkey = 0}}}, path_rec = 0x0, num_paths = 0}, ps = RDMA_PS_TCP, port_num = 0 '\000', event = 0x0, send_cq_channel = 0x0, send_cq = 0x0, recv_cq_channel = 0x0,
    recv_cq = 0x0, srq = 0x0, pd = 0x0, qp_type = IBV_QPT_RC}, cma_dev = 0x0, connect = 0x0, connect_len = 0, events_completed = 0, connect_error = 0, sync = 0, cond = {__data = {{__wseq = 0, __wseq32 = {
          __low = 0, __high = 0}}, {__g1_start = 0, __g1_start32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}},
    __size = '\000' <repeats 47 times>, __align = 0}, mut = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}},
    __size = '\000' <repeats 39 times>, __align = 0}, handle = 0, mc_list = 0x0, qp_init_attr = 0x0, initiator_depth = 0 '\000', responder_resources = 0 '\000', local_ece = {vendor_id = 0, options = 0,
    comp_mask = 0}, remote_ece = {vendor_id = 0, options = 0, comp_mask = 0}}
```

## Steps to Reproduce
1. setup a spdk nvme rdma target
2. rpc.py bdev_nvme_attach_controller -b Nvme0 -t rdma -a 10.1.39.26 -f IPv4 -s 4420 -n nqn.2016-06.io.spdk:test-rdma -i 10.1.38.31

## Context (Environment including OS version, SPDK version, etc.)
OS version: Almalinux 9.1
Kernel: 5.14.0-162.6.1
SPDK: 113075be6639ff9ca8fa9aa553edb483746fab1b
RDMA: librdmacm-44.0-2.el9.x86_64

my host has many ib devices, so i must use  -i param to specify a host ip to use specific ib device.
```
[root@wq-10-1-38-31.chinanet-north-2.node.vmhost /data0/spdk]# ibdev2netdev
mlx5_0 port 1 ==> enp1s0f1v15 (Up)
mlx5_bond_0 port 1 ==> enp1s0f0 (Up)
mlx5_bond_0 port 10 ==> enp1s0f0 (Up)
mlx5_bond_0 port 11 ==> enp1s0f0 (Up)
mlx5_bond_0 port 12 ==> enp1s0f0 (Up)
mlx5_bond_0 port 13 ==> enp1s0f0 (Up)
mlx5_bond_0 port 14 ==> enp1s0f0 (Up)
mlx5_bond_0 port 15 ==> enp1s0f0 (Up)
mlx5_bond_0 port 16 ==> enp1s0f0 (Up)
mlx5_bond_0 port 17 ==> enp1s0f0 (Up)
mlx5_bond_0 port 18 ==> enp1s0f0 (Up)
mlx5_bond_0 port 19 ==> enp1s0f0 (Up)
mlx5_bond_0 port 2 ==> enp1s0f0 (Up)
mlx5_bond_0 port 20 ==> enp1s0f0 (Up)
mlx5_bond_0 port 21 ==> enp1s0f0 (Up)
mlx5_bond_0 port 22 ==> enp1s0f0 (Up)
mlx5_bond_0 port 23 ==> enp1s0f0 (Up)
mlx5_bond_0 port 24 ==> enp1s0f0 (Up)
mlx5_bond_0 port 25 ==> enp1s0f0 (Up)
mlx5_bond_0 port 26 ==> enp1s0f0 (Up)
mlx5_bond_0 port 27 ==> enp1s0f0 (Up)
mlx5_bond_0 port 28 ==> enp1s0f0 (Up)
mlx5_bond_0 port 29 ==> enp1s0f0 (Up)
mlx5_bond_0 port 3 ==> enp1s0f0 (Up)
mlx5_bond_0 port 30 ==> enp1s0f0 (Up)
mlx5_bond_0 port 31 ==> enp1s0f0 (Up)
mlx5_bond_0 port 32 ==> enp1s0f0 (Up)
mlx5_bond_0 port 33 ==> enp1s0f0 (Up)
mlx5_bond_0 port 34 ==> enp1s0f0 (Up)
mlx5_bond_0 port 35 ==> enp1s0f0 (Up)
mlx5_bond_0 port 4 ==> enp1s0f0 (Up)
mlx5_bond_0 port 5 ==> enp1s0f0 (Up)
mlx5_bond_0 port 6 ==> enp1s0f0 (Up)
mlx5_bond_0 port 7 ==> enp1s0f0 (Up)
mlx5_bond_0 port 8 ==> enp1s0f0 (Up)
mlx5_bond_0 port 9 ==> enp1s0f0 (Up)
```

**Comment by C0reFast** [comment]
the issue seems releated to https://github.com/openucx/ucx/issues/2534

**Comment by C0reFast** [comment]
It's a known issue of OFED
1047616 | Description: When node GUID of a device is set to zero (0000:0000:0000:0000), RDMA_CM user space application may crash.
Workaround: Set node GUID to a nonzero value.
Keywords: RDMA_CM
