### ISSUE TITLE
Memory leaks when using rpc construct_virtio_user_blk_bdev

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#305]
## Expected Behavior
No error when killing spdk_tgt

## Current Behavior
=================================================================
==7933==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 2 object(s) allocated from:
    #0 0x7f34b27dc602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x6f0e4d in spdk_json_strdup /root/spdk_bdev_json/lib/json/json_util.c:86
    #2 0x6f3781 in spdk_json_decode_string /root/spdk_bdev_json/lib/json/json_util.c:417
    #3 0x6f2d5f in spdk_json_decode_object /root/spdk_bdev_json/lib/json/json_util.c:311
    #4 0x518d73 in spdk_rpc_create_virtio_user_blk_bdev /root/spdk_bdev_json/lib/bdev/virtio/bdev_virtio_rpc.c:331
    #5 0x6e25ff in spdk_jsonrpc_handler /root/spdk_bdev_json/lib/rpc/rpc.c:81
    #6 0x6e8dda in spdk_jsonrpc_server_handle_request /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server_tcp.c:178
    #7 0x6e48b5 in parse_single_request /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server.c:116
    #8 0x6e54d6 in spdk_jsonrpc_parse_request /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server.c:178
    #9 0x6e961e in spdk_jsonrpc_server_conn_recv /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server_tcp.c:237
    #10 0x6eaf60 in spdk_jsonrpc_server_poll /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server_tcp.c:385
    #11 0x6e326b in spdk_rpc_accept /root/spdk_bdev_json/lib/rpc/rpc.c:199
    #12 0x69facc in spdk_rpc_subsystem_poll /root/spdk_bdev_json/lib/event/rpc.c:51
    #13 0x69d3bd in _spdk_reactor_run /root/spdk_bdev_json/lib/event/reactor.c:492
    #14 0x69e7d1 in spdk_reactors_start /root/spdk_bdev_json/lib/event/reactor.c:643
    #15 0x6965f7 in spdk_app_start /root/spdk_bdev_json/lib/event/app.c:567
    #16 0x407f10 in main /root/spdk_bdev_json/app/spdk_tgt/spdk_tgt.c:121
    #17 0x7f349cd4982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 2 allocation(s).

## Possible Solution
None

## Steps to Reproduce
spdk_tgt.conf:
[Global]
[Ioat]
  Disable Yes
[Nvme]
  HotplugEnable Yes

virtio.conf:
[Global]
  NoPci Yes
[Ioat]
  Disable Yes

1. ./scripts/gen_nvme.sh >> spdk_tgt.conf
2. ./app/spdk_tgt/spdk_tgt -m 0x1 -p 0 -c spdk_tgt.conf -s 1024 -r /var/tmp/spdk.sock &
3. spdk_tgt_pid=$!
4. waitforlisten $spdk_tgt /var/tmp/spdk.sock
5. ./scripts/rpc.py construct_split_vbdev Nvme0n1 4
6. ./scripts/rpc.py construct_vhost_blk_controller naa.Nvme1n1p0.0 Nvme1n1p0
7. ./app/spdk_tgt/spdk_tgt -m 0x2 -p 0 -c virtio.conf -s 1024 -r /var/tmp/virtio.sock &
8. virtio_pid=$!
9. waitforlisten $virtio_pid /var/tmp/virtio.sock
10 ./scripts/rpc.py construct_virtio_user_blk_bdev naa.Nvme1n1p0.0 Nvme1n1p0
11. kill $virtio_pid

## Context (Environment including OS version, SPDK version, etc.)
Virtual machine with ubuntu 16.4 and two emulated nvme devices (1G, 2G).

**Comment by darsto** [comment]
patch submitted: https://review.gerrithub.io/c/spdk/spdk/+/411959
Thanks,
D.

**Comment by yidong0635** [comment]
follow:
  CONFIG：` asan=y`
`./scripts/gen_nvme.sh >> spdk_tgt.conf`
`./app/spdk_tgt/spdk_tgt -m 0x1 -p 0 -c spdk_tgt.conf -s 1024 -r /var/tmp/spdk.sock & spdk_tgt_pid=$!`
waitforlisten $spdk_tgt /var/tmp/spdk.sock
`./scripts/rpc.py construct_split_vbdev Nvme0n1 4`
`./scripts/rpc.py construct_vhost_blk_controller naa.Nvme1n1p0.0 Nvme0n1p0`
`./app/spdk_tgt/spdk_tgt -m 0x2 -p 0 -c virtio.conf -s 1024 -r /var/tmp/virtio.sock & virtio_pid=$!`
waitforlisten $virtio_pid /var/tmp/virtio.sock
`./scripts/rpc.py construct_virtio_user_blk_bdev naa.Nvme1n1p0.0 Nvme0n1p0`


```
virtio_user/vhost_user.c: 226:get_hugepage_file_info: *ERROR*: Exceed maximum of 8
virtio_user/vhost_user.c: 251:prepare_vhost_memory_user: *ERROR*: Failed to prepare memory for vhost-user
virtio.c: 336:virtio_dev_start: *ERROR*: Failed to set VIRTIO_CONFIG_S_DRIVER_OK status.
=================================================================
VHOST_CONFIG: recvmsg failed
VHOST_CONFIG: vhost peer closed
==216567==ERROR: AddressSanitizer: attempting double-free on 0x602000003c90 in thread T0 (reactor_0):
    #0 0x7f54492f27b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x55c647cb8ab7 in virtio_user_blk_dev_create /home/zong/spdk/lib/bdev/virtio/bdev_virtio_blk.c:531
    #2 0x55c647cb910b in bdev_virtio_user_blk_dev_create /home/zong/spdk/lib/bdev/virtio/bdev_virtio_blk.c:658
    #3 0x55c647cb9388 in spdk_rpc_create_virtio_user_blk_bdev /home/zong/spdk/lib/bdev/virtio/bdev_virtio_rpc.c:338
    #4 0x55c647d5502d in parse_single_request /home/zong/spdk/lib/jsonrpc/jsonrpc_server.c:116
    #5 0x55c647d5502d in spdk_jsonrpc_parse_request /home/zong/spdk/lib/jsonrpc/jsonrpc_server.c:178
    #6 0x55c647d564c3 in spdk_jsonrpc_server_conn_recv /home/zong/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:237
    #7 0x55c647d564c3 in spdk_jsonrpc_server_poll /home/zong/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:385
    #8 0x55c647d3cdc8 in spdk_rpc_subsystem_poll /home/zong/spdk/lib/event/rpc.c:51
    #9 0x55c647d3bc81 in _spdk_reactor_run /home/zong/spdk/lib/event/reactor.c:492
    #10 0x55c647d3c487 in spdk_reactors_start /home/zong/spdk/lib/event/reactor.c:643
    #11 0x55c647d394fd in spdk_app_start /home/zong/spdk/lib/event/app.c:567
    #12 0x55c647c585b8 in main /home/zong/spdk/app/spdk_tgt/spdk_tgt.c:121
    #13 0x7f5447dd71c0 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x211c0)
    #14 0x55c647c5b319 in _start (/home/zong/spdk/app/spdk_tgt/spdk_tgt+0x64319)

0x602000003c90 is located 0 bytes inside of 10-byte region [0x602000003c90,0x602000003c9a)
freed by thread T0 (reactor_0) here:
    #0 0x7f54492f27b8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8)
    #1 0x55c647cb7b43 in virtio_blk_dev_init /home/zong/spdk/lib/bdev/virtio/bdev_virtio_blk.c:436

previously allocated by thread T0 (reactor_0) here:
    #0 0x7f544928b538 in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x77538)
    #1 0x55c647cbac87 in virtio_dev_construct /home/zong/spdk/lib/virtio/virtio.c:285

SUMMARY: AddressSanitizer: double-free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7b8) in __interceptor_free
==216567==ABORTING

```
