### ISSUE TITLE
Failing to build spdk v23.05: dpdk build fails with a ninja error

### ISSUE THREAD

**Issue by divy2950** [spdk/spdk#3057]
# Sighting report
I am not able to build spdk. It is failing to build dpdk lib with a ninja error.

## Expected Behavior

Should build successfully without any error

## Current Behavior

```
  User defined options
    libdir        : lib
    prefix        : /vault/extern/spdk/BUILD/Linux-x86_64/spdk/dpdk/build
    c_args        :  -fPIC -Wno-error
    c_link_args   :
    disable_libs  : acl,bbdev,bitratestats,bpf,cfgfile,distributor,efd,eventdev,fib,flow_classify,graph,gro,gso,ip_frag,ipsec,jobstats,kni,latencystats,lpm,member,metrics,node,pdump,pipeline,port,rawdev,regexdev,rib,sched,stack,table
    enable_docs   : false
    enable_drivers: bus,bus/pci,bus/vdev,mempool/ring
    enable_kmods  : false
    tests         : false

Found ninja-1.11.1.git.kitware.jobserver-1 at /usr/local/bin/ninja
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
ninja: Entering directory `/vault/extern/spdk/BUILD/Linux-x86_64/spdk/dpdk/build-tmp'
[185/260] Generating drivers/rte_bus_vdev.pmd.c with a custom command
FAILED: drivers/rte_bus_vdev.pmd.c
/usr/bin/python3 ../buildtools/gen-pmdinfo-cfile.py /vault/extern/spdk/BUILD/Linux-x86_64/spdk/dpdk/build-tmp/buildtools ar /vault/extern/spdk/BUILD/Linux-x86_64/spdk/dpdk/build-tmp/drivers/libtmp_rte_bus_vdev.a drivers/rte_bus_vdev.pmd.c /usr/bin/python3 ../buildtools/pmdinfogen.py elf
ar: `x' cannot be used on thin archives.
Traceback (most recent call last):
  File "../buildtools/gen-pmdinfo-cfile.py", line 17, in <module>
    run_ar("x")
  File "../buildtools/gen-pmdinfo-cfile.py", line 14, in <lambda>
    stdout=subprocess.PIPE, check=True, cwd=temp
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ar', 'x', '/vault/extern/spdk/BUILD/Linux-x86_64/spdk/dpdk/build-tmp/drivers/libtmp_rte_bus_vdev.a']' returned non-zero exit status 1.
[205/260] Compiling C object lib/librte_vhost.a.p/vhost_vhost_crypto.c.o
ninja: build stopped: subcommand failed.
make[2]: *** [Makefile:180: all] Error 1
make[1]: *** [/vault/extern/spdk/BUILD/Linux-x86_64/spdk/mk/spdk.subdirs.mk:16: dpdkbuild] Error 2
make[1]: Leaving directory '/vault/extern/spdk/BUILD/Linux-x86_64/spdk'
```

## Context (Environment including OS version, SPDK version, etc.)
OS version: Centos 7
SPDK: v23.05

**Comment by mikeBashStuff** [comment]
This seems to relate to c78471cd061a0f64db006c538be34536bc66c12a which should be available in our DPDK submodule. Since this is not clear from the log above, would you kindly share some details on how exactly you are trying to build SPDK? `./configure` cmdline + full output from the build (which include DPDK's version as well) would be appreciated. Visible `prefix` above indicates you are building against the DPDK submodule, but I wonder if it's checked out at a proper version - SPDK v23.05 should have it at 23.03. Info about version of  `meson` would be useful as well.

**Comment by tomzawadzki** [comment]
@divy2950 Have you had a chance to try feedback above from @mikeBashStuff ?

**Comment by jimharris** [comment]
Closing due to no response from submitter.
