### ISSUE TITLE
The deletion of nvmf subsystem triggers two crash issues

### ISSUE THREAD

**Issue by jiewei-ke** [spdk/spdk#3100]
# Sighting report

When running a test to create and delete nvmf subsystems repeatedly, we run into two crash issues shown below. We use ESXi 8.0 as the nvmf hosts to connect subsystems in the meanwhile.

## Expected Behavior

No crash.

### Case 1

When nvmf_ctrlr_cmd_connect finds subsystem is not active, it will start a poller to run retry_connect. But the subsystem may be deleted during the retry interval, and retry_connect should not access the sgroup in this case.

```
(gdb) bt
#0  0x00007fe5660131f7 in raise () from /lib64/libc.so.6
#1  0x00007fe5660148e8 in abort () from /lib64/libc.so.6
#2  0x00007fe56600c266 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007fe56600c312 in __assert_fail () from /lib64/libc.so.6
#4  0x000055e315df4ac5 in retry_connect (arg=0x55e334b00000) at ctrlr.c:972
#5  0x000055e315e4b7d8 in thread_execute_timed_poller (thread=0x55e31931ca80, poller=0x55e334ca8000, now=2392831266483602)
    at thread.c:993
#6  0x000055e315e4baea in thread_poll (thread=0x55e31931ca80, max_msgs=0, now=2392831266483602) at thread.c:1083
#7  0x000055e315e4bb8f in spdk_thread_poll (thread=0x55e31931ca80, max_msgs=0, now=2392831266483602) at thread.c:1109
```

### Case 2

In nvmf_ctrlr_process_admin_cmd, we will get the subsystem id from the ctrlr and then decrement the sgroup's mgmt_io_outstanding for AER cases. However, the ctrlr may be null since the host sends admin commands before connect. 

```
(gdb) bt
#0  0x000056499cd3fc4c in nvmf_ctrlr_process_admin_cmd (req=0x5649bb535240) at ctrlr.c:3634
#1  0x000056499cd42195 in spdk_nvmf_request_exec (req=0x5649bb535240) at ctrlr.c:4673
#2  0x000056499cd55fc5 in nvmf_tcp_req_process (ttransport=ttransport@entry=0x5649a07d0fc0, tcp_req=0x5649bb535240) at tcp.c:2921
#3  0x000056499cd57a26 in nvmf_tcp_capsule_cmd_hdr_handle (pdu=0x2010eebfebb8, tqpair=0x5649ba05a700, ttransport=0x5649a07d0fc0)
    at tcp.c:1562
#4  nvmf_tcp_sock_process (tqpair=tqpair@entry=0x5649ba05a700) at tcp.c:2230
#5  0x000056499cd585a9 in nvmf_tcp_sock_cb (arg=0x5649ba05a700, group=<optimized out>, sock=<optimized out>) at tcp.c:3055
#6  0x000056499cd69297 in sock_group_impl_poll_count (max_events=32, group=0x56499f304700, group_impl=0x5649a8f44f50) at sock.c:691
#7  spdk_sock_group_poll_count (group=0x56499f304700, max_events=32) at sock.c:717
#8  0x000056499cd58521 in nvmf_tcp_poll_group_poll (group=0x56499f52fdd0) at tcp.c:3208
#9  0x000056499cd4a76b in nvmf_poll_group_poll (ctx=<optimized out>) at nvmf.c:72
#10 0x000056499cd6dde3 in thread_execute_poller (poller=0x5649b5072000, thread=0x56499f50ca80) at thread.c:932
#11 thread_poll (thread=thread@entry=0x56499f50ca80, max_msgs=max_msgs@entry=0, now=now@entry=2354685127128694) at thread.c:1058
#12 0x000056499cd6eade in spdk_thread_poll (thread=thread@entry=0x56499f50ca80, max_msgs=max_msgs@entry=0, now=2354685127128694,
    now@entry=0) at thread.c:1109
#13 0x000056499c676a56 in zbs::spdk_reactor_run (arg=0x56499f31c840) at ../src/common/spdk.cc:131
#14 0x000056499c6780ca in _spdk_thread_run () at ../src/common/spdk.cc:663
#15 operator() (__closure=<optimized out>) at ../src/common/spdk.cc:700
#16 std::_Function_handler<void(), zbs::zbs_spdk_init()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:316
#17 0x000056499c950657 in operator() (this=0x56499f2c48c8) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:706
#18 zbs::Thread::DoStart (this=this@entry=0x56499f2c4840) at ../src/common/thread.cc:234
#19 0x000056499c950781 in zbs::Thread::StartEntry (obj=0x56499f2c4840) at ../src/common/thread.cc:216
#20 0x00007f89d5569e25 in start_thread () from /lib64/libpthread.so.0
#21 0x00007f89d174934d in clone () from /lib64/libc.so.6

(gdb) p *req->qpair
$3 = {state = SPDK_NVMF_QPAIR_ACTIVE, state_cb = 0x0, state_cb_arg = 0x0, transport = 0x5649a07d0fc0, ctrlr = 0x0,
  group = 0x56499f2e74a0, qid = 0, sq_head = 0, sq_head_max = 0, connect_received = false, disconnect_started = false,
  first_fused_req = 0x0, outstanding = {tqh_first = 0x5649bb535240, tqh_last = 0x5649bb535630}, link = {tqe_next = 0x5649ba0cb500,
    tqe_prev = 0x56499f2e74d0}}

(gdb) p req->cmd->nvme_cmd
$4 = {opc = 12, fuse = 0, rsvd1 = 0, psdt = 1, cid = 31, nsid = 0, rsvd2 = 0, rsvd3 = 0, mptr = 0, dptr = {prp = {prp1 = 0,
```

## Possible Solution

The following patches are out for review:
https://review.spdk.io/gerrit/c/spdk/spdk/+/19434 nvmf: fix nullptr reference in retry_connect
https://review.spdk.io/gerrit/c/spdk/spdk/+/19435 nvmf: check ctrlr at the beginning of nvmf_ctrlr_process_admin_cmd

## Steps to Reproduce

Do some connect and delete subsystems in the meanwhile. Seems using ESXi 8.0 is easier to repro this issue than Linux host.

**Comment by changpe1** [comment]
@jiewei-ke your patches are merged, so closing this issue now.
