### ISSUE TITLE
Memory leaks when using rpc construct_virtio_pci_blk_bdev

### ISSUE THREAD

**Issue by pawelkax** [spdk/spdk#311]
Expected Behavior
No error when killing spdk_tgt

Current Behavior
=================================================================
==28843==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 21 byte(s) in 2 object(s) allocated from:
    #0 0x7f4c8279f602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
    #1 0x6ef838 in spdk_json_strdup /root/spdk_bdev_json/lib/json/json_util.c:86
    #2 0x6f216c in spdk_json_decode_string /root/spdk_bdev_json/lib/json/json_util.c:417
    #3 0x6f174a in spdk_json_decode_object /root/spdk_bdev_json/lib/json/json_util.c:311
    #4 0x518730 in spdk_rpc_create_virtio_pci_blk_bdev /root/spdk_bdev_json/lib/bdev/virtio/bdev_virtio_rpc.c:381
    #5 0x6e0fea in spdk_jsonrpc_handler /root/spdk_bdev_json/lib/rpc/rpc.c:81
    #6 0x6e77c5 in spdk_jsonrpc_server_handle_request /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server_tcp.c:178
    #7 0x6e32a0 in parse_single_request /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server.c:116
    #8 0x6e3ec1 in spdk_jsonrpc_parse_request /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server.c:178
    #9 0x6e8009 in spdk_jsonrpc_server_conn_recv /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server_tcp.c:237
    #10 0x6e994b in spdk_jsonrpc_server_poll /root/spdk_bdev_json/lib/jsonrpc/jsonrpc_server_tcp.c:385
    #11 0x6e1c56 in spdk_rpc_accept /root/spdk_bdev_json/lib/rpc/rpc.c:199
    #12 0x69ecf8 in spdk_rpc_subsystem_poll /root/spdk_bdev_json/lib/event/rpc.c:51
    #13 0x69c5e9 in _spdk_reactor_run /root/spdk_bdev_json/lib/event/reactor.c:492
    #14 0x69d9fd in spdk_reactors_start /root/spdk_bdev_json/lib/event/reactor.c:643
    #15 0x695823 in spdk_app_start /root/spdk_bdev_json/lib/event/app.c:567
    #16 0x407f10 in main /root/spdk_bdev_json/app/spdk_tgt/spdk_tgt.c:121
    #17 0x7f4c6cd0c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
SUMMARY: AddressSanitizer: 21 byte(s) leaked in 2 allocation(s).

Possible Solution
None

Steps to Reproduce
spdk_tgt.conf:
[Global]
[Ioat]
Disable Yes
[Nvme]
HotplugEnable Yes

virtio.conf:
[Global]
NoPci Yes
[Ioat]
Disable Yes

1. Compile spdk with asan enabled
2. Run vm with device virtio-blk-pci and log to vm.
3. ./scripts/gen_nvme.sh >> spdk_tgt.conf
4. ./app/spdk_tgt/spdk_tgt -m 0x1 -p 0 -c spdk_tgt.conf -s 1024 -r /var/tmp/spdk.sock &
spdk_tgt_pid=$!
5. waitforlisten $spdk_tgt /var/tmp/spdk.sock
6. pci_blk=$(lspci | grep 'Inc Virtio block device' | awk '{print $1;}')
7. $rpc_py construct_virtio_pci_blk_bdev 0000:$pci_blk Virtio1
8. kill $spdk_tgt_pid
Context (Environment including OS version, SPDK version, etc.)
Virtual machine with ubuntu 16.4 and two emulated nvme devices (1G, 2G).

**Comment by pawelkax** [comment]
Fixed with patch https://review.gerrithub.io/#/c/spdk/spdk/+/412548/
