### ISSUE TITLE
[nvmf-rdma] When cm event poller and qpair poll group share the same spdk thread, may incur a  deadlock when doing qpair disconnection

### ISSUE THREAD

**Issue by KKRainbow** [spdk/spdk#3118]
# Sighting report

If cm event poller and qpair poll group share the same spdk thread, the entire pthread may encounter a deadlock when disconnect a qpair.

## Expected Behavior

qpair should be destroyed successfully.

## Current Behavior

Trigger a deadlock in cm event thread.
```
#0  0x00007f7c6660e945 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007f7c65edaef3 in rdma_destroy_id () from /lib64/librdmacm.so.1
#2  0x0000560f012d6077 in nvmf_rdma_qpair_destroy (rqpair=0x560f2ccb2640) at rdma.c:949
#3  0x0000560f012d6e3c in nvmf_rdma_close_qpair (qpair=0x560f2ccb2640, cb_fn=0x560f012c1070 <_nvmf_transport_qpair_fini_complete>,
    cb_arg=0x560f6c0694a0) at rdma.c:4308
#4  0x0000560f012b7c58 in nvmf_qpair_request_cleanup (qpair=0x560f2ccb2640) at ctrlr.c:4390
#5  spdk_nvmf_request_free (req=<optimized out>) at ctrlr.c:4405
#6  0x0000560f012b7cbc in nvmf_qpair_free_aer (qpair=qpair@entry=0x560f2ccb2640) at ctrlr.c:3934
#7  0x0000560f012c2b87 in spdk_nvmf_qpair_disconnect (qpair=qpair@entry=0x560f2ccb2640, cb_fn=cb_fn@entry=0x0, ctx=ctx@entry=0x0)
    at nvmf.c:1311
#8  0x0000560f012d04a4 in nvmf_rdma_disconnect (evt=<optimized out>) at rdma.c:3362
#9  0x0000560f012d35cc in nvmf_process_cm_event (transport=0x560f0346a3c0) at rdma.c:3569
#10 nvmf_rdma_accept (ctx=0x560f0346a3c0) at rdma.c:3794
#11 0x0000560f012e44a8 in thread_execute_timed_poller (now=1024579599015709, poller=0x560f2ce31380, thread=0x560f03418380)
    at thread.c:993
#12 thread_poll (thread=thread@entry=0x560f03418380, max_msgs=max_msgs@entry=0, now=now@entry=1024579599015709) at thread.c:1083
#13 0x0000560f012e504e in spdk_thread_poll (thread=thread@entry=0x560f03418380, max_msgs=max_msgs@entry=0, now=1024579599015709,
    now@entry=0) at thread.c:1109
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x0000560f00d55ce6 in zbs::spdk_reactor_run (arg=0x560f03228840) at src/common/spdk.cc:131
#15 0x0000560f00d5735a in zbs::_spdk_thread_run () at src/common/spdk.cc:663
#16 zbs::<lambda()>::operator() (__closure=<optimized out>) at src/common/spdk.cc:700
#17 std::_Function_handler<void(), zbs::zbs_spdk_init()::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:316
#18 0x0000560f00f2b077 in std::function<void ()>::operator()() const (this=0x560f031ce5c8)
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/std_function.h:706
#19 zbs::Thread::DoStart (this=this@entry=0x560f031ce540) at src/common/thread.cc:234
#20 0x0000560f00f2b1a1 in zbs::Thread::StartEntry (obj=0x560f031ce540) at src/common/thread.cc:216
#21 0x00007f7c6660ae25 in start_thread () from /lib64/libpthread.so.0
#22 0x00007f7c625e334d in clone () from /lib64/libc.so.6
```

## Possible Solution

ack the cm event before destroy the cm_id

https://review.spdk.io/gerrit/c/spdk/spdk/+/19682

this patch also fix another minor problem: 

In the scenario where the retry ports are removed by the user while
waiting for a new RDMA device, we should halt the process of rescanning
for new InfiniBand (IB) devices since there will be no retry ports
available. However, it's important to note that if the user attempts
to listen on the same port again, it may fail since the new IB devices
are not yet initialized. To address this, we now perform a complete
device rescan whenever a listen operation fails.

## Steps to Reproduce

1. create a nvme target
2. create a poll group in the same spdk thread with nvme target.
3. connect a nvmf initiator.
4. remove the ib device by echo to sysfs

## Context (Environment including OS version, SPDK version, etc.)

OS: Linux 2d58e537b442 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 x86_64 x86_64 GNU/Linux
SPDK: spdk master

**Comment by AlekseyMarchuk** [comment]
The fix https://review.spdk.io/gerrit/c/spdk/spdk/+/19682 is merged, closing this issue
