### ISSUE TITLE
Memory leak in nvme/reconnect/reconnect.c

### ISSUE THREAD

**Issue by ivanallen** [spdk/spdk#3124]
# Sighting report

```
==1577522==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 624 byte(s) in 13 object(s) allocated from:
    #0 0x7fab775d94e7 in calloc (/lib64/libasan.so.8+0xc04e7)
    #1 0x49eabe in nvme_tcp_ctrlr_connect_qpair /source/spdk/lib/nvme/nvme_tcp.c:2035

Direct leak of 128 byte(s) in 4 object(s) allocated from:
    #0 0x7fab775d94e7 in calloc (/lib64/libasan.so.8+0xc04e7)
    #1 0x426737 in allocate_task src/test/reconnect.c:467
    #2 0x42682a in submit_io src/test/reconnect.c:486
    #3 0x426a96 in work_fn src/test/reconnect.c:513
    #4 0x42b58e in main src/test/reconnect.c:1122
    #5 0x7fab76135e4f in __libc_start_call_main (/lib64/libc.so.6+0x44e4f)

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7fab775d94e7 in calloc (/lib64/libasan.so.8+0xc04e7)
    #1 0x49eabe in nvme_tcp_ctrlr_connect_qpair /source/spdk/lib/nvme/nvme_tcp.c:2035
    #2 0x499882 in nvme_ctrlr_poll_internal /source/spdk/lib/nvme/nvme.c:697
    #3 0x499882 in spdk_nvme_probe_poll_async /source/spdk/lib/nvme/nvme.c:1510

Direct leak of 32 byte(s) in 4 object(s) allocated from:
    #0 0x7fab775d94e7 in calloc (/lib64/libasan.so.8+0xc04e7)
    #1 0x423786 in nvme_init_ns_worker_ctx src/test/reconnect.c:192
    #2 0x426978 in work_fn src/test/reconnect.c:503
    #3 0x42b58e in main src/test/reconnect.c:1122
    #4 0x7fab76135e4f in __libc_start_call_main (/lib64/libc.so.6+0x44e4f)
```

## Current Behavior

^up

```
[2023-09-09 14:50:24.711452] nvme_fabric.c: 596:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command failed, rc -5, trtype:TCP adrfam:IPv4 traddr:127.0.0.1 trsvcid:4422 subnqn:nqn.2016-06.io.spdk:cnode1
[2023-09-09 14:50:24.711515] nvme_fabric.c: 607:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command completed with error: sct 1, sc 130
[2023-09-09 14:50:24.711549] nvme_tcp.c:1993:nvme_tcp_ctrlr_connect_qpair_poll: *ERROR*: Failed to poll NVMe-oF Fabric CONNECT command
[2023-09-09 14:50:24.711620] nvme_tcp.c:1787:nvme_tcp_qpair_process_completions: *ERROR*: Failed to connect tqpair=0x613000001c40
[2023-09-09 14:50:24.711676] nvme_qpair.c: 797:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 2
qpair failed and we were unable to recover it.
[2023-09-09 14:50:24.721390] nvme_fabric.c: 596:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command failed, rc -5, trtype:TCP adrfam:IPv4 traddr:127.0.0.1 trsvcid:4422 subnqn:nqn.2016-06.io.spdk:cnode1
[2023-09-09 14:50:24.721443] nvme_fabric.c: 607:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command completed with error: sct 1, sc 130
[2023-09-09 14:50:24.721487] nvme_tcp.c:1993:nvme_tcp_ctrlr_connect_qpair_poll: *ERROR*: Failed to poll NVMe-oF Fabric CONNECT command
[2023-09-09 14:50:24.721516] nvme_tcp.c:1787:nvme_tcp_qpair_process_completions: *ERROR*: Failed to connect tqpair=0x613000001fc0
[2023-09-09 14:50:24.721609] nvme_qpair.c: 797:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 3
qpair failed and we were unable to recover it.
[2023-09-09 14:50:24.731364] nvme_fabric.c: 596:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command failed, rc -5, trtype:TCP adrfam:IPv4 traddr:127.0.0.1 trsvcid:4422 subnqn:nqn.2016-06.io.spdk:cnode1
[2023-09-09 14:50:24.731414] nvme_fabric.c: 607:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command completed with error: sct 1, sc 130
[2023-09-09 14:50:24.731453] nvme_tcp.c:1993:nvme_tcp_ctrlr_connect_qpair_poll: *ERROR*: Failed to poll NVMe-oF Fabric CONNECT command
[2023-09-09 14:50:24.731482] nvme_tcp.c:1787:nvme_tcp_qpair_process_completions: *ERROR*: Failed to connect tqpair=0x613000002340
[2023-09-09 14:50:24.731539] nvme_qpair.c: 797:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 4
qpair failed and we were unable to recover it.
[2023-09-09 14:50:24.741345] nvme_fabric.c: 596:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command failed, rc -5, trtype:TCP adrfam:IPv4 traddr:127.0.0.1 trsvcid:4422 subnqn:nqn.2016-06.io.spdk:cnode1
[2023-09-09 14:50:24.741406] nvme_fabric.c: 607:nvme_fabric_qpair_connect_poll: *ERROR*: Connect command completed with error: sct 1, sc 130
[2023-09-09 14:50:24.741441] nvme_tcp.c:1993:nvme_tcp_ctrlr_connect_qpair_poll: *ERROR*: Failed to poll NVMe-oF Fabric CONNECT command
[2023-09-09 14:50:24.741475] nvme_tcp.c:1787:nvme_tcp_qpair_process_completions: *ERROR*: Failed to connect tqpair=0x6130000018c0
[2023-09-09 14:50:24.741531] nvme_qpair.c: 797:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 1
[2023-09-09 14:50:24.741640] nvme_qpair.c: 797:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
[2023-09-09 14:50:24.741746] nvme_ctrlr.c:1015:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode1] in failed state.
A controller has encountered a failure and is being reset.
Controller properly reset.
qpair failed and we were unable to recover it.
```

## Steps to Reproduce

1. modify sleep(1) -> sleep(15) in function `nvme/reconnect/reconnect.c:nvme_poll_ctrlrs` to simulate timeout

```c
static void *
nvme_poll_ctrlrs(void *arg)
{
	// ...
		pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, &oldstate);

		/* This is a pthread cancellation point and cannot be removed. */
                - sleep(1);
		+ sleep(15);
	}

	return NULL;
}
```

2. compile reconnect.c with asan

3. start nvmf_tgt target

4. run
```
sudo ./build/linux/x86_64/debug/reconnect -q 1 -o 512 -r "trtype:TCP adrfam:IPv4 traddr:127.0.0.1 trsvcid:4422 subnqn:nqn.2016-06.io.spdk:cnode1" -w read -t 40
```

## Context (Environment including OS version, SPDK version, etc.)

I use this commit

```
commit 186986cf1044eaaf73e1c67ebcf3a7ce2f1376bb
Author: Konrad Sztyber <konrad.sztyber@intel.com>
Date:   Wed Apr 26 12:50:20 2023 +0200

    SPDK 23.01.1

    Signed-off-by: Konrad Sztyber <konrad.sztyber@intel.com>
    Change-Id: I8ccbda96627c2da0ec5797747afad077334f6088
    Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/17782
    Reviewed-by: Jim Harris <james.r.harris@intel.com>
    Reviewed-by: Aleksey Marchuk <alexeymar@nvidia.com>
    Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
```

**Comment by ivanallen** [comment]
I found a similar issue: https://github.com/spdk/spdk/issues/2976

**Comment by ksztyber** [comment]
Hi @ivanallen, there have been several patches fixing memleaks since 23.01 and I don't think all of them were backported to 23.01.x (certainly the one in #2976 wasn't). Can you retest on current master?

**Comment by ivanallen** [comment]
> Hi @ivanallen, there have been several patches fixing memleaks since 23.01 and I don't think all of them were backported to 23.01.x (certainly the one in #2976 wasn't). Can you retest on current master?

Thanks for your reply. I cherry-picked this commit: https://review.spdk.io/gerrit/c/spdk/spdk/+/17718 and it solved the problem.

**Comment by ksztyber** [comment]
Great, thanks for the update. I'll close the issue, since it's already fixed on master.
