### ISSUE TITLE
SPDK iSCSI target crashed while running rpc_config.sh with multiple NVMe devices

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#313]
As the title, I have run spdk/test/iscsi_tgt/rpc_config/rpc_config.sh in the machine which have multiple nvme devices. but the script reported crashing while running the last function, verify_add_nvme_bdev_rpc_methods. This function will construct NVMe bdev twice using every NVMe SSD's PCI address. When constructing NVMe bdev for the second NVMe device, the iscsi target will crash.

## Steps to Reproduce
1. find a machine which have two or more NVMe ssd; 
2.get latest spdk codes and compile it;
3. Run following script:
```
#!/usr/bin/env bash
testdir=$(readlink -f $(dirname $0))
rootdir=$(readlink -f $testdir/../..)
source $rootdir/test/common/autotest_common.sh
if [ ! $(uname -s) = Linux ]; then
        exit 0
fi
source $rootdir/test/iscsi_tgt/common.sh
timing_enter iscsi_tgt
create_veth_interfaces
start_stub "-s 12288 -i 0 -m $ISCSI_TEST_CORE_MASK "
trap "kill_stub; cleanup_veth_interfaces; exit 1" SIGINT SIGTERM EXIT
run_test ./test/iscsi_tgt/rpc_config/rpc_config.sh
trap "cleanup_veth_interfaces; exit 1" SIGINT SIGTERM EXIT
kill_stub
cleanup_veth_interfaces
trap - SIGINT SIGTERM EXIT
timing_exit iscsi_tgt
```
## Expected Behavior
The script finished without error.

## Current Behavior
The script reported coredump.

## Context (Environment including OS version, SPDK version, etc.)
Machine with more than two NVMe SSD.
SPDK commit:
9a9bef0a9aec8d4710823c5879c515304bcc2e29

core dump:
~~~
#0  spdk_mmio_read_4 (addr=<optimized out>) at /home/storage/spdk-latest/include/spdk/mmio.h:87
87              return *addr;
[Current thread is 1 (Thread 0x7ffff7fdcf80 (LWP 23535))]
Missing separate debuginfos, use: dnf debuginfo-install openssl-libs-1.1.0g-1.fc26.x86_64
(gdb) bt
#0  spdk_mmio_read_4 (addr=<optimized out>) at /home/storage/spdk-latest/include/spdk/mmio.h:87
#1  nvme_pcie_ctrlr_get_reg_4 (ctrlr=ctrlr@entry=0x12ffa1d700, offset=offset@entry=28, value=value@entry=0x7fffffffcebc) at nvme_pcie.c:366
#2  0x00000000004216a5 in nvme_transport_ctrlr_get_reg_4 (ctrlr=ctrlr@entry=0x12ffa1d700, offset=offset@entry=28, value=value@entry=0x7fffffffcebc) at nvme_transport.c:128
#3  0x000000000041b4c3 in nvme_ctrlr_get_csts (csts=0x7fffffffcebc, ctrlr=ctrlr@entry=0x12ffa1d700) at nvme_ctrlr.c:54
#4  spdk_nvme_ctrlr_get_regs_csts (ctrlr=ctrlr@entry=0x12ffa1d700) at nvme_ctrlr.c:1852
#5  0x000000000041de67 in _nvme_pcie_hotplug_monitor (cb_ctx=cb_ctx@entry=0x98def0, probe_cb=probe_cb@entry=0x416640 <probe_cb>, remove_cb=0x0) at nvme_pcie.c:299
#6  0x000000000041e115 in nvme_pcie_ctrlr_scan (trid=trid@entry=0x7fffffffda30, cb_ctx=cb_ctx@entry=0x98def0, probe_cb=probe_cb@entry=0x416640 <probe_cb>, remove_cb=remove_cb@entry=0x0,
    direct_connect=direct_connect@entry=false) at nvme_pcie.c:749
#7  0x0000000000421659 in nvme_transport_ctrlr_scan (trid=trid@entry=0x7fffffffda30, cb_ctx=cb_ctx@entry=0x98def0, probe_cb=probe_cb@entry=0x416640 <probe_cb>, remove_cb=remove_cb@entry=0x0,
    direct_connect=direct_connect@entry=false) at nvme_transport.c:98
#8  0x00000000004210eb in spdk_nvme_probe_internal (trid=trid@entry=0x7fffffffda30, cb_ctx=cb_ctx@entry=0x98def0, probe_cb=probe_cb@entry=0x416640 <probe_cb>,
    attach_cb=attach_cb@entry=0x416010 <attach_cb>, remove_cb=remove_cb@entry=0x0, connected_ctrlr=connected_ctrlr@entry=0x0) at nvme.c:531
#9  0x00000000004214c6 in spdk_nvme_probe (trid=trid@entry=0x7fffffffda30, cb_ctx=cb_ctx@entry=0x98def0, probe_cb=probe_cb@entry=0x416640 <probe_cb>,
    attach_cb=attach_cb@entry=0x416010 <attach_cb>, remove_cb=remove_cb@entry=0x0) at nvme.c:599
#10 0x0000000000417486 in spdk_bdev_nvme_create (trid=trid@entry=0x7fffffffda30, base_name=0x8eb520 "Nvme1", names=names@entry=0x7fffffffd630, count=count@entry=0x7fffffffd5f8) at bdev_nvme.c:928
#11 0x00000000004178c7 in spdk_rpc_construct_nvme_bdev (request=0x8eb120, params=<optimized out>) at bdev_nvme_rpc.c:133
#12 0x0000000000448d73 in parse_single_request (values=0x7fffec7f1030, request=0x8eb120) at jsonrpc_server.c:116
#13 spdk_jsonrpc_parse_request (conn=conn@entry=0x7fffec7f1020, json=json@entry=0x7fffec7f5038, size=133) at jsonrpc_server.c:178
#14 0x0000000000449693 in spdk_jsonrpc_server_conn_recv (conn=0x7fffec7f1020) at jsonrpc_server_tcp.c:237
#15 spdk_jsonrpc_server_poll (server=0x7fffec7f1010) at jsonrpc_server_tcp.c:385
#16 0x000000000044cc1c in spdk_rpc_accept () at rpc.c:199
#17 0x0000000000457999 in spdk_rpc_subsystem_poll (arg=<optimized out>) at rpc.c:51
#18 0x000000000045700e in _spdk_reactor_run (arg=0x8eaa00) at reactor.c:492
#19 0x0000000000457468 in spdk_reactors_start () at reactor.c:643
#20 0x0000000000456211 in spdk_app_start (opts=opts@entry=0x7fffffffdf50, start_fn=start_fn@entry=0x406110 <spdk_startup>, arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:567
#21 0x0000000000404e89 in main (argc=5, argv=0x7fffffffe0c8) at iscsi_tgt.c:113
~~~

## Possible Solution

https://review.gerrithub.io/c/spdk/spdk/+/412594

**Comment by liang2yan** [comment]
Patch merged. Just verified with latest codes, this issue can be closed now.
