### ISSUE TITLE
[discovery_remove_ifc.sh] ConnectionResetError, nvmf_tgt crash

### ISSUE THREAD

**Issue by slawekptak** [spdk/spdk#3134]
```
# CI Intermittent Failure
00:17:57.354    15:56:00	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=hxBET
00:17:57.354    15:56:00	-- host/discovery_remove_ifc.sh@29 -- # xargs
00:17:57.355    15:56:00	-- common/autotest_common.sh@22 -- # [[ hxBET == *\x* ]]
00:17:57.355    15:56:00	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:17:57.355    15:56:00	-- common/autotest_common.sh@25 -- # set +x
00:18:00.642  Traceback (most recent call last):
00:18:00.642    File "/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py", line 3538, in <module>
00:18:00.642      call_rpc_func(tmp_args)
00:18:00.642    File "/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py", line 3455, in call_rpc_func
00:18:00.642      args.func(args)
00:18:00.642    File "/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/scripts/rpc.py", line 1171, in bdev_get_bdevs
00:18:00.642      print_dict(rpc.bdev.bdev_get_bdevs(args.client,
00:18:00.642                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:18:00.642    File "/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/python/spdk/rpc/bdev.py", line 1603, in bdev_get_bdevs
00:18:00.642      return client.call('bdev_get_bdevs', params)
00:18:00.642             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:18:00.642    File "/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/python/spdk/rpc/client.py", line 187, in call
00:18:00.642      response = self.recv()
00:18:00.642                 ^^^^^^^^^^^
00:18:00.642    File "/var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/python/spdk/rpc/client.py", line 165, in recv
00:18:00.642      newdata = self.sock.recv(4096)
00:18:00.642                ^^^^^^^^^^^^^^^^^^^^
00:18:00.642  ConnectionResetError: [Errno 104] Connection reset by peer
00:18:00.642    15:56:03	-- common/autotest_common.sh@588 -- # xtrace_enable
00:18:00.642    15:56:03	-- common/autotest_common.sh@589 -- # [[ '' == 0 ]]
00:18:00.642   15:56:03	-- host/discovery_remove_ifc.sh@33 -- # [[ '' != \n\v\m\e\1\n\1 ]]
00:18:00.642   15:56:03	-- host/discovery_remove_ifc.sh@34 -- # sleep 1
00:18:01.209  /var/jenkins/workspace/nvmf-tcp-phy-autotest/spdk/test/nvmf/host/discovery_remove_ifc.sh: line 32: 838609 Aborted                 (core dumped) $SPDK_BIN_DIR/nvmf_tgt -m 0x1 -r $host_sock --wait-for-rpc -L bdev_nvme
00:18:01.209    15:56:04	-- host/discovery_remove_ifc.sh@33 -- # get_bdev_list
00:18:01.209    15:56:04	-- host/discovery_remove_ifc.sh@29 -- # rpc_cmd -s /tmp/host.sock bdev_get_bdevs
00:18:01.209    15:56:04	-- host/discovery_remove_ifc.sh@29 -- # jq -r '.[].name'
00:18:01.209    15:56:04	-- common/autotest_common.sh@561 -- # xtrace_disable
00:18:01.209    15:56:04	-- host/discovery_remove_ifc.sh@29 -- # xargs
00:18:01.210    15:56:04	-- host/discovery_remove_ifc.sh@29 -- # sort
00:18:01.210    15:56:04	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:18:01.210    15:56:04	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=hxBET
00:18:01.210    15:56:04	-- common/autotest_common.sh@22 -- # [[ hxBET == *\x* ]]
00:18:01.210    15:56:04	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:18:01.210    15:56:04	-- common/autotest_common.sh@25 -- # set +x
00:18:01.210   15:56:04	-- host/discovery_remove_ifc.sh@33 -- # [[ '' != \n\v\m\e\1\n\1 ]]
00:18:01.210   15:56:04	-- host/discovery_remove_ifc.sh@34 -- # sleep 1
00:18:02.587    15:56:05	-- host/discovery_remove_ifc.sh@33 -- # get_bdev_list
00:18:02.587    15:56:05	-- host/discovery_remove_ifc.sh@29 -- # rpc_cmd -s /tmp/host.sock bdev_get_bdevs
00:18:02.587    15:56:05	-- common/autotest_common.sh@561 -- # xtrace_disable
00:18:02.587    15:56:05	-- host/discovery_remove_ifc.sh@29 -- # jq -r '.[].name'
00:18:02.587    15:56:05	-- common/autotest_common.sh@20 -- # '[' no '!=' yes ']'
00:18:02.587    15:56:05	-- host/discovery_remove_ifc.sh@29 -- # sort
00:18:02.587    15:56:05	-- common/autotest_common.sh@21 -- # PREV_BASH_OPTS=hxBET
00:18:02.587    15:56:05	-- host/discovery_remove_ifc.sh@29 -- # xargs
00:18:02.587    15:56:05	-- common/autotest_common.sh@22 -- # [[ hxBET == *\x* ]]
00:18:02.587    15:56:05	-- common/autotest_common.sh@23 -- # XTRACE_DISABLED=yes
00:18:02.587    15:56:05	-- common/autotest_common.sh@25 -- # set +x
00:18:02.587   15:56:05	-- host/discovery_remove_ifc.sh@33 -- # [[ '' != \n\v\m\e\1\n\1 ]]
```
## Link to the failed CI build
[https://ci.spdk.io/results/autotest-per-patch/builds/109609/archive/nvmf-tcp-phy-autotest_51393/build.log](https://ci.spdk.io/results/autotest-per-patch/builds/109609/archive/nvmf-tcp-phy-autotest_51393/build.log)

**Comment by sberbz** [comment]
Can not reproduce, and issue occurs only once since Sep 14.
