### ISSUE TITLE
nvmf/rdma.c: SIGSEGV during subsystem deletion

### ISSUE THREAD

**Issue by mhae** [spdk/spdk#3157]
# Sighting report

I've applied the patch series https://review.spdk.io/gerrit/c/spdk/spdk/+/19118/2 on top of 23.01.

I'm seeing a SIGSEGV when the app is stopped under load and subsystems are deleted.

```
#1  0x00007f0d8792a537 in __GI_abort () at abort.c:79
#2  0x000055f37fa6ed27 in el::base::utils::abort (reason="Application has crashed due to [SIGSEGV] signal - [Called el::Helpers::crashAbort(11)]", status=<optimized out>) at external/easyloggingpp/easylogging++.cc:125
#3  el::Helpers::crashAbort (sig=<optimized out>, sourceFile=0x55f37ffa0a41 "", line=0) at external/easyloggingpp/easylogging++.cc:3139
#4  <signal handler called>
#5  nvmf_rdma_fill_wr_sgl (device=device@entry=0x7f0d7c05ffb0, rdma_req=rdma_req@entry=0x20014afe3358, wr=wr@entry=0x0, total_length=16384, rgroup=0x7f0d64011210) at rdma.c:1604
#6  0x000055f37fbad541 in nvmf_rdma_request_fill_iovs_multi_sgl (rdma_req=0x20014afe3358, device=0x7f0d7c05ffb0, rtransport=0x7f0d7c04dbb0) at rdma.c:1922
#7  nvmf_rdma_request_parse_sgl (rdma_req=0x20014afe3358, device=0x7f0d7c05ffb0, rtransport=0x7f0d7c04dbb0) at rdma.c:2052
#8  nvmf_rdma_request_process (rtransport=rtransport@entry=0x7f0d7c04dbb0, rdma_req=0x20014afe3358) at rdma.c:2288
#9  0x000055f37fbaf467 in nvmf_rdma_qpair_process_pending (rtransport=rtransport@entry=0x7f0d7c04dbb0, rqpair=rqpair@entry=0x7f0d7c1c79e0, drain=drain@entry=false) at rdma.c:3160
#10 0x000055f37fbb0418 in nvmf_rdma_poller_poll (rtransport=rtransport@entry=0x7f0d7c04dbb0, rpoller=rpoller@entry=0x7f0d64011290) at rdma.c:4500
#11 0x000055f37fbb08aa in nvmf_rdma_poll_group_poll (group=<optimized out>) at rdma.c:4531
#12 0x000055f37fb9af8c in nvmf_poll_group_poll (ctx=<optimized out>) at nvmf.c:70
#13 0x000055f37fbe64a0 in thread_execute_poller (poller=0x7f0d64000e60, thread=0x7f0d7c0518d0) at thread.c:932
#14 thread_poll (thread=thread@entry=0x7f0d7c0518d0, max_msgs=max_msgs@entry=0, now=now@entry=615321823676757) at thread.c:1058
#15 0x000055f37fbe72b0 in spdk_thread_poll (thread=thread@entry=0x7f0d7c0518d0, max_msgs=max_msgs@entry=0, now=615321823676757) at thread.c:1109
#16 0x000055f37fc0efe1 in _reactor_run (reactor=0x7f0d7c0429c0) at reactor.c:903
#17 reactor_run (arg=0x7f0d7c0429c0) at reactor.c:941
#18 0x000055f37fa73483 in eal_thread_loop.cold ()
#19 0x00007f0d88217ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#20 0x00007f0d87a03a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

The issue is that wr=0x0. I don't understand how this can be... In nvmf_rdma_request_fill_iovs_multi_sgl we're passing  current_wr to nvmf_rdma_fill_wr_sgl. But current_wr points to a struct that is always allocated:

```
	/* The first WR must always be the embedded data WR. This is how we unwind them later. */
	current_wr = &rdma_req->data.wr;
	assert(current_wr != NULL);
```
When I dump the rdma_req, I don't see an issue getting to rdma_req->data.wr. But then current_wr is suddenly 0x0 in the next call.
```
#6  0x000055f37fbad541 in nvmf_rdma_request_fill_iovs_multi_sgl (rdma_req=0x20014afe3358, device=0x7f0d7c05ffb0, rtransport=0x7f0d7c04dbb0) at rdma.c:1922
1922    in rdma.c
(gdb) p rdma_req
$11 = (struct spdk_nvmf_rdma_request *) 0x20014afe3358
(gdb) p *rdma_req
$12 = {req = {qpair = 0x7f0d7c1c79e0, length = 32768, xfer = 1 '\001', data_from_pool = true, dif_enabled = false, data = 0x0, cmd = 0x20012a61f0c0, rsp = 0x20012cc2f910, buf_link = {stqe_next = 0x0},
    timeout_tsc = 0, iovcnt = 2, iov = {{iov_base = 0x20009296c000, iov_len = 131072}, {iov_base = 0x200101c22000, iov_len = 131072}, {iov_base = 0x0, iov_len = 0} <repeats 59 times>}, buffers = {0x20009296b300,
      0x200101c21080, 0x0 <repeats 59 times>}, stripped_data = 0x0, dif = {dif_ctx = {block_size = 0, md_size = 0, md_interleave = false, guard_interval = 0, dif_type = SPDK_DIF_DISABLE, dif_flags = 0,
        init_ref_tag = 0, app_tag = 0, apptag_mask = 0, data_offset = 0, ref_tag_offset = 0, last_guard = 0, guard_seed = 0, remapped_init_ref_tag = 0}, elba_length = 0, orig_length = 0}, bdev_io_wait = {bdev = 0x0,
      cb_fn = 0x0, cb_arg = 0x0, link = {tqe_next = 0x0, tqe_prev = 0x0}}, cmd_cb_fn = 0x0, first_fused_req = 0x0, req_to_abort = 0x0, poller = 0x0, zcopy_bdev_io = 0x0, zcopy_phase = NVMF_ZCOPY_PHASE_NONE, link = {
      tqe_next = 0x0, tqe_prev = 0x7f0d7c1c7a20}}, fused_failed = false, data_wr = {type = 2 '\002'}, rsp_wr = {type = 1 '\001'}, state = 2 '\002', offset = 32768, recv = 0x20012a631f38, rsp = {wr = {
      wr_id = 35189925231098, next = 0x0, sg_list = 0x20014afe3a88, num_sge = 1, opcode = IBV_WR_SEND, send_flags = 2, {imm_data = 0, invalidate_rkey = 0}, wr = {rdma = {remote_addr = 0, rkey = 0}, atomic = {
          remote_addr = 0, compare_add = 0, swap = 0, rkey = 0}, ud = {ah = 0x0, remote_qpn = 0, remote_qkey = 0}}, qp_type = {xrc = {remote_srqn = 0}}, {bind_mw = {mw = 0x0, rkey = 0, bind_info = {mr = 0x0,
            addr = 0, length = 0, mw_access_flags = 0}}, tso = {hdr = 0x0, hdr_sz = 0, mss = 0}}}, sgl = {{addr = 35189418031376, length = 16, lkey = 330872}}}, iovpos = 0, num_outstanding_data_wr = 0,
  num_remaining_data_wr = 0, receive_tsc = 615321823696287, fused_pair = 0x0, state_link = {stqe_next = 0x20014b041f48}, remaining_tranfer_in_wrs = 0x0, transfer_wr = 0x20014afe3ad0, data = {rdma_wr = {
      type = 0 '\000'}, wr = {wr_id = 35189925231097, next = 0x200018afd888, sg_list = 0x20014afe3b50, num_sge = 1, opcode = IBV_WR_RDMA_READ, send_flags = 2, {imm_data = 0, invalidate_rkey = 0}, wr = {rdma = {
          remote_addr = 140643520184320, rkey = 1593088}, atomic = {remote_addr = 140643520184320, compare_add = 1593088, swap = 0, rkey = 0}, ud = {ah = 0x7fea1f0f8000, remote_qpn = 1593088, remote_qkey = 0}},
      qp_type = {xrc = {remote_srqn = 0}}, {bind_mw = {mw = 0x0, rkey = 0, bind_info = {mr = 0x0, addr = 0, length = 0, mw_access_flags = 0}}, tso = {hdr = 0x0, hdr_sz = 0, mss = 0}}}, sgl = {{addr = 35186831441920,
        length = 16384, lkey = 180066}, {addr = 0, length = 0, lkey = 0} <repeats 29 times>}}}
(gdb) p rdma_req->data.wr
$13 = {wr_id = 35189925231097, next = 0x200018afd888, sg_list = 0x20014afe3b50, num_sge = 1, opcode = IBV_WR_RDMA_READ, send_flags = 2, {imm_data = 0, invalidate_rkey = 0}, wr = {rdma = {
      remote_addr = 140643520184320, rkey = 1593088}, atomic = {remote_addr = 140643520184320, compare_add = 1593088, swap = 0, rkey = 0}, ud = {ah = 0x7fea1f0f8000, remote_qpn = 1593088, remote_qkey = 0}},
  qp_type = {xrc = {remote_srqn = 0}}, {bind_mw = {mw = 0x0, rkey = 0, bind_info = {mr = 0x0, addr = 0, length = 0, mw_access_flags = 0}}, tso = {hdr = 0x0, hdr_sz = 0, mss = 0}}}
(gdb) f 5
#5  nvmf_rdma_fill_wr_sgl (device=device@entry=0x7f0d7c05ffb0, rdma_req=rdma_req@entry=0x20014afe3358, wr=wr@entry=0x0, total_length=16384, rgroup=0x7f0d64011210) at rdma.c:1604
1604    in rdma.c
(gdb) p wr
$14 = (struct ibv_send_wr *) 0x0
```

I don't see this issues without the patch series. I think I applied everything but I'll double-check again.

## Expected Behavior

No aborts during graceful shutdown and subsystem deletion.

## Context (Environment including OS version, SPDK version, etc.)

SPDK 23.01, with patch series.

**Comment by AlekseyMarchuk** [comment]
Hi Michael,
There was a fix for this patch series from Konrad https://github.com/spdk/spdk/commit/31beb3ed6428a54a4afec37164249b4e22ceb728
Please check that you applied it

**Comment by mhae** [comment]
@AlekseyMarchuk , I think that fixed it!!! Thanks for pointing me to that fix. I missed it...
