### ISSUE TITLE
vfio long fuzzer (function no 6) hangs or generates core dump when weekend Jenkins job is running

### ISSUE THREAD

**Issue by m-spiewak** [spdk/spdk#3289]
long-fuzz-vfio-phy-autotest wekend jobs fail due to some errors in fuzzing function 6. Two kind of errors were seen:
1) The fuzzer either hangs without any meaningful information in log (see output log from build 87 [https://spdkci.intel.com/job/long-fuzz-vfio-phy-autotest/87/](https://spdkci.intel.com/job/long-fuzz-vfio-phy-autotest/87/) , llvm_vfio_6.txt file in llvm.tar.xz archive):
```
[2024-03-03 06:15:29.355820] vfio_user.c:3097:vfio_user_log: *ERROR*: /tmp/vfio-user-6/domain/1: msg0: cmd 8 failed: Invalid argument
[2024-03-03 06:15:29.355944] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 8 return failure
[2024-03-03 06:15:29.509812] vfio_user.c:3097:vfio_user_log: *ERROR*: /tmp/vfio-user-6/domain/1: msg0: cmd 8 failed: Invalid argument
[2024-03-03 06:15:29.509926] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 8 return failure
```
(and then it is killed by the script couple of hours later due to timeout)

2) The 6th fuzzing function causes core dump (see output log from build 86 [https://spdkci.intel.com/job/long-fuzz-vfio-phy-autotest/86/](https://spdkci.intel.com/job/long-fuzz-vfio-phy-autotest/86/) , llvm_vfio_6.txt file in llvm.tar.xz archive):
```
[2024-03-02 04:34:58.741896] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 8 return failure
[2024-03-02 04:34:58.898683] vfio_user.c:3097:vfio_user_log: *ERROR*: /tmp/vfio-user-6/domain/1: msg0: cmd 8 failed: Invalid argument
[2024-03-02 04:34:58.898795] vfio_user.c: 144:vfio_user_read: *ERROR*: Command 8 return failure
/var/jenkins/workspace/long-fuzz-vfio-phy-autotest/spdk/test/fuzz/llvm/vfio/run.sh: line 21: 3688913 Aborted                 (core dumped) $rootdir/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz -m $core -s $mem_size -P $output_dir/llvm/ -F $vfiouser_dir -c $vfiouser_cfg -t $timen -D $corpus_dir -Y $vfiouser_io_dir -r $fuzzer_dir/spdk$fuzzer_type.sock -Z $fuzzer_type
========== Backtrace start: ==========

in /var/jenkins/workspace/long-fuzz-vfio-phy-autotest/spdk/test/fuzz/llvm/vfio/run.sh:42 -> start_llvm_fuzz(["6"],["59997"],["0x40"])
     ...
   37  		# Adjust paths to allow multiply instance of fuzzer
   38  		sed -e "s%/tmp/vfio-user/domain/1%$vfiouser_dir%;
   39  			s%/tmp/vfio-user/domain/2%$vfiouser_io_dir%" $testdir/fuzz_vfio_json.conf > $vfiouser_cfg
   40  	
   41  		$rootdir/test/app/fuzz/llvm_vfio_fuzz/llvm_vfio_fuzz \
=> 42  			-m $core \
   43  			-s $mem_size \
   44  			-P $output_dir/llvm/ \
   45  			-F $vfiouser_dir \
   46  			-c $vfiouser_cfg \
   47  			-t $timen \
     ...
in /var/jenkins/workspace/long-fuzz-vfio-phy-autotest/spdk/test/fuzz/llvm/vfio/../common.sh:57 -> start_llvm_fuzz_all(["7"],["7"],["60000"])
     ...
   52  		for ((i = 0; i < fuzz_num; i += testn)); do
   53  			idx=-1 pids=()
   54  			# Run max up to $testn tests in parallel ...
   55  			while ((testn_idx = i + ++idx, testn_idx < fuzz_num && idx < testn)); do
   56  				core=$(printf "0x%x" $((0x1 << idx)))
=> 57  				start_llvm_fuzz $testn_idx $timen $core &> >(fuzzer_out_handler "$output_dir/llvm/llvm_${FUZZER}_${testn_idx}.txt") &
   58  				pids+=($!)
   59  			done
   60  			# ... and now wait for them
   61  			for pid in "${pids[@]}"; do
   62  				wait "$pid"
     ...
in /var/jenkins/workspace/long-fuzz-vfio-phy-autotest/spdk/test/fuzz/llvm/vfio/run.sh:74 -> main([])
     ...
   69  	mem_size=0
   70  	if [[ $SPDK_TEST_FUZZER_SHORT -eq 1 ]]; then
   71  		start_llvm_fuzz_short $fuzz_num $TIME
   72  	elif [[ $SPDK_TEST_FUZZER -eq 1 ]]; then
   73  		get_testn $fuzz_num 2048
=> 74  		start_llvm_fuzz_all $TESTN $fuzz_num $TIME
   75  	else
   76  		start_llvm_fuzz $1 $TIME 0x1
   77  	fi
   78  	
   79  	trap - SIGINT SIGTERM EXIT
     ...

========== Backtrace end ==========
```

Creating Github issue to track this.

**Comment by m-spiewak** [comment]
Quick investigation: it seems to be an error in irqs_disable() function, lack of proper sanity checks leading to out-of-boundary table access.
If the backtrace from the core file is correct (please look at https://spdkci.intel.com/job/long-fuzz-vfio-phy-autotest/86/artifact/output/coredumps/llvm_vfio_fuzz_3688913.core.bt.txt/*view*/ ), it seems that irqs_disable caused a fault.
Debug information points to Thread 1:
```
Core was generated by `/var/jenkins/workspace/long-fuzz-vfio-phy-autotest/spdk/test/app/fuzz/llvm_vfio'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa44eb1c884 in __pthread_kill_implementation () from /usr/lib64/libc.so.6
[Current thread is 1 (Thread 0x7fa44e852a40 (LWP 3688913))]

```
Backtrace for thread 1 points to irqs_disable():

```
#11 0x0000000000479577 in ubsan_GetStackTrace(__sanitizer::BufferedStackTrace*, unsigned long, unsigned long, unsigned long, void*, bool) ()
No symbol table info available.
#12 0x0000000000478b36 in __sanitizer::ReportDeadlySignal(__sanitizer::SignalContext const&, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) ()
No symbol table info available.
#13 0x0000000000478e5d in __sanitizer::HandleDeadlySignal(void*, void*, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) ()
No symbol table info available.
#14 <signal handler called>
No symbol table info available.
#15 0x00000000020e8856 in irqs_disable (vfu_ctx=0x603dcb0, index=2, start=284, count=4294967295) at ../../../libvfio-user/lib/irq.c:125
        i = 108685
        efds = 0x6042dcc
#16 0x00000000020e8a26 in handle_device_set_irqs (vfu_ctx=0x603dcb0, msg=0x5ea9390) at ../../../libvfio-user/lib/irq.c:384
        irq_set = 0x6046e90
        data_type = 4
        ret = 0
#17 0x00000000020eaed4 in handle_request (vfu_ctx=0x603dcb0, msg=0x5ea9390) at ../../../libvfio-user/lib/libvfio-user.c:1202
        ret = 0
```
        
Seems that for VFIO_PCI_MSIX_IRQ_INDEX (index == 2), and count == 4294967295 (this is 0xFFFFFFFF) we are doing out of boundary table read at index  i = 108685 in this >>> place (line 125):
```

    for (i = start; i < count; i++) {
>>>        if (efds[i] >= 0) {
            if (close(efds[i]) == -1) {
                vfu_log(vfu_ctx, LOG_DEBUG, "failed to close IRQ fd %d: %m",
                        efds[i]);
            }

            efds[i] = -1;
        }
    }
}
```


We probably need verification if 'i' doesn't go out of table here.
This assert is interesting:
```assert(start + count <= vfu_ctx->irq_count[index]);```
For start == 284, count == 0xFFFFFFFF, I'm not sure if  this works as intended (irq_count is a table of 32-bit integers). And this is an assert, so it is not included in release code.

**Comment by m-spiewak** [comment]
@sberbz If the issue: [https://github.com/nutanix/libvfio-user/issues/790](https://github.com/nutanix/libvfio-user/issues/790) is closed, can we also close this bug?

**Comment by sberbz** [comment]
I'm waiting for https://review.spdk.io/gerrit/c/spdk/spdk/+/22604
