### ISSUE TITLE
[raid/prcess]

### ISSUE THREAD

**Issue by YankunLi** [spdk/spdk#3305]
# Sighting report
Remove the second raid base bdev when raid is in process, spdk proces will crush.

## Expected Behavior
When raid is process for the  first base bdev, remove the second base bdev, the spdk process will crush.

## Possible Solution
Has a patch, fix it https://review.spdk.io/gerrit/c/spdk/spdk/+/22371
## Steps to Reproduce
version 24.01
1. create raid bdev with two base bdev(A and B), it no superblock;
2. remove base bdev A;
3. add new base C bdev to instead of base A;
4. when raid is rebuild, remove base B, the spdk process will crush.

stack:
Core was generated by `./build/bin/nvmf_tgt -r ./sock'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa63f6e8b8f in raise () from /usr/lib64/libc.so.6
[Current thread is 1 (Thread 0x7fa6416049c0 (LWP 3583231))]
Missing separate debuginfos, use: yum debuginfo-install fuse3-libs-3.3.0-15.9.el8.x86_64 glibc-2.28-225.0.3.el8.x86_64 libaio-0.3.112-1.el8.x86_64 libuuid-2.32.1-42.el8_8.x86_64 numactl-libs-2.0.12-13.el8.x86_64 openssl-libs-1.1.1k-9.el8_7.x86_64 zlib-1.2.11-21.el8_7.x86_64
(gdb) bt
#0  0x00007fa63f6e8b8f in raise () from /usr/lib64/libc.so.6
#1  0x00007fa63f6bbea5 in abort () from /usr/lib64/libc.so.6
#2  0x0000000000407c0a in __posix_abort (err=<optimized out>) at thread.c:219
#3  0x0000000000503455 in _bdev_lock_lba_range (bdev=bdev@entry=0x29e2c60, ch=ch@entry=0x0, offset=offset@entry=0, length=length@entry=20480000,
    cb_fn=cb_fn@entry=0x4fb6c0 <bdev_quiesce_range_locked>, cb_arg=cb_arg@entry=0x29d30a0) at bdev.c:9759
#4  0x000000000050363f in _spdk_bdev_quiesce (unquiesce=<optimized out>, cb_arg=0x2794c68, cb_fn=0x4477f0 <raid_bdev_remove_base_bdev_on_quiesced>, length=20480000, offset=0,
    module=<optimized out>, bdev=0x29e2c60) at bdev.c:10035
#5  _spdk_bdev_quiesce (bdev=0x29e2c60, module=<optimized out>, offset=0, length=20480000, cb_fn=0x4477f0 <raid_bdev_remove_base_bdev_on_quiesced>, cb_arg=0x2794c68, unquiesce=false)
    at bdev.c:9984
#6  0x00000000005036e7 in spdk_bdev_quiesce (bdev=<optimized out>, module=module@entry=0x989840 <g_raid_if>, cb_fn=cb_fn@entry=0x4477f0 <raid_bdev_remove_base_bdev_on_quiesced>,
    cb_arg=cb_arg@entry=0x2794c68) at bdev.c:10048
#7  0x0000000000447a8d in raid_bdev_remove_base_bdev_quiesce (base_info=0x2794c68) at bdev_raid.c:1917
#8  _raid_bdev_process_base_bdev_remove_cont (ctx=0x2794c68) at bdev_raid.c:1917
#9  0x000000000051e98e in msg_queue_run_batch (max_msgs=<optimized out>, thread=0x282c870) at thread.c:848
#10 thread_poll (thread=thread@entry=0x282c870, max_msgs=max_msgs@entry=0, now=now@entry=1875792645580526) at thread.c:1070
#11 0x000000000051f13f in spdk_thread_poll (thread=thread@entry=0x282c870, max_msgs=max_msgs@entry=0, now=1875792645580526) at thread.c:1163
#12 0x00000000004f5c29 in _reactor_run (reactor=0x282c300) at reactor.c:914
#13 reactor_run (arg=0x282c300) at reactor.c:952
#14 0x00000000004f6187 in spdk_reactors_start () at reactor.c:1068
#15 0x00000000004f2d9b in spdk_app_start (opts_user=opts_user@entry=0x7ffc521fe6c0, start_fn=start_fn@entry=0x4287b0 <nvmf_tgt_started>, arg1=arg1@entry=0x0) at app.c:866
#16 0x0000000000421b20 in main (argc=3, argv=0x7ffc521fe898) at nvmf_main.c:47

**Comment by YankunLi** [comment]
this patch to fix it https://review.spdk.io/gerrit/c/spdk/spdk/+/22371

**Comment by YankunLi** [comment]
a better patch(https://review.spdk.io/gerrit/c/spdk/spdk/+/22385) solves this problem.
