### ISSUE TITLE
GP5 failure

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3334]
# CI Intermittent Failure

```
08:23:27  Also:   hudson.remoting.ProxyException: hudson.remoting.Channel$CallSiteStackTrace: Remote call to GP5
08:23:27  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1787)
08:23:27  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
08:23:27  		at hudson.remoting.Channel.call(Channel.java:1003)
08:23:27  		at hudson.FilePath.act(FilePath.java:1230)
08:23:27  		at hudson.FilePath.act(FilePath.java:1219)
08:23:27  		at hudson.FilePath.mkdirs(FilePath.java:1410)
08:23:27  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:97)
08:23:27  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:71)
08:23:27  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
08:23:27  		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
08:23:27  		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
08:23:27  		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
08:23:27  		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
08:23:27  		at java.base/java.lang.Thread.run(Thread.java:840)
08:23:27  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 8bbb0c00-22b1-47b0-883d-fa0f69181e41
08:23:27  hudson.remoting.ProxyException: java.nio.file.FileSystemException: /var/jenkins/workspace/autotest-per-patch: Input/output error
08:23:27  	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
08:23:27  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
08:23:27  	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
08:23:27  	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389)
08:23:27  	at java.base/java.nio.file.Files.createDirectory(Files.java:690)
08:23:27  	at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:797)
08:23:27  	at java.base/java.nio.file.Files.createDirectories(Files.java:783)
08:23:27  	at hudson.FilePath.mkdirs(FilePath.java:3756)
08:23:27  	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1420)
08:23:27  	at hudson.FilePath$Mkdirs.invoke(FilePath.java:1415)
08:23:27  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3616)
08:23:27  	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
08:23:27  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
08:23:27  	at hudson.remoting.Request$2.run(Request.java:377)
08:23:27  	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
08:23:27  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
08:23:27  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
08:23:27  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
08:23:27  	at java.base/java.lang.Thread.run(Thread.java:829)
08:23:27  Finished: FAILURE
```
Backup node was brought online to mitigate this, CI should be working fine for now.

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_119747.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_119748.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @AlekseyMarchuk. log: https://ci.spdk.io/public_build/autotest-per-patch_119749.html

**Comment by mikeBashStuff** [comment]
Node was recovered last week so closing.
