### ISSUE TITLE
[sma_vhost] Failed to delete vhost device

### ISSUE THREAD

**Issue by m-spiewak** [spdk/spdk#3390]
# CI Intermittent Failure

sma_vhost test fails during device duplication test. The device can not be deleted:
```
00:23:26.091  ERROR:root:QMP: Failed to delete device
00:23:26.091  [2024-05-27 13:37:57.784132] rte_vhost_user.c:1866:vhost_user_dev_unregister: *ERROR*: Controller sma-0 has still valid connection.
00:23:26.091  ERROR:root:Failed to delete controller

```

## Link to the failed CI build

[https://ci.spdk.io/public_build/autotest-per-patch_123652.html](https://ci.spdk.io/public_build/autotest-per-patch_123652.html)

## Execution failed at
```
00:23:16.126   13:37:49 sma.sma_vhost -- sma/vhost_blk.sh@135 -- # delete_device virtio_blk:sma-0
00:23:16.126   13:37:49 sma.sma_vhost -- sma/vhost_blk.sh@37 -- # /var/jenkins/workspace/vfio-user-phy-autotest/spdk/scripts/sma-client.py
00:23:26.091  ERROR:root:QMP: Failed to delete device
00:23:26.091  [2024-05-27 13:37:57.784132] rte_vhost_user.c:1866:vhost_user_dev_unregister: *ERROR*: Controller sma-0 has still valid connection.
00:23:26.091  ERROR:root:Failed to delete controller
00:23:26.091  Traceback (most recent call last):
00:23:26.091    File "/var/jenkins/workspace/vfio-user-phy-autotest/spdk/scripts/sma-client.py", line 74, in <module>
00:23:26.091      main(sys.argv[1:])
00:23:26.091    File "/var/jenkins/workspace/vfio-user-phy-autotest/spdk/scripts/sma-client.py", line 69, in main
00:23:26.091      result = client.call(request['method'], request.get('params', {}))
00:23:26.091               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:23:26.091    File "/var/jenkins/workspace/vfio-user-phy-autotest/spdk/scripts/sma-client.py", line 43, in call
00:23:26.091      response = func(request=json_format.ParseDict(params, input()))
00:23:26.091                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:23:26.091    File "/usr/local/lib64/python3.11/site-packages/grpc/_channel.py", line 1160, in __call__
00:23:26.091      return _end_unary_response_blocking(state, call, False, None)
00:23:26.091             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:23:26.091    File "/usr/local/lib64/python3.11/site-packages/grpc/_channel.py", line 1003, in _end_unary_response_blocking
00:23:26.091      raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
00:23:26.091      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:23:26.092  grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
00:23:26.092  	status = StatusCode.INTERNAL
00:23:26.092  	details = "Failed to delete vhost device"
00:23:26.092  	debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:8080 {grpc_message:"Failed to delete vhost device", grpc_status:13, created_time:"2024-05-27T13:37:57.788868498+02:00"}"
00:23:26.092  >
00:23:26.092    13:37:57 sma.sma_vhost -- sma/vhost_blk.sh@37 -- # trap - ERR
00:23:26.092    13:37:57 sma.sma_vhost -- sma/vhost_blk.sh@37 -- # print_backtrace
00:23:26.092    13:37:57 sma.sma_vhost -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
00:23:26.092    13:37:57 sma.sma_vhost -- common/autotest_common.sh@1151 -- # args=('virtio_blk:sma-0')
00:23:26.092    13:37:57 sma.sma_vhost -- common/autotest_common.sh@1151 -- # local args
00:23:26.092    13:37:57 sma.sma_vhost -- common/autotest_common.sh@1153 -- # xtrace_disable
00:23:26.092    13:37:57 sma.sma_vhost -- common/autotest_common.sh@10 -- # set +x
00:23:26.092  ========== Backtrace start: ==========
00:23:26.092  
00:23:26.092  in /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/sma/vhost_blk.sh:37 -> delete_device(["virtio_blk:sma-0"])
00:23:26.092       ...
00:23:26.092     32  			}
00:23:26.092     33  		CREATE
00:23:26.092     34  	}
00:23:26.092     35  	
00:23:26.092     36  	function delete_device() {
00:23:26.092  => 37  		"$rootdir/scripts/sma-client.py" <<- DELETE
00:23:26.092     38  			{
00:23:26.092     39  			  "method": "DeleteDevice",
00:23:26.092     40  			  "params": {
00:23:26.092     41  			    "handle": "$1"
00:23:26.092     42  			  }
00:23:26.092       ...
00:23:26.092  in /var/jenkins/workspace/vfio-user-phy-autotest/spdk/test/sma/vhost_blk.sh:135 -> main([])
00:23:26.092       ...
00:23:26.092     130 	[[ $(rpc_cmd vhost_get_controllers | jq -r '. | length') -eq 2 ]]
00:23:26.092     131 	[[ "$tmp0" == "$devid0" ]]
00:23:26.092     132 	[[ "$tmp1" == "$devid1" ]]
00:23:26.092     133 	
00:23:26.092     134 	# Now delete both of them verifying via RPC
00:23:26.092  => 135 	delete_device "$devid0"
00:23:26.092     136 	NOT rpc_cmd vhost_get_controllers -n sma-0
00:23:26.092     137 	[[ $(rpc_cmd vhost_get_controllers | jq -r '. | length') -eq 1 ]]
00:23:26.092     138 	
00:23:26.092     139 	delete_device "$devid1"
00:23:26.092     140 	NOT rpc_cmd vhost_get_controllers -n sma-1
00:23:26.092       ...
00:23:26.092  
00:23:26.092  ========== Backtrace end ==========```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_124001.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_124193.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_124508.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_125082.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_124800.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_125297.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_125372.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_125455.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_125399.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_125539.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jkalwas. log: https://ci.spdk.io/public_build/autotest-per-patch_125588.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_126060.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_126155.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-master-vs-dpdk-v23.11_616.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @shuhei-matsumoto. log: https://ci.spdk.io/public_build/autotest-per-patch_126521.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_126636.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_126624.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-nightly_3908.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_127299.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @anton-nayshtut. log: https://ci.spdk.io/public_build/autotest-per-patch_127271.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_127315.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_127444.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @ksztyber. log: https://ci.spdk.io/public_build/autotest-per-patch_126602.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_128206.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @spdkci / Known Issue Detector. log: https://ci.spdk.io/public_build/autotest-spdk-v24.05-vs-dpdk-v22.11_196.html

**Comment by tomzawadzki** [comment]
This issue was initially reported as an intermittent failure, but has not been observed in the new SPDK-CI system. If this issue reoccurs or if clear reproduction steps can be provided that qualify it as a 'bug', please feel free to reopen it.
