### ISSUE TITLE
spdk_nvme_perf stuck

### ISSUE THREAD

**Issue by ivanallen** [spdk/spdk#3393]
# Sighting report

spdk_nvme_perf stuck

```
/usr/spdk/bin/spdk_nvme_perf -r 'trtype:RDMA adrfam:IPv4 traddr:10.3.21.169 trsvcid:17602 subnqn:nqn.2023-09.io.spdk:blockclient' -o 4096 -w randread -q 8 -t 10
Initializing NVMe Controllers
^C^C^C^C^C
^C^\Quit (core dumped)
```

## Expected Behavior

spdk_nvme_perf do work.

## Current Behavior

```
[root@node-169 /]# /usr/spdk/bin/spdk_nvme_perf -r 'trtype:RDMA adrfam:IPv4 traddr:10.3.21.169 trsvcid:17602 subnqn:nqn.2023-09.io.spdk:blockclient' -o 4096 -w randread -q 8 -t 10
Initializing NVMe Controllers
^C^C^C^C^C
^C^\Quit (core dumped)
[root@node-169 /]# ll
bash: ll: command not found
[root@node-169 /]# ls /tmp/core-spdk_nvme_perf-548-1717059821
/tmp/core-spdk_nvme_perf-548-1717059821
[root@node-169 /]# /opt/rh/gcc-toolset-12/
enable  root/
[root@node-169 /]# /opt/rh/gcc-toolset-12/
enable  root/
[root@node-169 /]# /opt/rh/gcc-toolset-12/root/
bin/   boot/  dev/   etc/   home/  lib/   lib64/ media/ mnt/   opt/   proc/  root/  run/   sbin/  srv/   sys/   tmp/   usr/   var/
[root@node-169 /]# /opt/rh/gcc-toolset-12/root/bin/gdb
gdb            gdb-add-index
[root@node-169 /]# /opt/rh/gcc-toolset-12/root/bin/gdb
gdb            gdb-add-index
[root@node-169 /]# /opt/rh/gcc-toolset-12/root/bin/gdb /usr/spdk/bin/spdk_nvme_perf /tmp/core-spdk_nvme_perf-548-1717059821
GNU gdb (GDB) Red Hat Enterprise Linux 11.2-4.el9
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/spdk/bin/spdk_nvme_perf...

warning: Can't open file /opt/afa-bdc/huge/spdk_pid548map_0 (deleted) during file-backed mapping note processing
[New LWP 548]
[New LWP 549]

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.centos.org/
Enable debuginfod for this session? (y or [n]) n
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/spdk/bin/spdk_nvme_perf -r trtype:RDMA adrfam:IPv4 traddr:[10.3.21.169](http://10.3.21.169/) trsv'.
Program terminated with signal SIGQUIT, Quit.
#0  nvme_transport_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_transport.c:610
610     nvme_transport.c: No such file or directory.
[Current thread is 1 (Thread 0x7fab2a8f49c0 (LWP 548))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-100.el9.x86_64 libaio-0.3.111-13.el9.x86_64 libgcc-11.3.1-2.1.el9.x86_64 libibverbs-48.0-1.el9.x86_64 libnl3-3.9.0-1.el9.x86_64 librdmacm-48.0-1.el9.x86_64 libuuid-2.37.4-18.el9.x86_64 numactl-libs-2.0.16-3.el9.x86_64 openssl-libs-3.0.1-43.el9_0.x86_64 zlib-1.2.11-35.el9_1.x86_64
(gdb) bt
#0  nvme_transport_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_transport.c:610
#1  0x0000000000439fb5 in spdk_nvme_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_qpair.c:799
#2  0x000000000043b8e5 in nvme_wait_for_completion_robust_lock_timeout_poll (qpair=0x2000003d7080, status=0x1683920, robust_mutex=0x0) at nvme.c:254
#3  0x000000000042b567 in nvme_fabric_qpair_connect_poll (qpair=0x2000003d7080) at nvme_fabric.c:593
#4  0x0000000000458f58 in nvme_rdma_ctrlr_connect_qpair_poll (ctrlr=0x2000003d8340, qpair=0x2000003d7080) at nvme_rdma.c:1403
#5  0x000000000045c810 in nvme_rdma_qpair_process_completions (qpair=0x2000003d7080, max_completions=31) at nvme_rdma.c:2738
#6  0x0000000000440bc0 in nvme_transport_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_transport.c:616
#7  0x0000000000439fb5 in spdk_nvme_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_qpair.c:799
#8  0x00000000004259e9 in nvme_ctrlr_process_init (ctrlr=0x2000003d8340) at nvme_ctrlr.c:3845
#9  0x000000000043c64b in nvme_ctrlr_poll_internal (ctrlr=0x2000003d8340, probe_ctx=0x1683df0) at nvme.c:703
#10 0x000000000043ead8 in spdk_nvme_probe_poll_async (probe_ctx=0x1683df0) at nvme.c:1517
#11 0x000000000043c90b in nvme_init_controllers (probe_ctx=0x1683df0) at nvme.c:753
#12 0x000000000043ce78 in spdk_nvme_probe (trid=0x1672890, cb_ctx=0x1672890, probe_cb=0x4106d4 <probe_cb>, attach_cb=0x41083e <attach_cb>, remove_cb=0x0) at nvme.c:906
#13 0x00000000004109be in register_controllers () at perf.c:3021
#14 0x000000000041111c in main (argc=11, argv=0x7ffce83d2218) at perf.c:3254
(gdb)
```

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)

```
[root@node-169 /]# uname -a
Linux node-169 5.14.0-162.nos.4.el8.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 24 07:51:00 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
spdk based on commit a771524779ceac7bdae7b15058404b9cc7320085

```
commit a771524779ceac7bdae7b15058404b9cc7320085 (origin/master, origin/XS, origin/HEAD)
Author: Michal Berger <michal.berger@intel.com>
Date:   Tue Mar 5 10:18:37 2024 +0100

    autopackage: Slurp spdk-ld-path while building against native DPDK

    This is created by the autobuild's build_native_dpdk() and used
    during vs-dpdk tests.

    Change-Id: I1bc0f240a6b9f49b4649fdbcd2e5ed6870b251c1
    Signed-off-by: Michal Berger <michal.berger@intel.com>
    Reviewed-on: https://review.spdk.io/gerrit/c/spdk/spdk/+/22126
    Tested-by: SPDK CI Jenkins <sys_sgci@intel.com>
    Reviewed-by: Tomasz Zawadzki <tomasz.zawadzki@intel.com>
    Reviewed-by: Konrad Sztyber <konrad.sztyber@intel.com>
    Reviewed-by: Karol Latecki <karol.latecki@intel.com>
```

## more info

coredump

```
(gdb) bt
#0  nvme_transport_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_transport.c:610
#1  0x0000000000439fb5 in spdk_nvme_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_qpair.c:799
#2  0x000000000043b8e5 in nvme_wait_for_completion_robust_lock_timeout_poll (qpair=0x2000003d7080, status=0x1683920, robust_mutex=0x0) at nvme.c:254
#3  0x000000000042b567 in nvme_fabric_qpair_connect_poll (qpair=0x2000003d7080) at nvme_fabric.c:593
#4  0x0000000000458f58 in nvme_rdma_ctrlr_connect_qpair_poll (ctrlr=0x2000003d8340, qpair=0x2000003d7080) at nvme_rdma.c:1403
#5  0x000000000045c810 in nvme_rdma_qpair_process_completions (qpair=0x2000003d7080, max_completions=31) at nvme_rdma.c:2738
#6  0x0000000000440bc0 in nvme_transport_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_transport.c:616
#7  0x0000000000439fb5 in spdk_nvme_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_qpair.c:799
#8  0x00000000004259e9 in nvme_ctrlr_process_init (ctrlr=0x2000003d8340) at nvme_ctrlr.c:3845
#9  0x000000000043c64b in nvme_ctrlr_poll_internal (ctrlr=0x2000003d8340, probe_ctx=0x1683df0) at nvme.c:703
#10 0x000000000043ead8 in spdk_nvme_probe_poll_async (probe_ctx=0x1683df0) at nvme.c:1517
#11 0x000000000043c90b in nvme_init_controllers (probe_ctx=0x1683df0) at nvme.c:753
#12 0x000000000043ce78 in spdk_nvme_probe (trid=0x1672890, cb_ctx=0x1672890, probe_cb=0x4106d4 <probe_cb>, attach_cb=0x41083e <attach_cb>, remove_cb=0x0) at nvme.c:906
#13 0x00000000004109be in register_controllers () at perf.c:3021
#14 0x000000000041111c in main (argc=11, argv=0x7ffce83d2218) at perf.c:3254
(gdb) info locals
transport = 0x2000003d7080
__PRETTY_FUNCTION__ = "nvme_transport_qpair_process_completions"
(gdb) p transport[0]
$1 = {ops = {name = '\000' <repeats 32 times>, type = 0, ctrlr_construct = 0x0, ctrlr_scan = 0x0, ctrlr_destruct = 0x0, ctrlr_enable = 0x0, ctrlr_set_reg_4 = 0x0, ctrlr_set_reg_8 = 0x0, ctrlr_get_reg_4 = 0x0, ctrlr_get_reg_8 = 0x0,
    ctrlr_set_reg_4_async = 0x0, ctrlr_set_reg_8_async = 0x0, ctrlr_get_reg_4_async = 0x0, ctrlr_get_reg_8_async = 0x0, ctrlr_get_max_xfer_size = 0x0, ctrlr_get_max_sges = 0x0, ctrlr_reserve_cmb = 0x0, ctrlr_map_cmb = 0x0,
    ctrlr_unmap_cmb = 0x0, ctrlr_enable_pmr = 0x0, ctrlr_disable_pmr = 0x0, ctrlr_map_pmr = 0x0, ctrlr_unmap_pmr = 0x0, ctrlr_create_io_qpair = 0x0, ctrlr_delete_io_qpair = 0x0, ctrlr_connect_qpair = 0x0, ctrlr_disconnect_qpair = 0x0,
    qpair_abort_reqs = 0x0, qpair_reset = 0x0, qpair_submit_request = 0x0, qpair_process_completions = 0x0, qpair_iterate_requests = 0x0, admin_qpair_abort_aers = 0x0, poll_group_create = 0x0, qpair_get_optimal_poll_group = 0x0,
    poll_group_add = 0x0, poll_group_remove = 0x0, poll_group_connect_qpair = 0x0, poll_group_disconnect_qpair = 0x0, poll_group_process_completions = 0x0, poll_group_destroy = 0x0, poll_group_get_stats = 0x0,
    poll_group_free_stats = 0x0, ctrlr_get_memory_domains = 0x0, ctrlr_ready = 0x0, ctrlr_get_registers = 0x0}, link = {tqe_next = 0x0, tqe_prev = 0x0}}
(gdb) set print pretty
(gdb) p transport[0]
$2 = {
  ops = {
    name = '\000' <repeats 32 times>,
    type = 0,
    ctrlr_construct = 0x0,
    ctrlr_scan = 0x0,
    ctrlr_destruct = 0x0,
    ctrlr_enable = 0x0,
    ctrlr_set_reg_4 = 0x0,
    ctrlr_set_reg_8 = 0x0,
    ctrlr_get_reg_4 = 0x0,
    ctrlr_get_reg_8 = 0x0,
    ctrlr_set_reg_4_async = 0x0,
    ctrlr_set_reg_8_async = 0x0,
    ctrlr_get_reg_4_async = 0x0,
    ctrlr_get_reg_8_async = 0x0,
    ctrlr_get_max_xfer_size = 0x0,
    ctrlr_get_max_sges = 0x0,
    ctrlr_reserve_cmb = 0x0,
    ctrlr_map_cmb = 0x0,
    ctrlr_unmap_cmb = 0x0,
    ctrlr_enable_pmr = 0x0,
    ctrlr_disable_pmr = 0x0,
    ctrlr_map_pmr = 0x0,
    ctrlr_unmap_pmr = 0x0,
    ctrlr_create_io_qpair = 0x0,
    ctrlr_delete_io_qpair = 0x0,
    ctrlr_connect_qpair = 0x0,
    ctrlr_disconnect_qpair = 0x0,
    qpair_abort_reqs = 0x0,
    qpair_reset = 0x0,
    qpair_submit_request = 0x0,
    qpair_process_completions = 0x0,
    qpair_iterate_requests = 0x0,
    admin_qpair_abort_aers = 0x0,
    poll_group_create = 0x0,
    qpair_get_optimal_poll_group = 0x0,
    poll_group_add = 0x0,
    poll_group_remove = 0x0,
    poll_group_connect_qpair = 0x0,
    poll_group_disconnect_qpair = 0x0,
    poll_group_process_completions = 0x0,
    poll_group_destroy = 0x0,
    poll_group_get_stats = 0x0,
    poll_group_free_stats = 0x0,
    ctrlr_get_memory_domains = 0x0,
    ctrlr_ready = 0x0,
    ctrlr_get_registers = 0x0
  },
  link = {
    tqe_next = 0x0,
    tqe_prev = 0x0
  }
}
(gdb) up
#1  0x0000000000439fb5 in spdk_nvme_qpair_process_completions (qpair=0x2000003d7080, max_completions=0) at nvme_qpair.c:799
799     nvme_qpair.c: No such file or directory.
(gdb) info locals
ret = 0
req = 0x0
tmp = 0xbfbfbfbfbfbfbfbf
__func__ = "spdk_nvme_qpair_process_completions"
(gdb) p qpair
$3 = (struct spdk_nvme_qpair *) 0x2000003d7080
(gdb) p qpair[0]
$4 = {
  ctrlr = 0x0,
  id = 0,
  qprio = 0 '\000',
  state = 0 '\000',
  async = 0 '\000',
  is_new_qpair = 0 '\000',
  abort_dnr = 0 '\000',
  in_completion_context = 0 '\000',
  delete_after_completion_context = 0 '\000',
  no_deletion_notification_needed = 0 '\000',
  last_fuse = 0 '\000',
  transport_failure_reason = 0 '\000',
  last_transport_failure_reason = 0 '\000',
  destroy_in_progress = 0 '\000',
  trtype = 0,
  num_outstanding_reqs = 0,
  reserved_req = 0x0,
  free_req = {
    stqh_first = 0x0,
    stqh_last = 0x0
  },
  queued_req = {
    stqh_first = 0x0,
    stqh_last = 0x0
  },
  poll_group_stailq = {
    stqe_next = 0x0
  },
  err_cmd_head = {
    tqh_first = 0x0,
    tqh_last = 0x0
  },
  err_req_head = {
    stqh_first = 0x0,
    stqh_last = 0x0
  },
  active_proc = 0x0,
  poll_group = 0x0,
  poll_group_tailq_head = 0x0,
  transport = 0x0,
  poll_status = 0x0,
  tailq = {
    tqe_next = 0x0,
    tqe_prev = 0x0
  },
  per_process_tailq = {
    tqe_next = 0x0,
    tqe_prev = 0x0
  },
  aborting_queued_req = {
    stqh_first = 0x0,
    stqh_last = 0x0
  },
  req_buf = 0x0
}
```

log:
```
[root@node-169 /]# /usr/spdk/bin/spdk_nvme_perf -r 'trtype:RDMA adrfam:IPv4 traddr:10.3.21.169 trsvcid:17602 subnqn:nqn.2023-09.io.spdk:blockclient' -o 4096 -w randread -q 8 -t 10 -G
[2024-05-30 17:36:00.251627] Starting SPDK v24.05 git sha1 c534c4b4d / DPDK 23.11.0 initialization...
[2024-05-30 17:36:00.251664] [ DPDK EAL parameters: perf --no-shconf -c 0x1 --no-pci --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --iova-mode=pa --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid655 ]
Initializing NVMe Controllers
[2024-05-30 17:36:00.279390] nvme_ctrlr.c:1478:_nvme_ctrlr_set_state: *DEBUG*: [nqn.2023-09.io.spdk:blockclient] setting state to connect adminq (no timeout)
[2024-05-30 17:36:00.279415] nvme_rdma.c:2261:nvme_rdma_ctrlr_construct: *DEBUG*: successfully initialized the nvmf ctrlr
[2024-05-30 17:36:00.279424] nvme_rdma.c:1291:nvme_rdma_ctrlr_connect_qpair: *DEBUG*: adrfam 1 ai_family 2
[2024-05-30 17:36:00.279428] nvme_rdma.c:1295:nvme_rdma_ctrlr_connect_qpair: *DEBUG*: trsvcid is 17602
[2024-05-30 17:36:00.279452] nvme_ctrlr.c:1478:_nvme_ctrlr_set_state: *DEBUG*: [nqn.2023-09.io.spdk:blockclient] setting state to wait for connect adminq (no timeout)
[2024-05-30 17:36:00.288979] nvme_rdma.c: 510:nvme_rdma_qpair_process_cm_event: *DEBUG*: Requested queue depth 32. Target receive queue depth 32.
[2024-05-30 17:36:00.290171] nvme_rdma.c:1180:nvme_rdma_connect_established: *DEBUG*: rc =0
[2024-05-30 17:36:00.290179] nvme_rdma.c:1185:nvme_rdma_connect_established: *DEBUG*: RDMA requests created
[2024-05-30 17:36:00.290188] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf680 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290194] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf6a8 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290202] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf6d0 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290209] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf6f8 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290215] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf720 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290221] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf748 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290228] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf770 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290234] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf798 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290240] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf7c0 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290246] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf7e8 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290252] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf810 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290259] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf838 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290266] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf860 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290272] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf888 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290279] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf8b0 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290286] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf8d8 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290292] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf900 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290299] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf928 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290305] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf950 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290312] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf978 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290319] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf9a0 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290325] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf9c8 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290332] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cf9f0 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290339] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfa18 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290346] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfa40 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290353] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfa68 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290360] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfa90 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290367] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfab8 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290374] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfae0 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290381] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfb08 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290387] nvme_rdma.c: 968:nvme_rdma_create_rsps: *DEBUG*: local addr 0x2000003cfb30 length 0x10 lkey 0x181326
[2024-05-30 17:36:00.290393] nvme_rdma.c:1199:nvme_rdma_connect_established: *DEBUG*: RDMA responses created
[2024-05-30 17:36:00.290400] nvme_rdma.c:1202:nvme_rdma_connect_established: *DEBUG*: rc =0
[2024-05-30 17:36:00.290407] nvme_rdma.c:1207:nvme_rdma_connect_established: *DEBUG*: RDMA responses submitted
[2024-05-30 17:36:00.290419] nvme_rdma.c:2340:nvme_rdma_qpair_submit_request: *DEBUG*: local addr 0x2000003d03c0 length 0x40 lkey 0x181326
[2024-05-30 17:36:00.290428] nvme_qpair.c: 218:nvme_admin_qpair_print_command: *NOTICE*: FABRIC CONNECT qid:0 cid:0 SGL KEYED DATA BLOCK ADDRESS 0x2000003cf200 len:0x400 key:0x181326
```

**Comment by ivanallen** [comment]
I captured tcp packet. It shows no response capsule for the connect command. I don't know what happed in nvmf target.

![image](https://github.com/spdk/spdk/assets/12481610/02dc78aa-7b98-402c-98ab-206139102237)
