### ISSUE TITLE
Initialization parameters must be an attributes hash, got NilClass nil (ArgumentError)

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3436]
```
00:04:09.019  FORCE_DISTRO=true
00:04:09.019  VAGRANT_BOX_VERSION=
00:04:09.019  EXTRA_VAGRANTFILES=
00:04:09.019  NIC_MODEL=e1000
00:04:09.019  
00:04:09.019  mkdir: created directory '/var/jenkins/workspace/nvmf-tcp-vg-autotest/fedora38-libvirt'
00:04:09.019  /var/jenkins/workspace/nvmf-tcp-vg-autotest/fedora38-libvirt /var/jenkins/workspace/nvmf-tcp-vg-autotest
00:04:12.303  Bringing machine 'default' up with 'libvirt' provider...
00:04:13.674  /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:86:in `new': Initialization parameters must be an attributes hash, got NilClass nil (ArgumentError)
00:04:13.674  	from /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:76:in `block in load'
00:04:13.674  	from /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:76:in `each'
00:04:13.674  	from /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:76:in `load'
00:04:13.674  	from /usr/lib/ruby/vendor_ruby/fog/libvirt/models/compute/volumes.rb:11:in `all'
00:04:13.674  	from /usr/lib/ruby/vendor_ruby/fog/libvirt/models/compute/server.rb:138:in `block in volumes'
00:04:13.674  	from /usr/lib/ruby/vendor_ruby/fog/libvirt/models/compute/server.rb:138:in `map'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/libvirt/models/compute/server.rb:138:in `volumes'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:78:in `block in object_attributes'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:77:in `map'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:77:in `object_attributes'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:63:in `attribute_string'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:53:in `object_string'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:14:in `block in format'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/formatador.rb:92:in `indent'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:41:in `indent'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/formatador.rb:14:in `format'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/core/model.rb:29:in `inspect'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:18:in `inspect'
00:04:13.675  	from /usr/lib/ruby/vendor_ruby/fog/core/collection.rb:18:in `to_s'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:17:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/call.rb:53:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/box_check_outdated.rb:23:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /var/lib/libvirt/images/.vagrant.d/gems/2.7.0/gems/vagrant-sshfs-1.3.7/lib/vagrant-sshfs/action_hostpath_fixup.rb:125:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /var/lib/libvirt/images/.vagrant.d/gems/2.7.0/gems/vagrant-sshfs-1.3.7/lib/vagrant-sshfs/action_hostpath_fixup.rb:102:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in `action_raw'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in `block in action'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/environment.rb:613:in `lock'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `call'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `action'
00:04:13.675  	from /usr/share/rubygems-integration/all/gems/vagrant-2.2.6/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
00:04:13.687  [Pipeline] }
00:04:13.707  [Pipeline] // stage
00:04:13.715  [Pipeline] }
00:04:13.732  [Pipeline] // wrap
00:04:13.739  [Pipeline] }
00:04:13.742  ERROR: script returned exit code 1
00:04:13.742  Setting overall build result to FAILURE
00:04:13.753  [Pipeline] // catchError
00:04:13.765  [Pipeline] stage
00:04:13.768  [Pipeline] { (Epilogue)
00:04:13.785  [Pipeline] sh
00:04:14.062  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:04:14.062  jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: line 9: cd: /var/jenkins/workspace/nvmf-tcp-vg-autotest/output: No such file or directory
00:04:14.070  [Pipeline] }
00:04:14.087  [Pipeline] // stage
00:04:14.092  [Pipeline] }
00:04:14.108  [Pipeline] // node
00:04:14.118  [Pipeline] End of Pipeline
00:04:14.137  ERROR: script returned exit code 1
00:04:14.142  Finished: FAILURE
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: Not Found

**Comment by ksztyber** [comment]
This happened once, three months ago. Closing.
