### ISSUE TITLE
[BlobFS-phy-autotest] java.lang.IllegalArgumentException: Could not instantiate {name=null} for hudson.plugins.git.BranchSpec

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3459]
This issue is specific to the `BlobFS-phy-autotest` job and has been already mitigated. However, some change could have been impacted by it so this issue is meant to serve as a place for submitting potential false positives.

Point of failure:
```
00:00:51.516  [Pipeline] readFile
00:00:51.537  [Pipeline] readFile
00:00:51.561  [Pipeline] checkout
00:00:51.575  [Pipeline] }
00:00:51.600  [Pipeline] // stage
00:00:51.612  [Pipeline] }
00:00:51.638  [Pipeline] // wrap
00:00:51.650  [Pipeline] }
00:00:51.662  java.lang.IllegalArgumentException
00:00:51.662  	at hudson.plugins.git.BranchSpec.setName(BranchSpec.java:47)
00:00:51.662  	at hudson.plugins.git.BranchSpec.<init>(BranchSpec.java:56)
00:00:51.662  Caused: java.lang.reflect.InvocationTargetException
00:00:51.662  	at jdk.internal.reflect.GeneratedConstructorAccessor302.newInstance(Unknown Source)
00:00:51.662  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
00:00:51.662  	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
00:00:51.662  	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:330)
00:00:51.662  Caused: java.lang.IllegalArgumentException: Could not instantiate {name=null} for hudson.plugins.git.BranchSpec
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:474)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerceList(DescribableModel.java:585)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:458)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
00:00:51.662  Caused: java.lang.IllegalArgumentException: Could not instantiate {extensions=[{$class=CloneOption, honorRefspec=true, noTags=false, reference=/var/ci_repos/rocksdb.git, shallow=false}, {$class=SubmoduleOption, disableSubmodules=true, parentCredentials=true, recursiveSubmodules=true, reference=/var/ci_repos/rocksdb.git, threads=8, trackingSubmodules=false}, {$class=RelativeTargetDirectory, relativeTargetDir=rocksdb}], submoduleCfg=[], userRemoteConfigs=[{url=http://review.spdk.io/spdk/rocksdb, credentialsId=00000000-0000-0000-0000-000000000002}], doGenerateSubmoduleConfigurations=false, branches=[{name=null}]} for hudson.plugins.git.GitSCM
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.coerce(DescribableModel.java:474)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.buildArguments(DescribableModel.java:409)
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:329)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:306)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
00:00:51.662  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
00:00:51.662  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
00:00:51.662  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
00:00:51.662  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.LoggingInvoker.methodCall(LoggingInvoker.java:105)
00:00:51.662  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: b190e0d0-8ca8-49eb-a48a-0436d3537013
00:00:51.662  Caused: java.lang.IllegalArgumentException: Could not instantiate {scm={$class=GitSCM, branches=[{name=null}], doGenerateSubmoduleConfigurations=false, extensions=[{$class=CloneOption, honorRefspec=true, noTags=false, reference=/var/ci_repos/rocksdb.git, shallow=false}, {$class=SubmoduleOption, disableSubmodules=true, parentCredentials=true, recursiveSubmodules=true, reference=/var/ci_repos/rocksdb.git, threads=8, trackingSubmodules=false}, {$class=RelativeTargetDirectory, relativeTargetDir=rocksdb}], submoduleCfg=[], userRemoteConfigs=[{url=http://review.spdk.io/spdk/rocksdb, credentialsId=00000000-0000-0000-0000-000000000002}]}} for org.jenkinsci.plugins.workflow.steps.scm.GenericSCMStep
00:00:51.662  	at org.jenkinsci.plugins.structs.describable.DescribableModel.instantiate(DescribableModel.java:334)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:306)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:196)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:124)
00:00:51.662  	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:47)
00:00:51.662  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
00:00:51.662  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
00:00:51.662  	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.LoggingInvoker.methodCall(LoggingInvoker.java:105)
00:00:51.662  	at lib.fetch_repo(lib.groovy:67)
00:00:51.662  	at lib.fetch_rocksdb(lib.groovy:142)
00:00:51.662  	at WorkflowScript.prepare(WorkflowScript:64)
00:00:51.662  	at WorkflowScript.run(WorkflowScript:150)
00:00:51.662  	at ___cps.transform___(Native Method)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:90)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:116)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:85)
00:00:51.662  	at jdk.internal.reflect.GeneratedMethodAccessor227.invoke(Unknown Source)
00:00:51.662  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
00:00:51.662  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
00:00:51.662  	at jdk.internal.reflect.GeneratedMethodAccessor230.invoke(Unknown Source)
00:00:51.662  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
00:00:51.662  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
00:00:51.662  	at jdk.internal.reflect.GeneratedMethodAccessor230.invoke(Unknown Source)
00:00:51.662  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
00:00:51.662  	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
00:00:51.662  	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
00:00:51.662  	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
00:00:51.662  	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
00:00:51.662  	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
00:00:51.662  	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
00:00:51.662  	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:147)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:17)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:49)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:180)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:423)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:331)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:295)
00:00:51.662  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$4(CpsVmExecutorService.java:136)
00:00:51.662  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
00:00:51.662  	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
00:00:51.662  	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
00:00:51.662  	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
00:00:51.663  	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
00:00:51.663  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
00:00:51.663  	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
00:00:51.663  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
00:00:51.663  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
00:00:51.663  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
00:00:51.663  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
00:00:51.663  	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
00:00:51.663  	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
00:00:51.663  	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
00:00:51.663  	at java.base/java.lang.Thread.run(Unknown Source)
00:00:51.663  Setting overall build result to FAILURE
00:00:51.675  [Pipeline] // catchError
00:00:51.684  [Pipeline] stage
00:00:51.685  [Pipeline] { (Epilogue)
00:00:51.699  [Pipeline] catchError
00:00:51.701  [Pipeline] {
00:00:51.713  [Pipeline] echo
00:00:51.715  Cleanup processes
00:00:51.721  [Pipeline] sh
00:00:52.006  + sudo pgrep -af /var/jenkins/workspace/BlobFS-phy-autotest/spdk
00:00:52.006  1606410 sudo pgrep -af /var/jenkins/workspace/BlobFS-phy-autotest/spdk
00:00:52.018  [Pipeline] sh
00:00:52.299  ++ sudo pgrep -af /var/jenkins/workspace/BlobFS-phy-autotest/spdk
00:00:52.299  ++ grep -v 'sudo pgrep'
00:00:52.299  ++ awk '{print $1}'
00:00:52.299  + sudo kill -9
00:00:52.299  + true
00:00:52.323  [Pipeline] sh
00:00:52.648  + jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh
00:00:52.648  jbp/jenkins/jjb-config/jobs/scripts/compress_artifacts.sh: line 9: cd: /var/jenkins/workspace/BlobFS-phy-autotest/output: No such file or directory
00:00:52.660  [Pipeline] }
00:00:52.664  ERROR: script returned exit code 1
00:00:52.682  [Pipeline] // catchError
00:00:52.692  [Pipeline] echo
00:00:52.693  Tests finished with errors. Please check the logs for more info.
00:00:52.697  [Pipeline] echo
00:00:52.699  Execution node will be rebooted.
00:00:52.715  [Pipeline] build
00:00:52.718  Scheduling project: reset-job
00:00:52.734  [Pipeline] sh
00:00:53.016  + logger -p user.info -t JENKINS-CI
00:00:53.026  [Pipeline] }
00:00:53.041  [Pipeline] // stage
00:00:53.047  [Pipeline] }
00:00:53.064  [Pipeline] // node
00:00:53.072  [Pipeline] End of Pipeline
00:00:53.124  Finished: FAILURE
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @KGoreczny. log: https://ci.spdk.io/public_build/autotest-per-patch_127032.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @mikeBashStuff. log: https://ci.spdk.io/public_build/autotest-per-patch_127039.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_127029.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @eugene-kobyak. log: https://ci.spdk.io/public_build/autotest-per-patch_127043.html

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @tomzawadzki. log: https://ci.spdk.io/public_build/autotest-per-patch_127042.html

**Comment by mikeBashStuff** [comment]
It's been couple of days since the fix and this issue was relatively short-lived so I am going to close it now.
