### ISSUE TITLE
[nvmf_llvm_fuzz] libFuzzer: deadly signal

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3466]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-nightly/builds/3934/archive/short-fuzz-phy-autotest_32475/build.log

Started popping in intermittent fashion under nightly, after bump to f39.

```
00:06:32.425  ###### Recommended dictionary. ######
00:06:32.425  "w\241X6\314f6\000" # Uses: 1
00:06:32.425  ###### End of recommended dictionary. ######
00:06:32.425  Done 36 runs in 2 second(s)
00:06:32.425  AddressSanitizer: CHECK failed: sanitizer_thread_arg_retval.cpp:56 "((t)) != (0)" (0x0, 0x0) (tid=1359369)
00:06:32.425      #0 0x4dc885 in __asan::CheckUnwind() asan_rtl.cpp.o
00:06:32.425      #1 0x4f6896 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4f6896) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #2 0x4f2305 in __sanitizer::ThreadArgRetval::BeforeJoin(unsigned long) const (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4f2305) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #3 0x4b7f63 in pthread_join (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4b7f63) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #4 0x556389 in exit_handler /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:827:3
00:06:32.425      #5 0x7fbf29fd2fd5 in __run_exit_handlers (/usr/lib64/libc.so.6+0x40fd5) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #6 0x7fbf29fd311d in exit (/usr/lib64/libc.so.6+0x4111d) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #7 0x2bd4885 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x2bd4885) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #8 0x55616d in start_fuzzer /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:871:8
00:06:32.425      #9 0x4ce7be in asan_thread_start(void*) asan_interceptors.cpp.o
00:06:32.425      #10 0x7fbf2a020896 in start_thread (/usr/lib64/libc.so.6+0x8e896) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #11 0x7fbf2a0a7a5b in __GI___clone3 (/usr/lib64/libc.so.6+0x115a5b) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425  
00:06:32.425  MS: 1 ChangeByte-; base unit: 0672d09428c0a8e07d1f5bf567fe855f611dd8f1
00:06:32.425  
00:06:32.425  
00:06:32.425  artifact_prefix='/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/../output/llvm/'; Test unit written to /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/../output/llvm/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
00:06:32.425  Base64: 
00:06:32.425  ==1359341== ERROR: libFuzzer: deadly signal
00:06:32.425      #0 0x4dd0a5 in __sanitizer_print_stack_trace (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4dd0a5) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #1 0x2c021fc in fuzzer::PrintStackTrace() (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x2c021fc) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #2 0x2be5cf7 in fuzzer::Fuzzer::CrashCallback() (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x2be5cf7) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #3 0x7fbf29fd099f  (/usr/lib64/libc.so.6+0x3e99f) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #4 0x7fbf2a022833 in __pthread_kill_implementation (/usr/lib64/libc.so.6+0x90833) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #5 0x7fbf29fd08ed in gsignal (/usr/lib64/libc.so.6+0x3e8ed) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #6 0x7fbf29fb88fe in abort (/usr/lib64/libc.so.6+0x268fe) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #7 0x4f874a in __sanitizer::Abort() (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4f874a) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #8 0x4f6804 in __sanitizer::Die() (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4f6804) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #9 0x4f689b in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4f689b) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #10 0x4f2305 in __sanitizer::ThreadArgRetval::BeforeJoin(unsigned long) const (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4f2305) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #11 0x4b7f63 in pthread_join (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x4b7f63) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #12 0x556389 in exit_handler /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:827:3
00:06:32.425      #13 0x7fbf29fd2fd5 in __run_exit_handlers (/usr/lib64/libc.so.6+0x40fd5) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #14 0x7fbf29fd311d in exit (/usr/lib64/libc.so.6+0x4111d) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.425      #15 0x2bd4885 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz+0x2bd4885) (BuildId: b9a5b1845fcc04dcdd2a6667a5b99d333fa38d0f)
00:06:32.425      #16 0x55616d in start_fuzzer /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz.c:871:8
00:06:32.425      #17 0x4ce7be in asan_thread_start(void*) asan_interceptors.cpp.o
00:06:32.426      #18 0x7fbf2a020896 in start_thread (/usr/lib64/libc.so.6+0x8e896) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.426      #19 0x7fbf2a0a7a5b in __GI___clone3 (/usr/lib64/libc.so.6+0x115a5b) (BuildId: 0d710e9d9dc10c500b8119c85da75004183618e2)
00:06:32.426  
00:06:32.426  NOTE: libFuzzer has rudimentary signal handlers.
00:06:32.426        Combine libFuzzer with AddressSanitizer or similar for better crash reports.
00:06:32.426  SUMMARY: libFuzzer: deadly signal
00:06:32.426  MS: 1 ChangeByte-; base unit: 0672d09428c0a8e07d1f5bf567fe855f611dd8f1
00:06:32.426  
00:06:32.426  
00:06:32.426  artifact_prefix='/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/../output/llvm/'; Test unit written to /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/../output/llvm/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
00:06:32.426  Base64: 
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- nvmf/run.sh@45 -- # trap - ERR
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- nvmf/run.sh@45 -- # print_backtrace
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1155 -- # args=('0x1' '1' '0' '1' '25')
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1155 -- # local args
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1157 -- # xtrace_disable
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@10 -- # set +x
00:06:32.426  ========== Backtrace start: ==========
00:06:32.426  
00:06:32.426  in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm/nvmf/run.sh:45 -> start_llvm_fuzz(["0"],["1"],["0x1"])
00:06:32.426       ...
00:06:32.426     40  		# Suppress false memory leaks reported by LSan
00:06:32.426     41  		echo "leak:spdk_nvmf_qpair_disconnect" > "$suppress_file"
00:06:32.426     42  		echo "leak:nvmf_ctrlr_create" >> "$suppress_file"
00:06:32.426     43  	
00:06:32.426     44  		$rootdir/test/app/fuzz/llvm_nvme_fuzz/llvm_nvme_fuzz \
00:06:32.426  => 45  			-m $core \
00:06:32.426     46  			-s $mem_size \
00:06:32.426     47  			-P $output_dir/llvm/ \
00:06:32.426     48  			-F "$trid" \
00:06:32.426     49  			-c $nvmf_cfg \
00:06:32.426     50  			-t $timen \
00:06:32.426       ...
00:06:32.426  in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm/nvmf/../common.sh:73 -> start_llvm_fuzz_short(["25"],["1"])
00:06:32.426       ...
00:06:32.426     68  	function start_llvm_fuzz_short() {
00:06:32.426     69  		local fuzz_num=$1
00:06:32.426     70  		local time=$2
00:06:32.426     71  	
00:06:32.426     72  		for ((i = 0; i < fuzz_num; i++)); do
00:06:32.426  => 73  			start_llvm_fuzz $i $time 0x1
00:06:32.426     74  		done
00:06:32.426     75  	}
00:06:32.426       ...
00:06:32.426  in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm/nvmf/run.sh:71 -> main([])
00:06:32.426       ...
00:06:32.426     66  	
00:06:32.426     67  	trap 'cleanup /tmp/llvm_fuzz* /var/tmp/suppress_nvmf_fuzz; exit 1' SIGINT SIGTERM EXIT
00:06:32.426     68  	
00:06:32.426     69  	mem_size=512
00:06:32.426     70  	if [[ $SPDK_TEST_FUZZER_SHORT -eq 1 ]]; then
00:06:32.426  => 71  		start_llvm_fuzz_short $fuzz_num $TIME
00:06:32.426     72  	elif [[ $SPDK_TEST_FUZZER -eq 1 ]]; then
00:06:32.426     73  		get_testn $fuzz_num $mem_size
00:06:32.426     74  		start_llvm_fuzz_all $TESTN $fuzz_num $TIME
00:06:32.426     75  	else
00:06:32.426     76  		start_llvm_fuzz $1 $TIME 0x1
00:06:32.426       ...
00:06:32.426  
00:06:32.426  ========== Backtrace end ==========
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1194 -- # return 0
00:06:32.426   09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- nvmf/run.sh@1 -- # cleanup /var/tmp/suppress_nvmf_fuzz
00:06:32.426   09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- ../common.sh@11 -- # rm -rf /var/tmp/suppress_nvmf_fuzz
00:06:32.426   09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- ../common.sh@13 -- # kill -9
00:06:32.426  kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
00:06:32.426   09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- ../common.sh@13 -- # :
00:06:32.426   09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- nvmf/run.sh@1 -- # exit 1
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1125 -- # trap - ERR
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1125 -- # print_backtrace
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1155 -- # args=('/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm/nvmf/run.sh' 'nvmf_llvm_fuzz')
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1155 -- # local args
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1157 -- # xtrace_disable
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@10 -- # set +x
00:06:32.426  ========== Backtrace start: ==========
00:06:32.426  
00:06:32.426  in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/common/autotest_common.sh:1125 -> run_test(["nvmf_llvm_fuzz"],["/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm/nvmf/run.sh"])
00:06:32.426       ...
00:06:32.426     1120		timing_enter $test_name
00:06:32.426     1121		echo "************************************"
00:06:32.426     1122		echo "START TEST $test_name"
00:06:32.426     1123		echo "************************************"
00:06:32.426     1124		xtrace_restore
00:06:32.426     1125		time "$@"
00:06:32.426     1126		xtrace_disable
00:06:32.426     1127		echo "************************************"
00:06:32.426     1128		echo "END TEST $test_name"
00:06:32.426     1129		echo "************************************"
00:06:32.426     1130		timing_exit $test_name
00:06:32.426       ...
00:06:32.426  in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm.sh:62 -> main([])
00:06:32.426       ...
00:06:32.426     57  		lcov_start
00:06:32.426     58  	fi
00:06:32.426     59  	
00:06:32.426     60  	for fuzzer in "${fuzzers[@]}"; do
00:06:32.426     61  		case "$fuzzer" in
00:06:32.426  => 62  			nvmf) run_test "nvmf_llvm_fuzz" "$testdir/llvm/$fuzzer/run.sh" ;;
00:06:32.426     63  			vfio) run_test "vfio_llvm_fuzz" "$testdir/llvm/$fuzzer/run.sh" ;;
00:06:32.426     64  		esac
00:06:32.426     65  	done
00:06:32.426     66  	
00:06:32.426     67  	if [[ $SPDK_TEST_FUZZER_SHORT -eq 0 ]]; then
00:06:32.426       ...
00:06:32.426  
00:06:32.426  ========== Backtrace end ==========
00:06:32.426    09:59:15 llvm_fuzz.nvmf_llvm_fuzz -- common/autotest_common.sh@1194 -- # return 0
00:06:32.426  
00:06:32.426  real	0m3.234s
00:06:32.426  user	0m4.012s
00:06:32.426  sys	0m0.674s
00:06:32.426    09:59:15 llvm_fuzz -- common/autotest_common.sh@1125 -- # trap - ERR
00:06:32.426    09:59:15 llvm_fuzz -- common/autotest_common.sh@1125 -- # print_backtrace
00:06:32.426    09:59:15 llvm_fuzz -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
00:06:32.426    09:59:15 llvm_fuzz -- common/autotest_common.sh@1155 -- # args=('/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm.sh' 'llvm_fuzz' '/var/jenkins/workspace/short-fuzz-phy-autotest/autorun-spdk.conf')
00:06:32.426    09:59:15 llvm_fuzz -- common/autotest_common.sh@1155 -- # local args
00:06:32.426    09:59:15 llvm_fuzz -- common/autotest_common.sh@1157 -- # xtrace_disable
00:06:32.426    09:59:15 llvm_fuzz -- common/autotest_common.sh@10 -- # set +x
00:06:32.426  ========== Backtrace start: ==========
00:06:32.426  
00:06:32.426  in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/common/autotest_common.sh:1125 -> run_test(["llvm_fuzz"],["/var/jenkins/workspace/short-fuzz-phy-autotest/spdk/test/fuzz/llvm.sh"])
00:06:32.426       ...
00:06:32.426     1120		timing_enter $test_name
00:06:32.426     1121		echo "************************************"
00:06:32.426     1122		echo "START TEST $test_name"
00:06:32.426     1123		echo "************************************"
00:06:32.426     1124		xtrace_restore
00:06:32.426     1125		time "$@"
00:06:32.426     1126		xtrace_disable
00:06:32.426     1127		echo "************************************"
00:06:32.426     1128		echo "END TEST $test_name"
00:06:32.426     1129		echo "************************************"
00:06:32.426     1130		timing_exit $test_name
00:06:32.426       ...
00:06:32.426  in /var/jenkins/workspace/short-fuzz-phy-autotest/spdk/autotest.sh:378 -> main(["/var/jenkins/workspace/short-fuzz-phy-autotest/autorun-spdk.conf"])
00:06:32.426       ...
00:06:32.426     373 		if [[ $SPDK_TEST_SMA -eq 1 ]]; then
00:06:32.426     374 			run_test "sma" $rootdir/test/sma/sma.sh
00:06:32.426     375 		fi
00:06:32.426     376 	
00:06:32.426     377 		if [[ $SPDK_TEST_FUZZER -eq 1 ]]; then
00:06:32.426  => 378 			run_test "llvm_fuzz" $rootdir/test/fuzz/llvm.sh
00:06:32.426     379 		fi
00:06:32.426     380 	fi
00:06:32.426     381 	
00:06:32.426     382 	trap - SIGINT SIGTERM EXIT
00:06:32.426     383 	
00:06:32.426       ...
00:06:32.426  
00:06:32.426  ========== Backtrace end ==========
```

**Comment by sberbz** [comment]
This issue seems to be caused by joining an already joined thread. 

Here is a failing check at line 56:  [sanitizer_thread_arg_retval.cpp](https://github.com/llvm/llvm-project-release-prs/blob/b3a30dc094050d74a3d5d1a1e2406ca648c7d67d/compiler-rt/lib/sanitizer_common/sanitizer_thread_arg_retval.cpp#L4)

This patch should fix this issue: https://review.spdk.io/gerrit/c/spdk/spdk/+/24450
pthread_join is only called in exit_handler, that is called by libfuzzer immediately after the tests ends.

**Comment by sberbz** [comment]
Another possible reason for this error is that asan does not include this thread because it was not created by pthread_create, only pthread_self is used to identify the current thread. Therefore, it may not be added to the list created by ASAN and at the moment of join it is not listed in the same way as if it had already been joined.

https://github.com/llvm/llvm-project/pull/75394/commits/4e031a9d6c67a926abb26fd5d30b655ababfbd4e#diff-c136d4c217da66e94612875ccabeb15eacc19d0dfc2523203151d8b16058fff5

**Comment by sberbz** [comment]
This issue may be caused by incorrect behavior of the LLVM sanitizer, and the option to skip these tests has only recently been added and will probably take some time to be implemented in Fedora.

Therefore, I propose to unblock nightly by disabling ASan for jobs using the LLVM fuzzer until this issue is resolved.
@mikeBashStuff @karlatec @jimharris

**Comment by sberbz** [comment]
> Another possible reason for this error is that asan does not include this thread because it was not created by ~pthread_create, only pthread_self is used to identify the current thread.~ Therefore, it may not be added to the list created by ASAN and at the moment of join it is not listed in the same way as if it had already been joined.
> 
> [llvm/llvm-project@4e031a9#diff-c136d4c217da66e94612875ccabeb15eacc19d0dfc2523203151d8b16058fff5](https://github.com/llvm/llvm-project/commit/4e031a9d6c67a926abb26fd5d30b655ababfbd4e#diff-c136d4c217da66e94612875ccabeb15eacc19d0dfc2523203151d8b16058fff5)

I thought the thread was created by dpdk in a non-standard way, by overloading pthread_create .

**Comment by karlatec** [comment]
@sberbz 

> Therefore, I propose to unblock nightly by disabling ASan for jobs using the LLVM fuzzer until this issue is resolved.

Disabled. Setting a reminder in two weeks to check if we can re-enable.

**Comment by karlatec** [comment]
Reminder obviously didn't kick in because it's  now 3 weeks since my last comment.
From what I understand there's still no fix so keeping ASAN disabled for LLVM Fuzzer tests.
