### ISSUE TITLE
[json_config] Silent core dump while trying to shutdown spdk_tgt

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3481]
# Sighting report

When the test attempts to shutdown the target app via `json_config_test_shutdown_app()` it sends `SIGINT` and then waits until the process dies out. This, however, doesn't check in any way if the application terminated successfully. In fact, the process gets hit with a `SIGSEGV` on its way out and the entire autotest path fails at the very end when the `autotest_cleanup()` checks if there are any cores around.

Point where application crashes:
```
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/json_config.sh@357 -- # '[' 100 -eq 0 ']'
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/json_config.sh@376 -- # json_config_test_shutdown_app target
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@31 -- # local app=target
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@34 -- # [[ -n 22 ]]
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@35 -- # [[ -n 73354 ]]
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@38 -- # kill -SIGINT 73354
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@40 -- # (( i = 0 ))
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:50.915Z]  20:01:50 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:51.482Z]  20:01:51 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:51.482Z]  20:01:51 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:51.482Z]  20:01:51 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:51.482Z]  20:01:51 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:52.050Z]  20:01:51 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:52.050Z]  20:01:51 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:52.050Z]  20:01:51 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:52.050Z]  20:01:51 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:52.307Z]  20:01:52 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:52.307Z]  20:01:52 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:52.307Z]  20:01:52 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:52.307Z]  20:01:52 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:52.875Z]  20:01:52 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:52.875Z]  20:01:52 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:52.875Z]  20:01:52 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:52.875Z]  20:01:52 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:53.455Z]  20:01:53 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:53.455Z]  20:01:53 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:53.455Z]  20:01:53 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:53.455Z]  20:01:53 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:54.027Z]  20:01:53 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:54.027Z]  20:01:53 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:54.027Z]  20:01:53 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:54.027Z]  20:01:53 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:54.595Z]  20:01:54 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:54.595Z]  20:01:54 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:54.595Z]  20:01:54 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:54.595Z]  20:01:54 json_config -- json_config/common.sh@45 -- # sleep 0.5
[2024-08-12T20:01:54.855Z] /home/vagrant/spdk_repo/spdk/test/json_config/common.sh: line 30: 73354 Segmentation fault      (core dumped) $SPDK_BIN_DIR/spdk_tgt ${app_params[$app]} ${app_extra_params} -r ${app_socket[$app]} "$@"
[2024-08-12T20:01:54.855Z]  20:01:54 json_config -- json_config/common.sh@40 -- # (( i++ ))
[2024-08-12T20:01:54.855Z]  20:01:54 json_config -- json_config/common.sh@40 -- # (( i < 30 ))
[2024-08-12T20:01:54.855Z]  20:01:54 json_config -- json_config/common.sh@41 -- # kill -0 73354
[2024-08-12T20:01:54.855Z]  20:01:54 json_config -- json_config/common.sh@42 -- # app_pid["$app"]=
[2024-08-12T20:01:54.855Z]  20:01:54 json_config -- json_config/common.sh@43 -- # break
[2024-08-12T20:01:54.855Z]  20:01:54 json_config -- json_config/common.sh@48 -- # [[ -n '' ]]
[2024-08-12T20:01:54.855Z] SPDK target shutdown done
```
Point of failure:
```
2024-08-12T20:04:25.812Z]  20:04:25  -- spdk/autotest.sh@394 -- # autotest_cleanup
[2024-08-12T20:04:25.812Z]  20:04:25  -- common/autotest_common.sh@1388 -- # local autotest_es=0
[2024-08-12T20:04:25.812Z]  20:04:25  -- common/autotest_common.sh@1389 -- # xtrace_disable
[2024-08-12T20:04:25.812Z]  20:04:25  -- common/autotest_common.sh@10 -- # set +x
[2024-08-12T20:04:25.812Z] ##### CORE BT spdk_tgt_73354.core.bt.txt #####
[2024-08-12T20:04:25.812Z] 
[2024-08-12T20:04:25.812Z] gdb: warning: Couldn't determine a path for the index cache directory.
[2024-08-12T20:04:25.812Z] 
[2024-08-12T20:04:25.812Z] warning: Can't open file /dev/shm/spdk_tgt_trace.pid73354 (deleted) during file-backed mapping note processing
[2024-08-12T20:04:25.812Z] [New LWP 73466]
[2024-08-12T20:04:25.812Z] [New LWP 73354]
[2024-08-12T20:04:25.812Z] [New LWP 73361]
[2024-08-12T20:04:25.812Z] [Thread debugging using libthread_db enabled]
[2024-08-12T20:04:25.812Z] Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[2024-08-12T20:04:25.812Z] Core was generated by `/home/vagrant/spdk_repo/spdk/build/bin/spdk_tgt -m 0x1 -s 1024 -S /var/tmp -r /'.
[2024-08-12T20:04:25.812Z] Program terminated with signal SIGSEGV, Segmentation fault.
[2024-08-12T20:04:25.812Z] #0  fdset_event_dispatch (arg=0x20000b829d00) at ../lib/vhost/fd_man.c:388
[2024-08-12T20:04:25.812Z] 388			if (pfdset->destroy)
[2024-08-12T20:04:25.812Z] [Current thread is 1 (Thread 0x7f1f9c0006c0 (LWP 73466))]
[2024-08-12T20:04:25.812Z] 
[2024-08-12T20:04:25.812Z] Thread 3 (Thread 0x7f1f9e2006c0 (LWP 73361)):
[2024-08-12T20:04:25.813Z] #0  0x00007f1f9f733e62 in epoll_wait () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #1  0x00007f1f9feae884 in eal_intr_handle_interrupts (totalfds=<optimized out>, pfd=<optimized out>) at ../lib/eal/linux/eal_interrupts.c:1077
[2024-08-12T20:04:25.813Z]         events = 0x7f1f9e1feb40
[2024-08-12T20:04:25.813Z]         nfds = <optimized out>
[2024-08-12T20:04:25.813Z]         events = <optimized out>
[2024-08-12T20:04:25.813Z]         nfds = <optimized out>
[2024-08-12T20:04:25.813Z] #2  eal_intr_thread_main (arg=<optimized out>) at ../lib/eal/linux/eal_interrupts.c:1163
[2024-08-12T20:04:25.813Z]         pipe_event = {events = 3, data = {ptr = 0x4, fd = 4, u32 = 4, u64 = 4}}
[2024-08-12T20:04:25.813Z]         src = <optimized out>
[2024-08-12T20:04:25.813Z]         numfds = <optimized out>
[2024-08-12T20:04:25.813Z]         pfd = <optimized out>
[2024-08-12T20:04:25.813Z]         __func__ = "eal_intr_thread_main"
[2024-08-12T20:04:25.813Z] #3  0x00007f1f9feaac4c in thread_start_wrapper (arg=0x7fff8b5ed0f0) at ../lib/eal/unix/rte_thread.c:114
[2024-08-12T20:04:25.813Z]         ctx = 0x7fff8b5ed0f0
[2024-08-12T20:04:25.813Z]         thread_func = 0x7f1f9fe99a40 <control_thread_start>
[2024-08-12T20:04:25.813Z]         thread_args = 0x1f407d0
[2024-08-12T20:04:25.813Z]         ret = 0
[2024-08-12T20:04:25.813Z] #4  0x00007f1f9f6ac897 in start_thread () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #5  0x00007f1f9f733a5c in clone3 () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] 
[2024-08-12T20:04:25.813Z] Thread 2 (Thread 0x7f1f9ef00a00 (LWP 73354)):
[2024-08-12T20:04:25.813Z] #0  0x00007f1f9fd139fb in __do_global_dtors_aux () from /home/vagrant/spdk_repo/dpdk/build/lib/librte_mempool.so.25
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #1  0x00007f1fa1da60f2 in _dl_call_fini (closure_map=closure_map@entry=0x7f1f9fd28560) at dl-call_fini.c:43
[2024-08-12T20:04:25.813Z]         array = 0x7f1f9fd1aca8
[2024-08-12T20:04:25.813Z]         sz = <optimized out>
[2024-08-12T20:04:25.813Z]         map = 0x7f1f9fd28560
[2024-08-12T20:04:25.813Z]         fini_array = <optimized out>
[2024-08-12T20:04:25.813Z]         fini = <optimized out>
[2024-08-12T20:04:25.813Z] #2  0x00007f1fa1daa06e in _dl_fini () at dl-fini.c:114
[2024-08-12T20:04:25.813Z]         l = 0x7f1f9fd28560
[2024-08-12T20:04:25.813Z]         maps = 0x7fff8b5ed540
[2024-08-12T20:04:25.813Z]         i = 118
[2024-08-12T20:04:25.813Z]         l = <optimized out>
[2024-08-12T20:04:25.813Z]         nmaps = <optimized out>
[2024-08-12T20:04:25.813Z]         nloaded = <optimized out>
[2024-08-12T20:04:25.813Z]         ns = 0
[2024-08-12T20:04:25.813Z]         do_audit = 0
[2024-08-12T20:04:25.813Z]         __PRETTY_FUNCTION__ = "_dl_fini"
[2024-08-12T20:04:25.813Z] #3  0x00007f1f9f65efd6 in __run_exit_handlers () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #4  0x00007f1f9f65f11e in exit () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #5  0x00007f1f9f646151 in __libc_start_call_main () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #6  0x00007f1f9f64620b in __libc_start_main_impl () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #7  0x0000000000402355 in _start ()
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] 
[2024-08-12T20:04:25.813Z] Thread 1 (Thread 0x7f1f9c0006c0 (LWP 73466)):
[2024-08-12T20:04:25.813Z] #0  fdset_event_dispatch (arg=0x20000b829d00) at ../lib/vhost/fd_man.c:388
[2024-08-12T20:04:25.813Z]         events = {{events = 17, data = {ptr = 0x225, fd = 549, u32 = 549, u64 = 549}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 522 times>, {events = 0, data = {ptr = 0x7f1f9f6758c8 <__printf_buffer_write+72>, fd = -1620617016, u32 = 2674350280, u64 = 139773795064008}}, {events = 2683054493, data = {ptr = 0x9fec299d00007f1f, fd = 32543, u32 = 32543, u64 = 11523631300820893471}}, {events = 32543, data = {ptr = 0x7f1f9bffd970, fd = -1677731472, u32 = 2617235824, u64 = 139773737949552}}, {events = 0, data = {ptr = 0x9bffd96000000000, fd = 0, u32 = 0, u64 = 11240942201280135168}}, {events = 32543, data = {ptr = 0x7f1f9f67dc0a <__printf_buffer+986>, fd = -1620583414, u32 = 2674383882, u64 = 139773795097610}}, {events = 0, data = {ptr = 0xffffffff00000000, fd = 0, u32 = 0, u64 = 18446744069414584320}}, {events = 4294967295, data = {ptr = 0x7f1f9fec298e, fd = -1611912818, u32 = 2683054478, u64 = 139773803768206}}, {events = 2683054478, data = {ptr = 0x7f1f, fd = 32543, u32 = 32543, u64 = 32543}}, {events = 0, data = {ptr = 0x7500000000, fd = 0, u32 = 0, u64 = 502511173632}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7f1f9bffd928, fd = -1677731544, u32 = 2617235752, u64 = 139773737949480}}, {events = 2617235751, data = {ptr = 0x7f1f, fd = 32543, u32 = 32543, u64 = 32543}}, {events = 0, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 3, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 32, data = {ptr = 0xa00000000, fd = 0, u32 = 0, u64 = 42949672960}}, {events = 0, data = {ptr = 0x9fec299d00000000, fd = 0, u32 = 0, u64 = 11523631300820860928}}, {events = 32543, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x1800000000, fd = 0, u32 = 0, u64 = 103079215104}}, {events = 48, data = {ptr = 0x7f1f9bffdb20, fd = -1677731040, u32 = 2617236256, u64 = 139773737949984}}, {events = 2617236064, data = {ptr = 0x7f1f, fd = 32543, u32 = 32543, u64 = 32543}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 84 times>, {events = 956301312, data = {ptr = 0x99913e9d1d354100, fd = 490029312, u32 = 490029312, u64 = 11065694603946836224}}, {events = 0, data = {ptr = 0x9bffd97000000000, fd = 0, u32 = 0, u64 = 11240942269999611904}}, {events = 32543, data = {ptr = 0x9, fd = 9, u32 = 9, u64 = 9}}, {events = 2683054478, data = {ptr = 0x9fec297500007f1f, fd = 32543, u32 = 32543, u64 = 11523631129022201631}}, {events = 32543, data = {ptr = 0x7fff8b5ec900, fd = -1956722432, u32 = 2338244864, u64 = 140735531632896}}, {events = 2617236016, data = {ptr = 0x9f6a0e8100007f1f, fd = 32543, u32 = 32543, u64 = 11487009746775473951}}, {events = 32543, data = {ptr = 0x7f1f9bffdb20, fd = -1677731040, u32 = 2617236256, u64 = 139773737949984}}, {events = 2617236291, data = {ptr = 0x9bffeb2000007f1f, fd = 32543, u32 = 32543, u64 = 11240961717611560735}}, {events = 32543, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x99913e9d1d354100, fd = 490029312, u32 = 490029312, u64 = 11065694603946836224}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7f1f9bffdb10, fd = -1677731056, u32 = 2617236240, u64 = 139773737949968}}, {events = 2674371686, data = {ptr = 0x3000007f1f, fd = 32543, u32 = 32543, u64 = 206158462751}}, {events = 48, data = {ptr = 0x7f1f9bffdb20, fd = -1677731040, u32 = 2617236256, u64 = 139773737949984}}, {events = 2617236064, data = {ptr = 0x1d35410000007f1f, fd = 32543, u32 = 32543, u64 = 2104659869121412895}}, {events = 2576432797, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x7f1f9fec2975, fd = -1611912843, u32 = 2683054453, u64 = 139773803768181}}, {events = 0, data = {ptr = 0x900000000, fd = 0, u32 = 0, u64 = 38654705664}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 11 times>, {events = 2617236256, data = {ptr = 0x9feb073c00007f1f, fd = 32543, u32 = 32543, u64 = 11523312025837010719}}, {events = 32543, data = {ptr = 0x7665642f7379732f, fd = 1937339183, u32 = 1937339183, u64 = 8531335224086852399}}, {events = 1936024425, data = {ptr = 0x2f6d65747379732f, fd = 1937339183, u32 = 1937339183, u64 = 3417499243072025391}}, {events = 1701080942, data = {ptr = 0x632f3065646f6e2f, fd = 1685024303, u32 = 1685024303, u64 = 7146984345695120943}}, {events = 3765616, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}} <repeats 337 times>, {events = 0, data = {ptr = 0x900000000, fd = 0, u32 = 0, u64 = 38654705664}}, {events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}, {events = 2683148040, data = {ptr = 0xffffffff00007f1f, fd = 32543, u32 = 32543, u64 = 18446744069414616863}}, {events = 0, data = {ptr = 0x2, fd = 2, u32 = 2, u64 = 2}}, {events = 2682886176, data = {ptr = 0x7f1f, fd = 32543, u32 = 32543, u64 = 32543}}, {events = 0, data = {ptr = 0x100000000, fd = 0, u32 = 0, u64 = 4294967296}}, {events = 0, data = {ptr = 0x9bfff4a000000000, fd = 0, u32 = 0, u64 = 11240972162971992064}}, {events = 32543, data = {ptr = 0x7f1f9fed9708 <internal_config+13384>, fd = -1611819256, u32 = 2683148040, u64 = 139773803861768}}, {events = 2682939352, data = {ptr = 0x215f2a000007f1f, fd = 32543, u32 = 32543, u64 = 150292931595501343}}, {events = 0, data = {ptr = 0x7f1f9fc16c40 <fdset_event_dispatch>, fd = -1614713792, u32 = 2680253504, u64 = 139773800967232}}}
[2024-08-12T20:04:25.813Z]         pfdentry = <optimized out>
[2024-08-12T20:04:25.813Z]         i = <optimized out>
[2024-08-12T20:04:25.813Z]         rcb = <optimized out>
[2024-08-12T20:04:25.813Z]         wcb = <optimized out>
[2024-08-12T20:04:25.813Z]         dat = <optimized out>
[2024-08-12T20:04:25.813Z]         fd = <optimized out>
[2024-08-12T20:04:25.813Z]         numfds = <optimized out>
[2024-08-12T20:04:25.813Z]         remove1 = 1
[2024-08-12T20:04:25.813Z]         remove2 = 0
[2024-08-12T20:04:25.813Z]         pfdset = <optimized out>
[2024-08-12T20:04:25.813Z] #1  0x00007f1f9fc16c4e in fdset_event_dispatch (arg=<optimized out>) at ../lib/vhost/fd_man.c:331
[2024-08-12T20:04:25.813Z]         i = <optimized out>
[2024-08-12T20:04:25.813Z]         rcb = <optimized out>
[2024-08-12T20:04:25.813Z]         wcb = <optimized out>
[2024-08-12T20:04:25.813Z]         dat = <optimized out>
[2024-08-12T20:04:25.813Z]         fd = <optimized out>
[2024-08-12T20:04:25.813Z]         numfds = <optimized out>
[2024-08-12T20:04:25.813Z]         remove1 = <optimized out>
[2024-08-12T20:04:25.813Z]         remove2 = <optimized out>
[2024-08-12T20:04:25.813Z]         pfdset = <optimized out>
[2024-08-12T20:04:25.813Z]         events = <optimized out>
[2024-08-12T20:04:25.813Z]         pfdentry = <optimized out>
[2024-08-12T20:04:25.813Z] #2  0x00007f1f9feaac4c in thread_start_wrapper (arg=0x7fff8b5ecb40) at ../lib/eal/unix/rte_thread.c:114
[2024-08-12T20:04:25.813Z]         ctx = 0x7fff8b5ecb40
[2024-08-12T20:04:25.813Z]         thread_func = 0x7f1f9fe99a40 <control_thread_start>
[2024-08-12T20:04:25.813Z]         thread_args = 0x215f2a0
[2024-08-12T20:04:25.813Z]         ret = 0
[2024-08-12T20:04:25.813Z] #3  0x00007f1f9f6ac897 in start_thread () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] #4  0x00007f1f9f733a5c in clone3 () from /usr/lib64/libc.so.6
[2024-08-12T20:04:25.813Z] No symbol table info available.
[2024-08-12T20:04:25.813Z] 
[2024-08-12T20:04:25.813Z] --
[2024-08-12T20:04:27.721Z] INFO: APP EXITING
[2024-08-12T20:04:27.721Z] INFO: killing all VMs
[2024-08-12T20:04:27.721Z] INFO: killing vhost app
[2024-08-12T20:04:27.721Z] INFO: EXIT DONE
[2024-08-12T20:04:27.721Z] 0000:00:03.0 (1af4 1001): Active devices: mount@vda:vda2,mount@vda:vda3,mount@vda:vda5, so not binding PCI dev
[2024-08-12T20:04:27.721Z] Waiting for block devices as requested
[2024-08-12T20:04:27.988Z] 0000:00:11.0 (1b36 0010): uio_pci_generic -> nvme
[2024-08-12T20:04:27.988Z] 0000:00:10.0 (1b36 0010): uio_pci_generic -> nvme
[2024-08-12T20:04:28.925Z] 0000:00:03.0 (1af4 1001): Active devices: mount@vda:vda2,mount@vda:vda3,mount@vda:vda5, so not binding PCI dev
[2024-08-12T20:04:28.925Z] Cleaning
[2024-08-12T20:04:28.925Z] Removing:    /dev/shm/spdk_tgt_trace.pid72802
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid72651
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid72802
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73000
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73081
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73114
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73218
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73236
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73354
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73512
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73702
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73719
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73896
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid73966
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74029
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74118
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74182
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74217
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74253
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74314
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74384
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74820
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74872
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74923
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid74937
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75004
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75018
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75085
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75101
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75152
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75170
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75210
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75228
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75356
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75386
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75461
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75626
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75696
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75754
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid75913
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid76230
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid76264
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid76616
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid76704
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid76737
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid76929
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid76938
[2024-08-12T20:04:28.925Z] Removing:    /var/run/dpdk/spdk_pid77114
[2024-08-12T20:04:28.925Z] Clean
[2024-08-12T20:04:35.508Z]  20:04:34  -- common/autotest_common.sh@1447 -- # return 1
[2024-08-12T20:04:35.508Z]   20:04:34  -- spdk/autotest.sh@394 -- # trap - ERR
[2024-08-12T20:04:35.508Z]   20:04:34  -- spdk/autotest.sh@394 -- # print_backtrace
[2024-08-12T20:04:35.508Z]   20:04:34  -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
[2024-08-12T20:04:35.508Z]   20:04:34  -- common/autotest_common.sh@1151 -- # args=('/home/vagrant/spdk_repo/autorun-spdk.conf')
[2024-08-12T20:04:35.508Z]   20:04:34  -- common/autotest_common.sh@1151 -- # local args
[2024-08-12T20:04:35.508Z]   20:04:34  -- common/autotest_common.sh@1153 -- # xtrace_disable
[2024-08-12T20:04:35.508Z]   20:04:34  -- common/autotest_common.sh@10 -- # set +x
[2024-08-12T20:04:35.508Z] ========== Backtrace start: ==========
[2024-08-12T20:04:35.508Z] 
[2024-08-12T20:04:35.508Z] in /home/vagrant/spdk_repo/spdk/autotest.sh:394 -> main(["/home/vagrant/spdk_repo/autorun-spdk.conf"])
[2024-08-12T20:04:35.508Z]      ...
[2024-08-12T20:04:35.508Z]    389 	fi
[2024-08-12T20:04:35.508Z]    390 	
[2024-08-12T20:04:35.508Z]    391 	trap - SIGINT SIGTERM EXIT
[2024-08-12T20:04:35.508Z]    392 	
[2024-08-12T20:04:35.508Z]    393 	timing_enter post_cleanup
[2024-08-12T20:04:35.508Z] => 394 	autotest_cleanup
[2024-08-12T20:04:35.508Z]    395 	timing_exit post_cleanup
[2024-08-12T20:04:35.508Z]    396 	
[2024-08-12T20:04:35.508Z]    397 	timing_exit autotest
[2024-08-12T20:04:35.508Z]    398 	chmod a+r $output_dir/timing.txt
[2024-08-12T20:04:35.508Z]    399 	
[2024-08-12T20:04:35.508Z]      ...
[2024-08-12T20:04:35.508Z] 
[2024-08-12T20:04:35.508Z] ========== Backtrace end ==========
```

Since the crash happened inside `fdset_event_dispatch()`, maybe it's also related to  https://github.com/spdk/spdk/issues/3455#issuecomment-2277622812 (issue occurred under vs-dpdk-main pipeline).

**Comment by mikeBashStuff** [comment]
https://ci.spdk.io/results/autotest-spdk-master-vs-dpdk-main/builds/3753/archive/vhost-initiator-vg-autotest_85853/index.html

**Comment by ksztyber** [comment]
> Since the crash happened inside fdset_event_dispatch(), maybe it's also related to https://github.com/spdk/spdk/issues/3455#issuecomment-2277622812 (issue occurred under vs-dpdk-main pipeline).

Unfortunately, I don't think these two issues are related. The problem in #3455 was with detaching a PCI device in a secondary process, while the stack trace here points to vhost code. And it does make sense - we're creating vhost controllers in this test. It looks like the segfault happens while the app is shutting down.
