### ISSUE TITLE
[spdkcli_vhost] pexpect timeout

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#3496]
```
00:13:08.245  ************************************
00:13:08.245  START TEST spdkcli_vhost
00:13:08.245  ************************************
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@1121 -- # /var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/vhost.sh
00:13:08.245  * Looking for test storage...
00:13:08.245  * Found test storage at /var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@9 -- # source /var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/common.sh
00:13:08.245    07:16:41 vhost.spdkcli_vhost -- spdkcli/common.sh@6 -- # spdkcli_job=/var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/spdkcli_job.py
00:13:08.245    07:16:41 vhost.spdkcli_vhost -- spdkcli/common.sh@7 -- # spdk_clear_config_py=/var/jenkins/workspace/vhost-phy-autotest/spdk/test/json_config/clear_config.py
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@11 -- # MATCH_FILE=spdkcli_vhost.test
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@12 -- # SPDKCLI_BRANCH=/
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@14 -- # sample_aio=/var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/sample_aio
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@15 -- # sample_aio2=/var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/sample_aio2
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@17 -- # trap cleanup EXIT
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@18 -- # timing_enter run_vhost_tgt
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@720 -- # xtrace_disable
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@10 -- # set +x
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/vhost.sh@19 -- # run_vhost_tgt
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/common.sh@39 -- # vhost_tgt_pid=2257619
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/common.sh@40 -- # waitforlisten 2257619
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- spdkcli/common.sh@38 -- # /var/jenkins/workspace/vhost-phy-autotest/spdk/build/bin/vhost -m 0x3 -p 0
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@827 -- # '[' -z 2257619 ']'
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@831 -- # local rpc_addr=/var/tmp/spdk.sock
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@832 -- # local max_retries=100
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@834 -- # echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
00:13:08.245  Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@836 -- # xtrace_disable
00:13:08.245   07:16:41 vhost.spdkcli_vhost -- common/autotest_common.sh@10 -- # set +x
00:13:08.504  [2024-08-21 07:16:41.293534] Starting SPDK v24.09-pre git sha1 e4d05eb60 / DPDK 24.03.0 initialization...
00:13:08.504  [2024-08-21 07:16:41.293646] [ DPDK EAL parameters: vhost --no-shconf -c 0x3 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=lib.power:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid2257619 ]
00:13:08.504  EAL: No free 2048 kB hugepages reported on node 1
00:13:08.504  [2024-08-21 07:16:41.488248] app.c: 910:spdk_app_start: *NOTICE*: Total cores available: 2
00:13:09.069  [2024-08-21 07:16:41.822203] reactor.c: 941:reactor_run: *NOTICE*: Reactor started on core 0
00:13:09.069  [2024-08-21 07:16:41.822218] reactor.c: 941:reactor_run: *NOTICE*: Reactor started on core 1
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- common/autotest_common.sh@856 -- # (( i == 0 ))
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- common/autotest_common.sh@860 -- # return 0
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- spdkcli/vhost.sh@20 -- # timing_exit run_vhost_tgt
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- common/autotest_common.sh@726 -- # xtrace_disable
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- common/autotest_common.sh@10 -- # set +x
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- spdkcli/vhost.sh@22 -- # timing_enter spdkcli_create_bdevs_config
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- common/autotest_common.sh@720 -- # xtrace_disable
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- common/autotest_common.sh@10 -- # set +x
00:13:09.327   07:16:42 vhost.spdkcli_vhost -- spdkcli/vhost.sh@33 -- # /var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/spdkcli_job.py ''\''/bdevs/malloc create 40 512 Malloc0'\'' '\''Malloc0'\'' True
00:13:09.327  '\''/bdevs/malloc create 32 512 Malloc1'\'' '\''Malloc1'\'' True
00:13:09.327  '\''/bdevs/malloc create 32 512 Malloc2'\'' '\''Malloc2'\'' True
00:13:09.327  '\''/bdevs/malloc create 32 4096 Malloc3'\'' '\''Malloc3'\'' True
00:13:09.327  '\''/bdevs/malloc create 32 4096 Malloc4'\'' '\''Malloc4'\'' True
00:13:09.327  '\''/bdevs/malloc create 32 4096 Malloc5'\'' '\''Malloc5'\'' True
00:13:09.327  '\''/bdevs/error create Malloc1'\'' '\''EE_Malloc1'\'' True
00:13:09.327  '\''/bdevs/error create Malloc4'\'' '\''EE_Malloc4'\'' True
00:13:09.327  '\''/bdevs/null create null_bdev0 32 512'\'' '\''null_bdev0'\'' True
00:13:09.327  '\''/bdevs/null create null_bdev1 32 512'\'' '\''null_bdev1'\'' True
00:13:09.327  '
00:13:41.387  Executing command: ['/bdevs/malloc create 40 512 Malloc0', 'Malloc0', True]
00:13:41.387  Executing command: ['/bdevs/malloc create 32 512 Malloc1', 'Malloc1', True]
00:13:41.387  Traceback (most recent call last):
00:13:41.387    File "/var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/spdkcli_job.py", line 64, in <module>
00:13:41.387      execute_command(*cmd[0:3])
00:13:41.387    File "/var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/spdkcli_job.py", line 15, in execute_command
00:13:41.387      child.expect("/>")
00:13:41.387    File "/usr/lib/python3.12/site-packages/pexpect/spawnbase.py", line 343, in expect
00:13:41.387      return self.expect_list(compiled_pattern_list,
00:13:41.387             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
00:13:41.388    File "/usr/lib/python3.12/site-packages/pexpect/spawnbase.py", line 372, in expect_list
00:13:41.388      return exp.expect_loop(timeout)
00:13:41.388             ^^^^^^^^^^^^^^^^^^^^^^^^
00:13:41.388    File "/usr/lib/python3.12/site-packages/pexpect/expect.py", line 181, in expect_loop
00:13:41.388      return self.timeout(e)
00:13:41.388             ^^^^^^^^^^^^^^^
00:13:41.388    File "/usr/lib/python3.12/site-packages/pexpect/expect.py", line 144, in timeout
00:13:41.388      raise exc
00:13:41.388  pexpect.exceptions.TIMEOUT: Timeout exceeded.
00:13:41.388  <pexpect.pty_spawn.spawn object at 0x7ff6857c9280>
00:13:41.388  command: /var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/../../scripts/spdkcli.py
00:13:41.388  args: ['/var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/../../scripts/spdkcli.py', '-s', '/var/tmp/spdk.sock']
00:13:41.388  buffer (last 100 chars): b' /bdevs/malloc create 32 512 Malloc1\r\n'
00:13:41.388  before (last 100 chars): b' /bdevs/malloc create 32 512 Malloc1\r\n'
00:13:41.388  after: <class 'pexpect.exceptions.TIMEOUT'>
00:13:41.388  match: None
00:13:41.388  match_index: None
00:13:41.388  exitstatus: None
00:13:41.388  flag_eof: False
00:13:41.388  pid: 2257722
00:13:41.388  child_fd: 5
00:13:41.388  closed: False
00:13:41.388  timeout: 30
00:13:41.388  delimiter: <class 'pexpect.exceptions.EOF'>
00:13:41.388  logfile: None
00:13:41.388  logfile_read: None
00:13:41.388  logfile_send: None
00:13:41.388  maxread: 2000
00:13:41.388  ignorecase: False
00:13:41.388  searchwindowsize: None
00:13:41.388  delaybeforesend: 0.05
00:13:41.388  delayafterclose: 0.1
00:13:41.388  delayafterterminate: 0.1
00:13:41.388  searcher: searcher_re:
00:13:41.388      0: re.compile(b'/>')
00:13:41.388    07:17:13 vhost.spdkcli_vhost -- spdkcli/vhost.sh@33 -- # trap - ERR
00:13:41.388    07:17:13 vhost.spdkcli_vhost -- spdkcli/vhost.sh@33 -- # print_backtrace
00:13:41.388    07:17:13 vhost.spdkcli_vhost -- common/autotest_common.sh@1149 -- # [[ ehxBET =~ e ]]
00:13:41.388    07:17:13 vhost.spdkcli_vhost -- common/autotest_common.sh@1151 -- # args=()
00:13:41.388    07:17:13 vhost.spdkcli_vhost -- common/autotest_common.sh@1151 -- # local args
00:13:41.388    07:17:13 vhost.spdkcli_vhost -- common/autotest_common.sh@1153 -- # xtrace_disable
00:13:41.388    07:17:13 vhost.spdkcli_vhost -- common/autotest_common.sh@10 -- # set +x
00:13:41.388  ========== Backtrace start: ==========
00:13:41.388  
00:13:41.388  in /var/jenkins/workspace/vhost-phy-autotest/spdk/test/spdkcli/vhost.sh:33 -> main([])
00:13:41.388       ...
00:13:41.388     28  	'/bdevs/malloc create 32 4096 Malloc5' 'Malloc5' True
00:13:41.388     29  	'/bdevs/error create Malloc1' 'EE_Malloc1' True
00:13:41.388     30  	'/bdevs/error create Malloc4' 'EE_Malloc4' True
00:13:41.388     31  	'/bdevs/null create null_bdev0 32 512' 'null_bdev0' True
00:13:41.388     32  	'/bdevs/null create null_bdev1 32 512' 'null_bdev1' True
00:13:41.388  => 33  	"
00:13:41.388     34  	dd if=/dev/zero of="$sample_aio" bs=2048 count=5000
00:13:41.388     35  	dd if=/dev/zero of="$sample_aio2" bs=2048 count=5000
00:13:41.388     36  	$spdkcli_job "'/bdevs/aio create sample0 $sample_aio 512' 'sample0' True
00:13:41.388     37  	'/bdevs/aio create sample1 $sample_aio2 512' 'sample1' True
00:13:41.388     38  	"
00:13:41.388       ...
00:13:41.388  
```

**Comment by spdkci** [comment]
Another instance of this failure. Reported by @jimharris. log: https://ci.spdk.io/public_build/autotest-per-patch_128362.html

**Comment by mikeBashStuff** [comment]
So this failed after sending a second command, without getting the prompt back (`/>`).  Either it just got lost in the stream or this is yet another example of vhost instability that we have been experiencing for some time now.
