### ISSUE TITLE
 [unittest_bdev_raid5f]: test_raid5f_submit_read_request_degraded ...raid5f_ut.c:482:37: runtime error: applying zero offset to null pointer

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3501]
# Sighting report

This pops up under `clang18` (shipped under fedora40) + `ubsan`:

```
Test: test_raid5f_submit_read_request_degraded ...raid5f_ut.c:482:37: runtime error: applying zero offset to null pointer
    #0 0x51ae3e in spdk_bdev_readv_blocks_degraded /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:482:37
    #1 0x519458 in spdk_bdev_readv_blocks_with_md /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:536:10
    #2 0x51bd90 in spdk_bdev_readv_blocks_ext /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:572:9
    #3 0x531a71 in raid_bdev_readv_blocks_ext /root/spdk/module/bdev/raid/bdev_raid.h:413:9
    #4 0x53bf78 in raid5f_chunk_submit /root/spdk/module/bdev/raid/raid5f.c:461:9
    #5 0x532e97 in raid5f_stripe_request_submit_chunks /root/spdk/module/bdev/raid/raid5f.c:595:7
    #6 0x531737 in raid5f_submit_reconstruct_read /root/spdk/module/bdev/raid/raid5f.c:766:2
    #7 0x52c7a9 in raid5f_submit_read_request /root/spdk/module/bdev/raid/raid5f.c:788:10
    #8 0x521557 in raid5f_submit_rw_request /root/spdk/module/bdev/raid/raid5f.c:816:9
    #9 0x549624 in test_raid5f_read_request /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:656:2
    #10 0x544d12 in test_raid5f_submit_rw_request /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:843:3
    #11 0x5449ae in __test_raid5f_submit_read_request /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:901:4
    #12 0x544193 in run_for_each_raid5f_config /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:879:3
    #13 0x51e830 in test_raid5f_submit_read_request_degraded /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:1115:2
    #14 0x7f12e8bcf66c  (/usr/lib64/libcunit.so.1+0x466c) (BuildId: 2b57dc493124068015ebe1e4a79a58e51353fa82)
    #15 0x7f12e8bcf9c7  (/usr/lib64/libcunit.so.1+0x49c7) (BuildId: 2b57dc493124068015ebe1e4a79a58e51353fa82)
    #16 0x7f12e8bd0a8f in CU_run_all_tests (/usr/lib64/libcunit.so.1+0x5a8f) (BuildId: 2b57dc493124068015ebe1e4a79a58e51353fa82)
    #17 0x60a4de in run_tests /root/spdk/lib/ut/ut.c:169:3
    #18 0x6078f6 in spdk_ut_run_tests /root/spdk/lib/ut/ut.c:225:8
    #19 0x51bee1 in main /root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut.c:1140:17
    #20 0x7f12e8239087 in __libc_start_call_main (/usr/lib64/libc.so.6+0x2a087) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)
    #21 0x7f12e823914a in __libc_start_main@GLIBC_2.2.5 (/usr/lib64/libc.so.6+0x2a14a) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)
    #22 0x42b6a4 in _start (/root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut+0x42b6a4) (BuildId: b2048eb5317fc957ca1fd7e71f99a5f434a6481d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior raid5f_ut.c:482:37
/root/spdk/test/common/autotest_common.sh: line 1096: 1316719 Aborted                 (core dumped) "$@"
```

Managed to track it down to `io_info_setup_degraded()` not initializing the `io_info->degraded_md_buf` due to `stripe_md_len` and `md_len` being set to 0. 

```
Breakpoint 1, io_info_setup_degraded (io_info=0x7ffff557a420) at raid5f_ut.c:793
793             struct raid5f_info *r5f_info = io_info->r5f_info;
Missing separate debuginfos, use: dnf debuginfo-install CUnit-2.1.3-32.fc40.x86_64 accel-config-libs-4.1.1-4.fc40.x86_64 fuse3-libs-3.16.2-3.fc40.x86_64 glibc-2.39-22.fc40.x86_64 json-c-0.17-3.fc40.x86_64 keyutils-libs-1.6.3-3.fc40.x86_64 libgcc-14.2.1-1.fc40.x86_64 libibverbs-48.0-4.fc40.x86_64 libnl3-3.10.0-1.fc40.x86_64 librdmacm-48.0-4.fc40.x86_64 libuuid-2.40.1-1.fc40.x86_64 openssl-libs-3.2.2-3.fc40.x86_64 zlib-ng-compat-2.1.7-1.fc40.x86_64
(gdb) s
794             struct raid_bdev *raid_bdev = r5f_info->raid_bdev;
(gdb) s
795             uint32_t blocklen = raid_bdev->bdev.blocklen;
(gdb) s
796             uint32_t md_len = raid_bdev->bdev.md_interleave ? 0 : raid_bdev->bdev.md_len;
(gdb) s
797             size_t stripe_len = r5f_info->stripe_blocks * blocklen;
(gdb) s
798             size_t stripe_md_len = r5f_info->stripe_blocks * md_len;
(gdb) s
800             io_info->degraded_buf = malloc(stripe_len);
(gdb) s
801             SPDK_CU_ASSERT_FATAL(io_info->degraded_buf != NULL);
(gdb) s
803             memset(io_info->degraded_buf, 0xab, stripe_len);
(gdb) s
805             memcpy(io_info->degraded_buf + io_info->stripe_offset_blocks * blocklen,
(gdb) s
806                    io_info->src_buf, io_info->num_blocks * blocklen);
(gdb) s
805             memcpy(io_info->degraded_buf + io_info->stripe_offset_blocks * blocklen,
(gdb) s
808             if (stripe_md_len != 0) {
(gdb) s
818             io_info_setup_parity(io_info, io_info->degraded_buf, io_info->degraded_md_buf);
(gdb) p raid_bdev->bdev.md_interleave
$1 = false
(gdb) p raid_bdev->bdev.md_len
$2 = 0
(gdb) p stripe_md_len
$3 = 0
(gdb)
```

So upon the actual `spdk_bdev_readv_blocks_degraded()` call:

```
Core was generated by `/root/spdk/test/unit/lib/bdev/raid/raid5f.c/raid5f_ut'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f9057ea8664 in __pthread_kill_implementation () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install CUnit-2.1.3-32.fc40.x86_64 accel-config-libs-4.1.1-4.fc40.x86_64 fuse3-libs-3.16.2-3.fc40.x86_64 glibc-2.39-22.fc40.x86_64 json-c-0.17-3.fc40.x86_64 keyutils-libs-1.6.3-3.fc40.x86_64 libgcc-14.2.1-1.fc40.x86_64 libibverbs-48.0-4.fc40.x86_64 libnl3-3.10.0-1.fc40.x86_64 librdmacm-48.0-4.fc40.x86_64 libuuid-2.40.1-1.fc40.x86_64 openssl-libs-3.2.2-3.fc40.x86_64 zlib-ng-compat-2.1.7-1.fc40.x86_64
(gdb) bt
#0  0x00007f9057ea8664 in __pthread_kill_implementation () from /usr/lib64/libc.so.6
#1  0x00007f9057e4fc4e in raise () from /usr/lib64/libc.so.6
#2  0x00007f9057e37902 in abort () from /usr/lib64/libc.so.6
#3  0x00000000004e8adb in __sanitizer::Abort() ()
#4  0x00000000004e6c75 in __sanitizer::Die() ()
#5  0x00000000004fb40c in __ubsan::ScopedReport::~ScopedReport() ()
#6  0x00000000004ff529 in handlePointerOverflowImpl(__ubsan::PointerOverflowData*, unsigned long, unsigned long, __ubsan::ReportOptions) ()
#7  0x00000000004ff0ce in __ubsan_handle_pointer_overflow ()
#8  0x000000000051ae3f in spdk_bdev_readv_blocks_degraded (desc=0x502000024670, ch=0x1, iov=0x5060000826a0, iovcnt=1, md_buf=0x0, offset_blocks=0, num_blocks=1, cb=0x517898 <raid5f_chunk_complete_bdev_io>, cb_arg=0x5110000793b8) at raid5f_ut.c:482
#9  0x0000000000519459 in spdk_bdev_readv_blocks_with_md (desc=0x502000024670, ch=0x1, iov=0x5060000826a0, iovcnt=1, md_buf=0x0, offset_blocks=0, num_blocks=1, cb=0x517898 <raid5f_chunk_complete_bdev_io>, cb_arg=0x5110000793b8) at raid5f_ut.c:536
#10 0x000000000051bd91 in spdk_bdev_readv_blocks_ext (desc=0x502000024670, ch=0x1, iov=0x5060000826a0, iovcnt=1, offset_blocks=0, num_blocks=1, cb=0x517898 <raid5f_chunk_complete_bdev_io>, cb_arg=0x5110000793b8, opts=0x7f9055b72d20) at raid5f_ut.c:572
#11 0x0000000000531a72 in raid_bdev_readv_blocks_ext (base_info=0x513000012a38, ch=0x1, iov=0x5060000826a0, iovcnt=1, offset_blocks=0, num_blocks=1, cb=0x517898 <raid5f_chunk_complete_bdev_io>, cb_arg=0x5110000793b8, opts=0x7f9055b72d20)
    at /root/spdk/module/bdev/raid/bdev_raid.h:413
#12 0x000000000053bf79 in raid5f_chunk_submit (chunk=0x5110000793b8) at /root/spdk/module/bdev/raid/raid5f.c:461
#13 0x0000000000532e98 in raid5f_stripe_request_submit_chunks (stripe_req=0x511000079300) at /root/spdk/module/bdev/raid/raid5f.c:595
#14 0x0000000000531738 in raid5f_submit_reconstruct_read (raid_io=0x5110000f7e80, stripe_index=0, chunk_idx=0 '\000', chunk_offset=0, cb=0x531768 <raid5f_stripe_request_reconstruct_xor_done>) at /root/spdk/module/bdev/raid/raid5f.c:766
#15 0x000000000052c7aa in raid5f_submit_read_request (raid_io=0x5110000f7e80, stripe_index=0, stripe_offset=0) at /root/spdk/module/bdev/raid/raid5f.c:788
#16 0x0000000000521558 in raid5f_submit_rw_request (raid_io=0x5110000f7e80) at /root/spdk/module/bdev/raid/raid5f.c:816
#17 0x0000000000549625 in test_raid5f_read_request (io_info=0x7f9055d7a420) at raid5f_ut.c:656
#18 0x0000000000544d13 in test_raid5f_submit_rw_request (r5f_info=0x504000000c50, raid_ch=0x502000024690, io_type=SPDK_BDEV_IO_TYPE_READ, stripe_index=0, stripe_offset_blocks=0, num_blocks=1) at raid5f_ut.c:843
#19 0x00000000005449af in __test_raid5f_submit_read_request (raid_bdev=0x51700001ab80, raid_ch=0x502000024690) at raid5f_ut.c:901
#20 0x0000000000544194 in run_for_each_raid5f_config (test_fn=0x544258 <__test_raid5f_submit_read_request>) at raid5f_ut.c:879
#21 0x000000000051e831 in test_raid5f_submit_read_request_degraded () at raid5f_ut.c:1115
#22 0x00007f905879266d in run_single_test.constprop () from /usr/lib64/libcunit.so.1
#23 0x00007f90587929c8 in run_single_suite.constprop () from /usr/lib64/libcunit.so.1
#24 0x00007f9058793a90 in CU_run_all_tests () from /usr/lib64/libcunit.so.1
#25 0x000000000060a4df in run_tests (config=0x7f9055b090a0) at ut.c:169
#26 0x00000000006078f7 in spdk_ut_run_tests (argc=1, argv=0x7ffdd98d3858, opts=0x0) at ut.c:225
#27 0x000000000051bee2 in main (argc=1, argv=0x7ffdd98d3858) at raid5f_ut.c:1140
(gdb) frame 8
#8  0x000000000051ae3f in spdk_bdev_readv_blocks_degraded (desc=0x502000024670, ch=0x1, iov=0x5060000826a0, iovcnt=1, md_buf=0x0, offset_blocks=0, num_blocks=1, cb=0x517898 <raid5f_chunk_complete_bdev_io>, cb_arg=0x5110000793b8) at raid5f_ut.c:482
482                     buf_md = io_info->degraded_md_buf +
(gdb) p *io_info
$1 = {r5f_info = 0x504000000c50, raid_ch = 0x502000024690, io_type = SPDK_BDEV_IO_TYPE_READ, stripe_index = 0, offset_blocks = 0, stripe_offset_blocks = 0, num_blocks = 1, src_buf = 0x525000277000, dest_buf = 0x525000279000, src_md_buf = 0x0, dest_md_buf = 0x0,
  buf_size = 4096, buf_md_size = 0, parity_buf = 0x521000d0c100, reference_parity = 0x521000488100, parity_buf_size = 4096, parity_md_buf = 0x0, reference_md_parity = 0x0, parity_md_buf_size = 0, degraded_buf = 0x525001cb8900, degraded_md_buf = 0x0,
  status = SPDK_BDEV_IO_STATUS_PENDING, bdev_io_queue = {tqh_first = 0x0, tqh_last = 0x7f9055d7a4d0}, bdev_io_wait_queue = {tqh_first = 0x0, tqh_last = 0x7f9055d7a4e0}, error = {type = TEST_BDEV_ERROR_NONE, bdev = 0x0, on_enomem_cb = 0x0, on_enomem_cb_ctx = 0x0}}
(gdb) p io_info->degraded_buf
$2 = (void *) 0x525001cb8900
(gdb) p io_info->degraded_md_buf
$3 = (void *) 0x0
(gdb)
```

But I have no clue what should drive `md_len != 0` in the context of the actual test here.

**Comment by mikeBashStuff** [comment]
Here's a fix from @apaszkie 
https://review.spdk.io/gerrit/c/spdk/spdk/+/24669
