### ISSUE TITLE
Coredump occurs, when bdev_lvol_dump_lvols is executed in the bdev_lvol_delete procedure

### ISSUE THREAD

**Issue by wangyalong96** [spdk/spdk#3505]
# Sighting report

Coredump

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  spdk_blob_is_thin_provisioned (blob=0x0) at blobstore.c:9526
9526            return !!(blob->invalid_flags & SPDK_BLOB_THIN_PROV);
[Current thread is 1 (Thread 0x7f9c8acee9c0 (LWP 4163814))]
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-164.el8.x86_64 keyutils-libs-1.5.10-9.el8.x86_64 libaio-0.3.112-1.el8.x86_64 libibverbs-35.0-1.el8.x86_64 libnl3-3.5.0-1.el8.x86_64 libpmem-1.12.1-1.el8.x86_64 libuuid-2.32.1-46.el8.x86_64 numactl-libs-2.0.16-4.el8.x86_64 openssl-libs-1.1.1k-12.el8_9.x86_64 zlib-1.2.11-17.el8.x86_64
(gdb) bt
#0  spdk_blob_is_thin_provisioned (blob=0x0) at blobstore.c:9526
#1  0x000000000045a151 in rpc_dump_lvol (w=w@entry=0x15a4ec0, lvol=lvol@entry=0x1154530) at vbdev_lvol_rpc.c:1173
#2  0x000000000045a37b in rpc_dump_lvols (lvs_bdev=0x12ef940, w=0x15a4ec0) at vbdev_lvol_rpc.c:1194
#3  rpc_bdev_lvol_get_lvols (request=0x113cc10, params=<optimized out>) at vbdev_lvol_rpc.c:1238
#4  0x0000000000553f6a in parse_single_request (values=<optimized out>, request=0x113cc10) at jsonrpc_server.c:126
#5  jsonrpc_parse_request (conn=conn@entry=0x7f9c846cc0a8, json=json@entry=0x7f9c846cc0c0, size=68) at jsonrpc_server.c:263
#6  0x0000000000554a5f in jsonrpc_server_conn_recv (conn=0x7f9c846cc0a8) at jsonrpc_server_tcp.c:294
#7  spdk_jsonrpc_server_poll (server=<optimized out>) at jsonrpc_server_tcp.c:425
#8  0x00000000005535ac in spdk_rpc_server_accept (server=<optimized out>) at rpc.c:258
#9  0x0000000000548527 in rpc_subsystem_poll_servers (arg=<optimized out>) at rpc.c:35
#10 0x000000000054a350 in thread_execute_timed_poller (now=3610673374221172, poller=0xf85e20, thread=0xf7d840) at thread.c:1024
#11 thread_poll (thread=thread@entry=0xf7d840, max_msgs=max_msgs@entry=0, now=now@entry=3610673374221172) at thread.c:1114
#12 0x000000000054a99f in spdk_thread_poll (thread=thread@entry=0xf7d840, max_msgs=max_msgs@entry=0, now=3610673374221172)
    at thread.c:1177
#13 0x00000000005203b9 in _reactor_run (reactor=0xf7b540) at reactor.c:967
#14 reactor_run (arg=0xf7b540) at reactor.c:1005
#15 0x00000000005209d7 in spdk_reactors_start () at reactor.c:1121
#16 0x000000000051d7e1 in spdk_app_start (opts_user=opts_user@entry=0x7ffe8781a5f0, 
    start_fn=start_fn@entry=0x43bc80 <nvmf_tgt_started>, arg1=arg1@entry=0x0) at app.c:981
#17 0x0000000000433cc4 in main (argc=5, argv=0x7ffe8781a7e8) at nvmf_main.c:47
```

## Possible Solution

check the lvol->ref_count before dump lvol info. Skip the lvol that ref_count is 0. 

## Steps to Reproduce

1. create one lvol
```
nohup nvmf_tgt -r /var/run/spdk/test_af.sock --cpumask [7,8,9] >> ./af.log 2>>./af.log  &
rpc.py -s /var/run/spdk/test_af.sock nvmf_create_transport -t tcp
rpc.py -s /var/run/spdk/test_af.sock bdev_nvme_attach_controller -b NVMeaf -t PCIe -a 0000:af:00.0
rpc.py -s /var/run/spdk/test_af.sock bdev_lvol_create_lvstore NVMeafn1 lvs
rpc.py -s /var/run/spdk/test_af.sock bdev_lvol_create -l lvs lv0 512000 -t
```

2. we need make dump_lvols and delete_lvol execute concurrently, so we make bdev_lvol_delete process pause to wait bdev_lvol_get_lvols cmd called. 
```
gdb attach `pidof nvmf_tgt`
(gdb) b lvol_close_blob_cb    (create breakpoint)
(gdb) c    (continue run on gdb)
```

3. execute lvol_delete and bdev_lvol_get_lvols **_on two consoles_**
```
rpc.py -s /var/run/nbs/test_af.sock bdev_lvol_delete  lvs/lv0
rpc.py -s /var/run/nbs/test_af.sock bdev_lvol_get_lvols
```

4. gdb should already stuck because the breakpoints, continue the gdb
```
(gdb) c  
```
5. segfault occur 

## Context (Environment including OS version, SPDK version, etc.)
1c5a5ee61864b02a73fd2f2150dcfe2982ea96f4

**Comment by wangyalong96** [comment]
[24668: bdev/lvol: fix dump_lvol and delete_lvol concurrent conflict. | https://review.spdk.io/gerrit/c/spdk/spdk/+/24668](url)

**Comment by jimharris** [comment]
> [24668: bdev/lvol: fix dump_lvol and delete_lvol concurrent conflict. | https://review.spdk.io/gerrit/c/spdk/spdk/+/24668](url)

GitHub mangled this URL, but I was able to just bring up the 24668 patch in Gerrit directly.

The patch looks good, I made one comment on Author and Signed-off lines though.

The reproduction steps here were great. You already had the fix but I wanted to see the SEGV for myself. I wish all reproduction steps were this clear!

**Comment by wangyalong96** [comment]
Thanks for your attention.
The reproduction steps  were updated. 
And I modify the author name format on https://review.spdk.io/gerrit/c/spdk/spdk/+/24681
