### ISSUE TITLE
[env_memory] lib/env_dpdk/memory.c:365:13: runtime error: applying non-zero offset 2097152 to null pointer

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3512]
# Sighting report

`clang18` + `ubsan` - this combination is used under `short-fuzz-phy-autotest` job.

```
************************************
START TEST env_memory
************************************
 09:47:14 env_memory -- common/autotest_common.sh@1121 -- # /root/spdk/test/env/memory/memory_ut


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: memory
  Test: alloc and free memory map .../root/spdk/lib/env_dpdk/memory.c:365:13: runtime error: applying non-zero offset 2097152 to null pointer
    #0 0x42c5d1 in spdk_mem_register /root/spdk/lib/env_dpdk/memory.c:365:13
    #1 0x4706a8 in test_mem_map_alloc_free /root/spdk/test/env/memory/memory_ut.c:178:3
    #2 0x7f7f049c966c  (/usr/lib64/libcunit.so.1+0x466c) (BuildId: 2b57dc493124068015ebe1e4a79a58e51353fa82)
    #3 0x7f7f049c99c7  (/usr/lib64/libcunit.so.1+0x49c7) (BuildId: 2b57dc493124068015ebe1e4a79a58e51353fa82)
    #4 0x7f7f049caa8f in CU_run_all_tests (/usr/lib64/libcunit.so.1+0x5a8f) (BuildId: 2b57dc493124068015ebe1e4a79a58e51353fa82)
    #5 0x489a1b in run_tests /root/spdk/lib/ut/ut.c:169:3
    #6 0x485bbb in spdk_ut_run_tests /root/spdk/lib/ut/ut.c:225:8
    #7 0x4702ea in main /root/spdk/test/env/memory/memory_ut.c:506:17
    #8 0x7f7f04039087 in __libc_start_call_main (/usr/lib64/libc.so.6+0x2a087) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)
    #9 0x7f7f0403914a in __libc_start_main@GLIBC_2.2.5 (/usr/lib64/libc.so.6+0x2a14a) (BuildId: 77c77fee058b19c6f001cf2cb0371ce3b8341211)
    #10 0x405874 in _start (/root/spdk/test/env/memory/memory_ut+0x405874) (BuildId: fefcdec7545babc79cdde5745a459a1ac4d9c404)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /root/spdk/lib/env_dpdk/memory.c:365:13
/root/spdk/test/common/autotest_common.sh: line 1096: 43131 Aborted                 (core dumped) "$@"
```

bt:

```
Core was generated by `/root/spdk/test/env/memory/memory_ut'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f7f040a8664 in __pthread_kill_implementation () from /usr/lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install CUnit-2.1.3-32.fc40.x86_64 accel-config-libs-4.1.1-4.fc40.x86_64 fuse3-libs-3.16.2-3.fc40.x86_64 glibc-2.39-22.fc40.x86_64 json-c-0.17-3.fc40.x86_64 keyutils-libs-1.6.3-3.fc40.x86_64 libgcc-14.2.1-1.fc40.x86_64 libibverbs-48.0-4.fc40.x86_64 libnl3-3.10.0-1.fc40.x86_64 librdmacm-48.0-4.fc40.x86_64 liburing-2.5-3.fc40.x86_64 libuuid-2.40.1-1.fc40.x86_64 openssl-libs-3.2.2-3.fc40.x86_64 zlib-ng-compat-2.1.7-1.fc40.x86_64
(gdb) thread apply all bt full

Thread 1 (Thread 0x7f7f046bf7c0 (LWP 43131)):
#0  0x00007f7f040a8664 in __pthread_kill_implementation () from /usr/lib64/libc.so.6
No symbol table info available.
#1  0x00007f7f0404fc4e in raise () from /usr/lib64/libc.so.6
No symbol table info available.
#2  0x00007f7f04037902 in abort () from /usr/lib64/libc.so.6
No symbol table info available.
#3  0x000000000041485b in __sanitizer::Abort() ()
No symbol table info available.
#4  0x0000000000412a45 in __sanitizer::Die() ()
No symbol table info available.
#5  0x00000000004209bc in __ubsan::ScopedReport::~ScopedReport() ()
No symbol table info available.
#6  0x0000000000424ad9 in handlePointerOverflowImpl(__ubsan::PointerOverflowData*, unsigned long, unsigned long, __ubsan::ReportOptions) ()
No symbol table info available.
#7  0x000000000042467e in __ubsan_handle_pointer_overflow ()
No symbol table info available.
#8  0x000000000042c5d2 in spdk_mem_register (vaddr=0x0, len=2097152) at /root/spdk/lib/env_dpdk/memory.c:365
        map = 0x0
        rc = 0
        seg_vaddr = 0x0
        seg_len = 2097152
        reg = 0
#9  0x00000000004706a9 in test_mem_map_alloc_free () at memory_ut.c:178
        map = 0xe21a140
        failed_map = 0xe219f20
        default_translation = 16045690981293355021
        i = 0
#10 0x00007f7f049c966d in run_single_test.constprop () from /usr/lib64/libcunit.so.1
No symbol table info available.
#11 0x00007f7f049c99c8 in run_single_suite.constprop () from /usr/lib64/libcunit.so.1
No symbol table info available.
#12 0x00007f7f049caa90 in CU_run_all_tests () from /usr/lib64/libcunit.so.1
No symbol table info available.
#13 0x0000000000489a1c in run_tests (config=0x7ffd30ad5970) at ut.c:169
        suite = 0x0
        test = 0x0
#14 0x0000000000485bbc in spdk_ut_run_tests (argc=1, argv=0x7ffd30ad5b28, opts=0x0) at ut.c:225
        config = {app = 0x7ffd30ad7a33 "/root/spdk/test/env/memory/memory_ut", test = 0x0, suite = 0x0, action = UT_ACTION_RUN_TESTS, opts = 0x0}
        rc = 0
#15 0x00000000004702eb in main (argc=1, argv=0x7ffd30ad5b28) at memory_ut.c:506
        suite = 0xe219f20
        num_failures = 32639
```

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/24729

**Comment by mikeBashStuff** [comment]
Patches merged, verified, closing.
