### ISSUE TITLE
spdk bdevperf core dumped when use iscsi initiator

### ISSUE THREAD

**Issue by xuhuagen** [spdk/spdk#352]
core dumped occurred when I run bdevperf command 
`./test/bdev/bdevperf/bdevperf -c ../bdev.conf -q 32 -s 4096 -w write -t 10`

bdev.conf as below:
```
[iSCSI_Initiator]
        URL iscsi://192.168.11.11/iqn.2016-06.io.spdk:disk1/0 iSCSI0
```
core dumped log:
```
[root@waikikibeach29 spdk]# gdb -c /tmp/core-reactor_0-11-0-0-317383-1530512244 test/bdev/bdevperf/bdevperf
GNU gdb (GDB) Fedora 8.0.1-36.fc27
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from test/bdev/bdevperf/bdevperf...done.

warning: core file may not match specified executable file.
[New LWP 317383]
[New LWP 317540]
[New LWP 317392]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./test/bdev/bdevperf/bdevperf -c ../bdev.conf -q 32 -s 4096 -w write -t 10'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000000000 in ?? ()
[Current thread is 1 (Thread 0x7fcdb2b622c0 (LWP 317383))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26-27.fc27.x86_64 libaio-0.3.110-9.fc27.x86_64 libibverbs-14-4.fc27.x86_64 libnl3-3.4.0-1.fc27.x86_64 librdmacm-14-4.fc27.x86_64 libuuid-2.30.2-3.fc27.x86_64 numactl-libs-2.0.11-5.fc27.x86_64 openssl-libs-1.1.0h-3.fc27.x86_64 zlib-1.2.11-4.fc27.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000004326b9 in bdev_iscsi_poll_lun (lun=<optimized out>) at bdev_iscsi.c:332
#2  0x000000000043c6c1 in _spdk_reactor_run (arg=0xb91c80) at reactor.c:518
#3  0x000000000043cce8 in spdk_reactors_start () at reactor.c:692
#4  0x000000000043b961 in spdk_app_start (opts=opts@entry=0x7fffda3d4d50, start_fn=start_fn@entry=0x406f80 <bdevperf_run>,
    arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:570
#5  0x000000000040560c in main (argc=<optimized out>, argv=<optimized out>) at bdevperf.c:1027
(gdb)
```

## Expected Behavior
bdevperf should  run success when io pattern is reset,unmap,reset and so on when I use iscsi initiator.
## Current Behavior

core dumped occurred when I run bdevperf command

## Steps to Reproduce
Target machine:
```
1. spdk/app/iscsi_tgt/iscsi_tgt &
2. spdk/scripts/rpc.py add_portal_group 1 192.168.11.11:3260
3.  spdk/scripts/rpc.py add_initiator_group 1 ANY 192.168.11.11/24
4. spdk/scripts/rpc.py construct_malloc_bdev 64 4096
5. spdk/scripts/rpc.py construct_target_node disk1 disk1_alias 'Malloc0:0' '1:1' 64 -d
```

Initiator machine:
```
1. cd path/to/spdk
2. ./configure --with-iscsi-initiator && make clean && make -j64
3. ./test/bdev/bdevperf/bdevperf -c ../bdev.conf -q 32 -s 4096 -w write -t 10
```

## Context (Environment including OS version, SPDK version, etc.)
Target machine
OS:  CentOS Linux release 7.5.1804
commit id: ccdf6c93145bacc4fbf10825a22679dfe0e8b6e9

Initiator machine
OS:  Fedora release 27
commit id: 69a762ca5290c0a23e2f5001990bae5ff7af38ad

**Comment by optimistyzy** [comment]
duplicated error, which is same with #340  @xuhuagen

**Comment by xuhuagen** [comment]
this issue is same with #340,so close it。
