### ISSUE TITLE
ctrlr_bdev.c: Memory leak in nvmf_bdev_ctrlr_unmap

### ISSUE THREAD

**Issue by rmvasuki** [spdk/spdk#3539]
# Sighting report

Memory leak observed when nvmf target fails an unmap command to a namespace in a subsystem which has the max_discard_size set.

## Expected Behavior

No memory leaks.

## Current Behavior

Memory leak observed. Confirmed by enabling asan/ubsan.

```
==71733==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0xffffa1d9b190 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0xaaaad9403e50 in nvmf_bdev_ctrlr_unmap /home/vasuki/spdk/lib/nvmf/ctrlr_bdev.c:691
    #2 0xaaaad9404ea0 in nvmf_bdev_ctrlr_dsm_cmd /home/vasuki/spdk/lib/nvmf/ctrlr_bdev.c:760
    #3 0xaaaad93cecc4 in nvmf_ctrlr_process_io_cmd /home/vasuki/spdk/lib/nvmf/ctrlr.c:4583
    #4 0xaaaad93d65d4 in spdk_nvmf_request_exec /home/vasuki/spdk/lib/nvmf/ctrlr.c:4919
    #5 0xaaaad94f5800 in nvmf_tcp_req_process /home/vasuki/spdk/lib/nvmf/tcp.c:3269
    #6 0xaaaad94ddf8c in nvmf_tcp_capsule_cmd_payload_handle /home/vasuki/spdk/lib/nvmf/tcp.c:1931
    #7 0xaaaad94e3400 in _nvmf_tcp_pdu_payload_handle /home/vasuki/spdk/lib/nvmf/tcp.c:2192
    #8 0xaaaad94e4b40 in nvmf_tcp_pdu_payload_handle /home/vasuki/spdk/lib/nvmf/tcp.c:2263
    #9 0xaaaad94ea324 in nvmf_tcp_sock_process /home/vasuki/spdk/lib/nvmf/tcp.c:2616
    #10 0xaaaad94f8164 in tcp_sock_cb /home/vasuki/spdk/lib/nvmf/tcp.c:3401
    #11 0xaaaad94f81a4 in nvmf_tcp_sock_cb /home/vasuki/spdk/lib/nvmf/tcp.c:3412
    #12 0xaaaad97f2214 in sock_group_impl_poll_count /home/vasuki/spdk/lib/sock/sock.c:765
    #13 0xaaaad97f23f8 in spdk_sock_group_poll_count /home/vasuki/spdk/lib/sock/sock.c:791
    #14 0xaaaad97f1d30 in spdk_sock_group_poll /home/vasuki/spdk/lib/sock/sock.c:742
    #15 0xaaaad94f9cb4 in nvmf_tcp_poll_group_poll /home/vasuki/spdk/lib/nvmf/tcp.c:3566
    #16 0xaaaad94a98c8 in nvmf_transport_poll_group_poll /home/vasuki/spdk/lib/nvmf/transport.c:735
    #17 0xaaaad9455b74 in nvmf_poll_group_poll /home/vasuki/spdk/lib/nvmf/nvmf.c:157
    #18 0xaaaad9836018 in thread_execute_poller /home/vasuki/spdk/lib/thread/thread.c:965
    #19 0xaaaad9838318 in thread_poll /home/vasuki/spdk/lib/thread/thread.c:1091
    #20 0xaaaad98391c4 in spdk_thread_poll /home/vasuki/spdk/lib/thread/thread.c:1179
    #21 0xaaaad96bcca4 in _reactor_run /home/vasuki/spdk/lib/event/reactor.c:967
    #22 0xaaaad96bd448 in reactor_run /home/vasuki/spdk/lib/event/reactor.c:1005
    #23 0xaaaad96be098 in spdk_reactors_start /home/vasuki/spdk/lib/event/reactor.c:1121
    #24 0xaaaad96aea3c in spdk_app_start /home/vasuki/spdk/lib/event/app.c:988
    #25 0xaaaad8eda3c0 in main /home/vasuki/spdk/app/nvmf_tgt/nvmf_main.c:47
    #26 0xffffa0df773c in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #27 0xffffa0df7814 in __libc_start_main_impl ../csu/libc-start.c:360
    #28 0xaaaad8eda02c in _start (/home/vasuki/spdk/build/bin/nvmf_tgt+0xf7a02c)
```

## Possible Solution

```
diff --git a/lib/nvmf/ctrlr_bdev.c b/lib/nvmf/ctrlr_bdev.c
index 33b376c70..441078e3a 100644
--- a/lib/nvmf/ctrlr_bdev.c
+++ b/lib/nvmf/ctrlr_bdev.c
@@ -718,7 +718,7 @@ nvmf_bdev_ctrlr_unmap(struct spdk_bdev *bdev, struct spdk_bdev_desc *desc,
                        SPDK_ERRLOG("invalid unmap size, should not exceed %" PRIu64 "Kib\n", max_discard_size);
                        response->status.sct = SPDK_NVME_SCT_GENERIC;
                        response->status.sc = SPDK_NVME_SC_INVALID_FIELD;
-                       return SPDK_NVMF_REQUEST_EXEC_STATUS_COMPLETE;
+                       break;
                }

                unmap_ctx->count++;
```

## Steps to Reproduce

1. Start nvmf_tgt, create TCP transport, create NVMe subsystem with the `--max-discard-size` parameter, add listeners and attach namespace to subsystem.
```
./build/bin/nvmf_tgt &
./scripts/rpc.py nvmf_create_transport -t TCP -u 16384 -m 8 -c 8192
./scripts/rpc.py nvmf_create_subsystem nqn.2016-06.io.spdk:cnode1 -a -s SPDK00000000000001 -d SPDK_Controller1 --max-discard-size=32768
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2016-06.io.spdk:cnode1 -t tcp -a 127.0.0.1 -s 4420
./scripts/rpc.py nvmf_subsystem_add_listener nqn.2014-08.org.nvmexpress.discovery -t tcp -a 127.0.0.1 -s 8009
./scripts/rpc.py bdev_nvme_attach_controller -t pcie -a 0000:12:00.0 -b nvme
./scripts/rpc.py nvmf_subsystem_add_ns nqn.2016-06.io.spdk:cnode1 nvmen2
```

3. Connect from a host and issue identify to verify the dataset management range size limit:
```
root@debian-vm:~# nvme nvm-id-ctrl /dev/nvme0n1
NVMe Identify Controller NVM:
vsl    : 0
wzsl   : 0
wusl   : 0
dmrl   : 1
dmrsl  : 65536
dmsl   : 0
```

4. Issue a large dsm command and observe that it fails
root@debian-vm:~# nvme dsm --ad -n 1 -b 131072 -s 0 /dev/nvme0
NVMe status: Invalid Field in Command: A reserved coded value or an unsupported value in a defined field(0x2)

5. Stop nvmf_tgt.

## Context (Environment including OS version, SPDK version, etc.)
OS: Debian 12
SPDK v25.01-pre git sha1 a59ab6df2 / DPDK 24.03.0

**Comment by jimharris** [comment]
Thanks @rmvasuki. Could you push this as a patch to Gerrit?

**Comment by rmvasuki** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/25042

**Comment by jimharris** [comment]
> https://review.spdk.io/gerrit/c/spdk/spdk/+/25042

Looks good to me. Thanks @rmvasuki!
