### ISSUE TITLE
SIGFPE received after switching to gscheduler

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3550]
Noticed while playing with `test/scheduler/rpc.sh`. Simple change which triggers the crash 100%:

```
--- a/test/scheduler/rpc.sh
+++ b/test/scheduler/rpc.sh
@@ -58,6 +58,7 @@ function scheduler_opts() {

        # Switch scheduler back and forth and verify values are kept (scheduler implementation specific)
        $rpc framework_set_scheduler gscheduler
+       sleep 5
        [[ "$($rpc framework_get_scheduler | jq -r '.scheduler_name')" == "gscheduler" ]]
        $rpc framework_set_scheduler dynamic
        [[ "$($rpc framework_get_scheduler | jq -r '. | select(.scheduler_name == "dynamic") | .core_limit')" -eq 42 ]]
```

Seems like leaving `gscheduler` for too long "breaks" the tsc counters and that leads to:

```
Core was generated by `/root/spdk/build/bin/spdk_tgt -m [1,2,3,4,73,74,75,76] --wait-for-rpc'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00000000004e8cdc in calculate_busy_pct (core=0x2b7d490) at gscheduler.c:38
38              return core->current_busy_tsc * 100 / total_tsc;
[Current thread is 1 (Thread 0x7f78ad5109c0 (LWP 802292))]
Missing separate debuginfos, use: dnf debuginfo-install fuse3-libs-3.16.1-1.fc39.x86_64 glibc-2.38-18.fc39.x86_64 keyutils-libs-1.6.3-1.fc39.x86_64 libaio-0.3.111-16.fc39.x86_64 libuuid-2.39.4-1.fc39.x86_64 numactl-libs-2.0.16-3.fc39.x86_64 openssl-libs-3.1.1-4.fc39.x86_64 zlib-1.2.13-4.fc39.x86_64
(gdb) p *core
$1 = {total_idle_tsc = 1928663470, total_busy_tsc = 0, current_idle_tsc = 0, current_busy_tsc = 0, lcore = 73, threads_count = 0, interrupt_mode = true, thread_infos = 0x0, isolated = false}
(gdb) p total_tsc
$2 = 0
```

That also seems to tie somehow to period of the dynamic scheduler as crash happens immediately when it's set to a way lower value. So simple reproducer would look like this:
```
#!/usr/bin/env bash

rootdir=$PWD
source "$rootdir/test/common/autotest_common.sh"

# smt, otherwise gscheduler kicks us out
"$rootdir/build/bin/spdk_tgt" --wait-for-rpc -m "[1,73]"  &
waitforlisten $!

rpc_cmd <<-RPC
        framework_set_scheduler dynamic -p 100
        framework_set_scheduler gscheduler
        framework_set_scheduler dynamic
RPC

wait $!
```
Which yields:
```
# ./t
  14:31:59  -- common/autotest_common.sh@1690 -- # [[ n == y ]]
 14:31:59  -- ./t@8 -- # waitforlisten 806966
 14:31:59  -- common/autotest_common.sh@831 -- # '[' -z 806966 ']'
 14:31:59  -- common/autotest_common.sh@835 -- # local rpc_addr=/var/tmp/spdk.sock
 14:31:59  -- common/autotest_common.sh@836 -- # local max_retries=100
 14:31:59  -- ./t@7 -- # /root/spdk/build/bin/spdk_tgt --wait-for-rpc -m '[1,73]'
 14:31:59  -- common/autotest_common.sh@838 -- # echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 14:31:59  -- common/autotest_common.sh@840 -- # xtrace_disable
 14:31:59  -- common/autotest_common.sh@10 -- # set +x
[2024-10-11 14:31:59.289918] Starting SPDK v25.01-pre git sha1 5031f0f3b / DPDK 24.03.0 initialization...
[2024-10-11 14:31:59.290016] [ DPDK EAL parameters: spdk_tgt --no-shconf -l 1,73 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=lib.power:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid806966 ]
EAL: No free 2048 kB hugepages reported on node 1
[2024-10-11 14:31:59.403005] app.c: 919:spdk_app_start: *NOTICE*: Total cores available: 2
[2024-10-11 14:31:59.495953] reactor.c:1005:reactor_run: *NOTICE*: Reactor started on core 73
[2024-10-11 14:31:59.495970] reactor.c:1005:reactor_run: *NOTICE*: Reactor started on core 1
 14:32:00  -- common/autotest_common.sh@860 -- # (( i == 0 ))
 14:32:00  -- common/autotest_common.sh@864 -- # return 0
 14:32:00  -- ./t@10 -- # rpc_cmd
 14:32:00  -- common/autotest_common.sh@561 -- # xtrace_disable
 14:32:00  -- common/autotest_common.sh@10 -- # set +x
[2024-10-11 14:32:00.167657] scheduler_dynamic.c: 427:set_opts: *NOTICE*: Setting scheduler load limit to 20
[2024-10-11 14:32:00.167691] scheduler_dynamic.c: 429:set_opts: *NOTICE*: Setting scheduler core limit to 80
[2024-10-11 14:32:00.167702] scheduler_dynamic.c: 431:set_opts: *NOTICE*: Setting scheduler core busy to 95
Connection closed with partial response:


Error while connecting to /var/tmp/spdk.sock
Is SPDK application running?
Error details: [Errno 111] Connection refused
 14:32:00  -- common/autotest_common.sh@589 -- # [[ 0 1 == 0 ]]
/root/spdk/test/common/autotest_common.sh: line 589: 806966 Floating point exception(core dumped) "$rootdir/build/bin/spdk_tgt" --wait-for-rpc -m "[1,73]"
  14:32:00  -- common/autotest_common.sh@589 -- # trap - ERR
  14:32:00  -- common/autotest_common.sh@589 -- # print_backtrace
  14:32:00  -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
  14:32:00  -- common/autotest_common.sh@1155 -- # args=()
  14:32:00  -- common/autotest_common.sh@1155 -- # local args
  14:32:00  -- common/autotest_common.sh@1157 -- # xtrace_disable
  14:32:00  -- common/autotest_common.sh@10 -- # set +x
========== Backtrace start: ==========

in /root/spdk/test/common/autotest_common.sh:589 -> rpc_cmd([])
     ...
   584                  echo "$rsp"
   585          done
   586
   587          rc=${!status[*]}
   588          xtrace_restore
=> 589          [[ $rc == 0 ]]
   590  }
   591
   592  function rpc_cmd_simple_data_json() {
   593
   594          local elems="$1[@]" elem
     ...
in ./t:10 -> main([])
     ...
   5
   6    # smt, otherwise gscheduler shows us a finger
   7    "$rootdir/build/bin/spdk_tgt" --wait-for-rpc -m "[1,73]"  &
   8    waitforlisten $!
   9
=> 10   rpc_cmd <<-RPC
   11           framework_set_scheduler dynamic -p 100
   12           framework_set_scheduler gscheduler
   13           framework_set_scheduler dynamic
   14   RPC
   15
     ...

========== Backtrace end ==========
  14:32:00  -- common/autotest_common.sh@1194 -- # return 0
```

The smaller reproducer which ties more closely the initial diff of `/test/scheduler/rpc.sh` (period in the actual test is set to 424242):
```
...
rpc_cmd framework_set_scheduler dynamic -p 10000000
sleep 1
rpc_cmd framework_set_scheduler gscheduler
wait $!
```

Which gives:
```
# ./t
  14:37:07  -- common/autotest_common.sh@1690 -- # [[ n == y ]]
 14:37:07  -- ./t@8 -- # waitforlisten 808367
 14:37:07  -- common/autotest_common.sh@831 -- # '[' -z 808367 ']'
 14:37:07  -- common/autotest_common.sh@835 -- # local rpc_addr=/var/tmp/spdk.sock
 14:37:07  -- common/autotest_common.sh@836 -- # local max_retries=100
 14:37:07  -- ./t@7 -- # /root/spdk/build/bin/spdk_tgt --wait-for-rpc -m '[1,73]'
 14:37:07  -- common/autotest_common.sh@838 -- # echo 'Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...'
Waiting for process to start up and listen on UNIX domain socket /var/tmp/spdk.sock...
 14:37:07  -- common/autotest_common.sh@840 -- # xtrace_disable
 14:37:07  -- common/autotest_common.sh@10 -- # set +x
[2024-10-11 14:37:07.246497] Starting SPDK v25.01-pre git sha1 5031f0f3b / DPDK 24.03.0 initialization...
[2024-10-11 14:37:07.246611] [ DPDK EAL parameters: spdk_tgt --no-shconf -l 1,73 --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=lib.power:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid808367 ]
EAL: No free 2048 kB hugepages reported on node 1
[2024-10-11 14:37:07.311600] app.c: 919:spdk_app_start: *NOTICE*: Total cores available: 2
[2024-10-11 14:37:07.358784] reactor.c:1005:reactor_run: *NOTICE*: Reactor started on core 73
[2024-10-11 14:37:07.358784] reactor.c:1005:reactor_run: *NOTICE*: Reactor started on core 1
 14:37:07  -- common/autotest_common.sh@860 -- # (( i == 0 ))
 14:37:07  -- common/autotest_common.sh@864 -- # return 0
 14:37:07  -- ./t@10 -- # rpc_cmd framework_set_scheduler dynamic -p 10000000
 14:37:07  -- common/autotest_common.sh@561 -- # xtrace_disable
 14:37:07  -- common/autotest_common.sh@10 -- # set +x
[2024-10-11 14:37:07.451838] scheduler_dynamic.c: 427:set_opts: *NOTICE*: Setting scheduler load limit to 20
[2024-10-11 14:37:07.451857] scheduler_dynamic.c: 429:set_opts: *NOTICE*: Setting scheduler core limit to 80
[2024-10-11 14:37:07.451864] scheduler_dynamic.c: 431:set_opts: *NOTICE*: Setting scheduler core busy to 95
 14:37:07  -- common/autotest_common.sh@589 -- # [[ 0 == 0 ]]
 14:37:07  -- ./t@11 -- # sleep 1
 14:37:08  -- ./t@12 -- # rpc_cmd framework_set_scheduler gscheduler
 14:37:08  -- common/autotest_common.sh@561 -- # xtrace_disable
 14:37:08  -- common/autotest_common.sh@10 -- # set +x
 14:37:08  -- common/autotest_common.sh@589 -- # [[ 0 == 0 ]]
 14:37:08  -- ./t@13 -- # wait 808367
./t: line 13: 808367 Floating point exception(core dumped) "$rootdir/build/bin/spdk_tgt" --wait-for-rpc -m "[1,73]"
  14:37:27  -- ./t@13 -- # trap - ERR
  14:37:27  -- ./t@13 -- # print_backtrace
  14:37:27  -- common/autotest_common.sh@1153 -- # [[ ehxBET =~ e ]]
  14:37:27  -- common/autotest_common.sh@1155 -- # args=()
  14:37:27  -- common/autotest_common.sh@1155 -- # local args
  14:37:27  -- common/autotest_common.sh@1157 -- # xtrace_disable
  14:37:27  -- common/autotest_common.sh@10 -- # set +x
========== Backtrace start: ==========

in ./t:13 -> main([])
     ...
   8    waitforlisten $!
   9
   10   rpc_cmd framework_set_scheduler dynamic -p 10000000
   11   sleep 1
   12   rpc_cmd framework_set_scheduler gscheduler
=> 13   wait $!
     ...

========== Backtrace end ==========
  14:37:27  -- common/autotest_common.sh@1194 -- # return 0
```
So here, with a way bigger period, the actual crash is deferred until ~20s mark but it does eventually happen.

bt:

```
(gdb) bt full
#0  0x00000000004e8cdc in calculate_busy_pct (core=0x2b7d490) at gscheduler.c:38
        total_tsc = 0
#1  0x00000000004e8d1a in check_sibling (_ctx=0x7ffec7824310, i=73) at gscheduler.c:51
        ctx = 0x7ffec7824310
        core = 0x2b7d490
        busy_pct = 0
#2  0x000000000063681c in spdk_cpuset_for_each_cpu (set=0x7ffec7824320, fn=0x4e8ce2 <check_sibling>, ctx=0x7ffec7824310) at cpuset.c:117
        n = 2 '\002'
        i = 9
        j = 1
#3  0x00000000004e8eec in balance (cores=0x2b7c250, core_count=77) at gscheduler.c:84
        ctx = {cores = 0x2b7c250, busy_pct = 0}
        smt_siblings = {str = '\000' <repeats 256 times>, cpus = "\002\000\000\000\000\000\000\000\000\002", '\000' <repeats 117 times>}
        governor = 0xa49b00 <dpdk_governor>
        core = 0x2b7c290
        capabilities = {priority = false}
        busy_pct = 0
        i = 1
        rc = 0
        __PRETTY_FUNCTION__ = "balance"
        __func__ = "balance"
#4  0x00000000005ca1e6 in _reactors_scheduler_balance (arg1=0x0, arg2=0x0) at reactor.c:828
        scheduler = 0xa49b80 <gscheduler>
#5  0x00000000005c9c16 in event_queue_run_batch (arg=0x2b6f140) at reactor.c:649
        event = 0x2000005c0500
        reactor = 0x2b6f140
        count = 1
        i = 0
        events = {0x2000005c0500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}
        __func__ = "event_queue_run_batch"
        __PRETTY_FUNCTION__ = "event_queue_run_batch"
#6  0x00000000005ca8e7 in _reactor_run (reactor=0x2b6f140) at reactor.c:968
        thread = 0x2b86b40
        lw_thread = 0x0
        tmp = 0x0
        now = 29838318984419877
        rc = 0
#7  0x00000000005cab15 in reactor_run (arg=0x2b6f140) at reactor.c:1022
        reactor = 0x2b6f140
        thread = 0x8000000000
        lw_thread = 0xa4c460 <rte_config>
        tmp = 0xc7824640
        thread_name = "reactor_1\000N\000\000\000\000\000)\252\\\000\000\000\000\000\000\000\000\000\001\000\000"
        last_sched = 29838318982399813
        __func__ = "reactor_run"
        __PRETTY_FUNCTION__ = <optimized out>
#8  0x00000000005cb027 in spdk_reactors_start () at reactor.c:1139
        reactor = 0x2b6f140
        i = 4294967295
        current_core = 1
        rc = 0
        __func__ = "spdk_reactors_start"
        __PRETTY_FUNCTION__ = "spdk_reactors_start"
#9  0x00000000005c6c8d in spdk_app_start (opts_user=0x7ffec78249a0, start_fn=0x40ae2a <spdk_tgt_started>, arg1=0x0) at app.c:991
        rc = 0
        tty = 0x2ae7090 "/dev/pts/3"
        tmp_cpumask = {str = '\000' <repeats 256 times>, cpus = "\002", '\000' <repeats 126 times>}
        g_env_was_setup = false
        opts_local = {name = 0x9040f4 "spdk_tgt", json_config_file = 0x0, json_config_ignore_errors = false, reserved17 = "\000\000\000\000\000\000", rpc_addr = 0x95acec "/var/tmp/spdk.sock", reactor_mask = 0x7ffec78265f4 "[1,2,3,4,73,74,75,76]", tpoint_group_mask = 0x0,
          shm_id = -1, reserved52 = "\000\000\000", shutdown_cb = 0x0, enable_coredump = true, reserved65 = "\000\000", mem_channel = -1, main_core = -1, mem_size = -1, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, no_huge = false,
          reserved84 = "\000\000\000", hugedir = 0x0, print_level = SPDK_LOG_INFO, reserved100 = "\000\000\000", num_pci_addr = 0, pci_blocked = 0x0, pci_allowed = 0x0, iova_mode = 0x0, delay_subsystem_init = true, reserved137 = "\000\000\000\000\000\000", num_entries = 32768,
          env_context = 0x0, log = 0x0, base_virtaddr = 35184372088832, opts_size = 253, disable_signal_handlers = false, interrupt_mode = false, enforce_numa = false, reserved187 = "\000\000\000\000", msg_mempool_size = 262143, rpc_allowlist = 0x0, vf_token = 0x0,
          lcore_map = 0x0, rpc_log_level = SPDK_LOG_DISABLED, rpc_log_file = 0x0, json_data = 0x0, json_data_size = 0, disable_cpumask_locks = false}
        opts = 0x7ffec78246d0
        i = 128
        core = 4294967295
        __func__ = "spdk_app_start"
#10 0x000000000040af7f in main (argc=4, argv=0x7ffec7824bd8) at spdk_tgt.c:102
        opts = {name = 0x9040f4 "spdk_tgt", json_config_file = 0x0, json_config_ignore_errors = false, reserved17 = "\000\000\000\000\000\000", rpc_addr = 0x95acec "/var/tmp/spdk.sock", reactor_mask = 0x7ffec78265f4 "[1,2,3,4,73,74,75,76]", tpoint_group_mask = 0x0,
          shm_id = -1, reserved52 = "\000\000\000", shutdown_cb = 0x0, enable_coredump = true, reserved65 = "\000\000", mem_channel = -1, main_core = -1, mem_size = -1, no_pci = false, hugepage_single_segments = false, unlink_hugepage = false, no_huge = false,
          reserved84 = "\000\000\000", hugedir = 0x0, print_level = SPDK_LOG_INFO, reserved100 = "\000\000\000", num_pci_addr = 0, pci_blocked = 0x0, pci_allowed = 0x0, iova_mode = 0x0, delay_subsystem_init = true, reserved137 = "\000\000\000\000\000\000", num_entries = 32768,
          env_context = 0x0, log = 0x0, base_virtaddr = 35184372088832, opts_size = 253, disable_signal_handlers = false, interrupt_mode = false, enforce_numa = false, reserved187 = "\000\000\000\000", msg_mempool_size = 0, rpc_allowlist = 0x0, vf_token = 0x0, lcore_map = 0x0,
          rpc_log_level = SPDK_LOG_DISABLED, rpc_log_file = 0x0, json_data = 0x0, json_data_size = 0, disable_cpumask_locks = false}
        rc = 1
(gdb)

```

**Comment by jimharris** [comment]
https://review.spdk.io/gerrit/c/spdk/spdk/+/25200 should fix this.
