### ISSUE TITLE
[nvmf_shutdown_tc4] spdk_nvme_perf: nvme_rdma.c:1837: nvme_rdma_qpair_destroy: Assertion `qpair->poll_group' failed.

### ISSUE THREAD

**Issue by mikeBashStuff** [spdk/spdk#3569]
# CI Intermittent Failure

https://ci.spdk.io/results/autotest-per-patch/builds/132064/archive/nvmf-phy-autotest_86818/build.log

Point of failure:

```
00:23:57.975  [2024-11-05 16:48:13.992902] nvme_qpair.c: 812:spdk_nvme_qpair_process_completions: *ERROR*: [nqn.2016-06.io.spdk:cnode9, 1] CQ transport error -6 (No such device or address) on qpair id 0
00:23:57.975  [2024-11-05 16:48:13.992976] nvme_ctrlr.c:1110:nvme_ctrlr_fail: *ERROR*: [nqn.2016-06.io.spdk:cnode9, 1] in failed state.
00:23:57.975  spdk_nvme_perf: nvme_rdma.c:1837: nvme_rdma_qpair_destroy: Assertion `qpair->poll_group' failed.
00:24:01.266  /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh: line 653: 1661775 Aborted                 (core dumped) $rootdir/build/bin/spdk_nvme_perf -q 128 -o 45056 -O 4096 -w randwrite -t 20 -r "trtype:$TEST_TRANSPORT adrfam:IPV4 traddr:$NVMF_FIRST_TARGET_IP trsvcid:$NVMF_PORT" -P 4
00:24:01.266   16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@653 -- # es=134
00:24:01.266   16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@661 -- # (( es > 128 ))
00:24:01.266   16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@662 -- # es=6
00:24:01.266   16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@663 -- # case "$es" in
00:24:01.266   16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@669 -- # es=0
00:24:01.266   16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@677 -- # (( !es == 0 ))
00:24:01.266    16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@677 -- # trap - ERR
00:24:01.266    16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@677 -- # print_backtrace
00:24:01.266    16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@1155 -- # [[ ehxBET =~ e ]]
00:24:01.266    16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@1157 -- # args=('1661775' 'wait' 'nvmf_shutdown_tc4' 'nvmf_shutdown_tc4' '--transport=rdma')
00:24:01.266    16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@1157 -- # local args
00:24:01.266    16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@1159 -- # xtrace_disable
00:24:01.266    16:48:17 nvmf_rdma.nvmf_target_extra.nvmf_shutdown.nvmf_shutdown_tc4 -- common/autotest_common.sh@10 -- # set +x
00:24:01.266  ========== Backtrace start: ==========
00:24:01.266  
00:24:01.266  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:677 -> NOT(["wait"],["1661775"])
00:24:01.266       ...
00:24:01.266     672 		elif [[ -n ${EXIT_STATUS:-} ]] && ((es != EXIT_STATUS)); then
00:24:01.266     673 			es=0
00:24:01.266     674 		fi
00:24:01.266     675 	
00:24:01.266     676 		# invert error code of any command and also trigger ERR on 0 (unlike bash ! prefix)
00:24:01.266  => 677 		((!es == 0))
00:24:01.266     678 	}
00:24:01.266     679 	
00:24:01.266     680 	function timing() {
00:24:01.266     681 		direction="$1"
00:24:01.266     682 		testname="$2"
00:24:01.266       ...
00:24:01.266  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/shutdown.sh:158 -> nvmf_shutdown_tc4([])
00:24:01.266       ...
00:24:01.266     153 	
00:24:01.266     154 		# Kill the target half way through
00:24:01.266     155 		killprocess $nvmfpid
00:24:01.266     156 		sleep 1
00:24:01.266     157 		# Due to IOs are completed with errors, perf exits with bad status
00:24:01.266  => 158 		NOT wait $perfpid
00:24:01.266     159 		stoptarget
00:24:01.266     160 	}
00:24:01.266     161 	
00:24:01.266     162 	run_test "nvmf_shutdown_tc1" nvmf_shutdown_tc1
00:24:01.266     163 	run_test "nvmf_shutdown_tc2" nvmf_shutdown_tc2
00:24:01.266       ...
00:24:01.266  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/common/autotest_common.sh:1127 -> run_test(["nvmf_shutdown_tc4"],["nvmf_shutdown_tc4"])
00:24:01.266       ...
00:24:01.266     1122		timing_enter $test_name
00:24:01.266     1123		echo "************************************"
00:24:01.266     1124		echo "START TEST $test_name"
00:24:01.266     1125		echo "************************************"
00:24:01.266     1126		xtrace_restore
00:24:01.266     1127		time "$@"
00:24:01.266     1128		xtrace_disable
00:24:01.266     1129		echo "************************************"
00:24:01.266     1130		echo "END TEST $test_name"
00:24:01.266     1131		echo "************************************"
00:24:01.266     1132		timing_exit $test_name
00:24:01.266       ...
00:24:01.266  in /var/jenkins/workspace/nvmf-phy-autotest/spdk/test/nvmf/target/shutdown.sh:167 -> main(["--transport=rdma"])
00:24:01.266       ...
00:24:01.266     162 	run_test "nvmf_shutdown_tc1" nvmf_shutdown_tc1
00:24:01.266     163 	run_test "nvmf_shutdown_tc2" nvmf_shutdown_tc2
00:24:01.266     164 	run_test "nvmf_shutdown_tc3" nvmf_shutdown_tc3
00:24:01.266     165 	# Temporarily disable on e810 due to issue #3523
00:24:01.266     166 	if ! [[ "$SPDK_TEST_NVMF_NICS" == "e810" && "$TEST_TRANSPORT" == "rdma" ]]; then
00:24:01.266  => 167 		run_test "nvmf_shutdown_tc4" nvmf_shutdown_tc4
00:24:01.266     168 	fi
00:24:01.266     169 	
00:24:01.266     170 	trap - SIGINT SIGTERM EXIT
00:24:01.266       ...
00:24:01.266  
00:24:01.266  ========== Backtrace end ==========
```

bt:

```
00:24:11.255  Core was generated by `/var/jenkins/workspace/nvmf-phy-autotest/spdk/build/bin/spdk_nvme_perf -q 128 -'.
00:24:11.255  Program terminated with signal SIGABRT, Aborted.
00:24:11.255  #0  0x00007f7931c61834 in __pthread_kill_implementation () from /usr/lib64/libc.so.6
00:24:11.255  [Current thread is 1 (Thread 0x7f7931173a00 (LWP 1661775))]
00:24:11.255  
00:24:11.255  Thread 3 (Thread 0x7f79310006c0 (LWP 1661795)):
00:24:11.255  #0  0x00007f7931ce6e62 in epoll_wait () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #1  0x00007f79327aa867 in eal_intr_handle_interrupts (pfd=5, totalfds=1) at ../lib/eal/linux/eal_interrupts.c:1077
00:24:11.255          events = {{events = 0, data = {ptr = 0x0, fd = 0, u32 = 0, u64 = 0}}}
00:24:11.255          nfds = 0
00:24:11.255  #2  0x00007f79327aaaa4 in eal_intr_thread_main (arg=0x0) at ../lib/eal/linux/eal_interrupts.c:1163
00:24:11.255          pipe_event = {events = 3, data = {ptr = 0x3, fd = 3, u32 = 3, u64 = 3}}
00:24:11.255          src = 0x0
00:24:11.255          numfds = 1
00:24:11.255          pfd = 5
00:24:11.255          __func__ = "eal_intr_thread_main"
00:24:11.255  #3  0x00007f7932788ce7 in control_thread_start (arg=0x1d37e60) at ../lib/eal/common/eal_common_thread.c:282
00:24:11.255          params = 0x1d37e60
00:24:11.255          start_arg = 0x0
00:24:11.255          start_routine = 0x7f79327aa8d6 <eal_intr_thread_main>
00:24:11.255  #4  0x00007f79327a1a30 in thread_start_wrapper (arg=0x7ffe5a2371e0) at ../lib/eal/unix/rte_thread.c:114
00:24:11.255          ctx = 0x7ffe5a2371e0
00:24:11.255          thread_func = 0x7f7932788c98 <control_thread_start>
00:24:11.255          thread_args = 0x1d37e60
00:24:11.255          ret = 0
00:24:11.255  #5  0x00007f7931c5f897 in start_thread () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #6  0x00007f7931ce6a5c in clone3 () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  
00:24:11.255  Thread 2 (Thread 0x7f792f6006c0 (LWP 1661834)):
00:24:11.255  #0  0x00007f7931caa163 in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #1  0x00007f7931cbcc97 in nanosleep () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #2  0x00007f7931cce5d3 in sleep () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #3  0x00000000004209b6 in nvme_poll_ctrlrs (arg=0x0) at perf.c:3197
00:24:11.255          entry = 0x0
00:24:11.255          oldstate = 1
00:24:11.255          rc = -6
00:24:11.255  #4  0x00007f7931c5f897 in start_thread () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #5  0x00007f7931ce6a5c in clone3 () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  
00:24:11.255  Thread 1 (Thread 0x7f7931173a00 (LWP 1661775)):
00:24:11.255  #0  0x00007f7931c61834 in __pthread_kill_implementation () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #1  0x00007f7931c0f8ee in raise () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.255  #2  0x00007f7931bf78ff in abort () from /usr/lib64/libc.so.6
00:24:11.255  No symbol table info available.
00:24:11.256  #3  0x00007f7931bf781b in __assert_fail_base.cold () from /usr/lib64/libc.so.6
00:24:11.256  No symbol table info available.
00:24:11.256  #4  0x00007f7931c07c57 in __assert_fail () from /usr/lib64/libc.so.6
00:24:11.256  No symbol table info available.
00:24:11.256  #5  0x00007f7932d50fd0 in nvme_rdma_qpair_destroy (rqpair=0x200000200440) at nvme_rdma.c:1837
00:24:11.256          group = 0x7f79329b49c2 <bit_array_get_word+249>
00:24:11.256          qpair = 0x200000200440
00:24:11.256          rctrlr = 0x2000003ac1c0
00:24:11.256          entry = 0x0
00:24:11.256          tmp = 0x200000200440
00:24:11.256          __PRETTY_FUNCTION__ = "nvme_rdma_qpair_destroy"
00:24:11.256  #6  0x00007f7932d51d2b in nvme_rdma_qpair_disconnected (rqpair=0x200000200440, ret=0) at nvme_rdma.c:1899
00:24:11.256          __func__ = "nvme_rdma_qpair_disconnected"
00:24:11.256  #7  0x00007f7932d5323b in nvme_rdma_ctrlr_delete_io_qpair (ctrlr=0x2000003ac1c0, qpair=0x200000200440) at nvme_rdma.c:2075
00:24:11.256          rc = 0
00:24:11.256          rqpair = 0x200000200440
00:24:11.256          __PRETTY_FUNCTION__ = "nvme_rdma_ctrlr_delete_io_qpair"
00:24:11.256          __func__ = "nvme_rdma_ctrlr_delete_io_qpair"
00:24:11.256  #8  0x00007f7932cd22e7 in nvme_transport_ctrlr_delete_io_qpair (ctrlr=0x2000003ac1c0, qpair=0x200000200440) at nvme_transport.c:476
00:24:11.256          transport = 0x7f7932e591c0 <g_transports+896>
00:24:11.256          rc = 8192
00:24:11.256          __PRETTY_FUNCTION__ = "nvme_transport_ctrlr_delete_io_qpair"
00:24:11.256          __func__ = "nvme_transport_ctrlr_delete_io_qpair"
00:24:11.256  #9  0x00007f7932c3f766 in spdk_nvme_ctrlr_free_io_qpair (qpair=0x200000200440) at nvme_ctrlr.c:643
00:24:11.256          ctrlr = 0x2000003ac1c0
00:24:11.256  #10 0x000000000040d426 in nvme_cleanup_ns_worker_ctx (ns_ctx=0x1e4dd30) at perf.c:1092
00:24:11.256          i = 1
00:24:11.256  #11 0x00000000004142dd in cleanup_ns_worker_ctx (ns_ctx=0x1e4dd30) at perf.c:1647
00:24:11.256          task = 0x0
00:24:11.256          ttask = 0x0
00:24:11.256  #12 0x0000000000416dbe in work_fn (arg=0x1d30480) at perf.c:1868
00:24:11.256          tsc_start = 27797414730031762
00:24:11.256          tsc_end = 27797460730031762
00:24:11.256          tsc_current = 27797428460657998
00:24:11.256          tsc_next_print = 27797428530031762
00:24:11.256          worker = 0x1d30480
00:24:11.256          ns_ctx = 0x1e4dd30
00:24:11.256          unfinished_ns_ctx = 0
00:24:11.256          warmup = false
00:24:11.256          rc = -1
00:24:11.256          check_rc = 0
00:24:11.256          check_now = 27797428460640750
00:24:11.256          swap = {tqh_first = 0xf, tqh_last = 0x7f793294689a <rte_lcore_id+28>}
00:24:11.256          task = 0x42064a <associate_workers_with_ns+520>
00:24:11.256  #13 0x00000000004215cf in main (argc=15, argv=0x7ffe5a2377e8) at perf.c:3354
00:24:11.256          rc = 0
00:24:11.256          worker = 0x0
00:24:11.256          main_worker = 0x1d30480
00:24:11.256          ns_ctx = 0x7f7931c6f373 <_int_malloc+3715>
00:24:11.256          opts = {name = 0x43757a "perf", core_mask = 0x7f793295167c "0x1", lcore_map = 0x0, shm_id = -1, mem_channel = -1, main_core = -1, mem_size = -1, no_pci = true, hugepage_single_segments = false, unlink_hugepage = false, no_huge = false, reserved = 0, num_pci_addr = 0, hugedir = 0x0, pci_blocked = 0x0, pci_allowed = 0x453860 <g_allowed_pci_addr>, iova_mode = 0x0, base_virtaddr = 35184372088832, env_context = 0x0, vf_token = 0x0, opts_size = 128, enforce_numa = false, reserved2 = "\000\000\000\000\000\000"}
00:24:11.256          thread_id = 140158462592704
00:24:11.256          __PRETTY_FUNCTION__ = "main"
00:24:11.256  
00:24:11.256  --
```

This test was already disabled under  e810 + rdma via 78d09f1ff9  (see #3523), setup above is mlx-based.

**Comment by mikeBashStuff** [comment]
https://ci.spdk.io/results/autotest-per-patch/builds/132064/archive/nvmf-phy-autotest_86818/index.html

**Comment by jimharris** [comment]
[Bug scrub] Assigning to @AlekseyMarchuk, he will take a look.

**Comment by AlekseyMarchuk** [comment]
Fix is here:
https://review.spdk.io/gerrit/c/spdk/spdk/+/25513

**Comment by AlekseyMarchuk** [comment]
The fix is merger, closing the issue
