### ISSUE TITLE
Assertion assert(first) in function  spdk_rdma_qp_queue_send_wrs hit during stressing out the spdk memory allocator

### ISSUE THREAD

**Issue by krchug** [spdk/spdk#3586]
# Sighting report

I have been tracing a qpair corruption and as a part of this I was trying to stress out the spdk allocator. 

The following changes are done to the spdk code:

1. Added a mempool allocate in nvmf_tgt_started function as under
```
#define MAX_POOL 4
typedef struct dummy_pool_entry_t {
    uint64_t arr[10];
} dummy_pool_entry_t;


struct spdk_mempool *g_mempool_ptr[MAX_POOL];

        static void
nvmf_tgt_started(void *arg1)
{
        char  name[40];
        if (getenv("MEMZONE_DUMP") != NULL) {
                spdk_memzone_dump(stdout);
                fflush(stdout);
        }
        memset(name, sizeof(char), 40);
    for(uint32_t i = 0; i < MAX_POOL; i++) {
    snprintf(name, 40, "DUMMY_POOL__%u", i);
            g_mempool_ptr[i] = spdk_mempool_create(name,
                        192675840,
                        sizeof(dummy_pool_entry_t),
                        SPDK_MEMPOOL_DEFAULT_CACHE_SIZE,
                        SPDK_ENV_SOCKET_ID_ANY);
            assert(g_mempool_ptr[i]);
    }
    SPDK_NOTICELOG("DONE\n");
}
```
2. Added an rpc in nvmf to start a poller and allocate 2Gb, 512MB, 16K and 1MB buffers every 1 second 
```
#define CONVERT_TICKS_TO_USEC(x) \
    (((x) * SPDK_SEC_TO_USEC)/spdk_get_ticks_hz())

static int
nvmf_allocator_poller(void *ctx)
{
        void *buf = NULL;
        uint64_t now = 0;
        uint64_t then = 0;
        uint64_t size = 0;

        now = spdk_get_ticks();

        if (g_counter % 4 == 0) {
                size = 2147483648;
                buf = spdk_dma_zmalloc(2147483648, 0, NULL);
        }else if (g_counter %3 == 0) {
                size = 1048576;
                buf = spdk_dma_zmalloc(1048576, 0, NULL);
        } else if (g_counter %2) {
                size = 536870912;
                buf = spdk_dma_zmalloc(536870912, 0, NULL);
        } else if (g_counter %5) {
                size = 16384;
                buf = spdk_dma_zmalloc(16384, 0, NULL);
        } else {
                size = 131072;
                buf = spdk_dma_zmalloc(131072, 0, NULL);
        }

        then = spdk_get_ticks() - now;

//assert(buf != NULL);
        if (buf != NULL) {
        g_counter ++;
        SPDK_WARNLOG("count %u: Allocated buffer %p size %lu time taken %llu usec\n", g_counter, buf, size,
                        CONVERT_TICKS_TO_USEC(then));
        } else {
        g_counter++;
                SPDK_NOTICELOG("STOP\n");
        }

        return SPDK_POLLER_BUSY;
}

static void
rpc_nvmf_start_poller(struct spdk_jsonrpc_request *request,
                  const struct spdk_json_val *params)
{
        int rc = EXIT_SUCCESS;
        if (g_poller == NULL) {
                SPDK_NOTICELOG("KRC: STARTING POLLER\n");
                g_counter = 0;
                g_poller = SPDK_POLLER_REGISTER(nvmf_allocator_poller,
                                        NULL,
                                        100000);
                assert(g_poller);
        } else {
                SPDK_NOTICELOG("KRC: STOPPING POLLER\n");
                spdk_poller_pause(g_poller);
                spdk_poller_unregister(&g_poller);
        }

        spdk_jsonrpc_send_bool_response(request, true);
}
SPDK_RPC_REGISTER("rpc_nvmf_start_poller", rpc_nvmf_start_poller, SPDK_RPC_STARTUP|SPDK_RPC_RUNTIME)
```

The setup looks something like this:

1. I have a target i.e. sn1 that exposes out 4 nvme drives via a subsystem with config as under
```
{
  "subsystems": [
    {
      "subsystem": "nvmf",
      "config": [
        {
          "method": "nvmf_create_transport",
          "params": {
            "trtype": "RDMA",
            "max_io_qpairs_per_ctrlr": 127,
            "in_capsule_data_size": 8192
          }
        },
	{
          "method": "nvmf_create_transport",
          "params": {
            "trtype": "tcp"
          }
        }
      ]
    },
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_set_options",
          "params": {
            "action_on_timeout": "abort",
            "timeout_us": 10000000,
            "transport_retry_count": 7,
            "bdev_retry_count": 3,
            "ctrlr_loss_timeout_sec": -1,
            "reconnect_delay_sec": 1
          }
        },
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "trtype": "PCIe",
            "name": "nvme0",
            "traddr": "20:00.0"
          }
        },
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "trtype": "PCIe",
            "name": "nvme1",
            "traddr": "21:00.0"
          }
        },
         {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "trtype": "PCIe",
            "name": "nvme2",
            "traddr": "43:00.0"
          }
        },
         {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "trtype": "PCIe",
            "name": "nvme3",
            "traddr": "44:00.0"
          }
        },
 
        {
          "method": "nvmf_create_subsystem",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx",
            "serial_number": "controller1_0",
            "model_number": "controller1_0",
            "ana_reporting": true,
            "allow_any_host":true
          }
        },
        {
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx",
            "namespace": {
              "bdev_name": "nvme0n1"
            }
          }
        },
	{
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx",
            "namespace": {
              "bdev_name": "nvme1n1"
            }
          }
        },
{
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx",
            "namespace": {
              "bdev_name": "nvme2n1"
            }
          }
        },
{
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx",
            "namespace": {
              "bdev_name": "nvme3n1"
            }
          }
        },

        {
          "method": "nvmf_subsystem_add_listener",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx",
            "listen_address": {
              "trtype": "RDMA",
              "adrfam": "IPv4",
              "traddr": "192.168.11.15",
              "trsvcid": "4420"
            }
          }
        },
        {
          "method": "nvmf_subsystem_add_listener",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx",
            "listen_address": {
              "trtype": "RDMA",
              "adrfam": "IPv4",
              "traddr": "192.168.10.15",
              "trsvcid": "4420"
            }
          }
        }

    ]
    }
    ]
}
```
2. I have another node i.e. sn3, which connects to these subsystems and exposes it out to a client with the following config
```
 {
  "subsystems": [
    {
      "subsystem": "nvmf",
      "config": [
        {
          "method": "nvmf_create_transport",
          "params": {
            "trtype": "RDMA",
            "max_io_qpairs_per_ctrlr": 127,
            "in_capsule_data_size": 8192
          }
        },
	{
          "method": "nvmf_create_transport",
          "params": {
            "trtype": "tcp"
          }
        }

      ]
    },
    {
      "subsystem": "bdev",
      "config": [
        {
          "method": "bdev_nvme_set_options",
          "params": {
            "action_on_timeout": "abort",
            "timeout_us": 1000000,
            "transport_retry_count": 7,
            "bdev_retry_count": 3,
            "ctrlr_loss_timeout_sec": -1,
            "reconnect_delay_sec": 1
          }
        },
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "name": "hed2_1_1",
            "trtype": "RDMA",
            "adrfam": "IPv4",
            "traddr": "192.168.11.15",
            "trsvcid": "4420",
            "subnqn": "nqn.2018-09.io.ngx:ngx",
            "ctrlr_loss_timeout_sec": -1,
            "reconnect_delay_sec": 1
          }
        },
        {
          "method": "bdev_nvme_attach_controller",
          "params": {
            "name": "hed2_1_1",
            "trtype": "RDMA",
            "adrfam": "IPv4",
            "traddr": "192.168.10.15",
            "trsvcid": "4420",
            "subnqn": "nqn.2018-09.io.ngx:ngx",
            "ctrlr_loss_timeout_sec": -1,
            "reconnect_delay_sec": 1,
            "multipath": "multipath"
          }
        },
	{
          "method": "nvmf_create_subsystem",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx_out",
            "serial_number": "controller1_0",
            "model_number": "controller1_0",
            "ana_reporting": true,
            "allow_any_host":true
          }
        },
	{
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx_out",
            "namespace": {
              "bdev_name": "hed2_1_1n1"
            }
          }
        },
	{
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx_out",
            "namespace": {
              "bdev_name": "hed2_1_1n2"
            }
          }
        },
	{
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx_out",
            "namespace": {
              "bdev_name": "hed2_1_1n3"
            }
          }
        },
	{
          "method": "nvmf_subsystem_add_ns",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx_out",
            "namespace": {
              "bdev_name": "hed2_1_1n4"
            }
          }
        },

	{
          "method": "nvmf_subsystem_add_listener",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx_out",
            "listen_address": {
              "trtype": "RDMA",
              "adrfam": "IPv4",
              "traddr": "172.17.10.17",
              "trsvcid": "4420"
            }
          }
        },
        {
          "method": "nvmf_subsystem_add_listener",
          "params": {
            "nqn": "nqn.2018-09.io.ngx:ngx_out",
            "listen_address": {
              "trtype": "RDMA",
              "adrfam": "IPv4",
              "traddr": "172.17.11.17",
              "trsvcid": "4420"
            }
          }
        }


    ]
    }
    ]
}
```
3. The client does a simple write fio on these 4 devices

Test case steps:

1. Start sn1 that exposes 4 nvme drives via a subsystem. Since the mempool allocations take time, the listener would be added but the mempool allocation will still take time to finish.
2. Start sn3 that connects to this node and exposes the drives out to the client. This will fail since the target is busy in mempool allocation which is expected.
```
sudo ./nvmf_tgt -m 0xff -c kc_snt3.conf 
[2024-12-11 05:01:00.654732] Starting SPDK v24.05 git sha1 40a5c2189 / DPDK 24.03.0 initialization...
[2024-12-11 05:01:00.654912] [ DPDK EAL parameters: nvmf --no-shconf -c 0xff --huge-unlink --no-telemetry --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid12431 ]
[2024-12-11 05:01:00.936453] app.c: 909:spdk_app_start: *NOTICE*: Total cores available: 8
[2024-12-11 05:01:01.027913] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 1
[2024-12-11 05:01:01.027989] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 3
[2024-12-11 05:01:01.027947] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 2
[2024-12-11 05:01:01.028026] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 4
[2024-12-11 05:01:01.028062] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 5
[2024-12-11 05:01:01.028143] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 6
[2024-12-11 05:01:01.028296] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 0
[2024-12-11 05:01:01.028327] reactor.c: 937:reactor_run: *NOTICE*: Reactor started on core 7
[2024-12-11 05:01:01.100005] rdma.c:2576:create_ib_device: *NOTICE*: Create IB device mlx5_0(0x558a7879ae00/0x558a7879f580) succeed.
[2024-12-11 05:01:01.101744] rdma.c:2576:create_ib_device: *NOTICE*: Create IB device mlx5_1(0x558a78799350/0x558a787e0c10) succeed.
[2024-12-11 05:01:01.103704] rdma.c:2576:create_ib_device: *NOTICE*: Create IB device mlx5_2(0x558a7879d050/0x558a788222a0) succeed.
[2024-12-11 05:01:01.105632] rdma.c:2576:create_ib_device: *NOTICE*: Create IB device mlx5_3(0x558a7879e230/0x558a78863930) succeed.
[2024-12-11 05:01:01.456493] tcp.c: 672:nvmf_tcp_create: *NOTICE*: *** TCP Transport Init ***
[2024-12-11 05:01:01.468731] nvme_rdma.c:1853:nvme_rdma_ctrlr_create_qpair: *NOTICE*: KRC: CTRLR 0x2000675024c0 RQPAIR 0x20009a6d7d80 qpair 0x20009a6d7d80 allocated
[2024-12-11 05:01:02.475774] nvme_rdma.c:1167:nvme_rdma_connect_established: *ERROR*: RDMA connect error -99
[2024-12-11 05:01:02.475810] nvme_rdma.c:2751:nvme_rdma_qpair_process_completions: *ERROR*: Failed to connect rqpair=0x20009a6d7d80
[2024-12-11 05:01:03.476987] nvme_rdma.c:1865:nvme_rdma_qpair_destroy: *NOTICE*: KRC: CTRLR 0x2000675024c0 RQPAIR 0x20009a6d7d80 qpair 0x20009a6d7d80 destroy
[2024-12-11 05:01:03.478552] nvme_qpair.c: 804:spdk_nvme_qpair_process_completions: *ERROR*: CQ transport error -6 (No such device or address) on qpair id 0
[2024-12-11 05:01:03.478569] nvme_ctrlr.c:1042:nvme_ctrlr_fail: *ERROR*: [nqn.2018-09.io.ngx:ngx] in failed state.
[2024-12-11 05:01:03.478578] nvme_ctrlr.c:4041:nvme_ctrlr_process_init: *ERROR*: [nqn.2018-09.io.ngx:ngx] Ctrlr is in error state
[2024-12-11 05:01:03.478592] nvme.c: 708:nvme_ctrlr_poll_internal: *ERROR*: Failed to initialize SSD: 192.168.11.15
[2024-12-11 05:01:03.478599] nvme_ctrlr.c:1031:nvme_ctrlr_fail: *NOTICE*: [nqn.2018-09.io.ngx:ngx] already in failed state
[2024-12-11 05:01:03.478608] nvme_rdma.c:2126:nvme_rdma_ctrlr_delete_io_qpair: *NOTICE*: KRC: CTRLR 0x2000675024c0 RQPAIR 0x20009a6d7d80 QPAIR 0x20009a6d7d80 trtype 1 about to delete
[2024-12-11 05:01:03.480590] json_config.c: 204:rpc_client_poller: *ERROR*: error response: 
{
  "code": -5,
  "message": "Input/output error"
}
[2024-12-11 05:01:03.480659] app.c: 378:app_start_application: *ERROR*: Failed to load subsystems for RUNTIME state with code: -22
[2024-12-11 05:01:03.480669] app.c:1053:spdk_app_stop: *WARNING*: spdk_app_stop'd on non-zero
```
3. Wait for mempool allocations on sn1 to complete
4. Now start sn3 which connects to this subsystem and exposes those 4 drives out to the client and wait for the mempool allocation to complete
5. Start fio on client on all 4 drives
6. Fire the rpc on sn3 to start zmallocing buffers
```
sudo ./rpc.py rpc_nvmf_start_poller
```
7. After almost 60 buffer allocations, I see timeouts and disconnects on sn3 for the subsystem that came from sn1
8. After a period of time the resets start failing and we hit the below assertion on sn1. Please note the fio stops on the client at this point
```

Thread 4 "reactor_2" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6663640 (LWP 137557)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737327281728) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737327281728) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737327281728) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737327281728, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7756476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff773c7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff773c71b in __assert_fail_base (fmt=0x7ffff78f1130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555555a00cce "first", file=0x555555a00d10 "rdma_verbs.c", 
    line=126, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff774de96 in __GI___assert_fail (assertion=0x555555a00cce "first", file=0x555555a00d10 "rdma_verbs.c", line=126, 
    function=0x555555a1e7c0 <__PRETTY_FUNCTION__.1.lto_priv.48> "spdk_rdma_qp_queue_send_wrs") at ./assert/assert.c:101
#7  0x00005555556ba59e in spdk_rdma_qp_queue_send_wrs (spdk_rdma_qp=0x7fffe8a55e30, first=0x0) at ../../lib/rdma/rdma_verbs.c:126
#8  0x0000555555654f13 in request_transfer_in (req=0x20004f1310a8) at ../../lib/nvmf/rdma.c:1096
#9  0x0000555555658714 in nvmf_rdma_request_process (rtransport=0x555555de5580, rdma_req=0x20004f1310a8) at ../../lib/nvmf/rdma.c:2214
#10 0x000055555565fcc4 in nvmf_rdma_poller_poll (rtransport=0x555555de5580, rpoller=0x7fffe800fbd0) at ../../lib/nvmf/rdma.c:4739
#11 0x0000555555660157 in nvmf_rdma_poll_group_poll (group=0x7fffe800f0e0) at ../../lib/nvmf/rdma.c:4867
#12 0x000055555563d102 in nvmf_transport_poll_group_poll (group=0x7fffe800f0e0) at ../../lib/nvmf/transport.c:728
#13 0x000055555562ce5e in nvmf_poll_group_poll (ctx=0x7fffe8000e70) at ../../lib/nvmf/nvmf.c:157
#14 0x00005555557058c3 in thread_execute_poller (thread=0x555555fe9de0, poller=0x7fffe8000f30) at ../../lib/thread/thread.c:959
#15 0x0000555555705e6c in thread_poll (thread=0x555555fe9de0, max_msgs=0, now=22851223211044) at ../../lib/thread/thread.c:1085
#16 0x000055555570614d in spdk_thread_poll (thread=0x555555fe9de0, max_msgs=0, now=22851223211044) at ../../lib/thread/thread.c:1173
#17 0x00005555556c0a1f in _reactor_run (reactor=0x555555dbaa00) at ../../lib/event/reactor.c:914
#18 0x00005555556c0b08 in reactor_run (arg=0x555555dbaa00) at ../../lib/event/reactor.c:952
#19 0x000055555576a324 in eal_thread_loop (arg=0x2) at ../../dpdk/build-tmp/../lib/eal/common/eal_common_thread.c:212
#20 0x000055555578660d in eal_worker_thread_loop (arg=0x2) at ../../dpdk/build-tmp/../lib/eal/linux/eal.c:916
#21 0x00007ffff77a8ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#22 0x00007ffff783a850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) f 7
#7  0x00005555556ba59e in spdk_rdma_qp_queue_send_wrs (spdk_rdma_qp=0x7fffe8a55e30, first=0x0) at ../../lib/rdma/rdma_verbs.c:126
126		assert(first);
(gdb) l -
121	spdk_rdma_qp_queue_send_wrs(struct spdk_rdma_qp *spdk_rdma_qp, struct ibv_send_wr *first)
122	{
123		struct ibv_send_wr *last;
124	
125		assert(spdk_rdma_qp);
126		assert(first);
127	
128		spdk_rdma_qp->stats->send.num_submitted_wrs++;
129		last = first;
130		while (last->next != NULL) {
(gdb) p first
$1 = (struct ibv_send_wr *) 0x0
(gdb) p *spdk_rdma_qp
$2 = {qp = 0x7fffe8af1628, cm_id = 0x555557825bc0, send_wrs = {first = 0x0, last = 0x20004f12f9c8}, recv_wrs = {first = 0x0, last = 0x0}, stats = 0x7fffe800fc50, shared_stats = true}
(gdb) p *spdk_rdma_qp->qp 
$3 = {context = 0x55555628d800, qp_context = 0x555557825e70, pd = 0x555555de56e0, send_cq = 0x7fffe8130430, recv_cq = 0x7fffe8130430, srq = 0x7fffe800fcf8, handle = 36, qp_num = 335, 
  state = IBV_QPS_RTS, qp_type = IBV_QPT_RC, mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, 
        __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, cond = {__data = {__wseq = {__value64 = 0, __value32 = {__low = 0, __high = 0}}, __g1_start = {
        __value64 = 0, __value32 = {__low = 0, __high = 0}}, __g_refs = {0, 0}, __g_size = {0, 0}, __g1_orig_size = 0, __wrefs = 0, __g_signals = {0, 0}}, 
    __size = '\000' <repeats 47 times>, __align = 0}, events_completed = 0}
(gdb) info locals
last = 0x0
__PRETTY_FUNCTION__ = "spdk_rdma_qp_queue_send_wrs"
(gdb) 
```

## Expected Behavior

The reset should complete, buffer allocations should fail and return buf=null and the io should continue.

## Current Behavior

Assertion hit in spdk_rdma_qp_queue_send_wrs

## Steps to Reproduce

Mentioned above

## Context (Environment including OS version, SPDK version, etc.)

Using Ubuntu 22.04.3 LTS & 5.15.0-100-generic kernel version. 
Using 5.8-OFED.5.8.4.1.5.1 version of ofed drivers and
Mellanox Technologies MT27800 Family [ConnectX-5] network adapters.
SPDK 24.05

**Comment by devmsb** [comment]
Any fix available?
