### ISSUE TITLE
ASAN errors when construct_raid_bdev with bdev that doesn't exist more than twice

### ISSUE THREAD

**Issue by ChenWang01** [spdk/spdk#372]
The SPDK target will report ASAN  error when construct_raid_bdev with bdev that doesn't exist more than twice.

## Expected Behavior
Target should be normal.

## Current Behavior

```
Starting SPDK v18.07-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: nvmf -c 0x1 --file-prefix=spdk_pid14358 ]
EAL: Detected 36 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Multi-process socket /var/run/.spdk_pid14358_unix
EAL: Probing VFIO support...
app.c: 530:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
bdev_raid_rpc.c: 264:raid_bdev_config_cleanup: *ERROR*: Config memory allocation failed
=================================================================
==14358==ERROR: AddressSanitizer: attempting double-free on 0x603000001e10 in thread T0 (reactor_0):
    #0 0x7f5c9dfe7c40 in realloc (/lib64/libasan.so.4+0xdec40)
    #1 0x48b275 in spdk_rpc_construct_raid_bdev /home/wangchen/spdk/lib/bdev/raid/bdev_raid_rpc.c:379
    #2 0x4dca2d in parse_single_request /home/wangchen/spdk/lib/jsonrpc/jsonrpc_server.c:116
    #3 0x4dca2d in spdk_jsonrpc_parse_request /home/wangchen/spdk/lib/jsonrpc/jsonrpc_server.c:178
    #4 0x4ddf59 in spdk_jsonrpc_server_conn_recv /home/wangchen/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:242
    #5 0x4ddf59 in spdk_jsonrpc_server_poll /home/wangchen/spdk/lib/jsonrpc/jsonrpc_server_tcp.c:386
    #6 0x4c2b78 in spdk_rpc_subsystem_poll /home/wangchen/spdk/lib/event/rpc.c:51
    #7 0x4c15d5 in _spdk_reactor_run /home/wangchen/spdk/lib/event/reactor.c:541
    #8 0x4c2237 in spdk_reactors_start /home/wangchen/spdk/lib/event/reactor.c:692
    #9 0x4bef6c in spdk_app_start /home/wangchen/spdk/lib/event/app.c:576
    #10 0x406ef2 in main /home/wangchen/spdk/app/nvmf_tgt/nvmf_main.c:79
    #11 0x7f5c9c684f29 in __libc_start_main (/lib64/libc.so.6+0x20f29)
    #12 0x4094d9 in _start (/home/wangchen/spdk/app/nvmf_tgt/nvmf_tgt+0x4094d9)

0x603000001e10 is located 0 bytes inside of 32-byte region [0x603000001e10,0x603000001e30)
freed by thread T0 (reactor_0) here:
    #0 0x7f5c9dfe7c40 in realloc (/lib64/libasan.so.4+0xdec40)
    #1 0x48aa70 in raid_bdev_config_cleanup /home/wangchen/spdk/lib/bdev/raid/bdev_raid_rpc.c:259

previously allocated by thread T0 (reactor_0) here:
    #0 0x7f5c9dfe7c40 in realloc (/lib64/libasan.so.4+0xdec40)
    #1 0x48b275 in spdk_rpc_construct_raid_bdev /home/wangchen/spdk/lib/bdev/raid/bdev_raid_rpc.c:379

SUMMARY: AddressSanitizer: double-free (/lib64/libasan.so.4+0xdec40) in realloc
==14358==ABORTING

```
## Possible Solution
double free in "spdk/lib/bdev/raid/bdev_raid_rpc.c" file.

## Steps to Reproduce

1. ./app/nvmf_tgt/nvmf_tgt
2. ./rpc.py construct_raid_bdev -n raid0 -s 4096 -r 0 -b nvme0n1
3. ./rpc.py construct_raid_bdev -n raid0 -s 4096 -r 0 -b nvme0n1

## Context (Environment including OS version, SPDK version, etc.)
OS: Fedora release 27 (Twenty Seven)
Linux version: 4.17.3-100.fc27.x86_64
gcc version: 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)
SPDK: master (commit id: 051297114cb393d3eb1169520d474e81b4215bf0)

**Comment by ChenWang01** [comment]
submit patch https://review.gerrithub.io/#/c/spdk/spdk/+/419975/

**Comment by liang2yan** [comment]
close this issue since patch merged.
