### ISSUE TITLE
Memory leak when running spdk/test/nvme/overhead/overhead with asan

### ISSUE THREAD

**Issue by xuhuagen** [spdk/spdk#393]
I run script test/nvme/nvme.sh and memory leak occur when running test/nvme/overhead/overhead

the log as below:
```
==13640==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8768 byte(s) in 8 object(s) allocated from:
    #0 0x7ffff6efea38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x408416 in register_ns /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:140
    #2 0x408416 in register_ctrlr /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:185
    #3 0x408416 in attach_cb /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:609

Direct leak of 8320 byte(s) in 8 object(s) allocated from:
    #0 0x7ffff6efe850 in malloc (/lib64/libasan.so.4+0xde850)
    #1 0x4082bb in register_ctrlr /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:165
    #2 0x4082bb in attach_cb /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:609

Indirect leak of 475136 byte(s) in 8 object(s) allocated from:
    #0 0x7ffff6efea38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x4085c4 in spdk_histogram_data_alloc_sized /home/xuhuagen/spdk/include/spdk/histogram_data.h:217
    #2 0x4085c4 in spdk_histogram_data_alloc /home/xuhuagen/spdk/include/spdk/histogram_data.h:229
    #3 0x4085c4 in register_ns /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:154
    #4 0x4085c4 in register_ctrlr /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:185
    #5 0x4085c4 in attach_cb /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:609

Indirect leak of 475136 byte(s) in 8 object(s) allocated from:
    #0 0x7ffff6efea38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x40852c in spdk_histogram_data_alloc_sized /home/xuhuagen/spdk/include/spdk/histogram_data.h:217
    #2 0x40852c in spdk_histogram_data_alloc /home/xuhuagen/spdk/include/spdk/histogram_data.h:229
    #3 0x40852c in register_ns /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:153
    #4 0x40852c in register_ctrlr /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:185
    #5 0x40852c in attach_cb /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:609

Indirect leak of 128 byte(s) in 8 object(s) allocated from:
    #0 0x7ffff6efea38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x408582 in spdk_histogram_data_alloc_sized /home/xuhuagen/spdk/include/spdk/histogram_data.h:211
    #2 0x408582 in spdk_histogram_data_alloc /home/xuhuagen/spdk/include/spdk/histogram_data.h:229
    #3 0x408582 in register_ns /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:154
    #4 0x408582 in register_ctrlr /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:185
    #5 0x408582 in attach_cb /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:609

Indirect leak of 128 byte(s) in 8 object(s) allocated from:
    #0 0x7ffff6efea38 in __interceptor_calloc (/lib64/libasan.so.4+0xdea38)
    #1 0x4084ed in spdk_histogram_data_alloc_sized /home/xuhuagen/spdk/include/spdk/histogram_data.h:211
    #2 0x4084ed in spdk_histogram_data_alloc /home/xuhuagen/spdk/include/spdk/histogram_data.h:229
    #3 0x4084ed in register_ns /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:153
    #4 0x4084ed in register_ctrlr /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:185
    #5 0x4084ed in attach_cb /home/xuhuagen/spdk/test/nvme/overhead/overhead.c:609

SUMMARY: AddressSanitizer: 967616 byte(s) leaked in 48 allocation(s).

```
## Current Behavior
ASAN mem leak when running spdk/test/nvme/overhead/overhead
## Steps to Reproduce

1. cd /path/to/spdk
2. ./configure --with-rdma --enable-asan
3. make clean && make -j
4../test/nvme/nvme.sh

## Context (Environment including OS version, SPDK version, etc.)
Target machine:
OS: Fedora release 27
SPDK version: 2b3abb2a339cfb1033108808ffa7577b860cca09

**Comment by wanghailiangx** [comment]
The memory is not completely released, there are mutiple malloc list, but only the last one is released. So I free all.
I submit a patch to fix it. https://review.gerrithub.io/#/c/spdk/spdk/+/422682/.
