### ISSUE TITLE
vhost core dump

### ISSUE THREAD

**Issue by beef9999** [spdk/spdk#408]
QEMU 2.12

Starting SPDK v18.07 / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: vhost -c 0x1 -m 1024 --legacy-mem --file-prefix=spdk_pid24488 ]

SPDK 18.04 was OK, what did you change?

```
[ DPDK EAL parameters: vhost -c 0x1 -m 1024 --legacy-mem --file-prefix=spdk_pid42291 ]
EAL: Detected 32 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid42291/mp_socket
EAL: Probing VFIO support...
EAL: VFIO support initialized
app.c: 530:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 718:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 492:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
EAL: PCI device 0000:03:00.0 on NUMA socket 0
EAL:   probe driver: 8086:a54 spdk_nvme
EAL:   using IOMMU type 1 (Type 1)
vbdev_lvol.c:1264:_vbdev_lvs_examine_cb: *INFO*: Lvol store found on nvme0n1 - begin parsing
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 8 pages on device 4d0d6062-a7e2-4963-8fff-336b4d14139f
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 1 pages on device 4d0d6062-a7e2-4963-8fff-336b4d14139f
vbdev_lvol.c:1213:_vbdev_lvs_examine_finish: *INFO*: Opening lvol 4d0d6062-a7e2-4963-8fff-336b4d14139f succeeded
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 8 pages on device adda0580-ffbd-4418-b40d-00262642cd59
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 1 pages on device adda0580-ffbd-4418-b40d-00262642cd59
vbdev_lvol.c:1213:_vbdev_lvs_examine_finish: *INFO*: Opening lvol adda0580-ffbd-4418-b40d-00262642cd59 succeeded
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 8 pages on device 0fb959d6-61c7-4745-a4fc-edd89fe0bb60
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 1 pages on device 0fb959d6-61c7-4745-a4fc-edd89fe0bb60
vbdev_lvol.c:1213:_vbdev_lvs_examine_finish: *INFO*: Opening lvol 0fb959d6-61c7-4745-a4fc-edd89fe0bb60 succeeded
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 8 pages on device 0d30ff91-42df-4e24-a0de-96c93ab7e651
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 1 pages on device 0d30ff91-42df-4e24-a0de-96c93ab7e651
vbdev_lvol.c:1213:_vbdev_lvs_examine_finish: *INFO*: Opening lvol 0d30ff91-42df-4e24-a0de-96c93ab7e651 succeeded
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 8 pages on device 7b8de2bc-5975-4d8d-9a03-f6f0d1f57bc8
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 1 pages on device 7b8de2bc-5975-4d8d-9a03-f6f0d1f57bc8
vbdev_lvol.c:1213:_vbdev_lvs_examine_finish: *INFO*: Opening lvol 7b8de2bc-5975-4d8d-9a03-f6f0d1f57bc8 succeeded
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 8 pages on device fd07b4ac-66a1-4482-980f-3a92eb636016
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 1 pages on device fd07b4ac-66a1-4482-980f-3a92eb636016
vbdev_lvol.c:1213:_vbdev_lvs_examine_finish: *INFO*: Opening lvol fd07b4ac-66a1-4482-980f-3a92eb636016 succeeded
vbdev_lvol.c:1218:_vbdev_lvs_examine_finish: *INFO*: Opening lvols finished
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 4d0d6062-a7e2-4963-8fff-336b4d14139f with type 1
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 4d0d6062-a7e2-4963-8fff-336b4d14139f with type 1
vbdev_lvol.c:1238:_vbdev_lvs_examine_cb: *INFO*: Lvol store not found on 4d0d6062-a7e2-4963-8fff-336b4d14139f
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device adda0580-ffbd-4418-b40d-00262642cd59 with type 1
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device adda0580-ffbd-4418-b40d-00262642cd59 with type 1
vbdev_lvol.c:1238:_vbdev_lvs_examine_cb: *INFO*: Lvol store not found on adda0580-ffbd-4418-b40d-00262642cd59
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 0fb959d6-61c7-4745-a4fc-edd89fe0bb60 with type 1
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 0fb959d6-61c7-4745-a4fc-edd89fe0bb60 with type 1
vbdev_lvol.c:1238:_vbdev_lvs_examine_cb: *INFO*: Lvol store not found on 0fb959d6-61c7-4745-a4fc-edd89fe0bb60
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 7b8de2bc-5975-4d8d-9a03-f6f0d1f57bc8 with type 1
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 7b8de2bc-5975-4d8d-9a03-f6f0d1f57bc8 with type 1
vbdev_lvol.c:1238:_vbdev_lvs_examine_cb: *INFO*: Lvol store not found on 7b8de2bc-5975-4d8d-9a03-f6f0d1f57bc8
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 0d30ff91-42df-4e24-a0de-96c93ab7e651 with type 1
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 0d30ff91-42df-4e24-a0de-96c93ab7e651 with type 1
vbdev_lvol.c:1238:_vbdev_lvs_examine_cb: *INFO*: Lvol store not found on 0d30ff91-42df-4e24-a0de-96c93ab7e651
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device fd07b4ac-66a1-4482-980f-3a92eb636016 with type 1
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device fd07b4ac-66a1-4482-980f-3a92eb636016 with type 1
vbdev_lvol.c:1238:_vbdev_lvs_examine_cb: *INFO*: Lvol store not found on fd07b4ac-66a1-4482-980f-3a92eb636016
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_rpc.c: 319:spdk_rpc_get_bdevs: *ERROR*: bdev 'lvs.nvme0n1/lvol.6870' does not exist
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 457:vbdev_lvol_store_first: *INFO*: Starting lvolstore iteration at 0x15b7980
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 8 pages on device 45dba763-3911-4d09-9554-36066d7a8622
vbdev_lvol.c: 876:vbdev_lvol_submit_request: *INFO*: Vbdev request type 1 submitted
vbdev_lvol.c: 839:lvol_read: *INFO*: Vbdev doing read at offset 0 using 1 pages on device 45dba763-3911-4d09-9554-36066d7a8622
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 45dba763-3911-4d09-9554-36066d7a8622 with type 1
vbdev_lvol.c: 784:lvol_op_comp: *INFO*: Vbdev processing callback on device 45dba763-3911-4d09-9554-36066d7a8622 with type 1
vbdev_lvol.c:1238:_vbdev_lvs_examine_cb: *INFO*: Lvol store not found on 45dba763-3911-4d09-9554-36066d7a8622
VHOST_CONFIG: vhost-user server: socket created, fd: 22
VHOST_CONFIG: bind to /var/tmp/vhost.6870
vhost.c: 759:spdk_vhost_dev_register: *INFO*: Controller vhost.6870: new controller added
vhost_scsi.c: 851:spdk_vhost_scsi_dev_add_tgt: *INFO*: Controller vhost.6870: defined target 'Target 0' using bdev 'lvs.nvme0n1/lvol.6870'
VHOST_CONFIG: new vhost user connection is 16
VHOST_CONFIG: new device, handle is 0
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_GET_FEATURES
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_GET_PROTOCOL_FEATURES
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_PROTOCOL_FEATURES
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_GET_QUEUE_NUM
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_OWNER
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_GET_FEATURES
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:0 file:23
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:1 file:24
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:2 file:25
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:3 file:26
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:4 file:27
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_CALL
VHOST_CONFIG: vring call idx:5 file:28
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_FEATURES
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_MEM_TABLE
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_NUM
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_BASE
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_ADDR
VHOST_CONFIG: guest memory region 0, size: 0x40000000
	 guest physical addr: 0x0
	 guest virtual  addr: 0x7fa900000000
	 host  virtual  addr: 0x2aaac0000000
	 mmap addr : 0x2aaac0000000
	 mmap size : 0x40000000
	 mmap align: 0x40000000
	 mmap off  : 0x0
VHOST_CONFIG: reallocate vq from 0 to 1 node
VHOST_CONFIG: /var/tmp/vhost.6870: read message VHOST_USER_SET_VRING_KICK
VHOST_CONFIG: vring kick idx:2 file:30
VHOST_CONFIG: virtio is now ready for processing.
vhost.c: 537:spdk_vhost_dev_mem_register: *INFO*: Registering VM memory for vtophys translation - 0x2aaac0000000 len:0x40000000
Segmentation fault (core dumped)
```

```
(gdb) bt
#0  0x000000000046ee79 in rte_mem_virt2memseg ()
#1  0x000000000045cdc5 in vtophys_get_paddr_memseg (vaddr=46912854032384) at vtophys.c:220
#2  spdk_vtophys_notify (cb_ctx=<optimized out>, map=0x7f823bf22010, action=SPDK_MEM_MAP_NOTIFY_REGISTER, vaddr=0x2aaac0000000, len=1073741824) at vtophys.c:356
#3  0x000000000045bec4 in spdk_mem_register (vaddr=<optimized out>, vaddr@entry=0x2aaac0000000, len=0, len@entry=1073741824) at memory.c:268
#4  0x000000000043e8ab in spdk_vhost_dev_mem_register (vdev=<optimized out>) at vhost.c:539
#5  start_device (vid=<optimized out>) at vhost.c:1089
#6  0x0000000000457731 in vhost_user_msg_handler (vid=<optimized out>, fd=fd@entry=14) at vhost_user.c:1354
#7  0x000000000045663f in vhost_user_read_cb (connfd=14, dat=0x7f822c0008c0, remove=0x7f8233b0dc18) at socket.c:293
#8  0x0000000000459460 in fdset_event_dispatch (arg=0x6ca260 <vhost_user+8192>) at fd_man.c:273
#9  0x00007f823e327e25 in start_thread (arg=0x7f8233b0e700) at pthread_create.c:308
#10 0x00007f823e051bad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```

**Comment by wanqunintel** [comment]
@beef9999 are you using vhost-scsi or vhost-blk?

**Comment by beef9999** [comment]
@wanqunintel vhost-scsi

**Comment by pawelwod** [comment]
Pls post commit id and try building with debug options.

I assume you are using centos as host?

**Comment by beef9999** [comment]
@pawelwod 
1. 18.07 release tarball
2. Updated with the detailed logs, see above
3. CentOS 7.5,  kernel 3.10.0-862

**Comment by darsto** [comment]
This is DPDK 18.05 issue. As we wait for the DPDK 18.05.1 stable release, which should have it fixed, you might want to use our internal dpdk fork https://github.com/spdk/dpdk/tree/spdk-18.05. Note that SPDK includes that particular DPDK repo as a git submodule, so you could just do:

```
git clone https://github.com/spdk/spdk
cd spdk
git submodule update --init
./configure
make
```

**Comment by ChenWang01** [comment]
I can produce this issue with SPDK 18.07 and DPDK 18.05 in our environment.
```
OS: CentOS Linux release 7.3.1611
Kernel: 3.10.0-327.el7.x86_64
```
Detail steps:
```
1. build DPDK 18.05
    make install T=x86_64-native-linuxapp-gcc DESTDIR=.  EXTRA_CFLAGS=-fPIC 
2. build SPDK 18.07
    ./configure --with-dpdk=../dpdk/x86_64-native-linuxapp-gcc/
3. ./app/vhost/vhost
4. ./rpc.py construct_nvme_bdev -b "nvme0" -t "PCIe" -a "0000:81:00.0"
5. ./rpc.py construct_vhost_scsi_controller vhost.0
6. ./rpc.py add_vhost_scsi_lun vhost.0 0 nvme0n1
7. qemu command to start VM with vhost scsi
```

**Comment by liang2yan** [comment]
@beef9999 , can you try  spdk dpdk submodule to see if this issue still exist?

**Comment by beef9999** [comment]
dpdk submodule could work
