### ISSUE TITLE
Nvmf target core dumped when using same device to construct crypto bdev again in nvmf.conf

### ISSUE THREAD

**Issue by xuhuagen** [spdk/spdk#448]
Now, I  try to add crypto option into nvmf.conf and start nvmf_tgt, nvmf config file like as below:
```
[Nvme]
TransportId "trtype:PCIe traddr:0000:06:00.0" Nvme0

[crypto]
  CRY Nvme0n1 Crypto_Nvme0n1 0123456789123456 crypto_aesni_mb
  CRY Nvme0n1 Crypto_Nvme1n1 0123456789123456 crypto_aesni_mb

[Subsystem1]
  NQN nqn.2016-06.io.spdk:cnode1
  Listen RDMA 192.168.11.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace Crypto_Nvme0n1 1
  Namespace Crypto_Nvme1n1 2
```

start nvmf_tgt then  ctrl+c to kill it, core dumped occur. 
```
[root@waikikibeach35 spdk]# ./app/nvmf_tgt/nvmf_tgt -c ../nvmf.conf
Starting SPDK v18.10-pre / DPDK 18.05.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --legacy-mem --file-prefix=spdk_pid15245 ]
EAL: Detected 44 lcore(s)
EAL: Detected 2 NUMA nodes
EAL: Multi-process socket /var/run/dpdk/spdk_pid15245/mp_socket
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 600:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 703:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
reactor.c: 490:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
vbdev_crypto.c:1204:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
vbdev_crypto.c:1204:vbdev_crypto_init: *NOTICE*: WARNING: You are storing your key in a plain text file!!
CRYPTODEV: [crypto_aesni_mb] - Creating cryptodev crypto_aesni_mb

CRYPTODEV: [crypto_aesni_mb] - Initialisation parameters - name: crypto_aesni_mb,socket id: 0, max queue pairs: 8, max sessions: 2048
vbdev_crypto.c: 219:vbdev_crypto_init_crypto_drivers: *NOTICE*: created virtual PMD crypto_aesni_mb
EAL: PCI device 0000:05:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:06:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:07:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:08:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:09:00.0 on NUMA socket 0
EAL:   probe driver: 8086:2701 spdk_nvme
EAL: PCI device 0000:0b:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:0c:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:0f:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
EAL: PCI device 0000:10:00.0 on NUMA socket 0
EAL:   probe driver: 8086:953 spdk_nvme
vbdev_crypto.c:1341:vbdev_crypto_claim: *NOTICE*: Match on Nvme0n1
vbdev_crypto.c:1412:vbdev_crypto_claim: *NOTICE*: registered crypto_bdev for: Crypto_Nvme0n1
vbdev_crypto.c:1341:vbdev_crypto_claim: *NOTICE*: Match on Nvme0n1
bdev.c:3274:spdk_bdev_open: *ERROR*: Could not open Nvme0n1 - crypto module already claimed it
vbdev_crypto.c:1402:vbdev_crypto_claim: *ERROR*: could not open bdev Nvme0n1
vbdev_crypto.c:1480:vbdev_crypto_examine: *ERROR*: could not claim bdev
conf.c: 293:spdk_nvmf_parse_subsystem: *ERROR*: Could not find namespace bdev 'Crypto_Nvme0n1'
^CSegmentation fault (core dumped)
```

the core dumped log as below:
```
[root@waikikibeach35 spdk]# gdb -c /tmp/core-reactor_0-11-0-0-15245-1538183853 ./app/nvmf_tgt/nvmf_tgt
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-110.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/xuhuagen/spdk/app/nvmf_tgt/nvmf_tgt...done.

warning: core file may not match specified executable file.
[New LWP 15245]
[New LWP 15247]
[New LWP 15246]
[New LWP 15248]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./app/nvmf_tgt/nvmf_tgt -c ../nvmf.conf'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000045ef6a in spdk_bdev_unregister (bdev=0x28bb320, cb_fn=<optimized out>, cb_arg=<optimized out>) at bdev.c:3242
3242            TAILQ_REMOVE(&g_bdev_mgr.bdevs, bdev, internal.link);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-222.el7.x86_64 libaio-0.3.109-13.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libibverbs-15-7.el7_5.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-15-7.el7_5.x86_64 libuuid-2.23.2-52.el7_5.1.x86_64 numactl-libs-2.0.9-7.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x000000000045ef6a in spdk_bdev_unregister (bdev=0x28bb320, cb_fn=<optimized out>, cb_arg=<optimized out>) at bdev.c:3242
#1  0x000000000043356d in vbdev_crypto_examine_hotremove_cb (ctx=0x28bb020) at vbdev_crypto.c:1293
#2  0x0000000000455d52 in _spdk_event_queue_run_batch (reactor=0x277b340, reactor=0x277b340) at reactor.c:205
#3  _spdk_reactor_run (arg=0x277b340) at reactor.c:502
#4  0x000000000045635d in spdk_reactors_start () at reactor.c:677
#5  0x0000000000454f71 in spdk_app_start (opts=opts@entry=0x7ffc8d037fb0, start_fn=start_fn@entry=0x407ba0 <nvmf_tgt_started>,
    arg1=arg1@entry=0x0, arg2=arg2@entry=0x0) at app.c:648
#6  0x0000000000406745 in main (argc=3, argv=0x7ffc8d038128) at nvmf_main.c:75
```

## Expected Behavior
nvmf target can exit normally.

## Current Behavior
nvmf core dumped occur when start with incorrect config in nvmf.conf

## Steps to Reproduce
1. add crypto option into nvmf target config file nvmf.conf
2.  starting nvmf_tgt with nvmf.conf

## Context (Environment including OS version, SPDK version, etc.)
OS version: CentOS Linux release 7.5.1804 (Core)
SPDK version: commit id ff852667f84e368c3bf51fb3579c0a1f87d141db

**Comment by peluse** [comment]
Can repro, should be pretty easy fix

**Comment by peluse** [comment]
Please try https://review.gerrithub.io/#/c/spdk/spdk/+/427317

thanks!

**Comment by xuhuagen** [comment]
@peluse I try this patch and core dumped can't be reproduced.

**Comment by peluse** [comment]
@xuhuagen also as a side note, please don't close these until the proposed fix is merged to master since technically it's not fixed until that happens.  Thanks!

**Comment by xuhuagen** [comment]
There is a better fix for it.

**Comment by xuhuagen** [comment]
@peluse  patch https://review.gerrithub.io/#/c/spdk/spdk/+/427317 has been abandoned. do you have a better fix for it?

**Comment by peluse** [comment]
sorry, didn't see this update.  Yes, the better fix has already been merged

**Comment by peluse** [comment]
so you can test off master and close if it passes

**Comment by xuhuagen** [comment]
I test off master and it passes.

**Comment by peluse** [comment]
Excellent, thanks for re-testing!
