### ISSUE TITLE
Seg. fault in iSCSI target by read and write workload and periodical TCP disconnection

### ISSUE THREAD

**Issue by shuhei-matsumoto** [spdk/spdk#457]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

Segmentation faults have occurred intermittently.

```
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor
conn.c1092spdk_iscsi_conn_flush_pdus_internal ERROR spdk_sock_writev() failed, errno 9 Bad file descriptor

Thread 1 reactor_0 received signal SIGSEGV, Segmentation fault.
spdk_iscsi_task_cpl (scsi_task=0x7ffc3c787a00) at conn.c917
917     conn.c No such file or directory.
Missing separate debuginfos, use zypper install libaio1-debuginfo-0.3.109-17.15.x86_64 libnuma1-debuginfo-2.0.9-9.1.x86_64 libopenssl1_0_0-debuginfo-1.0.2j-60.11.2.x86_64 libuuid1-debuginfo-2.28-44.9.1.x86_64 libz1-debuginfo-1.2.8-11.1.x86_64
(gdb) bt
#0  spdk_iscsi_task_cpl (scsi_task=0x7ffc3c787a00) at conn.c917
#1  0x000000000045646a in spdk_bdev_scsi_task_complete_cmd (bdev_io=optimized out, success=optimized out, cb_arg=0x7ffc3c787a00) at scsi_bdev.c1281
#2  0x000000000045ac32 in _spdk_event_queue_run_batch (reactor=0x8f0880, reactor=0x8f0880) at reactor.c205
#3  _spdk_reactor_run (arg=0x8f0880) at reactor.c502
#4  0x000000000045b23d in spdk_reactors_start () at reactor.c677
#5  0x0000000000459e51 in spdk_app_start (opts=opts@entry=0x7fffffffe2a0, start_fn=start_fn@entry=0x407400 spdk_startup, arg1=arg1@entry=0x0, 
    arg2=arg2@entry=0x0) at app.c650
#6  0x0000000000405efc in main (argc=3, argv=0x7fffffffe418) at iscsi_tgt.c112
(gdb) 

or 

conn.c:1092:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 9: Bad file descriptor
conn.c:1092:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 9: Bad file descriptor
conn.c:1092:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 9: Bad file descriptor
conn.c:1092:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 9: Bad file descriptor
conn.c:1092:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 9: Bad file descriptor
conn.c:1092:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 9: Bad file descriptor
conn.c:1092:spdk_iscsi_conn_flush_pdus_internal: *ERROR*: spdk_sock_writev() failed, errno 9: Bad file descriptor
conn.c: 460:spdk_iscsi_remove_conn: *NOTICE*: Terminating connections(tsih 24): 0

Thread 1 "reactor_0" received signal SIGSEGV, Segmentation fault.
spdk_del_connection_queued_task (conn=conn@entry=0x7ffbed85c250, tailq=tailq@entry=0x7ffbed85d280, lun=lun@entry=0x0) at iscsi.c:3484
3484    iscsi.c: No such file or directory.
Missing separate debuginfos, use: zypper install libaio1-debuginfo-0.3.109-17.15.x86_64 libnuma1-debuginfo-2.0.9-9.1.x86_64 libopenssl1_0_0-debuginfo-1.0.2j-60.11.2.x86_64 libuuid1-debuginfo-2.28-44.9.1.x86_64 libz1-debuginfo-1.2.8-11.1.x86_64
(gdb) bt
#0  spdk_del_connection_queued_task (conn=conn@entry=0x7ffbed85c250, tailq=tailq@entry=0x7ffbed85d280, lun=lun@entry=0x0) at iscsi.c:3484
#1  0x00000000004441e2 in spdk_clear_all_transfer_task (conn=conn@entry=0x7ffbed85c250, lun=lun@entry=0x0) at iscsi.c:3526
#2  0x000000000043ef7a in spdk_iscsi_conn_destruct (conn=0x7ffbed85c250) at conn.c:532
#3  0x000000000044db72 in spdk_iscsi_poll_group_poll (ctx=<optimized out>) at iscsi_subsystem.c:1177
#4  0x000000000045aca4 in _spdk_reactor_run (arg=0x8f0880) at reactor.c:514
#5  0x000000000045b23d in spdk_reactors_start () at reactor.c:677
#6  0x000000000045

```

## Expected Behavior
Safely TCP disconnection.

## Current Behavior
Segmentation fault occured.

## Possible Solution
None

## Steps to Reproduce
1. A Windows initiator login to the SPDK iSCSI target and created a connection to an LUN.
2. IO workload by IOmeter, 256KB, write:read = 7:3, random, iodepth=20
3. Periodical disconnection by the test tool wkillcx (ver 1.0.2) from the host (initiator)

**Comment by shuhei-matsumoto** [comment]
https://review.gerrithub.io/#/c/spdk/spdk/+/429090/
didn't fix the issue.

**Comment by shuhei-matsumoto** [comment]
100% read or 100% write are OK.
64KB, ImmediateData=No, write:read = 7:3 also reproduced the issue.
Mix of read and write may be the key.

**Comment by shuhei-matsumoto** [comment]
This issue has occured by using the latest master of SPDK.

**Comment by shuhei-matsumoto** [comment]
@wanqunintel 

Thank you for looking this patch and sorry for the late reply.

qd=20 was used and reported by my team member. We just wanted to do stress test for iSCSI error handling and didn't have any particular intention.

I submitted a patch https://review.gerrithub.io/#/c/spdk/spdk/+/430397/ to fix the issue.
It looks that the issue was fixed so far. If stress test continues today, I will be able to close the issue tomorrow.

**Comment by shuhei-matsumoto** [comment]
The issue reported here was fixed but calsoft (iSCSI certification test) failed. I'll continue investigation.

**Comment by shuhei-matsumoto** [comment]
I changed the patch and now fixed the issue and passed the calsoft test.

**Comment by shuhei-matsumoto** [comment]
No issue observed for a day in my evaluation.
