### ISSUE TITLE
NVMF target Memory leaks when send SIGTERM after finish fioplugin test

### ISSUE THREAD

**Issue by WenqianZong** [spdk/spdk#465]
nvmf taget occurred memory leaks when send SIGTERM after initator finished fioplugin test.

## Expected Behavior
no error occurred

## Current Behavior
nvmf taget occurred memory leaks

```
[root@waikikibeach45 spdk-latest]# ./app/nvmf_tgt/nvmf_tgt -c ../nvmf.conf
Starting SPDK v18.10-pre / DPDK 18.02.0 initialization...
[ DPDK EAL parameters: nvmf --no-shconf -c 0x1 --file-prefix=spdk_pid495225 ]
EAL: Detected 56 lcore(s)
EAL: Multi-process socket /var/run/.spdk_pid495225_unix
EAL: Probing VFIO support...
app.c: 602:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 703:spdk_reactors_init: *NOTICE*: Occupied cpu socket mask is 0x1
app.c: 528:spdk_app_setup_trace: *NOTICE*: Tracepoint Group Mask 0xFFFF specified.
app.c: 532:spdk_app_setup_trace: *NOTICE*: Use 'spdk_trace -s nvmf -p 495225' to capture a snapshot of events at runtime.
app.c: 534:spdk_app_setup_trace: *NOTICE*: Or copy /dev/shm/nvmf_trace.pid495225 for offline analysis/debug.
reactor.c: 490:_spdk_reactor_run: *NOTICE*: Reactor started on core 0 on socket 0
^C
=================================================================
==495225==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 5 byte(s) in 1 object(s) allocated from:
    #0 0x7f4fc58e2320 in strdup (/lib64/libasan.so.5+0x3b320)
    #1 0x5785e1 in rte_eal_init (/home/xuhuagen/spdk-latest/app/nvmf_tgt/nvmf_tgt+0x5785e1)
    #2 0x521346 in spdk_app_setup_env /home/xuhuagen/spdk-latest/lib/event/app.c:494
    #3 0x521ddd in spdk_app_start /home/xuhuagen/spdk-latest/lib/event/app.c:597
    #4 0x40a74b in main /home/xuhuagen/spdk-latest/app/nvmf_tgt/nvmf_main.c:75
    #5 0x7f4fc401324a in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: 5 byte(s) leaked in 1 allocation(s).
```

## Steps to Reproduce
On target:
1.  ./configure --with-dpdk=/home/xuhuagen/dpdk-18.02/x86_64-native-linuxapp-gcc/ --with-rdma --enable-asan --enable-debug
2.  make clean && make -j
3.  ./app/nvmf_tgt/nvmf_tgt -c ../nvmf.conf
4. ctrl + c to kill nvmf target
nvmf.conf
```
[Global]
  ReactorMask 0x3
[Malloc]
  NumberOfLuns 9
  LunSizeInMB 10240
[Nvmf]
  MaxQueuesPerSession 128
  MaxQueueDepth 256
  AcceptorPollRate 10000
[Nvme]
  RetryCount 4
  Timeout 0
  ActionOnTimeout None
  AdminPollRate 100000
  HotplugEnable No
[Subsystem1]
  NQN nqn.2018-07.io.spdk:cnode1
  Listen RDMA 192.168.11.11:4420
  AllowAnyHost Yes
  Host nqn.2016-06.io.spdk:init
  SN SPDK00000000000001
  MaxNamespaces 20
  Namespace Malloc0
  Namespace Malloc1
  Namespace Malloc2
  Namespace Malloc3
  Namespace Malloc4
  Namespace Malloc5
  Namespace Malloc6
  Namespace Malloc7
  Namespace Malloc8
```

On initator:
1.  ./configure --with-dpdk=/home/zong/dpdk-18.02/x86_64-native-linuxapp-gcc --with-rdma --with-fio=/usr/src/fio/
2.   make clean && make -j
3.   LD_PRELOAD=/home/zong/spdk/examples/nvme/fio_plugin/fio_plugin /usr/src/fio/fio ../fiojob_malloc

fiojob_malloc
```
[global]
ioengine=spdk
direct=1
verify=0
time_based=1
ramp_time=5
runtime=120
thread=1
numjobs=12
mem_size_mb=20480
bs=1024k
rw=read
iodepth=128
[job1]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=1
size=8G
[job2]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=2
size=8G
[job3]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=3
size=8G
[job4]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=4
size=8G
[job5]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=5
size=8G
[job6]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=6
size=8G
[job7]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=7
size=8G
[job8]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=8
size=8G
[job9]
filename=trtype=RDMA adrfam=IPv4 traddr=192.168.11.11 trsvcid=4420 ns=9
size=8G
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK  v18.10-pre DPDK 18.02.0

**Comment by jimharris** [comment]
Hi @WenqianZong,

Do you see this issue with the DPDK submodule in the SPDK repository?  We should focus the testing on that version of DPDK - not DPDK 18.02.

There was a known ASAN issue with upstream DPDK in DPDK 18.02.  The submodule had a fix for it.

(Removing bug label for now.)

Thanks,

-Jim

**Comment by WenqianZong** [comment]
I test this issue with the DPDK submodule in the SPDK, memory leaks didn't occurred. So close it.
