### ISSUE TITLE
duplicated QoS rpc command  will hung up or cause SPDK bdev_svc crash

### ISSUE THREAD

**Issue by liang2yan** [spdk/spdk#547]
It seems that SPDK can't correctly handle duplicated qos rpc command.

## Expected Behavior
bdev_svc not crashed or hung up.

## Current Behavior
bdev_svc crashed.

## Possible Solution
gang already submit a patch to fix this issue.
https://review.gerrithub.io/#/c/spdk/spdk/+/437519/

## Steps to Reproduce
using latest spdk codes    c68c2d28c13ffd145cd91eaff2ae279551fa1548:
1. configure bdev.conf as below:
```
[Malloc]
  NumberOfLuns 7
  LunSizeInMB 32
[QoS]
  Limit_IOPS Malloc0 20000
  Limit_BPS Malloc3 100
```
2. run bdev_svc as below:
`./test/app/bdev_svc/bdev_svc -c ./bdevconf
`
3. run qos rpc command:
```
./scripts/rpc.py set_bdev_qos_limit --rw_ios_per_sec 10000 Malloc0
./scripts/rpc.py set_bdev_qos_limit --rw_ios_per_sec 10000 Malloc0
```
4. the qos rpc command will hung up.

using commit id 9637e17d2d435e1e9d4b662d1405b9cda8d9c21d:
1. configure bdev.conf as below:
```
[Malloc]
  NumberOfLuns 7
  LunSizeInMB 32
[QoS]
  Limit_IOPS Malloc0 20000
  Limit_BPS Malloc3 100
```
2. run bdev_svc as below:
`./test/app/bdev_svc/bdev_svc -c ./bdevconf
`
3. run qos rpc command:
```
./scripts/rpc.py set_bdev_qos_limit_iops Malloc0 20000
./scripts/rpc.py set_bdev_qos_limit_iops Malloc0 20000

```
4. the spdk bdev_svc crashed. coredump as below:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000045faf3 in spdk_thread_send_msg (thread=0x0, fn=0x46a542 <_spdk_bdev_update_qos_limit_iops_msg>, ctx=0x1bb0f00) at thread.c:232
232             thread->msg_fn(fn, ctx, thread->thread_ctx);
[Current thread is 1 (Thread 0x7fc4fa0b0e00 (LWP 24940))]
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.26-28.fc27.x86_64 openssl-libs-1.1.0h-3.fc27.x86_64
(gdb) bt
#0  0x000000000045faf3 in spdk_thread_send_msg (thread=0x0, fn=0x46a542 <_spdk_bdev_update_qos_limit_iops_msg>, ctx=0x1bb0f00) at thread.c:232
#1  0x000000000046a8ba in spdk_bdev_set_qos_limit_iops (bdev=0x7fc4317b09c0, ios_per_sec=20000, cb_fn=0x456d62 <spdk_rpc_set_bdev_qos_limit_iops_complete>, cb_arg=0x1a9deb0) at bdev.c:3663
#2  0x0000000000456ed1 in spdk_rpc_set_bdev_qos_limit_iops (request=0x1a9deb0, params=0x7fc4ee73b070) at bdev_rpc.c:544
#3  0x000000000046c292 in spdk_jsonrpc_handler (request=0x1a9deb0, method=0x7fc4ee73b100, params=0x7fc4ee73b070) at rpc.c:81
#4  0x000000000046dd48 in spdk_jsonrpc_server_handle_request (request=0x1a9deb0, method=0x7fc4ee73b100, params=0x7fc4ee73b070) at jsonrpc_server_tcp.c:183
#5  0x000000000046cb9b in parse_single_request (request=0x1a9deb0, values=0x7fc4ee73b050) at jsonrpc_server.c:116
#6  0x000000000046ce9d in spdk_jsonrpc_parse_request (conn=0x7fc4ee73b040, json=0x7fc4ee73f058, size=117) at jsonrpc_server.c:179
#7  0x000000000046df62 in spdk_jsonrpc_server_conn_recv (conn=0x7fc4ee73b040) at jsonrpc_server_tcp.c:242
#8  0x000000000046e454 in spdk_jsonrpc_server_poll (server=0x7fc4ee73b010) at jsonrpc_server_tcp.c:386
#9  0x000000000046c6f5 in spdk_rpc_accept () at rpc.c:199
#10 0x000000000045c890 in spdk_rpc_subsystem_poll (arg=0x0) at rpc.c:51
#11 0x000000000045be9d in _spdk_reactor_run (arg=0x1aa1340) at reactor.c:537
#12 0x000000000045c34d in spdk_reactors_start () at reactor.c:677
#13 0x000000000045a509 in spdk_app_start (opts=0x7ffde18e0070, start_fn=0x4050ec <bdev_svc_start>, arg1=0xffffffffffffffff, arg2=0x0) at app.c:648
#14 0x0000000000405290 in main (argc=3, argv=0x7ffde18e01d8) at bdev_svc.c:107
(gdb) quit

```

**Comment by liang2yan** [comment]
verified with gang's patch, this issue can't be reproduced.

**Comment by Comphix** [comment]
The patch https://review.gerrithub.io/#/c/spdk/spdk/+/437519/ has been merged. Close this issue and Liang have also verified the change.
