### ISSUE TITLE
spdkcli: crash when using non existent tree path

### ISSUE THREAD

**Issue by pawelwod** [spdk/spdk#582]
## Expected Behavior
spdkcli should print error message (not crash)

## Current Behavior
spdkcli crashes

## Possible Solution
None

## Steps to Reproduce
1. Run target and spdkcli
2. try using nonexistent path

Logs:

```
./scripts/spdkcli.py
SPDK CLI v0.1

/> bdevs/x
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/shell.py", line 811, in _execute_command
    target = self._current_node.get_node(path)
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/node.py", line 1862, in get_node
    return next_node.get_node(next_path)
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/node.py", line 1865, in get_node
    return adjacent_node(path)
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/node.py", line 1827, in adjacent_node
    return self.get_child(name)
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/node.py", line 1796, in get_child
    % (self.path.rstrip('/'), name))
ValueError: No such path /bdevs/x

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/spdkcli.py", line 61, in <module>
    main()
  File "./scripts/spdkcli.py", line 57, in main
    spdk_shell.run_interactive()
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/shell.py", line 905, in run_interactive
    self._cli_loop()
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/shell.py", line 734, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/shell.py", line 848, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/local/lib/python3.5/dist-packages/configshell_fb/shell.py", line 813, in _execute_command
    raise ExecutionError(str(msg))
configshell_fb.node.ExecutionError: No such path /bdevs/x
```

## Context (Environment including OS version, SPDK version, etc.)
Ubuntu 16.04
Python3
SPDK: bf6210b test/iscsi: fix support for python 3.6 in calsoft.py

**Comment by pawelkax** [comment]
@pawelwod  @karlatec This issue is related to configshell_fb library not to spdkcli.

**Comment by karlatec** [comment]
> @pawelwod @karlatec This issue is related to configshell_fb library not to spdkcli.

Pawel, any way to try-catch this?

**Comment by pawelkax** [comment]
@karlatec @pawelwod Patch with fix: https://review.gerrithub.io/#/c/spdk/spdk/+/442323/
