### ISSUE TITLE
Jenkins: results for failed test not available

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#586]
https://review.gerrithub.io/c/spdk/spdk/+/429523

This is Paul's ISA-L patch.

Patch set 66 failed.  Results are not available - either through internal or external status pages.  Results are available through Jenkins directly:
https://10.102.17.104:8080/job/autotest-per-patch/20129/

Patch set from version 65 and 67 are both available.

**Comment by peluse** [comment]
Some notes:
* The post job to push logs is here: https://10.102.17.104:8080/view/Maintenance/job/copy-artifacts-to-jbp/945/ and its console output shows no issues
* The ext status server dir for output is here: https://ci.spdk.io/spdk-jenkins/results/autotest-per-patch/builds/20129/ and does exist however there are no sub directories
* ssh'd into static build server and checked /var/www/html/build_pool/results/autotest-per-patch/builds /20129 and it matches the external server

So, it look like the post job script to push the artifacts didn't totally work.  I notice we aren't checking the return value of rsync, I believe it has one.  If you guys can look maybe at least we can identify an rsync error and mark the build accordingly (well, I don't have a suggestion for what that would be right now but let me know about rsync).

**Comment by peluse** [comment]
yeah, the man page shows the exit values that we can check.  We might also want to temp add -v option and if it doesn't generate too much output leave it on for a little while to help with cases like this.

**Comment by karlatec** [comment]
It is not an rsync issue. We rsync'd the build directory which contains more than just the artifacts, so rsync was successful.

The artifacts are even missing in the Jenkins history itself, sot here were no artifacts to copy in the first place. See: https://10.102.17.104:8080/job/autotest-per-patch/20129/console
```
17:48:27 + spdk/autorun_post.py -d ./ -r ./spdk
17:48:37 [PostBuildScript] - [ERROR] Problem occurred: java.lang.InterruptedException
17:48:37 Build step 'Execute Scripts' marked build as failure
17:48:37 Archiving artifacts
17:48:37 ERROR: Failed to archive artifacts: *_autotest*/**/*,coverage/**,coverage.log,test_execution.log,ut_coverage/**/*,doc/**/*,post_process/**
17:48:37 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to __main_executor
17:48:37 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
17:48:37 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
17:48:37 		at hudson.remoting.Channel$2.adapt(Channel.java:944)
17:48:37 		at hudson.remoting.Channel$2.adapt(Channel.java:941)
[Long Java stack trace continuing]
```

[PostBuildScript] - [ERROR] Problem occurred: java.lang.InterruptedException.
This looks like an intermittent failure. I tried to find some info about this in logs, but Jenkins logger is, well... not very good.
Looking at the runtime of the build, displayed error and time between patch sets 66 and 67 - my bet is that build was trying to abort due to new patchset incoming, but this wasn't handled nicely.

**Comment by peluse** [comment]
Hmmm, now the build is gone so I can't double check but I looked internally and could have sworn I saw them, I think Jim did too.  To be clear though, the post job output you have above which is part of auto-test-per-patch is a groovy script that is collecting artifacts from all the subjobs into the main workspace prior to the separate job that is then executed to rsync them out - is that correct?

Its probably still a good idea to check the exit value of rsych.  I wonder is somehow the back to back patch pushes on this one had anything to do with it.  The build in question was running when I pushed the next one.

**Comment by karlatec** [comment]
> could have sworn I saw them, I think Jim did too
Checked more than once today, sorry :) They weren't there.

>To be clear though, the post job output you have above which is part of auto-test-per-patch is a groovy script that is collecting artifacts from all the subjobs into the main workspace prior to the separate job that is then executed to rsync them out - is that correct?
Exactly. 

> I wonder is somehow the back to back patch pushes on this one had anything to do with it.
Probably not, as it gets run after artifacts are archived (so archiving is already finished by then).

> The build in question was running when I pushed the next one.
Yup. Like I said - my bet is that Jenkins ABORT due to new patch set may have caused this issue (hence the "java.lang.InterruptedException")

**Comment by peluse** [comment]
Oh yeah you did say that :) . OK, I'd like to leave this open until one of us has a chance to try and make it more user friendly when this happens, at least a couple of days.  I will have time time after the release.... thanks!!
