### ISSUE TITLE
spdk_poller_register assertion failed

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#743]
Assertion failed when running test with Vhost.
Vhost running multiple cores, on different NUMA nodes.
2 bdevs on 2 vhost scsi controllers. Crash when attaching second VM to controller.

Update: does not necessarily have to use 2 separate numa nodes. Reproduces if more than 1 core from a single numa nodes is used.

## Expected Behavior
No assertion fail:)

## Current Behavior
Assertion fail :(

## Possible fix
Git bisect points at:
https://review.gerrithub.io/#/c/spdk/spdk/+/446998/

## Steps to Reproduce

1.  Build SPDK
```
git submodule update --init; ./configure --with-fio=/usr/src/fio --enable-debug; make clean; make -j100
```
2. sudo app/vhost/vhost -m [0,12-14]
Core 0 is NUMA 0 and cores 12-14 are NUMA 0 on my server.

3. Construct 2 bdevs and 2 vhost scsi controllers. Attach bdevs to controllers.
```
sudo scripts/rpc.py construct_nvme_bdev -b Nvme0 -t pcie -a 84:00.0
sudo scripts/rpc.py construct_split_vbdev Nvme0n1 2
sudo scripts/rpc.py construct_vhost_scsi_controller naa.0.0
sudo scripts/rpc.py construct_vhost_scsi_controller naa.0.1
sudo scripts/rpc.py add_vhost_scsi_lun naa.0.0 0 Nvme0n1p0
sudo scripts/rpc.py add_vhost_scsi_lun naa.0.1 0 Nvme0n1p1
```

4. Prepare VM execution command:
```
taskset -a -c 2 /usr/local/qemu/spdk-2.12/bin/qemu-system-x86_64 \
  -m 2048 --enable-kvm -cpu host -smp 1 -vga std -vnc :100 -daemonize \
  -object memory-backend-file,id=mem,size=2048M,mem-path=/dev/hugepages,share=on,prealloc=yes,host-nodes=0,policy=bind \
  -snapshot \
  -monitor telnet:127.0.0.1:10002,server,nowait \
  -numa node,memdev=mem \
  -pidfile /home/klateck/work/vms/0/qemu.pid \
  -serial file:/home/klateck/work/vms/0/serial.log \
  -D /home/klateck/work/vms/0/qemu.log \
  -chardev file,path=/home/klateck/work/vms/0/seabios.log,id=seabios -device isa-debugcon,iobase=0x402,chardev=seabios \
  -net user,hostfwd=tcp::10000-:22,hostfwd=tcp::10001-:8765 \
  -net nic \
  -drive file=/home/sys_sgsw/centos.qcow2,if=none,id=os_disk \
  -device ide-hd,drive=os_disk,bootindex=0 \
  -chardev socket,id=char_0,path=/home/klateck/work/spdk/naa.0.0 \
  -device vhost-user-scsi-pci,id=scsi_0,num_queues=1,chardev=char_0 

(Second VM is the same overall. Controller name is naa.0.1, taskset is -c 3)
```

5. Run first VM
6. Run second VM just after that. Vhost output:
```
thread.c: 963:spdk_get_io_channel: *ERROR*: No thread allocated
vhost_scsi.c:1319:spdk_vhost_scsi_start_cb: *ERROR*: naa.0.1: failed to alloc io_channel for SCSI target 0
thread.c: 592:spdk_get_thread: *ERROR*: No thread allocated
vhost: thread.c:678: spdk_poller_register: Assertion `false' failed.
Aborted (core dumped)
```
7. Backtrace from GDB:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `app/vhost/vhost -m [0,12-14]'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fb35c903428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb35c0cc700 (LWP 59950))]
(gdb) bt
#0  0x00007fb35c903428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fb35c90502a in __GI_abort () at abort.c:89
#2  0x00007fb35c8fbbd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x52e2bf "false", file=file@entry=0x52e140 "thread.c", line=line@entry=678,
    function=function@entry=0x52e8c0 <__PRETTY_FUNCTION__.8296> "spdk_poller_register") at assert.c:92
#3  0x00007fb35c8fbc82 in __GI___assert_fail (assertion=0x52e2bf "false", file=0x52e140 "thread.c", line=678, function=0x52e8c0 <__PRETTY_FUNCTION__.8296> "spdk_poller_register") at assert.c:101
#4  0x00000000004a5841 in spdk_poller_register (fn=0x46bd3b <vdev_worker>, arg=0x200007836e00, period_microseconds=0) at thread.c:678
#5  0x000000000046d30d in spdk_vhost_scsi_start_cb (vdev=0x200014e80b00, vsession=0x200007836e00, unused=0x0) at vhost_scsi.c:1332
#6  0x00000000004678b0 in spdk_vhost_event_cb (arg1=0x7fb3521a0a10, arg2=0x0) at vhost.c:921
#7  0x0000000000483d03 in _spdk_event_queue_run_batch (reactor=0x270d000) at reactor.c:174
#8  0x0000000000483ebf in _spdk_reactor_run (arg=0x270d000) at reactor.c:239
#9  0x00000000004ca091 in eal_thread_loop (arg=0x0) at /home/klateck/work/spdk/dpdk/lib/librte_eal/linuxapp/eal/eal_thread.c:153
#10 0x00007fb35cc9f6ba in start_thread (arg=0x7fb35c0cc700) at pthread_create.c:333
#11 0x00007fb35c9d541d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) quit
```

## Context (Environment including OS version, SPDK version, etc.)
SPDK: 1fb629c4d250bf61412402b982d82d9e23bd8d88
Qemu: spdk/qemu 2.12
OS: Ubuntu 16.04 4.15.0-46-generic
VM Guest OS: Centos 7.6 3.10.0-957.10.1.el7.x86_64

**Comment by darsto** [comment]
That's not vhost-specific. I pushed a fix: https://review.gerrithub.io/c/spdk/spdk/+/450353

Thanks

**Comment by karlatec** [comment]
Issue resolved by patch.

**Comment by karlatec** [comment]
Changing the title, as this is not vhost specific.

**Comment by jimharris** [comment]
Patch merged.
