### ISSUE TITLE
Segfault when sending json-rpc with unexpected parameter

### ISSUE THREAD

**Issue by karlatec** [spdk/spdk#798]
## Current Behavior
Spdk application segfaults when RPC command containing unexpected parameters is sent.

## Expected Behavior
Well, no segfault would be nice :)

## Steps to Reproduce
1. Compile SPDK
```
git submodule update --init; ./configure --with-fio=/usr/src/fio --enable-debug; make clean; make -j100
```
2. Argparse in scripts/rpc.py prevents us at Python level to pass any extra argument to function calls. Need to modify one of the functions a little bit.
```
klateck@GrizzlyPass7:~/work/spdk$ git diff
diff --git a/scripts/rpc/__init__.py b/scripts/rpc/__init__.py
index 0f29373..b2b5b6a 100644
--- a/scripts/rpc/__init__.py
+++ b/scripts/rpc/__init__.py
@@ -44,7 +44,9 @@ def get_rpc_methods(client, current=None):

 def get_spdk_version(client):
     """Get SPDK version"""
-    return client.call('get_spdk_version')
+    params = {}
+    params['test'] = "Get to the chopper!"
+    return client.call('get_spdk_version', params)
```
3. Run spdk app and issue rpc command via rpc.py:
```
klateck@GrizzlyPass7:~/work/spdk$ Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: spdk_tgt --no-shconf -c 0x1 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid89971 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0

klateck@GrizzlyPass7:~/work/spdk$ sudo scripts/rpc.py get_spdk_version
Exception:
Got JSON-RPC error response
response:
{
  "message": "get_spdk_version method requires no parameters",
  "code": -32602
}
klateck@GrizzlyPass7:~/work/spdk$
[1]+  Segmentation fault      (core dumped) sudo app/spdk_tgt/spdk_tgt
```
4. Backtrace:
```
klateck@GrizzlyPass7:~/work/spdk$ sudo gdb app/spdk_tgt/spdk_tgt core
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from app/spdk_tgt/spdk_tgt...done.

warning: core file may not match specified executable file.
[New LWP 40749]
[New LWP 40750]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `app/spdk_tgt/spdk_tgt'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004fcaa8 in spdk_jsonrpc_free_request (request=0x13289d0) at jsonrpc_server.c:285
285             request->conn->outstanding_requests--;
[Current thread is 1 (Thread 0x7f4fb8a8e980 (LWP 40749))]
(gdb) bt
#0  0x00000000004fcaa8 in spdk_jsonrpc_free_request (request=0x13289d0) at jsonrpc_server.c:285
#1  0x00000000004fdd06 in spdk_jsonrpc_server_poll (server=0x7f4fae0a7010) at jsonrpc_server_tcp.c:409
#2  0x00000000004fbbf8 in spdk_rpc_accept () at rpc.c:242
#3  0x00000000004a2589 in spdk_rpc_subsystem_poll (arg=0x0) at rpc.c:51
#4  0x00000000004bf7ed in spdk_thread_poll (thread=0x123bd50, max_msgs=0, now=16281569648623101) at thread.c:505
#5  0x00000000004a1d06 in _spdk_reactor_run (arg=0x123b7c0) at reactor.c:271
#6  0x00000000004a20c9 in spdk_reactors_start () at reactor.c:374
#7  0x00000000004a08c3 in spdk_app_start (opts=0x7fff2428c5e0, start_fn=0x40575f <spdk_tgt_started>, arg1=0x0) at app.c:688
#8  0x000000000040587b in main (argc=1, argv=0x7fff2428c778) at spdk_tgt.c:125

```

## Context (Environment including OS version, SPDK version, etc.)
SPDK Version: 5904aba vhost_ut: Add tests for spdk_vhost_vq_avail_ring_get

**Comment by darsto** [comment]
fix: https://review.gerrithub.io/c/spdk/spdk/+/455220

Thanks!
