### ISSUE TITLE
test/blobfs/mkfs/mkfs /usr/local/etc/spdk/rocksdb.conf Nvme0n1 failed with seg fault(core dumped)

### ISSUE THREAD

**Issue by virgilshi** [spdk/spdk#800]
Please use the issue tracker only for reporting suspected issues.

See [The SPDK Community Page](http://www.spdk.io/community/) for other SPDK communications channels.

## Expected Behavior

all step which the [website](https://spdk.io/doc/blobfs.html) shows work well.
## Current Behavior
Related issue is #503 , but differ from the issue as follow.

1.  when making rocksdb along with spdk, some errors happened, shown as followed.
```sh
/root/sl/spdk/lib/rocksdb/env_spdk.cc:62:38: error: ‘void rocksdb::SpdkInitializeThread()’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void SpdkInitializeThread(void);
                                      ^
In file included from /root/sl/spdk/lib/rocksdb/env_spdk.cc:34:0:
include/rocksdb/env.h:1135:6: note: previous declaration of ‘void rocksdb::SpdkInitializeThread()’
```
2. when running `gen_nvme.sh` first,  the configuration file just displays `[Nvme]`, which should have displayed the information about PCIe devices. Only after running `setup.sh`, does it display correctly, and it is a error or my misundertanding steps? Some errors are shown bellow.
```sh
root@wy-All-Series:~/sl/spdk# scripts/gen_nvme.sh > /usr/local/etc/spdk/rocksdb.conf
root@wy-All-Series:~/sl/spdk# cat /usr/local/etc/spdk/rocksdb.conf
[Nvme]
root@wy-All-Series:~/sl/spdk# HUGEMEM=5120 scripts/setup.sh
0000:01:00.0 (1d1d 1f1f): nvme -> vfio-pci
root@wy-All-Series:~/sl/spdk# cat /usr/local/etc/spdk/rocksdb.conf
[Nvme]
root@wy-All-Series:~/sl/spdk# scripts/gen_nvme.sh > /usr/local/etc/spdk/rocksdb.conf
root@wy-All-Series:~/sl/spdk# cat /usr/local/etc/spdk/rocksdb.conf
[Nvme]
  TransportID "trtype:PCIe traddr:0000:01:00.0" Nvme0
```
3. Most importantly, when I run `test/blobfs/mkfs/mkfs /usr/local/etc/spdk/rocksdb.conf Nvme0n1`, segment fault(core dumped) happened. Some errors are shown bellow.
```bash
root@wy-All-Series:~/sl/spdk# test/blobfs/mkfs/mkfs /usr/local/etc/spdk/rocksdb.conf Nvme0n1
Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: spdk_mkfs --no-shconf -c 0x3 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4085 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 2
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
EAL:   using IOMMU type 1 (Type 1)
Initializing filesystem on bdev Nvme0n1...nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:191 nsid:1 lba:0 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:191 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:189 nsid:1 lba:64 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:189 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:188 nsid:1 lba:128 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:188 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:187 nsid:1 lba:192 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:187 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:187 nsid:1 lba:0 len:1
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:187 cdw0:0 sqhd:0008 p:1 m:1 dnr:1
done.
Segmentation fault (core dumped)
```
## Steps to Reproduce

I configure and install spdk and rocksdb step by step according to the [website](https://spdk.io/doc/blobfs.html)，My operations is shown as follow.
```
root@wy-All-Series:~/sl/spdk# ./configure 
...
root@wy-All-Series:~/sl/spdk# make
...
root@wy-All-Series:~/sl/rocksdb# make db_bench SPDK_DIR=../spdk
...
/root/sl/spdk/lib/rocksdb/env_spdk.cc:62:38: error: ‘void rocksdb::SpdkInitializeThread()’ was declared ‘extern’ and later ‘static’ [-fpermissive]
 static void SpdkInitializeThread(void);
                                      ^
In file included from /root/sl/spdk/lib/rocksdb/env_spdk.cc:34:0:
include/rocksdb/env.h:1135:6: note: previous declaration of ‘void rocksdb::SpdkInitializeThread()’
 void SpdkInitializeThread(void);
      ^
Makefile:1709: recipe for target '/root/sl/spdk/lib/rocksdb/env_spdk.o' failed
make: *** [/root/sl/spdk/lib/rocksdb/env_spdk.o] Error 1


root@wy-All-Series:~/sl/spdk# scripts/gen_nvme.sh > /usr/local/etc/spdk/rocksdb.conf
root@wy-All-Series:~/sl/spdk# cat /usr/local/etc/spdk/rocksdb.conf
[Nvme]
root@wy-All-Series:~/sl/spdk# HUGEMEM=5120 scripts/setup.sh
0000:01:00.0 (1d1d 1f1f): nvme -> vfio-pci
root@wy-All-Series:~/sl/spdk# cat /usr/local/etc/spdk/rocksdb.conf
[Nvme]
root@wy-All-Series:~/sl/spdk# scripts/gen_nvme.sh > /usr/local/etc/spdk/rocksdb.conf
root@wy-All-Series:~/sl/spdk# cat /usr/local/etc/spdk/rocksdb.conf
[Nvme]
  TransportID "trtype:PCIe traddr:0000:01:00.0" Nvme0
root@wy-All-Series:~/sl/spdk# test/blobfs/mkfs/mkfs /usr/local/etc/spdk/rocksdb.conf Nvme0n1
Starting SPDK v19.07-pre / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: spdk_mkfs --no-shconf -c 0x3 --log-level=lib.eal:6 --log-level=lib.cryptodev:5 --log-level=user1:6 --base-virtaddr=0x200000000000 --match-allocations --file-prefix=spdk_pid4085 ]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: VFIO support initialized
app.c: 628:spdk_app_start: *NOTICE*: Total cores available: 2
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 1
reactor.c: 251:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
EAL:   using IOMMU type 1 (Type 1)
Initializing filesystem on bdev Nvme0n1...nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:191 nsid:1 lba:0 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:191 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:189 nsid:1 lba:64 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:189 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:188 nsid:1 lba:128 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:188 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:187 nsid:1 lba:192 len:64
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:187 cdw0:0 sqhd:0007 p:1 m:1 dnr:1
nvme_qpair.c: 137:nvme_io_qpair_print_command: *NOTICE*: WRITE sqid:1 cid:187 nsid:1 lba:0 len:1
nvme_qpair.c: 306:nvme_qpair_print_completion: *NOTICE*: INVALID NAMESPACE OR FORMAT (00/0b) sqid:1 cid:187 cdw0:0 sqhd:0008 p:1 m:1 dnr:1
done.
Segmentation fault (core dumped)

```

## Context (Environment including OS version, SPDK version, etc.)

```
root@wy-All-Series:~/sl/spdk# uname -sr
Linux 4.20.0+
root@wy-All-Series:~/sl/spdk# git branch
* master
root@wy-All-Series:~/sl/rocksdb# git branch
* spdk-v5.6.1
```

**Comment by glodfish-zg** [comment]
hi @virgilshi 
For the Rockdb compile error, you can downgrade the SPDK to version v19.01.

root@wy-All-Series:~/sl/spdk# HUGEMEM=5120 scripts/setup.sh
0000:01:00.0 (1d1d 1f1f): nvme -> vfio-pci

It seems that you do the test in the VM, it 's a virtual NVMe device. I am not sure about this, maybe @changpe1 can give some suggestion.

**Comment by virgilshi** [comment]
Thanks a lot for your reply. Rocksdb compile error disappeared by `git checkout v19.01`. My testing ssd is openchannel ssd, not VM.

**Comment by changpe1** [comment]
@virgilshi Is your NVMe SSD dual-mode one? I'm wondering if you will get the same result with common SSDs.

**Comment by virgilshi** [comment]
@changpe1 , thank you.
My testing SSD is  just one-mode one, i.e., Openchannel SSD. Can I use common SSDs(e.g., SATA SSDs, M.2 SSDs) for testing? OK, I will do it later and update the issue, thanks.  ( The first error has been solved with the help of @glodfish-zg, and the second error isn't too much urgent, maybe a negligible bug.  However, The last error is to be solved.)

**Comment by changpe1** [comment]
@virgilshi You can use SATA SSDs with SPDK AIO backend, edit the rocksdb.conf with
[AIO]
AIO /dev/sdX AIO0
and format you drive with test/blobfs/mkfs/mkfs /usr/local/etc/spdk/rocksdb.conf AIO0

**Comment by virgilshi** [comment]
OK, thank you very much.

**Comment by virgilshi** [comment]
I can run `test/blobfs/mkfs/mkfs /usr/local/etc/spdk/rocksdb.conf AIO0` and `./db_bench --spdk=/usr/local/etc/spdk/rocksdb.conf --spdk_bdev=AIO0` (`cmd1` for short) successfully. However when I run `cmd1` again in the same terminal, **new error appears ( i.e. Segmentation fault (core dumped))**.

### Steps to Reproduce
1. modify rocksdb.conf
```sh
cat /usr/local/etc/spdk/rocksdb.conf 
[AIO]
AIO /dev/sdb AIO0
```
2. configure and install spdk
```sh
cd spdk
./configure
make
```
3. make rocksdb with spdk
```sh
cd rocksdb
make db_bench SPDK_DIR=../spdk
```
4. set up and format
```sh
HUGEMEM=5120 scripts/setup.sh
test/blobfs/mkfs/mkfs /usr/local/etc/spdk/rocksdb.conf AIO0
```
5. test
```sh
./db_bench --spdk=/usr/local/etc/spdk/rocksdb.conf --spdk_bdev=AIO0
```
**ERROR**

```sh
root@test-All-Series:/home/test/Desktop/rocksdb# make db_bench SPDK_DIR=../spdk/Makefile:105: Warning: Compiling in debug mode. Don't use the resulting binary in production
Makefile:915: warning: overriding recipe for target 'clean'
/home/test/Desktop/spdk/mk/spdk.app.mk:47: warning: ignoring old recipe for target 'clean'
Makefile:1727: target 'utilities/merge_operators/cassandra/test_utils.d' given more than once in the same rule
  GEN      util/build_version.cc
make: 'db_bench' is up to date.
root@test-All-Series:/home/test/Desktop/rocksdb# ./db_bench --spdk=/usr/local/etc/spdk/rocksdb.conf --spdk_bdev=sdb ^C
root@test-All-Series:/home/test/Desktop/rocksdb# ./db_bench --spdk=/usr/local/etc/spdk/rocksdb.conf --spdk_bdev=AIO0  
Starting SPDK v19.01 / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: rocksdb --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid29195 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
using bdev AIO0
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
RocksDB:    version 5.6
Date:       Tue May 28 10:14:16 2019
CPU:        4 * Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz
CPUCache:   6144 KB
Keys:       16 bytes each
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
Write rate: 0 bytes/second
Read rate: 0 ops/second
Compression: Snappy
Memtablerep: skip_list
Perf Level: 1
------------------------------------------------
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
DB path: [/tmp/rocksdbtest-0/dbbench]
fillseq      :       0.760 micros/op 1315625 ops/sec;  145.5 MB/s
Please disable_auto_compactions in FillDeterministic benchmark
root@test-All-Series:/home/test/Desktop/rocksdb# ./db_bench --spdk=/usr/local/etc/spdk/rocksdb.conf --spdk_bdev=AIO0  
Starting SPDK v19.01 / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: rocksdb --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid29265 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
using bdev AIO0
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
Received signal 11 (Segmentation fault)
Segmentation fault (core dumped)
root@test-All-Series:/home/test/Desktop/rocksdb# git branch -v
  master      3c30815 Add SPDK BlobFS integration.
* spdk-v5.6.1 3c30815 Add SPDK BlobFS integration.

```

**Comment by changpe1** [comment]
@virgilshi Thanks for the update, can you add the call trace here for the segment fault issue ?

**Comment by virgilshi** [comment]
Thank you for your help, I'll try it now.

**Comment by virgilshi** [comment]
@changpe1 hi,
The call trace is below.
```bash
root@test-All-Series:/home/test/Desktop/rocksdb# gdb db_bench
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from db_bench...done.
(gdb) run --spdk=/usr/local/etc/spdk/rocksdb.conf --spdk_bdev=AIO0
Starting program: /home/test/Desktop/rocksdb/db_bench --spdk=/usr/local/etc/spdk/rocksdb.conf --spdk_bdev=AIO0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5ef0700 (LWP 13008)]
Starting SPDK v19.01 / DPDK 19.02.0 initialization...
[ DPDK EAL parameters: rocksdb --no-shconf -c 0x1 --base-virtaddr=0x200000000000 --file-prefix=spdk_pid13004 ]
EAL: Detected 4 lcore(s)
EAL: Detected 1 NUMA nodes
[New Thread 0x7ffff56ef700 (LWP 13009)]
EAL: No free hugepages reported in hugepages-1048576kB
EAL: Probing VFIO support...
app.c: 625:spdk_app_start: *NOTICE*: Total cores available: 1
reactor.c: 298:_spdk_reactor_run: *NOTICE*: Reactor started on core 0
using bdev AIO0
[New Thread 0x7ffff48ea700 (LWP 13010)]
[New Thread 0x7fffe7edd700 (LWP 13011)]
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
[New Thread 0x7fffe76dc700 (LWP 13012)]
[New Thread 0x7fffe6edb700 (LWP 13013)]
[New Thread 0x7fffe66da700 (LWP 13014)]
[Thread 0x7fffe66da700 (LWP 13014) exited]

Thread 6 "spdk_rocksdb" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe76dc700 (LWP 13012)]
alloc_fs_request (channel=channel@entry=0x30) at blobfs.c:262
262		if (channel->sync) {
(gdb) where
#0  alloc_fs_request (channel=channel@entry=0x30) at blobfs.c:262
#1  0x00000000007d48a6 in spdk_fs_open_file (fs=0x7ffff00060f0, _channel=0x0, name=name@entry=0x7fffdc000960 "/tmp/rocksdbtest-0/dbbench/000010.sst", 
    flags=flags@entry=0, file=file@entry=0x7fffe76db6c8) at blobfs.c:1160
#2  0x000000000063b0be in rocksdb::SpdkEnv::NewRandomAccessFile (this=<optimized out>, fname=..., result=0x7fffe76db790, options=...)
    at /home/test/Desktop/spdk/lib/rocksdb/env_spdk.cc:409
#3  0x00000000005e9689 in rocksdb::TableCache::GetTableReader (this=this@entry=0xe1a260, env_options=..., internal_comparator=..., fd=..., 
    sequential_mode=sequential_mode@entry=false, readahead=0, record_read_stats=true, file_read_hist=0xe1a820, table_reader=0x7fffe76db8e0, 
    skip_filters=false, level=0, prefetch_index_and_filter_in_cache=false) at db/table_cache.cc:96
#4  0x00000000005e9ea5 in rocksdb::TableCache::FindTable (this=0xe1a260, env_options=..., internal_comparator=..., fd=..., 
    handle=handle@entry=0xe26f18, no_io=false, record_read_stats=true, file_read_hist=0xe1a820, skip_filters=false, level=0, 
    prefetch_index_and_filter_in_cache=false) at db/table_cache.cc:148
#5  0x00000000005f11e8 in rocksdb::VersionBuilder::Rep::LoadTableHandlers(rocksdb::InternalStats*, int, bool)::{lambda()#1}::operator()() const (
    __closure=0xe26de0) at db/version_builder.cc:351
#6  std::_Function_handler<void (), rocksdb::VersionBuilder::Rep::LoadTableHandlers(rocksdb::InternalStats*, int, bool)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/5/functional:1871
#7  0x00007ffff6892c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7bc16ba in start_thread (arg=0x7fffe76dc700) at pthread_create.c:333
#9  0x00007ffff5ff841d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) list
257	static struct spdk_fs_request *
258	alloc_fs_request(struct spdk_fs_channel *channel)
259	{
260		struct spdk_fs_request *req;
261	
262		if (channel->sync) {
263			pthread_spin_lock(&channel->lock);
264		}
265	
266		req = TAILQ_FIRST(&channel->reqs);
(gdb) 

```
### Steps to Reproduce
The step is refered to [website](https://www.gnu.org/software/gcc/bugs/segfault.html).

**Comment by darsto** [comment]
Bug scrub: it could be version incompatibility between rocksdb and spdk. We need to update at least rocksdb docs.

**Comment by virgilshi** [comment]
@darsto , thanks.
Can I close the issue after rocksdb docs has been updated?
And can I ask other question whether the team will plan to develop leveldb via spdk? I am doing this but meet some difficulties. I hope to get your help.

**Comment by jessehui** [comment]
Hi @virgilshi , I think this issue is fixed. Please use SPDK of master branch and rocksdb for spdk-v5.14.3 branch.

**Comment by virgilshi** [comment]
@jessehui , thanks a lot. I'll try it later.

**Comment by changpe1** [comment]
We have update the documentation in spdk.io with spdk-v5.14.3, so I'm going to close this issue for now, you can reopen it if it still exist with spdk-v5.14.3, thanks.
