### ISSUE TITLE
bdevio seg faults with NVMe/TCP bdev

### ISSUE THREAD

**Issue by jimharris** [spdk/spdk#808]
The SPDK bdevio test fails with an NVMe/TCP namespace as a bdev.

This was found during refactoring of the NVMf tests for automated NVMe/TCP testing.

To reproduce:
1) Make sure you're running with a Linux kernel that supports NVMe/TCP.
2) Check out https://review.gerrithub.io/c/spdk/spdk/+/456698
3) Run "test/nvmf/target/bdevio.sh --transport=tcp"

bdevio output:

```
I/O targets:
  Nvme0n1: 131072 blocks of 512 bytes (64 MiB)


     CUnit - A unit testing framework for C - Version 2.1-3
     http://cunit.sourceforge.net/


Suite: bdevio tests on: Nvme0n1
  Test: blockdev write read 4k ...passed
  Test: blockdev write zeroes read 4k ...passed
  Test: blockdev write zeroes read 1m ...nvme_tcp.c: 722:nvme_tcp_qpair_submit_request: *ERROR*: nvme_tcp_req_init() failed
bdev_nvme.c:1859:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
nvme_tcp.c: 722:nvme_tcp_qpair_submit_request: *ERROR*: nvme_tcp_req_init() failed
bdev_nvme.c:1833:bdev_nvme_readv: *ERROR*: readv failed: rc = -1
FAILED
    1. bdevio.c:386  - CU_ASSERT_EQUAL(g_completion_success,true)
    2. bdevio.c:393  - CU_ASSERT_EQUAL(g_completion_success,true)
  Test: blockdev write zeroes read 3m ...nvme_tcp.c: 722:nvme_tcp_qpair_submit_request: *ERROR*: nvme_tcp_req_init() failed
bdev_nvme.c:1859:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
nvme_tcp.c: 722:nvme_tcp_qpair_submit_request: *ERROR*: nvme_tcp_req_init() failed
bdev_nvme.c:1833:bdev_nvme_readv: *ERROR*: readv failed: rc = -1
FAILED
    1. bdevio.c:386  - CU_ASSERT_EQUAL(g_completion_success,true)
    2. bdevio.c:393  - CU_ASSERT_EQUAL(g_completion_success,true)
  Test: blockdev write zeroes read 3.5m ...nvme_tcp.c: 722:nvme_tcp_qpair_submit_request: *ERROR*: nvme_tcp_req_init() failed
bdev_nvme.c:1859:bdev_nvme_writev: *ERROR*: writev failed: rc = -1
nvme_tcp.c: 722:nvme_tcp_qpair_submit_request: *ERROR*: nvme_tcp_req_init() failed
bdev_nvme.c:1833:bdev_nvme_readv: *ERROR*: readv failed: rc = -1
FAILED
    1. bdevio.c:386  - CU_ASSERT_EQUAL(g_completion_success,true)
    2. bdevio.c:393  - CU_ASSERT_EQUAL(g_completion_success,true)
  Test: blockdev reset ...nvme_ctrlr.c: 846:spdk_nvme_ctrlr_reset: *NOTICE*: resetting controller
nvme_tcp.c: 853:nvme_tcp_pdu_ch_handle: *ERROR*: Already received IC_RESP PDU, and we should reject this pdu=0x55d8f2423bf8
nvme_tcp.c:1607:nvme_tcp_qpair_process_completions: *ERROR*: Error polling CQ! (11): Resource temporarily unavailable
tcp.c:1573:spdk_nvmf_tcp_h2c_term_req_dump: *ERROR*: Error info of pdu(0x5591ba67ee30): Invalid PDU Header Field
test/nvmf/target/bdevio.sh: line 28: 14882 Segmentation fault      (core dumped) $rootdir/test/bdev/bdevio/bdevio -c $testdir/bdevperf.conf
```

gdb backtrace from the seg fault:

```
nvme_tcp_qpair_send_h2c_term_req_complete (cb_arg=0x0) at nvme_tcp.c:800
800             tqpair->state = NVME_TCP_QPAIR_STATE_EXITING;
(gdb) bt
#0  nvme_tcp_qpair_send_h2c_term_req_complete (cb_arg=0x0) at nvme_tcp.c:800
#1  0x00005568f1c2a509 in nvme_tcp_qpair_process_send_queue (tqpair=0x5568f38a4f50) at nvme_tcp.c:440
#2  nvme_tcp_qpair_process_completions (qpair=0x5568f38a4f50, max_completions=0) at nvme_tcp.c:1591
#3  0x00005568f1c28475 in nvme_transport_qpair_process_completions (qpair=qpair@entry=0x5568f38a4f50, max_completions=max_completions@entry=0) at nvme_transport.c:228
#4  0x00005568f1c25db5 in spdk_nvme_qpair_process_completions (qpair=qpair@entry=0x5568f38a4f50, max_completions=max_completions@entry=0) at nvme_qpair.c:451
#5  0x00005568f1c264ca in spdk_nvme_wait_for_completion_robust_lock (qpair=qpair@entry=0x5568f38a4f50, status=status@entry=0x7f690381e780, robust_mutex=robust_mutex@entry=0x0) at nvme.c:125
#6  0x00005568f1c264f7 in spdk_nvme_wait_for_completion (qpair=qpair@entry=0x5568f38a4f50, status=status@entry=0x7f690381e780) at nvme.c:139
#7  0x00005568f1c1e4ec in nvme_fabric_qpair_connect (qpair=qpair@entry=0x5568f38a4f50, num_entries=<optimized out>) at nvme_fabric.c:326
#8  0x00005568f1c2b82c in nvme_tcp_qpair_connect (tqpair=0x5568f38a4f50) at nvme_tcp.c:1722
#9  0x00005568f1c2bb98 in nvme_tcp_ctrlr_connect_qpair (ctrlr=<optimized out>, qpair=<optimized out>) at nvme_tcp.c:1734
#10 0x00005568f1c282f5 in nvme_transport_ctrlr_connect_qpair (ctrlr=ctrlr@entry=0x5568f38a36e0, qpair=<optimized out>) at nvme_transport.c:188
#11 0x00005568f1c1d330 in spdk_nvme_ctrlr_reset (ctrlr=ctrlr@entry=0x5568f38a36e0) at nvme_ctrlr.c:866
#12 0x00005568f1c122c8 in _bdev_nvme_reset (i=<optimized out>, status=0) at bdev_nvme.c:307
#13 0x00005568f1c5d9b2 in _call_completion (ctx=0x7f68ec01b4d0) at thread.c:1177
#14 0x00005568f1c5e147 in _spdk_msg_queue_run_batch (max_msgs=<optimized out>, thread=0x5568f38a61f0) at thread.c:415
#15 spdk_thread_poll (thread=thread@entry=0x5568f38a61f0, max_msgs=max_msgs@entry=0, now=now@entry=16756716784310) at thread.c:471
#16 0x00005568f1c5a153 in _spdk_reactor_run (arg=0x5568f38a5ac0) at reactor.c:272
#17 0x00005568f1c76e7d in eal_thread_loop ()
#18 0x00007f690538e6da in start_thread (arg=0x7f690381f700) at pthread_create.c:456
#19 0x00007f69050c8d7f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
```

**Comment by optimistyzy** [comment]
@jimharris  I pushed the following patch,  https://review.gerrithub.io/c/spdk/spdk/+/456755.   
But this path is based on  a very small patch(https://review.gerrithub.io/c/spdk/spdk/+/455899). It can solve the coredump issue, and I tested, it works well. For the very big I/O,  Need another patch.

**Comment by optimistyzy** [comment]
@jimharris  https://review.gerrithub.io/c/spdk/spdk/+/456760 This patch with one line can solve the wrong calculation of the io length.  With the patch series, we can fix the issue you reported in the bdevio.

**Comment by jimharris** [comment]
FYI - the patch series mentioned above has all been merged.  So this issue can be reproduce now by just running "test/nvmf/target/bdevio.sh --transport=tcp" with latest master.
