### ISSUE TITLE
test/nvme/reset endlessly print "sq_tail is passing sq_head"

### ISSUE THREAD

**Issue by glodfish-zg** [spdk/spdk#819]
run test/NVMe/reset and get the endless print 
nvme_pcie.c:1263:nvme_pcie_qpair_submit_tracker: *ERROR*: sq_tail is passing sq_head!

## Expected Behavior
run correctly without error message

## Current Behavior
endlessly print
nvme_pcie.c:1263:nvme_pcie_qpair_submit_tracker: *ERROR*: sq_tail is passing sq_head!

## Steps to Reproduce
1. test/nvme/reset/reset -q 128 -s 4096 -w read -t 60
2.
3.
4.

## Context (Environment including OS version, SPDK version, etc.)
spdk commit: fc3e1b6fb0b92f91b3f0cd1ce78e3351e7d8003d 

GDB：
(gdb) bt
#0  nvme_pcie_qpair_submit_tracker (qpair=0x200001993b18, tr=0x2000021ee000) at nvme_pcie.c:1263
#1  0x00000000004333b9 in nvme_pcie_qpair_submit_request (qpair=0x200001993b18, req=0x200001a5e840)
    at nvme_pcie.c:1986
#2  0x000000000043eb6a in nvme_transport_qpair_submit_request (qpair=0x200001993b18, req=0x200001a5e840)
    at nvme_transport.c:222
#3  0x000000000043734d in nvme_qpair_submit_request (qpair=0x200001993b18, req=0x200001a5e840)
    at nvme_qpair.c:603
#4  0x00000000004231d3 in spdk_nvme_ns_cmd_read (ns=0x20000199bf40, qpair=0x200001993b18,
    buffer=0x200001a32400, lba=2192, lba_count=8, cb_fn=0x405e5b <io_complete>, cb_arg=0x200001a620c0,
    io_flags=0) at nvme_ns_cmd.c:612
#5  0x0000000000405abf in submit_single_io (ns_ctx=0x607000000250) at reset.c:194
#6  0x0000000000405e58 in task_complete (task=0x200001a620c0, completion=0x7fffffffddf0) at reset.c:234
#7  0x0000000000405e7e in io_complete (ctx=0x200001a620c0, completion=0x7fffffffddf0) at reset.c:241
#8  0x0000000000428173 in nvme_complete_request (cb_fn=0x405e5b <io_complete>, cb_arg=0x200001a620c0,
    qpair=0x200001993b18, req=0x200001a5e700, cpl=0x7fffffffddf0) at nvme_internal.h:949
#9  0x000000000042f002 in nvme_pcie_qpair_complete_tracker (qpair=0x200001993b18, tr=0x2000021ed000,
    cpl=0x7fffffffddf0, print_on_error=true) at nvme_pcie.c:1304
#10 0x000000000042f67a in nvme_pcie_qpair_manual_complete_tracker (qpair=0x200001993b18, tr=0x2000021ed000,
    sct=0, sc=7, dnr=0, print_on_error=true) at nvme_pcie.c:1343
#11 0x000000000042f7be in nvme_pcie_qpair_abort_trackers (qpair=0x200001993b18, dnr=0) at nvme_pcie.c:1356
#12 0x000000000042fb61 in nvme_pcie_qpair_abort_reqs (qpair=0x200001993b18, dnr=0) at nvme_pcie.c:1415
#13 0x000000000043e97c in nvme_transport_qpair_abort_reqs (qpair=0x200001993b18, dnr=0)
    at nvme_transport.c:210
#14 0x0000000000435c9e in nvme_qpair_check_enabled (qpair=0x200001993b18) at nvme_qpair.c:413
#15 0x0000000000435d89 in spdk_nvme_qpair_process_completions (qpair=0x200001993b18, max_completions=0)
    at nvme_qpair.c:430
#16 0x0000000000405ec8 in check_io (ns_ctx=0x607000000250) at reset.c:247
#17 0x00000000004061f5 in work_fn (arg=0x6020000053b0) at reset.c:297
#18 0x000000000040720b in run_nvme_reset_cycle (retry_count=2) at reset.c:620
#19 0x000000000040771f in main (argc=9, argv=0x7fffffffe1a8) at reset.c:703

**Comment by glodfish-zg** [comment]
pushed a patch to fix this issue.

**Comment by glodfish-zg** [comment]
https://review.gerrithub.io/c/spdk/spdk/+/457755
