### ISSUE TITLE
[CI] TCP transport coredumps during NVMF shutdown.sh tests.

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#872]
## Expected Behavior
The TCP transport should be able to pass the shutdown.sh test without any issues.

## Current Behavior
The TCP transport fails consistently on the following assert in the NVMe-oF TCP shutdown test:

nvmf_tgt: tcp.c:2489: spdk_nvmf_tcp_req_process: Assertion `tcp_req->state != TCP_REQUEST_STATE_FREE' failed.

This may be a serious problem because the request that is hitting the assert has just been pulled from the pending data buffer list. All of the requests in this queue should be in the TCP_REQUEST_STATE_NEED_BUFFER state.  This makes me think there could be some sort of data corruption going on.This is evidenced in the core dump below.

~~~
#0  0x00007f28941b3eab in raise () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f289419e5b9 in abort () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f289419e491 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f28941ac612 in __assert_fail () from /lib64/libc.so.6
No symbol table info available.
#4  0x000000000069af76 in spdk_nvmf_tcp_req_process (ttransport=0x2f1cfd0, tcp_req=0x7f287c01eb70) at tcp.c:2489
        tqpair = 0x2f749f0
        rsp = 0x7f287c01edd8
        rc = 0
        prev_state = TCP_REQUEST_STATE_FREE
        progress = false
        group = 0x7f287c010f00
        __PRETTY_FUNCTION__ = "spdk_nvmf_tcp_req_process"
        __func__ = "spdk_nvmf_tcp_req_process"
#5  0x000000000069d187 in spdk_nvmf_tcp_qpair_process_pending (ttransport=0x2f1cfd0, tqpair=0x2f749f0) at tcp.c:2658
        tcp_req = 0x7f287c01eb70
        req_tmp = 0x7f287c01ef28
#6  0x0000000000687f3e in spdk_nvmf_tcp_qpair_flush_pdus_internal (tqpair=0x2f749f0) at tcp.c:854
        array_size = 32
        iovs = {{iov_base = 0x7f287c013770, iov_len = 24}, {iov_base = 0x7f287c013560, iov_len = 24}, {iov_base = 0x2f26f40, iov_len = 44171264}, {iov_base = 0x7f2891c4db10, iov_len = 4800899}, {iov_base = 0x2a20000, iov_len = 139811991029952}, {iov_base = 0x7f2891c4dab0, iov_len = 36573192192}, {iov_base = 0x2000078df440, iov_len = 139811855864368}, {iov_base = 0x80, iov_len = 2199023255553}, {iov_base = 0x2000078df440, iov_len = 32}, {iov_base = 0xc091c40000, iov_len = 11299392}, {iov_base = 0x80, iov_len = 8}, {iov_base = 0x0, iov_len = 32}, {iov_base = 0x7f2891c4db30, iov_len = 4804092}, {iov_base = 0x2000078df440, iov_len = 139811855864368}, {iov_base = 0x7f2891c4db80, iov_len = 7404417}, {iov_base = 0x2000078df440, iov_len = 139811855871008}, {iov_base = 0xc091c40000, iov_len = 49442624}, {iov_base = 0x7f287c011230, iov_len = 139811855864656}, {iov_base = 0x80, iov_len = 139811855871008}, {iov_base = 0x7f2891c4dbe0, iov_len = 7419285}, {iov_base = 0x209900002098, iov_len = 4421710912}, {iov_base = 0x7f2891c4dd00, iov_len = 35184729120576}, {iov_base = 0x2f26f40, iov_len = 3794536573984}, {iov_base = 0x7f287c011350, iov_len = 14800724518977}, {iov_base = 0x7f287c012c20, iov_len = 128}, {iov_base = 0x7f2891c4dc20, iov_len = 7423594}, {iov_base = 0x107300000, iov_len = 139812221017012}, {iov_base = 0x7f2891c4dbb8, iov_len = 139812221017020}, {iov_base = 0x2f26f40, iov_len = 0}, {iov_base = 0x20001547cc80, iov_len = 0}, {iov_base = 0x15100, iov_len = 0}, {iov_base = 0x7f2891c4dd00, iov_len = 35184729115776}}
        iovcnt = 1
        bytes = 0
        total_length = 24
        mapped_length = 24
        pdu = 0x7f287c013770
        pdu_length = 24
        completed_pdus_list = {tqh_first = 0x0, tqh_last = 0x7f2891c4dcb0}
        ttransport = 0x2f1cfd0
        __func__ = "spdk_nvmf_tcp_qpair_flush_pdus_internal"
        __PRETTY_FUNCTION__ = "spdk_nvmf_tcp_qpair_flush_pdus_internal"
~~~

I was able to gain some more information from testing locally. It looks like this assert is being hit before the qpair is freed, so this is not an incidence of the qpair being freed on the wrong thread.
I also confirmed that this is not a case of spdk_nvmf_tcp_req_free being called on the wrong thread to destroy quiesced I/O. These were the two main theories I had for why this failure would occur.

## Possible Solution
Ziye has a patch out that removes one of the calls to nvmf_tcp_qpair_process_pending because it has the potential to cause a very deep recursion chain. However his patch currently cannot pass the shutdown test either.

## Steps to Reproduce
This produces consistently on the test pool. It is more difficult to produce locally, but I have been able to do so inconsistently with the following command.

~~~
./test/nvmf/target/shutdown.sh --iso --transport=tcp
~~~

## Context (Environment including OS version, SPDK version, etc.)
The machines in the build pool are running kernel version 5.0.16 on fedora 28.

**Comment by Seth5141** [comment]
This was fixed by Ziye's patch https://review.gerrithub.io/c/spdk/spdk/+/462658. My bad for not closing it earlier.
