### ISSUE TITLE
Vhost target heap-buffer-overflow after fuzz testing

### ISSUE THREAD

**Issue by Seth5141** [spdk/spdk#873]
## Current Behavior
I encountered the following vhost target core dump when inspecting logs from the autofuzz jobs on Jenkins.

~~~
==786641==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x619000001d80 at pc 0x00000072a494 bp 0x7ffc9dff1d70 sp 0x7ffc9dff1d60
READ of size 1 at 0x619000001d80 thread T0 (reactor_0)
    #0 0x72a493 in bdev_scsi_mode_select_page /var/jenkins/workspace/Fuzz_Tests/autofuzz_vhost_all/spdk/lib/scsi/scsi_bdev.c:1180
    #1 0x72a790 in bdev_scsi_mode_select_page /var/jenkins/workspace/Fuzz_Tests/autofuzz_vhost_all/spdk/lib/scsi/scsi_bdev.c:1248
    #2 0x72a790 in bdev_scsi_mode_select_page /var/jenkins/workspace/Fuzz_Tests/autofuzz_vhost_all/spdk/lib/scsi/scsi_bdev.c:1248
    #3 0x72a790 in bdev_scsi_mode_select_page /var/jenkins/workspace/Fuzz_Tests/autofuzz_vhost_all/spdk/lib/scsi/scsi_bdev.c:1248
(repeats 250 times)
~~~

## Possible Solution
Not sure yet.

## Steps to Reproduce
~~~
spdk/test/fuzz/autofuzz.sh --module=vhost ==transport=all
~~~

## Context (Environment including OS version, SPDK version, etc.)
The test ran inside of a Qemu virtual machine running fedora 28 with kernel version 1.18.18-200 and 1 GiB hugepages configured.

**Comment by jimharris** [comment]
Closing for now - this needs some more analysis first.
